-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 010 — Módulo 1: Fundamentos del modelo de datos
-- ═══════════════════════════════════════════════════════════════════
-- Contenido completo del módulo: 11 lecciones + examen de región.
-- Dataset del curso: hospital (PACIENTE, EXPEDIENTE, MEDICO,
-- ESPECIALIDAD, CITA, ESTUDIO_LAB).
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 002 y 003.
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm01-modelo-de-datos'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m01-l01-modelo-de-datos',            '¿Qué es un modelo de datos?',            'leccion', 20, 1),
       ('m01-l02-entidades-y-atributos',      'Entidades y atributos',                  'leccion', 20, 2),
       ('m01-l03-relationship-vs-relation',   'Relación: relationship vs relation',     'leccion', 20, 3),
       ('m01-l04-anatomia-de-la-tabla',       'La anatomía de una tabla',               'leccion', 20, 4),
       ('m01-l05-modelo-er-y-notaciones',     'El modelo ER y sus notaciones',          'leccion', 20, 5),
       ('m01-l06-cardinalidad-1-1',           'Cardinalidad 1:1',                       'leccion', 20, 6),
       ('m01-l07-cardinalidad-1-n',           'Cardinalidad 1:N',                       'leccion', 20, 7),
       ('m01-l08-cardinalidad-n-m',           'Cardinalidad N:M',                       'leccion', 20, 8),
       ('m01-l09-participacion-y-opcionalidad','Participación y opcionalidad',          'leccion', 20, 9),
       ('m01-l10-llaves-candidatas-y-pk',     'Llaves candidatas y primary key',        'leccion', 20, 10),
       ('m01-l11-er-hospital',                'El modelo ER del hospital',              'leccion', 20, 11),
       ('m01-x01-examen',                     'Examen: Fundamentos del modelo de datos','examen',  40, 12)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm01-modelo-de-datos';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · ¿Qué es un modelo de datos?
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"El plano antes del edificio","body":"Un modelo de datos es la forma en que decides organizar, estructurar y relacionar la información antes de escribir una sola línea de código. Piensa en un hospital: pacientes, médicos, citas, estudios de laboratorio. ¿Cada cita guarda el nombre completo del paciente, o solo una referencia a él? ¿Qué pasa si la paciente cambia de teléfono? Un buen modelo responde estas preguntas UNA vez, y todo el sistema hereda esa claridad. Un mal modelo multiplica errores: datos duplicados, inconsistencias y consultas imposibles."}$j$),
  (2, 'texto', $j${"title":"Cuatro formas de organizar los mismos datos","body":"La historia de las bases de datos es la historia de cuatro modelos. El jerárquico (años 60, IBM IMS) organiza todo como un árbol. El de red (CODASYL, años 70) permite varios padres usando punteros. El relacional (E. F. Codd, 1970) organiza todo en tablas conectadas por llaves — es el modelo de Oracle. El documental (años 2010, MongoDB) guarda documentos JSON autocontenidos. En una entrevista es oro saber POR QUÉ ganó el relacional: consultas declarativas con SQL, independencia entre cómo se guardan los datos y cómo se consultan, e integridad garantizada por el motor."}$j$),
  (3, 'diagrama', $j${"title":"Los mismos datos del hospital, en cada modelo","component":"DataModelsComparison","props":{"inicial":"jerarquico"},"caption":"Cambia de pestaña y observa dónde se duplica la Dra. Reyes y dónde no. Esa diferencia definió 50 años de bases de datos."}$j$),
  (4, 'ejemplo_sql', $j${"title":"Así se ve el modelo relacional en Oracle","code":"SELECT paciente_id, nombre\nFROM paciente;","result":{"columns":["PACIENTE_ID","NOMBRE"],"rows":[["1","Ana Torres"],["2","Luis Vega"],["3","Marta Solís"]]},"caption":"Una tabla: filas y columnas. No importa cómo Oracle guarde esto físicamente en disco — tú lo consultas igual. Eso es independencia física, la gran idea de Codd."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un modelo de datos?","options":["El diagrama de clases de la aplicación","La forma de estructurar y relacionar la información, independiente de la aplicación","El servidor donde se guardan los datos","Un tipo de archivo de Oracle"],"correctIndex":1,"feedback":{"correct":"Exacto. El modelo define estructura y relaciones de los datos, antes e independientemente del código.","incorrect":"El modelo de datos no es hardware ni código: es la forma de estructurar y relacionar la información."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En el modelo jerárquico, la Dra. Reyes aparecía duplicada bajo cada cita. ¿Por qué?","options":["Porque el árbol solo permite UN padre por registro","Porque era más rápido duplicarla","Porque las médicas no podían ser registros raíz","Porque IMS no soportaba texto"],"correctIndex":0,"feedback":{"correct":"Correcto. Si cada registro tiene un solo padre, un dato compartido por dos ramas debe copiarse en ambas.","incorrect":"La limitación del modelo jerárquico es estructural: un solo padre por registro obliga a duplicar los datos compartidos."}}$j$),
  (7, 'quiz', $j${"variant":"fill_blank","prompt":"Oracle Database implementa el modelo ___.","options":["jerárquico","de red","relacional","documental"],"correctIndex":2,"feedback":{"correct":"Correcto. Oracle es un motor relacional: tablas, llaves y SQL.","incorrect":"Oracle organiza los datos en tablas conectadas por llaves: eso es el modelo relacional."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: ¿cuál fue la ventaja decisiva del modelo relacional sobre el jerárquico y el de red?","options":["Usaba menos espacio en disco","Consultas declarativas (SQL) sin conocer la estructura física de almacenamiento","Era el único que corría en mainframes","No necesitaba administradores"],"correctIndex":1,"feedback":{"correct":"Exacto. Con SQL declaras QUÉ quieres, no CÓMO recorrer punteros o árboles. El motor decide el camino.","incorrect":"La clave fue la independencia: SQL declara qué datos quieres sin importar cómo se almacenan ni navegando punteros."}}$j$),
  (9, 'resumen', $j${"title":"Resumen — Modelo de datos","points":["Un modelo de datos define cómo se estructura y relaciona la información, antes que el código.","Cuatro modelos históricos: jerárquico (árbol), de red (punteros), relacional (tablas) y documental (JSON).","El jerárquico y el de red obligaban a duplicar datos o a navegar estructuras físicas.","El relacional (Codd, 1970) ganó por sus consultas declarativas y su independencia física.","Oracle Database es un motor relacional: será nuestro modelo el resto del curso."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l01-modelo-de-datos';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Entidades y atributos
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"Entidad: lo que existe y quieres registrar","body":"Una entidad es un objeto del mundo real, con existencia propia, del que necesitas guardar información. Son los sustantivos de tu dominio: en el hospital, PACIENTE, MEDICO, CITA, ESTUDIO_LAB. Distingue dos niveles: el TIPO de entidad (PACIENTE, la plantilla) y la INSTANCIA u ocurrencia (Ana Torres, un paciente concreto). Cuando diseñas un modelo trabajas con tipos; cuando la base de datos vive, se llena de instancias."}$j$),
  (2, 'texto', $j${"title":"Atributos: lo que describes de cada entidad","body":"Un atributo es una propiedad que describe a la entidad: PACIENTE tiene nombre, dni, fecha_nacimiento, teléfono. Clasificaciones que aparecen en entrevistas: simple (dni) vs compuesto (dirección = calle + ciudad + código postal); monovaluado (fecha_nacimiento, una sola) vs multivaluado (teléfonos: puede tener varios — se resolverá con otra tabla); y almacenado vs DERIVADO. La edad es el ejemplo clásico de atributo derivado: nunca se guarda, se calcula desde fecha_nacimiento. Guardarla sería sembrar un dato que caduca cada cumpleaños."}$j$),
  (3, 'ejemplo_sql', $j${"title":"Atributos almacenados y derivados en Oracle","code":"SELECT nombre,\n       fecha_nacimiento,\n       TRUNC(MONTHS_BETWEEN(SYSDATE, fecha_nacimiento) / 12) AS edad\nFROM paciente;","result":{"columns":["NOMBRE","FECHA_NACIMIENTO","EDAD"],"rows":[["Ana Torres","14/02/1991","35"],["Luis Vega","30/07/1978","47"],["Marta Solís","09/11/2002","23"]]},"caption":"fecha_nacimiento es un atributo almacenado; edad es derivado: Oracle lo calcula al vuelo con MONTHS_BETWEEN y SYSDATE (las verás a fondo en el módulo 5)."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En el modelo del hospital, ¿cuál de estos es un TIPO de entidad?","options":["fecha_nacimiento","MEDICO","el valor O+","la edad de Ana"],"correctIndex":1,"feedback":{"correct":"Correcto. MEDICO es una entidad; fecha_nacimiento es un atributo y O+ es un valor.","incorrect":"MEDICO es la entidad (un objeto con existencia propia). Lo demás son atributos o valores de atributos."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué la edad se modela como atributo derivado y no se guarda?","options":["Porque ocupa demasiado espacio","Porque quedaría desactualizada: cambia sola con el tiempo","Porque Oracle no permite guardar números pequeños","Porque es un dato sensible"],"correctIndex":1,"feedback":{"correct":"Exacto. Un dato que puedes calcular y que caduca solo (cada cumpleaños) se deriva, no se almacena.","incorrect":"El problema es la desactualización: la edad cambia sola. Se calcula desde fecha_nacimiento cuando se necesita."}}$j$),
  (6, 'quiz', $j${"variant":"table_reading","table":"PACIENTE\n---------------------------------------\npaciente_id | nombre       | dni\n---------------------------------------\n1           | Ana Torres   | 44210987\n2           | Luis Vega    | 38765401\n3           | Marta Solís  | 51002344","prompt":"¿Cuántas INSTANCIAS de la entidad PACIENTE muestra esta tabla?","options":["Una","Tres","Nueve","Ninguna: son atributos"],"correctIndex":1,"feedback":{"correct":"Correcto. Cada fila es una instancia: Ana, Luis y Marta. Las columnas son los atributos.","incorrect":"Cada fila es una instancia de PACIENTE. Hay tres filas, por lo tanto tres instancias."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Un paciente puede tener varios teléfonos de contacto. ¿Qué tipo de atributo es teléfono?","options":["Derivado","Compuesto","Multivaluado","Simple"],"correctIndex":2,"feedback":{"correct":"Correcto. Varios valores del mismo atributo = multivaluado. En el modelo relacional se resuelve con una tabla aparte.","incorrect":"Si un atributo puede tener VARIOS valores a la vez (varios teléfonos), es multivaluado."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Entidades y atributos","points":["Entidad: objeto del mundo real que registras (PACIENTE, MEDICO, CITA).","Tipo de entidad = la plantilla; instancia = un caso concreto (Ana Torres).","Atributo: propiedad que describe a la entidad (nombre, dni, fecha_nacimiento).","Clasificaciones clave: simple/compuesto, monovaluado/multivaluado, almacenado/derivado.","La edad nunca se guarda: se deriva de fecha_nacimiento (en Oracle, con MONTHS_BETWEEN y SYSDATE)."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l02-entidades-y-atributos';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Relación: relationship vs relation
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"Las entidades no viven solas","body":"Un modelo con entidades sueltas no dice nada. El valor está en las asociaciones: un PACIENTE agenda una CITA, un MEDICO atiende una CITA, una CITA genera un ESTUDIO_LAB. En el modelo entidad-relación, estas asociaciones se llaman relationships y se nombran con un VERBO. Cuando leas o presentes un modelo, léelo como frases: cada médico ATIENDE cero o muchas citas."}$j$),
  (2, 'texto', $j${"title":"La trampa de la palabra relación","body":"Aquí cae medio mundo en las entrevistas. En inglés existen DOS términos que en español se traducen igual: RELATIONSHIP es la asociación entre entidades del modelo ER (paciente agenda cita). RELATION es un término formal del modelo relacional y significa... ¡TABLA! Por eso las bases de datos se llaman relacionales: por estar hechas de relations (tablas), NO por tener relaciones entre tablas. Si en una entrevista te preguntan qué es una relación en el modelo relacional, la respuesta es: una tabla."}$j$),
  (3, 'texto', $j${"title":"Grado de una relación (relationship)","body":"El grado indica cuántas entidades participan en la asociación. Binaria: dos entidades — la más común (MEDICO atiende CITA). Unaria o recursiva: la entidad se asocia consigo misma (un MEDICO supervisa a otros MEDICOS: jefa de servicio y residentes). Ternaria: tres entidades a la vez (poco frecuente; suele descomponerse en binarias). Reconocer una relación recursiva es pregunta habitual de entrevista."}$j$),
  (4, 'ejemplo_sql', $j${"title":"Un relationship hecho datos","code":"SELECT cita_id, paciente_id, medico_id\nFROM cita;","result":{"columns":["CITA_ID","PACIENTE_ID","MEDICO_ID"],"rows":[["501","1","9"],["502","1","9"],["503","2","10"],["504","3","9"]]},"caption":"Las columnas paciente_id y medico_id son el relationship convertido en datos: cada fila de CITA apunta al paciente que la agendó y al médico que la atiende. Formalmente son foreign keys (módulo 2)."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En el modelo relacional formal, ¿qué es una relation?","options":["Una foreign key","Una asociación entre dos tablas","Una tabla","Un JOIN"],"correctIndex":2,"feedback":{"correct":"Correcto. Relation = tabla. De ahí viene el nombre modelo relacional.","incorrect":"Relation significa tabla. La asociación entre entidades es relationship. Esta confusión es clásica de entrevista."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Un MEDICO supervisa a otros MEDICOS. ¿Qué tipo de relación es?","options":["Binaria","Ternaria","Recursiva (unaria)","No puede modelarse"],"correctIndex":2,"feedback":{"correct":"Correcto. La entidad se asocia consigo misma: relación recursiva o unaria.","incorrect":"Cuando la entidad se asocia consigo misma (médico supervisa médico) la relación es recursiva o unaria."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: ¿por qué las bases de datos relacionales se llaman así?","options":["Porque tienen relaciones (foreign keys) entre tablas","Porque relation es el término formal de Codd para tabla","Porque relacionan aplicaciones entre sí","Por el nombre de la empresa que las inventó"],"correctIndex":1,"feedback":{"correct":"Exacto. Vienen de relation = tabla en el álgebra relacional de Codd. Las FKs son consecuencia, no origen del nombre.","incorrect":"El nombre viene de relation (tabla) en la teoría de Codd, no de las asociaciones entre tablas."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Relaciones","points":["Relationship: asociación entre entidades, nombrada con un verbo (PACIENTE agenda CITA).","Relation: término formal para TABLA en el modelo relacional. No las confundas.","Base de datos relacional viene de relation = tabla (Codd), no de tener FKs.","Grados: binaria (dos entidades), recursiva (consigo misma), ternaria (tres).","En los datos, un relationship se materializa como columnas que referencian a otra tabla."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l03-relationship-vs-relation';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · La anatomía de una tabla
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"Dos vocabularios, una misma cosa","body":"El modelo relacional tiene un vocabulario formal (el de Codd, el de los libros y el de las entrevistas) y uno práctico (el del día a día con Oracle). Son la MISMA cosa con dos nombres: relación = tabla, tupla = fila, atributo = columna. A ellos se suman tres medidas: el dominio (qué valores puede tomar un atributo), el grado (cuántos atributos tiene la relación) y la cardinalidad (cuántas tuplas tiene). Quien maneja ambos vocabularios entiende cualquier libro, cualquier documentación y a cualquier entrevistador. Vamos a diseccionar una tabla real del hospital para fijarlos de una vez."}$j$),
  (2, 'diagrama', $j${"title":"Anatomía de la tabla PACIENTE","component":"TableAnatomyDiagram","props":{"nombre":"PACIENTE","columnas":[{"nombre":"paciente_id","pk":true,"dominio":"enteros positivos y únicos: 1, 2, 3, …"},{"nombre":"nombre","dominio":"texto de hasta 100 caracteres."},{"nombre":"grupo_sanguineo","dominio":"exactamente 8 valores posibles: O-, O+, A-, A+, B-, B+, AB- y AB+."},{"nombre":"fecha_nacimiento","dominio":"fechas válidas, nunca futuras."}],"filas":[["1","Ana Torres","O+","14/02/1991"],["2","Luis Vega","A-","03/09/1988"],["3","Marta Solís","B+","27/06/1995"]],"destacarDominio":"grupo_sanguineo","tuplaEjemplo":0},"caption":"Toca cada término (o cada zona de la tabla) y lee su definición formal y su equivalente práctico. Todos caen en entrevistas."}$j$),
  (3, 'texto', $j${"title":"La trampa de la palabra cardinalidad","body":"Dominio: grupo_sanguineo solo admite 8 valores; cualquier otro (¿C+?) es un error que la base debe rechazar. Grado: PACIENTE tiene 4 atributos, es una relación de grado 4 — y no cambia al insertar o borrar filas, porque es parte de la estructura. Cardinalidad: hoy PACIENTE tiene 3 tuplas; mañana pueden ser miles. Y aquí la trampa clásica de entrevista: cardinalidad DE UNA RELACIÓN (tabla) = número de tuplas; cardinalidad DE UNA RELACIÓN ER (relationship) = 1:1, 1:N o N:M. Misma palabra, dos conceptos distintos. Si un entrevistador la menciona, identifica primero de cuál habla — esa pregunta aclaratoria ya suma puntos."}$j$),
  (4, 'ejemplo_sql', $j${"title":"Grado y cardinalidad, medidos con Oracle","code":"SELECT column_name\nFROM user_tab_columns\nWHERE table_name = 'PACIENTE';","result":{"columns":["COLUMN_NAME"],"rows":[["PACIENTE_ID"],["NOMBRE"],["GRUPO_SANGUINEO"],["FECHA_NACIMIENTO"]],"note":"4 filas en el diccionario = grado 4. Y SELECT COUNT(*) FROM paciente devolvería 3: la cardinalidad actual."},"caption":"user_tab_columns es parte del diccionario de datos de Oracle: vistas donde la base se describe a sí misma. Lo retomaremos en el módulo 9."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En el vocabulario formal, una fila completa de PACIENTE (todos los datos de Ana Torres, por ejemplo) se llama:","options":["Atributo","Dominio","Tupla","Instancia de esquema"],"correctIndex":2,"feedback":{"correct":"Correcto. Tupla = fila = registro: una instancia concreta y completa de la relación.","incorrect":"La fila completa es la tupla. El atributo es la columna y el dominio son sus valores válidos."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Alguien intenta registrar un paciente con grupo sanguíneo 'C+'. ¿Qué concepto del modelo relacional se está violando?","options":["El grado de la relación","El dominio del atributo grupo_sanguineo","La cardinalidad de la tabla","La primary key"],"correctIndex":1,"feedback":{"correct":"Correcto. 'C+' está fuera del conjunto de valores válidos: viola el dominio. En el módulo 4 verás cómo Oracle lo impide con constraints CHECK.","incorrect":"'C+' no existe entre los 8 grupos sanguíneos válidos: el valor cae fuera del DOMINIO del atributo."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Una tabla tiene 5 atributos y 120 tuplas. En términos formales:","options":["Grado 120 y cardinalidad 5","Grado 5 y cardinalidad 120","Dominio 5 y grado 120","Cardinalidad 5 y dominio 120"],"correctIndex":1,"feedback":{"correct":"Correcto. Grado = nº de atributos (columnas); cardinalidad = nº de tuplas (filas).","incorrect":"Grado cuenta columnas (5) y cardinalidad cuenta filas (120). El dominio no es un número: es el conjunto de valores válidos."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: te preguntan por 'la cardinalidad'. ¿Qué conviene distinguir antes de responder?","options":["Si se refieren a filas o a columnas","Si hablan de la cardinalidad de una tabla (nº de tuplas) o de la cardinalidad de una relación ER (1:1, 1:N, N:M)","Si hablan de Oracle o de otro motor","Nada: cardinalidad siempre significa lo mismo"],"correctIndex":1,"feedback":{"correct":"Exacto. Misma palabra, dos conceptos. Hacer esa distinción en voz alta demuestra dominio del tema.","incorrect":"La palabra tiene doble uso: nº de tuplas de una tabla vs tipo de relación ER (1:1, 1:N, N:M). Distinguirlo es la respuesta senior."}}$j$),
  (9, 'resumen', $j${"title":"Resumen — Anatomía de una tabla","points":["Relación = tabla; tupla = fila; atributo = columna. Dos vocabularios, una misma cosa.","El dominio es el conjunto de valores VÁLIDOS de un atributo (grupo_sanguineo: solo 8 valores).","El grado es el número de atributos; es estructura, no cambia con los datos.","La cardinalidad de una tabla es su número de tuplas; cambia con cada INSERT o DELETE.","Ojo de entrevista: cardinalidad de tabla (nº de tuplas) ≠ cardinalidad ER (1:1, 1:N, N:M).","La primary key identifica cada tupla: única y nunca NULL."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l04-anatomia-de-la-tabla';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · El modelo ER y sus notaciones
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"Un idioma para diseñar antes de construir","body":"El modelo entidad-relación (ER) lo propuso Peter Chen en 1976 y sigue siendo EL lenguaje para diseñar bases de datos. Un diagrama ER dibuja las entidades, sus atributos y las relaciones entre ellas, ANTES de crear una sola tabla. Es el plano que se discute con el equipo (¿un paciente puede tener varias citas el mismo día?) cuando cambiar algo todavía cuesta cero. En proyectos reales, el diagrama ER es lo primero que te muestran al llegar y lo primero que te piden dibujar en una entrevista de diseño."}$j$),
  (2, 'texto', $j${"title":"Tres notaciones que debes reconocer","body":"El mismo modelo puede dibujarse con distintas notaciones. Chen: la original académica — entidades en rectángulos, relaciones en rombos, atributos en óvalos. Pata de gallo (crow's foot / IE): la más usada en herramientas modernas; la cardinalidad se dibuja en los extremos de la línea con barras, anillos y las famosas tres puntas. Barker: la notación de Oracle (Oracle Designer y Oracle SQL Developer Data Modeler); usa pata de gallo para el lado muchos, y marca lo OPCIONAL con línea discontinua. En una entrevista pueden mostrarte cualquiera: entrena el ojo con las dos que usarás de verdad."}$j$),
  (3, 'diagrama', $j${"title":"La misma relación, en las dos notaciones","component":"CardinalityDiagram","props":{"tipo":"1:N","verbo":"atiende","izquierda":{"nombre":"MÉDICO","card":"1","min":1,"descripcion":"La entidad del lado uno: cada cita es atendida por exactamente un médico."},"derecha":{"nombre":"CITA","card":"N","min":0,"descripcion":"La entidad del lado muchos: un médico puede tener cero, una o muchas citas."},"lecturas":["Cada MÉDICO atiende cero, una o muchas CITAS.","Cada CITA es atendida por exactamente un MÉDICO."]},"caption":"Usa los botones para alternar entre pata de gallo y Barker. Es exactamente la misma relación: cambia solo cómo se dibuja."}$j$),
  (4, 'ejemplo_sql', $j${"title":"El diagrama, verificado con datos","code":"SELECT cita_id, medico_id\nFROM cita\nORDER BY medico_id;","result":{"columns":["CITA_ID","MEDICO_ID"],"rows":[["501","9"],["502","9"],["504","9"],["503","10"]]},"caption":"El medico_id 9 (Dra. Reyes) se repite en tres filas: ese es el lado muchas del diagrama, visto en los datos reales."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la notación ER asociada a las herramientas de Oracle?","options":["Chen","Barker","UML","Martin extendida"],"correctIndex":1,"feedback":{"correct":"Correcto. Barker es la notación de Oracle Designer y de SQL Developer Data Modeler.","incorrect":"La notación de Oracle es Barker: pata de gallo para muchos y línea discontinua para lo opcional."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En notación pata de gallo, ¿qué significan las tres puntas que tocan una entidad?","options":["Exactamente tres instancias","Participación obligatoria","Muchas instancias de esa entidad","Que la entidad tiene tres atributos"],"correctIndex":2,"feedback":{"correct":"Correcto. La pata de gallo marca el lado muchos de la relación.","incorrect":"Las tres puntas (la pata de gallo) significan muchas: es el símbolo del lado N."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"En notación Barker, ¿cómo se indica que la participación es opcional?","options":["Con un rombo","Con un asterisco","Con la mitad de la línea discontinua","Escribiendo la palabra opcional"],"correctIndex":2,"feedback":{"correct":"Correcto. En Barker, la mitad discontinua de la línea marca el extremo opcional de la relación.","incorrect":"Barker marca lo opcional con trazo discontinuo en la mitad correspondiente de la línea."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Modelo ER y notaciones","points":["El diagrama ER (Chen, 1976) diseña entidades, atributos y relaciones antes de crear tablas.","Notación Chen: rectángulos, rombos y óvalos — la académica.","Notación pata de gallo (IE): la más común en herramientas; tres puntas = muchos.","Notación Barker: la de Oracle; línea discontinua = participación opcional.","El mismo modelo puede dibujarse en cualquier notación: entrena el ojo para leer ambas."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l05-modelo-er-y-notaciones';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Cardinalidad 1:1
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"Cardinalidad: cuántos con cuántos","body":"La cardinalidad de una relación responde una pregunta: ¿cuántas instancias de una entidad pueden asociarse con UNA instancia de la otra? Solo hay tres respuestas posibles y definen los tres tipos: 1:1 (uno a uno), 1:N (uno a muchos) y N:M (muchos a muchos). Elegir bien la cardinalidad es LA decisión de modelado: determina dónde van las llaves foráneas y cuántas tablas necesitas. En esta lección y las dos siguientes verás cada tipo con su diagrama y sus datos."}$j$),
  (2, 'texto', $j${"title":"1:1 — uno con uno","body":"En una relación 1:1, cada instancia de A se asocia con MÁXIMO una de B, y viceversa. Hospital: cada PACIENTE posee un único EXPEDIENTE clínico, y cada expediente pertenece a un único paciente. ¿Y por qué no fusionar las dos entidades en una? Razones reales para mantener 1:1 separado: el expediente tiene datos sensibles con permisos distintos (diagnósticos, alergias), puede no existir aún (paciente recién registrado), o son decenas de columnas que rara vez se consultan juntas. Anticipo técnico: en SQL, el 1:1 se implementa con una foreign key marcada UNIQUE."}$j$),
  (3, 'diagrama', $j${"title":"PACIENTE 1:1 EXPEDIENTE","component":"CardinalityDiagram","props":{"tipo":"1:1","verbo":"posee","izquierda":{"nombre":"PACIENTE","card":"1","min":1,"descripcion":"Cada expediente pertenece a exactamente un paciente: sin dueño no hay expediente."},"derecha":{"nombre":"EXPEDIENTE","card":"1","min":0,"descripcion":"Cada paciente posee cero o un expediente: puede acabar de registrarse y aún no tenerlo."},"lecturas":["Cada PACIENTE posee cero o un EXPEDIENTE.","Cada EXPEDIENTE pertenece a exactamente un PACIENTE."],"instancias":{"titulo":"Con datos del hospital:","izquierda":["Ana Torres","Luis Vega","Marta Solís","Jorge Paz"],"derecha":["Expediente E-701","Expediente E-702","Expediente E-703"],"conexiones":[[0,0],[1,1],[2,2]]}},"caption":"Cada línea conecta un paciente con SU expediente: nunca dos. Jorge Paz acaba de registrarse y aún no tiene — por eso su lado es opcional."}$j$),
  (4, 'ejemplo_sql', $j${"title":"El 1:1 en los datos","code":"SELECT expediente_id, paciente_id, grupo_sanguineo\nFROM expediente;","result":{"columns":["EXPEDIENTE_ID","PACIENTE_ID","GRUPO_SANGUINEO"],"rows":[["E-701","1","O+"],["E-702","2","A-"],["E-703","3","B+"]]},"caption":"Observa paciente_id: cada valor aparece UNA sola vez. Si apareciera repetido, la relación ya no sería 1:1. Esa unicidad se garantizará con una constraint UNIQUE (módulo 4)."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estas relaciones del mundo salud es 1:1?","options":["MEDICO y CITA","PACIENTE y EXPEDIENTE clínico","PACIENTE y ESTUDIO_LAB","ESPECIALIDAD y MEDICO"],"correctIndex":1,"feedback":{"correct":"Correcto. Un paciente, un expediente; un expediente, un paciente.","incorrect":"La 1:1 es PACIENTE–EXPEDIENTE: cada uno se asocia con máximo uno del otro. Las demás son 1:N."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: ¿cómo se implementa una relación 1:1 en una base relacional?","options":["Con dos foreign keys cruzadas","Con una foreign key con constraint UNIQUE","Duplicando las columnas en ambas tablas","Con un índice compuesto"],"correctIndex":1,"feedback":{"correct":"Exacto. La FK apunta a la otra tabla y el UNIQUE impide que dos filas apunten al mismo registro.","incorrect":"Se usa una foreign key con UNIQUE: referencia a la otra tabla y garantiza que nadie más apunte al mismo registro."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es una buena razón para mantener PACIENTE y EXPEDIENTE como entidades 1:1 separadas en vez de una sola tabla?","options":["Las tablas pequeñas siempre son mejores","El expediente tiene datos sensibles con permisos de acceso distintos","Oracle no permite tablas de más de 20 columnas","Para poder borrar pacientes más rápido"],"correctIndex":1,"feedback":{"correct":"Correcto. Separar permite dar permisos distintos, manejar su ausencia y aislar columnas poco consultadas.","incorrect":"La razón real es de diseño: datos sensibles con otros permisos, existencia opcional o columnas rara vez consultadas."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Cardinalidad 1:1","points":["La cardinalidad dice cuántas instancias de una entidad se asocian con UNA de la otra.","1:1: cada instancia de A con máximo una de B, y viceversa (PACIENTE–EXPEDIENTE).","Razones para separar en 1:1: permisos distintos, existencia opcional, columnas poco usadas.","Se implementa con una foreign key + UNIQUE.","En los datos se reconoce porque la columna de referencia no repite valores."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l06-cardinalidad-1-1';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Cardinalidad 1:N
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"1:N — la reina de las cardinalidades","body":"En una relación 1:N (uno a muchos), una instancia de A puede asociarse con MUCHAS de B, pero cada B pertenece a UNA sola A. Es, por mucho, la más común en cualquier base de datos real. En el hospital están por todas partes: un MEDICO atiende muchas CITAS (y cada cita tiene un solo médico), una ESPECIALIDAD agrupa muchos MEDICOS, una CITA genera muchos ESTUDIOS de laboratorio. Piensa en padre e hijos: el lado 1 es el padre, el lado N son los hijos."}$j$),
  (2, 'texto', $j${"title":"La regla de oro: la FK vive en el lado N","body":"Cuando el 1:N se convierte en tablas, la llave foránea SIEMPRE va en la tabla del lado muchos. ¿Por qué? Cada cita tiene UN médico: una columna medico_id en CITA basta y sobra. Al revés sería imposible: ¿cuántas columnas cita_id tendría que tener MEDICO para sus muchas citas? Esta regla — la FK vive en el hijo — resuelve la mitad de las preguntas de modelado de una entrevista técnica."}$j$),
  (3, 'diagrama', $j${"title":"MÉDICO 1:N CITA","component":"CardinalityDiagram","props":{"tipo":"1:N","verbo":"atiende","izquierda":{"nombre":"MÉDICO","card":"1","min":1,"descripcion":"El lado uno (padre): toda cita es atendida por exactamente un médico."},"derecha":{"nombre":"CITA","card":"N","min":0,"descripcion":"El lado muchos (hijos): un médico puede tener cero, una o muchas citas."},"lecturas":["Cada MÉDICO atiende cero, una o muchas CITAS.","Cada CITA es atendida por exactamente un MÉDICO."],"instancias":{"titulo":"Con datos del hospital:","izquierda":["Dra. Reyes","Dr. Molina","Dra. Ortiz"],"derecha":["Cita 501 · 12/03","Cita 502 · 04/05","Cita 503 · 15/03","Cita 504 · 20/03"],"conexiones":[[0,0],[0,1],[1,2],[0,3]]}},"caption":"La Dra. Reyes acumula tres citas; cada cita apunta a un único médico. La Dra. Ortiz aún no tiene citas — el lado N puede ser cero."}$j$),
  (4, 'ejemplo_sql', $j${"title":"El lado N, visto en los datos","code":"SELECT cita_id, medico_id,\n       TO_CHAR(fecha_hora, 'DD/MM') AS fecha\nFROM cita\nORDER BY medico_id;","result":{"columns":["CITA_ID","MEDICO_ID","FECHA"],"rows":[["501","9","12/03"],["502","9","04/05"],["504","9","20/03"],["503","10","15/03"]]},"caption":"medico_id es la foreign key viviendo en el lado N: se repite tantas veces como citas tenga cada médico. TO_CHAR da formato a la fecha (módulo 5)."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: en la relación 1:N entre MEDICO y CITA, ¿dónde va la foreign key?","options":["En MEDICO, columna cita_id","En CITA, columna medico_id","En una tercera tabla","En ambas tablas"],"correctIndex":1,"feedback":{"correct":"Correcto. La FK siempre vive en el lado N: cada cita guarda a SU médico.","incorrect":"La FK va en el lado muchos (CITA): cada cita tiene un solo médico, así que una columna basta."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estas relaciones del hospital es 1:N?","options":["PACIENTE y EXPEDIENTE","ESPECIALIDAD y MEDICO","PACIENTE y MEDICO","EXPEDIENTE y PACIENTE"],"correctIndex":1,"feedback":{"correct":"Correcto. Una especialidad agrupa muchos médicos; cada médico tiene una especialidad principal.","incorrect":"ESPECIALIDAD–MEDICO es 1:N. PACIENTE–EXPEDIENTE es 1:1 y PACIENTE–MEDICO es N:M (siguiente lección)."}}$j$),
  (7, 'quiz', $j${"variant":"table_reading","table":"CITA\n----------------------------------\ncita_id | medico_id | fecha\n----------------------------------\n501     | 9         | 12/03\n502     | 9         | 04/05\n503     | 10        | 15/03\n504     | 9         | 20/03","prompt":"Según la tabla, ¿cuántas citas atiende el médico con id 9?","options":["Una","Dos","Tres","Cuatro"],"correctIndex":2,"feedback":{"correct":"Correcto. El 9 aparece en las citas 501, 502 y 504: tres citas. Así se ve el lado N.","incorrect":"Cuenta las filas donde medico_id = 9: son 501, 502 y 504. Tres citas."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Cardinalidad 1:N","points":["1:N: una instancia de A con muchas de B; cada B con exactamente una A.","Es la cardinalidad más común: MEDICO–CITA, ESPECIALIDAD–MEDICO, CITA–ESTUDIO_LAB.","Regla de oro: la foreign key SIEMPRE vive en la tabla del lado N (el hijo).","En los datos, el lado N se reconoce por la FK repetida (medico_id 9, tres veces).","El lado N puede ser cero: un médico recién contratado aún no tiene citas."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l07-cardinalidad-1-n';

-- ═════════════════════════════════════════════════════════════════════
-- L08 · Cardinalidad N:M
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"N:M — muchos con muchos","body":"En una relación N:M, cada instancia de A puede asociarse con muchas de B, Y cada B con muchas de A. Hospital: un PACIENTE es atendido por varios MEDICOS a lo largo de su historia (cardióloga, pediatra...), y cada médico atiende a muchos pacientes. Aquí aparece un problema técnico que no existía en 1:1 ni 1:N: la relación N:M NO puede implementarse con una foreign key directa. ¿En qué tabla la pondrías? Cualquiera de los dos lados necesitaría guardar muchos valores en una columna — y eso está prohibido en el modelo relacional."}$j$),
  (2, 'diagrama', $j${"title":"PACIENTE N:M MÉDICO — el modelo conceptual","component":"CardinalityDiagram","props":{"tipo":"N:M","verbo":"es atendido por","izquierda":{"nombre":"PACIENTE","card":"N","min":0,"descripcion":"Un médico atiende a cero, uno o muchos pacientes."},"derecha":{"nombre":"MÉDICO","card":"N","min":0,"descripcion":"Un paciente es atendido por cero, uno o muchos médicos."},"lecturas":["Cada PACIENTE es atendido por cero, uno o muchos MÉDICOS.","Cada MÉDICO atiende a cero, uno o muchos PACIENTES."],"instancias":{"titulo":"Las líneas se cruzan: eso es N:M","izquierda":["Ana Torres","Luis Vega","Marta Solís"],"derecha":["Dra. Reyes","Dr. Molina"],"conexiones":[[0,0],[1,0],[1,1],[2,1]]}},"caption":"Luis Vega ve a dos médicos y la Dra. Reyes atiende a dos pacientes: muchos con muchos, las líneas se cruzan."}$j$),
  (3, 'texto', $j${"title":"La solución: entidad asociativa","body":"Toda relación N:M se descompone en DOS relaciones 1:N a través de una tabla intermedia (tabla puente o entidad asociativa) que guarda un par de foreign keys. En nuestro hospital esa tabla ya existe y tiene nombre propio: CITA. Cada cita conecta UN paciente con UN médico; el N:M emerge de acumular muchas citas. Y aquí el detalle que enamora a los entrevistadores: la entidad asociativa suele ganar atributos propios (fecha_hora, motivo, estado) hasta convertirse en una entidad de pleno derecho. Cuando te pregunten cómo modelar N:M, la respuesta completa es: tabla intermedia con dos FKs — y a menudo esa tabla ES un concepto del negocio."}$j$),
  (4, 'diagrama', $j${"title":"El N:M resuelto: dos 1:N a través de CITA","component":"ERDiagram","props":{"ancho":560,"alto":240,"entidades":[{"id":"paciente","nombre":"PACIENTE","x":10,"y":20,"atributos":[{"nombre":"paciente_id","pk":true},{"nombre":"nombre"}],"descripcion":"El lado uno de la primera relación: un paciente agenda muchas citas."},{"id":"cita","nombre":"CITA","x":205,"y":110,"atributos":[{"nombre":"cita_id","pk":true},{"nombre":"fecha_hora"},{"nombre":"paciente_id","fk":true},{"nombre":"medico_id","fk":true}],"descripcion":"La entidad asociativa: dos foreign keys (paciente y médico) más sus atributos propios."},{"id":"medico","nombre":"MÉDICO","x":400,"y":20,"atributos":[{"nombre":"medico_id","pk":true},{"nombre":"nombre"}],"descripcion":"El lado uno de la segunda relación: un médico atiende muchas citas."}],"relaciones":[{"de":"paciente","a":"cita","verbo":"agenda","extremoDe":{"card":"1","min":1},"extremoA":{"card":"N","min":0},"descripcion":"Primera mitad del N:M: un paciente, muchas citas."},{"de":"medico","a":"cita","verbo":"atiende","extremoDe":{"card":"1","min":1},"extremoA":{"card":"N","min":0},"descripcion":"Segunda mitad del N:M: un médico, muchas citas."}]},"caption":"El N:M conceptual se implementa como dos 1:N. CITA guarda las dos foreign keys."}$j$),
  (5, 'ejemplo_sql', $j${"title":"El N:M emergiendo de la tabla puente","code":"SELECT paciente_id, medico_id\nFROM cita\nORDER BY paciente_id;","result":{"columns":["PACIENTE_ID","MEDICO_ID"],"rows":[["1","9"],["1","9"],["2","10"],["3","9"]]},"caption":"El paciente 1 se repite (varios encuentros) y el médico 9 también (varios pacientes): ambos lados se repiten — eso es N:M. Cada fila individual sigue siendo un par único paciente-médico-momento."}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: ¿cómo se implementa una relación N:M en una base relacional?","options":["Con una foreign key en cada una de las dos tablas","Con una tabla intermedia que guarda una FK hacia cada lado","Con una columna multivaluada","No se puede: hay que evitar el N:M en el diseño"],"correctIndex":1,"feedback":{"correct":"Exacto. La tabla puente descompone el N:M en dos 1:N. En nuestro caso, esa tabla es CITA.","incorrect":"El N:M requiere una tabla intermedia con dos foreign keys: se descompone en dos relaciones 1:N."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estas relaciones es N:M?","options":["PACIENTE y EXPEDIENTE","MEDICO y CITA","PACIENTE y MEDICO","CITA y ESTUDIO_LAB"],"correctIndex":2,"feedback":{"correct":"Correcto. Muchos pacientes ven a muchos médicos: N:M, resuelta a través de CITA.","incorrect":"PACIENTE–MEDICO es la N:M: cada lado se asocia con muchos del otro. Se resuelve con CITA en medio."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué convierte a CITA en una entidad de pleno derecho y no en una simple tabla puente?","options":["Que tiene más de dos columnas","Que tiene atributos propios del negocio: fecha_hora, motivo, estado","Que Oracle la trata distinto","Que su nombre no combina los de las otras dos tablas"],"correctIndex":1,"feedback":{"correct":"Correcto. Cuando la asociación tiene datos propios, la tabla puente se vuelve un concepto real del negocio.","incorrect":"Lo que la eleva son sus atributos propios (fecha, motivo, estado): la asociación en sí lleva información."}}$j$),
  (9, 'resumen', $j${"title":"Resumen — Cardinalidad N:M","points":["N:M: cada instancia de un lado se asocia con muchas del otro, en ambas direcciones.","No puede implementarse con una FK directa: ninguna columna puede guardar muchos valores.","Se descompone en DOS relaciones 1:N mediante una tabla intermedia con dos FKs.","La entidad asociativa suele tener atributos propios y volverse concepto del negocio (CITA).","En los datos, el N:M se reconoce porque AMBAS columnas de FK repiten valores."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l08-cardinalidad-n-m';

-- ═════════════════════════════════════════════════════════════════════
-- L09 · Participación y opcionalidad
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"El mínimo también importa","body":"Hasta ahora hablamos del MÁXIMO (¿una o muchas?). Pero toda relación tiene una segunda pregunta: ¿es obligatorio participar? Ese es el MÍNIMO, y solo tiene dos valores: 0 (opcional) o 1 (obligatorio). La cardinalidad completa de un extremo se escribe (mín, máx): un médico atiende (0,N) citas — puede no tener ninguna; una cita es atendida por (1,1) médicos — siempre exactamente uno. Cuando el mínimo es 1 para TODAS las instancias, se dice que la participación es TOTAL; si alguna instancia puede quedarse fuera, es PARCIAL."}$j$),
  (2, 'texto', $j${"title":"Cómo se dibuja y por qué te importa","body":"En pata de gallo, el símbolo EXTERIOR (el más lejano a la entidad) es el mínimo: anillo = 0, barra = 1. En Barker, lo opcional se marca con la mitad discontinua de la línea. ¿Y por qué importa tanto? Porque el mínimo se convierte en decisiones concretas de SQL: participación obligatoria = columna NOT NULL; opcional = columna que acepta NULL. Un error de opcionalidad en el diseño se paga durante años: campos NULL que deberían ser obligatorios o inserciones bloqueadas sin razón. En entrevistas: EXPEDIENTE tiene participación total (todo expediente pertenece a un paciente, sin excepción); MEDICO en atiende es parcial (la recién contratada Dra. Ortiz aún no tiene citas)."}$j$),
  (3, 'diagrama', $j${"title":"Mínimos a la vista: MÉDICO (1,1) — CITA (0,N)","component":"CardinalityDiagram","props":{"tipo":"1:N","verbo":"atiende","izquierda":{"nombre":"MÉDICO","card":"1","min":1,"descripcion":"Mínimo 1: toda cita DEBE tener médico. Participación obligatoria — barra en pata de gallo, línea continua en Barker."},"derecha":{"nombre":"CITA","card":"N","min":0,"descripcion":"Mínimo 0: un médico puede no tener citas. Participación opcional — anillo en pata de gallo, línea discontinua en Barker."},"lecturas":["Cada MÉDICO atiende cero, una o muchas CITAS (opcional).","Cada CITA es atendida por exactamente un MÉDICO (obligatorio)."],"instancias":{"titulo":"La Dra. Ortiz participa en la relación... con cero citas:","izquierda":["Dra. Reyes","Dr. Molina","Dra. Ortiz"],"derecha":["Cita 501 · 12/03","Cita 502 · 04/05","Cita 503 · 15/03","Cita 504 · 20/03"],"conexiones":[[0,0],[0,1],[1,2],[0,3]]}},"caption":"Alterna a notación Barker y observa qué mitad de la línea se vuelve discontinua: la del extremo opcional."}$j$),
  (4, 'ejemplo_sql', $j${"title":"La participación parcial, encontrada con SQL","code":"SELECT medico_id, nombre\nFROM medico\nWHERE medico_id NOT IN (SELECT medico_id FROM cita);","result":{"columns":["MEDICO_ID","NOMBRE"],"rows":[["11","Dra. Carla Ortiz"]]},"caption":"La consulta encuentra a los médicos que NO participan en la relación: participación parcial con nombre y apellido. La sintaxis de subconsultas se estudia a fondo en el módulo 6."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué significa que EXPEDIENTE tenga participación TOTAL en la relación con PACIENTE?","options":["Que hay muchos expedientes","Que todo expediente pertenece obligatoriamente a un paciente","Que el expediente guarda todos los datos del paciente","Que la relación es 1:1"],"correctIndex":1,"feedback":{"correct":"Correcto. Participación total = ninguna instancia puede quedarse fuera de la relación: mínimo 1.","incorrect":"Participación total significa mínimo 1: no puede existir un expediente sin su paciente."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"La cardinalidad (0,N) de MÉDICO respecto a atiende significa:","options":["Un médico atiende exactamente N citas","Un médico debe atender al menos una cita","Un médico puede atender desde ninguna hasta muchas citas","Ningún médico atiende citas"],"correctIndex":2,"feedback":{"correct":"Correcto. Mínimo 0 (puede no tener) y máximo N (puede tener muchas).","incorrect":"(0,N) se lee: mínimo cero, máximo muchas. Puede no tener citas, o tener muchísimas."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: ¿en qué se traduce la participación obligatoria al crear la tabla?","options":["En un índice","En una columna NOT NULL","En una tabla adicional","En un trigger"],"correctIndex":1,"feedback":{"correct":"Exacto. Mínimo 1 = la FK no acepta NULL: toda fila debe participar en la relación.","incorrect":"Obligatorio significa que la foreign key será NOT NULL: no puede existir la fila sin esa referencia."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Participación y opcionalidad","points":["El mínimo de un extremo es 0 (opcional) o 1 (obligatorio); se escribe (mín, máx).","Participación total: todas las instancias participan (mínimo 1). Parcial: alguna puede no hacerlo.","Pata de gallo: símbolo exterior = mínimo (anillo 0, barra 1). Barker: mitad discontinua = opcional.","Obligatorio se traduce a NOT NULL; opcional, a columna que acepta NULL.","EXPEDIENTE participa total en posee; MEDICO participa parcial en atiende (Dra. Ortiz, cero citas)."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l09-participacion-y-opcionalidad';

-- ═════════════════════════════════════════════════════════════════════
-- L10 · Llaves candidatas y primary key
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"Identificar sin ambigüedad","body":"En un hospital hay dos pacientes llamados Luis Vega. ¿Cómo sabes cuál es cuál? Necesitas atributos que identifiquen a cada instancia SIN ambigüedad. La teoría define una escalera de conceptos: SUPERLLAVE: cualquier conjunto de atributos que identifica de forma única (dni + nombre + teléfono funciona, pero sobra). LLAVE CANDIDATA: una superllave MÍNIMA — si le quitas un atributo, deja de identificar. Una tabla puede tener varias: en PACIENTE, el dni y el email son candidatas. PRIMARY KEY: LA candidata que eliges como identificador oficial. LLAVES ALTERNAS: las candidatas que no elegiste (quedarán como UNIQUE)."}$j$),
  (2, 'texto', $j${"title":"Cómo elegir una buena primary key","body":"Criterios de una PK sana: nunca NULL, nunca cambia (estable), compacta, y sin significado de negocio. Este último sorprende: ¿por qué NO usar el dni? Porque los datos con significado cambian y fallan: hay errores de captura que obligan a corregirlo, pacientes extranjeros sin dni, y regulaciones que prohíben exponerlo. Por eso casi siempre se agrega una llave SUBROGADA (surrogate): un número sin significado generado por la base (paciente_id), y las candidatas naturales quedan como llaves alternas con UNIQUE. El debate llave natural vs subrogada es un clásico de entrevista senior: la respuesta madura es subrogada como PK + UNIQUE sobre la natural."}$j$),
  (3, 'ejemplo_sql', $j${"title":"Tres candidatas, una elegida","code":"SELECT paciente_id, dni, email, nombre\nFROM paciente;","result":{"columns":["PACIENTE_ID","DNI","EMAIL","NOMBRE"],"rows":[["1","44210987","ana.torres@mail.com","Ana Torres"],["2","38765401","lvega@mail.com","Luis Vega"],["3","51002344","marta.s@mail.com","Marta Solís"]]},"caption":"paciente_id, dni y email: las tres identifican de forma única (candidatas). paciente_id es la PK subrogada; dni y email son llaves alternas. nombre NO es candidata: puede repetirse."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es una llave candidata?","options":["Cualquier columna de la tabla","Una superllave mínima: identifica de forma única y no le sobra ningún atributo","La primera columna de la tabla","Una columna que acepta NULL"],"correctIndex":1,"feedback":{"correct":"Correcto. Identifica de forma única y es mínima: sin atributos de sobra.","incorrect":"Candidata = superllave mínima: identifica únicamente a cada fila y no le sobra nada."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué el email es una MALA primary key aunque sea único?","options":["Porque es texto y las PK deben ser números","Porque la gente cambia de email, y una PK debe ser estable","Porque Oracle no indexa emails","Porque puede tener mayúsculas"],"correctIndex":1,"feedback":{"correct":"Exacto. Una PK que cambia arrastra actualizaciones en cadena por todas las tablas que la referencian.","incorrect":"El problema es la estabilidad: los emails cambian, y cambiar una PK obliga a actualizar todas sus referencias."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de entrevista: ¿qué es una llave subrogada (surrogate key)?","options":["Una llave compuesta por varias columnas","Un identificador sin significado de negocio, generado por la base de datos","Una llave que sustituye a la foreign key","Una copia de seguridad de la PK"],"correctIndex":1,"feedback":{"correct":"Correcto. Un número artificial (paciente_id) estable y compacto. La respuesta senior: surrogate como PK + UNIQUE en la llave natural.","incorrect":"Subrogada = identificador artificial sin significado (paciente_id), generado por la base. Estable por diseño."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuántas primary keys puede tener una tabla?","options":["Una por cada columna única","Máximo dos","Exactamente una (aunque puede estar compuesta por varias columnas)","Ilimitadas"],"correctIndex":2,"feedback":{"correct":"Correcto. UNA sola PK por tabla; si necesita varias columnas, es una PK compuesta — sigue siendo una.","incorrect":"Solo una PK por tabla. Puede abarcar varias columnas (PK compuesta), pero sigue siendo una sola llave."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Llaves","points":["Superllave: identifica únicamente. Candidata: superllave mínima. PK: la candidata elegida.","Las candidatas no elegidas son llaves alternas y se protegen con UNIQUE.","Una buena PK: nunca NULL, estable, compacta y sin significado de negocio.","Llave subrogada: número artificial generado por la base (paciente_id) — estable por diseño.","Respuesta de entrevista: surrogate como PK + constraint UNIQUE sobre la llave natural (dni)."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l10-llaves-candidatas-y-pk';

-- ═════════════════════════════════════════════════════════════════════
-- L11 · El modelo ER del hospital
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"Leer un modelo real, completo","body":"Es hora de juntar todo el módulo en un solo diagrama: el modelo del hospital que nos acompañará el resto del curso. Método para leer cualquier ER (útil en el primer día de un trabajo nuevo y en entrevistas de diseño): 1) identifica las entidades y sus PKs; 2) recorre cada relación leyéndola como frase en ambas direcciones; 3) verifica cardinalidades máximas (¿dónde está la pata de gallo?); 4) verifica los mínimos (¿qué es opcional?); 5) localiza las entidades asociativas que resuelven N:M. Aplícalo al diagrama de abajo antes de responder las preguntas."}$j$),
  (2, 'diagrama', $j${"title":"El hospital completo: 6 entidades, 5 relaciones","component":"ERDiagram","props":{"ancho":580,"alto":440,"entidades":[{"id":"especialidad","nombre":"ESPECIALIDAD","x":20,"y":20,"atributos":[{"nombre":"especialidad_id","pk":true},{"nombre":"nombre"}],"descripcion":"Catálogo de especialidades médicas: Cardiología, Pediatría..."},{"id":"medico","nombre":"MÉDICO","x":20,"y":150,"atributos":[{"nombre":"medico_id","pk":true},{"nombre":"nombre"},{"nombre":"colegiatura"},{"nombre":"especialidad_id","fk":true}],"descripcion":"Personal médico del hospital. Su colegiatura es llave alterna (única)."},{"id":"cita","nombre":"CITA","x":230,"y":150,"atributos":[{"nombre":"cita_id","pk":true},{"nombre":"fecha_hora"},{"nombre":"motivo"},{"nombre":"estado"},{"nombre":"paciente_id","fk":true},{"nombre":"medico_id","fk":true}],"descripcion":"Entidad asociativa que resuelve el N:M entre PACIENTE y MÉDICO, con atributos propios."},{"id":"paciente","nombre":"PACIENTE","x":410,"y":150,"atributos":[{"nombre":"paciente_id","pk":true},{"nombre":"nombre"},{"nombre":"dni"},{"nombre":"fecha_nacimiento"}],"descripcion":"Personas atendidas por el hospital. dni es llave alterna."},{"id":"expediente","nombre":"EXPEDIENTE","x":410,"y":20,"atributos":[{"nombre":"expediente_id","pk":true},{"nombre":"paciente_id","fk":true},{"nombre":"grupo_sanguineo"}],"descripcion":"Historia clínica: relación 1:1 con PACIENTE (su FK será UNIQUE)."},{"id":"estudio","nombre":"ESTUDIO_LAB","x":230,"y":330,"atributos":[{"nombre":"estudio_id","pk":true},{"nombre":"cita_id","fk":true},{"nombre":"tipo"},{"nombre":"resultado"}],"descripcion":"Estudios de laboratorio solicitados durante una cita."}],"relaciones":[{"de":"especialidad","a":"medico","verbo":"agrupa","extremoDe":{"card":"1","min":1},"extremoA":{"card":"N","min":0},"descripcion":"Cada médico tiene una especialidad principal; una especialidad puede no tener médicos aún."},{"de":"medico","a":"cita","verbo":"atiende","extremoDe":{"card":"1","min":1},"extremoA":{"card":"N","min":0},"descripcion":"Un médico atiende muchas citas; toda cita tiene exactamente un médico."},{"de":"paciente","a":"cita","verbo":"agenda","extremoDe":{"card":"1","min":1},"extremoA":{"card":"N","min":0},"descripcion":"Un paciente agenda muchas citas; toda cita pertenece a un paciente."},{"de":"paciente","a":"expediente","verbo":"posee","extremoDe":{"card":"1","min":1},"extremoA":{"card":"1","min":0},"descripcion":"1:1 — cada paciente posee a lo sumo un expediente; todo expediente tiene dueño."},{"de":"cita","a":"estudio","verbo":"genera","extremoDe":{"card":"1","min":1},"extremoA":{"card":"N","min":0},"descripcion":"Una cita puede generar varios estudios de laboratorio."}]},"caption":"Toca cada entidad y cada verbo. Este modelo se convertirá en tablas reales con CREATE TABLE en el módulo 4."}$j$),
  (3, 'ejemplo_sql', $j${"title":"Recorrer el modelo con una consulta","code":"SELECT cita_id, TO_CHAR(fecha_hora, 'DD/MM') AS fecha, motivo\nFROM cita\nWHERE paciente_id = 1;","result":{"columns":["CITA_ID","FECHA","MOTIVO"],"rows":[["501","12/03","Control de presión arterial"],["502","04/05","Dolor torácico"]]},"caption":"Entender el modelo te dice exactamente dónde buscar: las citas de Ana viven en CITA, filtradas por su paciente_id."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Según el diagrama, la relación PACIENTE–EXPEDIENTE es:","options":["1:N, con la FK en PACIENTE","1:1, con participación opcional del lado EXPEDIENTE","N:M, resuelta por CITA","1:N, con la FK en EXPEDIENTE"],"correctIndex":1,"feedback":{"correct":"Correcto. Uno a uno: cada paciente posee a lo sumo un expediente y todo expediente tiene dueño.","incorrect":"Es 1:1: un paciente, un expediente. El lado expediente es opcional (un paciente recién registrado puede no tenerlo)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cómo se conecta PACIENTE con MÉDICO en este modelo?","options":["Con una FK directa entre ambos","No están conectados","A través de CITA: dos relaciones 1:N que resuelven el N:M","A través de EXPEDIENTE"],"correctIndex":2,"feedback":{"correct":"Correcto. CITA es la entidad asociativa: paciente agenda citas, médico atiende citas.","incorrect":"No hay FK directa: PACIENTE y MÉDICO se relacionan N:M a través de la entidad asociativa CITA."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué la FK especialidad_id está en MÉDICO y no al revés?","options":["Por orden alfabético","Porque MÉDICO es el lado N: cada médico tiene UNA especialidad","Porque ESPECIALIDAD tiene menos columnas","Es indistinto: podría ir en cualquiera"],"correctIndex":1,"feedback":{"correct":"Correcto. La FK vive en el lado muchos: cada médico apunta a su única especialidad.","incorrect":"Regla de oro del 1:N: la FK va en el lado muchos. Cada médico tiene una especialidad, así que la FK vive en MÉDICO."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Si se elimina un paciente, ¿qué debería pasar con su expediente? (adelanto del módulo 2)","options":["Nada: quedan expedientes huérfanos","Lo decide la regla de integridad referencial que definas (p. ej. borrado en cascada)","Oracle lo impide siempre","El expediente pasa a otro paciente"],"correctIndex":1,"feedback":{"correct":"Correcto. Eso es integridad referencial: TÚ defines la regla (impedir, poner NULL o borrar en cascada). Módulo 2.","incorrect":"Es una decisión de diseño llamada integridad referencial: impedir el borrado, anular la referencia o borrar en cascada. La verás en el módulo 2."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — El modelo del hospital","points":["Método de lectura: entidades y PKs → relaciones como frases → máximos → mínimos → asociativas.","Seis entidades: PACIENTE, EXPEDIENTE, MÉDICO, ESPECIALIDAD, CITA y ESTUDIO_LAB.","PACIENTE–EXPEDIENTE es 1:1; ESPECIALIDAD–MÉDICO, MÉDICO–CITA, PACIENTE–CITA y CITA–ESTUDIO_LAB son 1:N.","PACIENTE–MÉDICO es N:M, resuelto por la entidad asociativa CITA.","Este modelo se convertirá en tablas Oracle reales en el módulo 4 — y te acompañará todo el curso."]}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-l11-er-hospital';

-- ═════════════════════════════════════════════════════════════════════
-- L12 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l,
(values
  (1, 'texto', $j${"title":"El núcleo de la región","body":"Byte llegó al núcleo de la región: trece preguntas guardan el acceso. Todo lo que necesitas ya lo dominas — modelos de datos, entidades, relaciones, tuplas, atributos, dominios, cardinalidades, participación y llaves. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Un modelo de datos define principalmente:","options":["El hardware del servidor de base de datos","Cómo se estructura, organiza y relaciona la información","El lenguaje de programación del backend","La interfaz de usuario del sistema"],"correctIndex":1,"feedback":{"correct":"Correcto. Estructura y relaciones de la información, independiente de la aplicación.","incorrect":"El modelo de datos es la organización lógica de la información: estructura y relaciones."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué modelo de datos guarda documentos JSON autocontenidos y en cuál brilla Oracle?","options":["Documental y relacional, respectivamente","Jerárquico y de red, respectivamente","Relacional y documental, respectivamente","De red y jerárquico, respectivamente"],"correctIndex":0,"feedback":{"correct":"Correcto. MongoDB es documental; Oracle es el gran motor relacional.","incorrect":"El documental guarda JSON (MongoDB); Oracle implementa el modelo relacional."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En el hospital: MEDICO, colegiatura y la Dra. Reyes son, respectivamente:","options":["Entidad, atributo e instancia","Atributo, entidad e instancia","Instancia, atributo y entidad","Entidad, instancia y atributo"],"correctIndex":0,"feedback":{"correct":"Correcto. MEDICO es el tipo de entidad, colegiatura la describe, y la Dra. Reyes es una instancia concreta.","incorrect":"MEDICO = entidad (tipo), colegiatura = atributo, Dra. Reyes = instancia."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En el modelo relacional formal, relation significa:","options":["Foreign key","Asociación entre entidades","Tabla","Diagrama ER"],"correctIndex":2,"feedback":{"correct":"Correcto. Relation = tabla; relationship = asociación. La confusión clásica, superada.","incorrect":"Relation es tabla (por eso modelo relacional). La asociación entre entidades es relationship."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En notación Barker, la mitad discontinua de la línea de relación indica:","options":["El lado muchos","Participación opcional en ese extremo","Una relación recursiva","Que la relación aún no está aprobada"],"correctIndex":1,"feedback":{"correct":"Correcto. Discontinua = opcional; continua = obligatoria. Y la pata de gallo marca el lado muchos.","incorrect":"En Barker el trazo discontinuo marca lo opcional de ese extremo de la relación."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"La relación 1:1 PACIENTE–EXPEDIENTE se implementa con:","options":["Dos tablas puente","Una foreign key con constraint UNIQUE","Una columna multivaluada","Un trigger de sincronización"],"correctIndex":1,"feedback":{"correct":"Correcto. FK + UNIQUE: referencia al paciente y nadie más puede apuntarle.","incorrect":"1:1 = foreign key con UNIQUE, para que solo una fila referencie a cada paciente."}}$j$),
  (8, 'quiz', $j${"variant":"table_reading","table":"CITA\n-----------------------------------\ncita_id | paciente_id | medico_id\n-----------------------------------\n501     | 1           | 9\n502     | 1           | 9\n503     | 2           | 10\n504     | 3           | 9","prompt":"Ambas columnas de FK repiten valores (paciente 1 dos veces, médico 9 tres veces). ¿Qué cardinalidad revela esto entre PACIENTE y MÉDICO?","options":["1:1","1:N","N:M","Ninguna: es un error de datos"],"correctIndex":2,"feedback":{"correct":"Correcto. Repetición en AMBOS lados = muchos con muchos, resuelto por la tabla puente CITA.","incorrect":"Cuando ambas FKs repiten valores, ambos lados se asocian con muchos del otro: N:M."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"En una relación 1:N, la foreign key vive en:","options":["El lado 1 (el padre)","El lado N (el hijo)","Una tabla intermedia","Cualquiera de los dos lados"],"correctIndex":1,"feedback":{"correct":"Correcto. Regla de oro: la FK va en el lado muchos.","incorrect":"Siempre en el lado N: cada hijo guarda la referencia a su único padre."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Participación total de una entidad en una relación significa:","options":["Que participa con todas sus columnas","Que toda instancia debe participar: mínimo 1","Que puede participar muchas veces","Que la relación es N:M"],"correctIndex":1,"feedback":{"correct":"Correcto. Total = obligatoria para todas las instancias (mínimo 1); parcial = alguna puede quedarse fuera.","incorrect":"Total = ninguna instancia puede quedarse fuera de la relación (mínimo 1)."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Relación, tupla y atributo equivalen, en el vocabulario práctico, a:","options":["Tabla, fila y columna","Fila, tabla y columna","Tabla, columna y fila","Base de datos, tabla y fila"],"correctIndex":0,"feedback":{"correct":"Correcto. Relación = tabla, tupla = fila, atributo = columna. El vocabulario formal y el práctico nombran lo mismo.","incorrect":"El mapa es: relación → tabla, tupla → fila, atributo → columna."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"PACIENTE tiene 4 columnas y 3 filas. Formalmente, su grado y su cardinalidad son:","options":["Grado 3 y cardinalidad 4","Grado 4 y cardinalidad 3","Grado 12 y cardinalidad 7","Grado 4 y cardinalidad 4"],"correctIndex":1,"feedback":{"correct":"Correcto. Grado = nº de atributos (4); cardinalidad = nº de tuplas (3). El grado es estructura; la cardinalidad cambia con los datos.","incorrect":"Grado cuenta los atributos (columnas): 4. Cardinalidad cuenta las tuplas (filas): 3."}}$j$),
  (13, 'quiz', $j${"variant":"multiple_choice","prompt":"El conjunto de valores válidos de un atributo — los 8 grupos sanguíneos posibles para grupo_sanguineo — se llama:","options":["Grado","Rango","Dominio","Esquema"],"correctIndex":2,"feedback":{"correct":"Correcto. El dominio define qué valores puede tomar el atributo; todo lo demás debe ser rechazado.","incorrect":"Ese conjunto de valores válidos es el DOMINIO del atributo. El grado cuenta atributos y el esquema es la estructura completa."}}$j$),
  (14, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: ¿por qué elegir paciente_id (subrogada) como PK en lugar del dni?","options":["Porque los números ocupan menos que el texto","Porque el dni puede cambiar (correcciones), faltar (extranjeros) y exponerlo tiene restricciones — la PK debe ser estable y sin significado","Porque Oracle no acepta PKs de texto","Porque el dni no es único"],"correctIndex":1,"feedback":{"correct":"Impecable. Estabilidad y neutralidad: surrogate como PK, y el dni queda como llave alterna con UNIQUE.","incorrect":"La razón senior: los datos con significado cambian y fallan. PK subrogada estable + UNIQUE sobre el dni."}}$j$)
) as v(ord, kind, payload)
where l.slug = 'm01-x01-examen';
