-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 014 — SQL con Oracle · M3: Normalización
-- ═══════════════════════════════════════════════════════════════════
-- Cubre la Parte III del temario obligatorio COMPLETA: dependencias
-- funcionales, redundancia, las TRES anomalías (inserción /
-- actualización / eliminación), 1FN (atomicidad, multivalorados,
-- grupos repetitivos), 2FN (dependencia completa vs parcial), 3FN
-- (dependencias transitivas) y la comparación entre las tres.
-- Incluye el Diagrama 3.1 (evolución a 1FN: EDIFICIO→AULA) con
-- NetworkDiagram data-driven.
-- Precisión vinculante de Karen: normalización LÓGICA ≠ optimización
-- FÍSICA — la desnormalización es una decisión física posterior y
-- justificada con evidencia, no un atajo de diseño.
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- OJO: SQL con Oracle está PUBLICADO — esta migración sale en vivo.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 011 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm03-normalizacion'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m03-l01-dependencias-funcionales','Dependencias funcionales y redundancia','leccion',  20, 1),
       ('m03-l02-anomalias',              'Las tres anomalías',                    'leccion',  20, 2),
       ('m03-l03-1fn',                    'Primera Forma Normal',                  'leccion',  20, 3),
       ('m03-l04-2fn',                    'Segunda Forma Normal',                  'leccion',  20, 4),
       ('m03-l05-3fn',                    'Tercera Forma Normal',                  'leccion',  20, 5),
       ('m03-l06-panorama',               'El panorama: 1FN a 3FN (y más allá)',   'leccion',  20, 6),
       ('m03-l07-practica-diagnostico',   'Práctica: el diagnóstico',              'practica', 20, 7),
       ('m03-x01-examen',                 'Examen: Normalización',                 'examen',   40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm03-normalizacion';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Dependencias funcionales y redundancia
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Un solo lugar, y el mejor lugar posible","body":"La NORMALIZACIÓN es el método sistemático para lograr una meta simple de enunciar: almacenar cada pieza de información EN UN SOLO LUGAR, y en el MEJOR lugar posible. Su herramienta de análisis es la DEPENDENCIA FUNCIONAL: decimos que A determina B (se escribe A → B) cuando, conociendo el valor de A, el valor de B queda determinado sin ambigüedad. En el hospital: medico_id → colegiatura (conociendo el médico, su colegiatura es una sola); historia_clinica → fecha_nacimiento. Las dependencias funcionales son el mapa de 'qué pertenece a qué' — y las formas normales que vienen son, en el fondo, tres reglas sobre DÓNDE puede vivir cada dependencia."}$j$),
  (2, 'texto', $j${"title":"El precio de la redundancia","body":"¿Y por qué obsesionarse con el 'un solo lugar'? Por el riesgo de negocio de la REDUNDANCIA. Imagina el nombre del proveedor repetido en las 50 filas de sus productos: si el proveedor cambia de razón social, hay que actualizar las 50 — y si una actualización falla o alguien olvida una fila, el sistema queda diciendo DOS verdades contradictorias. ¿Cuál es la buena? Nadie sabe: la INCONSISTENCIA no avisa. En el hospital el caso gemelo: el teléfono del médico copiado en cada cita — el día que cambie, ¿cuántas citas quedarán con el teléfono viejo? La redundancia no es un problema de espacio en disco (eso es barato): es un problema de INTEGRIDAD. Cada copia extra es una promesa de inconsistencia futura."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos formales, ¿qué significa la dependencia funcional A → B?","options":["Que A y B están en tablas distintas","Que conociendo el valor de A, el valor de B queda DETERMINADO sin ambigüedad (medico_id → colegiatura)","Que A es más importante que B","Que B es una clave"],"correctIndex":1,"feedback":{"correct":"Correcto. A determina B: un valor de A no puede corresponder a dos valores distintos de B.","incorrect":"A → B se lee 'A determina B': fijado A, B es uno solo. Es la herramienta de análisis de toda la normalización."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"El nombre de un proveedor está copiado en las 50 filas de sus productos y el proveedor cambia de razón social. ¿Cuál es el riesgo REAL de esa redundancia?","options":["Que el disco se llene","La INCONSISTENCIA: si alguna fila no se actualiza, el sistema dirá dos verdades contradictorias — y nadie sabrá cuál es la buena","Que las consultas sean ilegales","Ninguno: copiar es más rápido"],"correctIndex":1,"feedback":{"correct":"Correcto. El problema no es el espacio (barato): es la integridad. Cada copia es una promesa de inconsistencia.","incorrect":"El riesgo es de integridad: 50 copias = 50 oportunidades de que el dato quede a medias tras un cambio."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Dependencias y redundancia","points":["Normalizar = almacenar cada información en UN solo lugar, y en el MEJOR lugar.","Dependencia funcional A → B: conociendo A, B queda determinado (medico_id → colegiatura).","Las formas normales son reglas sobre DÓNDE puede vivir cada dependencia.","La redundancia es riesgo de INTEGRIDAD, no de espacio: cada copia extra promete inconsistencia.","El caso del proveedor en 50 productos (o el teléfono del médico en cada cita): el enemigo a cazar."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-l01-dependencias-funcionales';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Las tres anomalías
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuando la tabla mal diseñada ataca","body":"La redundancia no se queda quieta: produce ANOMALÍAS — comportamientos absurdos que un buen diseño hace imposibles. Son tres, y las entrevistas piden las tres con nombre. ANOMALÍA DE INSERCIÓN: no puedes registrar un hecho porque el diseño te exige otro que no existe — en una tabla única proveedor+producto, no puedes dar de alta un proveedor nuevo hasta que tenga su primer producto. ANOMALÍA DE ACTUALIZACIÓN: un cambio real exige tocar MUCHAS filas — la razón social del proveedor, 50 actualizaciones; si una falla, inconsistencia. ANOMALÍA DE ELIMINACIÓN: borrar un hecho arrastra otro que querías conservar — eliminas el último producto del proveedor… y el proveedor entero desaparece del sistema, con su historial de contacto."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Las tres anomalías, en una tabla real","code":"-- Una sola tabla para todo (mal diseño a propósito):\nSELECT * FROM producto_proveedor;","result":{"columns":["PRODUCTO_ID","PRODUCTO","PROVEEDOR_ID","PROVEEDOR","TELEFONO_PROV"],"rows":[["P01","Guantes nitrilo","V7","MediSupply SA","555-0101"],["P02","Jeringas 5ml","V7","MediSupply SA","555-0101"],["P03","Gasas 10x10","V7","MediSupply SA","555-0101"],["P04","Termómetros","V9","Insumos Andinos","555-0202"]],"note":"INSERCIÓN: no puedes registrar al proveedor nuevo 'BioLab' sin inventarle un producto. ACTUALIZACIÓN: si MediSupply cambia de teléfono, son 3 filas (¿y si olvidas una?). ELIMINACIÓN: borra P04 y 'Insumos Andinos' se esfuma con su teléfono."},"caption":"Una tabla, tres trampas armadas. La solución de la normalización: PROVEEDOR y PRODUCTO como entidades separadas, relacionadas 1:N."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Un hospital no puede registrar a un médico recién contratado porque la tabla exige que tenga al menos una cita asignada. En términos de normalización, eso es una anomalía de…","options":["Actualización","INSERCIÓN: el diseño impide registrar un hecho real (el médico) sin otro que aún no existe (su cita)","Eliminación","Consulta"],"correctIndex":1,"feedback":{"correct":"Correcto. No poder dar de alta algo real por culpa del diseño = anomalía de inserción.","incorrect":"Cuando no puedes INSERTAR un hecho legítimo sin inventar otro, es anomalía de inserción."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Se elimina la última cita del paciente Jorge Paz y, con ella, desaparecen del sistema su nombre y su grupo sanguíneo (vivían solo en las filas de citas). Esa es la anomalía de…","options":["Inserción","Actualización","ELIMINACIÓN: borrar un hecho arrastró otro que debía conservarse","Redundancia"],"correctIndex":2,"feedback":{"correct":"Correcto. Borrar la cita no debía borrar al paciente: sus datos merecían vivir en su propia entidad.","incorrect":"Cuando un DELETE legítimo arrastra información que querías conservar, es anomalía de eliminación."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Cambiar la razón social de un proveedor exige actualizar las 50 filas donde está copiada, con riesgo de dejar alguna a medias. Nombre técnico:","options":["Anomalía de ACTUALIZACIÓN: un cambio real exige tocar muchas filas, con inconsistencia si alguna falla","Anomalía de inserción","Dependencia funcional","Integridad referencial"],"correctIndex":0,"feedback":{"correct":"Correcto. Un hecho cambió una vez en el mundo; el mal diseño lo cobra 50 veces en la base.","incorrect":"El cambio múltiple con riesgo de quedar a medias es la anomalía de ACTUALIZACIÓN — hija directa de la redundancia."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Las tres anomalías","points":["INSERCIÓN: no puedes registrar un hecho real sin inventar otro (el proveedor sin producto).","ACTUALIZACIÓN: un cambio del mundo exige tocar muchas filas — inconsistencia si alguna falla.","ELIMINACIÓN: borrar un hecho arrastra información que debía conservarse.","Las tres nacen de la misma raíz: información viviendo en el lugar equivocado (redundancia).","El buen diseño no 'maneja' las anomalías: las hace IMPOSIBLES."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-l02-anomalias';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Primera Forma Normal (+ Diagrama 3.1)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"1FN: cada celda, un solo valor","body":"La PRIMERA FORMA NORMAL exige ATOMICIDAD: todo atributo debe contener UN SOLO valor indivisible por instancia. Sus dos enemigos: los ATRIBUTOS MULTIVALORADOS — la celda 'aulas: A101, A102, B201' en EDIFICIO, o 'teléfonos: 555-1234, 555-5678' en PACIENTE (la regla del valor único del módulo 1, ahora con quien la cobre) — y los GRUPOS REPETITIVOS: columnas clonadas tipo aula1, aula2, aula3 que fingen cumplir pero solo disfrazan el problema (¿y cuando llegue la aula4? ¿y cómo consultas 'todas las aulas del edificio B'?). El precio de violar 1FN es inmediato: no puedes filtrar, contar ni relacionar lo que vive apretujado dentro de una celda. La solución es siempre la misma: el atributo multivaluado SE MUDA a su propia entidad, relacionada 1:N con la original."}$j$),
  (2, 'diagrama', $j${"title":"Diagrama 3.1 · La evolución a 1FN","component":"NetworkDiagram","props":{"label":"De atributo multivalorado a entidad propia (1:N)","ancho":520,"alto":372,"grupos":[{"id":"antes","x":14,"y":34,"w":492,"h":128,"titulo":"ANTES — viola 1FN","descripcion":"El atributo 'aulas' guarda una LISTA dentro de una celda: imposible filtrar por aula, contar aulas o relacionarlas con horarios."},{"id":"despues","x":14,"y":192,"w":492,"h":156,"titulo":"DESPUÉS — 1FN","descripcion":"El multivalorado se mudó a su propia entidad AULA, relacionada 1:N con EDIFICIO. Cada celda, un valor; cada aula, consultable."}],"nodos":[{"id":"edif1","x":34,"y":76,"w":200,"h":48,"titulo":"EDIFICIO","subtitulo":"# edificio_id · * nombre","descripcion":"La entidad original, correcta en sus otros atributos."},{"id":"aulas","x":268,"y":76,"w":222,"h":48,"titulo":"aulas: A101, A102, B201…","tag":"multivalorado","descripcion":"El infractor: una lista apretujada en una celda. La 1FN exige un valor atómico — esta celda guarda tres."},{"id":"edif2","x":34,"y":238,"w":200,"h":52,"titulo":"EDIFICIO","subtitulo":"# edificio_id · * nombre","descripcion":"Tras la evolución: EDIFICIO conserva lo suyo, sin listas."},{"id":"aula","x":286,"y":238,"w":204,"h":52,"titulo":"AULA","subtitulo":"# aula_id · | edificio · * codigo","descripcion":"La nueva entidad: cada aula es una instancia con su código atómico. Nota la barra: su UID depende de la relación con EDIFICIO (módulo 2 en acción)."}],"enlaces":[{"de":"edif2","a":"aula","tipo":"flecha","etiqueta":"1:N","descripcion":"Un edificio tiene muchas aulas; cada aula pertenece a un edificio. La lista se volvió relación — y ahora se consulta, se cuenta y se filtra."}],"hint":"Toca el infractor de arriba y la solución de abajo."},"caption":"La cura de 1FN es siempre la misma cirugía: el multivalorado se muda a su propia entidad, relacionada 1:N. Los grupos repetitivos (aula1, aula2, aula3…) reciben idéntico tratamiento."}$j$),
  (3, 'ejemplo_sql', $j${"title":"Por qué la celda-lista no se puede consultar","code":"-- Con la celda multivalorada (viola 1FN), esto es una pesadilla:\n--   'aulas' = 'A101, A102, B201'  →  ¿cómo filtro por B201?\n\n-- Tras la evolución a 1FN, es SQL de primer día:\nSELECT e.nombre AS edificio, a.codigo AS aula\nFROM   edificio e\nJOIN   aula a ON a.edificio_id = e.edificio_id\nWHERE  a.codigo = 'B201';","result":{"columns":["EDIFICIO","AULA"],"rows":[["Pabellón B","B201"]],"note":"Cada aula es una fila: filtrable, contable, relacionable. La celda-lista no permitía ninguna de las tres."},"caption":"1FN no es purismo: es la diferencia entre poder consultar tus datos o excavarlos con cadenas de texto."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Una tabla PACIENTE tiene la columna telefonos con valores como '555-1234, 555-5678'. ¿Qué forma normal viola y por qué?","options":["2FN, por dependencia parcial","1FN: el atributo no es ATÓMICO — guarda varios valores en una celda (multivalorado)","3FN, por dependencia transitiva","Ninguna: es práctico"],"correctIndex":1,"feedback":{"correct":"Correcto. La celda-lista viola la atomicidad de 1FN: los teléfonos merecen su propia entidad 1:N.","incorrect":"Varios valores en una celda = atributo multivalorado = violación de 1FN (atomicidad)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Para 'cumplir' 1FN, alguien reemplaza la celda-lista por las columnas telefono1, telefono2, telefono3. En términos técnicos eso es…","options":["Una solución correcta","Un GRUPO REPETITIVO: disfraza la violación — ¿y el teléfono 4? ¿y cómo consultas 'todos los teléfonos'? La cura real es la entidad 1:N","Tercera Forma Normal","Un UID compuesto"],"correctIndex":1,"feedback":{"correct":"Correcto. Columnas clonadas = el mismo problema con corbata. La entidad TELEFONO_PACIENTE 1:N es la cirugía real.","incorrect":"telefono1..telefono3 es un grupo repetitivo: límite artificial y consultas imposibles. 1FN pide la entidad aparte."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — 1FN","points":["1FN = ATOMICIDAD: cada atributo, UN valor indivisible por instancia.","Enemigo 1: el atributo multivalorado (la celda-lista 'A101, A102…').","Enemigo 2: el grupo repetitivo (aula1, aula2, aula3 — el disfraz del mismo problema).","La cura universal: mudar el multivalorado a su PROPIA entidad, relacionada 1:N.","Violar 1FN mata la consultabilidad: no filtras, no cuentas, no relacionas lo que vive en una celda."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-l03-1fn';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Segunda Forma Normal
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"2FN: depender del UID completo","body":"La SEGUNDA FORMA NORMAL entra en escena cuando el UID es COMPUESTO (módulo 2). La regla: todo atributo que no forme parte del UID debe depender de la TOTALIDAD del identificador — DEPENDENCIA COMPLETA — y no de un pedazo. Si un atributo depende solo de UNA PARTE del UID compuesto (DEPENDENCIA PARCIAL), está viviendo en la entidad equivocada. El caso clásico: la entidad SURTIDO con UID compuesto (proveedor_id + producto_id) y el atributo nombre_proveedor. ¿De qué depende ese nombre? Solo de proveedor_id — le da igual el producto. Resultado: el nombre se repite en cada producto del proveedor… y ya conoces las tres anomalías que despiertan. La cura: el atributo parcial SE MUDA a la entidad de la parte de la que depende (nombre_proveedor → PROVEEDOR)."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La dependencia parcial, cazada con datos","code":"-- SURTIDO: UID compuesto (proveedor_id + producto_id)\nSELECT proveedor_id, producto_id, nombre_proveedor, precio\nFROM   surtido\nORDER  BY proveedor_id, producto_id;","result":{"columns":["PROVEEDOR_ID","PRODUCTO_ID","NOMBRE_PROVEEDOR","PRECIO"],"rows":[["V7","P01","MediSupply SA","120"],["V7","P02","MediSupply SA","45"],["V7","P03","MediSupply SA","80"],["V9","P04","Insumos Andinos","300"]],"note":"nombre_proveedor se repite EXACTO en cada fila de V7: depende solo de proveedor_id (parcial). precio sí depende del par completo: cada proveedor pone su precio a cada producto — ese se queda."},"caption":"La prueba del oficio: pregunta a cada atributo '¿de cuánto UID dependes?'. El que responda 'de una parte' se muda; el que dependa del par completo, se queda."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"La 2FN solo puede violarse cuando…","options":["La tabla tiene muchas filas","El UID es COMPUESTO: solo entonces un atributo puede depender de una PARTE del identificador en vez de su totalidad","Hay valores nulos","La tabla no tiene índices"],"correctIndex":1,"feedback":{"correct":"Correcto. Con UID simple no hay 'partes' de las que depender: la 2FN es la regla de los UID compuestos.","incorrect":"La dependencia parcial requiere un UID con partes — es decir, compuesto. Con UID simple, 2FN se cumple sola."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En SURTIDO (UID: proveedor_id + producto_id), el atributo precio (lo que ESE proveedor cobra por ESE producto) y el atributo nombre_proveedor. ¿Cuál viola 2FN?","options":["precio: depende del par completo","nombre_proveedor: depende SOLO de proveedor_id (dependencia parcial) — debe mudarse a la entidad PROVEEDOR","Ambos","Ninguno"],"correctIndex":1,"feedback":{"correct":"Correcto. precio necesita al par (dependencia completa): se queda. El nombre ignora al producto: se muda.","incorrect":"Pregunta a cada uno de qué depende: precio → del par (se queda); nombre_proveedor → solo del proveedor (parcial: se muda)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En una entidad NOTA con UID compuesto (alumno_id + curso_id), el atributo nombre_alumno viola 2FN. La cura correcta es…","options":["Borrar el atributo del sistema","MUDARLO a la entidad ALUMNO (la parte de la que depende): la nota se queda con lo que depende del par completo, como la calificación","Duplicarlo también en CURSO","Convertir el UID en simple"],"correctIndex":1,"feedback":{"correct":"Correcto. Cada atributo a la entidad de la que realmente depende: nombre_alumno → ALUMNO; calificación → se queda (depende del par).","incorrect":"La cura de la dependencia parcial es la mudanza: el atributo va a la entidad de la parte que lo determina."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — 2FN","points":["2FN aplica a UIDs COMPUESTOS: todo atributo no-UID debe depender del identificador COMPLETO.","Dependencia COMPLETA: necesita todas las partes (precio depende de proveedor+producto).","Dependencia PARCIAL: depende de un pedazo (nombre_proveedor solo mira a proveedor_id) — violación.","La cura: mudar el atributo parcial a la entidad de la parte que lo determina.","El síntoma visible: el mismo valor repitiéndose en bloque — la redundancia de siempre."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-l04-2fn';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Tercera Forma Normal
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"3FN: un atributo no puede tener atributos propios","body":"La TERCERA FORMA NORMAL caza a la DEPENDENCIA TRANSITIVA: un atributo no-UID que depende de OTRO atributo no-UID (y solo a través de él, del UID). La formulación coloquial del oficio es imbatible: 'un atributo no puede tener atributos propios'. Caso clásico: la entidad CD de una cadena de tiendas guarda tienda_id… y también direccion_tienda. ¿De qué depende esa dirección? No del CD: de la TIENDA — cd_id → tienda_id → direccion_tienda es la cadena transitiva. Resultado: la dirección se repite en cada CD de la tienda, y si la tienda se muda, redundancia masiva que actualizar. En el hospital: CITA que guarda medico_id y también telefono_medico — el teléfono es atributo DEL MÉDICO, no de la cita. La cura de siempre: el atributo transitivo se muda a su dueño real (TIENDA, MEDICO), que queda conectado por la relación."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La transitiva, vista en las filas","code":"-- CITA guardando un atributo que no es suyo:\nSELECT cita_id, medico_id, telefono_medico, fecha\nFROM   cita\nWHERE  medico_id = 9;","result":{"columns":["CITA_ID","MEDICO_ID","TELEFONO_MEDICO","FECHA"],"rows":[["501","9","555-0909","12/03/2026"],["502","9","555-0909","04/05/2026"],["505","9","555-0909","01/01/2026"]],"note":"cita_id → medico_id → telefono_medico: la cadena transitiva. El teléfono se repite en cada cita del Dr. 9 — y el día que cambie, ¿cuántas citas quedarán mintiendo?"},"caption":"El interrogatorio de 3FN: '¿dependes del UID de ESTA entidad… o de otro atributo?'. telefono_medico confiesa: depende de medico_id. Se muda a MEDICO."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"La formulación coloquial de la 3FN es…","options":["Cada celda un solo valor","'Un atributo no puede tener atributos propios': ningún atributo no-UID puede depender de otro atributo no-UID (dependencia transitiva)","Todo depende del UID completo","Las tablas deben tener PK"],"correctIndex":1,"feedback":{"correct":"Correcto. Si un atributo 'cuelga' de otro atributo (y no del UID), ese otro es una entidad disfrazada.","incorrect":"3FN prohíbe la dependencia transitiva: atributo no-UID dependiendo de otro no-UID. 'Un atributo sin atributos propios'."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En la entidad CD hay tienda_id y direccion_tienda. La cadena cd_id → tienda_id → direccion_tienda delata…","options":["Una dependencia completa correcta","Una dependencia TRANSITIVA (violación de 3FN): la dirección depende de la tienda, no del CD — se muda a la entidad TIENDA","Un atributo multivalorado","Un UID artificial"],"correctIndex":1,"feedback":{"correct":"Correcto. El CD conserva su tienda_id (la relación); la dirección vive con su dueño real: TIENDA.","incorrect":"Depender del UID solo A TRAVÉS de otro atributo = transitiva = violación de 3FN. La dirección pertenece a TIENDA."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Detectas que EMPLEADO guarda departamento_id y también nombre_departamento y piso_departamento. Tras normalizar a 3FN, ¿qué queda en EMPLEADO?","options":["Todo igual","Solo departamento_id (la relación): nombre y piso se mudan a la entidad DEPARTAMENTO, su dueño real","Nada relacionado con departamentos","El piso, pero no el nombre"],"correctIndex":1,"feedback":{"correct":"Correcto. La relación se queda (la FK del físico); los atributos del departamento viven con el departamento.","incorrect":"EMPLEADO conserva la referencia (departamento_id); los atributos transitivos (nombre, piso) se mudan a DEPARTAMENTO."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — 3FN","points":["3FN prohíbe la dependencia TRANSITIVA: atributo no-UID que depende de otro no-UID.","La frase del oficio: 'un atributo no puede tener atributos propios'.","La cadena delatora: uid → atributo_puente → atributo_colgado (cd → tienda → dirección).","La cura: mudar los colgados a su dueño real; la entidad original conserva solo la referencia.","El atributo-puente era una entidad disfrazada pidiendo existir (TIENDA, MEDICO, DEPARTAMENTO)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-l05-3fn';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · El panorama: 1FN a 3FN (y más allá)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Las tres reglas, lado a lado","body":"El mapa completo para el bolsillo. 1FN — pregunta: ¿cada celda tiene UN valor atómico? — infractor típico: la celda-lista o el grupo repetitivo — cura: entidad nueva 1:N. 2FN — pregunta (solo con UID compuesto): ¿cada atributo depende del UID COMPLETO? — infractor: la dependencia parcial (nombre_proveedor en SURTIDO) — cura: mudanza a la entidad de la parte. 3FN — pregunta: ¿algún atributo depende de OTRO atributo en vez del UID? — infractor: la transitiva (direccion_tienda en CD) — cura: mudanza al dueño real. Memoriza la progresión con la frase clásica del oficio: cada atributo debe depender de la llave (1FN), de toda la llave (2FN) y de nada más que la llave (3FN). Para este curso — y para la enorme mayoría de los sistemas del mundo — llegar a 3FN ES estar normalizado; existe un refinamiento adicional (BCNF) para casos raros de UIDs solapados que conocerás si sigues la ruta académica."}$j$),
  (2, 'texto', $j${"title":"Normalizar es lógico; desnormalizar es físico","body":"Precisión final que separa niveles — y que las entrevistas usan de trampa. La NORMALIZACIÓN es una disciplina del modelo LÓGICO: garantiza integridad organizando dónde vive cada dependencia. La DESNORMALIZACIÓN — duplicar deliberadamente un dato para ahorrar joins — es una decisión de OPTIMIZACIÓN FÍSICA: se toma (si acaso) al final, sobre un sistema medido, con evidencia de que un join concreto duele, y aceptando por escrito el costo (reintroduces la redundancia y sus anomalías, y ahora te toca gestionarlas). Confundir los planos — 'diseñemos desnormalizado desde el inicio para que sea rápido' — es el error del aficionado: optimiza un problema que aún no existe pagando con inconsistencias que sí existirán. El orden profesional: modela normalizado, mide en producción, y desnormaliza solo donde los números lo exijan."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"La progresión clásica que resume 1FN, 2FN y 3FN es: cada atributo debe depender…","options":["De un índice, de una vista y de un trigger","De la llave (1FN), de TODA la llave (2FN) y de NADA MÁS que la llave (3FN)","Del nombre de la tabla","Del orden de las columnas"],"correctIndex":1,"feedback":{"correct":"Correcto. La frase del oficio: the key, the whole key, and nothing but the key.","incorrect":"La progresión: de la llave (atomicidad y pertenencia), de toda la llave (sin parciales), y de nada más que la llave (sin transitivas)."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un arquitecto propone 'diseñar desnormalizado desde el inicio, para ganar velocidad'. La objeción profesional correcta:","options":["La velocidad no importa","Confunde los planos: la normalización es diseño LÓGICO (integridad); la desnormalización es optimización FÍSICA que se decide al final, con mediciones — y aceptando el costo de reintroducir redundancia","Desnormalizar es ilegal en Oracle","Tiene razón: los joins siempre son lentos"],"correctIndex":1,"feedback":{"correct":"Correcto. Modela normalizado → mide → desnormaliza solo donde la evidencia lo exija, gestionando el costo.","incorrect":"Normalizar (lógico, integridad) ≠ desnormalizar (físico, optimización medida). Optimizar problemas inexistentes cuesta inconsistencias reales."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Una tabla con UID SIMPLE, celdas atómicas, y un atributo que depende de otro atributo no-UID. ¿Qué formas cumple y cuál viola?","options":["Viola 1FN","Cumple 1FN (celdas atómicas) y 2FN (UID simple: sin parciales posibles); VIOLA 3FN (dependencia transitiva)","Viola 2FN","Las cumple todas"],"correctIndex":1,"feedback":{"correct":"Correcto. El diagnóstico por capas: atomicidad ✓, UID simple hace 2FN automática ✓, la transitiva rompe 3FN ✗.","incorrect":"Celdas atómicas = 1FN ✓; UID simple = 2FN gratis ✓; atributo colgado de otro atributo = transitiva = 3FN ✗."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — El panorama","points":["1FN: de la llave (atomicidad) · 2FN: de TODA la llave (sin parciales) · 3FN: de NADA MÁS que la llave (sin transitivas).","Para casi todo sistema real, 3FN = normalizado (BCNF es el refinamiento para casos raros).","Normalización = disciplina del modelo LÓGICO (integridad).","Desnormalización = optimización FÍSICA: al final, con mediciones, aceptando el costo.","El orden profesional: modela normalizado → mide → desnormaliza solo con evidencia."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-l06-panorama';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Práctica: el diagnóstico (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"El hospital heredó tablas de un sistema viejo y te contrató para el diagnóstico: identificar qué forma normal viola cada una (o qué anomalía la aqueja). El caso 1 viene resuelto; completa los demás reemplazando cada ?.","instructions":["Caso 2 — SURTIDO con UID compuesto (proveedor_id + producto_id) guarda nombre_proveedor. ¿1fn, 2fn o 3fn?","Caso 3 — CITA (UID simple cita_id) guarda medico_id y también telefono_medico. ¿1fn, 2fn o 3fn?","Caso 4 — Al borrar el último producto del proveedor V9, el proveedor y su contacto desaparecieron del sistema. ¿insercion, actualizacion o eliminacion?","Escribe las respuestas en minúsculas, tal como aparecen en las opciones."],"initialCode":"-- HOJA DE DIAGNÓSTICO — Sistema heredado\n\n-- Caso 1 (ejemplo): RECETA con columna\n--   'medicamentos = Paracetamol, Ibuprofeno, Omeprazol'\ncaso1_forma_violada=1fn\n\n-- Caso 2: SURTIDO (UID: proveedor_id + producto_id)\n--   guarda nombre_proveedor\ncaso2_forma_violada=?\n\n-- Caso 3: CITA (UID simple: cita_id)\n--   guarda medico_id y telefono_medico\ncaso3_forma_violada=?\n\n-- Caso 4: borrar el último producto de V9 borró\n--   al proveedor y su contacto\ncaso4_anomalia=?","validators":["caso2_forma_violada\\s*=\\s*2fn\\b","caso3_forma_violada\\s*=\\s*3fn\\b","caso4_anomalia\\s*=\\s*eliminacion\\b"],"mockOutput":{"columns":["CASO","DIAGNÓSTICO","POR QUÉ"],"rows":[["1 · RECETA","1FN","celda-lista: el atributo no es atómico → entidad 1:N"],["2 · SURTIDO","2FN","nombre_proveedor depende SOLO de proveedor_id (parcial) → se muda a PROVEEDOR"],["3 · CITA","3FN","telefono_medico depende de medico_id, no del UID (transitiva) → se muda a MEDICO"],["4 · borrado V9","ELIMINACIÓN","borrar un hecho arrastró información que debía conservarse"]],"note":"Diagnóstico completo: las tres formas y una anomalía, cazadas con el interrogatorio de dependencias."},"hints":["Caso 2: el UID es compuesto y el atributo ignora a una de las partes → dependencia PARCIAL.","Caso 3: el UID es simple (2FN gratis); el teléfono cuelga de OTRO atributo (medico_id) → dependencia TRANSITIVA.","Caso 4: un DELETE legítimo se llevó datos que debían sobrevivir — la anomalía de eliminación (escríbela sin tilde: eliminacion)."],"successMessage":"Diagnóstico entregado: identificaste la celda-lista (1FN), la dependencia parcial (2FN), la transitiva (3FN) y la anomalía de eliminación. Este interrogatorio de dependencias es el que aplicarás a toda tabla heredada que encuentres en tu carrera.","failMessage":"Revisa el interrogatorio: caso2=2fn (parcial en UID compuesto) · caso3=3fn (transitiva: atributo colgado de otro atributo) · caso4=eliminacion (el borrado arrastró información)."}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-l07-practica-diagnostico';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La tercera región","body":"Byte llegó a la región de la normalización: once preguntas guardan el paso. Todo lo viviste: las dependencias funcionales, las tres anomalías con nombre, las tres formas normales con sus infractores y sus curas, y la frontera entre lo lógico y lo físico. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"La meta de la normalización, en una frase:","options":["Tablas con pocas columnas","Almacenar cada información en UN SOLO lugar, y en el MEJOR lugar posible","Bases de datos pequeñas","Consultas sin joins"],"correctIndex":1,"feedback":{"correct":"Correcto. Un lugar, el mejor: la integridad como principio de organización.","incorrect":"Normalizar organiza dónde vive cada dependencia: cada información en un solo lugar, el mejor posible."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"medico_id → colegiatura se lee: conociendo el médico, su colegiatura queda determinada. Ese concepto es…","options":["Una clave primaria","Una DEPENDENCIA FUNCIONAL: la herramienta de análisis de toda la normalización","Un join","Una anomalía"],"correctIndex":1,"feedback":{"correct":"Correcto. A → B: fijado A, B es uno solo. El mapa de 'qué pertenece a qué'.","incorrect":"Es una dependencia funcional (A determina B): con ellas se diagnostican las tres formas normales."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"No puedes registrar al proveedor nuevo 'BioLab' porque la tabla exige que tenga un producto. Anomalía de…","options":["Eliminación","Actualización","INSERCIÓN: el diseño impide registrar un hecho real sin inventar otro","Consulta"],"correctIndex":2,"feedback":{"correct":"Correcto. El hecho es legítimo; el diseño lo rechaza: anomalía de inserción.","incorrect":"No poder INSERTAR lo real sin inventar lo inexistente = anomalía de inserción."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"El teléfono de un proveedor está copiado en 40 filas y cambia. Si la corrección deja 3 filas viejas, el sistema queda inconsistente. Esa vulnerabilidad se llama anomalía de…","options":["ACTUALIZACIÓN: un cambio real exige tocar muchas filas, con riesgo de quedar a medias","Inserción","Eliminación","Atomicidad"],"correctIndex":0,"feedback":{"correct":"Correcto. Un hecho, muchas filas, inconsistencia esperando: la hija predilecta de la redundancia.","incorrect":"Cambio múltiple con riesgo de inconsistencia = anomalía de actualización."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"La columna 'aulas' de EDIFICIO guarda 'A101, A102, B201'. Forma violada y cura:","options":["3FN; borrar la columna","1FN (atributo multivalorado: sin atomicidad); la cura es mudarlo a una entidad AULA relacionada 1:N","2FN; hacer el UID simple","Ninguna"],"correctIndex":1,"feedback":{"correct":"Correcto. La celda-lista viola la atomicidad: cirugía de entidad nueva 1:N (el Diagrama 3.1).","incorrect":"Varios valores en una celda = 1FN violada. La lista se convierte en entidad AULA 1:N."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Reemplazar la celda-lista por las columnas aula1, aula2, aula3 'resuelve' 1FN. La evaluación técnica correcta:","options":["Solución perfecta","Es un GRUPO REPETITIVO: disfraza la violación con un límite artificial y consultas imposibles — la entidad 1:N sigue siendo la cura","Ahora viola 2FN","Es más rápido que un join"],"correctIndex":1,"feedback":{"correct":"Correcto. Columnas clonadas = el problema con corbata: ¿aula4? ¿'todas las aulas del edificio B'?","incorrect":"aula1..aula3 es grupo repetitivo: mismo mal, nueva máscara. 1FN pide la entidad aparte."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué una tabla con UID SIMPLE cumple 2FN automáticamente?","options":["Porque los UID simples son más rápidos","Porque la 2FN prohíbe depender de UNA PARTE del UID — y un UID sin partes no ofrece pedazos de los que depender","Porque 2FN solo aplica a Oracle","No la cumple automáticamente"],"correctIndex":1,"feedback":{"correct":"Correcto. Sin partes no hay dependencia parcial posible: la 2FN es la regla de los UID compuestos.","incorrect":"La dependencia parcial necesita un UID con partes (compuesto). Con UID simple, 2FN viene gratis."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"En CITA (UID simple) viven medico_id y telefono_medico. La cadena cita_id → medico_id → telefono_medico viola…","options":["1FN","2FN","3FN: dependencia TRANSITIVA — el teléfono es atributo del médico y se muda a la entidad MEDICO","Ninguna"],"correctIndex":2,"feedback":{"correct":"Correcto. 'Un atributo no puede tener atributos propios': el teléfono cuelga de medico_id, no del UID.","incorrect":"Atributo no-UID dependiendo de otro no-UID = transitiva = 3FN. Se muda a su dueño real (MEDICO)."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"La progresión que resume las tres formas: cada atributo debe depender de…","options":["la llave, toda la llave y nada más que la llave (1FN, 2FN, 3FN)","la tabla, el esquema y el usuario","el índice, la vista y el trigger","la fila, la columna y la celda"],"correctIndex":0,"feedback":{"correct":"Correcto. La frase del oficio — y la respuesta que abre puertas en entrevistas.","incorrect":"De la llave (1FN) → de toda la llave (2FN) → de nada más que la llave (3FN)."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"'Desnormalicemos desde el diseño para evitar joins lentos.' El error conceptual de la propuesta:","options":["Los joins no existen en Oracle","Confunde planos: normalizar es diseño LÓGICO (integridad); desnormalizar es optimización FÍSICA que se decide al final, con mediciones y aceptando el costo de la redundancia","Desnormalizar es imposible","Ninguno: es correcta"],"correctIndex":1,"feedback":{"correct":"Correcto. Optimizar un problema aún inexistente, pagando con inconsistencias reales: el error del aficionado.","incorrect":"Normalización lógica ≠ optimización física: modela normalizado, mide, y desnormaliza solo donde la evidencia lo exija."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'nuestra tabla de citas guarda también el nombre y el teléfono del paciente, así evitamos un join en la pantalla principal. ¿Lo dejamos así?' Tu respuesta senior:","options":["Sí: los joins siempre son el enemigo","No como diseño: viola 3FN (transitivas) y compra las tres anomalías. El modelo se normaliza; si LUEGO la métrica demuestra que ese join concreto duele, se evalúa desnormalizar como decisión física puntual, medida y documentada","Sí, pero solo los viernes","No: hay que borrar el teléfono del sistema"],"correctIndex":1,"feedback":{"correct":"Impecable. Integridad por defecto, optimización con evidencia: el orden profesional que separa arquitectos de aficionados.","incorrect":"La respuesta senior: normalizar primero (el diseño lógico protege la integridad); desnormalizar después SOLO si las mediciones del sistema real lo justifican — decisión física, puntual y documentada."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm03-x01-examen';
