-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 017 — SQL con Oracle · m04: DDL en Oracle
-- ═══════════════════════════════════════════════════════════════════
-- Cubre la Parte VII (integridad: las cinco constraints, nivel
-- columna vs tabla, acciones referenciales, declarativas ANTES que
-- triggers, activar/desactivar) y la Parte X en su tramo DDL
-- (CREATE TABLE y tipos de datos, ALTER, DELETE vs TRUNCATE vs DROP,
-- vistas, secuencias y sinónimos). DDL/DML/DCL/TCL como mapa inicial.
-- Precisiones vinculantes: distinguir DDL/DML/DCL/TCL; el DDL hace
-- COMMIT IMPLÍCITO; TRUNCATE es DDL y NO se revierte con ROLLBACK;
-- las secuencias DEJAN HUECOS (unicidad sí, continuidad no);
-- constraints declarativas ANTES que triggers; UNIQUE admite nulos.
-- Práctica de editor (regex+mockOutput): DDL real de la tabla LOTES.
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- OJO: SQL con Oracle está PUBLICADO — esta migración sale en vivo.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 011 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm04-ddl-oracle'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m04-l01-lenguajes',           'Las cuatro familias del SQL',        'leccion',  20, 1),
       ('m04-l02-create-tipos',        'CREATE TABLE y los tipos de datos',  'leccion',  20, 2),
       ('m04-l03-constraints',         'Constraints: la integridad declarada','leccion', 20, 3),
       ('m04-l04-alter-truncate',      'ALTER, TRUNCATE y DROP',             'leccion',  20, 4),
       ('m04-l05-vistas',              'Vistas: la consulta con nombre',     'leccion',  20, 5),
       ('m04-l06-secuencias-sinonimos','Secuencias y sinónimos',             'leccion',  20, 6),
       ('m04-l07-practica-ddl',        'Práctica: tu primer DDL completo',   'practica', 20, 7),
       ('m04-x01-examen',              'Examen: DDL en Oracle',              'examen',   40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm04-ddl-oracle';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Las cuatro familias del SQL
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Un idioma, cuatro familias","body":"Todo lo que se le dice a Oracle pertenece a una de CUATRO familias, y distinguirlas es pregunta segura de certificación y entrevista. DDL — Data Definition Language: define ESTRUCTURAS (CREATE, ALTER, DROP, TRUNCATE, RENAME). DML — Data Manipulation Language: manipula FILAS dentro de esas estructuras (INSERT, UPDATE, DELETE, MERGE — y SELECT, que algunos catálogos listan aparte como lenguaje de consulta). DCL — Data Control Language: administra PERMISOS (GRANT, REVOKE). TCL — Transaction Control Language: gobierna TRANSACCIONES (COMMIT, ROLLBACK, SAVEPOINT). La pista para no confundirlas: pregúntate sobre QUÉ actúa la orden — ¿estructuras, filas, permisos o transacciones? TRUNCATE, que vacía filas, parece DML… y es DDL: actúa sobre la estructura ('deja esta tabla como recién creada'), y esa clasificación tiene una consecuencia que verás en un minuto."}$j$),
  (2, 'texto', $j${"title":"La regla oculta del DDL","body":"Cada orden DDL ejecuta un COMMIT IMPLÍCITO: antes y después de correr, confirma definitivamente todo el trabajo pendiente de tu sesión — sin preguntarte. Ejecutas veinte INSERTs sin confirmar, luego un inocente CREATE TABLE… y los veinte INSERTs quedaron confirmados para siempre: el ROLLBACK que pensabas tener disponible ya no puede deshacerlos. Esta regla explica el comportamiento más traicionero del lenguaje: TRUNCATE es DDL, así que vaciar una tabla con TRUNCATE se confirma en el acto — NO se revierte con ROLLBACK, a diferencia de un DELETE (DML), que sí. El manejo fino de transacciones tiene su propio módulo más adelante; por ahora, graba la ley: DDL = compromiso inmediato e irreversible."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Clasifica estas órdenes SQL: GRANT, CREATE TABLE, UPDATE, COMMIT.","options":["DML · DDL · DCL · TCL en ese orden","DDL · DCL · TCL · DML en ese orden","DCL · DDL · DML · TCL en ese orden","Todas son en realidad de tipo DDL"],"correctIndex":2,"feedback":{"correct":"Correcto. GRANT administra permisos (DCL), CREATE define estructura (DDL), UPDATE toca filas (DML), COMMIT confirma la transacción (TCL).","incorrect":"La pista es sobre qué actúa cada una: GRANT→permisos (DCL), CREATE TABLE→estructura (DDL), UPDATE→filas (DML), COMMIT→transacción (TCL)."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es el COMMIT IMPLÍCITO del DDL?","options":["Un permiso especial que da el administrador","Un COMMIT que se ejecuta una vez cada hora","Es solamente un sinónimo de SAVEPOINT","El DDL confirma lo pendiente sin preguntar"],"correctIndex":3,"feedback":{"correct":"Correcto. DDL = compromiso inmediato: lo pendiente se confirma antes y después de la orden.","incorrect":"El DDL confirma la transacción pendiente automáticamente — la razón por la que TRUNCATE no se revierte con ROLLBACK."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta con trampa de certificación: TRUNCATE vacía todas las filas de una tabla. ¿A qué familia pertenece?","options":["DDL: actúa sobre la estructura de la tabla","DML, porque en el fondo toca las filas","DCL, porque necesita permisos previos","TCL, porque confirma la transacción activa"],"correctIndex":0,"feedback":{"correct":"Correcto. La trampa clásica: parece DML por vaciar filas, pero es DDL — con todas las consecuencias.","incorrect":"TRUNCATE es DDL aunque borre filas: redefine la tabla a su estado recién creado, hace commit implícito y es irreversible con ROLLBACK."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Las cuatro familias","points":["DDL define estructuras: CREATE, ALTER, DROP, TRUNCATE, RENAME.","DML manipula filas: INSERT, UPDATE, DELETE, MERGE (y SELECT consulta).","DCL administra permisos: GRANT, REVOKE · TCL gobierna transacciones: COMMIT, ROLLBACK, SAVEPOINT.","El DDL hace COMMIT IMPLÍCITO: confirma lo pendiente sin preguntar.","TRUNCATE es DDL (no DML): vaciar con TRUNCATE NO se revierte con ROLLBACK."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-l01-lenguajes';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · CREATE TABLE y los tipos de datos
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El momento de la verdad","body":"Módulos enteros de modelado conducen a esta orden: CREATE TABLE convierte tu diseño en una estructura real. Su anatomía: el nombre de la tabla (con las reglas de nomenclatura que ya dominas), y entre paréntesis la lista de columnas — cada una con su NOMBRE, su TIPO DE DATOS y, opcionalmente, un valor DEFAULT (lo que Oracle escribe si el INSERT no trae ese dato) y sus restricciones. Elegir el tipo de cada columna no es un trámite: es la PRIMERA LÍNEA DE DEFENSA de la integridad — una columna DATE rechaza sola el texto 'mañana', y un NUMBER(8,2) jamás aceptará 'gratis'. El tipo correcto convierte a Oracle en tu primer validador."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La farmacia estrena catálogo","code":"CREATE TABLE medicamentos (\n  medicamento_id  NUMBER(6)     CONSTRAINT med_pk PRIMARY KEY,\n  nombre          VARCHAR2(80)  NOT NULL,\n  clave_sanitaria CHAR(8),\n  precio          NUMBER(8,2)   DEFAULT 0 NOT NULL,\n  refrigerado     CHAR(1)       DEFAULT 'N'\n                  CONSTRAINT med_refri_ck CHECK (refrigerado IN ('S','N')),\n  caducidad       DATE          NOT NULL,\n  ficha_tecnica   CLOB\n);\n\nCOMMENT ON TABLE medicamentos IS 'Catálogo de farmacia del hospital';","result":{"columns":["RESULTADO"],"rows":[["Table MEDICAMENTOS created."],["Comment created."]],"note":"Cada columna declara nombre + tipo + (opcional) DEFAULT y restricciones. El DEFAULT trabaja solo: un INSERT que no mencione precio deja 0, y uno que no mencione refrigerado deja 'N'. COMMENT ON documenta la tabla dentro de la propia base."}}$j$),
  (3, 'texto', $j${"title":"Los tipos que usarás a diario","body":"VARCHAR2(n) — texto de longitud VARIABLE hasta n bytes: 'Ana' en un VARCHAR2(80) ocupa 3, no 80. CHAR(n) — longitud FIJA: rellena con espacios hasta n; solo tiene sentido para códigos de ancho constante (una clave de 8 siempre-8). La regla práctica: VARCHAR2 casi siempre. NUMBER(p,s) — número con PRECISIÓN p (total de dígitos) y ESCALA s (decimales): NUMBER(8,2) llega hasta 999999.99 — seis enteros, dos decimales. DATE — y aquí el clásico de examen: guarda fecha Y HORA (siglo, año, mes, día, hora, minuto, segundo), siempre. TIMESTAMP agrega fracciones de segundo cuando el instante exacto importa. Y los gigantes: CLOB para texto enorme (la ficha técnica completa), BLOB para binarios (la radiografía). Elegir tipo = declarar una regla de negocio que Oracle vigilará gratis en cada INSERT."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre VARCHAR2(20) y CHAR(20)?","options":["Ninguna: son exactamente sinónimos","VARCHAR2 ocupa lo real; CHAR rellena a fijo","CHAR acepta números y VARCHAR2 no los acepta","VARCHAR2 es una versión mucho más antigua"],"correctIndex":1,"feedback":{"correct":"Correcto. 'Ana' en VARCHAR2(20) son 3 bytes; en CHAR(20) son 20. El fijo solo paga cuando el ancho es constante por naturaleza.","incorrect":"VARCHAR2 = longitud variable (ocupa lo real); CHAR = fija (rellena con espacios). Regla práctica: VARCHAR2 casi siempre."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Una columna se declara NUMBER(8,2). ¿Qué significa exactamente?","options":["Tiene 8 decimales y 2 dígitos enteros","Admite solo números entre el 2 y el 8","8 dígitos en total, 2 de ellos decimales","Reserva 8 bytes de almacenamiento fijo"],"correctIndex":2,"feedback":{"correct":"Correcto. Precisión 8 (dígitos totales), escala 2 (decimales): seis enteros y dos decimales.","incorrect":"NUMBER(p,s): p dígitos en total, s de ellos decimales. NUMBER(8,2) → hasta 999999.99."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Clásico de examen: ¿qué guarda una columna de tipo DATE en Oracle?","options":["Solo la fecha: año, mes y día nada más","Únicamente la hora, sin ninguna fecha","Texto con un formato de fecha específico","Fecha y hora completas, siempre"],"correctIndex":3,"feedback":{"correct":"Correcto. DATE siempre lleva la hora dentro; TIMESTAMP agrega fracciones de segundo. Olvidarlo causa errores clásicos al comparar fechas.","incorrect":"DATE guarda fecha Y hora completas siempre. Que el formato de salida muestre solo la fecha no significa que la hora no esté ahí."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — CREATE TABLE y tipos","points":["CREATE TABLE materializa el diseño: columnas con nombre + tipo + DEFAULT + restricciones.","VARCHAR2 variable (casi siempre) · CHAR fijo con relleno (solo anchos constantes).","NUMBER(p,s): p dígitos totales, s decimales — NUMBER(8,2) llega a 999999.99.","DATE guarda fecha Y HORA siempre; TIMESTAMP suma fracciones de segundo; CLOB/BLOB para gigantes.","El tipo correcto es la primera línea de defensa: Oracle valida gratis en cada INSERT."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-l02-create-tipos';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Constraints: la integridad declarada
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Los cinco guardianes","body":"Oracle ofrece CINCO restricciones declarativas, y ya conoces la teoría de todas: NOT NULL (el * del modelo: la columna no admite vacío), UNIQUE (sin duplicados — y el recordatorio del módulo de identidad: ADMITE varios nulos, porque un nulo no es un valor que se repita), PRIMARY KEY (única + NOT NULL: el UID hecho llave), FOREIGN KEY (la relación: solo valores que existan en la PK o UNIQUE destino) y CHECK (una condición que cada fila debe cumplir: costo >= 0, estado IN ('S','N')). Se declaran en DOS niveles: a NIVEL COLUMNA — en la misma línea de la columna, para restricciones de una sola columna — o a NIVEL TABLA, al final del CREATE. La regla que decide: toda restricción que involucre DOS O MÁS columnas (una PK compuesta, una UNIQUE de tres columnas) SOLO puede declararse a nivel tabla — una línea de columna no puede hablar por sus vecinas."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La tabla CITAS, blindada","code":"CREATE TABLE citas (\n  cita_id      NUMBER(10)  CONSTRAINT cit_pk PRIMARY KEY,\n  paciente_id  NUMBER(6)   NOT NULL,\n  medico_id    NUMBER(6)   NOT NULL,\n  fecha        DATE        NOT NULL,\n  costo        NUMBER(8,2) CONSTRAINT cit_costo_ck CHECK (costo >= 0),\n  CONSTRAINT cit_pac_fk FOREIGN KEY (paciente_id)\n    REFERENCES pacientes (paciente_id),\n  CONSTRAINT cit_med_fk FOREIGN KEY (medico_id)\n    REFERENCES medicos (medico_id),\n  CONSTRAINT cit_agenda_uk UNIQUE (medico_id, fecha)\n);","result":{"columns":["RESULTADO"],"rows":[["Table CITAS created."]],"note":"Las restricciones de una columna viven en su línea (nivel columna: cit_pk, cit_costo_ck); las que necesitan hablar de varias — o se prefieren juntas al final — van a nivel tabla: las dos FKs y la UNIQUE compuesta que impide dos citas del mismo médico a la misma hora."}}$j$),
  (3, 'texto', $j${"title":"¿Y si borran al padre? (y la regla de oro)","body":"Una FK plantea la pregunta incómoda: ¿qué pasa si alguien borra al paciente que tiene citas? Por DEFECTO, Oracle RECHAZA el borrado — el padre con hijos no se toca. Dos alternativas se declaran en la FK: ON DELETE CASCADE (al borrar el padre, sus hijos se borran en cadena — útil para hijos que no significan nada sin él) y ON DELETE SET NULL (los hijos sobreviven con la FK en nulo — solo posible si la FK es opcional). Elegir es una regla de negocio más. Y la REGLA DE ORO de la integridad, que las entrevistas premian: toda regla que PUEDA declararse con una constraint, SE DECLARA — las declarativas van ANTES que los triggers. Una CHECK es más barata, está siempre activa, se ve en el diccionario y es imposible de esquivar; el trigger — código que se dispara ante eventos, lo verás en PL/SQL — queda para lo que las declarativas genuinamente no alcanzan."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres una restricción UNIQUE sobre la COMBINACIÓN de dos columnas (medico_id + fecha). ¿Dónde debe declararse?","options":["A nivel tabla, al final del CREATE","En la línea de cualquiera de las dos columnas","Dentro de un trigger de la tabla","Directamente en el código de la aplicación"],"correctIndex":0,"feedback":{"correct":"Correcto. La línea de una columna no puede hablar por sus vecinas: lo compuesto se declara al final, a nivel tabla.","incorrect":"Restricción de varias columnas → nivel tabla, siempre. El nivel columna solo alcanza para restricciones de esa columna."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Una FK se declara con ON DELETE CASCADE. ¿Qué significa?","options":["Que no se puede borrar nunca el padre","Borra en cadena las filas hijas del padre","Deja las FKs de los hijos puestas en nulo","Que la FK se desactiva al borrar el padre"],"correctIndex":1,"feedback":{"correct":"Correcto. CASCADE arrastra a los hijos. SET NULL los deja huérfanos con FK nula, y el defecto (sin cláusula) rechaza el borrado.","incorrect":"CASCADE = borrado en cadena. Las otras opciones existen pero con otro nombre: el defecto rechaza, y SET NULL anula la FK del hijo."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Regla de oro de la integridad: una regla de negocio puede implementarse como CHECK declarativa o como trigger. ¿Cuál va primero y por qué?","options":["El trigger, porque es una técnica más moderna","Ambas a la vez, en todos los casos siempre","La declarativa: barata, activa e inesquivable","Ninguna: eso se valida en la aplicación cliente"],"correctIndex":2,"feedback":{"correct":"Correcto. Declarativas ANTES que triggers: la respuesta que separa al que diseña integridad del que escribe código por reflejo.","incorrect":"La regla del oficio: si una constraint puede vigilar la regla, la constraint gana. El trigger es el plan B para lo inalcanzable."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Constraints","points":["Cinco guardianes: NOT NULL, UNIQUE (admite varios nulos), PRIMARY KEY, FOREIGN KEY, CHECK.","Nivel columna para restricciones de una columna; NIVEL TABLA obligatorio para las de varias (PK/UNIQUE compuestas).","Al borrar el padre: defecto = rechazo · ON DELETE CASCADE = hijos en cadena · ON DELETE SET NULL = FK nula (si es opcional).","Regla de oro: declarativas ANTES que triggers — más baratas, siempre activas, imposibles de esquivar.","Cada constraint con nombre propio (cit_pk, cit_costo_ck): los errores se entienden solos."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-l03-constraints';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · ALTER, TRUNCATE y DROP
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Las tablas también evolucionan","body":"El SDLC lo advirtió: los requisitos cambian, y ALTER TABLE es la herramienta para que el esquema cambie con ellos sin tirar nada. Sus movimientos: ADD agrega columnas o constraints nuevas; MODIFY cambia tipo, tamaño o DEFAULT de una columna (con límites sensatos: no puedes encoger un VARCHAR2 por debajo de lo que ya contiene); DROP COLUMN elimina una columna con sus datos; y RENAME COLUMN renombra. Además, las constraints tienen INTERRUPTOR: ALTER TABLE … DISABLE CONSTRAINT la apaga y ENABLE la reenciende. ¿Para qué apagar la integridad? El caso clásico es la CARGA MASIVA: desactivar la FK, cargar diez millones de filas históricas ya validadas, y reactivar con ENABLE VALIDATE — que revisa TODO lo cargado antes de dar el visto bueno. El interruptor es herramienta de administración, no una puerta trasera: siempre se reenciende validando."}$j$),
  (2, 'ejemplo_sql', $j${"title":"CITAS evoluciona sin perder una fila","code":"ALTER TABLE citas ADD (motivo VARCHAR2(200));\n\nALTER TABLE citas MODIFY (motivo VARCHAR2(400));\n\nALTER TABLE citas ADD CONSTRAINT cit_fecha_ck\n  CHECK (fecha >= DATE '2020-01-01');\n\nALTER TABLE citas DISABLE CONSTRAINT cit_agenda_uk;\n-- …carga masiva del histórico ya validado…\nALTER TABLE citas ENABLE VALIDATE CONSTRAINT cit_agenda_uk;","result":{"columns":["RESULTADO"],"rows":[["Table CITAS altered."],["Table CITAS altered."],["Table CITAS altered."],["Table CITAS altered."],["Table CITAS altered."]],"note":"La tabla ganó una columna, la agrandó, estrenó una CHECK y apagó/reencendió su UNIQUE para una carga masiva — todo con los datos existentes intactos. ENABLE VALIDATE revisa lo cargado antes de aceptar."}}$j$),
  (3, 'texto', $j${"title":"Tres maneras de destruir (elige con cuidado)","body":"Tres órdenes eliminan a escalas muy distintas, y confundirlas cuesta caro. DELETE (DML): borra FILAS, admite WHERE para elegir cuáles, es reversible con ROLLBACK mientras no confirmes — y siempre se escribe con su WHERE pensado, porque un DELETE sin WHERE arrasa la tabla entera fila por fila. TRUNCATE (DDL): vacía TODAS las filas de golpe, sin WHERE posible, muchísimo más rápido que DELETE… y por ser DDL hace COMMIT IMPLÍCITO: NO se revierte con ROLLBACK — la precisión que ya conoces, ahora en su hábitat. DROP TABLE: elimina la TABLA ENTERA — filas, estructura, constraints e índices; el esquema la olvida. La escalera del daño: DELETE poda, TRUNCATE vacía, DROP desaparece. Antes de escribir cualquiera de las tres en producción, respira y relee."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Necesitas vaciar una tabla de 10 millones de filas para recargarla completa. ¿DELETE o TRUNCATE, y cuál es el precio?","options":["DELETE: resulta bastante más rápido","Son idénticos en velocidad y en reversibilidad","DROP TABLE, y luego volver a crearla","TRUNCATE: veloz pero sin ROLLBACK (es DDL)"],"correctIndex":3,"feedback":{"correct":"Correcto. TRUNCATE gana en velocidad y pierde la red de seguridad: se confirma en el acto. DELETE es lento pero reversible antes del COMMIT.","incorrect":"TRUNCATE es la herramienta para vaciar completo… pagando la irreversibilidad del DDL. DELETE borra fila a fila y sí admite ROLLBACK."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es el caso de uso legítimo de ALTER TABLE … DISABLE CONSTRAINT?","options":["La carga masiva de datos ya validados","Esquivar reglas molestas en producción","Acelerar los SELECT de forma permanente","Ninguno: las constraints no se desactivan"],"correctIndex":0,"feedback":{"correct":"Correcto. El interruptor es de administración: se apaga para cargar, se reenciende VALIDANDO. Jamás como puerta trasera.","incorrect":"DISABLE/ENABLE existe para cargas masivas controladas — y el ENABLE VALIDATE revisa lo cargado: la integridad vuelve completa."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Ordena la 'escalera del daño' de menor a mayor alcance: DELETE con WHERE, TRUNCATE, DROP TABLE.","options":["TRUNCATE, luego DELETE y al final DROP","DELETE poda, TRUNCATE vacía, DROP desaparece","DROP, después TRUNCATE y por último DELETE","Los tres hacen exactamente lo mismo"],"correctIndex":1,"feedback":{"correct":"Correcto. Podar, vaciar, desaparecer — y solo DELETE es reversible con ROLLBACK.","incorrect":"DELETE (filas elegidas, reversible) → TRUNCATE (todas las filas, irreversible) → DROP (tabla completa: filas + estructura)."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — ALTER, TRUNCATE y DROP","points":["ALTER TABLE: ADD columnas/constraints · MODIFY tipos y tamaños · DROP COLUMN · RENAME COLUMN.","Interruptor de constraints: DISABLE para cargas masivas, ENABLE VALIDATE para volver revisando todo.","DELETE (DML): filas con WHERE, reversible con ROLLBACK — siempre con su WHERE pensado.","TRUNCATE (DDL): vacía todo de golpe, veloz, commit implícito — SIN vuelta atrás.","DROP TABLE: desaparece la tabla con estructura, constraints e índices. Podar < vaciar < desaparecer."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-l04-alter-truncate';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Vistas: la consulta con nombre
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Una consulta guardada que se usa como tabla","body":"Una VISTA es una consulta con nombre, guardada en la base, que se consulta EXACTAMENTE como si fuera una tabla — pero no duplica ni un byte de datos: cada vez que alguien la lee, Oracle ejecuta la consulta subyacente sobre las tablas reales, así que la vista está siempre al día. Sus dos superpoderes: SIMPLIFICAR — la consulta de tres joins que recepción necesita veinte veces al día se escribe UNA vez y se llama agenda_recepcion — y SEGURIDAD: la vista expone SOLO las columnas y filas debidas. Recepción ve fecha, paciente y médico; el costo de la cita y el diagnóstico no existen en su mundo. La vista es la fachada; las tablas, el edificio."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La agenda de recepción (sin costos, sin diagnósticos)","code":"CREATE OR REPLACE VIEW agenda_recepcion AS\n  SELECT c.fecha,\n         p.nombre AS paciente,\n         m.nombre AS medico\n  FROM   citas c\n  JOIN   pacientes p ON p.paciente_id = c.paciente_id\n  JOIN   medicos   m ON m.medico_id   = c.medico_id\n  WHERE  c.fecha >= TRUNC(SYSDATE)\nWITH READ ONLY;\n\nSELECT * FROM agenda_recepcion;","result":{"columns":["FECHA","PACIENTE","MEDICO"],"rows":[["2026-07-14 09:00","Laura Méndez","Dra. Ríos"],["2026-07-14 09:30","Hugo Castañeda","Dr. Salas"],["2026-07-14 10:00","Sofía Aguirre","Dra. Ríos"]],"note":"Tres joins escondidos tras un nombre: recepción consulta agenda_recepcion como si fuera una tabla. OR REPLACE actualiza la definición sin DROP previo, y WITH READ ONLY convierte la vista en vitrina: se mira, no se toca."}}$j$),
  (3, 'texto', $j${"title":"¿Se puede escribir a través de una vista?","body":"Depende de la vista. Una vista SIMPLE — una sola tabla, sin agrupaciones ni funciones — sí admite DML: el INSERT o UPDATE atraviesa la vista y aterriza en la tabla base. Una vista COMPLEJA — joins, GROUP BY, DISTINCT, funciones — es en general de solo lectura: Oracle no sabría a qué tabla enviar la escritura. Dos cláusulas gobiernan la frontera: WITH READ ONLY prohíbe todo DML (la vitrina de recepción), y WITH CHECK OPTION permite el DML pero con una condición elegante — la fila insertada o modificada DEBE seguir siendo visible para la vista. Si la vista muestra solo citas futuras, no podrás usar su nombre para colar una cita de 1999: lo que la vista no vería, la vista no lo acepta."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué contiene físicamente una VISTA?","options":["Una copia de los datos, refrescada de noche","Las filas que se consultaron la última vez","Solo la consulta; se ejecuta al leerla","Un respaldo comprimido de la tabla base"],"correctIndex":2,"feedback":{"correct":"Correcto. La vista es la consulta con nombre, no los datos: fachada al día sobre las tablas reales.","incorrect":"La vista no almacena filas: guarda la consulta y la ejecuta en cada lectura — por eso nunca está desactualizada."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"El personal de recepción debe ver la agenda (fecha, paciente, médico) pero JAMÁS el costo ni el diagnóstico. La herramienta correcta:","options":["Darles la tabla completa y pedir discreción","Borrar de raíz las columnas sensibles","Una segunda tabla duplicada sin esas columnas","Una vista con solo esas tres columnas"],"correctIndex":3,"feedback":{"correct":"Correcto. La vista como fachada de seguridad: lo que no expone, no existe para quien la consulta.","incorrect":"La vista expone exactamente lo debido sin duplicar datos: el uso de seguridad clásico. Duplicar tablas siembra inconsistencia."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Una vista muestra solo las citas FUTURAS y fue creada WITH CHECK OPTION. ¿Qué pasa si alguien intenta, a través de ella, insertar una cita con fecha de 1999?","options":["Oracle la rechaza: la vista no la vería","Se inserta normalmente en la tabla base","Se inserta pero queda oculta a la vista","La vista se convierte en una tabla real"],"correctIndex":0,"feedback":{"correct":"Correcto. 'Lo que la vista no vería, la vista no lo acepta': CHECK OPTION cierra la puerta trasera del DML.","incorrect":"WITH CHECK OPTION exige que el DML produzca filas visibles para la propia vista: la cita de 1999 quedaría fuera de su WHERE → rechazada."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Vistas","points":["Vista = consulta con NOMBRE que se usa como tabla; no duplica datos y siempre está al día.","Dos superpoderes: SIMPLIFICAR (los tres joins, escritos una vez) y SEGURIDAD (exponer solo lo debido).","CREATE OR REPLACE actualiza la definición sin DROP.","Vista simple admite DML hacia la tabla base; compleja (joins, GROUP BY) es en general solo lectura.","WITH READ ONLY prohíbe el DML · WITH CHECK OPTION solo acepta filas que la vista seguiría viendo."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-l05-vistas';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Secuencias y sinónimos
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La fábrica de números","body":"Los UID artificiales del módulo de identidad necesitan quién los fabrique, y esa es la SECUENCIA: un generador de números únicos, independiente de cualquier tabla. Se le pide el siguiente número con secuencia.NEXTVAL (cada llamada entrega uno nuevo, para siempre) y se repite el último entregado A TU SESIÓN con secuencia.CURRVAL. Y aquí la precisión que las certificaciones adoran: las secuencias DEJAN HUECOS, y eso es normal. Un INSERT que se revierte con ROLLBACK ya consumió su número (no se devuelve); los números en caché se pierden si la base se reinicia. La secuencia garantiza UNICIDAD, jamás CONTINUIDAD: verás saltos del 1007 al 1015 y no significan filas perdidas. Si el negocio exige folios sin huecos — facturación fiscal, por ejemplo — eso es OTRA pieza de diseño, no una secuencia."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Citas con folio automático","code":"CREATE SEQUENCE citas_seq\n  START WITH 1000\n  INCREMENT BY 1\n  CACHE 20;\n\nINSERT INTO citas (cita_id, paciente_id, medico_id, fecha)\nVALUES (citas_seq.NEXTVAL, 12, 3, SYSDATE);\n\nSELECT citas_seq.CURRVAL AS ultima_cita FROM dual;","result":{"columns":["ULTIMA_CITA"],"rows":[["1000"]],"note":"NEXTVAL fabricó el 1000 dentro del propio INSERT; CURRVAL lo repite para tu sesión (útil para insertar hijos con la FK correcta). CACHE 20 pre-reserva números en memoria por velocidad — y es una de las razones de los huecos."}}$j$),
  (3, 'texto', $j${"title":"Sinónimos: el alias que esconde la tubería","body":"El último objeto del arsenal DDL es el SINÓNIMO: un ALIAS para otro objeto. Las tablas reales viven en esquemas con dueño — la tabla de citas de verdad se llama admisiones.citas — y obligar a todos a escribir el prefijo acopla cada consulta a una ubicación que puede cambiar. CREATE SYNONYM citas FOR admisiones.citas crea el atajo: quien consulta citas llega al objeto real sin saber dónde vive. Privado (tuyo) o PÚBLICO (CREATE PUBLIC SYNONYM, para todos — requiere privilegios de administrador). Si mañana la tabla se muda de esquema, se recrea el sinónimo y NINGUNA consulta se toca: el alias absorbe la mudanza. ¿Y los índices, el otro gran objeto? Tienen módulo propio más adelante — son criatura de la optimización, no del diseño."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Diferencia entre secuencia.NEXTVAL y secuencia.CURRVAL:","options":["Son en realidad exactamente sinónimos","NEXTVAL da el siguiente; CURRVAL el último","CURRVAL fabrica el nuevo y NEXTVAL repite","NEXTVAL solo funciona dentro de un SELECT"],"correctIndex":1,"feedback":{"correct":"Correcto. NEXTVAL avanza la fábrica; CURRVAL recuerda tu último número — perfecto para insertar hijos con la FK del padre recién creado.","incorrect":"NEXTVAL = número nuevo cada vez. CURRVAL = el último que TU sesión recibió (exige un NEXTVAL previo en la sesión)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión de certificación: en una tabla con PK alimentada por secuencia aparecen ids 1005, 1006, 1012. ¿Qué pasó?","options":["Se corrompieron datos: restaurar el respaldo","Alguien borró filas: siempre es un incidente","Nada raro: las secuencias dejan huecos","La secuencia quedó definitivamente mal creada"],"correctIndex":2,"feedback":{"correct":"Correcto. Los huecos son comportamiento normal y documentado. Folios sin huecos = otra pieza de diseño, no una secuencia.","incorrect":"Los huecos son normales: el número entregado no se devuelve (rollback) y la caché se pierde al reiniciar. Unicidad sí; continuidad, jamás prometida."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué logra CREATE SYNONYM citas FOR admisiones.citas?","options":["Copia la tabla completa a tu esquema","Renombra de forma permanente la tabla","Crea una vista con los datos duplicados","Crea un alias que esconde el esquema"],"correctIndex":3,"feedback":{"correct":"Correcto. El sinónimo desacopla el nombre público de la ubicación real: el alias absorbe las mudanzas.","incorrect":"Es un alias, no una copia ni un renombre: apunta al objeto real y esconde su esquema dueño."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Secuencias y sinónimos","points":["SECUENCIA: fábrica de números únicos para UIDs artificiales — NEXTVAL entrega uno nuevo; CURRVAL repite el último de tu sesión.","Precisión: las secuencias DEJAN HUECOS (rollback, caché): unicidad garantizada, continuidad jamás.","Folios sin huecos (facturación) = diseño aparte, no una secuencia.","SINÓNIMO: alias que esconde el esquema dueño (citas → admisiones.citas); privado o PUBLIC.","La mudanza de esquema se absorbe recreando el sinónimo: las consultas no se tocan."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-l06-secuencias-sinonimos';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Práctica: tu primer DDL completo (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"La farmacia del hospital lleva su inventario por lotes y necesita la tabla LOTES ya, con la integridad completa. El esqueleto está escrito; te toca blindarlo (la tabla medicamentos ya existe, con PK medicamento_id).","instructions":["Convierte lote_id en la PRIMARY KEY, con la constraint nombrada lot_pk.","Haz que medicamento_id sea NOT NULL y además FOREIGN KEY hacia medicamentos (medicamento_id), con la constraint nombrada lot_med_fk.","Agrega la constraint lot_cant_ck: una CHECK que exija cantidad >= 0."],"initialCode":"-- Inventario de farmacia: la tabla LOTES\n-- (medicamentos ya existe, con PK medicamento_id)\n\nCREATE TABLE lotes (\n  lote_id         NUMBER(10),\n  medicamento_id  NUMBER(6),\n  cantidad        NUMBER(6) NOT NULL,\n  caducidad       DATE NOT NULL\n);","validators":["constraint\\s+lot_pk\\s+primary\\s+key","medicamento_id\\s+number\\s*\\(\\s*6\\s*\\)[^,]*not\\s+null","constraint\\s+lot_med_fk\\s+(foreign\\s+key\\s*\\(\\s*medicamento_id\\s*\\)\\s+)?references\\s+medicamentos\\s*\\(\\s*medicamento_id\\s*\\)","constraint\\s+lot_cant_ck\\s+check\\s*\\(\\s*cantidad\\s*>=\\s*0\\s*\\)"],"mockOutput":{"columns":["RESULTADO"],"rows":[["Table LOTES created."]],"note":"La tabla nació blindada: lot_pk garantiza identidad, lot_med_fk amarra cada lote a un medicamento real (y el NOT NULL lo vuelve obligatorio), y lot_cant_ck hace imposible una cantidad negativa. Cuatro reglas de negocio vigiladas por Oracle, gratis, en cada INSERT."},"hints":["La PK puede ir en la línea de la columna: lote_id NUMBER(10) CONSTRAINT lot_pk PRIMARY KEY.","Para la FK en línea de columna: medicamento_id NUMBER(6) NOT NULL CONSTRAINT lot_med_fk REFERENCES medicamentos (medicamento_id). (A nivel tabla también vale, con FOREIGN KEY (medicamento_id).)","La CHECK puede ir en la línea de cantidad o al final a nivel tabla: CONSTRAINT lot_cant_ck CHECK (cantidad >= 0)."],"successMessage":"Tabla LOTES creada con su integridad completa: PK nombrada, FK obligatoria hacia el catálogo y CHECK contra cantidades negativas. Este es el oficio: el DDL no solo crea estructuras — declara las reglas que Oracle vigilará por ti para siempre.","failMessage":"Revisa las tres piezas: CONSTRAINT lot_pk PRIMARY KEY en lote_id · medicamento_id con NOT NULL y CONSTRAINT lot_med_fk REFERENCES medicamentos (medicamento_id) · CONSTRAINT lot_cant_ck CHECK (cantidad >= 0). Los nombres de las constraints deben ser exactos."}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-l07-practica-ddl';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La sexta región","body":"Byte cruzó del papel al metal: en esta región las tablas existen de verdad, con sus guardianes activos. Once preguntas custodian la salida — las cuatro familias del lenguaje, tipos y constraints, la escalera del daño, vistas, secuencias y sinónimos. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Clasifica: REVOKE, TRUNCATE, MERGE, SAVEPOINT.","options":["DCL · DDL · DML · TCL en ese orden","DDL · DML · DCL · TCL en ese orden","DML · DML · DDL · DCL en ese orden","DCL · DML · DDL · TCL en ese orden"],"correctIndex":0,"feedback":{"correct":"Correcto. REVOKE quita permisos (DCL), TRUNCATE redefine la tabla (DDL — la trampa), MERGE toca filas (DML), SAVEPOINT marca la transacción (TCL).","incorrect":"REVOKE→DCL · TRUNCATE→DDL (aunque vacíe filas) · MERGE→DML · SAVEPOINT→TCL. La pista: ¿sobre qué actúa cada una?"}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Ejecutas 15 INSERTs sin confirmar y luego un CREATE INDEX. ¿Puedes revertir los INSERTs con ROLLBACK?","options":["Sí: el ROLLBACK siempre deshace lo pendiente","No: el CREATE INDEX hizo commit implícito","Sí, pero solo los primeros diez INSERTs","Solo si el índice se borra antes que nada"],"correctIndex":1,"feedback":{"correct":"Correcto. El DDL confirma lo pendiente sin preguntar: la regla oculta que más sorpresas causa en producción.","incorrect":"Todo DDL (CREATE, ALTER, DROP, TRUNCATE) hace commit implícito: al correr el CREATE INDEX, tus INSERTs se confirmaron definitivamente."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Para un nombre de persona de hasta 80 letras, ¿VARCHAR2(80) o CHAR(80), y por qué?","options":["CHAR(80): resulta más rápido en todo caso","CHAR(80): los nombres tienen ancho fijo","VARCHAR2(80): 'Ana' ocupa 3 bytes, no 80","Da exactamente igual cuál de los dos uses"],"correctIndex":2,"feedback":{"correct":"Correcto. Variable para longitudes variables; el fijo con relleno queda para códigos de ancho constante.","incorrect":"VARCHAR2 ocupa lo que el texto mide; CHAR rellena hasta 80 con espacios. Para texto de longitud variable, VARCHAR2 siempre."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué rechazaría una columna declarada NUMBER(7,2)?","options":["El valor 99999.99, por exceder el tope","El valor 0, porque no admite el cero","El valor 12.5, por tener pocos decimales","El 123456.78: son 8 dígitos y admite 7"],"correctIndex":3,"feedback":{"correct":"Correcto. NUMBER(7,2) = 7 dígitos totales con 2 decimales → máximo 99999.99: el 123456.78 (8 dígitos) excede la precisión.","incorrect":"Precisión 7, escala 2 → cinco enteros y dos decimales: el tope es 99999.99, y 123456.78 lo excede."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Una PRIMARY KEY compuesta por dos columnas, ¿en qué nivel se declara?","options":["A nivel tabla, obligatoriamente siempre","En la línea de la primera columna del par","En la línea de la segunda columna del par","Dentro de un trigger asociado a la tabla"],"correctIndex":0,"feedback":{"correct":"Correcto. Toda constraint que involucre 2+ columnas se declara a nivel tabla — la regla sin excepciones.","incorrect":"Compuesta → nivel tabla, siempre: CONSTRAINT xxx_pk PRIMARY KEY (col1, col2) al final del CREATE."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Una FK declarada con ON DELETE SET NULL exige que la columna FK sea…","options":["Que la columna FK sea NOT NULL siempre","Que la columna FK sea opcional (admita nulos)","Que la columna FK sea la PRIMARY KEY","Que la columna FK sea de tipo NUMBER"],"correctIndex":1,"feedback":{"correct":"Correcto. SET NULL escribe un nulo en la FK del hijo: si la columna fuera NOT NULL, la acción sería imposible.","incorrect":"SET NULL deja huérfanos con FK nula — la columna debe admitir nulos. Con FK obligatoria, las opciones son rechazar (defecto) o CASCADE."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Diferencia clave entre DELETE y TRUNCATE al vaciar una tabla:","options":["Ninguna: son totalmente intercambiables","TRUNCATE es más lento pero mucho más seguro","DELETE es DML reversible; TRUNCATE es DDL","DELETE borra también toda la estructura"],"correctIndex":2,"feedback":{"correct":"Correcto. La clasificación (DML vs DDL) explica todo lo demás: reversibilidad, WHERE y velocidad.","incorrect":"DELETE = DML reversible con WHERE; TRUNCATE = DDL veloz e irreversible. Confundirlos en producción cuesta datos."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"Tras desactivar una constraint para una carga masiva, ¿cómo se reactiva correctamente?","options":["ENABLE NOVALIDATE, para no perder tiempo","No se puede: hay que recrear toda la tabla","Se reactiva sola al llegar la medianoche","ENABLE VALIDATE: revisa todo lo cargado"],"correctIndex":3,"feedback":{"correct":"Correcto. El interruptor vuelve validando: la integridad regresa completa o la carga se corrige.","incorrect":"ENABLE VALIDATE revisa todas las filas cargadas: así el interruptor de administración nunca se convierte en puerta trasera."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estas afirmaciones sobre las VISTAS es correcta?","options":["No almacenan filas: guardan la consulta","Duplican los datos y se refrescan de noche","Solo se pueden leer una única vez","Son siempre más rápidas que las tablas"],"correctIndex":0,"feedback":{"correct":"Correcto. Consulta con nombre: cero duplicación, siempre al día, y fachada de seguridad.","incorrect":"La vista guarda la consulta, no los datos: se ejecuta en cada lectura, por eso nunca está desactualizada."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión de certificación: ¿qué GARANTIZA una secuencia de Oracle y qué NO?","options":["Garantiza números consecutivos sin huecos","Garantiza unicidad, no continuidad","Garantiza continuidad pero no unicidad","En realidad no garantiza absolutamente nada"],"correctIndex":1,"feedback":{"correct":"Correcto. Únicos sí, consecutivos no: los huecos del 1007 al 1015 no son filas perdidas.","incorrect":"Unicidad garantizada; continuidad jamás: el número consumido por un rollback no se devuelve y la caché se pierde al reiniciar."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'la regla es costo >= 0. ¿Por qué la implementaste como CHECK y no como trigger?' Tu respuesta senior:","options":["Porque los triggers están terminantemente prohibidos","Porque la CHECK es una técnica más moderna","Declarativa: barata, activa e inesquivable","Da exactamente igual: las dos hacen lo mismo"],"correctIndex":2,"feedback":{"correct":"Impecable. La regla de oro de la integridad, defendida con sus cuatro razones. Así se contesta en una entrevista.","incorrect":"La respuesta senior: declarativa siempre que alcance (barata, activa, visible, inesquivable); el trigger es el plan B para lo que la declarativa no puede vigilar."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm04-x01-examen';
