-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 018 — SQL con Oracle · m05: DML y consultas
-- ═══════════════════════════════════════════════════════════════════
-- Cubre la Parte IX en su tramo de una fila (SELECT, WHERE, ORDER BY,
-- funciones de fila de texto/número/fecha, conversión TO_CHAR/TO_DATE/
-- TO_NUMBER, NVL/NVL2/COALESCE/NULLIF, CASE/DECODE), la Parte X en su
-- tramo DML (INSERT, UPDATE, DELETE, MERGE) y la Parte XI de texto
-- avanzado (REGEXP_LIKE/SUBSTR/REPLACE/INSTR/COUNT).
-- Precisiones vinculantes: UPDATE/DELETE SIEMPRE con WHERE explicado
-- (procedimiento seguro: SELECT previo con el mismo WHERE, verificar
-- conteo, confirmar); conversión explícita sobre implícita; el DML
-- no confirmado se revierte (a diferencia del TRUNCATE, ya visto).
-- Práctica de editor (regex+mockOutput): consulta real con NVL,
-- WHERE y ORDER BY.
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- OJO: SQL con Oracle está PUBLICADO — esta migración sale en vivo.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 011 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm05-dml-consultas'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m05-l01-select',             'SELECT: elegir columnas',              'leccion',  20, 1),
       ('m05-l02-where-order',        'WHERE y ORDER BY: filtrar y ordenar',  'leccion',  20, 2),
       ('m05-l03-funciones-fila',     'Funciones de una fila',                'leccion',  20, 3),
       ('m05-l04-conversion',         'Conversión: TO_CHAR, TO_DATE, TO_NUMBER','leccion',20, 4),
       ('m05-l05-nulos-case',         'El arsenal del nulo, CASE y DECODE',   'leccion',  20, 5),
       ('m05-l06-regexp',             'Texto avanzado: REGEXP_*',             'leccion',  20, 6),
       ('m05-l07-dml-merge',          'DML: INSERT, UPDATE, DELETE y MERGE',  'leccion',  20, 7),
       ('m05-l08-practica-consultas', 'Práctica: el reporte de dirección',    'practica', 20, 8),
       ('m05-x01-examen',             'Examen: DML y consultas',              'examen',   40, 9)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm05-dml-consultas';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · SELECT: elegir columnas
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La orden más ejecutada del planeta","body":"El esquema existe y tiene datos: llegó la hora de preguntarle cosas. SELECT es la orden de LECTURA — no modifica nada, jamás — y su primer poder es la PROYECCIÓN: elegir qué COLUMNAS ves. SELECT * trae todas (cómodo para explorar, mala idea en código serio: pides lo que necesitas). Además de columnas puedes proyectar EXPRESIONES — costo * 1.16 calcula el IVA al vuelo, sin tocar la tabla — y bautizarlas con un ALIAS: AS costo_con_iva le da nombre legible al cálculo. El operador || CONCATENA textos para armar frases, y DISTINCT elimina duplicados del resultado: la lista de estados que realmente existen, sin repetir."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La farmacia pregunta a su catálogo","code":"SELECT nombre,\n       precio,\n       ROUND(precio * 1.16, 2)        AS precio_con_iva,\n       nombre || ' — pasillo B'       AS etiqueta\nFROM   medicamentos;\n\nSELECT DISTINCT refrigerado\nFROM   medicamentos;","result":{"columns":["NOMBRE","PRECIO","PRECIO_CON_IVA","ETIQUETA"],"rows":[["Amoxicilina 500","185.5","215.18","Amoxicilina 500 — pasillo B"],["Paracetamol 750","32","37.12","Paracetamol 750 — pasillo B"],["Insulina glargina","890","1032.4","Insulina glargina — pasillo B"]],"note":"La tabla no cambió: el IVA y la etiqueta se calcularon al vuelo, solo en el resultado. La segunda consulta con DISTINCT devolvería apenas dos filas: S y N — los valores que existen, sin repetir."}}$j$),
  (3, 'texto', $j${"title":"Tres letras pequeñas del oficio","body":"Detalles que separan la consulta limpia de la consulta con sorpresas. UNO: un alias con espacios exige comillas dobles (AS \"precio final\") — y ya sabes lo que opinamos de las comillas dobles: nombra sin espacios (precio_final) y vive en paz. DOS: la aritmética con NULO da NULO — si una cita no tiene costo registrado, costo * 1.16 no da cero: da nulo, y ese nulo contamina todo el cálculo (la lección 5 trae el antídoto). TRES: DISTINCT opera sobre la COMBINACIÓN completa de columnas listadas — SELECT DISTINCT medico_id, fecha no des-duplica médicos: des-duplica parejas médico+fecha. Tres letras pequeñas, tres horas de depuración ahorradas."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En un SELECT, elegir qué COLUMNAS aparecen en el resultado se llama…","options":["Es lo que se conoce como filtrado","Es lo que se conoce como agrupación","Proyección: elegir qué columnas ves","Es lo que se conoce como indexación"],"correctIndex":2,"feedback":{"correct":"Correcto. Proyección = elegir columnas; el filtrado de FILAS es asunto del WHERE, en la próxima lección.","incorrect":"Elegir columnas es la PROYECCIÓN. Filtrar filas (WHERE) y ordenar (ORDER BY) son las otras dos operaciones que verás enseguida."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Una tabla registra el costo de cada cita, pero algunas citas aún no tienen costo (nulo). ¿Qué devuelve la expresión costo * 1.16 para esas filas?","options":["Devuelve exactamente 0 en esas filas","Devuelve el factor 1.16 en esas filas","Devuelve un error de sintaxis claro","Nulo: la aritmética con nulo da nulo"],"correctIndex":3,"feedback":{"correct":"Correcto. Desconocido por 1.16 sigue siendo desconocido. El antídoto (NVL) llega en la lección 5.","incorrect":"El nulo no es cero: es 'no sé'. Y 'no sé' por 1.16 sigue siendo 'no sé' — nulo en la aritmética contamina el resultado."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué devuelve SELECT DISTINCT medico_id, fecha FROM citas?","options":["Las combinaciones médico+fecha sin repetir","Los médicos, cada uno una sola vez","Las fechas, cada una una sola vez","Una fila por cada médico con su última fecha"],"correctIndex":0,"feedback":{"correct":"Correcto. El mismo médico aparece varias veces si trabajó varias fechas: lo único que no se repite es la pareja completa.","incorrect":"DISTINCT des-duplica la COMBINACIÓN de todas las columnas del SELECT — no cada columna por separado."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — SELECT","points":["SELECT es LECTURA pura: jamás modifica datos.","PROYECCIÓN = elegir columnas; * trae todas (evítalo en código serio).","Expresiones al vuelo (costo * 1.16) con ALIAS legible (AS costo_con_iva, sin espacios).","|| concatena textos; DISTINCT des-duplica la COMBINACIÓN completa de columnas.","Aritmética con NULO da NULO — el antídoto llega en la lección 5."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l01-select';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · WHERE y ORDER BY
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"WHERE: la aduana de las filas","body":"Si SELECT elige columnas, WHERE elige FILAS: solo pasan las que cumplen la condición. El arsenal: comparadores (=, <>, >, >=, <, <=), BETWEEN a AND b (rango INCLUYENTE por ambos lados), IN (lista) para membresías, y LIKE para parecidos de texto con dos comodines — % significa 'cualquier cosa, incluso nada' y _ significa 'exactamente un carácter': LIKE 'Dra.%' atrapa todo lo que empiece con Dra. Combinas condiciones con AND, OR y NOT — y cuidado con la precedencia: AND se evalúa ANTES que OR, así que a = 1 OR b = 2 AND c = 3 no es lo que parece. Paréntesis siempre que mezcles: la consulta se lee como la pensaste. Y la regla de oro del nulo: NADA es igual a nulo — ni siquiera otro nulo. costo = NULL no encuentra nada jamás; al nulo se le pregunta con IS NULL o IS NOT NULL."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Las citas que le duelen al hospital","code":"SELECT cita_id, fecha, estado, costo\nFROM   citas\nWHERE  estado IN ('cancelada', 'no_asistio')\nAND    fecha BETWEEN DATE '2026-01-01' AND DATE '2026-06-30'\nAND    costo IS NOT NULL\nORDER  BY fecha DESC, costo DESC;","result":{"columns":["CITA_ID","FECHA","ESTADO","COSTO"],"rows":[["612","2026-06-28","cancelada","800"],["598","2026-06-28","no_asistio","350"],["544","2026-05-17","cancelada","520"],["501","2026-02-03","no_asistio","300"]],"note":"IN prueba la membresía, BETWEEN incluye ambos extremos, IS NOT NULL descarta las citas sin costo (con = NULL no saldría ninguna fila), y el ORDER BY desempata: primero por fecha descendente, y a fecha igual, la más cara arriba."}}$j$),
  (3, 'texto', $j${"title":"ORDER BY: el orden es una promesa explícita","body":"ORDER BY ordena el resultado: ASC (ascendente) es el defecto, DESC invierte, y puedes apilar criterios de desempate — ORDER BY fecha DESC, costo DESC ordena por fecha y, dentro de cada fecha, por costo. Se puede ordenar por columna, por alias o por expresión. Y la verdad incómoda que rompe sistemas: SIN ORDER BY, Oracle NO promete NINGÚN orden. El 'siempre me salen ordenadas por id' de tu máquina es coincidencia de hoy — cambia el plan de ejecución y el orden cambia con él. Si el orden importa (un reporte, una lista, un corte), se declara. El orden que no se pide, no existe."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué WHERE costo = NULL no devuelve ninguna fila, aunque haya citas sin costo?","options":["Porque las citas sin costo no existen","Porque nada es igual a nulo, ni otro nulo","Porque a la tabla le falta un índice","Porque NULL debe ir escrito en mayúsculas"],"correctIndex":1,"feedback":{"correct":"Correcto. El nulo es 'desconocido', y desconocido no es igual a nada. IS NULL / IS NOT NULL son sus únicas preguntas válidas.","incorrect":"La regla de oro: el nulo no se compara con =. WHERE costo IS NULL sí encuentra las citas sin costo."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué textos atrapa el patrón LIKE '_a%'?","options":["Los que contienen una 'a' en cualquier parte","Los que empiezan directamente con la 'a'","Los que tienen 'a' como segundo carácter","Los que terminan justamente con una 'a'"],"correctIndex":2,"feedback":{"correct":"Correcto. _ = un carácter exacto, % = lo que sea: 'Laura' y 'Karen' pasan; 'Ana' no (su segunda letra es n).","incorrect":"El _ ocupa exactamente UNA posición y el % el resto: '_a%' pide 'a' en la segunda posición."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Sin paréntesis, ¿cómo evalúa Oracle la condición estado = 'urgente' OR estado = 'alta' AND costo > 500?","options":["De izquierda a derecha, siempre en orden","Como (urgente OR alta) AND costo > 500","Da un claro error de sintaxis al correr","El AND se evalúa antes que el OR"],"correctIndex":3,"feedback":{"correct":"Correcto. La precedencia AND-antes-que-OR cambia el significado: paréntesis siempre que mezcles, para que la consulta diga lo que pensaste.","incorrect":"AND gana la precedencia: sin paréntesis, el OR abraza de más. (urgente OR alta) AND costo > 500 exige los paréntesis."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Una consulta sin ORDER BY 'siempre sale ordenada por id' en tu equipo. ¿Puedes confiar en ese orden?","options":["No: sin ORDER BY no hay orden garantizado","Sí: Oracle ordena por la PK por defecto","Sí, siempre que la tabla sea pequeña","Sí, pero únicamente los días lunes"],"correctIndex":0,"feedback":{"correct":"Correcto. El orden que no se pide no existe: si importa, se declara con ORDER BY.","incorrect":"Ese orden es un accidente del plan de ejecución: Oracle no promete nada sin ORDER BY. Los reportes que dependen de él revientan en producción."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — WHERE y ORDER BY","points":["WHERE filtra FILAS: comparadores, BETWEEN (incluyente), IN (membresía), LIKE (% = lo que sea, _ = un carácter).","Al nulo se le pregunta con IS NULL / IS NOT NULL — jamás con =.","AND se evalúa antes que OR: paréntesis siempre que los mezcles.","ORDER BY: ASC por defecto, DESC invierte, criterios apilables para desempates.","Sin ORDER BY no hay orden garantizado: el orden que importa se declara."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l02-where-order';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Funciones de una fila
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La caja de herramientas del texto","body":"Las FUNCIONES DE UNA FILA transforman un valor en otro, fila por fila — y se ANIDAN: el resultado de una alimenta a la siguiente, leyéndose de adentro hacia afuera. Las de texto que usarás a diario: UPPER y LOWER cambian todo a mayúsculas/minúsculas (el truco clásico para comparar sin pelear con cómo se capturó: WHERE UPPER(nombre) = 'ANA TORRES'); INITCAP pone Cada Palabra Con Inicial mayúscula; SUBSTR(texto, desde, cuántos) recorta (SUBSTR('Amoxicilina', 1, 4) → 'Amox'); LENGTH mide; TRIM poda espacios de las orillas; LPAD y RPAD rellenan hasta un ancho fijo (folios, alineación); INSTR encuentra la posición de un texto dentro de otro."}$j$),
  (2, 'texto', $j${"title":"Números y fechas: ROUND, TRUNC y el calendario","body":"Con números, dos hermanas que no son gemelas: ROUND REDONDEA al más cercano y TRUNC CORTA sin piedad — ROUND(123.456, 2) da 123.46, TRUNC(123.456, 2) da 123.45. MOD devuelve el residuo de la división (paridades, ciclos, turnos). Con fechas, Oracle es generoso: SYSDATE es el ahora del servidor; sumar números a una fecha suma DÍAS (fecha + 7 = en una semana); MONTHS_BETWEEN mide meses entre dos fechas y ADD_MONTHS desplaza meses completos. Y el truco que conecta con lo que ya sabes: como DATE guarda también la HORA, comparar por día exige TRUNC(fecha) — que pone la hora en 00:00 — o dos citas del mismo día a horas distintas 'no serán del mismo día' para tu WHERE."}$j$),
  (3, 'ejemplo_sql', $j${"title":"La alerta de caducidad de la farmacia","code":"SELECT UPPER(nombre)                         AS medicamento,\n       LPAD(TO_CHAR(precio), 10, '·')        AS precio_alineado,\n       ADD_MONTHS(caducidad, -3)             AS inicio_de_alerta\nFROM   medicamentos\nWHERE  TRUNC(SYSDATE) >= ADD_MONTHS(caducidad, -3)\nORDER  BY caducidad;","result":{"columns":["MEDICAMENTO","PRECIO_ALINEADO","INICIO_DE_ALERTA"],"rows":[["INSULINA GLARGINA","·······890","2026-05-02"],["AMOXICILINA 500","·····185.5","2026-06-15"]],"note":"Funciones anidadas leyéndose de adentro hacia afuera: TO_CHAR convierte el precio a texto y LPAD lo alinea a 10 posiciones. El WHERE compara días limpios: TRUNC(SYSDATE) contra la caducidad desplazada tres meses atrás — los medicamentos que ya entraron en su ventana de alerta."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"ROUND(87.966, 2) y TRUNC(87.966, 2) devuelven, respectivamente…","options":["Ambas devuelven 87.96 y 87.96 respectivamente","87.97 y 87.96: ROUND redondea, TRUNC corta","Devuelven 87.97 y 87.97 respectivamente","Devuelven 88 y 87 respectivamente"],"correctIndex":1,"feedback":{"correct":"Correcto. Redondear vs cortar: en dinero y dosis, elegir mal la hermana equivocada cuesta centavos… millones de veces.","incorrect":"ROUND mira el dígito siguiente y redondea (87.97); TRUNC simplemente corta (87.96). No son gemelas."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres todas las citas de HOY, pero WHERE fecha = SYSDATE no devuelve casi nada. ¿Por qué, y cómo se corrige?","options":["Porque no hay ninguna cita para hoy","Porque SYSDATE es en realidad un texto","DATE guarda la hora: usa TRUNC en ambos","Porque a la consulta le falta un JOIN"],"correctIndex":2,"feedback":{"correct":"Correcto. La cita de las 09:00 no es igual al ahora de las 11:23: TRUNC pone ambas horas en 00:00 y compara el día.","incorrect":"El clásico de DATE-con-hora: la igualdad exacta casi nunca coincide. TRUNC(fecha) = TRUNC(SYSDATE) compara por día."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué devuelve SUBSTR('HOSPITAL SAN RAFAEL', 10, 3)?","options":["Devuelve el texto 'HOS' del inicio","Devuelve el texto 'RAF' del final","Devuelve el texto 'L S' con espacio","'SAN': desde la posición 10 toma 3"],"correctIndex":3,"feedback":{"correct":"Correcto. SUBSTR(texto, desde, cuántos): la posición 10 es la S de SAN, y toma tres.","incorrect":"SUBSTR cuenta desde 1: la posición 10 cae en la S de 'SAN', y de ahí toma 3 caracteres."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Funciones de una fila","points":["Transforman valor por valor y se ANIDAN (se leen de adentro hacia afuera).","Texto: UPPER/LOWER (comparar sin pelear), INITCAP, SUBSTR, LENGTH, TRIM, LPAD/RPAD, INSTR.","ROUND redondea; TRUNC corta — no son gemelas, y en dinero importa.","Fechas: SYSDATE, fecha + n días, MONTHS_BETWEEN, ADD_MONTHS.","DATE lleva hora: comparar por día = TRUNC(fecha) en ambos lados."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l03-funciones-fila';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Conversión: TO_CHAR, TO_DATE, TO_NUMBER
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El favor que Oracle no debería hacerte","body":"Cuando mezclas tipos — comparar el texto '25' con el número 9, meter '01/07/2026' donde va una fecha — Oracle intenta convertir SOLO: la CONVERSIÓN IMPLÍCITA. Funciona… hasta que no: una sola fila con texto no numérico revienta la consulta entera, y las fechas interpretadas 'a la manera de la sesión' cambian de significado entre máquinas. La regla del oficio es conversión EXPLÍCITA, siempre: TO_CHAR convierte número o fecha A TEXTO con un FORMATO que tú dictas; TO_DATE convierte texto A FECHA declarando cómo leerlo; TO_NUMBER convierte texto A NÚMERO. El formato es un pequeño lenguaje: DD día, MM mes, YYYY año, HH24:MI hora; para números, 9 es dígito opcional, 0 obligatorio, y puedes fijar comas y símbolos ($999,999.99)."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El mismo dato, tres presentaciones","code":"SELECT TO_CHAR(fecha, 'DD/MM/YYYY HH24:MI')  AS agendada,\n       TO_CHAR(fecha, 'DAY')                 AS dia_semana,\n       TO_CHAR(costo, '$999,999.99')         AS costo_formato\nFROM   citas\nWHERE  fecha >= TO_DATE('01/07/2026', 'DD/MM/YYYY');","result":{"columns":["AGENDADA","DIA_SEMANA","COSTO_FORMATO"],"rows":[["02/07/2026 09:00","JUEVES","$950.00"],["14/07/2026 10:30","MARTES","$350.00"]],"note":"TO_CHAR presenta con el formato que TÚ dictas; TO_DATE le declara a Oracle cómo leer tu texto — sin adivinanzas. El formato es un contrato en ambas direcciones."}}$j$),
  (3, 'texto', $j${"title":"Por qué la implícita muerde (dos veces)","body":"Primera mordida: la conversión implícita depende de la CONFIGURACIÓN DE LA SESIÓN (idioma, formato de fecha por defecto). La consulta que funcionaba en tu equipo truena en el servidor — o peor, NO truena y lee '03/07' como marzo 7 en vez de julio 3: un error silencioso en datos médicos. Segunda mordida, que el módulo de optimización te cobrará: cuando la conversión implícita cae SOBRE LA COLUMNA (comparar una columna de texto con un número, por ejemplo), Oracle convierte fila por fila — y eso puede inutilizar índices y volver lenta una consulta que era instantánea. Conversión explícita = intención declarada: el formato viaja con la consulta y significa lo mismo en cualquier máquina."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Necesitas convertir el texto '15/08/2026' en una fecha real. ¿La herramienta correcta?","options":["TO_DATE con el formato 'DD/MM/YYYY'","TO_CHAR aplicado sobre ese texto","TO_NUMBER aplicado sobre ese texto","Un CAST implícito: Oracle lo adivina"],"correctIndex":0,"feedback":{"correct":"Correcto. TO_DATE con su máscara: sin adivinanzas de sesión, la fecha significa lo mismo en todas partes.","incorrect":"Texto→fecha es TO_DATE, y el segundo argumento (el formato) es la parte que evita que '03/07' cambie de mes según la máquina."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es el peligro de dejar que Oracle convierta tipos implícitamente?","options":["Ninguno en absoluto: siempre funciona exactamente igual","Depende de la sesión: significado y rendimiento","Es ilegal a partir de Oracle 12c","Solo llega a funcionar con los números"],"correctIndex":1,"feedback":{"correct":"Correcto. Las dos mordidas: significado que cambia entre entornos, y rendimiento que se desploma. Explícita siempre.","incorrect":"La implícita depende de la sesión (errores silenciosos entre máquinas) y puede costar índices. Por eso el oficio convierte explícito."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué produce TO_CHAR(1234.5, '$999,999.99')?","options":["Devuelve un error de formato bastante claro","Devuelve el texto plano '1234.5'","'$1,234.50': aplica la máscara exacta","Devuelve la máscara '$999,999.99'"],"correctIndex":2,"feedback":{"correct":"Correcto. La máscara dicta comas, decimales y símbolo: presentación controlada por ti, no por la sesión.","incorrect":"TO_CHAR aplica la máscara al valor: $1,234.50. Los 9 son posiciones de dígito; las comas y el $ salen tal cual."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Conversión","points":["TO_CHAR: número/fecha → texto CON formato · TO_DATE: texto → fecha · TO_NUMBER: texto → número.","El formato es un contrato: DD/MM/YYYY, HH24:MI, DAY; 9 dígito, $ y comas literales.","La implícita depende de la sesión: errores silenciosos entre máquinas (marzo 7 vs julio 3).","La implícita sobre una COLUMNA puede inutilizar índices (el módulo de optimización lo cobra).","Regla del oficio: conversión EXPLÍCITA siempre — la intención viaja con la consulta."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l04-conversion';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · El arsenal del nulo, CASE y DECODE
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuatro armas contra el desconocido","body":"El nulo contamina la aritmética (lección 1) y esquiva al = (lección 2): llegó la hora de domarlo. NVL(valor, sustituto) — si el valor es nulo, entrega el sustituto: NVL(costo, 0) desinfecta el cálculo ANTES de multiplicar. NVL2(valor, si_hay, si_nulo) — decide DOS caminos según haya valor o no: NVL2(costo, 'cobrada', 'pendiente'). COALESCE(a, b, c, …) — la multiherramienta estándar: devuelve el PRIMER no nulo de la lista, perfecta para cascadas de respaldo (teléfono móvil, si no el fijo, si no 'sin contacto'). NULLIF(a, b) — la inversa exótica: devuelve NULO si a y b son iguales (su truco estrella: NULLIF(divisor, 0) convierte el divisor cero en nulo y evita el error de división)."}$j$),
  (2, 'texto', $j${"title":"CASE y DECODE: la lógica entra al SELECT","body":"Para clasificar valores al vuelo hay dos herramientas. CASE es el condicional COMPLETO y estándar: CASE WHEN costo >= 800 THEN 'premium' WHEN costo >= 300 THEN 'estandar' ELSE 'social' END — evalúa condiciones EN ORDEN, gana la primera verdadera, y el ELSE atrapa el resto (sin ELSE, lo no clasificado sale nulo). DECODE es el atajo histórico de Oracle para IGUALDADES simples: DECODE(estado, 'A', 'Atendida', 'C', 'Cancelada', 'Otra') — pares valor/resultado y un defecto al final. La regla del oficio: CASE para lógica real (rangos, condiciones compuestas — y es SQL estándar); DECODE solo para mapeos cortos de igualdad. Y el favorito de las entrevistas Oracle: saber traducir uno al otro."}$j$),
  (3, 'ejemplo_sql', $j${"title":"El tablero de facturación","code":"SELECT cita_id,\n       NVL(costo, 0)                              AS costo_real,\n       NVL2(costo, 'cobrada', 'pendiente')        AS facturacion,\n       CASE\n         WHEN costo >= 800 THEN 'premium'\n         WHEN costo >= 300 THEN 'estandar'\n         ELSE 'social'\n       END                                        AS tarifa\nFROM   citas;","result":{"columns":["CITA_ID","COSTO_REAL","FACTURACION","TARIFA"],"rows":[["517","950","cobrada","premium"],["519","0","pendiente","social"],["523","350","cobrada","estandar"]],"note":"La cita 519 no tiene costo: NVL la vuelve 0 para el cálculo, NVL2 la etiqueta 'pendiente' y el CASE — como el nulo no es >= de nada — la manda al ELSE. Tres armas, un tablero coherente."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué devuelve COALESCE(NULL, NULL, 'móvil', 'fijo')?","options":["Devuelve un valor NULL al final","Devuelve el texto 'fijo' de la lista","Devuelve un error por tantos nulos","'móvil': el primer valor no nulo"],"correctIndex":3,"feedback":{"correct":"Correcto. La cascada de respaldos: recorre en orden y se queda con el primer no nulo.","incorrect":"COALESCE recorre la lista en orden y devuelve el primer no nulo: 'móvil' llega antes que 'fijo'."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Para qué sirve el truco NULLIF(divisor, 0) en una división?","options":["Convierte el divisor 0 en nulo","Redondea el resultado de la división","Convierte todos los nulos en ceros","Cuenta cuántos ceros hay en total"],"correctIndex":0,"feedback":{"correct":"Correcto. NULLIF(a, b) da nulo si son iguales: el divisor cero se vuelve nulo y la consulta sobrevive (fila en nulo, no error).","incorrect":"NULLIF devuelve nulo cuando sus dos argumentos son iguales: con (divisor, 0), el cero mortal se vuelve nulo inofensivo."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo prefiere el oficio CASE sobre DECODE?","options":["Nunca: DECODE resulta más rápido siempre","Para lógica real: rangos y condiciones","Cuando hay menos de tres valores","Únicamente dentro de Oracle 12c"],"correctIndex":1,"feedback":{"correct":"Correcto. CASE evalúa condiciones en orden y viaja a cualquier base; DECODE solo compara igualdades, al estilo Oracle.","incorrect":"DECODE solo sabe de igualdades (valor→resultado); los rangos y la lógica compuesta piden CASE — que además es estándar."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Nulos, CASE y DECODE","points":["NVL(valor, sustituto) desinfecta ANTES de operar · NVL2 decide dos caminos según haya valor.","COALESCE devuelve el primer no nulo (cascadas de respaldo) · NULLIF da nulo si son iguales (salva divisiones).","CASE: condiciones EN ORDEN, gana la primera verdadera; sin ELSE, lo demás sale nulo.","DECODE: el atajo Oracle para igualdades simples (valor, resultado, …, defecto).","CASE para lógica y estándar; DECODE para mapeos cortos — y en entrevista, saber traducirlos."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l05-nulos-case';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Texto avanzado: REGEXP_*
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuando LIKE se queda corto","body":"LIKE reconoce parecidos simples, pero pídele 'un teléfono de exactamente 10 dígitos' o 'un correo con forma de correo' y se rinde: para PATRONES de verdad existen las funciones REGEXP_*, que hablan EXPRESIONES REGULARES. La familia: REGEXP_LIKE(columna, patrón) filtra filas que cumplen el patrón; REGEXP_SUBSTR extrae el pedazo que lo cumple; REGEXP_REPLACE sustituye lo que lo cumple; REGEXP_INSTR dice en qué posición está; REGEXP_COUNT cuenta cuántas veces aparece. El mini-vocabulario para empezar: [0-9] un dígito · [a-z] una letra · {10} exactamente diez repeticiones · + una o más · ^ el inicio del texto · $ el final · . cualquier carácter. Con eso, '^[0-9]{10}$' se lee: desde el inicio, diez dígitos, y fin — un teléfono limpio."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Control de calidad de los teléfonos","code":"-- Los teléfonos BIEN capturados: exactamente 10 dígitos\nSELECT nombre, telefono\nFROM   pacientes\nWHERE  REGEXP_LIKE(telefono, '^[0-9]{10}$');\n\n-- Y la limpieza masiva: fuera todo lo que no sea dígito\nSELECT telefono,\n       REGEXP_REPLACE(telefono, '[^0-9]', '') AS telefono_limpio\nFROM   pacientes;","result":{"columns":["TELEFONO","TELEFONO_LIMPIO"],"rows":[["55-1234-5678","5512345678"],["(33) 8765 4321","3387654321"],["4491112233","4491112233"]],"note":"El patrón [^0-9] — el ^ DENTRO de los corchetes significa negación — atrapa todo lo que NO es dígito, y REGEXP_REPLACE lo borra. La misma consulta con NOT REGEXP_LIKE(...) encuentra los mal capturados: control de calidad en una línea."}}$j$),
  (3, 'texto', $j${"title":"Dónde brillan (y cuándo no usarlas)","body":"Tres escenarios donde las REGEXP_* pagan su sueldo. CALIDAD: encontrar lo MAL capturado negando el patrón — WHERE NOT REGEXP_LIKE(telefono, '^[0-9]{10}$') lista los teléfonos con guiones, espacios o letras que se colaron antes de que existiera tu CHECK. EXTRACCIÓN: REGEXP_SUBSTR(correo, '[^@]+$') saca el dominio después de la arroba. LIMPIEZA: el REGEXP_REPLACE del ejemplo, normalizando miles de filas en una orden. Y la advertencia del oficio: las REGEXP_* son más CARAS que LIKE — el motor de patrones trabaja duro en cada fila. Se usan cuando LIKE genuinamente no alcanza, no para lucirse: 'empieza con Dra.' es LIKE 'Dra.%', no una expresión regular."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué filas acepta WHERE REGEXP_LIKE(telefono, '^[0-9]{10}$')?","options":["Las que contienen al menos un dígito","Las que empiezan con el número 10","Las que son exactamente diez dígitos","Las de teléfonos claramente extranjeros"],"correctIndex":2,"feedback":{"correct":"Correcto. ^ ancla el inicio, [0-9]{10} exige diez dígitos, $ ancla el final: nada más cabe.","incorrect":"El patrón se lee: inicio ^, diez dígitos [0-9]{10}, final $. Solo pasan los teléfonos perfectamente limpios."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Para BORRAR de un texto todo lo que no sea dígito (guiones, espacios, paréntesis), la herramienta es…","options":["REGEXP_LIKE con el patrón adecuado","REGEXP_COUNT contando los dígitos","TRIM, que poda las orillas del texto","REGEXP_REPLACE con el patrón [^0-9]"],"correctIndex":3,"feedback":{"correct":"Correcto. REPLACE sustituye lo que matchea; con '' lo borra. El ^ dentro de corchetes niega el conjunto.","incorrect":"La sustitución masiva es REGEXP_REPLACE; el patrón [^0-9] (negación dentro de corchetes) atrapa lo que no es dígito."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"'Encuentra los nombres que empiezan con Dra.' — ¿LIKE o REGEXP, y por qué?","options":["LIKE 'Dra.%': el parecido es simple","REGEXP siempre, porque es más moderno","REGEXP, porque LIKE no acepta puntos","Ninguno: eso no se puede consultar"],"correctIndex":0,"feedback":{"correct":"Correcto. La herramienta más simple que resuelva el problema: REGEXP es para los patrones de verdad (formatos, validaciones), no para prefijos.","incorrect":"Un prefijo simple es territorio de LIKE (barato y claro). REGEXP paga cuando el patrón es genuinamente complejo — 10 dígitos exactos, un formato de correo."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — REGEXP_*","points":["REGEXP_LIKE filtra · REGEXP_SUBSTR extrae · REGEXP_REPLACE sustituye · REGEXP_INSTR ubica · REGEXP_COUNT cuenta.","Vocabulario base: [0-9] dígito · {10} exactamente diez · + una o más · ^ inicio · $ fin · [^…] negación.","'^[0-9]{10}$' = teléfono limpio de 10 dígitos exactos.","Brillan en calidad (negar el patrón), extracción y limpieza masiva.","Más caras que LIKE: se usan cuando LIKE no alcanza, no por lucirse."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l06-regexp';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · DML: INSERT, UPDATE, DELETE y MERGE
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"INSERT: filas nuevas, siempre con lista","body":"El DML manipula filas, y su primera orden es INSERT INTO tabla (columnas) VALUES (valores). La lista de columnas parece opcional — Oracle acepta INSERT sin ella, emparejando por posición — pero el oficio la exige SIEMPRE: el INSERT posicional se rompe (o peor, cruza datos en silencio) el día que un ALTER agregue una columna. Con lista, cada valor declara su destino, las columnas no mencionadas reciben su DEFAULT (¿recuerdas el precio 0 y el refrigerado 'N' del CREATE?) o nulo, y el INSERT sobrevive a la evolución de la tabla. Para cargas desde otra consulta existe INSERT INTO tabla (columnas) SELECT …: el resultado completo de la consulta entra como filas nuevas."}$j$),
  (2, 'texto', $j${"title":"UPDATE y DELETE: la regla innegociable","body":"UPDATE tabla SET columna = valor WHERE condición modifica; DELETE FROM tabla WHERE condición borra. Y aquí está LA regla innegociable de este curso: UPDATE y DELETE se escriben SIEMPRE con su WHERE explícito y PENSADO. Sin WHERE, afectan TODAS las filas de la tabla — sin pregunta de confirmación, sin aviso: un UPDATE distraído puede ponerle el mismo costo a cincuenta mil citas en un parpadeo. El procedimiento del oficio para tocar datos en producción: (1) un SELECT con el MISMO WHERE, para ver exactamente qué filas serán tocadas; (2) el UPDATE o DELETE; (3) verificar que el conteo de filas afectadas coincida con lo esperado; (4) solo entonces confirmar. Mientras no confirmes, el DML se revierte con ROLLBACK — a diferencia del TRUNCATE, y ya sabes por qué. El manejo completo de la transacción llega en su propio módulo."}$j$),
  (3, 'ejemplo_sql', $j${"title":"El procedimiento seguro, paso a paso","code":"-- 1 · Ver EXACTAMENTE qué se va a tocar (el mismo WHERE)\nSELECT cita_id, costo\nFROM   citas\nWHERE  cita_id = 519;\n\n-- 2 · Tocar exactamente eso\nUPDATE citas\nSET    costo = 350\nWHERE  cita_id = 519;\n\n-- 3 · El conteo confirma el alcance: '1 row updated.'\n--     Si dijera '50000 rows updated.'… ROLLBACK y a revisar.","result":{"columns":["RESULTADO"],"rows":[["1 row updated."]],"note":"El SELECT previo con el mismo WHERE es el ensayo general; el conteo de filas afectadas es el veredicto. Una fila esperada, una fila tocada: ahora sí se puede confirmar."}}$j$),
  (4, 'ejemplo_sql', $j${"title":"MERGE: el 'actualiza o inserta' en una orden","code":"-- Sincronizar el catálogo con la lista del proveedor:\n-- lo que ya existe se actualiza, lo nuevo se inserta.\nMERGE INTO medicamentos m\nUSING catalogo_proveedor p\nON (m.medicamento_id = p.medicamento_id)\nWHEN MATCHED THEN\n  UPDATE SET m.precio = p.precio\nWHEN NOT MATCHED THEN\n  INSERT (medicamento_id, nombre, precio)\n  VALUES (p.medicamento_id, p.nombre, p.precio);","result":{"columns":["RESULTADO"],"rows":[["27 rows merged."]],"note":"El clásico 'upsert' sin scripts con ifs: una orden decide fila por fila — coincide → UPDATE; no existe → INSERT. La condición del ON es el criterio de identidad entre las dos fuentes."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué el oficio exige la LISTA DE COLUMNAS en todo INSERT, si Oracle acepta omitirla?","options":["Porque sin la lista todo resulta más lento","El posicional se rompe si un ALTER cambia","Porque la lista es obligatoria desde 12c","Es únicamente una cuestión de estética"],"correctIndex":1,"feedback":{"correct":"Correcto. El posicional apuesta a que la tabla jamás cambie — y las tablas cambian. La lista es el seguro.","incorrect":"Sin lista, los valores se emparejan por posición: un ALTER posterior los descuadra. La lista declara el destino de cada valor."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Vas a corregir el costo de UNA cita. ¿Cuál es el procedimiento seguro ANTES del UPDATE?","options":["Ejecutarlo rápido para no pensarlo de más","Hacer un respaldo completo de toda la base","Un SELECT con el mismo WHERE, y verificar","Desactivar todas las constraints de la tabla"],"correctIndex":2,"feedback":{"correct":"Correcto. Ensayo (SELECT), ejecución (UPDATE con WHERE), veredicto (el conteo), y solo entonces confirmar.","incorrect":"El procedimiento del oficio: SELECT previo con el mismo WHERE → UPDATE → verificar conteo → confirmar. Cada paso atrapa un error distinto."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace MERGE que un UPDATE y un INSERT sueltos no logran igual de bien?","options":["Borra los duplicados de la tabla","Es solamente un alias del UPDATE","Convierte las tablas en vistas","Sincroniza en una orden: el upsert"],"correctIndex":3,"feedback":{"correct":"Correcto. La decisión actualizar-o-insertar viaja dentro de la orden: sin scripts con ifs, sin dos pasadas.","incorrect":"MERGE = WHEN MATCHED THEN UPDATE + WHEN NOT MATCHED THEN INSERT, decidido fila a fila contra la condición del ON."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — DML","points":["INSERT SIEMPRE con lista de columnas: el posicional se rompe cuando la tabla evoluciona.","Columnas no mencionadas → DEFAULT o nulo · INSERT INTO … SELECT para cargas desde consultas.","REGLA INNEGOCIABLE: UPDATE y DELETE siempre con WHERE explícito y pensado.","Procedimiento seguro: SELECT con el mismo WHERE → ejecutar → verificar conteo → confirmar.","El DML no confirmado se revierte con ROLLBACK · MERGE = actualiza-o-inserta en una orden atómica."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l07-dml-merge';

-- ═════════════════════════════════════════════════════════════════════
-- L08 · Práctica: el reporte de dirección (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"La dirección del hospital pide el reporte de citas de alto costo para el comité de finanzas. Escribe la consulta completa sobre la tabla citas (columnas: cita_id, paciente_id, fecha, estado, costo — el costo puede venir nulo).","instructions":["Proyecta tres columnas: paciente_id, fecha, y el costo protegido contra nulos: NVL(costo, 0) con el alias costo_real (usa AS).","Consulta la tabla citas.","Filtra: solo las citas con costo mayor o igual a 500.","Ordena de mayor a menor costo (DESC): la más cara primero."],"initialCode":"-- Reporte para el comité: citas de alto costo (>= 500),\n-- la más cara primero. Columnas: paciente_id, fecha, costo_real.\n\nSELECT paciente_id\nFROM   citas;","validators":["select\\s+paciente_id\\s*,\\s*fecha\\s*,\\s*nvl\\s*\\(\\s*costo\\s*,\\s*0\\s*\\)\\s+as\\s+costo_real","from\\s+citas","where\\s+costo\\s*>=\\s*500","order\\s+by\\s+(costo_real|costo|nvl\\s*\\(\\s*costo\\s*,\\s*0\\s*\\)|3)\\s+desc"],"mockOutput":{"columns":["PACIENTE_ID","FECHA","COSTO_REAL"],"rows":[["12","2026-07-02","950"],["7","2026-06-21","800"],["23","2026-05-30","640"],["31","2026-06-05","520"]],"note":"El reporte del comité: solo las citas de 500 en adelante, la más cara arriba, y ningún nulo saboteando la columna de costos."},"hints":["La lista del SELECT: paciente_id, fecha, NVL(costo, 0) AS costo_real — en ese orden y con el alias exacto.","Las cláusulas van en orden: SELECT → FROM → WHERE → ORDER BY. El filtro es WHERE costo >= 500.","Para ordenar de mayor a menor: ORDER BY costo_real DESC (también vale ORDER BY costo DESC)."],"successMessage":"Reporte entregado: proyección con NVL, filtro con WHERE y orden explícito con DESC — la anatomía completa de una consulta profesional. La dirección tiene sus números; tú tienes las cuatro cláusulas dominadas.","failMessage":"Revisa las cuatro piezas: SELECT paciente_id, fecha, NVL(costo, 0) AS costo_real · FROM citas · WHERE costo >= 500 · ORDER BY costo_real DESC. Los alias y el orden de las cláusulas importan."}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-l08-practica-consultas';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La séptima región","body":"Byte ya no construye la base: CONVERSA con ella. Once preguntas custodian esta región — proyección, filtros, funciones, conversiones, nulos, patrones y el DML con su regla innegociable. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué devuelve SELECT DISTINCT estado, medico_id FROM citas?","options":["Las combinaciones estado+médico sin repetir","Los estados, cada uno una sola vez","Los médicos, cada uno una sola vez","Una fila por cada estado con el primer médico"],"correctIndex":0,"feedback":{"correct":"Correcto. DISTINCT des-duplica parejas completas, no columnas sueltas.","incorrect":"DISTINCT mira la COMBINACIÓN de todas las columnas listadas: solo la pareja repetida desaparece."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Hay citas con costo nulo, pero WHERE costo = NULL devuelve cero filas. La consulta correcta es…","options":["WHERE costo == NULL, con doble igual","WHERE costo IS NULL: la pregunta válida","WHERE NULL = costo, invirtiendo el orden","WHERE costo LIKE NULL, con comodín"],"correctIndex":1,"feedback":{"correct":"Correcto. Nada es igual a nulo, ni otro nulo: IS NULL es la única pregunta que responde.","incorrect":"El nulo esquiva al = por definición ('desconocido no es igual a nada'): IS NULL / IS NOT NULL son sus preguntas."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En un patrón LIKE, ¿qué diferencia hay entre los comodines % y _ ?","options":["Ninguna: son dos comodines idénticos","% es para números y _ para las letras","% acepta cualquier cosa; _ un carácter","_ acepta cualquier cosa y % un carácter"],"correctIndex":2,"feedback":{"correct":"Correcto. 'A%' = empieza con A; 'A_' = A y exactamente un carácter más.","incorrect":"% = cero o más caracteres; _ = uno exacto. Con eso se leen todos los patrones LIKE."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Para un corte de caja, ¿ROUND(total, 2) o TRUNC(total, 2)? ¿Cuál es la diferencia?","options":["Son totalmente equivalentes en dinero","TRUNC redondea bastante mejor que ROUND","ROUND solo funciona con enteros puros","ROUND redondea; TRUNC corta el milésimo"],"correctIndex":3,"feedback":{"correct":"Correcto. 87.966 → 87.97 con ROUND, 87.96 con TRUNC: en dinero, la elección es política contable, no capricho.","incorrect":"ROUND mira el siguiente dígito y redondea; TRUNC corta. En cortes de caja la diferencia se acumula."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué el oficio prefiere TO_DATE('03/07/2026', 'DD/MM/YYYY') en vez de dejar que Oracle convierta el texto solo?","options":["La implícita depende de la sesión","Porque TO_DATE es una función más corta","Porque la implícita viene deshabilitada","Porque valida contra el calendario maya"],"correctIndex":0,"feedback":{"correct":"Correcto. La máscara explícita fija el significado en cualquier entorno — y evita el error silencioso más caro: el que no truena.","incorrect":"La implícita lee según la configuración de la sesión: 03/07 es ambiguo. TO_DATE con máscara significa lo mismo en todas partes."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"NVL(costo, 0) y COALESCE(movil, fijo, 'sin contacto'). ¿Qué hace cada una?","options":["Hacen lo mismo con distinto nombre","NVL cubre un nulo; COALESCE, una lista","NVL cuenta nulos y COALESCE los borra","Ambas convierten los nulos en texto"],"correctIndex":1,"feedback":{"correct":"Correcto. NVL es el caso simple (dos argumentos); COALESCE generaliza a n respaldos en orden.","incorrect":"NVL(x, sustituto) cubre un nulo; COALESCE(a, b, c…) entrega el primer no nulo de la lista."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál regla clasificaría tarifas por RANGO de costo ('premium' si costo >= 800, 'estandar' si >= 300, si no 'social')?","options":["DECODE(costo, 800, 'premium', 300, 'estandar')","Un LIKE con comodines sobre el costo","CASE WHEN costo >= 800 … ELSE 'social' END","NVL2(costo, 'premium', 'social') directo"],"correctIndex":2,"feedback":{"correct":"Correcto. DECODE solo compara igualdades — costo=800 exacto, no >= 800. La lógica de rangos pide CASE.","incorrect":"DECODE empareja por IGUALDAD (800 exacto): los rangos exigen CASE, que evalúa condiciones en orden."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué encuentra WHERE NOT REGEXP_LIKE(telefono, '^[0-9]{10}$')?","options":["Los teléfonos perfectamente válidos","Los teléfonos de exactamente diez dígitos limpios","Únicamente los teléfonos que son nulos","Los teléfonos mal capturados, para limpiar"],"correctIndex":3,"feedback":{"correct":"Correcto. Negar el patrón de lo correcto lista lo incorrecto: guiones, espacios, letras y capturas viejas salen a la luz.","incorrect":"El patrón describe el teléfono perfecto; el NOT lo invierte: aparecen los que necesitan limpieza."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Ejecutas UPDATE citas SET costo = 350 y Oracle responde '48512 rows updated.' ¿Qué pasó y qué haces?","options":["Faltó el WHERE: ROLLBACK inmediato","Todo bien: era exactamente lo esperado","Nada grave: Oracle pregunta antes de guardar","Se actualizó solo la primera de las citas"],"correctIndex":0,"feedback":{"correct":"Correcto. El conteo delató el desastre a tiempo: ROLLBACK lo deshace porque aún no se confirmaba. La regla innegociable existe por esto.","incorrect":"48512 filas = UPDATE sin WHERE. El DML sin confirmar se revierte con ROLLBACK — por eso el conteo se verifica SIEMPRE antes de confirmar."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Cada lunes llega el catálogo del proveedor: medicamentos que ya existen (precio nuevo) y medicamentos nunca vistos. La orden idónea:","options":["Un DELETE completo de todo y luego un INSERT masivo","MERGE: actualiza lo que existe, inserta lo nuevo","Dos UPDATEs seguidos, uno tras otro","Un TRUNCATE y una recarga completa"],"correctIndex":1,"feedback":{"correct":"Correcto. El upsert de manual: sincronización en una orden atómica, sin borrar historia ni escribir scripts con ifs.","incorrect":"Borrar y recargar destruye lo que no vino en el archivo (y el TRUNCATE ni ROLLBACK tiene). MERGE sincroniza: actualiza lo que existe, inserta lo nuevo."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'debes corregir el costo de UNA cita en la base de producción. Descríbeme tu procedimiento completo.' Tu respuesta senior:","options":["Un UPDATE rápido y a otra cosa: es una sola fila","Le pido a otra persona con más experiencia que lo haga","SELECT con el mismo WHERE, UPDATE, verifico conteo y confirmo","Un TRUNCATE de la tabla y una recarga completa desde el respaldo"],"correctIndex":2,"feedback":{"correct":"Impecable. Ensayo, ejecución acotada por PK, veredicto por conteo y confirmación consciente: el procedimiento que protege datos reales.","incorrect":"La respuesta senior tiene cuatro pasos: SELECT previo con el mismo WHERE → UPDATE por PK → verificar el conteo → confirmar (o ROLLBACK). La red existe: se usa."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm05-x01-examen';
