-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 019 — SQL con Oracle · m06: Joins y subqueries
-- ═══════════════════════════════════════════════════════════════════
-- Cubre la Parte IX en su tramo multi-tabla: INNER JOIN en sintaxis
-- ANSI, OUTER joins (LEFT/RIGHT/FULL), self join (la recursiva del
-- m3a hecha consulta), CROSS JOIN/producto cartesiano, NATURAL JOIN
-- y USING (y por qué el oficio prefiere ON), operadores de conjunto
-- (UNION, UNION ALL, INTERSECT, MINUS) y subconsultas: de una fila,
-- multifila (IN/ANY/ALL), correladas, EXISTS/NOT EXISTS con la
-- trampa de NOT IN + nulos, e inline views.
-- Práctica de editor (regex+mockOutput): el anti-join clásico
-- (pacientes sin citas: LEFT JOIN + IS NULL).
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- OJO: SQL con Oracle está PUBLICADO — esta migración sale en vivo.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 011 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm06-joins-subqueries'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m06-l01-inner-join',      'JOIN: las tablas conversan',            'leccion',  20, 1),
       ('m06-l02-outer-joins',     'OUTER joins: nadie se queda fuera',     'leccion',  20, 2),
       ('m06-l03-self-cross',      'Self join, CROSS y los joins con trampa','leccion', 20, 3),
       ('m06-l04-conjuntos',       'Operadores de conjunto',                'leccion',  20, 4),
       ('m06-l05-subconsultas',    'Subconsultas: una fila y multifila',    'leccion',  20, 5),
       ('m06-l06-correladas',      'Correladas, EXISTS e inline views',     'leccion',  20, 6),
       ('m06-l07-practica-joins',  'Práctica: los pacientes fantasma',      'practica', 20, 7),
       ('m06-x01-examen',          'Examen: Joins y subqueries',            'examen',   40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm06-joins-subqueries';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · JOIN: las tablas conversan
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La promesa de las FKs, cobrada","body":"Normalizaste con disciplina: los datos del paciente viven en pacientes, los de la cita en citas, y una FK los conecta. El JOIN es el momento de cobrar esa promesa — combinar filas de dos tablas usando la conexión que diseñaste. La sintaxis ANSI (la del estándar, la de este curso): FROM citas c JOIN pacientes p ON p.paciente_id = c.paciente_id. Tres piezas: las tablas con su ALIAS corto (c, p — obligatorios en la práctica: dos tablas pueden tener columnas homónimas y cada columna debe declarar su dueño), la palabra JOIN, y el ON con la condición de emparejamiento — casi siempre FK = PK, la ruta que el modelo dejó pavimentada. El JOIN a secas es INNER: solo salen las filas que ENCUENTRAN pareja en la otra tabla; la cita sin paciente válido (que tu FK ya impide) o el paciente sin citas, simplemente no aparecen."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La agenda por fin dice nombres","code":"SELECT c.fecha,\n       p.nombre       AS paciente,\n       m.nombre       AS medico,\n       c.costo\nFROM   citas c\nJOIN   pacientes p ON p.paciente_id = c.paciente_id\nJOIN   medicos   m ON m.medico_id   = c.medico_id\nORDER  BY c.fecha;","result":{"columns":["FECHA","PACIENTE","MEDICO","COSTO"],"rows":[["2026-07-02","Laura Méndez","Dra. Ríos","950"],["2026-07-14","Hugo Castañeda","Dr. Salas","350"],["2026-07-14","Sofía Aguirre","Dra. Ríos","640"]],"note":"Dos JOINs encadenados: citas empareja con pacientes por una FK y con medicos por otra. Cada columna declara su dueño con el alias (c.fecha, p.nombre) — y la consulta se lee como la frase que el modelo prometió: qué paciente ve a qué médico, cuándo y por cuánto."}}$j$),
  (3, 'texto', $j${"title":"Lo que el INNER calla","body":"El INNER JOIN es honesto pero silencioso: descarta sin avisar todo lo que no empareja. Consecuencia práctica que debes anticipar: si el reporte 'citas con su paciente' devuelve MENOS filas que la tabla citas, no es un bug del JOIN — es una FK opcional con nulos (la cita sin médico asignado no encuentra pareja) o un emparejamiento mal escrito en el ON. La disciplina del oficio: conocer el CONTEO esperado antes de confiar en el resultado, y sospechar del ON antes que del motor. Y una nota de estilo que te ahorrará discusiones: la sintaxis vieja de Oracle ponía los joins en el WHERE (FROM citas, pacientes WHERE …) — funciona, pero mezcla emparejamiento con filtrado; la ANSI separa responsabilidades: ON empareja, WHERE filtra. En este curso, siempre ANSI."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En la sintaxis ANSI de un JOIN, ¿qué papel juega la cláusula ON?","options":["Filtra filas después de combinar","Declara la condición de EMPAREJAMIENTO entre las dos tablas (casi siempre FK = PK) — el WHERE queda libre para filtrar","Ordena el resultado","Nombra la consulta"],"correctIndex":1,"feedback":{"correct":"Correcto. ON empareja, WHERE filtra: la separación de responsabilidades que la sintaxis vieja mezclaba.","incorrect":"El ON dice CÓMO se conectan las tablas (la ruta FK→PK del modelo); filtrar el resultado es trabajo del WHERE."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un INNER JOIN entre dos tablas, ¿qué filas devuelve?","options":["Todas las de ambas tablas","Solo las que ENCUENTRAN PAREJA en la otra tabla según el ON: lo que no empareja se descarta sin aviso","Todas las de la primera tabla","Las que no tienen pareja"],"correctIndex":1,"feedback":{"correct":"Correcto. El INNER es un club de parejas: los solteros de ambos lados quedan fuera, silenciosamente.","incorrect":"INNER = solo coincidencias. Conservar a los que no tienen pareja es trabajo de los OUTER joins (siguiente lección)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué el oficio exige ALIAS de tabla (c, p) y prefijos en cada columna (c.fecha, p.nombre) al hacer JOIN?","options":["Por velocidad","Porque dos tablas pueden tener columnas HOMÓNIMAS: cada columna debe declarar su dueño, o la consulta se vuelve ambigua (y Oracle la rechaza si hay conflicto)","Es un requisito de Oracle 12c","Por tradición, sin razón técnica"],"correctIndex":1,"feedback":{"correct":"Correcto. pacientes.nombre y medicos.nombre existen a la vez: sin dueño declarado, 'nombre' es ambiguo.","incorrect":"Con varias tablas en juego, las columnas homónimas (nombre, id, fecha…) exigen dueño: el alias corto lo declara sin ruido."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — INNER JOIN","points":["JOIN combina filas de dos tablas por la ruta que el modelo pavimentó (FK = PK).","Sintaxis ANSI: FROM tabla1 alias JOIN tabla2 alias ON condición — ON empareja, WHERE filtra.","Alias de tabla y columnas con dueño (c.fecha): las homónimas exigen claridad.","INNER = solo coincidencias: lo que no empareja se descarta SIN aviso.","Menos filas de las esperadas → sospecha de FKs con nulos o del ON, no del motor."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-l01-inner-join';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · OUTER joins: nadie se queda fuera
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuando los sin-pareja son la noticia","body":"El negocio pregunta cosas que el INNER no puede responder: ¿qué pacientes NO han venido nunca? ¿qué medicamentos NO se han recetado? Los sin-pareja son justo la noticia. Los OUTER joins conservan filas aunque no emparejen: LEFT JOIN conserva TODAS las filas de la tabla izquierda (las que no encuentran pareja salen con NULOS en las columnas del lado derecho); RIGHT JOIN es el espejo (conserva la derecha); FULL JOIN conserva ambas orillas. En la práctica, el oficio escribe casi todo como LEFT — poniendo a la izquierda la tabla cuyas filas no quieres perder — porque leer siempre en la misma dirección evita errores. Los nulos que rellenan el lado sin pareja no son datos: son la marca de 'aquí no hubo pareja' — y esa marca es explotable."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El tablero completo (y los fantasmas al final)","code":"SELECT p.nombre,\n       c.fecha,\n       c.costo\nFROM   pacientes p\nLEFT   JOIN citas c ON c.paciente_id = p.paciente_id\nORDER  BY p.nombre;","result":{"columns":["NOMBRE","FECHA","COSTO"],"rows":[["Hugo Castañeda","2026-07-14","350"],["Laura Méndez","2026-07-02","950"],["Renata Ibarra","(null)","(null)"],["Sofía Aguirre","2026-07-14","640"]],"note":"Renata jamás ha agendado una cita: el INNER la habría borrado del reporte; el LEFT la conserva con nulos en las columnas de citas. Esos nulos son la marca de 'sin pareja' — y la próxima línea del oficio los convierte en la respuesta: WHERE c.cita_id IS NULL deja SOLO a los pacientes sin citas."}}$j$),
  (3, 'texto', $j${"title":"El anti-join: la joya del LEFT","body":"La combinación LEFT JOIN + IS NULL es tan útil que tiene nombre propio: el ANTI-JOIN. La receta: LEFT JOIN para conservar a todos los de la izquierda, y WHERE derecha.columna_no_nullable IS NULL para quedarte SOLO con los que no emparejaron — pregunta por una columna que jamás sería nula si la pareja existiera (la PK del lado derecho es la elección segura). 'Pacientes sin citas', 'medicamentos nunca recetados', 'médicos sin agenda esta semana': todas son la misma consulta con distinto disfraz. Una advertencia fina: si necesitas FILTRAR el lado derecho (solo citas de 2026), esa condición va en el ON, no en el WHERE — en el WHERE mataría los nulos y tu LEFT degeneraría en INNER sin que lo notes."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En un LEFT JOIN, las filas de la tabla izquierda que NO encuentran pareja…","options":["Se descartan","Se CONSERVAN, con NULOS rellenando las columnas del lado derecho — la marca de 'sin pareja'","Se duplican","Generan un error"],"correctIndex":1,"feedback":{"correct":"Correcto. El LEFT no pierde a nadie de la izquierda; los nulos del lado derecho delatan a los sin-pareja.","incorrect":"Esa es la diferencia con el INNER: el LEFT conserva toda la izquierda y marca con nulos donde no hubo pareja."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué devuelve el 'anti-join' — LEFT JOIN citas c … WHERE c.cita_id IS NULL — sobre pacientes?","options":["Los pacientes con más citas","EXACTAMENTE los pacientes SIN ninguna cita: el LEFT conserva a todos y el IS NULL sobre la PK derecha filtra a los que no emparejaron","Las citas sin costo","Todos los pacientes"],"correctIndex":1,"feedback":{"correct":"Correcto. La joya del LEFT: los nulos de 'sin pareja' se vuelven la respuesta. La PK derecha es la columna segura para preguntar.","incorrect":"cita_id es PK de citas: solo es nulo cuando NO hubo pareja. El filtro deja únicamente a los pacientes fantasma."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En un LEFT JOIN quieres conservar a TODOS los pacientes pero contar solo sus citas de 2026. ¿Dónde va la condición de fecha?","options":["En el WHERE, como siempre","En el ON: en el WHERE mataría las filas con nulos y el LEFT degeneraría en INNER — perderías a los pacientes sin citas","En el ORDER BY","En el SELECT"],"correctIndex":1,"feedback":{"correct":"Correcto. El WHERE filtra DESPUÉS de combinar: los sin-pareja (fecha nula) no pasarían el filtro. En el ON, la condición solo limita qué parejas se forman.","incorrect":"La condición sobre el lado derecho de un LEFT va en el ON: puesta en el WHERE elimina los nulos de 'sin pareja' y el LEFT se comporta como INNER."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — OUTER joins","points":["LEFT conserva toda la izquierda · RIGHT la derecha · FULL ambas orillas.","Los nulos del lado sin pareja no son datos: son la marca de 'no emparejó'.","El oficio escribe casi todo como LEFT: leer siempre en la misma dirección evita errores.","ANTI-JOIN = LEFT JOIN + WHERE pk_derecha IS NULL: 'los que no tienen' (pacientes sin citas).","Filtros del lado derecho van en el ON — en el WHERE degeneran el LEFT en INNER."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-l02-outer-joins';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Self join, CROSS y los joins con trampa
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Self join: la oreja de cerdo, consultada","body":"¿Recuerdas la relación recursiva — MEDICO supervisado por MEDICO, con su FK apuntando a la propia tabla? El SELF JOIN es su consulta natural: la tabla se une CONSIGO MISMA, y los alias dejan de ser cortesía para volverse indispensables — son lo único que distingue los dos papeles. FROM medicos m JOIN medicos jefe ON jefe.medico_id = m.supervisor_id: la misma tabla dos veces, una como 'el médico', otra como 'su jefe'. Detalle que ya dominas: como supervisor_id es opcional (la jefa de servicio no tiene supervisor), el JOIN a secas la excluiría del reporte — un LEFT JOIN la conserva con jefe en nulo. El modelado del m3a y los joins de este módulo se saludan."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El organigrama en una consulta","code":"SELECT m.nombre        AS medico,\n       jefe.nombre     AS supervisor\nFROM   medicos m\nLEFT   JOIN medicos jefe\n       ON jefe.medico_id = m.supervisor_id\nORDER  BY supervisor NULLS FIRST;","result":{"columns":["MEDICO","SUPERVISOR"],"rows":[["Dra. Ríos","(null)"],["Dr. Salas","Dra. Ríos"],["Dra. Peña","Dra. Ríos"]],"note":"Una tabla, dos papeles: los alias m y jefe desdoblan a medicos igual que el diagrama de la oreja de cerdo. El LEFT conserva a la Dra. Ríos — la punta de la pirámide, sin supervisor — y NULLS FIRST la muestra arriba."}}$j$),
  (3, 'texto', $j${"title":"CROSS, NATURAL y USING: conócelos para esquivarlos","body":"Tres parientes que debes reconocer — dos de ellos para no usarlos por accidente. CROSS JOIN produce el PRODUCTO CARTESIANO: cada fila de una tabla con CADA fila de la otra — 1,000 pacientes × 5,000 citas = 5 millones de filas. Tiene usos legítimos (generar combinaciones: todas las tallas × todos los colores), pero en la vida real suele ser un ACCIDENTE: el join al que se le olvidó el ON (en la sintaxis vieja, la coma sin WHERE). Si una consulta tarda una eternidad y devuelve millones, busca el join sin condición. NATURAL JOIN empareja SOLO por nombres de columna iguales en ambas tablas — magia frágil: funciona hoy, y el día que alguien agregue una columna homónima (activo, notas…), tu consulta cambia de significado EN SILENCIO. JOIN … USING (columna) es el punto medio honesto (declara la columna, sin dueños). El oficio prefiere ON: explícito, inmune a los renombres y evoluciones de las tablas."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En un self join (una tabla unida consigo misma), ¿qué vuelve indispensables a los ALIAS?","options":["La velocidad","Son lo ÚNICO que distingue los dos papeles de la misma tabla (m = el médico, jefe = su supervisor): sin alias, la consulta no puede referirse a cada copia","Un requisito de licencia","Nada: son opcionales"],"correctIndex":1,"feedback":{"correct":"Correcto. La tabla aparece dos veces: los alias desdoblan los papeles, como en el diagrama de la recursiva.","incorrect":"Con la misma tabla dos veces en el FROM, solo los alias distinguen '¿cuál medicos?': el papel de cada copia."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Una consulta con dos tablas tarda una eternidad y devuelve millones de filas absurdas. ¿El sospechoso número uno?","options":["Falta un índice","Un PRODUCTO CARTESIANO accidental: un join SIN condición de emparejamiento (el ON olvidado) — cada fila se combinó con TODAS las de la otra tabla","El servidor está lento","Demasiados alias"],"correctIndex":1,"feedback":{"correct":"Correcto. 1,000 × 5,000 = 5 millones: la explosión cartesiana delata al join sin ON.","incorrect":"Millones de combinaciones absurdas = producto cartesiano: revisa que cada JOIN tenga su ON antes de culpar al servidor."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué el oficio evita NATURAL JOIN aunque 'funcione'?","options":["Porque es más lento siempre","Porque empareja por nombres de columna IGUALES: si mañana ambas tablas ganan una columna homónima, la consulta cambia de significado EN SILENCIO — la fragilidad disfrazada de magia","Porque no existe en Oracle","Porque exige alias"],"correctIndex":1,"feedback":{"correct":"Correcto. El NATURAL apuesta a que los nombres nunca coincidan por accidente — y las tablas evolucionan. ON es explícito e inmune.","incorrect":"El peligro del NATURAL es silencioso: una columna homónima nueva (activo, notas) cambia el emparejamiento sin avisar. Por eso: ON."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Self, CROSS y las trampas","points":["SELF JOIN: la tabla consigo misma; los alias son los dos papeles (m, jefe) — la recursiva del m3a, consultada.","La punta de la pirámide exige LEFT (supervisor nulo).","CROSS JOIN = producto cartesiano: legítimo para combinaciones, pero casi siempre un ON olvidado.","NATURAL JOIN empareja por nombres iguales: frágil y silencioso — evítalo.","USING declara la columna; ON es el estándar del oficio: explícito e inmune a la evolución."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-l03-self-cross';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Operadores de conjunto
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Apilar resultados: la otra forma de combinar","body":"El JOIN combina tablas HORIZONTALMENTE (columnas de aquí y de allá en la misma fila). Los OPERADORES DE CONJUNTO apilan resultados VERTICALMENTE: dos consultas completas, un solo resultado. UNION junta ambos resultados Y ELIMINA duplicados; UNION ALL junta TODO sin deduplicar — y es más rápido, porque deduplicar obliga a ordenar y comparar millones de filas: si sabes que no hay duplicados (o los quieres), UNION ALL es la elección profesional. INTERSECT devuelve solo lo que aparece EN AMBOS resultados. MINUS — el nombre Oracle del EXCEPT estándar — devuelve lo del primero QUE NO ESTÁ en el segundo: la resta de conjuntos. Las reglas del juego: ambas consultas deben tener el MISMO número de columnas, de tipos COMPATIBLES y en el mismo orden; los nombres de columna los dicta la PRIMERA consulta; y el ORDER BY va UNA sola vez, al final de todo."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El directorio unificado del hospital","code":"SELECT nombre, 'paciente' AS tipo FROM pacientes\nUNION ALL\nSELECT nombre, 'medico'   AS tipo FROM medicos\nORDER  BY nombre;\n\n-- ¿Qué medicamentos recetados este año TAMBIÉN se recetaron el pasado?\nSELECT medicamento_id FROM recetas_2026\nINTERSECT\nSELECT medicamento_id FROM recetas_2025;","result":{"columns":["NOMBRE","TIPO"],"rows":[["Dr. Salas","medico"],["Dra. Ríos","medico"],["Hugo Castañeda","paciente"],["Laura Méndez","paciente"]],"note":"UNION ALL apila los dos directorios sin pagar deduplicación (una persona no puede estar dos veces), la columna literal 'tipo' recuerda de qué consulta vino cada fila, y el ORDER BY único cierra el conjunto completo."}}$j$),
  (3, 'texto', $j${"title":"UNION vs UNION ALL: la elección que se nota","body":"La diferencia entre UNION y UNION ALL parece cosmética y es de INGENIERÍA. UNION deduplica: para lograrlo, el motor debe comparar todas las filas del resultado combinado — trabajo real, memoria real, tiempo real. UNION ALL simplemente concatena. La pregunta correcta antes de elegir: ¿PUEDEN existir duplicados entre los dos resultados, y me estorban? Pacientes y médicos son conjuntos disjuntos por diseño → UNION ALL sin dudar. Dos listas de correos de campañas distintas que pueden compartir gente → UNION, y el costo se paga con gusto. Elegir UNION 'por si acaso' en conjuntos disjuntos es pagar peaje en una carretera vacía; elegir UNION ALL donde sí hay duplicados es enviar dos veces el mismo correo. La elección delata si pensaste en tus datos."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre UNION y UNION ALL?","options":["Ninguna: son sinónimos","UNION elimina duplicados (pagando ordenar y comparar todo); UNION ALL concatena sin deduplicar — más rápido, la elección cuando los conjuntos son disjuntos","UNION ALL elimina duplicados","UNION solo acepta dos columnas"],"correctIndex":1,"feedback":{"correct":"Correcto. Deduplicar cuesta trabajo real: se paga solo cuando los duplicados existen y estorban.","incorrect":"UNION deduplica (y cobra por ello); UNION ALL apila tal cual. Conjuntos disjuntos por diseño → UNION ALL."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres los medicamentos recetados en 2025 que YA NO se recetaron en 2026. El operador Oracle correcto:","options":["INTERSECT","MINUS: lo del primer resultado que NO está en el segundo — la resta de conjuntos (recetas_2025 MINUS recetas_2026)","UNION ALL","CROSS JOIN"],"correctIndex":1,"feedback":{"correct":"Correcto. MINUS (el EXCEPT estándar, con nombre Oracle) resta el segundo conjunto del primero.","incorrect":"'Estaba y ya no está' es una resta: MINUS. INTERSECT daría lo contrario — lo que sigue en ambos años."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Al combinar dos consultas con UNION, ¿dónde puede ir el ORDER BY?","options":["Después de cada consulta","UNA sola vez, AL FINAL de todo: ordena el resultado combinado completo","Solo en la primera consulta","En el ON"],"correctIndex":1,"feedback":{"correct":"Correcto. El conjunto se arma primero y se ordena una vez, al final — y los nombres de columna los dicta la primera consulta.","incorrect":"Los operadores de conjunto arman UN resultado: el ORDER BY único va al final y ordena el total combinado."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Operadores de conjunto","points":["JOIN combina horizontal; los operadores de conjunto apilan VERTICAL: dos consultas, un resultado.","UNION deduplica (pagando el costo) · UNION ALL concatena — disjuntos por diseño → UNION ALL.","INTERSECT = lo que está en ambos · MINUS (Oracle) = lo del primero que no está en el segundo.","Reglas: mismo número de columnas, tipos compatibles, mismo orden; nombres los dicta la primera.","ORDER BY una sola vez, al final del conjunto completo."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-l04-conjuntos';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Subconsultas: una fila y multifila
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Una consulta dentro de otra","body":"'Muéstrame las citas más caras que LA CITA 519.' Para responder necesitas primero un dato (el costo de la 519) y luego usarlo como filtro. La SUBCONSULTA hace ambos pasos en una orden: una consulta entre paréntesis cuyo resultado alimenta a la consulta externa — WHERE costo > (SELECT costo FROM citas WHERE cita_id = 519). Oracle resuelve primero la interna, y su resultado se vuelve el valor de comparación. La clasificación que gobierna todo: la subconsulta DE UNA FILA devuelve exactamente un valor, y se usa con los operadores de siempre (=, >, <, >=); la MULTIFILA devuelve varias, y exige operadores que sepan de listas: IN (¿está en la lista?), ANY (¿supera a ALGUNO?), ALL (¿supera a TODOS?)."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El filtro que se calcula solo","code":"-- Una fila: las citas más caras que la cita 519\nSELECT cita_id, fecha, costo\nFROM   citas\nWHERE  costo > (SELECT costo\n                FROM   citas\n                WHERE  cita_id = 519);\n\n-- Multifila: pacientes atendidos por la Dra. Ríos\nSELECT nombre\nFROM   pacientes\nWHERE  paciente_id IN (SELECT paciente_id\n                       FROM   citas\n                       WHERE  medico_id = 3);","result":{"columns":["NOMBRE"],"rows":[["Laura Méndez"],["Sofía Aguirre"]],"note":"La primera subconsulta devuelve UN valor (el costo de la 519, garantizado por la PK) y alimenta al >. La segunda devuelve una LISTA de paciente_id y el IN pregunta membresía — el operador correcto para cada forma."}}$j$),
  (3, 'texto', $j${"title":"El error que te aprenderás de memoria","body":"¿Qué pasa si usas un operador de una fila con una subconsulta que devuelve varias? Oracle revienta con el error más famoso de las subconsultas: ORA-01427, 'single-row subquery returns more than one row'. La lección detrás del error: el operador es una PROMESA sobre cuántas filas vendrán — el = promete una, y la subconsulta lo traicionó. El diagnóstico profesional: no 'cambiar = por IN a ver si jala', sino preguntarte QUÉ debía devolver la subconsulta. ¿Era conceptualmente un valor único y vinieron varios? El WHERE interno está mal (o falta una condición). ¿Era una lista legítima? Entonces sí: IN, ANY o ALL. El error es molesto en desarrollo y valioso siempre: truena HOY en tu pantalla, no mañana en el reporte del director. La subconsulta que 'casi siempre devuelve una fila' es una bomba de tiempo con buen historial."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"WHERE costo > (SELECT costo FROM citas WHERE cita_id = 519). ¿Por qué es seguro usar el operador > aquí?","options":["Porque > acepta listas","Porque la subconsulta filtra por la PK (cita_id): devuelve garantizadamente UNA fila — la promesa del operador de una fila se cumple por diseño","Porque las subconsultas siempre devuelven una fila","No es seguro"],"correctIndex":1,"feedback":{"correct":"Correcto. La PK garantiza unicidad: la subconsulta es de una fila POR DISEÑO, no por suerte.","incorrect":"El > exige un valor único, y filtrar por PK lo garantiza: así se construyen subconsultas de una fila confiables."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Una subconsulta devuelve varios valores y la consulta truena con ORA-01427 ('single-row subquery returns more than one row'). ¿El diagnóstico correcto?","options":["Cambiar = por IN sin pensarlo, para que deje de tronar","Preguntarse QUÉ debía devolver: si era un valor único, el WHERE interno está mal; si era una lista legítima, entonces sí corresponde IN/ANY/ALL","Reiniciar la base","Quitar la subconsulta"],"correctIndex":1,"feedback":{"correct":"Correcto. El error delata una promesa rota: primero se corrige el concepto, no el síntoma. El IN 'para que jale' esconde bugs.","incorrect":"ORA-01427 = el operador prometió una fila y llegaron varias. Diagnostica la intención antes de cambiar el operador."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué pregunta cada operador multifila: IN, ANY y ALL?","options":["Son intercambiables","IN: ¿está en la lista? · > ANY: ¿supera a ALGUNO de la lista? · > ALL: ¿supera a TODOS?","IN cuenta, ANY suma, ALL promedia","IN es de una fila"],"correctIndex":1,"feedback":{"correct":"Correcto. Membresía, alguno y todos: tres preguntas distintas sobre la misma lista.","incorrect":"IN pregunta membresía; ANY compara contra al menos uno; ALL contra todos. Elegir mal cambia la respuesta, no solo la sintaxis."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Subconsultas","points":["Subconsulta = consulta entre paréntesis cuyo resultado alimenta a la externa (se resuelve primero).","DE UNA FILA: un valor, operadores =, >, <… — garantízala filtrando por PK/UNIQUE, no por suerte.","MULTIFILA: lista, operadores IN (membresía), ANY (alguno), ALL (todos).","ORA-01427 = promesa rota: el operador esperaba una fila y llegaron varias.","El diagnóstico corrige el CONCEPTO (¿qué debía devolver?), no el síntoma (cambiar = por IN)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-l05-subconsultas';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Correladas, EXISTS e inline views
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La subconsulta que mira hacia afuera","body":"Las subconsultas de la lección pasada eran independientes: se resuelven una vez y listo. La SUBCONSULTA CORRELADA rompe esa independencia — REFERENCIA a la fila de la consulta externa, así que conceptualmente se evalúa PARA CADA fila de afuera. Su pareja natural es EXISTS: WHERE EXISTS (SELECT 1 FROM citas c WHERE c.paciente_id = p.paciente_id) pregunta, paciente por paciente, '¿existe al menos una cita TUYA?' — la correlación es el c.paciente_id = p.paciente_id que mira hacia afuera. EXISTS no le importa QUÉ devuelva la subconsulta (por eso el SELECT 1 convencional): solo si devuelve ALGO, y el motor puede detenerse en la primera coincidencia. NOT EXISTS pregunta lo contrario — y es la tercera forma de encontrar a los pacientes fantasma, junto al anti-join."}$j$),
  (2, 'texto', $j${"title":"La trampa de NOT IN (memorízala hoy)","body":"'Pacientes sin citas' también se escribe WHERE paciente_id NOT IN (SELECT paciente_id FROM citas)… y aquí vive una de las trampas más crueles de SQL: si esa subconsulta devuelve AUNQUE SEA UN nulo, el NOT IN completo devuelve CERO filas. Sin error, sin aviso: cero. La lógica de tres valores del nulo tiene la culpa — 'no está en una lista que contiene desconocido' no puede afirmarse — pero el efecto práctico es un reporte vacío que parece correcto. Las defensas: NOT EXISTS es INMUNE a los nulos (la elección profesional para 'los que no tienen'), o un IS NOT NULL dentro de la subconsulta si insistes en NOT IN. La pregunta de entrevista clásica es exactamente esta: '¿por qué tu NOT IN devuelve vacío?' — y ahora tienes la respuesta."}$j$),
  (3, 'ejemplo_sql', $j${"title":"Inline view: una consulta como tabla","code":"-- ¿Qué citas superan el costo de referencia de SU médico?\n-- La inline view calcula la referencia; el JOIN la usa.\nSELECT c.cita_id, c.medico_id, c.costo, ref.costo_base\nFROM   citas c\nJOIN   (SELECT medico_id,\n               MIN(costo) + 200 AS costo_base\n        FROM   citas\n        GROUP  BY medico_id) ref\n       ON ref.medico_id = c.medico_id\nWHERE  c.costo > ref.costo_base;","result":{"columns":["CITA_ID","MEDICO_ID","COSTO","COSTO_BASE"],"rows":[["517","3","950","550"],["544","5","820","500"]],"note":"La subconsulta del FROM — la INLINE VIEW — es un resultado tratado como tabla: tiene alias (ref), columnas propias y se joinea como cualquiera. El GROUP BY que ves adentro es un adelanto del próximo módulo; lo importante hoy: el FROM acepta consultas, no solo tablas."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué distingue a una subconsulta CORRELADA de una independiente?","options":["Que usa paréntesis dobles","Que REFERENCIA a la fila de la consulta externa (c.paciente_id = p.paciente_id): conceptualmente se evalúa para CADA fila de afuera","Que devuelve más filas","Que solo funciona con números"],"correctIndex":1,"feedback":{"correct":"Correcto. La correlación es esa mirada hacia afuera: la subconsulta depende de la fila externa en turno.","incorrect":"La correlada menciona columnas de la consulta externa — por eso no puede resolverse una sola vez, como las independientes."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu reporte 'pacientes sin citas' con NOT IN devuelve CERO filas, aunque sabes que existen. ¿La causa más probable?","options":["No hay pacientes sin citas, punto","La subconsulta del NOT IN devuelve algún NULO — y NOT IN con un nulo en la lista devuelve cero filas, sin error ni aviso. Defensa: NOT EXISTS (inmune) o IS NOT NULL adentro","El servidor perdió los datos","Falta un ORDER BY"],"correctIndex":1,"feedback":{"correct":"Correcto. La trampa clásica de la lógica de tres valores: un solo nulo en la lista y el NOT IN entero se vacía. NOT EXISTS no la sufre.","incorrect":"NOT IN + nulo en la subconsulta = resultado vacío silencioso. Por eso el oficio escribe 'los que no tienen' con NOT EXISTS."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es una INLINE VIEW?","options":["Una vista creada con CREATE VIEW","Una subconsulta EN EL FROM, tratada como tabla: tiene alias y columnas, y se joinea como cualquier tabla — sin crear ningún objeto","Un índice temporal","Una tabla duplicada"],"correctIndex":1,"feedback":{"correct":"Correcto. El FROM acepta consultas: el resultado se comporta como tabla desechable, solo para esa consulta.","incorrect":"La inline view vive dentro del FROM de UNA consulta — a diferencia de la vista del m04, no se crea ni queda guardada."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué EXISTS se escribe convencionalmente como EXISTS (SELECT 1 FROM …)?","options":["El 1 es la primera columna de la tabla","Porque a EXISTS no le importa QUÉ devuelve la subconsulta, solo SI devuelve algo: el 1 es un relleno honesto, y el motor puede parar en la primera coincidencia","Porque devuelve el número de filas","Es obligatorio por sintaxis"],"correctIndex":1,"feedback":{"correct":"Correcto. EXISTS pregunta existencia, no contenido — y se detiene al primer hallazgo: eficiente por naturaleza.","incorrect":"EXISTS ignora las columnas devueltas: el SELECT 1 lo declara con honestidad. Lo único que cuenta es si apareció al menos una fila."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Correladas, EXISTS e inline views","points":["CORRELADA: referencia la fila externa — se evalúa conceptualmente para cada fila de afuera.","EXISTS pregunta existencia (SELECT 1; para en la primera coincidencia) · NOT EXISTS: 'los que no tienen'.","TRAMPA: NOT IN con un nulo en la subconsulta devuelve CERO filas sin aviso — NOT EXISTS es inmune.","Tres formas de hallar a los 'sin': anti-join (LEFT + IS NULL), NOT EXISTS, NOT IN (con IS NOT NULL).","INLINE VIEW: subconsulta en el FROM tratada como tabla — sin crear objetos."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-l06-correladas';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Práctica: los pacientes fantasma (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Trabajo social necesita contactar a los pacientes registrados que JAMÁS han agendado una cita — los pacientes fantasma. Escribe el anti-join clásico sobre pacientes (PK paciente_id) y citas (PK cita_id, FK paciente_id). Usa los alias p y c.","instructions":["FROM pacientes con alias p.","LEFT JOIN citas con alias c, emparejando ON c.paciente_id = p.paciente_id.","Filtra con WHERE c.cita_id IS NULL (la PK del lado derecho: solo es nula cuando no hubo pareja).","Proyecta p.nombre y p.telefono, y ordena por p.nombre."],"initialCode":"-- Pacientes que JAMÁS han agendado: el anti-join.\n-- Alias: p (pacientes) y c (citas).\n\nSELECT p.nombre, p.telefono\nFROM   pacientes p;","validators":["from\\s+pacientes\\s+p\\b","left\\s+(outer\\s+)?join\\s+citas\\s+c\\b","on\\s+(c\\.paciente_id\\s*=\\s*p\\.paciente_id|p\\.paciente_id\\s*=\\s*c\\.paciente_id)","where\\s+c\\.cita_id\\s+is\\s+null","order\\s+by\\s+p\\.nombre"],"mockOutput":{"columns":["NOMBRE","TELEFONO"],"rows":[["Renata Ibarra","5512345678"],["Tomás Gutiérrez","3387654321"]],"note":"Los fantasmas, encontrados: el LEFT conservó a todos los pacientes, y el IS NULL sobre la PK de citas dejó solo a quienes nunca emparejaron."},"hints":["El LEFT JOIN va después del FROM: LEFT JOIN citas c ON c.paciente_id = p.paciente_id.","El filtro pregunta por la PK del lado DERECHO: WHERE c.cita_id IS NULL — solo es nula donde no hubo pareja.","Cierra con ORDER BY p.nombre. El orden de las cláusulas: FROM → LEFT JOIN … ON → WHERE → ORDER BY."],"successMessage":"Anti-join dominado: LEFT para no perder a nadie, IS NULL sobre la PK derecha para quedarte con los que no emparejaron. La misma receta responde 'medicamentos nunca recetados' y 'médicos sin agenda' — y en la entrevista, recuerda a su hermano inmune a nulos: NOT EXISTS.","failMessage":"Revisa la receta: FROM pacientes p · LEFT JOIN citas c ON c.paciente_id = p.paciente_id · WHERE c.cita_id IS NULL · ORDER BY p.nombre. Los alias p y c son parte del contrato."}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-l07-practica-joins';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La octava región","body":"Byte ya no consulta tablas: consulta el MODELO — las rutas que las FKs pavimentaron. Once preguntas custodian esta región: joins de todos los sabores, conjuntos que se apilan y subconsultas que miran hacia afuera. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"En la sintaxis ANSI, la división de trabajo correcta entre ON y WHERE es…","options":["Son intercambiables","ON declara el EMPAREJAMIENTO entre tablas (FK = PK); WHERE FILTRA el resultado — mezclar ambos era el vicio de la sintaxis vieja","ON filtra y WHERE empareja","Ambos ordenan"],"correctIndex":1,"feedback":{"correct":"Correcto. Emparejar y filtrar son responsabilidades distintas — y en los LEFT, confundirlas cambia el resultado.","incorrect":"ON = cómo se conectan las tablas; WHERE = qué filas sobreviven. La separación es el corazón de la sintaxis ANSI."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Un INNER JOIN devuelve menos filas que la tabla original y no hay error. ¿La causa típica?","options":["El motor perdió filas","Filas SIN PAREJA: una FK opcional con nulos o un ON mal escrito — el INNER descarta sin avisar lo que no empareja","El ORDER BY las ocultó","Un límite de licencia"],"correctIndex":1,"feedback":{"correct":"Correcto. El INNER calla a los sin-pareja: el conteo esperado es tu detector, y el ON tu primer sospechoso.","incorrect":"El INNER solo muestra coincidencias: la cita con medico_id nulo desaparece del reporte sin aviso. Sospecha del ON y de las FKs opcionales."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué join conserva TODAS las filas de la tabla izquierda, rellenando con nulos donde no hubo pareja?","options":["INNER JOIN","LEFT JOIN — y esos nulos son la marca explotable de 'sin pareja'","CROSS JOIN","NATURAL JOIN"],"correctIndex":1,"feedback":{"correct":"Correcto. El LEFT no pierde a nadie de la izquierda; el FULL, de paso, no pierde a nadie de ningún lado.","incorrect":"Conservar la izquierda completa es el LEFT JOIN: los nulos del lado derecho marcan a los sin-pareja."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La receta completa del ANTI-JOIN ('los pacientes que NO tienen citas'):","options":["INNER JOIN + DISTINCT","LEFT JOIN citas + WHERE citas.pk IS NULL: conservar a todos y quedarse con los que no emparejaron — preguntando por una columna que jamás sería nula con pareja","RIGHT JOIN + COUNT","UNION de ambas tablas"],"correctIndex":1,"feedback":{"correct":"Correcto. La PK derecha solo es nula sin pareja: el filtro convierte la marca en la respuesta.","incorrect":"Anti-join = LEFT (nadie se pierde) + IS NULL sobre la PK derecha (solo los sin-pareja sobreviven al filtro)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Una consulta de dos tablas devuelve 5 millones de filas absurdas. El diagnóstico:","options":["Faltó DISTINCT","PRODUCTO CARTESIANO: un join sin condición de emparejamiento (el ON olvidado) combinó cada fila con todas las de la otra tabla","Sobran índices","La tabla creció"],"correctIndex":1,"feedback":{"correct":"Correcto. 1,000 × 5,000 = 5,000,000: la aritmética delata al ON ausente.","incorrect":"La explosión multiplicativa es la firma del cartesiano accidental: todo JOIN necesita su ON."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué NATURAL JOIN se considera frágil en código de producción?","options":["Porque es más lento","Porque empareja por TODOS los nombres de columna coincidentes: una columna homónima agregada mañana cambia el emparejamiento EN SILENCIO","Porque no acepta alias","Porque fue eliminado de Oracle"],"correctIndex":1,"feedback":{"correct":"Correcto. La consulta correcta de hoy se corrompe con el ALTER de mañana, sin error alguno. ON es explícito e inmune.","incorrect":"El NATURAL decide el ON por ti según los nombres — y los nombres cambian. El emparejamiento explícito no se corrompe en silencio."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Dos listas de resultados que por diseño NO comparten filas deben apilarse. ¿UNION o UNION ALL?","options":["UNION, por si acaso","UNION ALL: sin duplicados posibles, deduplicar es pagar peaje en carretera vacía — UNION obligaría al motor a comparar todo el resultado","UNION, que es más moderno","INTERSECT"],"correctIndex":1,"feedback":{"correct":"Correcto. La elección delata si pensaste en tus datos: disjuntos por diseño → ALL, sin dudar.","incorrect":"UNION deduplica (trabajo real de ordenar y comparar); si los duplicados no pueden existir, UNION ALL da lo mismo, gratis."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"ORA-01427: 'single-row subquery returns more than one row'. ¿Qué promesa se rompió?","options":["La de la PK","La del OPERADOR: =, > o < esperaban UN valor de la subconsulta y llegaron varios — se diagnostica qué debía devolver antes de cambiar el operador","La del ORDER BY","La de la FK"],"correctIndex":1,"feedback":{"correct":"Correcto. El operador de una fila es una promesa sobre el resultado; el arreglo correcto depende de la intención, no del síntoma.","incorrect":"Los operadores de comparación prometen subconsulta de una fila. Si llegaron varias: ¿WHERE interno mal, o era una lista y corresponde IN/ANY/ALL?"}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu NOT IN (SELECT paciente_id FROM citas) devuelve cero filas aunque hay pacientes sin citas. ¿Qué pasó y cuál es la defensa?","options":["La base está corrupta","La subconsulta trae algún NULO y NOT IN con nulo devuelve vacío sin aviso — defensa: NOT EXISTS (inmune a nulos) o IS NOT NULL dentro de la subconsulta","Faltó un alias","El NOT IN necesita ORDER BY"],"correctIndex":1,"feedback":{"correct":"Correcto. La trampa de tres valores más cruel de SQL — y la pregunta de entrevista que ahora respondes con precisión.","incorrect":"Un solo nulo en la lista vacía el NOT IN entero, sin error. NOT EXISTS es la forma profesional de 'los que no tienen'."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es una subconsulta CORRELADA y cuál es su pareja natural?","options":["Una consulta con dos JOINs","La que REFERENCIA la fila externa (se evalúa para cada fila de afuera); su pareja es EXISTS, que pregunta existencia y para en la primera coincidencia","Una vista guardada","Un sinónimo"],"correctIndex":1,"feedback":{"correct":"Correcto. La correlación mira hacia afuera; EXISTS (SELECT 1 …) la aprovecha preguntando solo '¿hay algo tuyo?'.","incorrect":"Correlada = depende de la fila externa en turno. EXISTS/NOT EXISTS son su uso estrella: existencia, no contenido."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'dame DOS formas de encontrar pacientes sin citas, y dime cuál evitarías y por qué.' Tu respuesta senior:","options":["Solo hay una forma","Anti-join (LEFT JOIN + WHERE pk_derecha IS NULL) y NOT EXISTS con subconsulta correlada — ambas correctas. Evitaría NOT IN sin protección: si la subconsulta trae un nulo, devuelve vacío en silencio; usable solo con IS NOT NULL adentro","DELETE de los pacientes con citas y ver qué queda","Un CROSS JOIN filtrado"],"correctIndex":1,"feedback":{"correct":"Impecable. Dos soluciones correctas, una trampa nombrada con su causa (lógica de tres valores) y su mitigación: respuesta de contratación inmediata.","incorrect":"La respuesta senior ofrece anti-join y NOT EXISTS, y descarta NOT IN desprotegido por la trampa del nulo — con la mitigación de IS NOT NULL si no hay opción."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm06-x01-examen';
