-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 020 — Redes y Sistemas · Módulo 1: ¿Qué es una red?
-- ═══════════════════════════════════════════════════════════════════
-- Contenido completo del módulo: 5 lecciones + examen de región.
-- Hilo conductor del curso: la red de una clínica (mismo universo que
-- el hospital del curso de SQL).
-- Contrato del bloque 'laboratorio' (lo mapea courseStore.js):
--   { title, code (comandos Windows y Linux), caption, result? }
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 006.
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'redes-y-sistemas' and m.slug = 'm01-que-es-una-red'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m01-l01-que-es-una-red',    '¿Qué es una red y por qué existe?', 'leccion', 20, 1),
       ('m01-l02-cliente-y-servidor','Cliente y servidor',                'leccion', 20, 2),
       ('m01-l03-piezas-fisicas',    'Las piezas físicas',                'leccion', 20, 3),
       ('m01-l04-la-red-de-tu-casa', 'La red de tu casa',                 'leccion', 20, 4),
       ('m01-l05-lab-conoce-tu-red', 'Lab: conoce tu propia red',         'leccion', 20, 5),
       ('m01-x01-examen',            'Examen: ¿Qué es una red?',          'examen',  40, 6)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'redes-y-sistemas' and m.slug = 'm01-que-es-una-red';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · ¿Qué es una red y por qué existe?
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El problema antes del cable","body":"Imagina una clínica sin red: la recepcionista anota una cita en su computadora, la imprime y camina hasta el consultorio para entregarla. El laboratorio guarda los resultados en una USB y alguien la lleva de piso en piso. Cada computadora es una isla. Una red es exactamente lo contrario: dos o más dispositivos conectados que pueden compartir información y recursos al instante. Cuando la recepcionista guarda la cita, el médico la ve en su pantalla un segundo después. Ese es el problema que las redes resuelven: eliminar la distancia entre la información y quien la necesita."}$j$),
  (2, 'texto', $j${"title":"Qué comparte una red y qué necesita para funcionar","body":"Una red comparte tres cosas: información (el expediente que consultan recepción y el médico a la vez), recursos (una sola impresora para toda la clínica, una sola conexión a internet para todos) y servicios (el sistema de citas al que todos se conectan). Y para lograrlo necesita tres ingredientes que estudiaremos módulo a módulo: un MEDIO por donde viajen los datos (cable, fibra u ondas), DIRECCIONES para saber quién es quién (módulo 3) y REGLAS comunes para entenderse — los protocolos (módulos 2 y 4). Medio, direcciones y reglas: recuérdalos, porque todo el curso cuelga de esos tres."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es una red de computadoras?","options":["Un grupo de computadoras del mismo fabricante","El cableado estructurado de todo un edificio","Dispositivos conectados que comparten datos y recursos","Cualquier equipo con acceso a internet contratado"],"correctIndex":2,"feedback":{"correct":"Correcto. Lo esencial es la conexión para compartir: la información y los recursos dejan de ser islas.","incorrect":"Una red son dispositivos conectados que comparten información y recursos. Internet es solo una red (enorme) más."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En la clínica, recepción y el médico consultan la MISMA cita al mismo tiempo desde computadoras distintas. ¿Qué problema resolvió la red?","options":["Hizo que las computadoras funcionaran más rápido","Abarató el costo de las impresoras de la clínica","Impidió que los expedientes en papel se dañaran","Eliminó la distancia entre el dato y quien lo necesita"],"correctIndex":3,"feedback":{"correct":"Exacto. Sin red, la información viajaba en papel o USB; con red, llega al instante a quien la necesita.","incorrect":"La clave está en el acceso: la red lleva la información al instante a quien la necesita, sin papel ni USB de por medio."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Los tres ingredientes de toda red son:","options":["Cables, computadoras y pantallas de red","Medio, direcciones y reglas (protocolos)","Internet, Wi-Fi y un router doméstico","Servidores, clientes e impresoras"],"correctIndex":1,"feedback":{"correct":"Correcto. Un medio por donde viajar, direcciones para saber quién es quién y reglas comunes para entenderse.","incorrect":"Son medio (cable/ondas), direcciones (quién es quién) y reglas comunes (protocolos). El resto son piezas, no ingredientes."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — ¿Qué es una red?","points":["Una red son dos o más dispositivos conectados que comparten información y recursos.","Sin red, cada computadora es una isla: la información viaja en papel o USB.","Una red comparte información, recursos (impresoras, internet) y servicios (el sistema de citas).","Los tres ingredientes: MEDIO (cable, fibra, ondas), DIRECCIONES (módulo 3) y REGLAS o protocolos (módulos 2 y 4).","Internet no es 'la red': es una red de redes — la más grande de todas."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm01-l01-que-es-una-red';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Cliente y servidor
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Roles, no máquinas","body":"En una red, quien PIDE algo es el cliente y quien RESPONDE es el servidor. Y aquí va la idea que muchos entienden mal (y que aclara cualquier entrevista): cliente y servidor son ROLES, no tipos de computadora. Cuando la recepcionista abre el sistema de citas, su computadora es cliente y la máquina que guarda las citas es servidor. Pero si esa misma recepcionista comparte una carpeta y el médico la abre desde su consultorio, la computadora de recepción está actuando como servidor. Una misma máquina puede jugar ambos papeles a la vez — tu laptop lo hace todos los días."}$j$),
  (2, 'texto', $j${"title":"La conversación: petición y respuesta","body":"Toda la comunicación cliente-servidor es una conversación de dos frases: el cliente envía una PETICIÓN ('dame la agenda de hoy') y el servidor devuelve una RESPUESTA (la agenda, o un error si algo falló). Para que eso funcione, el servidor vive ESCUCHANDO: un programa despierto esperando peticiones, aunque nadie le hable en horas. Por eso un servidor de la clínica no se apaga al final del día. Un solo servidor atiende a muchos clientes a la vez: cientos de recepcionistas, médicos y laboratorios hablando con la misma máquina. En el módulo 4 verás la pieza que hace posible esa escucha: los puertos."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"La app de recepción consulta la agenda del día al sistema central. ¿Quién es el cliente?","options":["La app de recepción, que hace la petición","El sistema central, que almacena los datos","La red misma, que transporta los datos","Los dos equipos actúan como cliente"],"correctIndex":0,"feedback":{"correct":"Correcto. Cliente = quien pide. La app pide la agenda; el sistema central responde: ese es el servidor.","incorrect":"El cliente es quien PIDE. La app de recepción pide la agenda; el sistema central que responde es el servidor."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Un servidor es siempre una computadora grande y costosa montada en un rack?","options":["Sí, por eso reciben el nombre de servidores","Solo cuando se usan en empresas pequeñas","Solo si ejecuta Windows Server u otro sistema similar","No: servidor es un ROL que cualquier máquina puede jugar"],"correctIndex":3,"feedback":{"correct":"Exacto. Es un rol: tu laptop compartiendo una carpeta ya está actuando como servidor.","incorrect":"Servidor es un rol, no un tipo de hardware: cualquier máquina que responde peticiones lo está jugando."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué significa que un servidor 'escucha'?","options":["Que graba todas las conversaciones que cruzan la red","Que mantiene un programa despierto esperando peticiones","Que solo atiende dentro del horario laboral de oficina","Que necesita un micrófono conectado para funcionar"],"correctIndex":1,"feedback":{"correct":"Correcto. Escuchar = esperar peticiones permanentemente. Por eso los servidores no se apagan.","incorrect":"Escuchar significa esperar peticiones: un programa despierto listo para responder en cualquier momento."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Cliente y servidor","points":["Cliente = quien pide; servidor = quien responde. Son ROLES, no tipos de máquina.","Una misma computadora puede ser cliente y servidor a la vez.","La comunicación es petición → respuesta, siempre.","El servidor vive escuchando: espera peticiones aunque nadie le hable en horas.","Un solo servidor atiende a muchos clientes a la vez — los puertos (módulo 4) lo hacen posible."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm01-l02-cliente-y-servidor';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Las piezas físicas
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cada caja tiene un trabajo","body":"Dos piezas hacen casi todo el trabajo, y confundirlas es el error clásico. El SWITCH conecta dispositivos DENTRO de una misma red: es el cartero interno de la clínica, que lleva sobres entre consultorios sin salir del edificio. El ROUTER conecta REDES DISTINTAS entre sí: es la oficina de correos, la única que sabe enviar cartas a otras ciudades. Cuando la computadora de recepción le manda algo a la impresora del pasillo, basta el switch. Cuando consulta un sitio de internet, el paquete tiene que pasar por el router — la puerta de salida de la red."}$j$),
  (2, 'texto', $j${"title":"Access point, módem… y la caja de tu casa","body":"Dos piezas más completan el equipo. El ACCESS POINT (AP) es un switch sin cables: conecta los dispositivos Wi-Fi a la red, convirtiendo ondas de radio en tráfico de red. El MÓDEM traduce entre tu red y la línea de tu proveedor de internet (fibra, cable coaxial o telefónica) — dos mundos con señales físicas distintas. ¿Y la caja que te instaló tu proveedor en casa? Hace los CUATRO papeles a la vez: es módem, router, switch (sus puertos traseros) y access point (su Wi-Fi). Una sola caja, cuatro trabajos — por eso decimos 'el router de la casa', aunque sea mucho más que eso."}$j$),
  (3, 'texto', $j${"title":"Los medios: por dónde viajan los bits","body":"Los datos necesitan un camino físico. Cable de cobre (Ethernet): confiable, rápido, pero limitado en distancia — el estándar dentro de un edificio. Fibra óptica: pulsos de luz, velocidades enormes y kilómetros de alcance — une edificios, ciudades y continentes. Ondas de radio (Wi-Fi): comodísimas, pero comparten el aire con paredes, microondas y vecinos, así que son menos estables. Regla práctica que verás en toda infraestructura seria: lo que no se mueve y es crítico va por CABLE; la movilidad usa Wi-Fi. El servidor de expedientes de la clínica jamás debería colgar de una señal inalámbrica."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre un switch y un router?","options":["El switch es una versión más moderna del router","El router solo se usa en redes de empresas grandes","Switch conecta dentro de una red; router, entre redes","Son dos nombres para el mismo aparato"],"correctIndex":2,"feedback":{"correct":"Correcto. Cartero interno (switch) vs oficina de correos (router). Dentro de la red vs entre redes.","incorrect":"Switch = dentro de una misma red. Router = entre redes distintas (tu red ↔ internet, por ejemplo)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La caja que instaló tu proveedor de internet en tu casa es:","options":["Módem, router, switch y access point en un aparato","Únicamente un módem que traduce la señal","Únicamente un router que reparte internet","Un servidor que aloja las páginas web del sitio"],"correctIndex":0,"feedback":{"correct":"Exacto. Cuatro papeles en una caja: traduce la señal del proveedor, rutea, conecta por cable y da Wi-Fi.","incorrect":"Hace los cuatro trabajos: módem (traduce), router (conecta con internet), switch (puertos) y AP (Wi-Fi)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"El servidor de expedientes de la clínica, ¿por cable o por Wi-Fi? ¿Por qué?","options":["Wi-Fi, para poder cambiarlo de lugar con facilidad","Wi-Fi, porque es una tecnología más moderna que el cable","Da igual: cable y Wi-Fi dan la misma velocidad","Cable: un equipo crítico e inmóvil pide el medio estable"],"correctIndex":3,"feedback":{"correct":"Correcto. Regla de infraestructura: lo crítico e inmóvil va por cable; el Wi-Fi comparte el aire y es menos estable.","incorrect":"Un servidor crítico no se mueve: le corresponde el medio más estable — cable. El Wi-Fi es para la movilidad."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Las piezas físicas","points":["Switch: conecta dispositivos DENTRO de una red (el cartero interno).","Router: conecta REDES distintas — es la puerta de salida hacia internet.","Access point: el switch del aire; módem: traduce entre tu red y la línea del proveedor.","La caja de tu casa hace los 4 papeles: módem + router + switch + AP.","Medios: cobre (edificio), fibra (distancias y velocidad), ondas (movilidad).","Lo crítico e inmóvil va por cable; la movilidad usa Wi-Fi."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm01-l03-piezas-fisicas';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · La red de tu casa
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Tu primera red completa","body":"Ya conoces las piezas; ahora míralas trabajando juntas en la red que usas todos los días. Todos tus dispositivos — laptop, teléfono, TV, impresora — forman tu red local (LAN, Local Area Network), y absolutamente todo lo que entra o sale de tu casa pasa por un único punto: el router. Esa forma — muchos dispositivos alrededor de un centro — se llama topología de estrella y es la más común del mundo. Explora el diagrama: toca cada dispositivo y cada línea."}$j$),
  (2, 'diagrama', $j${"title":"La red doméstica típica","component":"NetworkDiagram","props":{"label":"Red doméstica · topología de estrella","ancho":520,"alto":300,"grupos":[{"id":"casa","x":14,"y":60,"w":340,"h":226,"titulo":"Tu casa · LAN","descripcion":"Tu red local (LAN): todos los dispositivos que comparten tu router. Entre ellos se hablan directo, sin salir a internet."}],"nodos":[{"id":"router","x":34,"y":120,"w":130,"titulo":"Router de casa","subtitulo":"módem·router·AP·switch","descripcion":"La caja del proveedor con sus 4 papeles: traduce la señal (módem), conecta tu LAN con internet (router), reparte por cable (switch) y por Wi-Fi (access point). Todo pasa por aquí."},{"id":"laptop","x":224,"y":76,"w":110,"titulo":"Laptop","subtitulo":"Wi-Fi","descripcion":"Cliente típico: pide páginas, videos y archivos. Conectada por Wi-Fi (línea discontinua)."},{"id":"telefono","x":224,"y":136,"w":110,"titulo":"Teléfono","subtitulo":"Wi-Fi","descripcion":"Otro cliente Wi-Fi. Dentro de la casa puede hablar con la TV o la impresora sin salir a internet."},{"id":"tv","x":224,"y":196,"w":110,"titulo":"Smart TV","subtitulo":"Wi-Fi","descripcion":"Cliente de streaming: pide video a servidores de internet a través del router."},{"id":"impresora","x":34,"y":216,"w":130,"titulo":"Impresora","subtitulo":"cable","descripcion":"Conectada por cable (línea continua): no se mueve y así gana estabilidad. Es un recurso COMPARTIDO: todos le imprimen."},{"id":"internet","x":396,"y":120,"w":110,"titulo":"Internet","subtitulo":"la red de redes","descripcion":"Todo lo que vive fuera de tu casa: los servidores de las páginas, videos y servicios que usas. Solo se llega a través del router."}],"enlaces":[{"de":"router","a":"internet","tipo":"doble","etiqueta":"WAN","descripcion":"La conexión con tu proveedor (WAN, Wide Area Network): la ÚNICA puerta entre tu casa e internet."},{"de":"laptop","a":"router","discontinuo":true,"etiqueta":"Wi-Fi","descripcion":"Enlace inalámbrico: ondas de radio entre la laptop y el access point del router."},{"de":"telefono","a":"router","discontinuo":true,"descripcion":"Enlace Wi-Fi del teléfono al router."},{"de":"tv","a":"router","discontinuo":true,"descripcion":"Enlace Wi-Fi de la TV al router."},{"de":"impresora","a":"router","etiqueta":"cable","descripcion":"Enlace Ethernet por cable: continuo en el diagrama = medio físico estable."}],"hint":"Toca un dispositivo, una línea o la zona LAN para ver qué papel juega."},"caption":"Línea continua = cable · línea discontinua = Wi-Fi. Nota que TODO pasa por el router: es el centro de la estrella y la única salida a internet."}$j$),
  (3, 'texto', $j${"title":"El viaje de un clic","body":"Abres el navegador en la laptop y entras a un sitio web. ¿Qué acaba de pasar? 1) Tu laptop armó una petición ('dame la página') y la envió por Wi-Fi al router. 2) El router la sacó por la conexión WAN hacia internet. 3) La petición cruzó redes hasta llegar al servidor del sitio web. 4) El servidor respondió con la página y la respuesta hizo el viaje de vuelta hasta tu pantalla. Todo en milisegundos. Las preguntas que este viaje deja abiertas son exactamente el resto del curso: ¿cómo supo la red a dónde ir? (direcciones, módulo 3), ¿en qué idioma pidió la página? (protocolos, módulo 4), ¿quién decidió el camino? (routing, módulo 6)."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Según el diagrama, ¿cuál es la ÚNICA puerta entre tu casa e internet?","options":["La laptop, que es la que abre el navegador","El router, el centro por donde pasa todo","La Smart TV, que consume mucho ancho de banda","Cada dispositivo tiene su propia salida a internet"],"correctIndex":1,"feedback":{"correct":"Correcto. Topología de estrella: todo pasa por el centro, y la salida a internet (WAN) es solo una.","incorrect":"Todo el tráfico que entra o sale de la casa pasa por el router: es el centro de la estrella y la única puerta."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"El teléfono le envía una foto a la impresora de la casa. ¿La foto sale a internet?","options":["Sí, todo el tráfico pasa siempre por internet","Solo si la foto pesa más de unos cuantos megas","No: ambos están en la misma LAN y el router los une","Depende de lo que permita tu proveedor de internet"],"correctIndex":2,"feedback":{"correct":"Exacto. Tráfico LOCAL: dentro de la LAN los dispositivos se hablan a través del switch/AP del router, sin tocar internet.","incorrect":"Ambos viven en la misma LAN: el tráfico local viaja por el router (su parte switch/AP) sin salir a internet."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En el diagrama, ¿qué significa una línea discontinua?","options":["Un enlace inalámbrico por Wi-Fi","Una conexión con fallas o defectuosa","Un cable de fibra óptica de alta velocidad","Una conexión que está apagada"],"correctIndex":0,"feedback":{"correct":"Correcto. Continua = cable físico; discontinua = ondas de radio (Wi-Fi). Convención que reutilizaremos en todo el catálogo.","incorrect":"La línea discontinua representa el enlace inalámbrico (Wi-Fi); la continua, el cable físico."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — La red de tu casa","points":["Tus dispositivos forman una LAN (red local); todo pasa por el router: topología de estrella.","La conexión router–proveedor se llama WAN: la única puerta a internet.","El tráfico entre dispositivos de la casa es LOCAL: no sale a internet.","Línea continua = cable; discontinua = Wi-Fi (convención de nuestros diagramas).","El viaje de un clic: laptop → router → internet → servidor → de vuelta. Direcciones, protocolos y routing (módulos 3, 4 y 6) explican cómo."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm01-l04-la-red-de-tu-casa';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Lab: conoce tu propia red
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Tu primer laboratorio","body":"Hora de tocar red de verdad. En este lab vas a descubrir la identidad de tu computadora en tu propia red y a comprobar que la conexión funciona, con las dos herramientas de diagnóstico más usadas del mundo. Todo se hace sobre TU red y con comandos de solo lectura: no cambian nada, solo preguntan. Abre una terminal — en Windows: PowerShell o CMD; en Linux o macOS: la Terminal — y sigue cada paso."}$j$),
  (2, 'laboratorio', $j${"title":"Paso 1 — Descubre tu dirección y tu puerta de salida","code":"# ── Windows (PowerShell o CMD) ──\nipconfig\n\n# ── Linux ──\nip addr\nip route\n\n# ── macOS ──\nifconfig\nnetstat -nr | grep default","caption":"En la salida, ubica tres datos de tu adaptador activo (Wi-Fi o Ethernet). En Windows se llaman 'Dirección IPv4', 'Máscara de subred' y 'Puerta de enlace predeterminada'; en Linux, la línea 'inet' y el 'default via' de ip route.","result":{"columns":["CAMPO","VALOR DE EJEMPLO","QUÉ ES"],"rows":[["Dirección IPv4","192.168.1.34","La identidad de TU equipo en la LAN"],["Máscara de subred","255.255.255.0","El tamaño de tu red (módulo 3)"],["Puerta de enlace","192.168.1.1","Tu router: la salida a internet"]],"note":"Tus números serán distintos, pero casi seguro empiezan con 192.168: es el rango privado más común (módulo 3)."}}$j$),
  (3, 'laboratorio', $j${"title":"Paso 2 — Ping: ¿hay alguien ahí?","code":"# 1) A tu router (usa TU puerta de enlace del paso 1)\nping 192.168.1.1\n\n# 2) A un servidor de internet (DNS público de Google)\nping 8.8.8.8\n\n# 3) A un nombre de dominio\nping google.com","caption":"ping envía un mensajito ('¿estás ahí?') y mide cuánto tarda la respuesta. En Linux/macOS detenlo con Ctrl+C. Compara los tiempos de los tres destinos.","result":{"columns":["DESTINO","TIEMPO TÍPICO","QUÉ PRUEBA"],"rows":[["Tu router","1–5 ms","Tu LAN funciona"],["8.8.8.8","10–60 ms","Tu salida a internet funciona"],["google.com","10–60 ms","Además, los NOMBRES se resuelven (DNS)"]],"note":"¿Por qué el router responde en 2 ms y Google en 40? Distancia: uno está en tu sala; el otro, a muchas redes de por medio."}}$j$),
  (4, 'texto', $j${"title":"Qué acabas de comprobar","body":"Con dos comandos hiciste un diagnóstico real: leíste la identidad de red de tu equipo (su IP), identificaste a tu router (la puerta de enlace) y probaste la conexión en capas — primero la LAN, luego internet, luego los nombres. Ese orden no es casual: es EXACTAMENTE como un técnico aísla un problema. ¿No hay red? Ping al router: si falla, el problema está en tu casa. ¿Responde? Ping a 8.8.8.8: si falla, es tu proveedor. ¿Responde? Ping a google.com: si ESTE falla, el problema es DNS (módulo 3). Acabas de aprender el árbol de diagnóstico más usado del planeta."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La 'puerta de enlace predeterminada' (default gateway) que encontraste es:","options":["El servidor de Google que usaste con ping","Tu propio equipo dentro de la red local","El servidor de tu proveedor de internet","Tu router: por donde tu equipo sale de la LAN"],"correctIndex":3,"feedback":{"correct":"Correcto. La puerta de enlace es tu router: todo lo que va fuera de tu LAN pasa por él.","incorrect":"La puerta de enlace es la IP de tu ROUTER dentro de la LAN: la salida de tu red hacia las demás."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"El ping a tu router tarda 2 ms y a google.com tarda 40 ms. ¿Por qué la diferencia?","options":["Los servidores de Google responden con lentitud","El router está a un salto; Google, a muchas redes","El Wi-Fi acelera los pings dentro de la red local","Los tiempos que muestra ping son valores al azar"],"correctIndex":1,"feedback":{"correct":"Exacto. La latencia crece con la distancia y los saltos entre redes. 2 ms = tu sala; 40 ms = medio mundo.","incorrect":"Es la distancia: el router está a un salto; Google, a muchas redes de por medio. Cada salto suma milisegundos."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"ping 8.8.8.8 responde bien, pero ping google.com falla. ¿Dónde está el problema?","options":["En tu router, que dejó de dar servicio","En tu proveedor de internet, que está caído","En el DNS: internet va, pero los nombres no","En el cable de red, que está desconectado"],"correctIndex":2,"feedback":{"correct":"Correcto. Si la IP responde pero el nombre no, la conexión está bien y lo roto es el DNS. Lo estudiamos a fondo en el módulo 3.","incorrect":"Internet funciona (8.8.8.8 respondió); lo que falla es traducir nombres a direcciones: eso es DNS (módulo 3)."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Lab: conoce tu propia red","points":["ipconfig / ip addr muestran tu identidad de red: IP, máscara y puerta de enlace.","La puerta de enlace (gateway) es tu router: la salida de la LAN.","ping mide si un destino responde y cuánto tarda: la herramienta #1 de diagnóstico.","Diagnóstico en capas: router (¿mi LAN?) → 8.8.8.8 (¿mi internet?) → google.com (¿mi DNS?).","Latencia: a más saltos y distancia, más milisegundos.","Todos los comandos del lab son de solo lectura: preguntan, no cambian nada."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm01-l05-lab-conoce-tu-red';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La primera región","body":"Byte llegó a la primera región del mundo de Redes: diez preguntas guardan el paso. Todo lo que necesitas ya lo viviste — redes, clientes y servidores, switches y routers, tu propia LAN y tus primeros comandos de diagnóstico. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Una red de computadoras es, en esencia:","options":["Dispositivos conectados que comparten datos y recursos","Una conexión a internet contratada con un proveedor","Un conjunto de cables que recorren un edificio","Un grupo de servidores en un centro de datos"],"correctIndex":0,"feedback":{"correct":"Correcto. Conexión para compartir: esa es la esencia.","incorrect":"Lo esencial: dispositivos conectados que comparten información y recursos. Internet es solo una red más."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Los tres ingredientes de toda red son:","options":["Router, switch y módem de la red","Wi-Fi, cable de cobre y fibra óptica","Cliente, servidor e impresora compartida","Medio, direcciones y reglas (protocolos)"],"correctIndex":3,"feedback":{"correct":"Correcto. Por dónde viajar, quién es quién y en qué idioma hablar.","incorrect":"Medio (por dónde), direcciones (quién es quién) y reglas o protocolos (en qué idioma)."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu laptop comparte una carpeta que el teléfono abre, mientras el navegador de la misma laptop ve una página web. La laptop está siendo:","options":["Solamente cliente, porque pide una página","Servidor y cliente a la vez: son roles, no máquinas","Solamente servidor, porque comparte la carpeta","Un router que conecta las dos redes"],"correctIndex":1,"feedback":{"correct":"Exacto. Sirve la carpeta (servidor) y pide la página (cliente). Roles simultáneos.","incorrect":"Hace ambos papeles a la vez: sirve la carpeta y pide la página. Cliente y servidor son roles, no tipos de máquina."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué un servidor no se apaga al final del día?","options":["Porque encendido consume menos energía que apagado","Porque tarda demasiado en volver a arrancar","Porque vive escuchando peticiones a cualquier hora","Porque el fabricante prohíbe apagarlo por garantía"],"correctIndex":2,"feedback":{"correct":"Correcto. Escuchar es su trabajo: esperar peticiones aunque nadie hable en horas.","incorrect":"El rol del servidor es escuchar permanentemente: si se apaga, nadie responde a los clientes."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Switch y router: ¿cuál es cuál?","options":["Switch conecta dentro de una red; router, entre redes","Switch conecta redes distintas; router, la misma red","Los dos hacen lo mismo, solo cambia la velocidad","El switch es inalámbrico y el router va por cable"],"correctIndex":0,"feedback":{"correct":"Correcto. El cartero interno (switch) y la oficina de correos (router).","incorrect":"Switch = dentro de la red; router = entre redes. El error clásico — ya no caerás en él."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"La caja que tu proveedor instaló en tu casa hace de:","options":["Únicamente un módem que traduce la señal","Un router y un módem, nada más","Un servidor que aloja los sitios de internet","Módem, router, switch y access point"],"correctIndex":3,"feedback":{"correct":"Correcto. Cuatro papeles en una sola caja.","incorrect":"Los cuatro papeles: traduce la señal, rutea hacia internet, da puertos de cable y emite Wi-Fi."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"La laptop le manda un documento a la impresora de la casa. ¿El documento viaja por internet?","options":["Sí, siempre pasa por internet primero","No: es tráfico local dentro de la LAN","Solo durante la noche o en horas valle","Depende del tamaño del documento a imprimir"],"correctIndex":1,"feedback":{"correct":"Correcto. Misma LAN = tráfico local vía switch/AP, sin tocar internet.","incorrect":"Ambos dispositivos están en la misma LAN: el tráfico es local y no sale a internet."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"La 'puerta de enlace predeterminada' de tu equipo es:","options":["La dirección IP de los servidores de Google","La dirección IP de tu propio equipo","La IP de tu router dentro de la LAN","La contraseña de acceso a tu red Wi-Fi"],"correctIndex":2,"feedback":{"correct":"Correcto. El gateway es tu router: por ahí sale todo lo que va fuera de tu red.","incorrect":"Es la IP de tu ROUTER en la LAN: la salida de tu red hacia las demás."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Sin internet en casa, haces ping a tu router y responde; a 8.8.8.8 y NO responde. ¿Dónde está el problema?","options":["Fuera de casa: en la conexión con tu proveedor","En tu laptop, que perdió la configuración","En tu red local, que dejó de funcionar","En el DNS, que no traduce los nombres"],"correctIndex":0,"feedback":{"correct":"Correcto. La LAN está viva (el router respondió); lo roto está más allá: la salida a internet.","incorrect":"El router respondió: tu LAN funciona. Lo que falla es el tramo hacia internet — tu proveedor."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: '¿el servidor de expedientes puede ir en Wi-Fi para ahorrarnos el cableado?' Tu respuesta senior:","options":["Sí, el Wi-Fi moderno es idéntico al cable en todo","No: un equipo crítico e inmóvil va por cable","Sí, siempre que la contraseña del Wi-Fi sea fuerte","No, porque los servidores no traen tarjeta Wi-Fi"],"correctIndex":1,"feedback":{"correct":"Impecable. Criterio de infraestructura: criticidad + inmovilidad = cable. La movilidad es la razón de ser del Wi-Fi.","incorrect":"La respuesta senior valora el criterio: equipo crítico que no se mueve → cable (estabilidad); Wi-Fi para lo que se mueve."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm01-x01-examen';
