-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 022 — Redes y Sistemas · Módulo 3: Direccionamiento
-- ═══════════════════════════════════════════════════════════════════
-- 7 lecciones + práctica de editor + examen de región.
-- AJUSTE DE KAREN (obligatorio): la parte de subredes/CIDR incluye
-- práctica de CÁLCULO con 3 casos — implementada como lección
-- kind='practica' (la hoja de subredes en el editor, validada por
-- valores: máscara, hosts útiles y prefijo).
-- Labs con contrato {title, code (Win/Linux), caption, result?}:
-- nslookup y tracert/traceroute.
-- Reglas de contenido: sin tecnología interna de la plataforma;
-- quizzes autocontenidos o con términos técnicos.
-- OJO: Redes está PUBLICADO — correr esta migración hace el M3
-- visible a los usuarios AL INSTANTE.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 006.
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'redes-y-sistemas' and m.slug = 'm03-direccionamiento'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m03-l01-direccion-ip',      'La dirección IP',                     'leccion',  20, 1),
       ('m03-l02-subredes-cidr',     'Subredes, máscaras y CIDR',           'leccion',  20, 2),
       ('m03-l03-practica-subredes', 'Práctica: la hoja de subredes',       'practica', 20, 3),
       ('m03-l04-nat',               'NAT: muchas casas, una puerta',       'leccion',  20, 4),
       ('m03-l05-dhcp',              'DHCP: quién reparte las direcciones', 'leccion',  20, 5),
       ('m03-l06-dns',               'DNS: la guía telefónica de internet', 'leccion',  20, 6),
       ('m03-l07-ipv6',              'IPv6: por qué existe',                'leccion',  20, 7),
       ('m03-l08-lab-camino',        'Lab: sigue el camino de un nombre',   'leccion',  20, 8),
       ('m03-x01-examen',            'Examen: Direccionamiento',            'examen',   40, 9)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'redes-y-sistemas' and m.slug = 'm03-direccionamiento';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · La dirección IP
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El segundo ingrediente: quién es quién","body":"En el módulo 1 aprendiste los tres ingredientes de toda red: medio, DIRECCIONES y reglas. Este módulo entero es el segundo. Una dirección IP (versión 4, la que verás en todas partes) son cuatro números de 0 a 255 separados por puntos — 192.168.1.25 — e identifica a UN dispositivo dentro de una red: la computadora de recepción, la impresora del pasillo, el servidor de expedientes, cada uno con la suya. Sin IP no hay entrega posible: es la dirección postal que la capa 3 escribe en cada paquete (el sobre del encapsulamiento que ya conoces). ¿De dónde sale la tuya? Casi nunca la escribes a mano: alguien la reparte — el quinto capítulo de este módulo te presenta al repartidor."}$j$),
  (2, 'texto', $j${"title":"Públicas y privadas: dos mundos","body":"Hay dos clases de IP. Las PRIVADAS viven dentro de las redes locales y están reservadas por convención mundial: todo lo que empieza con 192.168.x.x o 10.x.x.x (y el rango 172.16 a 172.31) es privado. Las PÚBLICAS identifican en internet: son únicas en el mundo y las administra tu proveedor. La consecuencia curiosa: tu laptop puede tener 192.168.1.25… y la laptop de tu vecino TAMBIÉN, sin conflicto alguno — porque cada una vive en su propia red local, como dos casas distintas pueden tener ambas una 'habitación 2'. Hacia internet, ambas casas salen con su IP pública, que sí es única. ¿Cómo se traduce lo privado a lo público? Esa magia se llama NAT y tiene su propia lección en este módulo."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estas es una dirección IPv4 válida?","options":["192.168.300.5 — algún número pasa de 255","192-168-1-25 con guiones en vez de puntos","192.168.1.25 — cuatro números de 0 a 255","1921681.25 sin ningún separador"],"correctIndex":2,"feedback":{"correct":"Correcto. Cuatro octetos de 0 a 255, con puntos. El 300 de la primera opción se pasa del límite.","incorrect":"IPv4: cuatro números de 0 a 255 separados por puntos. 192.168.300.5 no vale: 300 supera el máximo de 255."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"La computadora de recepción de una clínica tiene la IP 192.168.1.25. En términos de clases de IP, esa dirección es:","options":["Pública: la ve todo internet directamente","Una dirección inválida que no funciona","Una dirección del protocolo IPv6","Privada: reservada para redes locales"],"correctIndex":3,"feedback":{"correct":"Correcto. 192.168.x.x es rango privado: solo tiene sentido dentro de esa red local.","incorrect":"192.168.x.x es uno de los rangos PRIVADOS por convención mundial: vive dentro de la red local, no en internet."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu laptop tiene 192.168.1.25 y la laptop de tu vecino tiene EXACTAMENTE la misma IP. ¿Por qué no hay conflicto?","options":["Cada una está en una red local distinta","Porque los conflictos de IP se resuelven solos","Porque una de las dos casas está apagada","Sí hay conflicto: internet deja de funcionar"],"correctIndex":0,"feedback":{"correct":"Correcto. Como la 'habitación 2' de dos casas distintas: la unicidad de las privadas es por red, no mundial.","incorrect":"Las IP privadas se repiten en millones de redes sin problema: cada una solo necesita ser única DENTRO de su red local."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — La dirección IP","points":["IPv4: cuatro números de 0 a 255 separados por puntos — identifica UN dispositivo en una red.","Es la dirección que viaja en el paquete (capa 3): sin IP no hay entrega.","PRIVADAS (192.168.x.x, 10.x.x.x, 172.16–31.x.x): viven en redes locales y se repiten entre redes sin conflicto.","PÚBLICAS: únicas en el mundo, las administra el proveedor — la cara de tu red hacia internet.","Quién reparte las IP (DHCP) y quién traduce privado↔público (NAT): más adelante en este módulo."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l01-direccion-ip';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Subredes, máscaras y CIDR
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Una IP son dos datos en uno","body":"Aquí está el secreto mejor guardado del direccionamiento: una IP no es un solo dato, son DOS pegados — la parte de RED (el barrio) y la parte de HOST (la casa dentro del barrio). ¿Dónde termina una y empieza la otra? Eso lo dice la MÁSCARA, y la forma moderna de escribirla es la notación CIDR: una barra y un número al final — 192.168.10.0/24. El /24 significa: los primeros 24 bits (de los 32 que tiene una IPv4) son la parte de red; los 32 − 24 = 8 bits restantes son para los hosts. ¿Por qué importa? Porque un dispositivo usa esta división para decidir algo crucial en cada envío: si el destino está en MI red (entrega directa, vía switch) o en OTRA (hay que pasar por el router). La frontera del módulo 1 — dentro vs fuera — vive exactamente aquí."}$j$),
  (2, 'texto', $j${"title":"El cálculo sin dolor: de /n a hosts y máscara","body":"Dos fórmulas y ya sabes calcular subredes. HOSTS ÚTILES: con /n quedan 32−n bits de host, que generan 2^(32−n) direcciones… menos 2 reservadas (la primera nombra a la red misma y la última es el broadcast — el altavoz que llega a todos). Fórmula completa: 2^(32−n) − 2. Ejemplo: /24 → 8 bits → 256 − 2 = 254 hosts útiles; /26 → 6 bits → 64 − 2 = 62. MÁSCARA DECIMAL: es el /n disfrazado — n unos seguidos convertidos a los cuatro números. Los valores que verás siempre: /24 = 255.255.255.0 · /25 = 255.255.255.128 · /26 = 255.255.255.192 · /27 = 255.255.255.224. Nota el patrón del último número: 0, 128, 192, 224 — cada bit extra de red suma la mitad de lo que sumó el anterior (128, 64, 32…)."}$j$),
  (3, 'texto', $j${"title":"Para qué partir una red: la clínica segmentada","body":"¿Y para qué querría alguien un /26 en vez del /24 de siempre? Para PARTIR una red grande en barrios separados: eso es una SUBRED. La clínica es el caso de libro: una subred para administración (expedientes y facturación), otra para los equipos médicos, otra para el Wi-Fi de los pacientes en la sala de espera. Mismo edificio, mismos cables quizá — pero fronteras lógicas: el invitado de la sala de espera NO está en la misma red que el servidor de expedientes, y cruzar de una subred a otra obliga a pasar por el router… donde se puede vigilar y filtrar. Guarda esta idea con nombre propio — SEGMENTACIÓN — porque el módulo 6 la convierte en la herramienta estrella de la seguridad de redes."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En la notación CIDR 192.168.10.0/24, ¿qué significa exactamente el /24?","options":["Que la red tiene exactamente 24 dispositivos","Los primeros 24 bits son RED y los 8 restantes HOST","Que es la subred número 24 de la lista","Que la dirección caduca en 24 horas"],"correctIndex":1,"feedback":{"correct":"Correcto. El /n marca la frontera: n bits de red, 32−n de host.","incorrect":"El /24 dice dónde corta la dirección: 24 bits identifican la red y los 32−24=8 restantes identifican cada host."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Aplicando la fórmula 2^(32−n) − 2: ¿cuántos hosts útiles tiene una red /26?","options":["64 direcciones en total disponibles","26, como el número de la máscara","62: 6 bits de host → 64 − 2 reservadas","254 hosts útiles, como en una red /24"],"correctIndex":2,"feedback":{"correct":"Correcto. 32−26 = 6 bits → 2^6 = 64 − 2 (red y broadcast) = 62.","incorrect":"Con /26 quedan 6 bits de host: 2^6 = 64 direcciones, menos las 2 reservadas (red y broadcast) = 62 útiles."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En el cálculo de hosts útiles siempre se restan 2 direcciones. ¿Cuáles son y para qué se reservan?","options":["Las dos primeras, por pura tradición","La del router y la del servidor principal","Dos de repuesto por si alguna falla","La primera (la red) y la última (broadcast)"],"correctIndex":3,"feedback":{"correct":"Correcto. La dirección de red y el broadcast no se asignan a ningún dispositivo: por eso el −2 de la fórmula.","incorrect":"Se reservan la primera (identifica a la red) y la última (broadcast, el altavoz de la subred): ningún host puede usarlas."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Subredes y CIDR","points":["Una IP son dos partes: RED (el barrio) + HOST (la casa). La máscara marca la frontera.","CIDR: /n = n bits de red. Hosts útiles = 2^(32−n) − 2 (la red misma y el broadcast se reservan).","/24 = 255.255.255.0 (254 hosts) · /26 = 255.255.255.192 (62) · /27 = 255.255.255.224 (30).","La división red/host decide cada envío: ¿mi red (directo) u otra (vía router)?","Partir una red en subredes = SEGMENTACIÓN: fronteras lógicas con control en el cruce — la estrella del módulo 6."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l02-subredes-cidr';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Práctica: la hoja de subredes (kind = practica — ajuste de Karen)
-- 3 casos de cálculo validados por valores en el editor.
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"La clínica está rediseñando sus subredes y te pasó la hoja de cálculo a medio llenar. El caso 1 viene resuelto de ejemplo; completa los otros dos reemplazando cada ? por tu cálculo. Las fórmulas: hosts útiles = 2^(32−n) − 2, y la máscara sale del patrón 0 · 128 · 192 · 224.","instructions":["Caso 2 — la red 192.168.10.0/26: calcula su máscara decimal y sus hosts útiles.","Caso 3 — el laboratorio clínico necesita conectar 30 equipos: encuentra el prefijo /n MÁS AJUSTADO que les da cabida (pista: prueba con la fórmula hasta que los hosts útiles alcancen justo).","Reemplaza solo los ? — el resto de la hoja no se toca.","EJECUTA para revisar tu hoja; COMPRUEBA cuando esté completa."],"initialCode":"# HOJA DE SUBREDES — Clínica San Rafael\n# hosts útiles = 2^(32-n) - 2 · máscaras: /24=.0 /25=.128 /26=.192 /27=.224\n\n# Caso 1 (ejemplo resuelto): red de administración — 192.168.10.0/24\ncaso1_mascara=255.255.255.0\ncaso1_hosts_utiles=254\n\n# Caso 2: red de equipos médicos — 192.168.10.0/26\ncaso2_mascara=?\ncaso2_hosts_utiles=?\n\n# Caso 3: laboratorio clínico — 30 equipos\n# ¿el prefijo /n más ajustado que les da cabida?\ncaso3_prefijo=?","validators":["caso2_mascara\\s*=\\s*255\\.255\\.255\\.192","caso2_hosts_utiles\\s*=\\s*62\\b","caso3_prefijo\\s*=\\s*/?27\\b"],"mockOutput":{"columns":["CASO","RED","MÁSCARA","HOSTS ÚTILES"],"rows":[["1 · Administración","192.168.10.0/24","255.255.255.0","254"],["2 · Equipos médicos","192.168.10.0/26","255.255.255.192","62"],["3 · Laboratorio","/27","255.255.255.224","30 (justos para 30 equipos)"]],"note":"La hoja completa: tres subredes dimensionadas — ni direcciones desperdiciadas ni equipos sin lugar."},"hints":["Caso 2: /26 deja 32−26 = 6 bits de host → 2^6 − 2 = 62 útiles. Y la máscara de /26, según el patrón, termina en .192.","Caso 3: prueba la fórmula — /28 da 2^4−2 = 14 (no alcanza), /27 da 2^5−2 = 30 (¡justo!). El más ajustado es el que alcanza con el número más grande de n.","Escribe los valores tal cual: caso2_mascara=255.255.255.192 · caso2_hosts_utiles=62 · caso3_prefijo=/27"],"successMessage":"Hoja de subredes entregada: dimensionaste tres redes con la fórmula, incluido el /27 exacto para los 30 equipos del laboratorio. Este cálculo aparece en todo examen de redes del mundo real — y acabas de hacerlo sin calculadora.","failMessage":"Revisa con las fórmulas: /26 → máscara 255.255.255.192 y 2^6−2 = 62 hosts; para 30 equipos, /27 da 2^5−2 = 30 justos (el /28 se queda corto con 14)."}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l03-practica-subredes';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · NAT: muchas casas, una puerta
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El truco que salvó a internet","body":"IPv4 tiene un problema aritmético: 32 bits dan unos 4300 millones de direcciones… y hay muchos más dispositivos que eso en el mundo. La solución que compró décadas de tiempo se llama NAT (Network Address Translation, traducción de direcciones de red): dentro de tu red, todos usan IP PRIVADAS (gratis, repetibles); hacia internet, la red entera comparte UNA pública. ¿Quién hace el malabar? El router: cada vez que un paquete sale, REESCRIBE la dirección de origen — quita la privada, pone la pública — y apunta el cambio en su tabla de traducciones para saber a quién entregarle la respuesta cuando vuelva. Los 40 dispositivos de la clínica navegan a la vez… y todos los sitios web ven a un solo visitante: la IP pública del router."}$j$),
  (2, 'texto', $j${"title":"Las dos caras de tu conexión","body":"Consecuencia práctica que confunde a todo el mundo la primera vez: tienes DOS direcciones a la vez. La privada (192.168.1.25, la que reparte tu router y ves en la configuración de tu equipo) y la pública (la del router hacia internet, la que ven los sitios web — los servicios tipo '¿cuál es mi IP?' te muestran esta). No son la misma y no se parecen. Y una consecuencia de seguridad interesante: con NAT, nadie desde internet puede iniciar una conexión directa hacia tu laptop — el router no sabría a qué dispositivo interno entregarla si no hay una traducción previa apuntada en su tabla. No es un firewall (eso llega en el módulo 6), pero de fábrica ya te esconde."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué hace exactamente el NAT del router cuando un paquete sale hacia internet?","options":["Reescribe la IP de origen y la anota en su tabla","Cifra el contenido del paquete que sale","Comprime el paquete para que viaje más rápido","Le agrega publicidad al paquete de salida"],"correctIndex":0,"feedback":{"correct":"Correcto. Traducción a la salida + tabla para el camino de vuelta: ese es todo el truco.","incorrect":"NAT = traducir direcciones: cambia la privada por la pública al salir, y su tabla recuerda a quién devolverle cada respuesta."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Los 40 dispositivos de una clínica navegan a la vez por internet. ¿Cuántas IP públicas están usando y por qué?","options":["40 direcciones, una por cada dispositivo","Una: con NAT toda la red comparte la del router","Ninguna dirección pública es necesaria","Depende de la hora del día y el uso"],"correctIndex":1,"feedback":{"correct":"Correcto. Muchas casas, una puerta: por eso IPv4 sigue vivo con más dispositivos que direcciones.","incorrect":"Con NAT, la red entera sale por UNA pública (la del router): las 40 privadas solo existen puertas adentro."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — NAT","points":["IPv4 se quedó corto (~4300 millones de direcciones); NAT fue el truco que compró décadas.","Dentro: IP privadas repetibles. Hacia internet: UNA pública compartida.","El router reescribe el origen de cada paquete y su tabla de traducciones enruta las respuestas.","Tienes dos direcciones a la vez: la privada (tu equipo) y la pública (tu router — la que ven los sitios).","Efecto colateral: desde internet nadie inicia conexiones directas hacia tus dispositivos — NAT te esconde de fábrica."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l04-nat';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · DHCP: quién reparte las direcciones
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El repartidor automático","body":"Prometimos contarte de dónde sale tu IP. La respuesta es DHCP (Dynamic Host Configuration Protocol): cuando un dispositivo se conecta a la red, grita '¿alguien me da una dirección?' y el servidor DHCP — en tu casa, otro de los sombreros del router — le PRESTA una IP libre de su rango, junto con el kit completo para funcionar: la máscara, la puerta de enlace (el gateway del módulo 1) y el servidor DNS (siguiente lección). El préstamo se llama LEASE y tiene vencimiento: el dispositivo lo renueva periódicamente, y si se va de la red, esa IP vuelve al fondo común para el siguiente. Por eso conectarte a cualquier Wi-Fi 'simplemente funciona': nadie configuró nada a mano — DHCP hizo el papeleo en milisegundos."}$j$),
  (2, 'texto', $j${"title":"Cuándo NO usar el repartidor: la IP fija","body":"Si DHCP presta direcciones que pueden cambiar, hay un problema esperando: ¿y si la impresora de la clínica amanece con OTRA IP y nadie la encuentra? Para los dispositivos que otros necesitan ubicar SIEMPRE — impresoras, servidores, cámaras — se usa IP FIJA (estática): se configura a mano o se le pide al DHCP que reserve siempre la misma para ese equipo. La regla profesional de reparto: los CLIENTES (laptops, teléfonos, tablets — los que van y vienen) usan DHCP; la INFRAESTRUCTURA (lo que sirve a otros) usa direcciones fijas. Nota cómo rima con la regla del cable y el Wi-Fi del módulo 1: lo que sirve y no se mueve, estable; lo que va y viene, flexible."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Te conectas al Wi-Fi de una cafetería y todo funciona sin configurar nada. En términos de protocolos, ¿qué acaba de pasar?","options":["Fue simplemente magia interna del navegador web","Tu equipo se inventó una IP al azar","DHCP te prestó una IP libre con su configuración","La cafetería copió la IP de tu casa"],"correctIndex":2,"feedback":{"correct":"Correcto. El repartidor hizo el papeleo en milisegundos: IP + máscara + gateway + DNS.","incorrect":"Fue DHCP: al conectarte pediste dirección y el servidor te prestó una libre con toda la configuración necesaria."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En una clínica, ¿qué dispositivos deben tener IP FIJA en vez de la que reparte DHCP, y por qué?","options":["Todos los equipos de la red, por precaución de seguridad","Solo los teléfonos de los empleados","Ninguno: usar DHCP es obligatorio","Los que otros deben ubicar: impresoras, servidores, cámaras"],"correctIndex":3,"feedback":{"correct":"Correcto. Infraestructura = fija; clientes que van y vienen = DHCP. La impresora no puede amanecer con otra dirección.","incorrect":"La regla: lo que SIRVE a otros (impresora, servidor) necesita dirección estable — fija; los clientes móviles usan DHCP."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — DHCP","points":["DHCP reparte direcciones automáticamente: IP + máscara + gateway + DNS, el kit completo.","El préstamo (lease) tiene vencimiento y se renueva; al irte, tu IP vuelve al fondo común.","En casa, el servidor DHCP es otro sombrero del router.","Clientes que van y vienen → DHCP; infraestructura que otros buscan (impresoras, servidores) → IP fija.","Por DHCP es que cualquier Wi-Fi 'simplemente funciona' sin configurar nada."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l05-dhcp';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · DNS: la guía telefónica de internet
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Los humanos usan nombres; las redes, números","body":"Nadie navega escribiendo 142.250.64.100: escribimos nombres. Pero acabas de aprender que los paquetes SOLO entienden direcciones IP. El puente es DNS (Domain Name System): la guía telefónica de internet — le das un nombre (clinica-sanrafael.com) y te devuelve su IP. Cada vez que escribes una dirección en el navegador, ANTES de cualquier otra cosa tu equipo hace una consulta DNS: pregunta al servidor DNS que le asignó DHCP (¿recuerdas el kit?), y solo cuando tiene la IP en la mano puede armar el paquete y enviarlo. Sin DNS, internet seguiría funcionando… pero tendrías que memorizar números de teléfono de cada sitio del mundo."}$j$),
  (2, 'texto', $j${"title":"El viaje de una consulta (y por qué a veces 'no carga')","body":"El viaje del nombre, paso a paso: (1) tu equipo revisa su CACHÉ — si visitaste el sitio hace poco, la IP ya está apuntada y no pregunta nada; (2) si no, consulta a su servidor DNS (normalmente el del proveedor, o públicos famosos como 8.8.8.8 — el número al que hacías ping en el módulo 1 es justamente un DNS de Google); (3) ese servidor averigua la respuesta preguntando en la jerarquía mundial de nombres, la apunta en SU caché y te la devuelve. Todo en milisegundos. Y aquí un clásico del diagnóstico: si el ping a 8.8.8.8 funciona pero 'internet no carga', la sospechosa es la resolución de nombres — la red está viva, pero la guía telefónica no contesta. Con el lab de esta región vas a interrogarla tú directamente."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿cuál es el trabajo de DNS?","options":["Traducir nombres de dominio a direcciones IP","Cifrar la conexión de extremo a extremo","Acelerar la descarga de las páginas","Repartir direcciones IP en la red local"],"correctIndex":0,"feedback":{"correct":"Correcto. La guía telefónica: nombre entra, IP sale. (Repartir IPs es DHCP — primo, pero otro oficio.)","incorrect":"DNS traduce nombres a IPs. No reparte direcciones (eso es DHCP) ni cifra nada: es la guía telefónica."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En una red, el ping a 8.8.8.8 responde perfecto, pero ninguna página 'carga' por su nombre. El diagnóstico más probable es:","options":["El cable de red está roto o mal conectado al puerto","Falla el DNS: hay internet, pero los nombres no","El navegador está muy desactualizado","La IP pública del router ya caducó"],"correctIndex":1,"feedback":{"correct":"Correcto. Red viva + nombres muertos = problema de DNS. Un diagnóstico de capa en capa, como los del módulo 2.","incorrect":"Si el ping por IP funciona, la conectividad está bien: lo que falla es la guía telefónica — la resolución DNS."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — DNS","points":["DNS traduce nombres (clinica.com) a direcciones IP: la guía telefónica de internet.","Toda visita a un sitio empieza con una consulta DNS — antes que cualquier paquete de contenido.","El viaje: caché local → servidor DNS (del proveedor o público, como 8.8.8.8) → jerarquía mundial.","Las respuestas se guardan en caché: la segunda visita no pregunta.","Ping por IP funciona pero los nombres no cargan = sospecha de DNS. Diagnóstico clásico."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l06-dns';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · IPv6: por qué existe
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La solución definitiva al agotamiento","body":"NAT fue el parche; IPv6 es la solución de fondo. En vez de los 32 bits de IPv4, usa 128 — un número de direcciones tan absurdo (340 sextillones) que cada grano de arena del planeta podría tener millones. La reconoces a simple vista: ocho grupos de caracteres hexadecimales (números y letras a–f) separados por DOS PUNTOS — 2001:0db8:85a3::8a2e:0370:7334 — y con un atajo de escritura: el :: comprime una racha de grupos en cero. Con espacio de sobra, cada dispositivo puede tener su propia dirección pública mundial: el NAT deja de ser necesidad. ¿Y por qué sigues viendo IPv4 en todas partes? Porque la transición es lenta: hoy conviven — la mayoría de las redes hablan ambos (dual stack) — y IPv4 seguirá años en tu ipconfig. Reconocer las dos es parte del oficio."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estas es una dirección IPv6?","options":["192.168.1.25, la dirección privada de siempre","255.255.255.192, una máscara de subred","2001:0db8:85a3::8a2e:0370:7334 en hexadecimal","www.clinica.com, un nombre de dominio"],"correctIndex":2,"feedback":{"correct":"Correcto. Hexadecimal + dos puntos = IPv6. El :: es el atajo que comprime grupos en cero.","incorrect":"IPv6 se reconoce por los grupos hexadecimales con DOS PUNTOS: 2001:0db8:… Los puntos simples son IPv4."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Con el espacio gigante de IPv6 (128 bits), ¿qué pieza del módulo deja de ser una necesidad y por qué?","options":["DNS, porque los nombres de dominio ya no existen","DHCP, porque las IP se inventan solas","El router entero deja de hacer falta","NAT: sobran direcciones, cada equipo con IP pública"],"correctIndex":3,"feedback":{"correct":"Correcto. NAT nació del agotamiento de IPv4; con 340 sextillones de direcciones, el malabar sobra.","incorrect":"NAT existía para compartir UNA pública entre muchos. IPv6 da direcciones para todos: el truco deja de ser necesario."}}$j$),
  (4, 'resumen', $j${"title":"Resumen — IPv6","points":["IPv6: 128 bits — direcciones prácticamente infinitas. La solución de fondo al agotamiento de IPv4.","Se reconoce por los grupos hexadecimales con dos puntos: 2001:0db8:… (el :: comprime ceros).","Con espacio de sobra, NAT deja de ser necesidad: cada dispositivo puede tener su pública.","Hoy conviven: dual stack (IPv4 + IPv6 a la vez) es lo normal — verás ambas en tu configuración.","La transición lleva años y seguirá: reconocer las dos es parte del oficio."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l07-ipv6';

-- ═════════════════════════════════════════════════════════════════════
-- L08 · Lab: sigue el camino de un nombre (nslookup + tracert/traceroute)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Hoy interrogas a internet","body":"Todo lo de este módulo se puede VER con dos comandos que vienen en cualquier computadora. Con nslookup interrogas al DNS en persona: le das un nombre y te muestra qué servidor respondió y qué IP devolvió — la consulta que tu navegador hace en secreto, ahora a la vista. Con tracert (Windows) o traceroute (Linux/Mac) sigues el CAMINO de tus paquetes salto a salto: cada línea de su salida es un router intermedio que tu tráfico cruzó — empezando por el primero de todos, que ya conoces con nombre y apellido: tu gateway. Abre tu terminal (la misma del laboratorio del módulo 1) y ejecuta los dos bloques siguientes."}$j$),
  (2, 'laboratorio', $j${"title":"nslookup: interroga a la guía telefónica","code":"# Windows, Linux y Mac (el mismo comando en todos):\nnslookup example.com\n\n# ¿Y si preguntas por un nombre que no existe?\nnslookup este-sitio-no-existe-12345.com","caption":"Fíjate en DOS datos de la salida: el 'Server' (QUIÉN respondió: tu servidor DNS, normalmente el router o el del proveedor) y la 'Address' final (la IP que el nombre esconde). La segunda consulta te muestra cómo se ve un nombre que NO está en la guía.","result":{"columns":["SALIDA (primera consulta)"],"rows":[["Server:  192.168.1.1"],["Address: 192.168.1.1#53"],[""],["Non-authoritative answer:"],["Name:    example.com"],["Address: 93.184.215.14"]],"note":"El servidor 192.168.1.1 (¡tu router, haciendo de DNS!) tradujo example.com a su IP. 'Non-authoritative' significa que respondió de su caché — la lección de DNS, en vivo."}}$j$),
  (3, 'laboratorio', $j${"title":"tracert / traceroute: el camino salto a salto","code":"# Windows:\ntracert example.com\n\n# Linux / Mac:\ntraceroute example.com","caption":"Cada línea numerada es un ROUTER que tu paquete cruzó. Verifica tres cosas: el salto 1 debe ser tu gateway (la IP de tu router — compárala con la del lab del módulo 1); los saltos siguientes son los routers de tu proveedor; y nota cómo el tiempo (ms) crece con la distancia. Algunos saltos muestran * * *: ese router prefirió no identificarse — normal.","result":{"columns":["#","SALIDA (ejemplo)"],"rows":[["1","192.168.1.1 · 2 ms   ← tu gateway"],["2","10.220.0.1 · 8 ms   ← proveedor"],["3","172.30.14.9 · 12 ms"],["4","* * *              ← no se identifica"],["5","93.184.215.14 · 98 ms ← destino"],["",""]],"note":"El viaje del módulo 2 (encapsulamiento) hecho visible: cada salto es un router abriendo el sobre hasta la capa 3, leyendo la IP de destino y pasando el paquete al siguiente."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En la salida de tracert/traceroute, ¿qué representa cada línea numerada?","options":["Un router intermedio que el paquete cruzó","Un intento de conexión que falló","Un servidor DNS de los que respondió","Una IP privada de tu propia red"],"correctIndex":0,"feedback":{"correct":"Correcto. La ruta completa, router a router — con tu gateway siempre de primero.","incorrect":"Cada salto es un router del camino: el 1 es tu gateway y los siguientes, los routers entre tú y el destino."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Ejecutas nslookup y el campo 'Server' muestra 192.168.1.1. ¿Qué significa?","options":["El sitio consultado vive dentro de tu casa","Tu servidor DNS es tu propio router: él respondió","No hay conexión a internet ahora mismo","La consulta de nombre falló por completo"],"correctIndex":1,"feedback":{"correct":"Correcto. El router de casa suele hacer también de DNS para la red local — un sombrero más sobre los cuatro del módulo 1.","incorrect":"192.168.1.1 es tu router: hace de servidor DNS local, respondiendo de caché o preguntando al proveedor por ti."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — El lab del camino","points":["nslookup interroga al DNS: muestra QUIÉN respondió (Server) y la IP del nombre (Address).","'Non-authoritative answer' = respondió una caché, no la fuente original: la lección de DNS en vivo.","tracert (Windows) / traceroute (Linux/Mac): la ruta salto a salto — cada línea, un router.","El salto 1 es SIEMPRE tu gateway; los * * * son routers que no se identifican (normal).","Acabas de ver el encapsulamiento del módulo 2 en acción: routers abriendo sobres hasta la capa 3."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-l08-lab-camino';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La tercera región","body":"Byte llegó a la región del direccionamiento: diez preguntas guardan el paso. Todo lo viviste: las IP y sus dos mundos, las subredes con su fórmula, el NAT, el repartidor DHCP, la guía telefónica DNS, el nuevo mundo IPv6 y los comandos con los que interrogaste a internet. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"192.168.1.25 y 10.0.0.7 comparten algo importante. ¿Qué son?","options":["Direcciones públicas visibles en internet","Direcciones del protocolo IPv6","Privadas: rangos reservados para redes locales","Máscaras de subred de las redes"],"correctIndex":2,"feedback":{"correct":"Correcto. 192.168.x.x y 10.x.x.x son rangos privados por convención mundial.","incorrect":"Ambas pertenecen a los rangos PRIVADOS (192.168.x.x y 10.x.x.x): viven en redes locales, no en internet."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En 192.168.10.0/26, la fórmula 2^(32−n) − 2 da como hosts útiles:","options":["254 hosts útiles, como en una red /24","64 hosts, todos utilizables","30 hosts útiles en total","62: seis bits de host → 64 − 2 reservadas"],"correctIndex":3,"feedback":{"correct":"Correcto. 32−26 = 6 → 2^6 = 64 − 2 = 62. La fórmula de tu hoja de subredes.","incorrect":"32−26 deja 6 bits de host: 2^6 = 64, menos la dirección de red y el broadcast = 62 útiles."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"La máscara decimal equivalente a /26 es:","options":["255.255.255.192, según el patrón de la /26","255.255.255.0, la máscara de una /24","255.255.255.224, la máscara de una /27","255.255.0.0, la máscara de una /16"],"correctIndex":0,"feedback":{"correct":"Correcto. Cada bit extra suma la mitad del anterior: 128 + 64 = 192.","incorrect":"El patrón del último octeto: /24→0, /25→128, /26→192, /27→224. Para /26: 255.255.255.192."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un laboratorio necesita conectar 30 equipos. El prefijo MÁS ajustado que les da cabida es:","options":["/28, que solo da 14 hosts útiles","/27: 2^5 − 2 = 30 hosts útiles justos","/24, tomando siempre lo más grande","/30, que da apenas 2 hosts"],"correctIndex":1,"feedback":{"correct":"Correcto. /27 da exactamente 30 útiles; /28 se queda corto con 14. Dimensionar justo es el oficio.","incorrect":"/27 deja 5 bits de host: 2^5 − 2 = 30, cabida exacta. /28 solo alcanza para 14."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué una clínica separa administración, equipos médicos y Wi-Fi de pacientes en SUBREDES distintas?","options":["Para gastar más direcciones IP disponibles","Porque el cable de red no alcanza tan lejos","Segmentación: cruzar obliga a pasar por el router","Porque lo exige el proveedor de internet"],"correctIndex":2,"feedback":{"correct":"Correcto. Barrios separados con control en el cruce: la semilla de seguridad que florece en el módulo 6.","incorrect":"Partir la red crea fronteras lógicas: el tráfico entre subredes pasa por el router, donde se vigila y filtra."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Cuarenta dispositivos de una oficina navegan a la vez y todos los sitios web ven UNA sola dirección. El responsable es:","options":["DNS, que traduce los nombres de dominio a IPs","DHCP, que reparte las direcciones","El navegador, al abrir la página","NAT: traduce las privadas a la única pública"],"correctIndex":3,"feedback":{"correct":"Correcto. Muchas casas, una puerta: la traducción de direcciones del router.","incorrect":"Es NAT: privadas adentro, UNA pública afuera, y la tabla de traducciones haciendo el reparto de vuelta."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Al conectarte a una red, tu equipo recibe automáticamente IP, máscara, gateway y servidor DNS. El protocolo que hizo ese reparto es:","options":["DHCP: presta una dirección libre y su configuración","NAT, que traduce las IP al salir a internet","DNS, que resuelve los nombres de dominio a IPs","IPv6, que da direcciones de sobra"],"correctIndex":0,"feedback":{"correct":"Correcto. El repartidor automático: por él, cualquier Wi-Fi 'simplemente funciona'.","incorrect":"Es DHCP: el préstamo automático de dirección + máscara + gateway + DNS al conectarte."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"El ping a 8.8.8.8 responde, pero ningún sitio carga por su nombre. La causa más probable:","options":["El módem está apagado o acaba de reiniciarse","Falla el DNS: hay conexión, pero no traducción","Se acabaron las IP privadas de la red","La tabla del NAT del router está llena"],"correctIndex":1,"feedback":{"correct":"Correcto. Red viva, guía telefónica muerta: el diagnóstico apunta a DNS.","incorrect":"Si la IP responde, la salida a internet está bien: lo roto es la traducción de nombres — DNS."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"En la salida de tracert/traceroute, el salto número 1 es SIEMPRE:","options":["El servidor de destino que consultaste","Un servidor DNS que respondió antes","Tu gateway: la puerta de salida de tu red","Una dirección IPv6 del proveedor"],"correctIndex":2,"feedback":{"correct":"Correcto. Todo viaje hacia afuera empieza por la misma puerta: tu router.","incorrect":"El primer salto es tu gateway — el router de tu red, por donde sale todo el tráfico hacia otras redes."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'la clínica quiere que el Wi-Fi de los pacientes no pueda tocar el servidor de expedientes — ¿basta con ponerle otra contraseña al Wi-Fi?' Tu respuesta senior:","options":["Sí, con una contraseña larga y muy fuerte ya alcanza de sobra","No, la única solución real es apagar el Wi-Fi por completo","Sí, si además se oculta el nombre de la red a la vista","No: la clave dice quién entra, no a dónde; hace falta subred aparte"],"correctIndex":3,"feedback":{"correct":"Impecable. Autenticar no es segmentar: la frontera de verdad es de direccionamiento (subredes) con control en el router. El módulo 6 arma esta arquitectura completa.","incorrect":"La respuesta senior separa dos cosas: la contraseña decide quién ENTRA; la subred decide a dónde LLEGA. Invitados en su propia subred, y el router vigilando el cruce."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm03-x01-examen';
