-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 023 — Redes y Sistemas · Módulo 4: Protocolos clave
-- ═══════════════════════════════════════════════════════════════════
-- 7 lecciones + examen de región (48 bloques).
-- Incluye el diagrama del temario: "El viaje de una petición HTTPS"
-- (DNS → TCP → TLS → HTTP) con NetworkDiagram data-driven.
-- Hilos que paga: el servidor "escuchando" del M1 recibe su dirección
-- completa (IP:puerto); las capas del M2 se encarnan (transporte=TCP/UDP,
-- aplicación=HTTP); el DNS del M3 abre el viaje HTTPS.
-- Reglas de contenido: sin tecnología interna de la plataforma;
-- quizzes autocontenidos o con términos técnicos.
-- OJO: Redes está PUBLICADO — correr esta migración hace el M4
-- visible a los usuarios AL INSTANTE.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 006.
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'redes-y-sistemas' and m.slug = 'm04-protocolos-clave'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m04-l01-puertos',        'Puertos: las puertas numeradas',      'leccion', 20, 1),
       ('m04-l02-tcp-udp',        'TCP y UDP: fiabilidad o velocidad',   'leccion', 20, 2),
       ('m04-l03-http-https',     'HTTP y HTTPS: la conversación web',   'leccion', 20, 3),
       ('m04-l04-tls',            'TLS: qué protege el candado (y qué no)', 'leccion', 20, 4),
       ('m04-l05-viaje-https',    'El viaje de una petición HTTPS',      'leccion', 20, 5),
       ('m04-l06-ssh',            'SSH: administrar a distancia',        'leccion', 20, 6),
       ('m04-l07-correo',         'Correo: SMTP, IMAP y el phishing',    'leccion', 20, 7),
       ('m04-x01-examen',         'Examen: Protocolos clave',            'examen',  40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'redes-y-sistemas' and m.slug = 'm04-protocolos-clave';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Puertos: las puertas numeradas
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Una dirección no basta","body":"En el módulo 1 aprendiste que un servidor vive ESCUCHANDO, y prometimos contarte la pieza que lo hace posible. Aquí está: el servidor de la clínica tiene UNA IP… pero corre varios servicios a la vez — la web de citas, el correo, el acceso remoto del técnico. ¿Cómo sabe la red a cuál de ellos va cada paquete? Por el PUERTO: un número (de 0 a 65535) que funciona como puerta numerada dentro de la máquina. Cada servicio escucha en la suya, y la capa de transporte (la capa 4 del módulo 2 — su cabecera llevaba justamente los puertos) entrega cada conversación tras la puerta correcta. La dirección completa de un servicio no es la IP: es IP:puerto — 192.168.1.10:443 dice máquina Y puerta."}$j$),
  (2, 'texto', $j${"title":"Los números que hay que saludar","body":"Los servicios famosos tienen puertos reservados por convención mundial (los 'well-known ports'), y conocer los principales es vocabulario del oficio: 80 = HTTP (web sin cifrar) · 443 = HTTPS (web cifrada) · 22 = SSH (administración remota) · 53 = DNS (¡la guía telefónica del módulo 3 también tiene su puerta!) · 25/587 = SMTP (envío de correo) · 143 = IMAP (lectura de correo). Del lado del cliente no hay número fijo: tu navegador usa un puerto EFÍMERO (alto y temporal) para cada conversación — por eso puedes tener veinte pestañas abiertas contra el mismo sitio sin que las respuestas se mezclen: cada una es una pareja IP:puerto distinta."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué es un puerto?","options":["Un cable especial","Un NÚMERO que identifica a un servicio concreto dentro de una máquina: la puerta numerada tras la que ese servicio escucha","Una dirección IP corta","Un tipo de router"],"correctIndex":1,"feedback":{"correct":"Correcto. La IP encuentra la máquina; el puerto encuentra el servicio dentro de ella.","incorrect":"El puerto es un número (0–65535) que distingue servicios dentro de una misma máquina: la web en una puerta, el correo en otra."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un servidor con UNA sola IP atiende a la vez su página web y el correo, sin mezclar nada. ¿Qué lo hace posible?","options":["Tiene dos cables","Los PUERTOS: cada servicio escucha en su puerta numerada (la web en la 443, el correo en la suya) y la capa de transporte reparte","Se turnan por horario","Es imposible: necesita dos IPs"],"correctIndex":1,"feedback":{"correct":"Correcto. Una máquina, muchas puertas: IP:puerto es la dirección completa de cada servicio.","incorrect":"Una IP con varios puertos: cada servicio en su puerta. La cabecera de transporte (capa 4) lleva el número que decide la entrega."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"De la lista de puertos reservados, ¿cuál corresponde a HTTPS — la web cifrada?","options":["22","80","443","53"],"correctIndex":2,"feedback":{"correct":"Correcto. 443 = HTTPS. Sus vecinos famosos: 80 HTTP, 22 SSH, 53 DNS.","incorrect":"HTTPS vive en el 443. El 80 es HTTP sin cifrar, el 22 es SSH y el 53 es DNS."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Puertos","points":["La IP encuentra la máquina; el PUERTO encuentra el servicio dentro de ella: la dirección completa es IP:puerto.","Cada servicio escucha tras su puerta numerada — la promesa del 'servidor que escucha' del módulo 1, cumplida.","Los números del oficio: 80 HTTP · 443 HTTPS · 22 SSH · 53 DNS · 25/587 SMTP · 143 IMAP.","El cliente usa puertos efímeros: por eso veinte pestañas no se mezclan.","Los puertos viajan en la cabecera de transporte — la capa 4 del módulo 2."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-l01-puertos';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · TCP y UDP: fiabilidad o velocidad
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Correo certificado vs postales","body":"La capa de transporte tiene dos estilos, y elegir el correcto es una decisión de ingeniería. TCP es el correo certificado: antes de enviar nada, establece una CONEXIÓN con el destino (un saludo de tres pasos), numera cada segmento, exige CONFIRMACIÓN de recibido y REENVÍA lo que se pierda — garantiza que todo llegue completo y en orden, a cambio de ceremonia y algo de velocidad. UDP es la postal: sin conexión, sin confirmaciones, sin reenvíos — dispara datagramas y confía. Mucho más rápido y ligero… sin ninguna garantía. Ninguno es 'mejor': son herramientas para problemas distintos."}$j$),
  (2, 'texto', $j${"title":"Cuál usar: la pregunta del byte perdido","body":"La decisión se toma con una pregunta: ¿qué pasa si se pierde un pedazo? Si la respuesta es 'desastre' — una página web a la que le falta la mitad, un expediente médico incompleto, un archivo corrupto — necesitas TCP: web, correo y transferencias de archivos van por ahí. Si la respuesta es 'ni se nota, pero llegar TARDE sí arruina todo' — un instante de video congelado en la videollamada con el especialista, un frame perdido del streaming — eso es UDP: re-pedir un pedazo viejo no tiene sentido cuando el momento ya pasó. Dato curioso que une módulos: las consultas DNS van por UDP — son tan pequeñas y rápidas que si una se pierde, sale más barato repreguntar que mantener toda la ceremonia de TCP."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de garantías, ¿qué ofrece TCP que UDP no?","options":["Mayor velocidad","Conexión establecida, entrega COMPLETA y EN ORDEN, con confirmaciones y reenvío de lo perdido","Cifrado automático","Direcciones IP más largas"],"correctIndex":1,"feedback":{"correct":"Correcto. El correo certificado: todo llega, en orden, o se reenvía. La velocidad es justo lo que sacrifica.","incorrect":"TCP garantiza entrega completa y ordenada (conexión + confirmaciones + reenvíos); UDP es el rápido sin garantías. El cifrado es asunto de TLS."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Una clínica hace videollamadas con especialistas remotos. Ese tráfico viaja por UDP y no por TCP. ¿Por qué es la elección correcta?","options":["Porque UDP es más seguro","Porque en video EN VIVO llegar tarde arruina más que perder un instante: re-pedir un frame viejo no tiene sentido cuando el momento ya pasó","Porque TCP no soporta video","Porque UDP cifra mejor"],"correctIndex":1,"feedback":{"correct":"Correcto. La pregunta del byte perdido: un frame menos ni se nota; medio segundo de retraso, sí.","incorrect":"El tiempo real prefiere velocidad sobre perfección: un pedazo perdido no se extraña, pero la ceremonia de TCP atrasaría la conversación."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — TCP y UDP","points":["TCP: conexión + orden + confirmaciones + reenvíos = todo llega completo. El correo certificado.","UDP: sin ceremonia, rápido, sin garantías. La postal.","La pregunta decisiva: ¿perder un pedazo es desastre (TCP) o llegar tarde es peor (UDP)?","Web, correo y archivos → TCP. Video en vivo, llamadas, juegos → UDP.","Las consultas DNS van por UDP: tan pequeñas que repreguntar sale más barato que la ceremonia."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-l02-tcp-udp';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · HTTP y HTTPS: la conversación web
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El idioma de la web","body":"HTTP (HyperText Transfer Protocol) es el protocolo de aplicación — capa 7, el nivel de los idiomas que hablan los programas — con el que navegador y servidor conversan. La conversación es la de siempre: PETICIÓN y RESPUESTA. El navegador pide (GET /citas — 'dame la página de citas'; POST — 'te envío estos datos, guárdalos') y el servidor responde con un CÓDIGO DE ESTADO y el contenido. Los códigos son vocabulario del oficio: 200 = todo bien · 404 = eso no existe aquí (el más famoso de internet) · 403 = existe pero no tienes permiso · 500 = el servidor tiene un problema interno. Cuando una página 'no carga', el código de estado es la primera pista del diagnóstico."}$j$),
  (2, 'texto', $j${"title":"El problema de HTTP: viaja desnudo","body":"HTTP tiene un defecto de nacimiento: viaja en TEXTO PLANO. ¿Recuerdas la lección de encapsulamiento del módulo 2? Los intermediarios ven los sobres, no la carta… pero si la carta va SIN CIFRAR, quien esté en el camino — el Wi-Fi de la cafetería, cualquier equipo intermedio — puede leerla completa: contraseñas, expedientes, tarjetas. La solución es HTTPS: el MISMO HTTP, pero viajando dentro de un túnel cifrado llamado TLS (siguiente lección). Es la S final: HTTP por el puerto 80 y desnudo; HTTPS por el 443 y cifrado. El candado que ves junto a la dirección en el navegador anuncia exactamente eso. Hoy, ningún sitio serio — y ninguna clínica — debería hablar HTTP a secas."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Visitas una página y el servidor responde con el código 404. En términos del protocolo, ¿qué te está diciendo?","options":["Todo bien, aquí está la página","Que el recurso pedido NO EXISTE en ese servidor","Que no tienes permiso","Que el servidor explotó por dentro"],"correctIndex":1,"feedback":{"correct":"Correcto. 404 = no existe. Sus vecinos: 200 todo bien, 403 sin permiso, 500 error interno del servidor.","incorrect":"404 es el 'no existe' de la web. 200 = bien · 403 = sin permiso · 500 = problema interno del servidor."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia real entre HTTP y HTTPS?","options":["HTTPS es una versión más moderna con más funciones","Ninguna en el idioma: HTTPS es el MISMO HTTP viajando dentro de un túnel cifrado (TLS), por el puerto 443 en vez del 80","HTTPS es más lento y por eso mejor","HTTP es solo para páginas viejas"],"correctIndex":1,"feedback":{"correct":"Correcto. La S es el túnel: mismo idioma, pero cifrado. 80 desnudo, 443 con candado.","incorrect":"El idioma es idéntico: la diferencia es que HTTPS viaja cifrado dentro de TLS (puerto 443). HTTP a secas viaja legible para cualquiera en el camino."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — HTTP y HTTPS","points":["HTTP: el idioma de la web (capa 7) — petición (GET/POST) y respuesta con código de estado.","Códigos del oficio: 200 bien · 404 no existe · 403 sin permiso · 500 error del servidor.","HTTP viaja en texto plano: cualquiera en el camino puede leer la carta.","HTTPS = el mismo HTTP dentro del túnel cifrado TLS. Puerto 80 → 443.","El candado del navegador anuncia el túnel — la próxima lección revisa qué promete exactamente."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-l03-http-https';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · TLS: qué protege el candado (y qué no)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Las dos promesas del candado","body":"TLS (Transport Layer Security) hace dos trabajos, y los dos importan. PRIMERO, cifra la conversación: navegador y servidor acuerdan claves secretas al inicio, y desde ahí todo viaja ilegible para los intermediarios — el contenido queda protegido incluso cruzando redes ajenas. SEGUNDO, verifica la IDENTIDAD del sitio mediante su CERTIFICADO: un documento digital que dice 'este servidor es realmente clinica-sanrafael.com', firmado por una autoridad de certificación en la que tu navegador ya confía de fábrica. Si el certificado no cuadra — vencido, de otro dominio, firmado por nadie — el navegador te frena con una advertencia a pantalla completa. Esas advertencias no se ignoran: son el sistema funcionando."}$j$),
  (2, 'texto', $j${"title":"Lo que el candado NO promete","body":"Aquí viene la lección que separa al usuario informado del resto: el candado significa 'la conexión con ESTE sitio es privada y el sitio es quien dice ser'… y NADA MÁS. No dice que el sitio sea honesto: un sitio de estafa puede tener su certificado perfectamente válido — clinica-sanrafae1.com (¿notaste el 1?) puede lucir su candado mientras te roba la contraseña. El candado autentica el NOMBRE, no las intenciones. Y otro límite: TLS cifra el contenido, pero no oculta A QUIÉN visitas — los intermediarios siguen viendo el destino de tus paquetes (los sobres del módulo 2), solo que ya no pueden leer la carta. Guarda ambas ideas: reaparecen en el phishing (última lección) y en toda tu ruta de seguridad."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿cuáles son las DOS promesas de TLS?","options":["Velocidad y ahorro de datos","CIFRAR la conversación (ilegible para intermediarios) y VERIFICAR la identidad del sitio mediante su certificado","Bloquear virus y publicidad","Ocultar tu ubicación"],"correctIndex":1,"feedback":{"correct":"Correcto. Privacidad del contenido + autenticidad del nombre: ese es el contrato completo del candado.","incorrect":"TLS promete dos cosas: nadie lee la conversación (cifrado) y el sitio es quien dice ser (certificado). Ni más, ni menos."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un sitio de estafa que imita a un banco muestra el candado de HTTPS en el navegador. ¿Es posible, y qué significa?","options":["Imposible: el candado garantiza sitios honestos","Posible: el candado autentica el NOMBRE del dominio y cifra la conexión — no juzga las intenciones del sitio. La conexión con el estafador es privada… con el estafador","Posible, pero solo en teléfonos","Imposible: los certificados cuestan millones"],"correctIndex":1,"feedback":{"correct":"Correcto. El candado dice 'conexión privada con este dominio', no 'este dominio es de fiar'. La distinción que salva cuentas bancarias.","incorrect":"Cualquier dominio puede tener certificado válido, también los fraudulentos: el candado verifica identidad del nombre, no honestidad."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — TLS","points":["TLS cifra la conversación: los intermediarios ven los sobres, ya no la carta.","El certificado verifica la identidad: 'este servidor ES clinica.com', firmado por una autoridad de confianza.","Las advertencias de certificado del navegador no se ignoran: son el sistema funcionando.","El candado NO promete honestidad: un sitio de estafa puede tenerlo — autentica el nombre, no las intenciones.","TLS tampoco oculta A QUIÉN visitas: cifra el contenido, no el destino."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-l04-tls';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · El viaje de una petición HTTPS (diagrama del temario)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Todo el curso en dos segundos","body":"Escribes el nombre de un sitio, pulsas Enter, y en menos de dos segundos aparece la página. En ese parpadeo ocurrió TODO lo que has aprendido, en un orden preciso: la guía telefónica tradujo el nombre (DNS, módulo 3), el correo certificado abrió la conexión (TCP, hacia el puerto 443), el candado se cerró (TLS) y solo entonces se habló el idioma de la web (HTTP) — ya en privado. Explora el diagrama del siguiente bloque: toca cada paso y cada flecha, y fíjate en el ORDEN — cada etapa necesita a la anterior, y esa dependencia es la clave de todo diagnóstico: cuando algo falla, se revisa etapa por etapa, de arriba hacia abajo."}$j$),
  (2, 'diagrama', $j${"title":"El viaje de una petición HTTPS","component":"NetworkDiagram","props":{"label":"De escribir el nombre a ver la página","ancho":520,"alto":448,"nodos":[{"id":"inicio","x":150,"y":16,"w":220,"h":40,"titulo":"Escribes clinica.com","subtitulo":"y pulsas Enter","descripcion":"El punto de partida: un nombre humano. Los paquetes necesitan una IP — por eso el primer paso es siempre la traducción."},{"id":"dns","x":150,"y":92,"w":220,"h":44,"titulo":"1 · DNS","subtitulo":"nombre → IP","tag":"módulo 3","descripcion":"La consulta a la guía telefónica: tu equipo pregunta a su servidor DNS qué IP tiene clinica.com. Sin respuesta aquí, el viaje no empieza — el diagnóstico 'ping sí, nombres no' vive en este paso."},{"id":"tcp","x":150,"y":168,"w":220,"h":44,"titulo":"2 · TCP","subtitulo":"conexión al puerto 443","descripcion":"Con la IP en mano, el saludo de tres pasos abre una conexión fiable con el puerto 443 del servidor: desde ahora, todo llega completo y en orden — o se reenvía."},{"id":"tls","x":150,"y":244,"w":220,"h":44,"titulo":"3 · TLS","subtitulo":"certificado + cifrado","descripcion":"El candado se cierra: el servidor presenta su certificado (¿eres realmente clinica.com?), se acuerdan las claves y la conversación queda ilegible para los intermediarios."},{"id":"http","x":150,"y":320,"w":220,"h":44,"titulo":"4 · HTTP","subtitulo":"petición y respuesta","descripcion":"Recién ahora se habla el idioma de la web — GET /citas → 200 con el contenido — pero ya dentro del túnel: cualquier intermediario ve sobres cifrados."},{"id":"fin","x":150,"y":396,"w":220,"h":40,"titulo":"La página aparece","subtitulo":"~2 segundos después","descripcion":"Cuatro protocolos coordinados en un parpadeo. Cada uno hizo UN trabajo: traducir, conectar, cifrar, conversar."}],"enlaces":[{"de":"inicio","a":"dns","tipo":"flecha","descripcion":"Nada viaja aún: primero hay que saber la IP de destino."},{"de":"dns","a":"tcp","tipo":"flecha","etiqueta":"con la IP","descripcion":"La respuesta del DNS habilita el paso 2: ya se sabe a qué máquina conectarse."},{"de":"tcp","a":"tls","tipo":"flecha","etiqueta":"conexión abierta","descripcion":"Sobre la conexión fiable de TCP se negocia el cifrado: TLS necesita un canal donde nada se pierda."},{"de":"tls","a":"http","tipo":"flecha","etiqueta":"túnel cifrado","descripcion":"Con el candado cerrado, HTTP conversa en privado: peticiones y respuestas ilegibles para el camino."},{"de":"http","a":"fin","tipo":"flecha","etiqueta":"200 OK","descripcion":"La respuesta llega, el navegador la pinta: el viaje termina donde empezó — en tu pantalla."}],"hint":"Toca cada paso y cada flecha. El orden ES la lección: cada etapa necesita a la anterior."},"caption":"DNS → TCP → TLS → HTTP: traducir, conectar, cifrar, conversar. Cuando algo falle, diagnostica en ese orden — el paso roto detiene a todos los que siguen."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En el viaje de una petición HTTPS, el orden correcto de los cuatro protocolos es:","options":["HTTP → TLS → TCP → DNS","DNS → TCP → TLS → HTTP: traducir el nombre, abrir la conexión, cerrar el candado, conversar","TCP → DNS → HTTP → TLS","El orden es aleatorio"],"correctIndex":1,"feedback":{"correct":"Correcto. Cada etapa necesita a la anterior: sin IP no hay conexión, sin conexión no hay cifrado, sin cifrado no se conversa.","incorrect":"El orden es dependencia pura: DNS da la IP → TCP abre la conexión → TLS la cifra → HTTP conversa dentro."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un usuario reporta que 'la página no abre'. Sabiendo que el viaje es DNS → TCP → TLS → HTTP, ¿por qué conviene diagnosticar EN ESE ORDEN?","options":["Por tradición","Porque cada etapa depende de la anterior: el paso roto detiene a todos los que siguen — encontrarlo primero evita buscar donde no es","Porque HTTP nunca falla","Porque el DNS es el más lento"],"correctIndex":1,"feedback":{"correct":"Correcto. El diagnóstico por etapas del módulo 2, aplicado: encuentra el primer eslabón roto y los demás se explican solos.","incorrect":"La cadena se rompe en su primer eslabón fallido: revisar en orden (¿resuelve el nombre? ¿conecta? ¿certificado válido?) localiza el problema sin adivinar."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — El viaje HTTPS","points":["Cuatro protocolos en orden de dependencia: DNS (traducir) → TCP (conectar, puerto 443) → TLS (cifrar y verificar) → HTTP (conversar).","Cada etapa necesita a la anterior: sin IP no hay conexión; sin conexión, no hay candado; sin candado, no se habla.","Todo ocurre en ~2 segundos, cada protocolo haciendo UN trabajo.","El diagnóstico sigue el mismo orden: el primer eslabón roto explica el resto.","Este diagrama es el módulo entero en una imagen — y reaparecerá en tus cursos de seguridad."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-l05-viaje-https';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · SSH: administrar a distancia
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La terminal que viaja cifrada","body":"El servidor de expedientes de la clínica vive en un cuarto cerrado con llave — pero el técnico lo administra desde su oficina, o desde su casa. ¿Cómo? Con SSH (Secure Shell, puerto 22): una TERMINAL REMOTA CIFRADA — el técnico escribe comandos en su equipo y se ejecutan en el servidor, con toda la sesión viajando dentro de un túnel cifrado (el mismo espíritu de TLS: nadie en el camino lee nada). SSH reemplazó a su antecesor Telnet, que hacía lo mismo… en texto plano: cada comando y CADA CONTRASEÑA viajaban legibles para cualquier intermediario. Hoy usar Telnet es negligencia; ver su puerto abierto en un equipo es una señal de alarma. La autenticación de SSH admite contraseña o — el estándar profesional — LLAVES criptográficas: un par de archivos (llave privada que guardas, pública que instalas en el servidor) que ni se teclea ni se adivina."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué es SSH y en qué puerto vive?","options":["Un antivirus, puerto 80","Una TERMINAL REMOTA CIFRADA (puerto 22): comandos escritos aquí, ejecutados allá, con la sesión completa dentro de un túnel cifrado","Un tipo de cable, puerto 443","Un navegador para servidores, puerto 53"],"correctIndex":1,"feedback":{"correct":"Correcto. La herramienta con la que se administra medio internet, desde cualquier parte.","incorrect":"SSH = Secure Shell, puerto 22: una terminal remota donde todo — comandos y contraseñas — viaja cifrado."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"SSH reemplazó a Telnet como terminal remota. ¿Cuál era el problema letal de Telnet?","options":["Era demasiado lento","Viajaba en TEXTO PLANO: cada comando y cada contraseña quedaban legibles para cualquier intermediario del camino","No funcionaba en Windows","Usaba demasiados puertos"],"correctIndex":1,"feedback":{"correct":"Correcto. La lección de HTTP repetida: lo que viaja sin cifrar, lo lee el camino. Con contraseñas de administrador en juego, letal.","incorrect":"Telnet hacía lo mismo que SSH pero sin cifrar: contraseñas de administrador viajando legibles. Por eso hoy verlo activo es señal de alarma."}}$j$),
  (4, 'resumen', $j${"title":"Resumen — SSH","points":["SSH (puerto 22): terminal remota cifrada — comandos escritos aquí, ejecutados en el servidor.","Toda la sesión viaja en túnel cifrado: nadie en el camino lee comandos ni contraseñas.","Su antecesor Telnet iba en texto plano: hoy es negligencia y señal de alarma.","Autenticación profesional: llaves criptográficas (privada contigo, pública en el servidor).","Así se administra la infraestructura del mundo — incluido el servidor de la clínica."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-l06-ssh';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Correo: SMTP, IMAP y el phishing
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El cartero y el buzón","body":"El correo electrónico usa protocolos distintos para ir y para venir. SMTP (puertos 25/587) es el CARTERO: lleva el mensaje de tu servidor de correo al del destinatario — solo envía. Para LEER, dos opciones: IMAP (puerto 143) mantiene los mensajes EN el servidor y los sincroniza — por eso ves lo mismo en el teléfono y la laptop, y lo que borras en uno desaparece en el otro; POP, el veterano, descarga los mensajes a UN dispositivo y suele borrarlos del servidor — hoy casi siempre querrás IMAP. Tres protocolos, tres oficios: SMTP envía, IMAP sincroniza, POP descarga."}$j$),
  (2, 'texto', $j${"title":"Por qué existe el phishing","body":"SMTP nació en los años 80, entre universidades que confiaban entre sí — y arrastra ese pecado original: el campo 'De:' (el remitente) es texto que el emisor ESCRIBE LIBREMENTE, como el remitente de un sobre de papel. El protocolo no verifica que quien dice ser 'Banco Nacional' lo sea. De esa grieta vive el PHISHING: correos que imitan a tu banco, a tu jefa o a la clínica para pescarte credenciales o pagos. Las defensas técnicas modernas (verificaciones que los servidores se hacen entre sí) atajan mucho, pero no todo — y por eso la última línea de defensa es de CRITERIO: desconfía de la urgencia ('su cuenta será suspendida HOY'), revisa el dominio real detrás del nombre amable, y ante cualquier duda verifica POR OTRO CANAL — llama al número que ya tenías, no al que trae el correo. Y recuerda la lección del candado: que el enlace lleve HTTPS no lo vuelve legítimo."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"De los protocolos de correo, ¿cuál ENVÍA y cuál permite leer lo mismo sincronizado en varios dispositivos?","options":["IMAP envía; SMTP sincroniza","SMTP envía (el cartero); IMAP mantiene y sincroniza los mensajes en el servidor (el buzón compartido)","POP hace ambas cosas","HTTP envía y DNS sincroniza"],"correctIndex":1,"feedback":{"correct":"Correcto. SMTP = ida; IMAP = lectura sincronizada. POP, el veterano, descarga a un solo dispositivo.","incorrect":"El cartero es SMTP (solo envía); IMAP guarda los mensajes en el servidor y los sincroniza entre tus dispositivos."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué debilidad de diseño del correo hace posible el phishing?","options":["Los archivos adjuntos pesan mucho","El remitente ('De:') es un campo que el emisor escribe LIBREMENTE y el protocolo no verifica — como el remitente de un sobre de papel","Los servidores de correo no usan puertos","El correo no funciona con HTTPS"],"correctIndex":1,"feedback":{"correct":"Correcto. SMTP nació entre quienes confiaban entre sí: el 'De:' se declara, no se demuestra. De esa grieta vive el phishing.","incorrect":"El protocolo no verifica el remitente: cualquiera puede escribir 'Banco Nacional' en el De:. Por eso la defensa final es tu criterio."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Correo y phishing","points":["SMTP (25/587) envía · IMAP (143) sincroniza en el servidor · POP descarga a un dispositivo.","El 'De:' del correo se declara, no se verifica: el pecado original de SMTP.","De esa grieta vive el phishing: correos que imitan para pescar credenciales o pagos.","Defensas de criterio: desconfiar de la urgencia, mirar el dominio real, verificar POR OTRO CANAL.","El candado no legitima: un enlace de phishing puede llevar HTTPS válido (lección de TLS)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-l07-correo';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La cuarta región","body":"Byte llegó a la región de los protocolos: diez preguntas guardan el paso. Todo lo viviste: las puertas numeradas, el correo certificado y las postales, la conversación de la web con su candado, el viaje completo de una petición, la terminal cifrada y el cartero ingenuo del correo. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"La dirección COMPLETA de un servicio en la red — máquina y puerta — se escribe:","options":["Solo la IP basta","IP:puerto — por ejemplo 192.168.1.10:443 — porque la IP encuentra la máquina y el puerto, el servicio dentro de ella","nombre@dominio","MAC + máscara"],"correctIndex":1,"feedback":{"correct":"Correcto. Dos coordenadas: la máquina (IP) y la puerta del servicio (puerto).","incorrect":"IP:puerto: la IP localiza la máquina y el puerto distingue cuál de sus servicios atiende."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Empareja los puertos con sus servicios: 443, 22 y 53 son, respectivamente:","options":["HTTP, DNS y SSH","HTTPS, SSH y DNS","SSH, HTTPS y SMTP","DNS, IMAP y HTTP"],"correctIndex":1,"feedback":{"correct":"Correcto. 443 la web cifrada, 22 la terminal remota, 53 la guía telefónica.","incorrect":"El vocabulario del oficio: 443 = HTTPS · 22 = SSH · 53 = DNS (y 80 = HTTP sin cifrar)."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Descargas el expediente PDF de un paciente: no puede faltarle ni un byte. El protocolo de transporte correcto y su razón:","options":["UDP, por velocidad","TCP: conexión, orden, confirmaciones y reenvíos — la garantía de que el archivo llega completo","UDP, porque cifra","Cualquiera da igual"],"correctIndex":1,"feedback":{"correct":"Correcto. Perder un pedazo = archivo corrupto: eso es territorio TCP.","incorrect":"Un archivo incompleto es un archivo roto: TCP garantiza entrega completa y en orden — la pregunta del byte perdido."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En una videollamada en vivo se pierde un instante de video y NO se reenvía. En términos de protocolos, esto es:","options":["Un error de la red","UDP funcionando como debe: en tiempo real, re-pedir un pedazo viejo no tiene sentido — llegar tarde arruina más que perder un frame","TCP fallando","El candado de TLS"],"correctIndex":1,"feedback":{"correct":"Correcto. La postal: rápida y sin ceremonia. El momento perdido ya pasó; el retraso sí se nota.","incorrect":"Es el diseño de UDP: velocidad sobre perfección. En vivo, un frame perdido ni se extraña; medio segundo de retraso, sí."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"El navegador pide una página y recibe el código 500. El diagnóstico correcto:","options":["La página no existe","No tienes permiso","El SERVIDOR tiene un problema interno: la petición llegó bien, pero algo falló de su lado","Todo salió bien"],"correctIndex":2,"feedback":{"correct":"Correcto. 500 = 'el problema es mío', dice el servidor. 404 = no existe · 403 = sin permiso · 200 = bien.","incorrect":"Los 5xx son problemas DEL SERVIDOR: tu petición llegó, pero algo explotó de su lado. 404 = no existe, 403 = sin permiso."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"HTTPS se diferencia de HTTP en que:","options":["Usa otro idioma de peticiones","Es el MISMO HTTP viajando dentro del túnel cifrado TLS (puerto 443): mismo idioma, carta ilegible para el camino","Es más nuevo y con más funciones","Solo funciona en bancos"],"correctIndex":1,"feedback":{"correct":"Correcto. La S es el túnel: el idioma no cambia, la privacidad sí.","incorrect":"Mismo protocolo, distinto viaje: HTTPS mete la conversación HTTP dentro de TLS — cifrada de extremo a extremo del túnel."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Un correo 'del banco' trae un enlace con candado HTTPS válido. En términos de TLS, ¿qué puedes concluir?","options":["Es legítimo: el candado lo garantiza","Solo que la conexión con ESE dominio es cifrada y el dominio es quien dice ser — nada sobre su honestidad: el phishing con HTTPS existe","Que el banco pagó su certificado","Que el correo pasó un antivirus"],"correctIndex":1,"feedback":{"correct":"Correcto. El candado autentica el nombre y cifra el canal; las intenciones no son asunto suyo.","incorrect":"El candado promete privacidad e identidad del DOMINIO — un dominio fraudulento puede tener certificado válido. La honestidad se verifica por otro canal."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"El orden del viaje de una petición HTTPS es DNS → TCP → TLS → HTTP porque:","options":["Es alfabético al revés","Cada etapa DEPENDE de la anterior: sin IP no hay conexión, sin conexión no se negocia el cifrado, y sin cifrado no se conversa","El DNS es el más antiguo","TLS exige ir tercero por estándar"],"correctIndex":1,"feedback":{"correct":"Correcto. Una cadena de dependencias — y por eso el diagnóstico la recorre en el mismo orden.","incorrect":"Es dependencia pura: la IP habilita la conexión, la conexión habilita el candado, el candado habilita la conversación privada."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"El técnico administra el servidor de una clínica desde su casa escribiendo comandos. El protocolo correcto y por qué su antecesor quedó prohibido:","options":["Telnet, porque es más simple","SSH (puerto 22): terminal remota cifrada — Telnet hacía lo mismo en texto plano, con las contraseñas legibles para el camino","HTTP, porque es la web","IMAP, porque sincroniza"],"correctIndex":1,"feedback":{"correct":"Correcto. SSH cifra la sesión completa; Telnet regalaba las credenciales a cualquier intermediario.","incorrect":"SSH es la terminal remota cifrada del oficio. Telnet — su antecesor en texto plano — es hoy negligencia."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'un usuario dice que el candado del navegador significa que el sitio es seguro y puede confiar en él — ¿qué le corriges?' Tu respuesta senior:","options":["Nada: el candado garantiza confianza total","Que el candado promete DOS cosas — conexión cifrada e identidad del dominio — y ninguna de ellas es honestidad: un sitio fraudulento puede lucir HTTPS válido; la legitimidad se juzga por el dominio real y verificando por otro canal","Que el candado es decorativo","Que solo los bancos tienen candado de verdad"],"correctIndex":1,"feedback":{"correct":"Impecable. Cifrado + identidad ≠ honestidad: la distinción que desarma medio phishing. La ruta de seguridad construye sobre exactamente esta idea.","incorrect":"La respuesta senior separa las promesas: TLS cifra y autentica el NOMBRE del dominio — las intenciones del sitio no están en el contrato. HTTPS fraudulento existe."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm04-x01-examen';
