-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 024 — Redes y Sistemas · Módulo 5: Sistemas
-- ═══════════════════════════════════════════════════════════════════
-- 6 lecciones + examen de región (43 bloques).
-- AJUSTE DE KAREN (obligatorio): la lección de logs establece la
-- estructura TIMESTAMP + ORIGEN + EVENTO ("la tríada del registro")
-- como concepto con nombre propio, reutilizable para DFIR.
-- Labs con contrato {title, code (Win/Linux), caption, result?}:
-- procesos (Task Manager/ps), puertos (netstat/ss) y logs
-- (visor de eventos/journalctl).
-- Reglas de contenido: sin tecnología interna de la plataforma;
-- quizzes autocontenidos o con términos técnicos.
-- OJO: Redes está PUBLICADO — correr esta migración hace el M5
-- visible a los usuarios AL INSTANTE.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 006.
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'redes-y-sistemas' and m.slug = 'm05-sistemas'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m05-l01-procesos',        'Procesos y servicios',                 'leccion', 20, 1),
       ('m05-l02-puertos-abiertos','Puertos abiertos: puertas de entrada', 'leccion', 20, 2),
       ('m05-l03-permisos-linux',  'Usuarios y permisos en Linux',         'leccion', 20, 3),
       ('m05-l04-permisos-windows','Usuarios y permisos en Windows',       'leccion', 20, 4),
       ('m05-l05-logs',            'Logs: la caja negra del sistema',      'leccion', 20, 5),
       ('m05-l06-lab-radiografia', 'Lab: la radiografía de tu equipo',     'leccion', 20, 6),
       ('m05-x01-examen',          'Examen: Sistemas',                     'examen',  40, 7)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'redes-y-sistemas' and m.slug = 'm05-sistemas';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Procesos y servicios
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Lo que corre detrás de la pantalla","body":"Hasta ahora miramos la red; este módulo mira DENTRO de las máquinas conectadas a ella. Primer concepto: un PROCESO es un programa EN EJECUCIÓN — el archivo del programa es la receta; el proceso, el plato cocinándose. Cada proceso recibe un PID (identificador numérico único), pertenece a un usuario y consume recursos (CPU, memoria). En tu equipo hay decenas corriendo ahora mismo: el navegador (varios, de hecho), el antivirus, y una multitud que jamás has visto. Esos invisibles tienen nombre propio: SERVICIOS (o daemons, en el mundo Linux) — procesos SIN ventana que arrancan solos y viven de fondo esperando trabajo. ¿Te suena? El 'servidor que vive escuchando' del módulo 1 ES un servicio: el sistema de citas de la clínica es un proceso de fondo en su servidor, despierto a las 3 de la mañana por si alguien lo llama."}$j$),
  (2, 'texto', $j${"title":"Para qué mirarlos: diagnóstico y sospecha","body":"Ver la lista de procesos (Task Manager en Windows, el comando ps en Linux — los usarás en el lab) responde dos preguntas del oficio. La de RENDIMIENTO: ¿qué se está comiendo la CPU o la memoria cuando el equipo 'va lento'? La lista, ordenada por consumo, delata al glotón en segundos. Y la de SEGURIDAD: ¿reconozco todo lo que corre? Un proceso con nombre extraño, que corre como un usuario que no debería, o que nadie recuerda haber instalado, es una bandera roja — buena parte del software malicioso vive precisamente así: como un proceso más, camuflado entre los legítimos, esperando que nadie mire la lista. Inventariar lo que corre es el primer paso de toda auditoría."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿cuál es la diferencia entre un programa y un proceso?","options":["Ninguna, son sinónimos","El programa es el archivo (la receta); el proceso es ese programa EN EJECUCIÓN (el plato cocinándose), con su PID, su usuario y su consumo","El proceso es más pequeño","El programa corre y el proceso se guarda"],"correctIndex":1,"feedback":{"correct":"Correcto. Un mismo programa puede generar varios procesos a la vez — tu navegador lo hace ahora mismo.","incorrect":"Programa = archivo en disco; proceso = ese programa corriendo, con identificador (PID), dueño y recursos asignados."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"El sistema de citas de una clínica corre en el servidor sin ventana ni pantalla, arrancó solo al encender la máquina y responde peticiones a cualquier hora. Ese tipo de proceso se llama:","options":["Un virus","Un SERVICIO (daemon): proceso de fondo que vive esperando trabajo — el 'servidor que escucha' del que hablan las redes","Un archivo temporal","Un navegador"],"correctIndex":1,"feedback":{"correct":"Correcto. Los servicios son la mitad invisible del sistema — y donde viven los servidores de verdad.","incorrect":"Es un servicio o daemon: proceso sin ventana, de arranque automático, que espera peticiones de fondo."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Procesos y servicios","points":["Proceso = programa EN EJECUCIÓN: PID único, usuario dueño, consumo de CPU/memoria.","Servicio (daemon) = proceso de fondo sin ventana que espera trabajo — el 'servidor que escucha' del módulo 1.","La lista de procesos responde rendimiento (¿quién come CPU?) y seguridad (¿reconozco todo?).","El software malicioso suele vivir como un proceso más, camuflado: inventariar lo que corre es auditar.","Las herramientas (Task Manager, ps) te esperan en el lab de este módulo."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm05-l01-procesos';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Puertos abiertos: puertas de entrada
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Puerto abierto = proceso escuchando","body":"Hora de unir los dos últimos módulos en una sola idea: un PUERTO ABIERTO es un PROCESO que escucha en esa puerta. El puerto 443 de la clínica está 'abierto' porque el proceso del servidor web lo reclamó y espera conexiones ahí; el 22, porque el servicio de SSH hace lo propio. No hay puertas abiertas por sí solas: detrás de cada una hay SIEMPRE un proceso concreto, con su PID y su dueño — y el comando netstat (lab de este módulo) te muestra exactamente esa pareja: qué puertos están en escucha y qué proceso abrió cada uno. Cuando el módulo pasado decía 'el servidor escucha en el 443', ahora sabes la mecánica completa: un servicio reclamó esa puerta al sistema."}$j$),
  (2, 'texto', $j${"title":"Cada puerta abierta es superficie de ataque","body":"Ahora la lectura de seguridad: cada puerto abierto es una PUERTA DE ENTRADA a la máquina — un lugar donde alguien de fuera puede tocar y obtener respuesta. Al conjunto de puertas expuestas se le llama SUPERFICIE DE ATAQUE, y la regla profesional es de sentido común: tan pequeña como sea posible — solo deben estar abiertos los puertos de los servicios que la máquina NECESITA ofrecer. El servidor de la clínica necesita su 443 (la web de citas) y su 22 (la administración del técnico); si una auditoría encuentra además el 23 abierto (Telnet — el fantasma en texto plano del módulo anterior), eso es una alarma: o alguien configuró mal, o algo se instaló sin permiso. Auditar puertos es inventariar puertas — y cerrar las que sobran es la mejora de seguridad más barata que existe."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué significa que un puerto esté 'abierto' en una máquina?","options":["Que el cable está conectado","Que hay un PROCESO escuchando en esa puerta, esperando conexiones — detrás de cada puerto abierto hay siempre un servicio concreto","Que el firewall se apagó","Que la máquina es pública"],"correctIndex":1,"feedback":{"correct":"Correcto. Puerto abierto = proceso escuchando: la pareja que netstat te muestra completa.","incorrect":"Un puerto no se abre solo: lo abre un proceso que lo reclama para escuchar. Puerto abierto = servicio esperando ahí."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Una auditoría del servidor de una clínica encuentra abiertos los puertos 443 (web de citas), 22 (SSH del técnico) y 23 (Telnet, que nadie usa). En términos de superficie de ataque, ¿qué corresponde hacer?","options":["Nada: más puertos abiertos es más flexibilidad","Cerrar el 23: cada puerta abierta es superficie de ataque, y solo deben quedar las de los servicios que la máquina NECESITA","Cerrar el 443, por si acaso","Abrir más puertos de respaldo"],"correctIndex":1,"feedback":{"correct":"Correcto. El 443 y el 22 trabajan; el 23 solo expone (y en texto plano). Cerrar lo que sobra: la mejora más barata.","incorrect":"La regla: superficie mínima. Los puertos con oficio (443, 22) se quedan; el 23 sin uso — y Telnet, además — se cierra ya."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Puertos abiertos","points":["Puerto abierto = un proceso escuchando en esa puerta: siempre hay un servicio detrás.","netstat muestra la pareja completa: puerto en escucha + proceso que lo abrió.","Cada puerta expuesta es SUPERFICIE DE ATAQUE: la regla es mantenerla mínima.","Solo abiertos los puertos que la máquina NECESITA ofrecer; lo demás se cierra.","Un puerto abierto que nadie reconoce (el 23 fantasma) es una alarma de auditoría."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm05-l02-puertos-abiertos';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Usuarios y permisos en Linux
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cada cosa corre COMO alguien","body":"Los sistemas serios son multiusuario, y la pieza clave es esta: todo proceso corre COMO un usuario, y solo puede hacer lo que SU usuario tiene permitido. En Linux hay un usuario que lo puede todo: root, el superusuario — y del otro lado, los usuarios normales con poderes acotados. De ahí nace el principio más citado de la seguridad: MÍNIMO PRIVILEGIO — cada quien (persona o servicio) con los permisos justos para su trabajo, ni uno más. El servidor web de la clínica no corre como root: corre como un usuario de servicio sin poderes, de modo que si alguien logra engañarlo, hereda un usuario enclenque y no las llaves del reino. Trabajar el día a día como root es el pecado capital de Linux."}$j$),
  (2, 'texto', $j${"title":"Leer permisos y pedir poder prestado","body":"Los archivos en Linux declaran sus permisos en tres letras — r (leer), w (escribir), x (ejecutar) — repetidas para tres públicos: el DUEÑO, su GRUPO y OTROS (todos los demás). El comando ls -l los muestra: rw-r--r-- se lee 'el dueño lee y escribe; el grupo solo lee; otros solo leen'. El expediente de un paciente con esos permisos puede ser LEÍDO por cualquiera con acceso a la máquina — quizá no es lo que la clínica quiere. Para tareas administrativas puntuales existe sudo: ejecutar UN comando con los poderes de root, autenticándote — y dejando REGISTRO de quién lo hizo y cuándo (recuerda ese detalle: reaparece en dos lecciones). Poder prestado, auditado y por comando: esa es la forma correcta de administrar."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de seguridad de sistemas, ¿qué enuncia el principio de MÍNIMO PRIVILEGIO?","options":["Que solo root debe usar la máquina","Que cada usuario o servicio debe tener los permisos JUSTOS para su trabajo, ni uno más — si algo se compromete, el daño queda acotado","Que los permisos se revisan una vez al año","Que nadie debe tener contraseña"],"correctIndex":1,"feedback":{"correct":"Correcto. Poderes justos: si engañan al servidor web, heredan un usuario enclenque, no las llaves del reino.","incorrect":"Mínimo privilegio = permisos exactos para el trabajo, nada extra. Es la razón por la que los servicios NO corren como root."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un archivo en Linux muestra permisos rw-r--r--. ¿Qué puede hacer con él la categoría OTROS (cualquier usuario de la máquina)?","options":["Leerlo y escribirlo","Solo LEERLO: el último bloque (r--) es el de otros — dueño rw-, grupo r--, otros r--","Nada","Ejecutarlo"],"correctIndex":1,"feedback":{"correct":"Correcto. Tres bloques para tres públicos: dueño / grupo / otros. Ese último r-- deja el archivo legible para todos.","incorrect":"Se lee por bloques: rw- (dueño) · r-- (grupo) · r-- (otros). Otros solo puede leer — que ya puede ser demasiado para un expediente."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Permisos en Linux","points":["Todo proceso corre COMO un usuario y hereda sus límites.","root lo puede todo; el día a día NUNCA se trabaja como root.","MÍNIMO PRIVILEGIO: permisos justos para el trabajo — el principio más citado de la seguridad.","Permisos rwx por tres públicos: dueño / grupo / otros. ls -l los muestra; rw-r--r-- = otros pueden leer.","sudo presta el poder de root por UN comando, autenticado y CON REGISTRO — ese registro reaparece pronto."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm05-l03-permisos-linux';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Usuarios y permisos en Windows
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El mismo mapa con otros nombres","body":"Windows juega el mismo juego con otros nombres, y traducir entre ambos mundos es habilidad de oficio. El equivalente de root es la cuenta ADMINISTRADOR (y el grupo Administradores); los usuarios ESTÁNDAR son los acotados. El equivalente de sudo es el UAC (Control de Cuentas de Usuario): esa ventana que oscurece la pantalla y pregunta '¿Quieres permitir que esta aplicación haga cambios?' — es Windows pidiéndote confirmación antes de prestar el poder administrativo, exactamente el 'poder prestado por operación' de la lección anterior. Y los permisos de archivo viven en las propiedades de cada carpeta (pestaña Seguridad): quién lee, quién escribe, quién ejecuta — el rwx de Linux con interfaz gráfica y más granularidad."}$j$),
  (2, 'texto', $j${"title":"La regla práctica: cuenta estándar para vivir","body":"La aplicación del mínimo privilegio en Windows cabe en una regla: el día a día se vive en una cuenta ESTÁNDAR, y la de administrador se usa solo cuando algo lo exige (y el UAC lo pedirá). ¿Por qué importa tanto? Porque todo programa que ejecutas — incluido el adjunto malicioso que alguien abrió sin querer — corre CON TUS PERMISOS: si eres administrador, el malware es administrador; si eres estándar, el malware nace enclenque y el UAC se interpone antes de cualquier cambio profundo. En la clínica: las recepcionistas y los médicos usan cuentas estándar; solo el técnico tiene la administrativa, y solo la usa cuando administra. Una decisión de configuración que desactiva la mitad del malware del mundo: gratis."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Traduce entre mundos: los equivalentes en Windows de root y de sudo son…","options":["Invitado y el antivirus","La cuenta ADMINISTRADOR y el UAC (la ventana de '¿permitir cambios?'): el mismo poder total y el mismo préstamo confirmado por operación","El Task Manager y el navegador","No existen equivalentes"],"correctIndex":1,"feedback":{"correct":"Correcto. Mismo mapa, otros nombres: Administrador = root; UAC = el préstamo de poder con confirmación.","incorrect":"Administrador equivale a root (poder total) y el UAC a sudo: pedir confirmación antes de prestar poderes administrativos."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué la recomendación profesional es usar una cuenta ESTÁNDAR para el día a día y no una de administrador?","options":["Porque las cuentas estándar son más rápidas","Porque todo programa que ejecutes — incluido un malware — corre CON TUS PERMISOS: en cuenta estándar, el malware nace sin poder y el UAC se interpone antes de cambios profundos","Porque el administrador gasta más licencias","Por estética del escritorio"],"correctIndex":1,"feedback":{"correct":"Correcto. Mínimo privilegio aplicado: el malware hereda tus límites. Estándar para vivir, administrador solo para administrar.","incorrect":"Los programas heredan los permisos de quien los ejecuta: con cuenta estándar, lo malicioso nace acotado y el UAC frena la escalada."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Permisos en Windows","points":["El mapa traducido: Administrador = root · usuarios estándar = acotados · UAC = sudo (poder prestado con confirmación).","Los permisos de archivos viven en Propiedades → Seguridad: quién lee, escribe, ejecuta.","Regla de oro: cuenta ESTÁNDAR para el día a día; la administrativa solo cuando algo lo exige.","Todo lo que ejecutas corre con TUS permisos — el malware incluido: acótate y lo acotas.","En la clínica: recepción y médicos en estándar; el técnico administra, y solo cuando administra."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm05-l04-permisos-windows';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Logs: la caja negra del sistema (AJUSTE: la tríada del registro)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El sistema lo anota todo","body":"Mientras usas una máquina, ella escribe su diario: cada inicio de sesión (y cada intento fallido), cada servicio que arranca o se cae, cada sudo ejecutado (el registro prometido hace dos lecciones), cada error. Esos diarios son los LOGS — la caja negra del sistema, como la de los aviones: nadie la mira mientras todo va bien, y lo cuenta TODO cuando algo salió mal. Dónde viven: en Windows, el Visor de Eventos los organiza por categorías; en Linux, son archivos en /var/log más el comando journalctl para consultarlos. Cada servicio serio escribe además el suyo: el servidor web anota cada petición, la base de datos cada conexión. En el lab de este módulo abrirás los de tu propia máquina."}$j$),
  (2, 'texto', $j${"title":"La tríada del registro: timestamp + origen + evento","body":"Aquí viene un concepto que te acompañará toda la ruta, así que dale nombre propio: LA TRÍADA DEL REGISTRO. Toda línea de log del mundo — del sistema, del router, del servidor web, de la base de datos — responde tres preguntas: CUÁNDO (el TIMESTAMP: fecha y hora exactas, al segundo o mejor), QUIÉN/DESDE DÓNDE (el ORIGEN: qué servicio la escribió, qué usuario actuó, desde qué IP) y QUÉ PASÓ (el EVENTO: la acción y su resultado). Míralo en una línea real: '2026-07-13 03:12:44 · sshd · Failed password for admin from 203.0.113.7' — cuándo (3:12 de la madrugada), origen (el servicio SSH; la IP 203.0.113.7), evento (intento de login fallido como admin). Una línea, historia completa."}$j$),
  (3, 'texto', $j${"title":"Por qué la tríada lo es todo: reconstruir historias","body":"La tríada no es una curiosidad de formato: es LA herramienta para reconstruir lo que pasó. El TIMESTAMP permite ORDENAR eventos en una línea de tiempo — incluso entre máquinas distintas: el log del router, el del servidor y el de la base de datos, entrelazados por sus horas, cuentan una sola historia. El ORIGEN permite CORRELACIONAR: ¿esta IP que falló veinte contraseñas en el SSH es la misma que después apareció logueada en la base de datos? Y el EVENTO dice qué se intentó y qué se logró. Ese trabajo — ordenar por tiempo, correlacionar por origen, leer los eventos — tiene nombre profesional: es el corazón del ANÁLISIS FORENSE DIGITAL (DFIR), y hay un curso entero de eso más adelante en tu ruta. Cuando llegues, la tríada ya será tu vieja amiga. Una condición práctica para que funcione: los relojes de las máquinas deben estar sincronizados — un timestamp mentiroso rompe la línea de tiempo."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuáles son las tres preguntas que responde toda línea de log — la tríada del registro?","options":["Marca, modelo y versión","CUÁNDO (timestamp) + QUIÉN/DESDE DÓNDE (origen) + QUÉ PASÓ (evento)","Usuario, contraseña y correo","IP, máscara y gateway"],"correctIndex":1,"feedback":{"correct":"Correcto. Timestamp + origen + evento: la anatomía universal de todo registro — del router a la base de datos.","incorrect":"La tríada: cuándo (timestamp exacto), quién/desde dónde (servicio, usuario, IP) y qué pasó (la acción y su resultado)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Lees en un log: '2026-07-13 03:12:44 · sshd · Failed password for admin from 203.0.113.7'. Según la tríada, ¿cuál es el ORIGEN de este evento?","options":["Las 03:12:44","El servicio sshd y la IP 203.0.113.7: quién lo escribió y desde dónde vino la acción","El password","El día 13"],"correctIndex":1,"feedback":{"correct":"Correcto. Origen = quién/desde dónde: el servicio que anotó (sshd) y la IP actuante. El cuándo es el timestamp; el qué, el login fallido.","incorrect":"El origen responde quién/desde dónde: el servicio sshd y la IP 203.0.113.7. La hora es el timestamp; el intento fallido, el evento."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En un análisis forense, los logs del router, del servidor y de la base de datos se entrelazan en UNA línea de tiempo. ¿Qué componente de la tríada lo hace posible, y cuál es su condición práctica?","options":["El evento, si está en mayúsculas","El TIMESTAMP — ordena eventos de máquinas distintas en una sola historia — a condición de que los relojes estén sincronizados","El origen, si es la misma IP","Ninguno: los logs no se pueden combinar"],"correctIndex":1,"feedback":{"correct":"Correcto. El tiempo es el hilo que cose los diarios de varias máquinas — y un reloj desincronizado rompe la costura.","incorrect":"El timestamp ordena los eventos de todas las máquinas en una línea de tiempo común — por eso los relojes sincronizados son sagrados."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Logs","points":["Los logs son la caja negra: el sistema anota logins, fallos, servicios, cada sudo, cada error.","Dónde viven: Visor de Eventos (Windows) · /var/log y journalctl (Linux) · y cada servicio escribe el suyo.","LA TRÍADA DEL REGISTRO: timestamp (cuándo) + origen (quién/desde dónde) + evento (qué pasó). Apréndetela con nombre.","El timestamp ordena la línea de tiempo (relojes sincronizados: sagrado); el origen correlaciona; el evento cuenta.","Ordenar + correlacionar + leer = el corazón del análisis forense (DFIR): la tríada te espera en esa ruta."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm05-l05-logs';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Lab: la radiografía de tu equipo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Tres radiografías de tu propia máquina","body":"Todo lo del módulo se puede ver AHORA MISMO en tu equipo, con herramientas que ya trae. Vas a tomar tres radiografías: la de PROCESOS (qué corre), la de PUERTOS (qué escucha) y la de LOGS (qué quedó anotado) — el mismo inventario con el que empieza cualquier auditoría profesional. Abre tu terminal (la de los labs anteriores) y ve bloque por bloque. En cada salida, tu misión es la misma: reconocer lo aprendido — PIDs y servicios, la pareja puerto-proceso, y la tríada del registro en líneas reales."}$j$),
  (2, 'laboratorio', $j${"title":"Radiografía 1: qué corre (procesos)","code":"# Windows — el panel visual:\n#   Ctrl+Shift+Esc abre el Task Manager → pestaña Procesos\n# y en terminal:\ntasklist | more\n\n# Linux / Mac:\nps aux | head -15","caption":"Busca tres cosas: procesos que reconoces (tu navegador), la columna de USUARIO (¿quién corre cada cosa? — nota cuántos corren como el sistema y no como tú) y el consumo de CPU/memoria. ¿Hay algo que no reconozcas? Búscalo por nombre antes de sospechar: la mayoría de los desconocidos son piezas legítimas del sistema.","result":{"columns":["USER","PID","%CPU","COMMAND"],"rows":[["root","1","0.0","systemd"],["root","812","0.1","sshd"],["www-data","1044","0.3","nginx: worker"],["karen","2301","4.2","firefox"]],"note":"Cuatro filas que cuentan el módulo: el sistema (root), un servicio escuchando (sshd), un servidor web corriendo como usuario acotado (www-data — ¡mínimo privilegio aplicado!) y tu navegador corriendo como tú."}}$j$),
  (3, 'laboratorio', $j${"title":"Radiografía 2: qué escucha (puertos abiertos)","code":"# Windows:\nnetstat -ano | findstr LISTENING\n\n# Linux:\nss -tlnp\n# (o el clásico: netstat -tlnp)","caption":"Cada línea LISTENING/LISTEN es una puerta abierta: un proceso escuchando. Fíjate en la pareja puerto ↔ PID/proceso, y pregunta como auditor: ¿reconozco el servicio detrás de cada puerta? Los puertos del oficio (módulo 4) te ayudarán a leer: 443, 22, 53…","result":{"columns":["PROTO","LOCAL","ESTADO","PROCESO"],"rows":[["TCP","0.0.0.0:22","LISTEN","sshd (812)"],["TCP","0.0.0.0:443","LISTEN","nginx (1044)"],["TCP","127.0.0.1:5432","LISTEN","postgres (933)"]],"note":"Tres puertas: SSH (22) y web (443) abiertas al mundo (0.0.0.0), y una base de datos (5432) que SOLO escucha en 127.0.0.1 — la propia máquina: superficie de ataque bien pensada."}}$j$),
  (4, 'laboratorio', $j${"title":"Radiografía 3: qué quedó anotado (logs)","code":"# Windows — el panel visual:\n#   Win+R → eventvwr → Registros de Windows → Sistema\n\n# Linux — las últimas 20 líneas del diario del sistema:\njournalctl -n 20\n\n# y los intentos de autenticación:\njournalctl -u ssh -n 10","caption":"Elige CUALQUIER línea de la salida y descomponla en la tríada: ¿cuál es su timestamp? ¿qué servicio o usuario es el origen? ¿qué evento anota? Hazlo con tres líneas distintas — ese gesto de lectura es exactamente el que usarás en análisis forense.","result":{"columns":["SALIDA (ejemplo)"],"rows":[["jul 13 08:02:11 servidor sshd[812]: Accepted publickey for tecnico from 192.168.1.40"],["jul 13 08:15:03 servidor sudo[2410]: tecnico : COMMAND=/usr/bin/systemctl restart nginx"],["jul 13 08:15:04 servidor systemd[1]: Stopped nginx."]],"note":"Tres líneas, una mini-historia reconstruible por la tríada: el técnico entró por SSH con su llave (8:02), usó sudo para reiniciar el servidor web (8:15:03 — el registro de sudo prometido) y el sistema anotó la parada (8:15:04)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En la salida de un comando de puertos (netstat/ss), una línea marca 127.0.0.1:5432 LISTEN mientras otras marcan 0.0.0.0:443. ¿Qué diferencia expresa esa primera columna?","options":["El 5432 es más rápido","La dirección donde se escucha: 127.0.0.1 = solo la PROPIA máquina puede conectarse; 0.0.0.0 = abierto a la red — menos exposición para la base de datos","El 5432 está cerrado","Es un error de la herramienta"],"correctIndex":1,"feedback":{"correct":"Correcto. Escuchar solo en 127.0.0.1 saca ese servicio de la superficie de ataque de la red: nadie externo puede ni tocarlo.","incorrect":"127.0.0.1 significa 'solo yo': la base de datos escucha, pero únicamente para procesos de la misma máquina. 0.0.0.0 expone a toda la red."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — La radiografía","points":["Tres radiografías = el inventario de toda auditoría: procesos (qué corre), puertos (qué escucha), logs (qué quedó anotado).","Task Manager/tasklist y ps aux: la lista de procesos con usuario y consumo.","netstat/ss: la pareja puerto ↔ proceso; 127.0.0.1 escucha solo local, 0.0.0.0 expone a la red.","Visor de Eventos y journalctl: los diarios — y cada línea se descompone en la tríada.","Leíste una mini-historia real en tres líneas de log: eso, a escala, es el análisis forense."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm05-l06-lab-radiografia';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La quinta región","body":"Byte llegó a la región de los sistemas: diez preguntas guardan el paso. Todo lo viviste: los procesos y sus servicios, las puertas abiertas, los permisos en los dos mundos, la caja negra con su tríada y la radiografía de tu propia máquina. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Un programa instalado y un proceso se diferencian en que:","options":["Son exactamente lo mismo","El programa es el archivo en disco; el proceso es ese programa EN EJECUCIÓN, con PID, usuario dueño y consumo de recursos","El proceso es la versión de pago","El programa corre más rápido"],"correctIndex":1,"feedback":{"correct":"Correcto. Receta vs plato cocinándose — y un programa puede generar varios procesos a la vez.","incorrect":"Archivo (programa) vs ejecución (proceso): el proceso vive, tiene PID, dueño y consumo."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Un proceso sin ventana, que arrancó solo con el sistema y vive de fondo esperando peticiones, se llama:","options":["Ventana minimizada","SERVICIO (o daemon): la forma en que viven los servidores — el 'proceso que escucha'","Archivo oculto","Acceso directo"],"correctIndex":1,"feedback":{"correct":"Correcto. La mitad invisible del sistema: servicios esperando trabajo.","incorrect":"Es un servicio/daemon: proceso de fondo, sin interfaz, esperando peticiones — así vive un servidor."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"'El puerto 443 está abierto en el servidor.' La mecánica exacta detrás de esa frase es:","options":["El cable de red está conectado","Un PROCESO (el servidor web) reclamó esa puerta y ESCUCHA en ella: detrás de todo puerto abierto hay un servicio concreto con su PID","El firewall lo pintó de verde","La máquina tiene internet"],"correctIndex":1,"feedback":{"correct":"Correcto. Puerto abierto = proceso escuchando: la pareja que netstat/ss muestran completa.","incorrect":"Los puertos no se abren solos: un proceso los reclama para escuchar. Puerto abierto = servicio esperando ahí."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"El conjunto de puertas expuestas de una máquina se llama superficie de ataque, y la regla profesional dice que debe ser:","options":["Lo más grande posible, por flexibilidad","MÍNIMA: solo los puertos de los servicios que la máquina NECESITA ofrecer — cerrar los demás es la mejora de seguridad más barata","Igual en todas las máquinas","Secreta pero abierta"],"correctIndex":1,"feedback":{"correct":"Correcto. Cada puerta de más es riesgo gratuito: se cierra lo que no trabaja.","incorrect":"Superficie mínima: cada puerto abierto sin oficio es una puerta de entrada regalada."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"El servidor web de una clínica corre como el usuario acotado www-data y no como root. El principio de seguridad aplicado es:","options":["Ahorro de memoria","MÍNIMO PRIVILEGIO: si alguien engaña al servicio, hereda un usuario sin poderes — no las llaves del reino","Compatibilidad con Windows","Balanceo de carga"],"correctIndex":1,"feedback":{"correct":"Correcto. Poderes justos para el trabajo: el daño de un compromiso queda acotado de fábrica.","incorrect":"Es mínimo privilegio: el servicio tiene solo los permisos de su oficio, y quien lo comprometa hereda esa jaula."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Permisos rw-r----- en un expediente de Linux. ¿Quién puede LEERLO?","options":["Todos los usuarios de la máquina","El DUEÑO (que además escribe) y su GRUPO — otros no tienen ningún permiso (---)","Solo root","Nadie"],"correctIndex":1,"feedback":{"correct":"Correcto. rw- (dueño) · r-- (grupo) · --- (otros): el público general quedó fuera — mejor para un expediente.","incorrect":"Por bloques: dueño rw-, grupo r--, otros ---. Dueño y grupo leen; el resto de la máquina, nada."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"La ventana de Windows que oscurece la pantalla y pregunta '¿Quieres permitir que esta aplicación haga cambios?' es, en términos del modelo de permisos:","options":["Publicidad del sistema","El UAC — el equivalente de sudo: la confirmación antes de prestar el poder administrativo para UNA operación","Un error de Windows","El antivirus"],"correctIndex":1,"feedback":{"correct":"Correcto. Poder prestado, confirmado por operación: el mismo patrón de sudo con interfaz gráfica.","incorrect":"Es el UAC: Windows pidiendo confirmación antes de elevar permisos — el sudo del otro mundo."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"Un empleado abre un adjunto malicioso. ¿Por qué el daño es MUY distinto según use una cuenta estándar o una de administrador?","options":["No hay diferencia","Porque todo programa corre CON LOS PERMISOS de quien lo ejecuta: en cuenta estándar el malware nace acotado; en administrador, nace con las llaves","Porque las cuentas estándar no abren adjuntos","Porque el administrador tiene mejor antivirus"],"correctIndex":1,"feedback":{"correct":"Correcto. El malware hereda tus límites: la razón por la que el día a día se vive en cuenta estándar.","incorrect":"Los procesos heredan los permisos del usuario: malware ejecutado por un administrador ES administrador. Estándar para vivir."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"La tríada del registro — la anatomía de toda línea de log — es:","options":["Usuario + contraseña + correo","TIMESTAMP (cuándo) + ORIGEN (quién/desde dónde) + EVENTO (qué pasó)","IP + máscara + gateway","Programa + proceso + puerto"],"correctIndex":1,"feedback":{"correct":"Correcto. Cuándo, quién/desde dónde, qué: las tres preguntas que responde todo log del mundo.","incorrect":"La tríada: timestamp exacto + origen (servicio/usuario/IP) + evento (la acción y su resultado)."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'los logs ocupan espacio y nadie los lee — ¿para qué conservarlos?' Tu respuesta senior:","options":["Para llenar el disco","Porque son la caja negra: con su tríada (timestamp+origen+evento) se reconstruye cualquier incidente — ordenando por tiempo y correlacionando orígenes entre máquinas. Leerlos DESPUÉS de un problema es análisis forense; vigilarlos ANTES es detección","Solo por obligación legal","Tiene razón: se pueden borrar"],"correctIndex":1,"feedback":{"correct":"Impecable. La caja negra del avión tampoco 'se usa'… hasta el día que lo explica todo. La tríada es tu herramienta para ese día — y DFIR, su curso.","incorrect":"La respuesta senior: los logs reconstruyen historias (tríada: ordenar por timestamp, correlacionar por origen, leer eventos). Forense después, detección antes — sin ellos, un incidente es un misterio sin testigos."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm05-x01-examen';
