-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 026 — Redes y Sistemas · Módulo 7: Tráfico real y el puente
-- ═══════════════════════════════════════════════════════════════════
-- EL MÓDULO FINAL del curso: 5 lecciones + examen del curso completo.
-- Wireshark sobre tráfico PROPIO (labs de captura y lectura: el
-- encapsulamiento del M2 y el viaje HTTPS del M4, vistos en paquetes
-- reales), la NOTA ÉTICA CENTRAL del curso (captura solo en redes
-- propias o con autorización escrita), la caja de herramientas de
-- diagnóstico completa, y el puente a nube, DFIR y ciberseguridad.
-- El examen final cruza los 7 módulos; la entrevista de cierre es LA
-- clásica: '¿qué pasa cuando escribes una dirección y pulsas Enter?'.
-- Reglas de contenido: sin tecnología interna de la plataforma;
-- quizzes autocontenidos o con términos técnicos.
-- OJO: Redes está PUBLICADO — correr esta migración hace el M7
-- visible AL INSTANTE… y completa el curso.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 006.
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'redes-y-sistemas' and m.slug = 'm07-trafico-y-puente'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m07-l01-analizador',        'Wireshark: ver los paquetes',           'leccion', 20, 1),
       ('m07-l02-lab-captura',       'Lab: tu primera captura',               'leccion', 20, 2),
       ('m07-l03-leer-capturas',     'Leer capturas: el curso en vivo',       'leccion', 20, 3),
       ('m07-l04-caja-herramientas', 'La caja de herramientas',               'leccion', 20, 4),
       ('m07-l05-puente',            'El puente: adónde va cada camino',      'leccion', 20, 5),
       ('m07-x01-examen',            'Examen final: Redes y Sistemas',        'examen',  40, 6)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'redes-y-sistemas' and m.slug = 'm07-trafico-y-puente';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Wireshark: ver los paquetes (+ nota ética central)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La herramienta que hace visible el curso","body":"Durante seis módulos hablamos de tramas, paquetes, capas y protocolos como si se pudieran ver. Ahora se pueden. Un ANALIZADOR DE TRÁFICO captura los paquetes que entran y salen de tu equipo y te los muestra uno a uno, con todas sus capas abiertas. El estándar del oficio es WIRESHARK: gratuito, de código abierto, disponible para Windows, Linux y Mac (wireshark.org), y presente en el escritorio de todo administrador de redes, auditor de seguridad y analista forense del mundo. Con él verás EN VIVO el encapsulamiento del módulo 2, el viaje HTTPS del módulo 4 y el candado de TLS haciendo su trabajo. Es también una herramienta poderosa de verdad — y por eso, antes de abrirla, la regla del oficio va primero."}$j$),
  (2, 'nota_etica', $j${"title":"La regla central del curso: captura solo lo tuyo","body":"Esta es la nota ética más importante del curso, y la firma de tu ingreso al oficio. Un analizador de tráfico captura TODO lo que pasa por la red — conversaciones de otras personas incluidas, si la red es compartida. Por eso la regla es absoluta y sin matices: se captura tráfico ÚNICAMENTE en redes PROPIAS o con AUTORIZACIÓN ESCRITA del dueño. Capturar en redes ajenas — la empresa donde trabajas sin permiso del área responsable, el café, la universidad, el vecino — es DELITO en la mayoría de los países y una violación de la privacidad de personas concretas. Así trabajan los profesionales que admirarás en esta ruta: los auditores de seguridad capturan CON contrato firmado que define alcance y fechas; los analistas forenses, CON autorización formal de la investigación. La herramienta es la misma que usarás hoy; la diferencia entre el profesional y el intruso es el papel que lo autoriza. Todos los labs de este módulo son sobre TU propia red y TU propio tráfico."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué hace un analizador de tráfico como Wireshark?","options":["Acelera la conexión","CAPTURA los paquetes que pasan por una interfaz de red y los muestra con todas sus capas abiertas, uno a uno","Bloquea virus","Cambia la IP del equipo"],"correctIndex":1,"feedback":{"correct":"Correcto. El microscopio de las redes: cada paquete, con sus sobres abiertos capa por capa.","incorrect":"Un analizador captura y DISECCIONA el tráfico: cada trama con sus capas visibles — el encapsulamiento hecho herramienta."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un auditor de seguridad y un intruso pueden usar exactamente la misma herramienta de captura. ¿Qué separa legalmente a uno del otro?","options":["La versión del programa","La AUTORIZACIÓN: el auditor captura con contrato escrito que define alcance y fechas; sin autorización (o en red ajena), capturar es delito","La velocidad de la red","La marca de la laptop"],"correctIndex":1,"feedback":{"correct":"Correcto. La herramienta no distingue: el papel que autoriza, sí. Red propia o contrato — sin excepciones.","incorrect":"La frontera es la autorización escrita del dueño de la red: con ella es auditoría; sin ella, delito y violación de privacidad."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — El analizador","points":["Wireshark: el analizador de tráfico estándar del oficio — gratuito, multiplataforma, en wireshark.org.","Captura los paquetes de una interfaz y los muestra con las capas abiertas: el curso entero, visible.","⚖️ LA REGLA CENTRAL: capturar SOLO en redes propias o con autorización ESCRITA — sin matices.","Los profesionales capturan con contrato (auditores) o autorización formal (forenses): el papel hace la diferencia.","Todos los labs de este módulo: tu red, tu tráfico."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm07-l01-analizador';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Lab: tu primera captura
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Quince minutos para ver tu primer paquete","body":"Instala Wireshark desde wireshark.org (siguiente-siguiente sirve; en Windows acepta instalar Npcap, el componente que captura). El plan del lab: capturar un minuto de TU tráfico mientras visitas un sitio, detener, y filtrar para encontrar las piezas del curso. Dos ideas antes de empezar: la captura junta TODO (tu equipo habla más de lo que crees — actualizaciones, sincronizaciones, la nube), así que los FILTROS son tus ojos: escribes uno en la barra superior y la vista se queda solo con lo que pediste. Y segundo: captura poco tiempo — un minuto da miles de paquetes de sobra."}$j$),
  (2, 'laboratorio', $j${"title":"Captura un minuto de tu propio tráfico","code":"# 1) Abre Wireshark (Windows, Linux o Mac: misma interfaz)\n# 2) En la lista de interfaces, elige la activa: la que muestra\n#    una gráfica de actividad (tu Wi-Fi o tu Ethernet)\n# 3) Doble clic para empezar a capturar\n# 4) Sin cerrar Wireshark: abre el navegador y visita example.com\n# 5) Vuelve a Wireshark y pulsa el botón rojo (detener)\n\n# Ya tienes tu primera captura: miles de filas, una por paquete.","caption":"Cada fila es un paquete real que entró o salió de tu equipo: número, tiempo, origen, destino, protocolo y resumen. Los colores agrupan protocolos. No intentes leerlo todo — para eso son los filtros del siguiente bloque.","result":{"columns":["No.","SOURCE","DESTINATION","PROTOCOL","INFO"],"rows":[["102","192.168.1.25","192.168.1.1","DNS","Standard query A example.com"],["103","192.168.1.1","192.168.1.25","DNS","response A 93.184.215.14"],["104","192.168.1.25","93.184.215.14","TCP","SYN → 443"],["108","192.168.1.25","93.184.215.14","TLSv1.3","Client Hello"]],"note":"Cuatro filas de una captura real: la consulta DNS con su respuesta, el inicio del saludo TCP hacia el 443 y el arranque de TLS. ¿Reconoces el viaje del módulo 4? Sigue en la próxima lección."}}$j$),
  (3, 'laboratorio', $j${"title":"Filtros: tus ojos en la captura","code":"# Escribe en la barra de filtro (arriba) y pulsa Enter:\n\ndns\n#   → solo consultas y respuestas de nombres (módulo 3)\n\ntcp.port == 443\n#   → solo el tráfico web cifrado (módulo 4)\n\nip.addr == 192.168.1.1\n#   → solo lo que habla con tu gateway (¡usa TU IP del módulo 1!)\n\ndns || tls\n#   → combinados: la guía telefónica y el candado a la vez","caption":"La barra se pinta VERDE cuando el filtro es válido y ROJA cuando no. Prueba los cuatro; con cada uno, la captura gigante se convierte en una historia legible. Filtrar es el 80% del oficio de leer capturas.","result":{"columns":["FILTRO","QUÉ DEJA VER"],"rows":[["dns","Las preguntas '¿qué IP tiene…?' y sus respuestas"],["tcp.port == 443","Las conversaciones HTTPS completas"],["ip.addr == …","Todo lo que cruza con una máquina concreta"],["dns || tls","La unión de dos filtros: || es el 'or' de Wireshark"]],"note":"Los filtros usan los nombres técnicos del curso: protocolos, puertos, direcciones. Todo lo aprendido es ahora un comando de búsqueda."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Capturas un minuto de tráfico y obtienes miles de paquetes de decenas de conversaciones mezcladas. ¿Cuál es la herramienta para encontrar lo que buscas?","options":["Leer fila por fila con paciencia","Los FILTROS (dns, tcp.port == 443, ip.addr == …): reducen la vista a la historia que te interesa — filtrar es el 80% de leer capturas","Capturar de nuevo","Ordenar alfabéticamente"],"correctIndex":1,"feedback":{"correct":"Correcto. La captura junta todo; el filtro cuenta UNA historia. Sin filtros, la aguja se queda en el pajar.","incorrect":"Los filtros son los ojos del analista: dns, tcp.port == 443, ip.addr — la vista se queda solo con lo pedido."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Tu primera captura","points":["Wireshark desde wireshark.org (en Windows, con Npcap); se captura en la interfaz ACTIVA.","El flujo del lab: capturar → generar tráfico (visitar un sitio) → detener → filtrar.","Cada fila es un paquete real: tiempo, origen, destino, protocolo, resumen.","Filtros esenciales: dns · tcp.port == 443 · ip.addr == x.x.x.x · combinables con ||.","Capturas cortas + filtros precisos = el método. Tu equipo habla más de lo que crees."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm07-l02-lab-captura';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Leer capturas: el curso en vivo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El panel de detalle: los sobres, abiertos","body":"Haz clic en cualquier paquete de tu captura y mira el panel central: Wireshark te muestra el paquete DISECCIONADO en capas plegables — Frame, Ethernet, Internet Protocol, Transmission Control Protocol, y arriba lo que corresponda (TLS, DNS…). ¿Lo reconoces? Es EXACTAMENTE el encapsulamiento del módulo 2: la trama (con las direcciones MAC), que envuelve al paquete (con las IP), que envuelve al segmento (con los puertos), que envuelve los datos. Cada sobre del que hablamos en teoría es una sección desplegable en tu pantalla. Ábrelos uno a uno en un paquete real: las MAC de tu equipo y tu router en Ethernet, las IP de origen y destino en IP, los puertos en TCP. La teoría del curso, en material tangible."}$j$),
  (2, 'laboratorio', $j${"title":"Sigue el viaje HTTPS completo en tu captura","code":"# Con tu captura del lab anterior abierta:\n\n# 1) El paso DNS — filtra:\ndns\n#    Busca la pareja: 'Standard query A example.com'\n#    y su respuesta con la IP. (El viaje empieza aquí: módulo 3)\n\n# 2) El saludo TCP — filtra (usa la IP de la respuesta DNS):\nip.addr == 93.184.215.14 && tcp\n#    Busca los TRES primeros: [SYN] → [SYN, ACK] → [ACK]\n#    El 'saludo de tres pasos' del módulo 4, paquete por paquete.\n\n# 3) El candado — filtra:\ntls\n#    Busca 'Client Hello' y 'Server Hello': la negociación\n#    del cifrado y el certificado.\n\n# 4) La conversación — después del saludo TLS, verás filas\n#    'Application Data': ese ES el HTTP… y no se puede leer.","caption":"El paso 4 es la lección más importante del lab: haz clic en un paquete 'Application Data' y busca el contenido — solo verás bytes ilegibles. Ese es el candado de TLS funcionando: los intermediarios (y tu propio analizador) ven los sobres, no la carta. Los metadatos (a quién, cuándo, cuánto), en cambio, están todos a la vista.","result":{"columns":["PASO","EN LA CAPTURA","MÓDULO"],"rows":[["1 · DNS","query A + response con la IP","M3"],["2 · TCP","[SYN] → [SYN, ACK] → [ACK] al puerto 443","M4"],["3 · TLS","Client Hello / Server Hello / certificado","M4"],["4 · HTTP","'Application Data' — bytes CIFRADOS, ilegibles","M2/M4"]],"note":"El diagrama del módulo 4, verificado con tus propios paquetes. Y la promesa de TLS, comprobada: ni tu analizador puede leer la carta."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En el panel de detalle de un analizador, un paquete se muestra como secciones plegables: Frame → Ethernet → IP → TCP → TLS. ¿Qué concepto del modelo de capas estás viendo?","options":["Un error de la herramienta","El ENCAPSULAMIENTO: cada capa envolvió a la anterior — trama (MAC) → paquete (IP) → segmento (puertos) → datos — y el analizador abre los sobres","La tabla de rutas","El firewall del equipo"],"correctIndex":1,"feedback":{"correct":"Correcto. Los sobres dentro de sobres, ahora desplegables con el mouse: la teoría hecha pantalla.","incorrect":"Cada sección es un sobre del encapsulamiento: Ethernet trae las MAC, IP las direcciones, TCP los puertos — el módulo 2 en vivo."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En tu propia captura, los paquetes 'Application Data' de una conexión HTTPS muestran solo bytes ilegibles. ¿Qué significa?","options":["La captura falló","Que TLS funciona: el contenido viaja CIFRADO y ni tu propio analizador puede leerlo — se ven los metadatos (quién, cuándo, cuánto), no la carta","Que el sitio está caído","Que faltó un filtro"],"correctIndex":1,"feedback":{"correct":"Correcto. La promesa del candado, comprobada en material real: sobres visibles, carta ilegible.","incorrect":"Es el cifrado de TLS haciendo su trabajo: el analizador ve el tráfico (metadatos) pero no puede leer el contenido."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Leer capturas","points":["El panel de detalle es el encapsulamiento desplegable: Frame → Ethernet (MAC) → IP → TCP (puertos) → arriba.","El viaje HTTPS del módulo 4, verificable en tu captura: DNS → SYN/SYN-ACK/ACK → Client/Server Hello → Application Data.","'Application Data' ilegible = TLS cumpliendo: ni tu analizador lee la carta.","Los metadatos sí quedan a la vista: a quién, cuándo, cuánto — la lección del Wi-Fi, confirmada.","Leer capturas = filtrar + abrir sobres + reconocer protocolos: el oficio del analista."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm07-l03-leer-capturas';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · La caja de herramientas
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Siete módulos, una caja de herramientas","body":"Sin darte cuenta, armaste un kit de diagnóstico profesional. Inventario: ipconfig / ip addr te dice QUIÉN ERES (tu IP, tu máscara, tu gateway — módulo 1). ping prueba si HAY CAMINO hasta una dirección (módulo 1). nslookup interroga la GUÍA TELEFÓNICA (módulo 3). tracert / traceroute muestra el CAMINO salto a salto (módulo 3). netstat / ss lista las PUERTAS ABIERTAS y quién escucha (módulo 5). El Visor de Eventos / journalctl abre la CAJA NEGRA (módulo 5). Y Wireshark VE LOS PAQUETES mismos (este módulo). Con esas siete herramientas — todas gratuitas, casi todas ya instaladas — se diagnostica la inmensa mayoría de los problemas de red del mundo real."}$j$),
  (2, 'texto', $j${"title":"El método: diagnóstico por capas","body":"Las herramientas sin método son ruido. El método es el del curso entero: DIAGNOSTICAR POR CAPAS, de lo cercano a lo lejano. 'No tengo internet' se ataca en orden: (1) ¿quién soy? — ipconfig: ¿tengo IP y gateway? Si no, el problema es local (cable, Wi-Fi, DHCP). (2) ¿llego a mi propia puerta? — ping al gateway: si falla, el problema está en TU red. (3) ¿llego afuera? — ping a 8.8.8.8: si falla aquí pero el gateway respondía, el problema es la salida (proveedor). (4) ¿funcionan los nombres? — nslookup: si el ping por IP va pero los nombres no, es DNS. (5) ¿y el servicio? — si todo lo anterior pasa, el problema es del sitio o del servicio concreto (los códigos HTTP del módulo 4 hablan). Cinco preguntas en orden, cada una descartando un tramo: así diagnostica un profesional — y así responderás en cualquier entrevista técnica."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"'No tengo internet.' Según el diagnóstico por capas, ¿cuál es el ORDEN correcto de las primeras tres comprobaciones?","options":["Reiniciar todo tres veces","ipconfig (¿tengo IP y gateway?) → ping al gateway (¿mi red funciona?) → ping a 8.8.8.8 (¿hay salida?): de lo cercano a lo lejano, descartando tramos","nslookup → Wireshark → llamar al proveedor","ping a 8.8.8.8 → ipconfig → apagar el router"],"correctIndex":1,"feedback":{"correct":"Correcto. Cada paso descarta un tramo: local → tu red → la salida. El orden ES el método.","incorrect":"De adentro hacia afuera: primero quién soy (ipconfig), luego mi puerta (gateway), luego la calle (8.8.8.8). Cada paso acota."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"El ping a 8.8.8.8 responde perfecto, pero nslookup falla y ninguna página abre por su nombre. El tramo roto es:","options":["El cable de red","La resolución DNS: hay salida a internet (el ping lo prueba) pero la guía telefónica no contesta — el diagnóstico del módulo 3, ahora dentro del método completo","El gateway","El navegador"],"correctIndex":1,"feedback":{"correct":"Correcto. El clásico: conectividad viva, nombres muertos = DNS. Las herramientas se confirman entre sí.","incorrect":"IP responde y nombres no: el eslabón roto es DNS — nslookup lo confirma y el resto del kit lo descartó."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — La caja de herramientas","points":["El kit: ipconfig/ip addr (quién soy) · ping (¿hay camino?) · nslookup (nombres) · tracert (el camino) · netstat/ss (puertas) · logs (la caja negra) · Wireshark (los paquetes).","Todo gratuito, casi todo preinstalado: el oficio no exige comprar nada.","EL MÉTODO: diagnóstico por capas, de lo cercano a lo lejano — cada paso descarta un tramo.","La secuencia de oro: ipconfig → ping gateway → ping 8.8.8.8 → nslookup → el servicio.","Herramientas + método + la tríada de los logs = un técnico que no adivina: acota."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm07-l04-caja-herramientas';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · El puente: adónde va cada camino
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Este curso era la base de tres caminos","body":"Redes y Sistemas es el curso fundacional de tu catálogo por una razón concreta: TODO lo que sigue construye sobre él. LA NUBE es, literalmente, las redes de otros — alquilas subredes, configuras firewalls y segmentas zonas… en centros de datos ajenos: el idioma de la nube ES el de los módulos 3 y 6 (cuando llegues a ese curso, las 'VPC' que verás son tus subredes con otro nombre). El ANÁLISIS FORENSE (DFIR) reconstruye incidentes con exactamente dos materiales que ya dominas: los logs con su tríada (módulo 5) y las capturas de tráfico (este módulo) — ordenar por timestamp, correlacionar orígenes, leer eventos: ya lo hiciste. Y la CIBERSEGURIDAD DEFENSIVA endurece sistemas con las ideas que ya practicaste: superficie de ataque mínima, mínimo privilegio, segmentación, denegar por defecto, seguridad en capas. No aprendiste 'un curso de redes': aprendiste el idioma en que están escritos los tres caminos."}$j$),
  (2, 'texto', $j${"title":"Lo que llevas en la mochila","body":"El inventario final, módulo a módulo: (M1) qué es una red, clientes y servidores, las piezas físicas y tu primera terminal. (M2) el mapa de capas OSI/TCP-IP y el encapsulamiento — el idioma de la profesión. (M3) direcciones, subredes con su fórmula, NAT, DHCP, DNS y el camino salto a salto. (M4) puertos, TCP/UDP, el viaje HTTPS y las dos promesas del candado. (M5) procesos, puertas abiertas, mínimo privilegio y la tríada del registro. (M6) VLANs, routing, firewalls, la clínica segmentada, VPN y la seguridad del aire. (M7) los paquetes en vivo, la ética de la captura y el método de diagnóstico. Además de un examen superado por región… y una entrevista técnica respondida en cada una. La red de la clínica que diseñamos juntos queda contigo: es el plano mental que reconocerás en cada red seria que toques."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué se dice que 'la nube son las redes de otros'?","options":["Porque no usa redes","Porque en la nube alquilas y configuras EXACTAMENTE lo aprendido — subredes, firewalls, segmentación en zonas — sobre centros de datos ajenos: el idioma es el mismo","Porque la nube no tiene direcciones IP","Porque es inalámbrica"],"correctIndex":1,"feedback":{"correct":"Correcto. Las VPC y grupos de seguridad que verás en ese curso son tus subredes y firewalls con otro nombre.","incorrect":"La nube se configura con este curso: subredes, firewalls, zonas — infraestructura de red, alquilada en vez de comprada."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"El análisis forense digital (DFIR) reconstruye incidentes a partir de dos materiales que este curso ya te enseñó a leer. ¿Cuáles?","options":["Contratos y facturas","Los LOGS (con su tríada: timestamp + origen + evento) y las CAPTURAS de tráfico: ordenar por tiempo, correlacionar orígenes, leer eventos","Los manuales de usuario","Las contraseñas del equipo"],"correctIndex":1,"feedback":{"correct":"Correcto. La caja negra y el microscopio: el forense arma la historia con exactamente esos dos materiales.","incorrect":"DFIR vive de logs (la tríada del módulo 5) y capturas (este módulo): los dos testigos de todo incidente."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — El curso completo, en siete líneas","points":["M1: la red, clientes y servidores, las piezas físicas — y tu primera terminal.","M2: capas OSI/TCP-IP y encapsulamiento — el idioma del oficio.","M3: IP, subredes (2^(32−n)−2), NAT, DHCP, DNS — cómo se encuentran las máquinas.","M4: puertos, TCP/UDP, el viaje HTTPS y el candado con sus dos promesas.","M5: procesos, puertas abiertas, mínimo privilegio y la tríada del registro.","M6: VLANs, routing, firewalls y la clínica segmentada por zonas de confianza.","M7: los paquetes en vivo, la ética de la captura y el método de diagnóstico — el puente a nube, DFIR y ciberseguridad."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm07-l05-puente';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen final: el curso completo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La región final","body":"Byte llegó a la última región: el guardián del curso completo. Diez preguntas que cruzan los siete módulos — de tu primera LAN al paquete diseccionado. Las que falles volverán al final hasta que las domines. Es la última puerta del mundo de Redes. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Switch y router, en una línea cada uno:","options":["Ambos conectan redes distintas","El switch entrega DENTRO de una red (por MAC, capa 2); el router conecta REDES distintas (por IP, capa 3)","El switch es inalámbrico; el router no","Son sinónimos comerciales"],"correctIndex":1,"feedback":{"correct":"Correcto. El cartero interno y la oficina de correos — con su capa y su dirección cada uno.","incorrect":"Switch = dentro de la red, tramas y MAC (capa 2). Router = entre redes, paquetes e IP (capa 3)."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Al bajar por las capas, los nombres del dato son:","options":["Datos → paquete → segmento → trama → bits","Datos → segmento (puertos) → paquete (IPs) → trama (MACs) → bits","Bits → trama → paquete → datos","Datos → sobre → carta → buzón"],"correctIndex":1,"feedback":{"correct":"Correcto. El encapsulamiento — que ya viste desplegable en tu propio analizador.","incorrect":"Transporte lo hace segmento, red lo hace paquete, enlace lo hace trama, física lo hace bits: sobres dentro de sobres."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Una subred /26 ofrece cuántos hosts útiles, y por qué se restan dos:","options":["64, sin restas","62: 2^(32−26) − 2 — la primera dirección nombra a la red y la última es el broadcast","26","254"],"correctIndex":1,"feedback":{"correct":"Correcto. La fórmula de tu hoja de subredes: 2^6 = 64, menos red y broadcast.","incorrect":"2^(32−26) = 64 direcciones, menos las 2 reservadas (red y broadcast) = 62 útiles."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Cuarenta dispositivos navegan con UNA sola IP pública, y al conectarte a cualquier Wi-Fi recibes tu configuración automáticamente. Los dos responsables son:","options":["DNS y TLS","NAT (traduce privadas ↔ pública en el router) y DHCP (reparte IP + máscara + gateway + DNS al conectarte)","VPN y VLAN","TCP y UDP"],"correctIndex":1,"feedback":{"correct":"Correcto. El traductor de la puerta y el repartidor automático: la pareja del módulo 3.","incorrect":"NAT comparte la pública entre todos; DHCP te presta la configuración al llegar. Traductor y repartidor."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"El viaje de una petición HTTPS, en orden:","options":["HTTP → TCP → TLS → DNS","DNS (nombre → IP) → TCP (conexión al 443) → TLS (certificado y cifrado) → HTTP (la conversación, ya en privado)","TLS → DNS → HTTP → TCP","El orden no importa"],"correctIndex":1,"feedback":{"correct":"Correcto. Traducir, conectar, cifrar, conversar — y así lo viste, paquete a paquete, en tu captura.","incorrect":"Cada etapa habilita la siguiente: DNS da la IP, TCP abre, TLS cifra, HTTP conversa. Lo verificaste en Wireshark."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Un sitio de estafa muestra el candado HTTPS válido. Las dos promesas reales del candado son:","options":["Honestidad y velocidad","Conexión CIFRADA e identidad del DOMINIO — ninguna de las dos es honestidad: el phishing con HTTPS existe","Antivirus y respaldo","Anonimato y descuentos"],"correctIndex":1,"feedback":{"correct":"Correcto. El contrato completo del candado — y ni una cláusula sobre intenciones.","incorrect":"TLS promete privacidad del canal e identidad del nombre. La legitimidad del sitio se juzga aparte."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"En una red segmentada por zonas, el Wi-Fi de invitados no llega a los servidores internos porque:","options":["Los invitados no conocen la contraseña correcta","No existe regla del firewall que permita ese cruce — y la denegación por defecto bloquea todo lo no permitido: la contraseña decide quién ENTRA; la segmentación, a dónde LLEGA","El Wi-Fi es más lento","Los servidores están apagados de noche"],"correctIndex":1,"feedback":{"correct":"Correcto. Arquitectura sobre contraseñas: zonas por confianza con el vigilante en cada cruce.","incorrect":"Es la segmentación: invitados solo tiene salida a internet, y el firewall deniega por defecto el resto de cruces."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"La tríada del registro — presente en cada línea de log del router, del sistema y del firewall — es:","options":["IP + máscara + gateway","TIMESTAMP (cuándo) + ORIGEN (quién/desde dónde) + EVENTO (qué pasó): con ella se reconstruye cualquier incidente","Usuario + contraseña + permiso","Puerto + protocolo + veredicto"],"correctIndex":1,"feedback":{"correct":"Correcto. Ordenar por tiempo, correlacionar por origen, leer eventos: el corazón del análisis forense.","incorrect":"Cuándo + quién/desde dónde + qué: la anatomía universal del log, tu herramienta para reconstruir historias."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo es legítimo capturar tráfico de red con un analizador?","options":["Siempre que la red sea inalámbrica","SOLO en redes propias o con autorización ESCRITA del dueño: los profesionales capturan con contrato — sin ese papel, es delito","Cuando la red no tiene contraseña","Cuando nadie mira"],"correctIndex":1,"feedback":{"correct":"Correcto. La regla central del curso: la herramienta no distingue — el papel que autoriza, sí.","incorrect":"Red propia o autorización escrita, sin matices: capturar tráfico ajeno es delito y violación de privacidad."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista — LA clásica del oficio: '¿qué pasa cuando escribes una dirección en el navegador y pulsas Enter?' Tu respuesta senior, en un párrafo:","options":["La página baja del satélite directamente","DNS traduce el nombre a IP; TCP abre conexión al 443 de esa IP; TLS verifica el certificado y cifra; HTTP pide la página dentro del túnel — y cada paquete viaja encapsulado en capas, saltando router a router (cada uno decidiendo solo el siguiente salto), saliendo por el gateway y el NAT de tu red","El navegador ya tiene todas las páginas guardadas","Es imposible saberlo"],"correctIndex":1,"feedback":{"correct":"Impecable. Siete módulos en un párrafo: la respuesta con la que se abren puertas en entrevistas — y la prueba de que el mundo de Redes es tuyo. Byte lo celebra. 🌐","incorrect":"La respuesta senior encadena el curso: DNS → TCP (443) → TLS → HTTP, sobre paquetes encapsulados que saltan router a router desde tu gateway, traducidos por el NAT. Cada pieza tiene su módulo — repásalas y vuelve por la corona."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'redes-y-sistemas' and l.slug = 'm07-x01-examen';
