-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 033 — Python desde Cero · Módulo 2: Decisiones
-- ═══════════════════════════════════════════════════════════════════
-- Temario v2 (9 módulos). Reaprovecha el material aprobado del 031 v1
-- (lecciones de decisiones + diagrama de flujo + práctica del triage);
-- el material de bucles pasó a la 034.
-- Reglas de contenido (Karen): el entorno se explica por su USO; los
-- quizzes van autocontenidos (contexto en el enunciado) o apoyados en
-- términos técnicos.
-- Lección nueva respecto al v1: L3 · and, or y not.
-- El curso sigue is_published = false hasta la 041.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 031 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'python-desde-cero' and m.slug = 'm02-decisiones'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m02-l01-if-else',            'Decisiones: if y else',           'leccion',  20, 1),
       ('m02-l02-elif-escalera',      'elif: la escalera de decisiones', 'leccion',  20, 2),
       ('m02-l03-and-or-not',         'and, or y not',                   'leccion',  20, 3),
       ('m02-l04-pensar-algoritmos',  'Pensar en algoritmos',            'leccion',  20, 4),
       ('m02-l05-practica-triage',    'Práctica: el triage',             'practica', 20, 5),
       ('m02-x01-examen',             'Examen: Decisiones',              'examen',   40, 6)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'python-desde-cero' and m.slug = 'm02-decisiones';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Decisiones: if y else
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Programas que deciden","body":"Hasta ahora tus programas ejecutan todas las líneas, de arriba a abajo, sin desviarse. Pero la clínica necesita programas que DECIDAN: si la temperatura pasa de 38, avisar; si no, seguir normal. Eso es if: una condición que, si es verdadera, ejecuta un bloque de código. Y aquí viene la regla de oro de Python: el bloque se marca con INDENTACIÓN — las líneas 'dentro' del if van desplazadas 4 espacios, y esa sangría ES sintaxis, no decoración. Para escribir condiciones usas COMPARADORES: > mayor, < menor, >= mayor o igual, <= menor o igual, != distinto, y el que más confunde al principio: == (doble igual) COMPARA, mientras que = (uno solo) ASIGNA. temperatura == 38 pregunta; temperatura = 38 guarda."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"El primer triage","code":"temperatura = float(input(\"Temperatura del paciente: \"))\n\nif temperatura >= 38:\n    print(\"ALERTA: el paciente tiene fiebre\")\n    print(\"Avisar al médico de turno\")\nelse:\n    print(\"Temperatura sin alarma\")\n\nprint(\"Registro guardado\")  # esta línea corre SIEMPRE: ya no está indentada","result":{"columns":["CONSOLA"],"rows":[["Temperatura del paciente: 38.7"],["ALERTA: el paciente tiene fiebre"],["Avisar al médico de turno"],["Registro guardado"]],"note":"Las dos líneas indentadas pertenecen al if; 'Registro guardado' está fuera y se ejecuta con o sin fiebre."},"caption":"else = qué hacer cuando la condición es falsa. La indentación decide quién pertenece a quién."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En Python, ¿qué define qué líneas están 'dentro' de un if?","options":["Las llaves { }","La indentación: la sangría es parte de la sintaxis","El punto y coma","Escribirlas en mayúsculas"],"correctIndex":1,"feedback":{"correct":"Correcto. En Python la sangría no es estética: delimita los bloques.","incorrect":"Python no usa llaves: el bloque del if se define con INDENTACIÓN (4 espacios). Es sintaxis, no decoración."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre = y == ?","options":["Ninguna, son intercambiables","= asigna un valor a una variable; == compara dos valores","== asigna y = compara","= es para números y == para textos"],"correctIndex":1,"feedback":{"correct":"Correcto. temperatura = 38 guarda; temperatura == 38 pregunta si vale 38.","incorrect":"Uno solo (=) ASIGNA; el doble (==) COMPARA. Confundirlos es el error clásico dentro de un if."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de comparadores: ¿qué devuelve la expresión 5 >= 5?","options":["False, porque no es mayor","True: >= significa 'mayor O IGUAL', y la igualdad cuenta","Un error","5"],"correctIndex":1,"feedback":{"correct":"Correcto. El signo = del comparador incluye la igualdad: 5 >= 5 es True. Un detalle que decide fronteras (¿38.0 es fiebre?).","incorrect":">= se lee 'mayor o igual': la igualdad también lo cumple. 5 >= 5 → True. Por eso 38.0 SÍ dispara un if temperatura >= 38."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — if y else","points":["if ejecuta un bloque solo si la condición es verdadera; else cubre el caso contrario.","La INDENTACIÓN (4 espacios) define el bloque: en Python es sintaxis.","Comparadores: > < >= <= != y == (comparar). Recuerda: = asigna, == compara.",">= y <= incluyen la igualdad: 38.0 cumple temperatura >= 38.","Lo no indentado queda fuera de la decisión y corre siempre."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm02-l01-if-else';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · elif: la escalera de decisiones
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La escalera","body":"La vida real rara vez es sí/no: una temperatura puede ser hipotermia, normal, febrícula o fiebre. Para eso existe elif ('else if'): encadenas condiciones y Python las evalúa DE ARRIBA HACIA ABAJO, entrando SOLO en la primera que sea verdadera — el resto de la escalera se salta. Por eso el ORDEN importa: las condiciones más exigentes van arriba. El else final es la red de seguridad: atrapa todo lo que no cayó en ninguna condición anterior. Una escalera bien ordenada tiene otra virtud: cada peldaño ya sabe que los anteriores fallaron, así que no necesita repetir sus condiciones."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"La escalera del triage completo","code":"temperatura = 36.2\n\nif temperatura >= 39:\n    categoria = \"URGENTE\"\nelif temperatura >= 38:\n    categoria = \"Fiebre\"\nelif temperatura < 36:\n    categoria = \"Hipotermia\"\nelse:\n    categoria = \"Normal\"\n\nprint(f\"{temperatura} °C → {categoria}\")","result":{"columns":["CONSOLA"],"rows":[["36.2 °C → Normal"]],"note":"36.2 no llega a 39, no llega a 38 y no baja de 36: cae en el else. Prueba mentalmente con 39.5, 38.2 y 35.4."},"caption":"Primera condición verdadera gana. Si pusieras >= 38 ANTES de >= 39, los urgentes quedarían clasificados como fiebre — el orden es parte del algoritmo."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: clasificar la presión","body":"Tu turno: la presión sistólica del paciente llega en una variable presion. Escribe la escalera que la clasifique: menor que 90 → \"Baja\" · de 90 a 129 → \"Normal\" · de 130 a 139 → \"Elevada\" · 140 o más → \"Alta\". Muestra el resultado con una f-string, tipo: Presión 135 → Elevada. Pista: si ordenas bien la escalera, cada elif ya descarta lo anterior y no necesitas condiciones dobles. Resuélvelo antes de mirar la solución del siguiente bloque."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"presion = 135\n\nif presion < 90:\n    categoria = \"Baja\"\nelif presion < 130:\n    categoria = \"Normal\"\nelif presion < 140:\n    categoria = \"Elevada\"\nelse:\n    categoria = \"Alta\"\n\nprint(f\"Presión {presion} → {categoria}\")","result":{"columns":["CONSOLA"],"rows":[["Presión 135 → Elevada"]],"note":"Al llegar al segundo elif ya sabes que presion >= 130 (el anterior la habría atrapado): basta preguntar < 140."},"caption":"¿Escribiste condiciones dobles tipo presion >= 90 y presion < 130? Funciona, pero la escalera ordenada lo hace sola: cada peldaño descarta el anterior."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En una escalera if/elif/elif/else, ¿cuántas ramas se ejecutan?","options":["Todas las que sean verdaderas","Solo la PRIMERA condición verdadera (o el else si ninguna lo es)","Siempre el else","Las dos primeras"],"correctIndex":1,"feedback":{"correct":"Correcto. Python evalúa de arriba a abajo y entra solo en la primera verdadera; el resto se salta.","incorrect":"Solo entra en UNA rama: la primera condición verdadera de arriba a abajo — por eso el orden importa."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué papel juega el else al final de una escalera?","options":["Es una condición más que se evalúa primero","Es la red de seguridad: atrapa todos los casos que no cumplieron ninguna condición anterior","Detiene el programa","Es opcional solo si hay un solo if"],"correctIndex":1,"feedback":{"correct":"Correcto. else no lleva condición: recoge todo lo que las condiciones anteriores dejaron pasar.","incorrect":"else no evalúa nada: es la salida por defecto para lo que ninguna condición atrapó — la red de seguridad de la escalera."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — elif","points":["elif encadena condiciones: se evalúan de arriba a abajo y gana la PRIMERA verdadera.","El orden de la escalera es parte del algoritmo: lo más exigente arriba.","else es la red de seguridad: atrapa lo que ninguna condición cumplió.","Cada peldaño ya sabe que los anteriores fallaron: no repitas sus condiciones.","Una escalera clasifica un valor en categorías: el patrón del triage."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm02-l02-elif-escalera';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · and, or y not (nueva en el temario v2)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Decisiones que dependen de dos cosas","body":"Muchas decisiones reales combinan condiciones, y para eso existen los OPERADORES LÓGICOS. and exige que AMBAS condiciones sean verdaderas: derivar a urgencias si hay fiebre Y dificultad para respirar — una sola no basta. or se conforma con que AL MENOS UNA lo sea: aplicar tarifa reducida si el paciente es adulto mayor O tiene seguro. Y not INVIERTE un valor de verdad: not es_alergico es verdadero justo cuando es_alergico es falso. Un consejo de estilo que te ahorrará errores: cuando mezcles and y or en la misma condición, usa paréntesis para dejar clarísimo qué se agrupa con qué — el que lea tu código (incluida tu yo del futuro) te lo agradecerá."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Combinando condiciones en la clínica","code":"temperatura = 38.4\ndificultad_respirar = True\nedad = 70\ntiene_seguro = False\n\nderivar_urgencias = temperatura >= 38 and dificultad_respirar\ntarifa_reducida = edad >= 65 or tiene_seguro\n\nprint(f\"Derivar a urgencias: {derivar_urgencias}\")\nprint(f\"Tarifa reducida: {tarifa_reducida}\")","result":{"columns":["CONSOLA"],"rows":[["Derivar a urgencias: True"],["Tarifa reducida: True"]],"note":"Cada expresión lógica produce un bool (True/False) que puedes guardar en una variable con nombre — y el if de después se lee como una frase."},"caption":"and: ambas verdaderas (38.4 >= 38 ✓ y hay dificultad ✓). or: basta una (70 >= 65 ✓, aunque no haya seguro)."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: ¿se puede recetar?","body":"Tu turno: un medicamento pediátrico se puede recetar si el paciente NO es alérgico y, además, tiene más de 12 años O pesa más de 40 kg. Tienes las variables es_alergico (bool), edad (int) y peso (float). Escribe la condición en una variable se_puede_recetar y muéstrala con una f-string. Pista: necesitas not, and, or… y un par de paréntesis para agrupar la parte del or. Resuélvelo antes de mirar la solución."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"es_alergico = False\nedad = 11\npeso = 43.5\n\nse_puede_recetar = not es_alergico and (edad > 12 or peso > 40)\n\nprint(f\"¿Se puede recetar?: {se_puede_recetar}\")","result":{"columns":["CONSOLA"],"rows":[["¿Se puede recetar?: True"]],"note":"No es alérgico (not False → True) y, aunque tiene 11 años, pesa más de 40 kg: el or se cumple por el peso."},"caption":"Los paréntesis agrupan el or: sin ellos, la condición diría otra cosa. Ante la duda, paréntesis."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de operadores lógicos: ¿cuándo es verdadera la expresión A and B?","options":["Cuando al menos una de las dos es verdadera","Solo cuando AMBAS son verdaderas","Cuando A es verdadera, sin importar B","Nunca"],"correctIndex":1,"feedback":{"correct":"Correcto. and es exigente: las dos o nada. Para 'basta una' está or.","incorrect":"and exige que ambas condiciones sean verdaderas a la vez; si te basta una, el operador es or."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"not (temperatura >= 38) es exactamente equivalente a:","options":["temperatura > 38","temperatura <= 38","temperatura < 38","temperatura != 38"],"correctIndex":2,"feedback":{"correct":"Correcto. Negar 'mayor o igual que 38' deja 'menor que 38': el = de la frontera cambia de lado.","incorrect":"Lo contrario de 'temperatura >= 38' es 'temperatura < 38'. Ojo con la frontera: 38.0 cumplía la primera, así que NO puede cumplir su negación."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — and, or y not","points":["and: ambas condiciones verdaderas. or: al menos una. not: invierte el valor de verdad.","Una expresión lógica produce un bool: puedes guardarla en una variable con nombre y el if se lee como una frase.","Al mezclar and y or, usa paréntesis para agrupar sin ambigüedad.","not (x >= 38) equivale a x < 38: al negar, la frontera cambia de lado.","Fiebre Y dificultad respiratoria = and; adulto mayor O con seguro = or."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm02-l03-and-or-not';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Pensar en algoritmos (diagrama de flujo del triage)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Antes del código, el plan","body":"Un ALGORITMO es una receta precisa: pasos ordenados que resuelven un problema, escritos ANTES de programar. Los profesionales los dibujan como DIAGRAMAS DE FLUJO: cajas de proceso, cajas de decisión y flechas que marcan el camino. Vamos a diseñar el clasificador de signos vitales de la clínica — el mismo que construirás en la práctica de este módulo: entra una temperatura, el flujo la examina de la condición más urgente a la más leve, y sale una categoría. Explora el diagrama del siguiente bloque: toca cada caja y cada flecha, y fíjate en el ORDEN de las preguntas."}$j$),
  (2, 'diagrama', $j${"title":"El flujo del clasificador","component":"NetworkDiagram","props":{"label":"Clasificador de signos vitales · diagrama de flujo","ancho":520,"alto":364,"nodos":[{"id":"inicio","x":30,"y":24,"w":170,"h":36,"titulo":"Leer temperatura","subtitulo":"entrada","descripcion":"El punto de partida: el dato entra al programa (de un input, de un archivo… da igual: el flujo es el mismo)."},{"id":"d1","x":30,"y":92,"w":170,"h":36,"titulo":"¿temp >= 39?","tag":"decisión","descripcion":"La PRIMERA pregunta es la más urgente. Si es verdadera, el flujo sale por 'sí' y no pregunta nada más."},{"id":"urgente","x":330,"y":92,"w":160,"h":36,"titulo":"URGENTE","subtitulo":"llamar al médico","descripcion":"Categoría terminal: el flujo acaba aquí para 39 °C o más."},{"id":"d2","x":30,"y":160,"w":170,"h":36,"titulo":"¿temp >= 38?","tag":"decisión","descripcion":"Segunda pregunta. Ojo: si el flujo llegó aquí, YA sabes que temp < 39 — la pregunta anterior lo descartó."},{"id":"fiebre","x":330,"y":160,"w":160,"h":36,"titulo":"Fiebre","subtitulo":"revisar en turno","descripcion":"Para temperaturas de 38 a 38.9: fiebre sin urgencia."},{"id":"d3","x":30,"y":228,"w":170,"h":36,"titulo":"¿temp < 36?","tag":"decisión","descripcion":"Tercera pregunta: el otro extremo. Llegar aquí implica temp < 38."},{"id":"hipotermia","x":330,"y":228,"w":160,"h":36,"titulo":"Hipotermia","subtitulo":"abrigar y vigilar","descripcion":"Para temperaturas por debajo de 36 °C."},{"id":"normal","x":30,"y":300,"w":170,"h":36,"titulo":"Normal","subtitulo":"sin alarma","descripcion":"La red de seguridad: lo que no cayó en ninguna pregunta. En código será el else."}],"enlaces":[{"de":"inicio","a":"d1","tipo":"flecha","descripcion":"El dato entra a la primera decisión."},{"de":"d1","a":"urgente","tipo":"flecha","etiqueta":"sí","descripcion":"39 o más: URGENTE, y el flujo termina — las demás preguntas ni se evalúan."},{"de":"d1","a":"d2","tipo":"flecha","etiqueta":"no","descripcion":"Menos de 39: el flujo baja a la siguiente pregunta."},{"de":"d2","a":"fiebre","tipo":"flecha","etiqueta":"sí","descripcion":"38 o más (y ya sabemos que menos de 39): Fiebre."},{"de":"d2","a":"d3","tipo":"flecha","etiqueta":"no","descripcion":"Menos de 38: a la siguiente pregunta."},{"de":"d3","a":"hipotermia","tipo":"flecha","etiqueta":"sí","descripcion":"Bajo 36: Hipotermia."},{"de":"d3","a":"normal","tipo":"flecha","etiqueta":"no","descripcion":"Ni alta ni baja: Normal. Es el else del código."}],"hint":"Toca las cajas y las flechas. Sigue el camino de 38.5 °C con el dedo."},"caption":"Cada caja de decisión será un if/elif; el camino 'no' baja al siguiente peldaño; Normal es el else. El diagrama ES la escalera de la lección anterior, dibujada."}$j$),
  (3, 'texto', $j${"title":"Del diagrama al código","body":"La traducción es directa, casi mecánica: cada caja de DECISIÓN se convierte en un if o elif (en el mismo orden del diagrama, de arriba a abajo), cada flecha 'sí' en el bloque indentado de esa condición, y la caja final sin pregunta en el else. Por eso diseñar primero vale oro: si el diagrama está bien pensado — preguntas en el orden correcto, todos los caminos cubiertos —, el código sale solo y sin huecos. Los errores de lógica (¿y si la temperatura es exactamente 38?, ¿qué pasa con 35.9?) se cazan mucho más barato en el dibujo que en el programa ya escrito. Este hábito — pensar el flujo antes de teclear — te acompañará en cada proyecto del curso."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"El diagrama, traducido línea a línea","code":"temperatura = 38.5\n\nif temperatura >= 39:          # primera decisión del diagrama\n    categoria = \"URGENTE\"\nelif temperatura >= 38:        # segunda decisión\n    categoria = \"Fiebre\"\nelif temperatura < 36:         # tercera decisión\n    categoria = \"Hipotermia\"\nelse:                          # la caja sin pregunta: Normal\n    categoria = \"Normal\"\n\nprint(f\"{temperatura} °C → {categoria}\")","result":{"columns":["CONSOLA"],"rows":[["38.5 °C → Fiebre"]],"note":"38.5: la primera pregunta da no (no llega a 39), la segunda da sí (pasa de 38) → Fiebre. Exactamente el camino que seguiste en el diagrama."},"caption":"Cuatro cajas del diagrama, cuatro ramas de código. Cuando el plan está claro, programar es traducir."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un triage clasifica así: >= 39 URGENTE · >= 38 Fiebre · < 36 Hipotermia · resto Normal, preguntando en ese orden. ¿Qué categoría recibe una temperatura de 38.5 °C?","options":["URGENTE","Fiebre: la primera pregunta da 'no' y la segunda da 'sí'","Hipotermia","Normal"],"correctIndex":1,"feedback":{"correct":"Correcto. No llega a 39 (baja por 'no'), sí pasa de 38 (sale por 'sí'): Fiebre.","incorrect":"Sigue el flujo en orden: ¿38.5 >= 39? No → baja. ¿38.5 >= 38? Sí → Fiebre."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Al traducir un diagrama de flujo a Python, cada caja de decisión se convierte en…","options":["Un print","Un if o elif, en el mismo orden del diagrama","Una variable","Un comentario"],"correctIndex":1,"feedback":{"correct":"Correcto. Decisión = if/elif en orden; la caja final sin pregunta = else.","incorrect":"Las decisiones del diagrama son los if/elif del código, en el mismo orden de arriba a abajo."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Pensar en algoritmos","points":["Un algoritmo es una receta precisa; el diagrama de flujo la dibuja antes de programar.","Cajas de decisión = if/elif en el mismo orden; la salida sin pregunta = else.","El orden de las preguntas es parte del diseño: lo más urgente primero.","Los errores de lógica se cazan más barato en el diagrama que en el código.","En la práctica que sigue, este diagrama se vuelve programa en tus manos."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm02-l04-pensar-algoritmos';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Práctica: el triage (kind = practica, motor real)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"La clínica quiere el triage automático que diseñaste en el diagrama: dada la temperatura de un paciente, el programa debe imprimir su categoría. Te dejamos la primera regla escrita; completa la escalera.","instructions":["Mantén la primera regla: temperatura >= 39 → categoria = \"URGENTE\".","Agrega un elif para temperatura >= 38 → categoria = \"Fiebre\".","Agrega un elif para temperatura < 36 → categoria = \"Hipotermia\".","Cierra con un else → categoria = \"Normal\".","Deja el print final tal cual. EJECUTA para ver la salida; COMPRUEBA cuando esté listo."],"initialCode":"temperatura = 38.6\n\n# Escalera del triage:\n# >= 39 URGENTE · >= 38 Fiebre · < 36 Hipotermia · resto Normal\nif temperatura >= 39:\n    categoria = \"URGENTE\"\n# TODO: completa los dos elif y el else\n\nprint(f\"Temperatura: {temperatura} °C → {categoria}\")","validators":["elif\\s+temperatura\\s*>=\\s*38\\s*:","elif\\s+temperatura\\s*<\\s*36\\s*:","else\\s*:","categoria\\s*=\\s*[\"']fiebre[\"']","categoria\\s*=\\s*[\"']hipotermia[\"']","categoria\\s*=\\s*[\"']normal[\"']"],"entradas":[],"salidaEsperada":["Temperatura: 38.6 °C → Fiebre"],"mockOutput":{"columns":["CONSOLA"],"rows":[["Temperatura: 38.6 °C → Fiebre"]],"note":"38.6 no llega a 39, pero sí pasa de 38: cae en tu primer elif."},"hints":["La escalera va de lo más exigente a lo más leve: después del if >= 39 sigue elif temperatura >= 38.","El tercer peldaño pregunta por el otro extremo: elif temperatura < 36 para Hipotermia.","El else no lleva condición: atrapa todo lo que no cayó antes y asigna \"Normal\"."],"successMessage":"Triage operativo. La escalera clasifica cualquier temperatura: acabas de convertir un diagrama de flujo en un programa que funciona.","failMessage":"Revisa la escalera: elif temperatura >= 38 (Fiebre), elif temperatura < 36 (Hipotermia) y else (Normal), cada uno asignando su categoría."}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm02-l05-practica-triage';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La segunda región","body":"Byte llegó a la región de las decisiones: diez preguntas guardan el paso. Todo lo viviste: if y else, la escalera del elif, los operadores lógicos y el arte de dibujar el algoritmo antes de teclearlo. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"En Python, el bloque que pertenece a un if se delimita con:","options":["Llaves { }","Paréntesis","Indentación: la sangría es sintaxis","La palabra end"],"correctIndex":2,"feedback":{"correct":"Correcto. La sangría define los bloques: es sintaxis, no estética.","incorrect":"Python no usa llaves ni end: el bloque se marca con INDENTACIÓN (4 espacios)."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"temperatura = 38 y temperatura == 38 son:","options":["Lo mismo escrito de dos formas","Asignación (guardar 38) y comparación (¿vale 38?), respectivamente","Comparación y asignación, respectivamente","Dos errores de sintaxis"],"correctIndex":1,"feedback":{"correct":"Correcto. = guarda; == pregunta.","incorrect":"= ASIGNA un valor; == COMPARA dos valores. Dentro de un if casi siempre quieres ==."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un triage pregunta en orden: if temperatura >= 39 → URGENTE · elif >= 38 → Fiebre · elif < 36 → Hipotermia · else → Normal. ¿Qué categoría recibe exactamente 39.0?","options":["Fiebre, porque también pasa de 38","URGENTE: >= incluye la igualdad, la primera condición verdadera gana y las demás no se evalúan","Normal","Las dos primeras"],"correctIndex":1,"feedback":{"correct":"Correcto. 39.0 >= 39 es True (la igualdad cuenta): entra ahí y la escalera termina.","incorrect":"39.0 cumple la PRIMERA condición (>= incluye la igualdad): URGENTE, y el resto ni se mira."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En ese mismo triage, reordenas la escalera poniendo elif temperatura >= 38 ANTES del caso >= 39. ¿Qué se rompe?","options":["Nada: el orden no importa","Los pacientes de 39+ quedan clasificados como Fiebre: la condición amplia los atrapa antes","El programa no compila","El else deja de funcionar"],"correctIndex":1,"feedback":{"correct":"Correcto. 39.5 también cumple >= 38: la primera verdadera gana, y URGENTE se vuelve inalcanzable.","incorrect":"El orden ES el algoritmo: >= 38 atrapa también a los de 39+, y ningún paciente llegaría a URGENTE."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de operadores lógicos, A and B es verdadero…","options":["Cuando al menos una es verdadera","Solo cuando ambas son verdaderas","Cuando A es falsa","Siempre que B sea un número"],"correctIndex":1,"feedback":{"correct":"Correcto. and exige las dos; or se conforma con una.","incorrect":"and es el exigente: ambas condiciones verdaderas. Para 'basta una' existe or."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Una clínica deriva a urgencias si hay fiebre Y dificultad para respirar, y da tarifa reducida si el paciente es adulto mayor O tiene seguro. Los operadores correctos son:","options":["or para urgencias, and para la tarifa","and para urgencias (ambas deben cumplirse), or para la tarifa (basta una)","and para ambas","or para ambas"],"correctIndex":1,"feedback":{"correct":"Correcto. 'Y' exige las dos condiciones (and); 'O' se conforma con una (or).","incorrect":"Urgencias exige AMBAS señales → and. La tarifa se gana con UNA sola → or."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"not (edad >= 65) es exactamente equivalente a:","options":["edad > 65","edad <= 65","edad < 65","edad != 65"],"correctIndex":2,"feedback":{"correct":"Correcto. Negar 'mayor o igual' deja 'menor': la frontera (65) cambia de lado.","incorrect":"Lo contrario de 'edad >= 65' es 'edad < 65': quien tiene exactamente 65 cumplía la original, no su negación."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"En una escalera, ¿qué casos atrapa el else final?","options":["Los que cumplieron la primera condición","Todos los que NO cumplieron ninguna condición anterior: es la red de seguridad","Solo los errores","Ninguno: else es decorativo"],"correctIndex":1,"feedback":{"correct":"Correcto. else no pregunta nada: recoge lo que las condiciones dejaron pasar.","incorrect":"else es la salida por defecto: atrapa todo lo que ninguna condición anterior capturó."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"En un diagrama de flujo, las cajas de decisión y la caja final sin pregunta se traducen a Python como:","options":["print y variables","if/elif (en el mismo orden) y else","input y print","Comentarios"],"correctIndex":1,"feedback":{"correct":"Correcto. Decisiones = if/elif en orden; la salida que atrapa el resto = else.","incorrect":"Cada decisión es un if/elif en el orden del diagrama, y la caja sin pregunta es el else."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: '¿por qué el ORDEN de las condiciones en una escalera if/elif es parte del diseño del algoritmo?' Tu respuesta senior:","options":["No lo es: Python las ordena solo","Porque gana la primera condición verdadera: si una condición amplia va antes que una exigente, la exigente se vuelve inalcanzable — el orden decide qué casos llegan a cada rama","Porque el orden alfabético es obligatorio","Porque las escaleras largas son más lentas"],"correctIndex":1,"feedback":{"correct":"Impecable. La escalera se evalúa de arriba a abajo y la primera verdadera gana: ordenar de lo más exigente a lo más general ES diseñar el algoritmo.","incorrect":"La respuesta senior: como gana la primera condición verdadera, el orden decide qué casos captura cada rama — una condición amplia arriba 'roba' los casos de las exigentes."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm02-x01-examen';
