-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 035 — Python desde Cero · Módulo 4: Estructuras de datos
-- ═══════════════════════════════════════════════════════════════════
-- Temario v2 (9 módulos). Aquí aterriza el material "con listas" que
-- M3 dejó anotado (recorrer temperaturas, llamar pacientes, total y
-- fiebres, promedio) y la ANALOGÍA CENTRAL del curso:
--   lista de diccionarios = tabla (fila = dict, columna = clave).
-- Reglas de contenido: sin tecnología interna; quizzes autocontenidos
-- o con términos técnicos.
-- La práctica final NO usa input(): lista de diccionarios en memoria.
-- El curso sigue is_published = false hasta la 041.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 031 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'python-desde-cero' and m.slug = 'm04-estructuras-de-datos'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m04-l01-listas',             'Listas: tu primera colección',       'leccion',  20, 1),
       ('m04-l02-slicing',            'Rebanadas e índices negativos',      'leccion',  20, 2),
       ('m04-l03-diccionarios',       'Diccionarios: el registro con nombre','leccion', 20, 3),
       ('m04-l04-lista-de-dicts',     'Lista de diccionarios = tabla',      'leccion',  20, 4),
       ('m04-l05-tuplas-y-sets',      'Tuplas y sets: cuándo cada una',     'leccion',  20, 5),
       ('m04-l06-practica-agenda',    'Práctica: la agenda del turno',      'practica', 20, 6),
       ('m04-x01-examen',             'Examen: Estructuras de datos',       'examen',   40, 7)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'python-desde-cero' and m.slug = 'm04-estructuras-de-datos';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Listas: tu primera colección
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Una colección ordenada","body":"Una LISTA guarda varios valores en orden, entre corchetes: temperaturas = [36.5, 38.2, 39.4]. Cada elemento tiene su POSICIÓN o índice y — aquí se cumple la promesa del módulo 3 — se cuenta DESDE CERO: temperaturas[0] es 36.5, temperaturas[1] es 38.2. Las listas son secuencias, como las cadenas: len(temperaturas) las mide, el operador in pregunta si un valor está dentro, y el for las recorre elemento a elemento. La diferencia importante: las listas son MUTABLES — pueden crecer y cambiar después de creadas, cosa que las cadenas no permiten."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"El for que ya dominas, sobre tu primera lista","code":"temperaturas = [36.5, 38.2, 39.4, 35.8]\n\nprint(f\"Pacientes del turno: {len(temperaturas)}\")\nprint(f\"Primero del turno: {temperaturas[0]} °C\")\n\nfor temp in temperaturas:\n    if temp >= 38:\n        print(f\"{temp} °C → revisar paciente\")\n    else:\n        print(f\"{temp} °C → sin alarma\")","result":{"columns":["CONSOLA"],"rows":[["Pacientes del turno: 4"],["Primero del turno: 36.5 °C"],["36.5 °C → sin alarma"],["38.2 °C → revisar paciente"],["39.4 °C → revisar paciente"],["35.8 °C → sin alarma"]],"note":"El mismo for de los módulos anteriores: la variable temp toma cada elemento de la lista, en orden."},"caption":"Recorrer y filtrar, ahora sobre datos de verdad. Así se revisan 4 pacientes… o 4 millones."}$j$),
  (3, 'texto', $j${"title":"Las listas cambian: append y asignación","body":"Como son mutables, las listas tienen verbos. lista.append(valor) añade un elemento AL FINAL — es como llega cada paciente nuevo a la agenda. Y la asignación por índice reemplaza: lista[0] = 36.9 corrige el primer valor (¿un error de tipeo en la toma?). Ojo con el error clásico de esta semana: pedir un índice que no existe — temperaturas[10] en una lista de 4 — lanza IndexError, el primo del ValueError que ya conoces. Los índices válidos de una lista de n elementos van de 0 a n-1: por eso len() y los índices se llevan tan bien."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"La agenda crece","code":"agenda = [\"Ana Torres\", \"Luis Vega\"]\n\nagenda.append(\"Marta Solís\")   # llega una paciente nueva\nagenda[0] = \"Ana Torres López\"  # corregimos el primer registro\n\nprint(agenda)\nprint(f\"Pacientes en agenda: {len(agenda)}\")","result":{"columns":["CONSOLA"],"rows":[["['Ana Torres López', 'Luis Vega', 'Marta Solís']"],["Pacientes en agenda: 3"]],"note":"append añadió al final; la asignación agenda[0] = … reemplazó al primero. print(lista) muestra la lista completa, con sus corchetes."},"caption":"append para crecer, asignación por índice para corregir: los dos verbos del día a día."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Con pacientes = [\"Ana\", \"Luis\", \"Marta\"], ¿qué devuelve pacientes[1]?","options":["\"Ana\", porque es el primero","\"Luis\": los índices cuentan desde 0, así que el 1 es el segundo","\"Marta\"","Un error"],"correctIndex":1,"feedback":{"correct":"Correcto. Índices desde 0: pacientes[0] es \"Ana\", pacientes[1] es \"Luis\".","incorrect":"Los índices empiezan en 0: el [1] no es el primero sino el SEGUNDO — \"Luis\"."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué significa que una lista sea MUTABLE?","options":["Que solo acepta números","Que puede cambiar después de creada: crecer con append, corregirse por índice","Que se borra al terminar el programa","Que no se puede recorrer con for"],"correctIndex":1,"feedback":{"correct":"Correcto. Mutable = modificable en el lugar. Las cadenas, en cambio, son inmutables.","incorrect":"Mutable significa modificable: una lista crece (append) y se corrige (lista[i] = …) sin crear una nueva."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Listas","points":["Una lista guarda valores EN ORDEN, entre corchetes: [36.5, 38.2, 39.4].","Los índices cuentan desde 0: lista[0] es el primero; los válidos van de 0 a len-1.","len() mide, in pregunta, for recorre — igual que en las cadenas: ambas son secuencias.","Las listas son MUTABLES: append(valor) añade al final, lista[i] = x corrige.","Pedir un índice inexistente lanza IndexError — primo del ValueError del módulo 1."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm04-l01-listas';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Rebanadas e índices negativos
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Rebanadas: pedir un tramo","body":"A veces no quieres UN elemento sino un TRAMO: los tres primeros pacientes de la mañana, los últimos cinco análisis. Eso es el SLICING (rebanada): lista[1:3] devuelve una lista nueva con los elementos de la posición 1 a la 3 — y aquí reaparece tu vieja amiga, la convención de range: INICIO INCLUIDO, FINAL EXCLUIDO, así que [1:3] trae exactamente 2 elementos (posiciones 1 y 2). Los extremos se pueden omitir: lista[:3] = desde el principio, lista[2:] = hasta el final. Y los ÍNDICES NEGATIVOS cuentan desde atrás: lista[-1] es el último elemento, lista[-2] el penúltimo — comodísimo cuando no sabes cuántos hay. Todo esto funciona igual en cadenas: nombre[:3] son sus tres primeras letras."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"El turno en rebanadas","code":"citas = [\"Ana Torres\", \"Luis Vega\", \"Marta Solís\", \"Jorge Paz\", \"Rosa León\"]\n\nprint(f\"Turno de la mañana: {citas[:3]}\")\nprint(f\"Turno de la tarde:  {citas[3:]}\")\nprint(f\"Última cita del día: {citas[-1]}\")","result":{"columns":["CONSOLA"],"rows":[["Turno de la mañana: ['Ana Torres', 'Luis Vega', 'Marta Solís']"],["Turno de la tarde:  ['Jorge Paz', 'Rosa León']"],["Última cita del día: Rosa León"]],"note":"[:3] = posiciones 0, 1 y 2 (el 3 queda fuera). [-1] cuenta desde atrás: el último, sin importar cuántos haya."},"caption":"Rebanadas para partir el día en turnos; índice negativo para el cierre. La convención 'final excluido' hace que [:3] y [3:] no se pisen ni dejen huecos."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: llamar a los pacientes","body":"Tu turno: tienes pacientes = [\"Ana Torres\", \"Luis Vega\", \"Marta Solís\"]. Escribe un bucle que llame a cada uno con su número de turno: Turno 1: pase Ana Torres, Turno 2: pase Luis Vega, Turno 3: pase Marta Solís. Pista: es el patrón contador del módulo 3 — una variable turno = 1 antes del bucle, que crece dentro con turno = turno + 1. Resuélvelo antes de mirar la solución."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"pacientes = [\"Ana Torres\", \"Luis Vega\", \"Marta Solís\"]\n\nturno = 1\nfor nombre in pacientes:\n    print(f\"Turno {turno}: pase {nombre}\")\n    turno = turno + 1","result":{"columns":["CONSOLA"],"rows":[["Turno 1: pase Ana Torres"],["Turno 2: pase Luis Vega"],["Turno 3: pase Marta Solís"]],"note":"La variable del for lleva el nombre; el contador lleva la cuenta. Dos variables, dos trabajos."},"caption":"El contador del módulo 3 + la lista del módulo 4: las piezas ya se combinan solas."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Con citas = [\"a\", \"b\", \"c\", \"d\", \"e\"], ¿cuántos elementos devuelve citas[1:3]?","options":["3 elementos","2: las posiciones 1 y 2 — el final (3) se excluye","4 elementos","1 elemento"],"correctIndex":1,"feedback":{"correct":"Correcto. Inicio incluido, final excluido — la misma convención de range: [1:3] trae \"b\" y \"c\".","incorrect":"La rebanada excluye el final: [1:3] son las posiciones 1 y 2 (dos elementos), igual que range(1, 3)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de índices: ¿qué devuelve lista[-1]?","options":["Un error: los índices no pueden ser negativos","El ÚLTIMO elemento: los índices negativos cuentan desde atrás","El primero","La lista invertida"],"correctIndex":1,"feedback":{"correct":"Correcto. -1 es el último, -2 el penúltimo: perfectos cuando no sabes cuántos elementos hay.","incorrect":"Los índices negativos cuentan desde el final: lista[-1] es el último elemento, sin importar el tamaño."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Rebanadas e índices","points":["Slicing: lista[1:3] devuelve un tramo — inicio incluido, final excluido (la convención de range).","Extremos omitibles: [:3] desde el principio, [3:] hasta el final — no se pisan ni dejan huecos.","Índices negativos: [-1] el último, [-2] el penúltimo.","Todo funciona igual en cadenas: nombre[:3] son sus tres primeras letras.","Lista + contador manual: el patrón para numerar turnos."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm04-l02-slicing';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Diccionarios: el registro con nombre
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuando la posición no basta","body":"En una lista, los datos se identifican por POSICIÓN. Pero la ficha de un paciente — nombre, edad, grupo sanguíneo — pide algo mejor: identificar cada dato por su NOMBRE. Eso es un DICCIONARIO: pares clave: valor entre llaves. paciente = {\"nombre\": \"Ana Torres\", \"edad\": 35, \"grupo\": \"O+\"}. Se accede por clave — paciente[\"edad\"] devuelve 35 —, se corrige igual — paciente[\"edad\"] = 36 — y se amplía inventando la clave nueva: paciente[\"ciudad\"] = \"Lima\". Dos advertencias técnicas: las claves suelen ser cadenas (¡con comillas!), y pedir una clave que no existe lanza KeyError — el tercer primo de la familia de errores que estás coleccionando para el módulo 6."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"La ficha del paciente","code":"paciente = {\n    \"nombre\": \"Ana Torres\",\n    \"edad\": 35,\n    \"grupo\": \"O+\",\n    \"tiene_seguro\": True\n}\n\nprint(f\"Paciente: {paciente['nombre']} ({paciente['edad']} años)\")\nprint(f\"Grupo sanguíneo: {paciente['grupo']}\")\n\npaciente[\"ciudad\"] = \"Lima\"   # clave nueva: la ficha crece\nprint(f\"Ciudad: {paciente['ciudad']}\")","result":{"columns":["CONSOLA"],"rows":[["Paciente: Ana Torres (35 años)"],["Grupo sanguíneo: O+"],["Ciudad: Lima"]],"note":"Dentro de un f-string con comillas dobles, las claves van con comillas simples: {paciente['nombre']}."},"caption":"Cada dato tiene nombre propio: la ficha se lee sola. Compárala con una lista donde la edad fuera 'el elemento 1'."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: la cita","body":"Tu turno: construye un diccionario cita con tres claves — paciente (\"Ana Torres\"), especialidad (\"Cardiología\") y costo (850) — y muestra con una f-string: Cita de Ana Torres con Cardiología: $850. Después súbele el costo a 900 corrigiendo la clave y vuelve a mostrarlo. Resuélvelo antes de mirar la solución."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"cita = {\n    \"paciente\": \"Ana Torres\",\n    \"especialidad\": \"Cardiología\",\n    \"costo\": 850\n}\n\nprint(f\"Cita de {cita['paciente']} con {cita['especialidad']}: ${cita['costo']}\")\n\ncita[\"costo\"] = 900\nprint(f\"Costo actualizado: ${cita['costo']}\")","result":{"columns":["CONSOLA"],"rows":[["Cita de Ana Torres con Cardiología: $850"],["Costo actualizado: $900"]],"note":"La misma clave sirve para leer y para corregir: cita['costo'] a ambos lados de la historia."},"caption":"¿Pusiste las comillas en las claves? Es el tropiezo más común de la semana."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Con paciente = {\"nombre\": \"Luis\", \"edad\": 41}, ¿cómo obtienes la edad?","options":["paciente[1]","paciente[\"edad\"]: en un diccionario se accede por CLAVE, no por posición","paciente.edad()","edad in paciente"],"correctIndex":1,"feedback":{"correct":"Correcto. Las claves nombran los datos: paciente[\"edad\"] → 41.","incorrect":"Los diccionarios no usan posiciones sino CLAVES: paciente[\"edad\"] — con la clave entre comillas."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué error lanza pedir una clave que no existe, como paciente[\"telefono\"]?","options":["ValueError","IndexError","KeyError: la clave no está en el diccionario","No lanza error, devuelve 0"],"correctIndex":2,"feedback":{"correct":"Correcto. La familia crece: ValueError (conversión), IndexError (posición), KeyError (clave). Los domarás juntos en el módulo 6.","incorrect":"Clave inexistente = KeyError. Ya conoces tres primos: ValueError, IndexError y KeyError — cita con ellos en el módulo 6."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Diccionarios","points":["Un diccionario guarda pares clave: valor entre llaves: {\"nombre\": \"Ana\", \"edad\": 35}.","Se accede, corrige y amplía por clave: paciente[\"edad\"], paciente[\"ciudad\"] = \"Lima\".","Las claves llevan comillas (suelen ser cadenas); los valores pueden ser de cualquier tipo.","Clave inexistente → KeyError (tercer primo: ValueError, IndexError, KeyError).","Lista = datos por posición; diccionario = datos por nombre. La ficha del paciente es un diccionario natural."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm04-l03-diccionarios';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Lista de diccionarios = tabla (LA analogía central del curso)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La idea más importante del curso","body":"Junta las dos piezas y aparece la estructura que mueve el mundo de los datos: una LISTA DE DICCIONARIOS. Cada diccionario es una FILA (una cita completa, con sus datos nombrados); cada clave es una COLUMNA (paciente, costo, temperatura); la lista entera es la TABLA. Si vienes del mundo de las bases de datos, reconócelo: esto ES una tabla, viviendo en la memoria de tu programa. Y se trabaja con lo que ya sabes: for fila in tabla la recorre fila por fila, un if filtra las filas que cumplen algo, y los acumuladores del módulo 3 responden ¿cuántos? y ¿cuánto? Cuando en el módulo 7 leas un archivo CSV real, lo que obtendrás será exactamente esto — apréndelo aquí y el resto del curso es cuesta abajo."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"El día de la clínica, en números","code":"citas = [\n    {\"paciente\": \"Ana Torres\",  \"costo\": 850, \"temperatura\": 38.2},\n    {\"paciente\": \"Luis Vega\",   \"costo\": 600, \"temperatura\": 36.8},\n    {\"paciente\": \"Marta Solís\", \"costo\": 700, \"temperatura\": 39.1},\n    {\"paciente\": \"Jorge Paz\",   \"costo\": 550, \"temperatura\": 37.0}\n]\n\ntotal = 0\nfiebres = 0\n\nfor cita in citas:\n    total = total + cita[\"costo\"]\n    if cita[\"temperatura\"] >= 38:\n        fiebres = fiebres + 1\n\nprint(f\"Ingresos del día: {total}\")\nprint(f\"Con fiebre: {fiebres} de {len(citas)} pacientes\")","result":{"columns":["CONSOLA"],"rows":[["Ingresos del día: 2700"],["Con fiebre: 2 de 4 pacientes"]],"note":"En cada vuelta, cita es UNA fila completa; cita[\"costo\"] es la celda de esa fila en la columna costo."},"caption":"Recorrer + filtrar + acumular sobre una tabla: acabas de hacer tu primer análisis de datos de verdad."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: sobre el promedio","body":"Tu turno, con la misma tabla citas del ejemplo: calcula (1) el costo PROMEDIO de las citas (suma / cantidad, con un acumulador y len()), y (2) cuántas citas cuestan MÁS que ese promedio — necesitarás un segundo bucle DESPUÉS de conocer el promedio, porque no puedes comparar contra un número que aún no existe. Muestra el promedio con dos decimales (:.2f). Resuélvelo antes de mirar la solución."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"citas = [\n    {\"paciente\": \"Ana Torres\",  \"costo\": 850},\n    {\"paciente\": \"Luis Vega\",   \"costo\": 600},\n    {\"paciente\": \"Marta Solís\", \"costo\": 700},\n    {\"paciente\": \"Jorge Paz\",   \"costo\": 550}\n]\n\nsuma = 0\nfor cita in citas:\n    suma = suma + cita[\"costo\"]\n\npromedio = suma / len(citas)\n\ncaras = 0\nfor cita in citas:\n    if cita[\"costo\"] > promedio:\n        caras = caras + 1\n\nprint(f\"Costo promedio: {promedio:.2f}\")\nprint(f\"Citas sobre el promedio: {caras}\")","result":{"columns":["CONSOLA"],"rows":[["Costo promedio: 675.00"],["Citas sobre el promedio: 2"]],"note":"El segundo bucle NECESITA el promedio ya calculado: el orden de los pasos es parte del algoritmo — lo mismo que aprendiste con los diagramas de flujo."},"caption":"850 y 700 superan el promedio de 675. Dos pasadas sobre la tabla: una para conocer, otra para comparar."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En la analogía 'lista de diccionarios = tabla', ¿qué representa CADA diccionario de la lista?","options":["Una columna","Una FILA completa, con sus datos nombrados por clave","La tabla entera","Un error"],"correctIndex":1,"feedback":{"correct":"Correcto. Fila = diccionario, columna = clave, tabla = la lista completa.","incorrect":"Cada diccionario es UNA fila (una cita, un paciente); las claves compartidas son las columnas."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Dentro de for cita in citas:, ¿qué es exactamente cita[\"costo\"]?","options":["La columna costo completa","La CELDA de la fila actual en la columna costo: el costo de ESTA cita","El total de todos los costos","El nombre de la clave"],"correctIndex":1,"feedback":{"correct":"Correcto. La variable del bucle trae una fila; la clave elige su celda: fila + columna = celda.","incorrect":"cita es la fila de ESTA vuelta y [\"costo\"] su celda en esa columna: el costo de una sola cita."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Lista de diccionarios = tabla","points":["LA analogía central: fila = diccionario, columna = clave, tabla = lista de diccionarios.","for fila in tabla recorre fila a fila; fila[\"columna\"] es la celda.","Un if dentro del for FILTRA filas; los acumuladores responden ¿cuántos? y ¿cuánto?","Para comparar contra un promedio, primero hay que calcularlo: dos pasadas, en orden.","El CSV que leerás en el módulo 7 producirá exactamente esta estructura."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm04-l04-lista-de-dicts';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Tuplas y sets: cuándo cada una
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Las dos primas especializadas","body":"Dos estructuras más completan tu caja de herramientas. La TUPLA es una lista INMUTABLE — paréntesis en vez de corchetes: horario = (9, 17). Una vez creada, no se toca: perfecta para lo que NO debe cambiar (el par apertura-cierre, unas coordenadas, una fecha compuesta). Si intentas modificarla, Python te frena con un error — y eso es una VIRTUD: proteger un dato de cambios accidentales. El SET (conjunto) va entre llaves como el diccionario pero sin claves: {\"O+\", \"A-\"} — no admite DUPLICADOS y no garantiza orden. Su superpoder: convertir una lista en set elimina los repetidos de un golpe, y preguntar con in es rapidísimo. ¿Cuál usar? Orden y cambios → lista · datos con nombre → diccionario · fijo e intocable → tupla · únicos sin repetir → set."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Grupos sanguíneos del turno, sin repetir","code":"horario = (9, 17)   # tupla: apertura y cierre, intocables\n\ngrupos_del_turno = [\"O+\", \"A-\", \"O+\", \"B+\", \"O+\", \"A-\"]\nunicos = set(grupos_del_turno)\n\nprint(f\"Horario: de {horario[0]} a {horario[1]}\")\nprint(f\"Tomas registradas: {len(grupos_del_turno)}\")\nprint(f\"Grupos distintos que necesita el banco de sangre: {len(unicos)}\")\nprint(f\"¿Hubo algún B+?: {\"B+\" in unicos}\")","result":{"columns":["CONSOLA"],"rows":[["Horario: de 9 a 17"],["Tomas registradas: 6"],["Grupos distintos que necesita el banco de sangre: 3"],["¿Hubo algún B+?: True"]],"note":"set() redujo 6 tomas a 3 grupos únicos: O+, A- y B+. La tupla se lee por índice, como una lista — solo que nadie puede modificarla."},"caption":"La pregunta '¿cuántos DISTINTOS?' es un set esperando a ser usado. La respuesta '9 a 17, y no se cambia' es una tupla."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué distingue a una tupla de una lista?","options":["La tupla es más rápida de escribir","La tupla es INMUTABLE: una vez creada no admite cambios — ideal para datos que deben protegerse","La tupla solo guarda números","No hay diferencia, son sinónimos"],"correctIndex":1,"feedback":{"correct":"Correcto. Paréntesis, inmutable, protegida: para el dato que nadie debe tocar.","incorrect":"La diferencia es la INMUTABILIDAD: la tupla no se modifica después de creada — y esa protección es su razón de ser."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Registraste 20 tomas de grupo sanguíneo con repetidos y quieres saber cuántos grupos DISTINTOS hubo. La herramienta natural es:","options":["Una tupla","Un diccionario","Convertir la lista en set: elimina duplicados de un golpe, y len() cuenta los únicos","Ordenar la lista a mano"],"correctIndex":2,"feedback":{"correct":"Correcto. set(lista) → únicos; len(set(lista)) → cuántos distintos. La pregunta '¿cuántos distintos?' es un set.","incorrect":"El set no admite duplicados: set(lista) deja solo los valores únicos y len() los cuenta."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Elige la estructura correcta para cada dato: (1) las citas del día en orden de llegada, (2) la ficha de un paciente, (3) el par apertura-cierre de la clínica, (4) las ciudades DISTINTAS de origen de los pacientes.","options":["lista · diccionario · tupla · set","tupla · lista · set · diccionario","diccionario · lista · lista · tupla","set · tupla · diccionario · lista"],"correctIndex":0,"feedback":{"correct":"Correcto. Orden y cambios → lista; datos con nombre → diccionario; fijo → tupla; únicos → set.","incorrect":"La regla: orden/cambios = lista · nombre = diccionario · intocable = tupla · sin repetir = set. Repásala con cada dato."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Tuplas y sets","points":["Tupla (paréntesis): lista inmutable — protege lo que no debe cambiar.","Set (llaves, sin claves): sin duplicados y sin orden garantizado.","set(lista) elimina repetidos; len(set(lista)) cuenta los distintos.","El operador in en un set es rapidísimo: ideal para preguntar pertenencia.","La caja completa: lista (orden), diccionario (nombre), tupla (fijo), set (únicos)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm04-l05-tuplas-y-sets';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Práctica: la agenda del turno (lista de diccionarios, motor real)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"La agenda del turno vive en memoria como una tabla: una lista de diccionarios con paciente, costo y temperatura. La dirección quiere el parte del día: cada paciente con su temperatura, y al final el resumen — citas, ingresos y fiebres.","instructions":["Recorre la tabla con for cita in citas:","Dentro del bucle ya está el print de cada paciente: complétalo acumulando — suma cita[\"costo\"] a total.","Cuenta las fiebres: if cita[\"temperatura\"] >= 38 → suma 1 a fiebres.","No toques el print final: usa tus acumuladores. EJECUTA para ver el parte; COMPRUEBA cuando cuadre."],"initialCode":"citas = [\n    {\"paciente\": \"Ana Torres\",  \"costo\": 850, \"temperatura\": 38.2},\n    {\"paciente\": \"Luis Vega\",   \"costo\": 600, \"temperatura\": 36.8},\n    {\"paciente\": \"Marta Solís\", \"costo\": 700, \"temperatura\": 39.1}\n]\n\ntotal = 0\nfiebres = 0\n\n# TODO: recorre citas; en cada vuelta:\n#   - imprime f\"{cita['paciente']}: {cita['temperatura']} °C\"\n#   - acumula el costo en total\n#   - si la temperatura es >= 38, suma 1 a fiebres\n\nprint(f\"Citas: {len(citas)} · Total: {total:.2f} · Fiebres: {fiebres}\")","validators":["for\\s+cita\\s+in\\s+citas\\s*:","cita\\[\\s*[\"']costo[\"']\\s*\\]","if\\s+cita\\[\\s*[\"']temperatura[\"']\\s*\\]\\s*>=\\s*38","total\\s*(=\\s*total\\s*\\+|\\+=)","fiebres\\s*(=\\s*fiebres\\s*\\+\\s*1|\\+=\\s*1)"],"entradas":[],"salidaEsperada":["Ana Torres: 38.2 °C","Luis Vega: 36.8 °C","Marta Solís: 39.1 °C","Citas: 3 · Total: 2150.00 · Fiebres: 2"],"mockOutput":{"columns":["CONSOLA"],"rows":[["Ana Torres: 38.2 °C"],["Luis Vega: 36.8 °C"],["Marta Solís: 39.1 °C"],["Citas: 3 · Total: 2150.00 · Fiebres: 2"]],"note":"El parte del día: tres filas recorridas, dos acumuladores respondiendo ¿cuánto? y ¿cuántas?"},"hints":["El bucle: for cita in citas: — cada vuelta trae una FILA completa (un diccionario).","Dentro: print(f\"{cita['paciente']}: {cita['temperatura']} °C\") y total = total + cita[\"costo\"].","El conteo va con su condición: if cita[\"temperatura\"] >= 38: fiebres = fiebres + 1."],"successMessage":"Parte del día entregado: recorriste una tabla en memoria, celda a celda, y la resumiste con acumuladores. Esta estructura — lista de diccionarios — es la que te devolverá cada CSV que leas de aquí en adelante.","failMessage":"Revisa: for cita in citas:, el print con cita['paciente'] y cita['temperatura'], total acumulando cita[\"costo\"], y fiebres sumando 1 solo cuando la temperatura sea >= 38."}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm04-l06-practica-agenda';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La cuarta región","body":"Byte llegó a la región de las estructuras: diez preguntas guardan el paso. Todo lo viviste: listas e índices desde 0, rebanadas, diccionarios con sus claves, la tabla hecha de filas con nombre, y las primas especializadas — tupla y set. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Con temperaturas = [36.5, 38.2, 39.4], ¿qué devuelve temperaturas[0]?","options":["0","36.5: los índices cuentan desde 0","38.2","La lista completa"],"correctIndex":1,"feedback":{"correct":"Correcto. El primer elemento vive en el índice 0.","incorrect":"Los índices empiezan en 0: temperaturas[0] es el PRIMER elemento, 36.5."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Para añadir a \"Rosa León\" AL FINAL de la lista agenda, la instrucción es:","options":["agenda[0] = \"Rosa León\"","agenda.append(\"Rosa León\")","agenda + \"Rosa León\"","append(agenda)"],"correctIndex":1,"feedback":{"correct":"Correcto. append añade al final; la asignación por índice REEMPLAZA lo que había.","incorrect":"El verbo para crecer es append: agenda.append(\"Rosa León\"). agenda[0] = … reemplazaría al primero."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Con citas = [\"a\", \"b\", \"c\", \"d\", \"e\"], la rebanada citas[:2] devuelve:","options":["[\"a\", \"b\"]: desde el principio, con el final (2) excluido","[\"a\", \"b\", \"c\"]","[\"b\", \"c\"]","[\"d\", \"e\"]"],"correctIndex":0,"feedback":{"correct":"Correcto. [:2] = posiciones 0 y 1 — inicio incluido, final excluido, como en range.","incorrect":"La rebanada excluye su tope: [:2] trae las posiciones 0 y 1: [\"a\", \"b\"]."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Sin saber cuántos elementos tiene la lista citas, ¿cómo obtienes el ÚLTIMO?","options":["citas[len]","citas[-1]: los índices negativos cuentan desde atrás","citas[0]","ultimo(citas)"],"correctIndex":1,"feedback":{"correct":"Correcto. -1 siempre es el último, tenga la lista 3 elementos o 3 millones.","incorrect":"citas[-1]: el índice negativo cuenta desde el final — el comodín cuando no sabes el tamaño."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En un diccionario, los datos se identifican por:","options":["Su posición, desde 0","Su CLAVE: paciente[\"edad\"] — y pedir una clave inexistente lanza KeyError","Su longitud","Orden alfabético"],"correctIndex":1,"feedback":{"correct":"Correcto. Las claves nombran; los índices numeran. Y la clave que no existe protesta con KeyError.","incorrect":"El diccionario funciona por CLAVES con nombre: paciente[\"edad\"]. La posición es asunto de las listas."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"En la estructura citas = [{\"paciente\": \"Ana\", \"costo\": 850}, {\"paciente\": \"Luis\", \"costo\": 600}], cada diccionario representa:","options":["Una columna de la tabla","Una FILA: un registro completo con sus datos nombrados","El total de costos","Un error de sintaxis"],"correctIndex":1,"feedback":{"correct":"Correcto. Fila = diccionario, columna = clave, tabla = lista de diccionarios: LA analogía del curso.","incorrect":"Cada diccionario es una fila (una cita completa); las claves compartidas — paciente, costo — son las columnas."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Dentro de for cita in citas:, la expresión cita[\"costo\"] es:","options":["La suma de todos los costos","La celda de la fila actual en la columna costo","La lista de costos","Una clave nueva"],"correctIndex":1,"feedback":{"correct":"Correcto. Fila (cita) + columna (\"costo\") = celda: el costo de ESTA vuelta.","incorrect":"cita trae UNA fila por vuelta; [\"costo\"] elige su celda. Para el total necesitas un acumulador."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué guardarías el horario de la clínica en la tupla (9, 17) y no en una lista?","options":["Porque las tuplas son más bonitas","Porque la tupla es INMUTABLE: protege un dato que no debe cambiar por accidente","Porque las listas no aceptan números","Porque la tupla ordena sola"],"correctIndex":1,"feedback":{"correct":"Correcto. La inmutabilidad es protección: nadie modifica el horario por error.","incorrect":"La tupla no admite cambios tras crearse: esa protección es exactamente lo que quieres para un dato fijo."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"De una lista de 30 ciudades de pacientes (con repetidas), quieres saber cuántas ciudades DISTINTAS hay. La expresión es:","options":["len(ciudades)","len(set(ciudades)): el set elimina duplicados y len cuenta los únicos","set(len(ciudades))","ciudades.unicos()"],"correctIndex":1,"feedback":{"correct":"Correcto. set() deja los únicos; len() los cuenta. '¿Cuántos distintos?' = set.","incorrect":"Primero set(ciudades) para quedarte con los únicos, luego len() para contarlos: len(set(ciudades))."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: '¿por qué decimos que una lista de diccionarios ES una tabla, y por qué importa tanto?' Tu respuesta senior:","options":["Es un truco de memoria sin más fondo","Porque fila = diccionario, columna = clave y tabla = lista: todo dato tabular — un CSV, el resultado de una consulta — se modela así, y quien domina esa estructura ya sabe recorrer, filtrar y resumir cualquier dato","Porque Python no tiene otra forma de guardar datos","Porque las tablas solo existen en las bases de datos"],"correctIndex":1,"feedback":{"correct":"Impecable. Es EL modelo mental del trabajo con datos: cuando leas tu primer CSV en el módulo 7, ya sabrás exactamente qué hacer con él.","incorrect":"La respuesta senior: fila = dict, columna = clave, tabla = lista. Todo dato tabular llega en esa forma — dominarla es dominar el recorrido, el filtro y el resumen de cualquier dato."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm04-x01-examen';
