-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 036 — Python desde Cero · Módulo 5: Funciones
-- ═══════════════════════════════════════════════════════════════════
-- Temario v2 (9 módulos): def, parámetros/valores por defecto, return
-- y composición, y "leer clases sin miedo" (SOLO lectura, sin POO
-- profunda — condición del curso). La práctica construye la primera
-- librería clínica del alumno (semilla del proyecto integrador).
-- El return-en-vez-de-print del examen siembra M8 (assert prueba
-- funciones que devuelven valores).
-- Reglas de contenido: sin tecnología interna; quizzes autocontenidos
-- o con términos técnicos.
-- El curso sigue is_published = false hasta la 041.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 031 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'python-desde-cero' and m.slug = 'm05-funciones'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m05-l01-def',               'def: pasos con nombre propio',      'leccion',  20, 1),
       ('m05-l02-return',            'return: funciones que entregan',    'leccion',  20, 2),
       ('m05-l03-defecto-componer',  'Valores por defecto y composición', 'leccion',  20, 3),
       ('m05-l04-leer-clases',       'Leer clases sin miedo',             'leccion',  20, 4),
       ('m05-l05-practica-libreria', 'Práctica: tu librería clínica',     'practica', 20, 5),
       ('m05-x01-examen',            'Examen: Funciones',                 'examen',   40, 6)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'python-desde-cero' and m.slug = 'm05-funciones';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · def: pasos con nombre propio
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Nombrar los pasos","body":"Tu clasificador del módulo 3 funciona… pero cada vez que lo necesites tendrás que copiarlo y pegarlo. En programación, copiar y pegar el mismo bloque es una señal universal: ese bloque quiere ser una FUNCIÓN. Una función es un bloque de código con nombre propio: se DEFINE una vez con def nombre(): — encabezado, dos puntos y cuerpo indentado, como ya es costumbre — y se EJECUTA cuantas veces quieras LLAMÁNDOLA por su nombre: nombre(). Grábate la distinción, porque es el tropiezo de la semana: DEFINIR no ejecuta nada — Python solo memoriza la receta; la comida se cocina al LLAMAR. De hecho, llevas todo el curso llamando funciones: print(), len(), input() son funciones que alguien definió para ti."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Definir una vez, llamar mil veces","code":"def saludar_turno():\n    print(\"Clínica San Rafael\")\n    print(\"Turno de la mañana: consultorios abiertos\")\n\n# hasta aquí NO ha pasado nada visible: solo se definió\n\nsaludar_turno()   # primera llamada: ahora sí se ejecuta\nsaludar_turno()   # segunda llamada: mismo bloque, sin copiar nada","result":{"columns":["CONSOLA"],"rows":[["Clínica San Rafael"],["Turno de la mañana: consultorios abiertos"],["Clínica San Rafael"],["Turno de la mañana: consultorios abiertos"]],"note":"Dos llamadas, dos ejecuciones del mismo bloque. La definición (def) por sí sola no imprimió nada."},"caption":"def guarda la receta; la llamada — con sus paréntesis — la cocina. Sin paréntesis no hay ejecución."}$j$),
  (3, 'texto', $j${"title":"Parámetros: funciones que reciben datos","body":"Una función sin datos siempre hace lo mismo. El poder llega con los PARÁMETROS: def clasificar(temperatura): declara que la función necesita un dato para trabajar, y cada llamada se lo entrega: clasificar(38.6). Dos términos técnicos que las entrevistas adoran distinguir: el PARÁMETRO es la variable en la definición (temperatura); el ARGUMENTO es el valor concreto que le pasas en la llamada (38.6). Dentro de la función, el parámetro se usa como cualquier variable — pero solo existe ahí dentro: es LOCAL. Puedes declarar varios, separados por comas: def registrar(nombre, temperatura):, y los argumentos se entregan en el mismo orden."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"El triage, ahora reutilizable","code":"def clasificar(temperatura):\n    if temperatura >= 39:\n        print(f\"{temperatura} °C → URGENTE\")\n    elif temperatura >= 38:\n        print(f\"{temperatura} °C → Fiebre\")\n    elif temperatura < 36:\n        print(f\"{temperatura} °C → Hipotermia\")\n    else:\n        print(f\"{temperatura} °C → Normal\")\n\nclasificar(38.6)\nclasificar(35.2)\nclasificar(37.0)","result":{"columns":["CONSOLA"],"rows":[["38.6 °C → Fiebre"],["35.2 °C → Hipotermia"],["37.0 °C → Normal"]],"note":"La escalera se escribió UNA vez. Cada llamada entrega un argumento distinto y el parámetro temperatura lo recibe."},"caption":"Tu escalera del módulo 2, empaquetada con nombre: tres pacientes clasificados en tres líneas."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Escribes def avisar(): con su bloque, ejecutas el programa… y no pasa nada visible. ¿Por qué?","options":["La función tiene un error","DEFINIR no ejecuta: la función solo corre cuando se LLAMA — faltó avisar()","Las funciones no imprimen","Faltó indentación"],"correctIndex":1,"feedback":{"correct":"Correcto. def memoriza la receta; la llamada con paréntesis la ejecuta.","incorrect":"def solo DEFINE. Para ejecutar el bloque hay que llamar la función por su nombre: avisar()."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En def clasificar(temperatura): … y la llamada clasificar(38.6), los términos técnicos correctos son:","options":["38.6 es el parámetro y temperatura el argumento","temperatura es el PARÁMETRO (la variable de la definición) y 38.6 el ARGUMENTO (el valor de la llamada)","Ambos se llaman variables globales","temperatura es una constante"],"correctIndex":1,"feedback":{"correct":"Correcto. Parámetro en la definición, argumento en la llamada — distinción de entrevista.","incorrect":"El PARÁMETRO vive en la definición (temperatura); el ARGUMENTO es el valor concreto de cada llamada (38.6)."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — def","points":["Una función es un bloque con nombre: se define UNA vez (def nombre():) y se llama cuantas veces quieras (nombre()).","DEFINIR no ejecuta; la llamada — con paréntesis — sí.","Los PARÁMETROS declaran qué datos necesita la función; los ARGUMENTOS son los valores de cada llamada.","El parámetro es una variable LOCAL: solo existe dentro de la función.","print(), len() e input() son funciones: llevas todo el curso llamándolas."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm05-l01-def';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · return: funciones que entregan
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"print muestra; return ENTREGA","body":"Tu clasificar() imprime la categoría… y ahí muere: nadie puede usar ese resultado para nada más. La palabra clave return cambia el juego: la función ENTREGA un valor a quien la llamó, y ese valor se puede guardar en una variable, comparar en un if, pasar a otra función o acumular en un total. categoria = clasificar(38.6) solo es posible si clasificar hace return. Dos detalles técnicos: return TERMINA la función en ese instante (lo que haya después no se ejecuta), y una función puede tener varios return — por ejemplo, uno por rama de una escalera. Mención especial para las funciones que devuelven bool: def es_fiebre(temperatura): return temperatura >= 38 se lee como una PREGUNTA, y su llamada dentro de un if — if es_fiebre(t): — se lee como español."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"El clasificador que entrega","code":"def clasificar(temperatura):\n    if temperatura >= 39:\n        return \"URGENTE\"\n    elif temperatura >= 38:\n        return \"Fiebre\"\n    elif temperatura < 36:\n        return \"Hipotermia\"\n    return \"Normal\"\n\ncategoria = clasificar(38.6)      # el valor entregado se guarda\nprint(f\"Resultado: {categoria}\")\n\nif clasificar(39.4) == \"URGENTE\":  # o se usa directo en un if\n    print(\"Protocolo de urgencia activado\")","result":{"columns":["CONSOLA"],"rows":[["Resultado: Fiebre"],["Protocolo de urgencia activado"]],"note":"Cada rama entrega con su propio return y la función termina ahí — por eso el último ni necesita else."},"caption":"El valor entregado vive fuera de la función: guardado, comparado, reutilizado. Eso print no lo puede dar."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: la pregunta con nombre","body":"Tu turno: define es_fiebre(temperatura), que devuelva True si la temperatura es 38 o más (una sola línea de cuerpo: return con la comparación). Luego úsala para contar las fiebres de la lista [36.5, 38.2, 39.1, 37.2] con el patrón acumulador del módulo 3 — pero ahora el if se lee como español: if es_fiebre(temp):. Muestra el conteo. Resuélvelo antes de mirar la solución."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"def es_fiebre(temperatura):\n    return temperatura >= 38\n\ntemperaturas = [36.5, 38.2, 39.1, 37.2]\n\nfiebres = 0\nfor temp in temperaturas:\n    if es_fiebre(temp):\n        fiebres = fiebres + 1\n\nprint(f\"Fiebres del turno: {fiebres}\")","result":{"columns":["CONSOLA"],"rows":[["Fiebres del turno: 2"]],"note":"La comparación temperatura >= 38 YA es un bool: se entrega directo, sin if. Y el bucle se lee solo: 'si es fiebre, suma'."},"caption":"¿Escribiste if temperatura >= 38: return True…? Funciona, pero la comparación directa es el estilo Python: una línea."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿cuál es la diferencia entre print y return dentro de una función?","options":["Ninguna: ambos muestran en pantalla","print MUESTRA en la consola; return ENTREGA un valor a quien llamó — guardable, comparable, reutilizable","return es más lento","print entrega y return muestra"],"correctIndex":1,"feedback":{"correct":"Correcto. Mostrar ≠ entregar: solo el valor de return puede guardarse en una variable o usarse en un if.","incorrect":"print pinta en la consola y nada más; return ENTREGA el valor: categoria = clasificar(38.6) solo funciona con return."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Una función ejecuta return \"Fiebre\" en su segunda línea. ¿Qué pasa con las líneas que vienen después dentro de la función?","options":["Se ejecutan normalmente","No se ejecutan: return TERMINA la función en ese instante","Se ejecutan solo si hay else","Se guardan para la próxima llamada"],"correctIndex":1,"feedback":{"correct":"Correcto. return entrega y sale: por eso una escalera puede tener un return por rama sin pisarse.","incorrect":"return es puerta de salida: la función termina ahí y entrega su valor. Lo posterior no corre."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — return","points":["print muestra; return ENTREGA un valor a quien llamó.","El valor entregado se guarda (x = f(...)), se compara (if f(...) == …) o se pasa a otra función.","return TERMINA la función al instante; puede haber varios (uno por rama).","Las funciones que devuelven bool son preguntas con nombre: if es_fiebre(t): se lee como español.","return temperatura >= 38 — la comparación ya es un bool: entrégala directa."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm05-l02-return';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Valores por defecto y composición
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Parámetros con plan B","body":"A veces un parámetro casi siempre vale lo mismo. Los VALORES POR DEFECTO lo resuelven: def registrar(nombre, prioridad=\"normal\"): — si la llamada no entrega prioridad, vale \"normal\"; si la entrega, se usa la suya. Regla de sintaxis: los parámetros con defecto van AL FINAL de la lista. Y un lujo de legibilidad: los ARGUMENTOS CON NOMBRE — registrar(\"Ana Torres\", prioridad=\"alta\") — dicen qué es cada valor en la propia llamada. Los verás en todas las librerías del mundo real: las funciones profesionales tienen muchos parámetros opcionales, y las llamadas se leen gracias a los nombres."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Registro con prioridad opcional","code":"def registrar(nombre, prioridad=\"normal\"):\n    print(f\"[{prioridad.upper()}] {nombre} en lista de espera\")\n\nregistrar(\"Ana Torres\")                      # usa el defecto\nregistrar(\"Luis Vega\", \"alta\")               # lo reemplaza por posición\nregistrar(\"Marta Solís\", prioridad=\"alta\")   # con nombre: se lee solo","result":{"columns":["CONSOLA"],"rows":[["[NORMAL] Ana Torres en lista de espera"],["[ALTA] Luis Vega en lista de espera"],["[ALTA] Marta Solís en lista de espera"]],"note":".upper() pone el texto en mayúsculas — un método de las cadenas: pista de la próxima lección."},"caption":"Tres llamadas, tres estilos: defecto, posicional y con nombre. La tercera es la que mejor se lee."}$j$),
  (3, 'texto', $j${"title":"Componer: funciones que llaman funciones","body":"El verdadero poder aparece al COMPONER: una función puede llamar a otras, y el programa se convierte en una pirámide de piezas con nombre. La de arriba cuenta la historia completa; las de abajo hacen cada trabajo. Es la receta profesional para el problema grande: pártelo en funciones pequeñas — cada una haciendo UNA cosa bien, con nombre honesto — y compón. Bonus que ya conoces sin saberlo: len(set(ciudades)) del módulo 4 ES composición — el resultado de set() entra directo a len(). Cuando escribas el proyecto integrador, esta lección será tu columna vertebral."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"El parte del turno, compuesto","code":"def es_fiebre(temperatura):\n    return temperatura >= 38\n\ndef contar_fiebres(temperaturas):\n    fiebres = 0\n    for temp in temperaturas:\n        if es_fiebre(temp):          # una función usando a la otra\n            fiebres = fiebres + 1\n    return fiebres\n\ndef parte_del_turno(temperaturas):\n    print(f\"Pacientes: {len(temperaturas)}\")\n    print(f\"Fiebres: {contar_fiebres(temperaturas)}\")\n\nparte_del_turno([36.5, 38.2, 39.1, 37.2])","result":{"columns":["CONSOLA"],"rows":[["Pacientes: 4"],["Fiebres: 2"]],"note":"Tres pisos: parte_del_turno llama a contar_fiebres, que llama a es_fiebre. Cada pieza, una responsabilidad."},"caption":"Lee la función de arriba: cuenta la historia completa sin un solo detalle técnico. Eso es componer."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Con def registrar(nombre, prioridad=\"normal\"):, la llamada registrar(\"Ana\") es:","options":["Un error: faltó un argumento","Válida: prioridad toma su valor por defecto, \"normal\"","Válida, pero prioridad queda vacía","Un aviso de Python"],"correctIndex":1,"feedback":{"correct":"Correcto. El defecto es el plan B: si la llamada no lo entrega, se usa \"normal\".","incorrect":"El parámetro con defecto es opcional: sin argumento, prioridad vale \"normal\" y la llamada es perfectamente válida."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de composición: en la expresión len(set(ciudades)), ¿qué está pasando?","options":["Un error de paréntesis","Composición: el valor que RETORNA set() entra como argumento de len()","len y set son la misma función","set borra la lista original siempre"],"correctIndex":1,"feedback":{"correct":"Correcto. El return de una función alimenta a la siguiente: composición pura, y ya la usabas en el módulo 4.","incorrect":"Es composición: set(ciudades) entrega los únicos, y ese resultado es el argumento de len(). Return alimentando llamadas."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Defectos y composición","points":["Valor por defecto: def registrar(nombre, prioridad=\"normal\") — opcional en la llamada; van al final de la lista.","Argumentos con nombre: registrar(\"Ana\", prioridad=\"alta\") — la llamada se documenta sola.","Componer = funciones llamando funciones: piezas pequeñas con nombre honesto, historia clara arriba.","len(set(x)) ya era composición: el return de una alimenta a la otra.","El proyecto integrador se construye así: partir, nombrar, componer."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm05-l03-defecto-componer';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Leer clases sin miedo (solo lectura — sin POO profunda)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Objetivo modesto: leerlas, no escribirlas","body":"Tarde o temprano abrirás código ajeno y encontrarás la palabra class. Este curso no te pide escribir clases — te pide algo más útil a tu nivel: LEERLAS SIN SUSTO. Las ideas: una CLASE es un molde para fabricar OBJETOS; un objeto empaqueta DATOS (sus atributos) junto con las FUNCIONES que saben trabajarlos (sus MÉTODOS — funciones que se llaman con punto). Y la revelación: llevas medio curso usando objetos. \"ana\".upper() llama al método upper del objeto cadena; agenda.append(...) llama al método append del objeto lista. El punto es la señal: objeto.metodo() significa 'objeto, haz tu trabajo'."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Una clase, leída línea a línea","code":"class Paciente:                        # el molde\n    def __init__(self, nombre, temperatura):\n        # __init__ corre al FABRICAR el objeto y guarda sus datos\n        self.nombre = nombre           # atributo: dato del objeto\n        self.temperatura = temperatura\n\n    def tiene_fiebre(self):            # método: función del objeto\n        return self.temperatura >= 38\n\n# fabricar objetos: se llama a la clase como una función\nana = Paciente(\"Ana Torres\", 38.6)\nluis = Paciente(\"Luis Vega\", 36.5)\n\nprint(f\"{ana.nombre}: ¿fiebre? {ana.tiene_fiebre()}\")\nprint(f\"{luis.nombre}: ¿fiebre? {luis.tiene_fiebre()}\")","result":{"columns":["CONSOLA"],"rows":[["Ana Torres: ¿fiebre? True"],["Luis Vega: ¿fiebre? False"]],"note":"self es 'este objeto en particular': cuando ana llama tiene_fiebre, self.temperatura es LA temperatura de ana (38.6)."},"caption":"Dos objetos del mismo molde, cada uno con sus datos. El método pregunta por los datos de SU objeto — eso es self."}$j$),
  (3, 'texto', $j${"title":"Lo que necesitas reconocer (y nada más)","body":"Tu kit de lectura completo: (1) class Algo: define un molde; (2) Algo(argumentos) FABRICA un objeto — la llamada se parece a una función, y los argumentos van al __init__; (3) objeto.atributo LEE un dato del objeto (sin paréntesis); (4) objeto.metodo() EJECUTA una función del objeto (con paréntesis); (5) dentro de la clase, self es 'este objeto'. Con esas cinco llaves puedes leer la documentación de cualquier librería — que está llena de objetos — y el código de tus futuros colegas. Escribir tus propias clases tendrá su momento, más adelante en tu ruta; hoy ya no te intimidan."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué es un MÉTODO?","options":["Cualquier línea con paréntesis","Una función que vive en un objeto y se llama con punto: agenda.append(...), \"ana\".upper()","Una variable global","Un tipo de bucle"],"correctIndex":1,"feedback":{"correct":"Correcto. Método = función de un objeto. El punto es la señal: objeto.metodo().","incorrect":"Un método es una función que pertenece a un objeto y se invoca con punto — ya usabas append y upper sin saber su apellido."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Dentro de una clase, ¿qué representa self?","options":["La clase entera","EL OBJETO CONCRETO con el que se está trabajando: sus atributos son self.nombre, self.temperatura…","Una palabra decorativa","El primer paciente de la lista"],"correctIndex":1,"feedback":{"correct":"Correcto. Cuando ana llama a su método, self ES ana: self.temperatura es su 38.6, no la de otro.","incorrect":"self es 'este objeto en particular': el que llamó al método. Por eso self.temperatura cambia según quién pregunte."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Leer clases","points":["Clase = molde; objeto = lo fabricado; atributos = sus datos; métodos = sus funciones (con punto).","Algo(argumentos) fabrica un objeto; los argumentos van al __init__.","objeto.atributo lee (sin paréntesis); objeto.metodo() ejecuta (con paréntesis).","self = 'este objeto': sus datos son self.loquesea.","Ya usabas objetos: cadenas y listas lo son — .upper() y .append() son métodos. Hoy solo LEEMOS clases; escribirlas vendrá después en tu ruta."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm05-l04-leer-clases';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Práctica: tu librería clínica (motor real)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"La clínica empieza su librería de utilidades: funciones con nombre que todo el equipo reutilizará. Tú escribes las dos primeras; el código de prueba de abajo las pondrá a trabajar sobre el turno real.","instructions":["Define es_fiebre(temperatura): devuelve True si la temperatura es 38 o más (un return de una línea basta).","Define promedio(suma, cantidad): devuelve la división suma / cantidad.","No toques el código de prueba: él llama a TUS funciones.","EJECUTA para ver el parte; COMPRUEBA cuando cuadre."],"initialCode":"# Tu librería clínica: dos funciones reutilizables.\n\n# TODO 1: define es_fiebre(temperatura) → True si es 38 o más\n\n# TODO 2: define promedio(suma, cantidad) → suma / cantidad\n\n\n# ── código de prueba (no lo toques) ──\ntemperaturas = [36.5, 38.2, 39.1]\nsuma = 0\nfiebres = 0\nfor temp in temperaturas:\n    suma = suma + temp\n    if es_fiebre(temp):\n        fiebres = fiebres + 1\n\nprint(f\"Fiebres: {fiebres}\")\nprint(f\"Promedio: {promedio(suma, len(temperaturas)):.1f} °C\")","validators":["def\\s+es_fiebre\\s*\\(\\s*temperatura\\s*\\)\\s*:","def\\s+promedio\\s*\\(\\s*suma\\s*,\\s*cantidad\\s*\\)\\s*:","return"],"entradas":[],"salidaEsperada":["Fiebres: 2","Promedio: 37.9 °C"],"mockOutput":{"columns":["CONSOLA"],"rows":[["Fiebres: 2"],["Promedio: 37.9 °C"]],"note":"Tus funciones, llamadas por el código de prueba: 38.2 y 39.1 son fiebre, y el promedio del turno es 37.9."},"hints":["def es_fiebre(temperatura): y en la línea siguiente (indentada) return temperatura >= 38 — la comparación ya es un bool.","def promedio(suma, cantidad): con return suma / cantidad.","Las funciones deben definirse ANTES del código de prueba que las llama — escríbelas donde están los TODO."],"successMessage":"Librería inaugurada: dos funciones con nombre honesto que cualquier programa puede llamar. En el proyecto integrador, esta librería crecerá contigo.","failMessage":"Revisa: def es_fiebre(temperatura): con return temperatura >= 38, y def promedio(suma, cantidad): con return suma / cantidad — definidas ANTES del código de prueba."}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm05-l05-practica-libreria';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La quinta región","body":"Byte llegó a la región de las funciones: diez preguntas guardan el paso. Todo lo viviste: def y la llamada, parámetros y argumentos, el return que entrega, los valores por defecto, la composición y tu kit para leer clases. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre DEFINIR una función y LLAMARLA?","options":["Ninguna","def guarda la receta sin ejecutar nada; la llamada nombre() la ejecuta","def ejecuta y la llamada define","Las funciones se ejecutan solas al definirse"],"correctIndex":1,"feedback":{"correct":"Correcto. Definir memoriza; llamar cocina. Sin paréntesis no hay ejecución.","incorrect":"def solo DEFINE (nada visible pasa); el bloque corre cuando la llamas: nombre()."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En def registrar(nombre): y la llamada registrar(\"Ana\"), los términos técnicos son:","options":["nombre es el argumento; \"Ana\" el parámetro","nombre es el PARÁMETRO; \"Ana\" es el ARGUMENTO","Ambos son parámetros","Ambos son retornos"],"correctIndex":1,"feedback":{"correct":"Correcto. Parámetro en la definición; argumento en la llamada.","incorrect":"La variable de la definición es el parámetro; el valor concreto de la llamada es el argumento."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres guardar el resultado de una función en una variable: resultado = calcular(10). ¿Qué necesita la función?","options":["Un print al final","Un return: print muestra en consola, pero solo return ENTREGA un valor a quien llama","Dos parámetros","Ser muy corta"],"correctIndex":1,"feedback":{"correct":"Correcto. Sin return, resultado quedaría vacío por mucho print que haya dentro.","incorrect":"print pinta en pantalla y nada más; para que la asignación funcione, la función debe ENTREGAR con return."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Una función ejecuta su return en la línea 2 de 5. Las líneas 3, 4 y 5:","options":["Se ejecutan igual","No se ejecutan: return termina la función al instante","Se ejecutan en la próxima llamada","Dan error"],"correctIndex":1,"feedback":{"correct":"Correcto. return entrega y sale: es la puerta de salida de la función.","incorrect":"return TERMINA la función ahí mismo: lo que sigue no corre en esa llamada."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"def es_urgente(temperatura): return temperatura >= 39 — ¿qué entrega esta función?","options":["La temperatura","Un bool (True/False): la comparación ya es un valor de verdad, listo para un if","El texto \"urgente\"","Nada"],"correctIndex":1,"feedback":{"correct":"Correcto. La comparación produce el bool y return lo entrega: una pregunta con nombre.","incorrect":"temperatura >= 39 ya ES True o False; la función entrega ese bool — y if es_urgente(t): se lee como español."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Con def registrar(nombre, prioridad=\"normal\"):, ¿qué imprime prioridad si llamas registrar(\"Ana\", prioridad=\"alta\")?","options":["\"normal\", el defecto manda siempre","\"alta\": el argumento de la llamada reemplaza al valor por defecto","Ambos","Un error por usar el nombre"],"correctIndex":1,"feedback":{"correct":"Correcto. El defecto es plan B: solo aplica cuando la llamada no entrega el valor.","incorrect":"El valor por defecto solo actúa en ausencia de argumento: aquí la llamada entregó \"alta\" y esa gana."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"En calcular_total(filtrar_fiebres(citas)), ¿qué patrón estás viendo?","options":["Un error de paréntesis","COMPOSICIÓN: el valor que retorna filtrar_fiebres entra como argumento de calcular_total","Dos funciones sin relación","Recursión"],"correctIndex":1,"feedback":{"correct":"Correcto. El return de una alimenta a la otra: así se arman los programas grandes con piezas pequeñas.","incorrect":"Es composición: primero corre filtrar_fiebres, y su resultado es el argumento de calcular_total."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"En agenda.append(\"Rosa León\"), el término técnico para append es:","options":["Variable","MÉTODO: una función que vive en el objeto lista y se llama con punto","Parámetro","Clase"],"correctIndex":1,"feedback":{"correct":"Correcto. Las listas son objetos y append es uno de sus métodos.","incorrect":"append es un MÉTODO: función del objeto lista, invocada con punto — objeto.metodo()."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Lees ana = Paciente(\"Ana Torres\", 38.6) en código ajeno. ¿Qué está pasando?","options":["Se define una función llamada Paciente","Se FABRICA un objeto del molde (clase) Paciente; los argumentos van a su __init__","Se borra a la paciente","Se imprime la ficha"],"correctIndex":1,"feedback":{"correct":"Correcto. Llamar a la clase fabrica el objeto: ana queda con sus atributos nombre y temperatura.","incorrect":"Paciente(...) con mayúscula es una CLASE llamándose: fabrica un objeto y sus argumentos van al __init__."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: '¿por qué tus funciones deberían ENTREGAR con return en vez de imprimir con print?' Tu respuesta senior:","options":["Porque print está prohibido en las empresas","Porque el valor entregado es REUTILIZABLE y COMPROBABLE: se guarda, se compone con otras funciones y se puede verificar automáticamente — una función que solo imprime muere en la pantalla","Porque return es más rápido","No hay diferencia real"],"correctIndex":1,"feedback":{"correct":"Impecable. Y guarda la palabra 'comprobable': en el módulo 8 escribirás pruebas que verifican valores entregados — a un print no se le puede preguntar nada.","incorrect":"La respuesta senior: return hace la función reutilizable (su valor viaja) y comprobable (se puede verificar con pruebas — módulo 8). El print acopla el resultado a la pantalla."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm05-x01-examen';
