-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 037 — Python desde Cero · Módulo 6: Excepciones y robustez
-- ═══════════════════════════════════════════════════════════════════
-- Temario v2 (9 módulos). Paga las semillas plantadas en M1/M4:
-- ValueError (el BONUS de la toma de temperatura), IndexError y
-- KeyError por fin se doman con try/except. Cierra con validación de
-- datos sucios — la antesala directa de M7 (los CSV reales de la
-- clínica traen exactamente esas imperfecciones).
-- Reglas de contenido: sin tecnología interna; quizzes autocontenidos
-- o con términos técnicos.
-- El curso sigue is_published = false hasta la 041.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 031 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'python-desde-cero' and m.slug = 'm06-excepciones-y-robustez'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m06-l01-errores-con-nombre', 'Errores con nombre y apellido',    'leccion',  20, 1),
       ('m06-l02-try-except',         'try/except: el paracaídas',        'leccion',  20, 2),
       ('m06-l03-reintentar',         'Reintentar hasta que esté bien',   'leccion',  20, 3),
       ('m06-l04-datos-sucios',       'Validar datos sucios',             'leccion',  20, 4),
       ('m06-l05-practica-blindaje',  'Práctica: el registro blindado',   'practica', 20, 5),
       ('m06-x01-examen',             'Examen: Excepciones y robustez',   'examen',   40, 6)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'python-desde-cero' and m.slug = 'm06-excepciones-y-robustez';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Errores con nombre y apellido
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El error es un mapa, no un castigo","body":"Cuando algo falla, Python DETIENE el programa y publica un TRACEBACK: el informe del accidente. Léelo de abajo hacia arriba y encontrarás tres datos de oro: el TIPO de error (su nombre técnico), el MENSAJE (qué salió mal exactamente) y la LÍNEA donde ocurrió. Ya coleccionaste varios tipos en el camino: ValueError (una conversión imposible, como el BONUS del módulo 1), TypeError (mezclar tipos: \"texto\" + 35), IndexError (posición que no existe en una lista) y KeyError (clave que no está en el diccionario). Hoy se suma ZeroDivisionError (dividir entre cero) — y sobre todo, hoy dejan de detenerte: este módulo te enseña a esperarlos y manejarlos."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Leyendo un accidente completo","code":"temperatura = float(\"treinta y ocho\")\nprint(\"Esta línea nunca se ejecuta\")","result":{"columns":["CONSOLA"],"rows":[["Traceback (most recent call last):"],["  File \"<exec>\", line 1, in <module>"],["ValueError: could not convert string to float: 'treinta y ocho'"]],"note":"Tipo: ValueError · Mensaje: no pudo convertir esa cadena a float · Línea: 1. Y ojo: el print de la línea 2 jamás corrió — el error DETUVO el programa."},"caption":"Tres datos de oro en dos líneas: qué falló, por qué y dónde. Quien lee tracebacks depura en minutos; quien no, adivina durante horas."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos técnicos, ¿qué tres datos clave te da un traceback?","options":["El autor, la fecha y la versión","El TIPO de error, el MENSAJE y la LÍNEA donde ocurrió","Solo que algo falló","La solución exacta del problema"],"correctIndex":1,"feedback":{"correct":"Correcto. Tipo + mensaje + línea: el mapa completo del accidente.","incorrect":"El traceback dice QUÉ tipo de error fue, POR QUÉ (mensaje) y DÓNDE (línea). Leerlo es la habilidad número uno."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Empareja el accidente con su error: citas[10] en una lista de 4 elementos lanza…","options":["ValueError","KeyError","IndexError: la posición pedida no existe en la lista","ZeroDivisionError"],"correctIndex":2,"feedback":{"correct":"Correcto. Posición inexistente = IndexError. Su primo de los diccionarios (clave inexistente) es KeyError.","incorrect":"Las posiciones son asunto de IndexError; ValueError es de conversiones y KeyError de claves de diccionario."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un programa de 10 líneas lanza un error en la línea 3 (sin protección alguna). ¿Qué pasa con las líneas 4 a 10?","options":["Se ejecutan igual","No se ejecutan: el error DETIENE el programa en ese punto","Se ejecutan en orden inverso","Se ejecutan la próxima vez"],"correctIndex":1,"feedback":{"correct":"Correcto. Sin manejo, el error frena todo ahí mismo — por eso importa aprender a manejarlos.","incorrect":"Un error sin manejar detiene el programa al instante: nada posterior corre. try/except (siguiente lección) cambia eso."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Errores con nombre","points":["Un error sin manejar DETIENE el programa y publica un traceback.","El traceback da tipo, mensaje y línea: léelo de abajo hacia arriba.","La familia: ValueError (conversión), TypeError (mezclar tipos), IndexError (posición), KeyError (clave), ZeroDivisionError (÷0).","Cada error tiene nombre técnico: conocerlos es poder esperarlos.","Leer tracebacks con calma es la habilidad #1 de depuración — se entrena desde hoy."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm06-l01-errores-con-nombre';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · try/except: el paracaídas
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Esperar el golpe y amortiguarlo","body":"try/except es el paracaídas: en el bloque try va el código QUE PUEDE FALLAR; en el except, qué hacer SI falla. Si el try sale bien, el except se salta completo; si algo revienta dentro del try, el programa NO se detiene — salta al except y continúa. La regla profesional: captura el error ESPECÍFICO — except ValueError: — y no un except pelado que atrape cualquier cosa: los errores que no esperabas deben seguir viéndose, porque son avisos de bugs reales. Y mantén el try PEQUEÑO: solo la línea arriesgada, no el programa entero — así sabes exactamente qué estás protegiendo."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"La deuda del módulo 1, pagada","code":"respuesta = \"treinta y ocho\"   # lo que tecleó el usuario\n\ntry:\n    temperatura = float(respuesta)\n    print(f\"Registrada: {temperatura} °C\")\nexcept ValueError:\n    print(\"Eso no es un número: usa el formato 38.6\")\n\nprint(\"El programa sigue vivo\")","result":{"columns":["CONSOLA"],"rows":[["Eso no es un número: usa el formato 38.6"],["El programa sigue vivo"]],"note":"float() lanzó su ValueError… y el except lo atrapó: mensaje claro y el programa continúa. El print del try no corrió porque el error saltó antes."},"caption":"El mismo caso que te presentamos como BONUS en el módulo 1: hoy tiene paracaídas. Nota la última línea: la vida sigue."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: el promedio a prueba de ceros","body":"Tu turno: tu función promedio(suma, cantidad) del módulo 5 tiene un talón de Aquiles — si cantidad es 0 (un turno sin pacientes), suma / cantidad lanza ZeroDivisionError. Define promedio_seguro(suma, cantidad) que intente la división con try y, si salta ZeroDivisionError, devuelva 0. Pruébala con promedio_seguro(113.8, 3) y promedio_seguro(0, 0). Resuélvelo antes de mirar la solución."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"def promedio_seguro(suma, cantidad):\n    try:\n        return suma / cantidad\n    except ZeroDivisionError:\n        return 0\n\nprint(f\"Turno normal: {promedio_seguro(113.8, 3):.1f}\")\nprint(f\"Turno vacío:  {promedio_seguro(0, 0):.1f}\")","result":{"columns":["CONSOLA"],"rows":[["Turno normal: 37.9"],["Turno vacío:  0.0"]],"note":"Dos return: el del try entrega la división cuando se puede; el del except entrega el 0 de emergencia."},"caption":"Una función robusta decide QUÉ devolver cuando el mundo falla — en vez de dejar que el error detenga a quien la llamó."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En un try/except, el código del try se ejecuta SIN errores. ¿Qué pasa con el bloque except?","options":["Se ejecuta también, por si acaso","Se SALTA completo: except solo corre cuando el try falla","Se ejecuta a la mitad","Lanza un error"],"correctIndex":1,"feedback":{"correct":"Correcto. El except es el plan B: sin accidente, no hay paracaídas que abrir.","incorrect":"except solo se ejecuta si algo falla dentro del try; si todo sale bien, se salta entero."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué se prefiere except ValueError: (específico) a un except: pelado que atrape todo?","options":["Porque se escribe más corto","Porque los errores que NO esperabas deben seguir viéndose: son avisos de bugs reales que un except genérico silenciaría","Porque el except pelado es más lento","No hay diferencia"],"correctIndex":1,"feedback":{"correct":"Correcto. Atrapa lo que esperas y deja hablar a lo que no: silenciar todo esconde bugs.","incorrect":"El except genérico atrapa TAMBIÉN los errores inesperados y los esconde — y un bug escondido es un bug eterno. Captura específico."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — try/except","points":["try envuelve el código que puede fallar; except dice qué hacer si falla.","Si el try sale bien, el except se salta; si falla, el programa NO se detiene: salta al except y sigue.","Captura el error ESPECÍFICO (except ValueError:): lo inesperado debe seguir viéndose.","Mantén el try pequeño: solo la línea arriesgada.","Una función robusta usa try/except para decidir qué devolver cuando algo falla (promedio_seguro)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm06-l02-try-except';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Reintentar hasta que esté bien
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El patrón de la entrada robusta","body":"Rechazar el dato malo está bien; VOLVER A PEDIRLO está mejor. El patrón junta dos viejos conocidos: un while que repite MIENTRAS no tengamos un dato válido, y un try/except que intenta la conversión en cada vuelta. La pieza clave es una variable BANDERA (un bool): valido = False antes del bucle, while not valido: para seguir insistiendo, y valido = True DENTRO del try, justo después de la línea arriesgada — si la conversión falla, esa línea nunca corre, la bandera sigue en False y el bucle pide de nuevo. Este patrón está en todos los formularios serios del mundo: el usuario se equivoca, el programa explica y re-pregunta, nadie se estrella."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Pedir la temperatura hasta que sea un número","code":"valido = False\n\nwhile not valido:\n    respuesta = input(\"Temperatura: \")\n    try:\n        temperatura = float(respuesta)\n        valido = True          # solo se llega aquí si float() funcionó\n    except ValueError:\n        print(\"Número inválido — ejemplo válido: 38.6\")\n\nprint(f\"Registrada: {temperatura} °C\")","result":{"columns":["CONSOLA"],"rows":[["Temperatura: treinta y ocho"],["Número inválido — ejemplo válido: 38.6"],["Temperatura: 38.6"],["Registrada: 38.6 °C"]],"note":"Primera vuelta: float falló, la bandera quedó en False, el bucle insistió. Segunda vuelta: conversión exitosa, bandera en True, bucle cerrado."},"caption":"while + try + bandera: el trío de la entrada robusta. El usuario puede equivocarse mil veces; el programa, ninguna."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En el patrón de reintento, ¿por qué valido = True va DENTRO del try, después de la conversión?","options":["Por estética","Porque si la conversión falla, el error salta ANTES de esa línea: la bandera solo se enciende cuando la conversión de verdad funcionó","Porque el while lo exige","Podría ir en cualquier parte"],"correctIndex":1,"feedback":{"correct":"Correcto. El error interrumpe el try en la línea que falló: la bandera queda apagada y el bucle re-pregunta.","incorrect":"La posición es el truco: si float() falla, el salto al except ocurre ANTES de valido = True — la bandera solo se enciende con éxito real."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué aporta el while al patrón de entrada robusta que un try/except solo no da?","options":["Velocidad","La REINSISTENCIA: rechazar el dato malo Y volver a pedirlo, las veces que haga falta","Mejores mensajes de error","Nada, es decorativo"],"correctIndex":1,"feedback":{"correct":"Correcto. try/except amortigua UNA caída; el while convierte la caída en 'inténtalo de nuevo'.","incorrect":"El try solo maneja un intento; el while repite hasta conseguir un dato válido: esa persistencia es el patrón completo."}}$j$),
  (5, 'resumen', $j${"title":"Resumen — Reintentar","points":["Entrada robusta = while (insistir) + try/except (amortiguar) + bandera bool (saber cuándo parar).","valido = True va DENTRO del try, tras la línea arriesgada: solo se enciende con éxito real.","Si la conversión falla, el except explica y el bucle re-pregunta.","El usuario puede equivocarse mil veces; el programa no se cae ninguna.","Este patrón vive en todos los formularios del mundo real."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm06-l03-reintentar';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Validar datos sucios
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Los datos del mundo real llegan sucios","body":"Hasta hoy tus datos fueron limpios porque los escribimos nosotros. El mundo real no es así: registros VACÍOS (\"\"), números con formato raro (\"36,8\" con coma en vez de punto), valores ABSURDOS que sí se convierten (una temperatura de 380 es un float perfectamente válido… y un paciente imposible). Tu defensa tiene dos herramientas y cada una caza lo suyo: try/except atrapa lo que REVIENTA (conversiones imposibles); el if valida lo que NO revienta pero está MAL (vacíos, rangos absurdos — las reglas del negocio). La regla profesional: valida temprano y falla claro — un dato malo detectado en la puerta cuesta un mensaje; colado hasta el análisis, cuesta un diagnóstico equivocado. En el próximo módulo leerás archivos REALES de la clínica… y traen exactamente estas sorpresas."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"La puerta de entrada con doble filtro","code":"lectura = \"380\"   # se convierte bien… pero es imposible\n\nif lectura == \"\":\n    print(\"Registro vacío: se omite\")\nelse:\n    try:\n        temperatura = float(lectura)\n        if 30 <= temperatura <= 45:\n            print(f\"Aceptada: {temperatura} °C\")\n        else:\n            print(f\"Fuera de rango humano: {temperatura} — revisar registro\")\n    except ValueError:\n        print(f\"Formato inválido: '{lectura}'\")","result":{"columns":["CONSOLA"],"rows":[["Fuera de rango humano: 380.0 — revisar registro"]],"note":"El try no protestó — 380 ES un número. Fue el if de rango quien lo cazó: cada filtro atrapa lo suyo."},"caption":"El doble filtro: try para lo que revienta, if para lo que miente. 30 <= x <= 45 es un encadenado de comparadores: Python lo permite y se lee de corrido."}$j$),
  (3, 'texto', $j${"title":"Mini-reto: la edad con doble filtro","body":"Tu turno: la edad del paciente llega como cadena en la variable dato. Escribe la defensa completa: (1) si dato es la cadena vacía, imprime Registro vacío; (2) si no, intenta convertir con int() — si salta ValueError, imprime Formato inválido; (3) si convierte, acepta solo edades entre 0 y 120 — fuera de eso, imprime Edad imposible. Prueba mentalmente con \"35\", \"treinta\", \"\" y \"250\". Resuélvelo antes de mirar la solución."}$j$),
  (4, 'ejemplo_codigo', $j${"title":"Solución propuesta — inténtala antes de mirar","code":"dato = \"250\"\n\nif dato == \"\":\n    print(\"Registro vacío\")\nelse:\n    try:\n        edad = int(dato)\n        if 0 <= edad <= 120:\n            print(f\"Edad registrada: {edad}\")\n        else:\n            print(f\"Edad imposible: {edad}\")\n    except ValueError:\n        print(f\"Formato inválido: '{dato}'\")","result":{"columns":["CONSOLA"],"rows":[["Edad imposible: 250"]],"note":"\"250\" pasa el try (es un int válido) y cae en el if de rango. \"treinta\" habría caído en el except; \"\" ni siquiera llega al try."},"caption":"Tres destinos para tres suciedades distintas: vacío, formato y rango. La puerta de la clínica ya no deja pasar cualquier cosa."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La lectura \"380\" se convierte a float sin error, pero es una temperatura imposible. ¿Qué herramienta la detecta?","options":["try/except: toda suciedad es un error","Un if de RANGO (30 <= t <= 45): el dato no revienta, pero viola una regla del negocio — eso es trabajo del if","print","No se puede detectar"],"correctIndex":1,"feedback":{"correct":"Correcto. try caza lo que revienta; el if caza lo que miente. 380 es un float legal y una temperatura ilegal.","incorrect":"float(\"380\") funciona sin error: al try no le consta nada. Los valores absurdos-pero-convertibles se cazan con if de rango."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En términos de defensa de datos, ¿qué significa 'valida temprano, falla claro'?","options":["Validar solo los lunes","Detectar el dato malo EN LA ENTRADA con un mensaje específico — antes de que contamine cálculos y decisiones río abajo","Poner todos los if al final","Ocultar los errores al usuario"],"correctIndex":1,"feedback":{"correct":"Correcto. Un dato malo en la puerta cuesta un mensaje; colado hasta el análisis, cuesta conclusiones equivocadas.","incorrect":"La idea: filtrar en la entrada, con mensajes que digan exactamente qué está mal — no dejar que el dato sucio viaje por el programa."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Datos sucios","points":["El mundo real trae vacíos (\"\"), formatos raros (\"36,8\") y valores absurdos convertibles (380).","try/except caza lo que REVIENTA (conversiones); el if caza lo que MIENTE (vacíos y rangos).","30 <= x <= 45: los comparadores se encadenan y se leen de corrido.","Valida temprano, falla claro: el dato malo se detiene en la puerta, con mensaje específico.","El módulo 7 lee archivos reales de la clínica — y traen exactamente estas sorpresas."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm06-l04-datos-sucios';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Práctica: el registro blindado (motor real)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Del registro de enfermería llegó el turno como una lista de lecturas EN TEXTO — y viene sucio: hay entradas ilegibles y campos vacíos. Tu programa debe procesarlas todas sin caerse ni una vez, contando cuántas son válidas y cuántas no.","instructions":["Dentro del bucle, INTENTA convertir la lectura con float(lectura) usando try.","Si la conversión funciona, suma 1 a validas.","Si salta ValueError, captúralo con except ValueError: y suma 1 a invalidas.","El pass del esqueleto es un relleno que no hace nada: bórralo al escribir tu código. No toques los print finales."],"initialCode":"lecturas = [\"38.2\", \"treinta\", \"39.0\", \"\"]\n\nvalidas = 0\ninvalidas = 0\n\nfor lectura in lecturas:\n    # TODO: try con float(lectura) → suma a validas;\n    #       except ValueError → suma a invalidas\n    pass\n\nprint(f\"Lecturas válidas: {validas}\")\nprint(f\"Lecturas inválidas: {invalidas}\")","validators":["try\\s*:","float\\s*\\(\\s*lectura\\s*\\)","except\\s+ValueError\\s*:","validas\\s*(=\\s*validas\\s*\\+\\s*1|\\+=\\s*1)","invalidas\\s*(=\\s*invalidas\\s*\\+\\s*1|\\+=\\s*1)"],"entradas":[],"salidaEsperada":["Lecturas válidas: 2","Lecturas inválidas: 2"],"mockOutput":{"columns":["CONSOLA"],"rows":[["Lecturas válidas: 2"],["Lecturas inválidas: 2"]],"note":"\"38.2\" y \"39.0\" convierten; \"treinta\" y la cadena vacía lanzan ValueError — y tu programa sobrevivió a las cuatro."},"hints":["Estructura dentro del for: try: / temperatura = float(lectura) / validas = validas + 1, y luego except ValueError: / invalidas = invalidas + 1.","La cadena vacía \"\" también lanza ValueError al convertirse: tu except la cuenta como inválida sin trabajo extra.","¿Sigue el pass ahí? Bórralo: era solo el relleno del esqueleto."],"successMessage":"Registro blindado: cuatro lecturas sucias procesadas sin una sola caída. Esta defensa es exactamente la que usarás en el próximo módulo con los archivos reales de la clínica.","failMessage":"Revisa: try: con float(lectura) y validas sumando dentro; except ValueError: con invalidas sumando — y el pass del esqueleto eliminado."}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm06-l05-practica-blindaje';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La sexta región","body":"Byte llegó a la región de la robustez: diez preguntas guardan el paso. Todo lo viviste: la familia de errores con nombre, el paracaídas try/except, el patrón de reintento y el doble filtro contra datos sucios. Las preguntas que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Un error sin manejar en mitad del programa:","options":["Se ignora y el programa sigue","DETIENE el programa ahí mismo y publica un traceback con tipo, mensaje y línea","Se guarda para después","Borra las variables"],"correctIndex":1,"feedback":{"correct":"Correcto. Sin paracaídas, el accidente frena todo — y el traceback es el informe.","incorrect":"Sin try/except, el error detiene el programa en esa línea; el traceback cuenta qué, por qué y dónde."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"int(\"7b\"), citas[9] (en una lista de 3) y ficha[\"telefono\"] (clave inexistente) lanzan, respectivamente:","options":["ValueError, IndexError, KeyError","TypeError, KeyError, IndexError","ValueError, KeyError, IndexError","Los tres el mismo error"],"correctIndex":0,"feedback":{"correct":"Correcto. Conversión → ValueError; posición → IndexError; clave → KeyError. La familia, cada uno en su casa.","incorrect":"Conversión imposible = ValueError · posición inexistente = IndexError · clave inexistente = KeyError."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Una enfermera registra \"36,8\" (con coma). float(\"36,8\") produce:","options":["36.8 sin problema","ValueError: para float, la coma no es un separador decimal válido","36 a secas","TypeError"],"correctIndex":1,"feedback":{"correct":"Correcto. float espera punto decimal: la coma lo hace inconvertible. Dato sucio clásico de archivos reales.","incorrect":"La coma no vale como decimal para float: \"36,8\" lanza ValueError — de las suciedades más comunes en registros reales."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En un try/except, ¿cuándo se ejecuta el bloque except?","options":["Siempre, después del try","SOLO si algo falla dentro del try; si todo sale bien, se salta completo","Antes del try","Cuando el usuario lo pide"],"correctIndex":1,"feedback":{"correct":"Correcto. El except es el plan B: sin accidente no se abre el paracaídas.","incorrect":"except corre únicamente cuando el try falla; con éxito, se salta entero y el programa sigue."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué un except: pelado (sin tipo) se considera mala práctica?","options":["Porque es más largo de escribir","Porque atrapa TAMBIÉN los errores inesperados y los silencia: bugs reales quedan escondidos","Porque no compila","Porque solo funciona con números"],"correctIndex":1,"feedback":{"correct":"Correcto. Captura lo que esperas (except ValueError:); deja que lo inesperado se vea y se arregle.","incorrect":"El except genérico silencia errores que no anticipaste — y un bug silenciado es un bug eterno. Específico siempre."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"En el patrón de reintento (while not valido + try), la línea valido = True va:","options":["Antes del while","DENTRO del try, después de la conversión: solo se ejecuta si la conversión funcionó","Dentro del except","Después del bucle"],"correctIndex":1,"feedback":{"correct":"Correcto. Si float() falla, el salto al except ocurre antes: la bandera solo se enciende con éxito.","incorrect":"El truco del patrón: al fallar la conversión, el error salta ANTES de valido = True — la bandera queda apagada y el bucle insiste."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Un turno sin pacientes: suma = 0, y calculas suma / len(citas) con la lista vacía. ¿Qué error salta?","options":["ValueError","IndexError","ZeroDivisionError: len(citas) es 0 y dividir entre cero es imposible","Ninguno, da 0"],"correctIndex":2,"feedback":{"correct":"Correcto. len([]) = 0 → división entre cero. Un promedio robusto lo maneja con try/except ZeroDivisionError.","incorrect":"La lista vacía hace len() = 0, y x / 0 lanza ZeroDivisionError — el clásico del promedio sin datos."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"La lectura \"420\" se convierte a float sin protestar, pero como temperatura corporal es imposible. La herramienta que la detecta es:","options":["try/except ValueError","Un if de rango (30 <= t <= 45): el valor convierte bien pero viola la regla del negocio","print","except ZeroDivisionError"],"correctIndex":1,"feedback":{"correct":"Correcto. try caza lo que revienta; el if de rango caza lo que miente.","incorrect":"420 es un float perfectamente convertible: el try no ve nada raro. Los absurdos convertibles son trabajo del if de rango."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"'Valida temprano, falla claro' significa:","options":["Poner los errores en mayúsculas","Detectar el dato malo EN LA ENTRADA, con mensaje específico, antes de que contamine el análisis río abajo","Validar después de calcular","Nunca mostrar errores"],"correctIndex":1,"feedback":{"correct":"Correcto. En la puerta cuesta un mensaje; en el análisis, un diagnóstico equivocado.","incorrect":"La defensa va en la entrada: dato malo detectado temprano + mensaje claro = problema barato."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'para que nada se caiga, ¿envuelvo todo el programa en un único try gigante?' Tu respuesta senior:","options":["Sí, cuanto más grande el try, más protección","No: el try va PEQUEÑO y pegado a la línea arriesgada, capturando el error específico — un try gigante con except genérico silencia bugs y no dice dónde falló nada","Sí, pero solo en producción","Da igual el tamaño"],"correctIndex":1,"feedback":{"correct":"Impecable. Protección quirúrgica: try pequeño + except específico = sabes qué proteges y lo inesperado sigue viéndose.","incorrect":"La respuesta senior: try pequeño y específico. El try gigante convierte el programa en una caja negra donde los bugs desaparecen… hasta que explotan en otro lado."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'python-desde-cero' and l.slug = 'm06-x01-examen';
