-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 042 — SQL con Oracle · m07: Agregación y analítica
-- ═══════════════════════════════════════════════════════════════════
-- (La numeración salta de 019 a 042: el rango 010-019 del curso se
-- agotó; continúa en 042-046 según el plan de la 011.)
-- Cubre la Parte IX en su tramo de agregación: funciones de grupo
-- (COUNT/SUM/AVG/MIN/MAX, COUNT(*) vs COUNT(col) vs DISTINCT, y la
-- precisión de que IGNORAN nulos), GROUP BY con su regla de oro
-- (ORA-00979), HAVING vs WHERE con el orden lógico de ejecución,
-- CTEs (WITH) y funciones de ventana/analíticas: OVER, PARTITION BY,
-- ROW_NUMBER/RANK/DENSE_RANK y el top-N por grupo.
-- Práctica de editor (regex+mockOutput): GROUP BY + HAVING real
-- (ingresos por médico).
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- OJO: SQL con Oracle está PUBLICADO — esta migración sale en vivo.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 011 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm07-agregacion-analitica'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m07-l01-funciones-grupo',  'Funciones de grupo (y sus nulos)',    'leccion',  20, 1),
       ('m07-l02-group-by',         'GROUP BY: una fila por grupo',        'leccion',  20, 2),
       ('m07-l03-having',           'HAVING vs WHERE: el orden de todo',   'leccion',  20, 3),
       ('m07-l04-cte',              'CTEs: consultas con nombre (WITH)',   'leccion',  20, 4),
       ('m07-l05-ventana',          'Funciones de ventana: OVER y PARTITION BY','leccion',20, 5),
       ('m07-l06-ranking',          'Rankings y el top-N por grupo',       'leccion',  20, 6),
       ('m07-l07-practica-grupos',  'Práctica: ingresos por médico',       'practica', 20, 7),
       ('m07-x01-examen',           'Examen: Agregación y analítica',      'examen',   40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm07-agregacion-analitica';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Funciones de grupo (y sus nulos)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"De muchas filas, un número","body":"Hasta ahora cada fila del resultado venía de una fila de la tabla. Las FUNCIONES DE GRUPO cambian la escala: toman MUCHAS filas y devuelven UN valor. Las cinco de cabecera: COUNT cuenta, SUM suma, AVG promedia, MIN y MAX encuentran extremos. Y las tres caras de COUNT que las certificaciones adoran distinguir: COUNT(*) cuenta FILAS, existan nulos o no; COUNT(columna) cuenta solo los valores NO NULOS de esa columna; COUNT(DISTINCT columna) cuenta valores no nulos SIN repetir. Sobre la tabla de citas: COUNT(*) dice cuántas citas hay, COUNT(costo) cuántas tienen costo registrado, y COUNT(DISTINCT paciente_id) cuántos pacientes distintos han venido — tres preguntas distintas, tres números distintos."}$j$),
  (2, 'texto', $j${"title":"La letra chica: los nulos no votan","body":"La precisión que vale dinero: las funciones de grupo IGNORAN los nulos. AVG(costo) no promedia todas las citas — promedia solo las que TIENEN costo: las pendientes de facturar ni suman ni dividen. Si el hospital tiene 100 citas y 20 sin costo, AVG(costo) divide entre 80. ¿Está mal? Depende de la PREGUNTA: '¿cuál es el costo promedio de lo facturado?' → AVG(costo) es correcto; '¿cuánto ingresa en promedio por cita agendada?' → necesitas AVG(NVL(costo, 0)), que convierte los nulos en ceros votantes ANTES de promediar. Dos promedios legítimos, dos números distintos — y elegir sin pensar es cómo un reporte financiero miente sin que nadie mienta. La función no está rota: la pregunta estaba sin afinar."}$j$),
  (3, 'ejemplo_sql', $j${"title":"Tres COUNT, tres respuestas","code":"SELECT COUNT(*)                    AS citas_totales,\n       COUNT(costo)                AS citas_facturadas,\n       COUNT(DISTINCT paciente_id) AS pacientes_distintos,\n       ROUND(AVG(costo), 2)        AS promedio_facturado,\n       ROUND(AVG(NVL(costo, 0)), 2) AS promedio_por_cita\nFROM   citas;","result":{"columns":["CITAS_TOTALES","CITAS_FACTURADAS","PACIENTES_DISTINTOS","PROMEDIO_FACTURADO","PROMEDIO_POR_CITA"],"rows":[["50","47","38","604.26","568"]],"note":"Cincuenta citas, 47 con costo: AVG(costo) divide entre 47 (lo facturado promedia 604.26), AVG(NVL(costo,0)) divide entre 50 (cada cita agendada aporta 568). Ninguno es 'el bueno': cada uno responde SU pregunta."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En una tabla de 100 filas donde 20 tienen la columna costo en nulo, ¿qué devuelven COUNT(*) y COUNT(costo)?","options":["Devuelven exactamente 100 y 100 respectivamente","Devuelven 80 y 80 respectivamente","100 y 80: filas vs valores no nulos","Devuelven 80 y 100 respectivamente"],"correctIndex":2,"feedback":{"correct":"Correcto. El asterisco cuenta existencias; la columna cuenta valores presentes. Veinte nulos separan las dos respuestas.","incorrect":"COUNT(*) = filas (100); COUNT(costo) = valores no nulos (80). La diferencia entre ambos es, de hecho, un detector de nulos."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"AVG(costo) sobre citas con nulos, ¿entre cuántas divide?","options":["Entre todas las filas de la tabla","Entre las filas del último mes","Da un error de ejecución si hay nulos","Solo entre las filas con costo no nulo"],"correctIndex":3,"feedback":{"correct":"Correcto. Los nulos no votan: AVG promedia a los presentes. Para que voten como cero: AVG(NVL(costo, 0)).","incorrect":"Las funciones de grupo saltan los nulos: AVG(costo) es el promedio de lo registrado, no de todo. NVL los convierte en ceros votantes."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Finanzas pregunta '¿cuánto ingresa en promedio por cita AGENDADA?' (las citas sin costo aún no facturan). ¿AVG(costo) o AVG(NVL(costo, 0))?","options":["AVG(NVL(costo, 0)): los nulos votan cero","AVG(costo): es en el fondo exactamente lo mismo","Cualquiera de los dos sirve igual","COUNT(costo) sobre esa columna"],"correctIndex":0,"feedback":{"correct":"Correcto. Dos promedios legítimos para dos preguntas distintas: elegir es entender la pregunta, no la sintaxis.","incorrect":"'Por cita agendada' incluye a las sin costo: NVL las hace votar como cero. AVG(costo) solo promedia lo facturado."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Funciones de grupo","points":["Muchas filas → UN valor: COUNT, SUM, AVG, MIN, MAX.","COUNT(*) cuenta filas · COUNT(col) cuenta no-nulos · COUNT(DISTINCT col) no-nulos sin repetir.","Las funciones de grupo IGNORAN nulos: los pendientes ni suman ni dividen.","AVG(costo) = promedio de lo registrado · AVG(NVL(costo,0)) = promedio con nulos votando como cero.","La función correcta la dicta LA PREGUNTA del negocio, no la sintaxis."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-l01-funciones-grupo';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · GROUP BY: una fila por grupo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Del total único al total por grupo","body":"La lección pasada colapsó la tabla entera en un número. GROUP BY colapsa POR GRUPOS: 'los ingresos, pero POR MÉDICO' — una fila por cada valor distinto de la columna agrupadora, con las funciones de grupo calculadas DENTRO de cada grupo. GROUP BY medico_id parte la tabla de citas en un montón por médico, y el SUM/COUNT/AVG opera montón por montón. Se puede agrupar por VARIAS columnas — GROUP BY medico_id, estado produce una fila por cada combinación médico+estado que exista — y la granularidad del reporte la decide esa lista: más columnas en el GROUP BY, grupos más finos, más filas en el resultado."}$j$),
  (2, 'texto', $j${"title":"La regla de oro (y su error con nombre)","body":"La regla que gobierna todo GROUP BY: cada columna del SELECT debe ser O una función de grupo, O estar EN el GROUP BY. Sin excepciones. ¿Por qué? Si agrupas por médico y pides la columna fecha, ¿CUÁL fecha del montón mostraría Oracle? Hay cincuenta por grupo — la petición es ambigua, y Oracle no adivina: revienta con el error que memorizarás sin querer: ORA-00979, 'not a GROUP BY expression'. Cuando lo veas, la pregunta correcta no es 'cómo lo callo' sino '¿qué quería yo?': ¿la fecha MÁXIMA del grupo (MAX(fecha))? ¿agrupar TAMBIÉN por fecha (agregarla al GROUP BY)? El error señala una decisión sin tomar, no un capricho del motor."}$j$),
  (3, 'ejemplo_sql', $j${"title":"El tablero por médico y estado","code":"SELECT medico_id,\n       estado,\n       COUNT(*)              AS citas,\n       SUM(NVL(costo, 0))    AS ingresos\nFROM   citas\nGROUP  BY medico_id, estado\nORDER  BY medico_id, estado;","result":{"columns":["MEDICO_ID","ESTADO","CITAS","INGRESOS"],"rows":[["3","atendida","18","12400"],["3","cancelada","2","0"],["5","atendida","15","9800"],["5","no_asistio","3","950"]],"note":"Una fila por combinación médico+estado: la Dra. Ríos (3) atendió 18 y le cancelaron 2. Las dos columnas sin función de grupo (medico_id, estado) están AMBAS en el GROUP BY — la regla de oro, cumplida."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"SELECT medico_id, fecha, COUNT(*) FROM citas GROUP BY medico_id truena con ORA-00979. ¿Por qué?","options":["Le falta un alias a la consulta","fecha no se agrega ni se agrupa","COUNT no acepta el asterisco (*)","El GROUP BY va antes que el FROM"],"correctIndex":1,"feedback":{"correct":"Correcto. La regla de oro: cada columna del SELECT es agregada o agrupadora. La fecha suelta es una pregunta ambigua.","incorrect":"ORA-00979 = columna en el SELECT que ni se agrega ni se agrupa. ¿Querías MAX(fecha)? ¿O agrupar también por fecha? El error pide esa decisión."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué produce GROUP BY medico_id, estado?","options":["Una sola fila por cada médico","Una sola fila por cada estado","Una fila por combinación médico+estado","Una única fila con todos los totales"],"correctIndex":2,"feedback":{"correct":"Correcto. La lista del GROUP BY define la granularidad: cada combinación real se vuelve un grupo con sus propios agregados.","incorrect":"Agrupar por dos columnas parte los datos por parejas médico+estado: la granularidad del reporte vive en esa lista."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Al ver ORA-00979 ('not a GROUP BY expression'), ¿cuál es la reacción profesional?","options":["Quitar el GROUP BY completo, sin más","Reiniciar la sesión y volver a intentar","Agregar la columna al GROUP BY sin pensar","Preguntarse qué se quería de esa columna"],"correctIndex":3,"feedback":{"correct":"Correcto. Agregarla al GROUP BY 'para que jale' cambia la granularidad del reporte en silencio: primero se decide la intención.","incorrect":"Callar el error sin decidir (agregando la columna por reflejo) multiplica los grupos y cambia los números. La intención primero."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — GROUP BY","points":["GROUP BY parte la tabla en grupos: una fila de resultado por grupo, con los agregados calculados adentro.","La lista del GROUP BY define la GRANULARIDAD: más columnas, grupos más finos.","Regla de oro: toda columna del SELECT es función de grupo O está en el GROUP BY.","ORA-00979 = una columna que ni se agrega ni se agrupa: una decisión sin tomar.","Corregirlo por reflejo cambia la granularidad en silencio: decide la intención primero."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-l02-group-by';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · HAVING vs WHERE: el orden de todo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Dos aduanas, dos momentos","body":"'Muéstrame los médicos con MÁS de 10 citas atendidas.' El 'atendidas' filtra FILAS (antes de agrupar); el 'más de 10' filtra GRUPOS (después de contar). Dos aduanas: WHERE filtra filas ANTES de que el GROUP BY las agrupe — las canceladas ni entran al conteo; HAVING filtra grupos DESPUÉS de agregar — los médicos que no llegaron a 10 desaparecen del reporte. Por eso el WHERE no puede usar funciones de grupo (WHERE COUNT(*) > 10 revienta: en ese momento aún no se ha contado nada) y el HAVING sí. La firma completa: WHERE para condiciones de FILA, HAVING para condiciones de AGREGADO."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Las dos aduanas trabajando juntas","code":"SELECT medico_id,\n       COUNT(*)           AS atendidas,\n       SUM(NVL(costo, 0)) AS ingresos\nFROM   citas\nWHERE  estado = 'atendida'          -- aduana de FILAS (antes de agrupar)\nGROUP  BY medico_id\nHAVING COUNT(*) > 10                -- aduana de GRUPOS (después de contar)\nORDER  BY ingresos DESC;","result":{"columns":["MEDICO_ID","ATENDIDAS","INGRESOS"],"rows":[["3","18","12400"],["5","15","9800"]],"note":"El WHERE dejó fuera canceladas y no-asistencias ANTES de contar; el GROUP BY agrupó lo que sobrevivió; el HAVING descartó a los médicos de 10 o menos; el ORDER BY ordenó lo que quedó. Cuatro cláusulas, cuatro momentos."}}$j$),
  (3, 'texto', $j${"title":"El orden lógico: la consulta se ejecuta al revés de como se lee","body":"El secreto que ordena todas las piezas del curso: la consulta se ESCRIBE empezando por SELECT, pero se EJECUTA (lógicamente) en otro orden — FROM (y sus JOINs: armar la fuente) → WHERE (filtrar filas) → GROUP BY (agrupar) → HAVING (filtrar grupos) → SELECT (proyectar y calcular) → ORDER BY (ordenar al final). Este mapa explica misterios acumulados: por qué el WHERE no ve los agregados (corre antes), por qué el ORDER BY sí puede usar alias del SELECT (corre después), y por qué el HAVING vive entre el GROUP BY y el SELECT. Cuando una consulta 'no tiene sentido', recórrela en orden de EJECUCIÓN, no de lectura: los errores se explican solos."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué WHERE COUNT(*) > 10 revienta, pero HAVING COUNT(*) > 10 funciona?","options":["WHERE corre antes de agrupar; HAVING después","Es una regla completamente arbitraria del motor","COUNT solo funciona junto con el HAVING","A la consulta simplemente le falta un alias"],"correctIndex":0,"feedback":{"correct":"Correcto. Cada aduana en su momento: filas antes de agrupar (WHERE), grupos después de agregar (HAVING).","incorrect":"El orden lógico manda: WHERE corre antes del GROUP BY (sin conteos aún); HAVING corre después (conteos listos)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"El orden LÓGICO de ejecución de una consulta es…","options":["SELECT → FROM → WHERE → GROUP BY (se lee)","FROM → WHERE → GROUP BY → HAVING → SELECT","ORDER BY → SELECT → FROM, en ese orden","Aleatorio: lo decide el optimizador"],"correctIndex":1,"feedback":{"correct":"Correcto. Fuente, filas, grupos, filtro de grupos, proyección, orden: el mapa que explica qué cláusula ve qué cosa.","incorrect":"La consulta se escribe desde SELECT pero se ejecuta desde FROM: ese desfase explica por qué WHERE no ve agregados y ORDER BY sí ve alias."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"'Médicos con más de 10 citas ATENDIDAS': ¿dónde va cada condición?","options":["Ambas condiciones van en el WHERE","Ambas condiciones van en el HAVING","estado en WHERE; COUNT(*) > 10 en HAVING","El estado en HAVING y el conteo en WHERE"],"correctIndex":2,"feedback":{"correct":"Correcto. Poner el estado en el HAVING también 'funciona' a veces — pero filtra tarde y cuenta de más: cada condición en su aduana.","incorrect":"La condición de fila (estado) va antes de agrupar: WHERE. La condición sobre el conteo solo puede evaluarse después: HAVING."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — HAVING y el orden","points":["WHERE filtra FILAS antes de agrupar · HAVING filtra GRUPOS después de agregar.","WHERE no puede usar funciones de grupo (aún no existen); HAVING sí.","Orden lógico: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY.","El desfase escribir/ejecutar explica qué cláusula ve qué cosa (alias, agregados).","Consulta sin sentido → recórrela en orden de EJECUCIÓN, no de lectura."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-l03-having';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · CTEs: consultas con nombre (WITH)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La inline view, con nombre y modales","body":"Las inline views del módulo pasado funcionan, pero anidadas se vuelven cebollas: para leer la consulta hay que excavar desde el paréntesis más profundo. La CTE (Common Table Expression) las endereza: WITH nombre AS (SELECT …) define la consulta intermedia ARRIBA, con nombre propio, y la consulta principal la usa como si fuera una tabla. Se encadenan separadas por coma — WITH a AS (…), b AS (…) — y cada una puede usar a las anteriores: la lógica compleja se cuenta como una historia, paso a paso, en el orden en que se piensa. Mismo poder que la inline view, legibilidad de otra liga; el motor las trata esencialmente igual — la CTE es para el HUMANO que leerá la consulta en seis meses. Ese humano suele ser tu yo del futuro."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La historia en dos pasos","code":"WITH ingresos_por_medico AS (\n  SELECT medico_id,\n         SUM(NVL(costo, 0)) AS ingresos\n  FROM   citas\n  WHERE  estado = 'atendida'\n  GROUP  BY medico_id\n)\nSELECT m.nombre,\n       i.ingresos\nFROM   ingresos_por_medico i\nJOIN   medicos m ON m.medico_id = i.medico_id\nORDER  BY i.ingresos DESC;","result":{"columns":["NOMBRE","INGRESOS"],"rows":[["Dra. Ríos","12400"],["Dr. Salas","9800"],["Dra. Peña","7350"]],"note":"Paso 1 (la CTE): calcular los ingresos por médico. Paso 2 (la principal): ponerles nombre y ordenar. La misma consulta como inline view anidada existiría — pero se leería desde adentro hacia afuera, como una cebolla."}}$j$),
  (3, 'texto', $j${"title":"Cuándo la CTE es la herramienta","body":"Tres señales de que toca WITH. UNO: la inline view se anidaría más de un nivel — cada nivel extra de paréntesis es un piso menos de legibilidad. DOS: el mismo resultado intermedio se usa DOS VECES en la consulta (compararlo consigo mismo, joinearlo dos veces): la CTE se define una vez y se referencia por nombre, sin duplicar el bloque. TRES: la consulta expresa un PROCESO ('primero calculo X, luego lo cruzo con Y, al final filtro Z') — las CTEs encadenadas narran ese proceso en orden. La cultura del equipo lo agradece: una consulta de reporte seria en el mundo real casi siempre abre con WITH, y el revisor lee los nombres de las CTEs como el índice de un documento."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es una CTE (WITH nombre AS (…)) y en qué se diferencia de una inline view?","options":["Una tabla completamente nueva guardada en el esquema","Un simple índice temporal interno","Una vista creada con CREATE VIEW","Una consulta intermedia con nombre, arriba"],"correctIndex":3,"feedback":{"correct":"Correcto. La CTE es la inline view enderezada: nombre arriba, historia en orden, cero objetos creados.","incorrect":"La CTE vive solo en su consulta (no es CREATE VIEW ni tabla): es la subconsulta del FROM, con nombre y puesta al inicio."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un mismo cálculo intermedio se necesita DOS veces dentro de una consulta. ¿Por qué la CTE gana a la inline view?","options":["Se define una vez y se referencia por nombre","Porque es siempre bastante más rápida","Porque las inline views no se joinean","Porque la CTE no necesita declarar ningún alias"],"correctIndex":0,"feedback":{"correct":"Correcto. Un solo lugar que mantener: si el cálculo cambia, cambia una vez. La copia duplicada es un bug esperando fecha.","incorrect":"La ventaja es la reutilización por nombre: el mismo bloque duplicado en dos inline views tarde o temprano se desincroniza."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cómo se encadenan varias CTEs y qué puede usar cada una?","options":["Se unen con UNION entre ellas","Por coma; cada una usa a las anteriores","Con paréntesis anidados uno en otro","No se pueden encadenar de ningún modo"],"correctIndex":1,"feedback":{"correct":"Correcto. WITH a AS (…), b AS (… usa a …): la consulta cuenta su proceso en el orden en que se piensa.","incorrect":"WITH a AS (…), b AS (…): comas entre CTEs, y las posteriores ven a las anteriores — el proceso narrado en orden."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — CTEs","points":["WITH nombre AS (SELECT …): la consulta intermedia con nombre, definida ARRIBA.","Mismo poder que la inline view; legibilidad de otra liga — es para el humano de dentro de seis meses.","Se encadenan por comas y cada una puede usar a las anteriores: la lógica como historia.","Señales de uso: anidamiento creciente, resultado usado dos veces, consulta que narra un proceso.","No crea objetos: vive y muere con su consulta."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-l04-cte';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Funciones de ventana: OVER y PARTITION BY
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Agregar sin colapsar","body":"El GROUP BY tiene un precio: COLAPSA las filas — pides ingresos por médico y pierdes las citas individuales. ¿Y si necesitas AMBOS a la vez: cada cita junto al total de su médico, para calcular qué porcentaje aporta? Esa es la especialidad de las FUNCIONES DE VENTANA (o analíticas): un agregado con la cláusula OVER — SUM(costo) OVER (PARTITION BY medico_id) — que calcula el total del grupo y lo escribe EN CADA FILA, sin colapsar nada. PARTITION BY define el grupo (como el GROUP BY, pero sin fusionar filas); OVER () a secas usa la tabla entera como grupo. La diferencia con GROUP BY cabe en una frase: GROUP BY responde preguntas SOBRE grupos; la ventana responde preguntas sobre CADA FILA en el contexto de su grupo."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Cada cita frente al total de su médico","code":"SELECT cita_id,\n       medico_id,\n       costo,\n       SUM(costo) OVER (PARTITION BY medico_id) AS total_medico,\n       ROUND(100 * costo / SUM(costo) OVER (PARTITION BY medico_id), 1) AS pct\nFROM   citas\nWHERE  estado = 'atendida';","result":{"columns":["CITA_ID","MEDICO_ID","COSTO","TOTAL_MEDICO","PCT"],"rows":[["517","3","950","12400","7.7"],["523","3","350","12400","2.8"],["544","5","820","9800","8.4"]],"note":"Las citas siguen ahí — nada se colapsó — pero cada una carga el total de SU médico y el porcentaje que aporta. Con GROUP BY esto exigiría un join de la tabla contra su propio agregado; la ventana lo hace en una pasada."}}$j$),
  (3, 'texto', $j${"title":"El detalle y el contexto, juntos","body":"Este patrón — cada fila con su contexto — resuelve preguntas que antes dolían: ¿esta cita está por encima del promedio de su médico? (costo > AVG(costo) OVER (PARTITION BY medico_id) — bueno, casi: las ventanas no pueden ir en el WHERE, porque el orden lógico las calcula en el SELECT; se filtran desde una CTE, y ahí las dos lecciones anteriores se dan la mano). ¿Cuánto acumula la caja al cierre de cada día? (SUM con OVER y un ORDER BY interno que verás en la próxima lección). La regla mental para elegir herramienta: si el reporte pierde filas de detalle y está bien perderlas → GROUP BY; si cada fila necesita saber algo de su grupo → ventana. Y como las ventanas se calculan tarde (en el SELECT), el WHERE de su misma consulta no puede verlas: filtrar por una ventana = envolverla en una CTE y filtrar afuera."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es LA diferencia entre SUM(costo) con GROUP BY y SUM(costo) OVER (PARTITION BY …)?","options":["El resultado numérico es siempre distinto","La ventana solo funciona con fechas","GROUP BY colapsa; la ventana conserva filas","OVER es un sinónimo directo de GROUP BY"],"correctIndex":2,"feedback":{"correct":"Correcto. Mismo agregado, distinta forma: grupos colapsados vs detalle con contexto.","incorrect":"La ventana no fusiona filas: cada cita conserva su identidad Y conoce el total de su grupo. Ese es todo el superpoder."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En una función de ventana, ¿qué papel juega PARTITION BY?","options":["Ordena el resultado final de la consulta","Elimina los duplicados del resultado","Crea particiones físicas reales en disco","Define el grupo de cálculo, sin colapsar"],"correctIndex":3,"feedback":{"correct":"Correcto. PARTITION BY medico_id = 'calcula esto por médico, y escríbelo en cada fila del médico'.","incorrect":"PARTITION BY delimita la ventana (el grupo de cálculo). OVER () sin partición usa toda la tabla como grupo."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres SOLO las citas cuyo costo supere el promedio de su médico, pero WHERE costo > AVG(costo) OVER (…) revienta. ¿Por qué, y cuál es la salida?","options":["La ventana nace en el SELECT: filtra en CTE","Las ventanas no existen realmente dentro de Oracle","A la consulta le falta un GROUP BY final","AVG no acepta la cláusula OVER nunca"],"correctIndex":0,"feedback":{"correct":"Correcto. El orden lógico manda otra vez: la ventana nace en el SELECT, así que se filtra desde afuera (CTE) — las lecciones se dan la mano.","incorrect":"El WHERE corre antes que el SELECT donde nace la ventana: envuélvela en una CTE y filtra la columna calculada desde afuera."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Funciones de ventana","points":["Agregado + OVER = calcular sobre el grupo SIN colapsar filas: detalle y contexto juntos.","PARTITION BY define el grupo de cálculo; OVER () a secas = la tabla entera.","GROUP BY responde sobre GRUPOS; la ventana, sobre CADA FILA en su contexto.","Las ventanas nacen en el SELECT: el WHERE no las ve — se filtran envueltas en una CTE.","El patrón estrella: cada fila con el total/promedio de su grupo (porcentajes, comparaciones)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-l05-ventana';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Rankings y el top-N por grupo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Tres jueces para el mismo podio","body":"Dentro del OVER cabe también un ORDER BY — y con él llegan las funciones de RANKING, que numeran filas según un orden. Son tres jueces con criterios distintos ante un EMPATE: ROW_NUMBER reparte números ÚNICOS sí o sí (1, 2, 3, 4 — a los empatados los desempata arbitrariamente); RANK respeta el empate y SALTA lugares (1, 2, 2, 4: dos medallas de plata, nadie de bronce); DENSE_RANK respeta el empate SIN saltar (1, 2, 2, 3). La firma completa: RANK() OVER (PARTITION BY medico_id ORDER BY costo DESC) — un podio POR MÉDICO, ordenado por costo. Elegir juez es una decisión de negocio: ¿los empatados comparten lugar? ¿el siguiente hereda el hueco? En un concurso importa; en un reporte de 'la cita más cara', también."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El top-1 por grupo: la receta completa","code":"WITH ranking AS (\n  SELECT cita_id,\n         medico_id,\n         costo,\n         ROW_NUMBER() OVER (PARTITION BY medico_id\n                            ORDER BY costo DESC) AS rn\n  FROM   citas\n  WHERE  estado = 'atendida'\n)\nSELECT cita_id, medico_id, costo\nFROM   ranking\nWHERE  rn = 1;","result":{"columns":["CITA_ID","MEDICO_ID","COSTO"],"rows":[["517","3","950"],["544","5","820"],["561","7","780"]],"note":"LA cita más cara de CADA médico, en una consulta: la ventana numera dentro de cada partición (rn), la CTE le da nombre al resultado, y el filtro rn = 1 se queda con el podio. Cambia rn = 1 por rn <= 3 y tienes el top-3 por grupo."}}$j$),
  (3, 'texto', $j${"title":"La receta que resuelve media analítica","body":"Memoriza el patrón del ejemplo, porque es LA receta del top-N por grupo — una de las preguntas más frecuentes en entrevistas de SQL: ventana de ranking con PARTITION BY (el grupo) y ORDER BY (el criterio) dentro de una CTE, y el filtro rn <= N afuera (afuera porque, como ya sabes, el WHERE no ve las ventanas de su propia consulta). Variantes del mismo esqueleto: 'el último registro de cada paciente' (PARTITION BY paciente_id ORDER BY fecha DESC, rn = 1), 'los 3 medicamentos más caros por categoría', 'la primera compra de cada cliente'. Y el matiz del juez: con ROW_NUMBER un empate en el primer lugar deja UNA fila (desempate arbitrario); con RANK, un empate deja DOS filas con rn = 1. Si los empates importan al negocio, el juez se elige con intención."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Cuatro filas ordenadas por costo, las dos primeras EMPATADAS. ¿Qué numeración da cada juez: ROW_NUMBER, RANK, DENSE_RANK?","options":["Los tres dan 1,2,3,4 exactamente por igual siempre","1,2,3,4 · 1,1,3,4 · 1,1,2,3 (por empates)","1,1,1,1 · 1,2,3,4 · 4,3,2,1 distinto","Los tres dan siempre 1,1,2,2 igual"],"correctIndex":1,"feedback":{"correct":"Correcto. Único-sí-o-sí, empate-con-hueco, empate-sin-hueco: tres políticas para el mismo podio.","incorrect":"ROW_NUMBER nunca repite (1,2,3,4); RANK repite y salta (1,1,3,4); DENSE_RANK repite sin saltar (1,1,2,3)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La receta profesional del 'top-3 por grupo' es…","options":["Un GROUP BY con un LIMIT 3 al final","Tres consultas separadas con UNION","Ranking en CTE y WHERE rn <= 3 afuera","Un ORDER BY combinado con DISTINCT"],"correctIndex":2,"feedback":{"correct":"Correcto. El esqueleto que resuelve media analítica: numerar por partición adentro, filtrar el número afuera.","incorrect":"El top-N por grupo pide numerar DENTRO de cada grupo (ventana con PARTITION BY) y filtrar el número desde una CTE."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En 'la cita más cara de cada médico', dos citas de la Dra. Ríos empatan en el primer lugar. ¿Qué diferencia hace el juez elegido?","options":["No hace ninguna diferencia real","RANK dejará una sola fila arriba","DENSE_RANK las elimina a las dos","ROW_NUMBER deja una; RANK deja dos"],"correctIndex":3,"feedback":{"correct":"Correcto. El filtro rn = 1 devuelve una o dos filas según el juez: la elección es de negocio, no de sintaxis.","incorrect":"Con ROW_NUMBER el empate se rompe arbitrariamente (una fila); con RANK ambas empatadas llevan el 1 (dos filas). Elegir juez = decidir qué pasa con los empates."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Rankings","points":["ORDER BY dentro del OVER habilita el ranking por partición.","ROW_NUMBER: únicos sí o sí · RANK: empata y salta (1,1,3) · DENSE_RANK: empata sin saltar (1,1,2).","LA receta del top-N por grupo: ranking en CTE + WHERE rn <= N afuera.","Variantes del mismo esqueleto: el último registro de cada X, la primera compra, el top-3 por categoría.","Los empates son decisión de negocio: el juez se elige con intención."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-l06-ranking';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Práctica: ingresos por médico (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"La dirección quiere el tablero de productividad: por cada médico, cuántas citas tiene y cuánto ha ingresado — pero solo los médicos con actividad real (3 citas o más). Escribe la consulta completa sobre la tabla citas (medico_id, costo con posibles nulos).","instructions":["Proyecta: medico_id, COUNT(*) con alias num_citas, y SUM(NVL(costo, 0)) con alias ingresos (usa AS en ambos).","FROM citas.","Agrupa por medico_id.","Conserva solo los grupos con COUNT(*) >= 3 (la cláusula que filtra grupos).","Ordena por ingresos de mayor a menor (DESC)."],"initialCode":"-- Tablero de productividad por médico (mínimo 3 citas),\n-- ordenado por ingresos.\n\nSELECT medico_id\nFROM   citas;","validators":["select\\s+medico_id\\s*,\\s*count\\s*\\(\\s*\\*\\s*\\)\\s+as\\s+num_citas\\s*,\\s*sum\\s*\\(\\s*nvl\\s*\\(\\s*costo\\s*,\\s*0\\s*\\)\\s*\\)\\s+as\\s+ingresos","from\\s+citas","group\\s+by\\s+medico_id","having\\s+count\\s*\\(\\s*\\*\\s*\\)\\s*>=\\s*3","order\\s+by\\s+ingresos\\s+desc"],"mockOutput":{"columns":["MEDICO_ID","NUM_CITAS","INGRESOS"],"rows":[["3","20","12400"],["5","18","9800"],["7","11","7350"]],"note":"El tablero completo: cada médico con su conteo y sus ingresos (nulos votando como cero), los de menos de 3 citas fuera del reporte, y el que más ingresa arriba."},"hints":["La lista del SELECT lleva las dos agregadas con su alias: COUNT(*) AS num_citas, SUM(NVL(costo, 0)) AS ingresos.","El filtro de grupos NO es WHERE: es HAVING COUNT(*) >= 3, y va después del GROUP BY medico_id.","Cierra con ORDER BY ingresos DESC. Orden completo: SELECT → FROM → GROUP BY → HAVING → ORDER BY."],"successMessage":"Tablero entregado: agregados con nulos domados (NVL), regla de oro del GROUP BY cumplida, HAVING filtrando grupos y orden explícito. Esta consulta es el pan de cada día del análisis de datos — y ya es tuya.","failMessage":"Revisa las cinco piezas: SELECT medico_id, COUNT(*) AS num_citas, SUM(NVL(costo, 0)) AS ingresos · FROM citas · GROUP BY medico_id · HAVING COUNT(*) >= 3 · ORDER BY ingresos DESC."}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-l07-practica-grupos';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La novena región","body":"Byte dejó de mirar filas: ahora ve PATRONES — totales, promedios, podios y porcentajes. Once preguntas custodian esta región: los agregados y sus nulos, las dos aduanas, el orden de todo, y las ventanas que no colapsan nada. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"En una tabla con filas cuyo costo a veces es nulo: COUNT(*), COUNT(costo) y COUNT(DISTINCT costo) devuelven…","options":["Filas · valores no nulos · no nulos únicos","Los tres devuelven exactamente el mismo número","Solo funcionan bien cuando no hay nulos","El tercero da un error de ejecución"],"correctIndex":0,"feedback":{"correct":"Correcto. Existencias, presencias y presencias únicas: la diferencia entre los tres COUNT es un diagnóstico gratis.","incorrect":"COUNT(*) cuenta filas; COUNT(col) salta nulos; DISTINCT además des-duplica. Tres números, tres significados."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"AVG(costo) reporta 604 pero finanzas insiste en que el promedio por cita es 568. ¿La explicación más probable?","options":["El área de finanzas calculó mal","Hay costos nulos: AVG los ignora al dividir","Oracle redondea de una forma bastante distinta","La tabla de citas está corrupta"],"correctIndex":1,"feedback":{"correct":"Correcto. Dos promedios legítimos para dos preguntas: la discrepancia delata a los nulos ignorados, no a un error de nadie.","incorrect":"Las funciones de grupo ignoran nulos: AVG(costo) promedia lo facturado; con NVL los pendientes votan como cero y sale el número de finanzas."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"La regla de oro del GROUP BY (la que ORA-00979 vigila) dice que…","options":["El GROUP BY va siempre al final de todo","Solo se puede agrupar por una columna","Cada columna: agregada o en el GROUP BY","El GROUP BY exige un ORDER BY después"],"correctIndex":2,"feedback":{"correct":"Correcto. Sin la regla, Oracle tendría que adivinar qué fecha (de las 50 del grupo) mostrarte — y no adivina.","incorrect":"ORA-00979 = columna que ni se agrega ni agrupa. La regla de oro: agregada o agrupadora, sin terceras opciones."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál cláusula puede usar funciones de grupo en su condición, y por qué?","options":["El WHERE, porque siempre filtra todo","Ambas cláusulas por igual, sin distinción","El FROM, al armar la fuente de datos","HAVING: corre después del GROUP BY"],"correctIndex":3,"feedback":{"correct":"Correcto. La aduana de grupos trabaja con los conteos ya hechos; la de filas, antes de que existan.","incorrect":"El orden lógico decide: WHERE va antes de agrupar (sin agregados aún); HAVING después (agregados listos)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"El orden LÓGICO de ejecución que explica qué cláusula ve qué cosa:","options":["FROM → WHERE → GROUP BY → HAVING → SELECT","SELECT → WHERE → GROUP BY, tal como se lee arriba","WHERE → FROM → SELECT, en ese orden","GROUP BY → FROM → WHERE, al revés"],"correctIndex":0,"feedback":{"correct":"Correcto. Fuente, filas, grupos, filtro de grupos, proyección, orden — el mapa mental de todo SQL.","incorrect":"La consulta se ejecuta desde FROM, no desde SELECT: ese mapa explica por qué WHERE no ve agregados ni ventanas, y ORDER BY sí ve alias."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo abre una consulta con WITH (CTE) en lugar de anidar inline views?","options":["Nunca: son del todo ilegales juntas","Cuando hay pasos, anidamiento o reuso","Solo con más de diez tablas unidas","Únicamente cuando no hay ningún JOIN"],"correctIndex":1,"feedback":{"correct":"Correcto. La CTE es la inline view enderezada: nombres arriba, historia en orden, cero duplicación.","incorrect":"WITH gana cuando la consulta cuenta un proceso: pasos nombrados en orden, reutilizables, sin excavar paréntesis."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"SUM(costo) OVER (PARTITION BY medico_id) escribe el total del médico en cada fila. ¿Qué habría exigido lograrlo con GROUP BY?","options":["Nada en absoluto: el GROUP BY lo hace igual de bien","Habría exigido un trigger específico","Joinear la tabla contra su propio agregado","Habría exigido usar dos bases distintas"],"correctIndex":2,"feedback":{"correct":"Correcto. Detalle + contexto en una pasada: el GROUP BY colapsa, y recuperar el detalle costaría un self-join contra el agregado.","incorrect":"GROUP BY colapsa las filas: para conservar el detalle habría que joinear la tabla contra su agregado. La ventana evita todo eso."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué no puedes filtrar WHERE rn = 1 en la MISMA consulta donde defines rn como ROW_NUMBER() OVER (…)?","options":["Porque rn es una palabra reservada","Porque ROW_NUMBER en realidad no devuelve números","En realidad sí se puede, siempre","La ventana nace en SELECT; el WHERE va antes"],"correctIndex":3,"feedback":{"correct":"Correcto. El orden lógico una vez más: la ventana no existe cuando el WHERE pregunta por ella. CTE y filtro afuera.","incorrect":"El WHERE corre antes del SELECT donde nace la ventana: por eso la receta del top-N envuelve el ranking en una CTE."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Filas ordenadas con un empate en el segundo lugar: 900, 700, 700, 500. ¿Qué numera RANK y qué numera DENSE_RANK?","options":["RANK: 1,2,2,4 (salta) · DENSE: 1,2,2,3","Ambos numeran igual: 1,2,3,4 sin más","RANK 1,2,2,3 y DENSE_RANK 1,2,2,4","Los dos dan siempre 1,1,2,2 igual"],"correctIndex":0,"feedback":{"correct":"Correcto. El hueco tras el empate es la firma de RANK; DENSE_RANK comprime. ROW_NUMBER, mientras tanto, habría desempatado a la fuerza.","incorrect":"RANK deja hueco tras el empate (1,2,2,4); DENSE_RANK no (1,2,2,3). El juez se elige según qué deben significar los empates."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"La receta canónica de 'el último registro de cada paciente':","options":["Usar simplemente la función MAX(fecha) y ya está","ROW_NUMBER por paciente ORDER fecha, rn=1","Un ORDER BY fecha DESC con DISTINCT","Un GROUP BY por paciente_id y fecha"],"correctIndex":1,"feedback":{"correct":"Correcto. El esqueleto del top-N por grupo, con N=1 y el criterio 'fecha más reciente'. MAX(fecha) daría LA fecha, pero no el registro completo.","incorrect":"MAX(fecha) devuelve solo la fecha; para traer la FILA completa del último registro se numera por partición y se filtra rn = 1."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'tu reporte dice que el promedio de costo es 604, y el tablero del director dice 568. Explica la discrepancia y di cuál número es el correcto.' Tu respuesta senior:","options":["Uno de los dos sistemas tiene un bug seguro","El promedio verdadero es siempre en realidad el más bajo","Ambos valen: uno ignora nulos, otro los cuenta cero","Hay que borrar las citas que no tienen costo"],"correctIndex":2,"feedback":{"correct":"Impecable. Explicaste el mecanismo (nulos ignorados), reconciliaste ambos números y devolviste la decisión al negocio con documentación: análisis senior.","incorrect":"La respuesta senior reconcilia: AVG(costo) vs AVG(NVL(costo,0)) — dos preguntas legítimas, dos números. El 'correcto' lo decide qué pregunta el negocio."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm07-x01-examen';
