-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 043 — SQL con Oracle · m08: Transacciones y seguridad
-- ═══════════════════════════════════════════════════════════════════
-- Cubre la Parte XI: la transacción como unidad atómica (dónde
-- empieza y dónde termina), ACID letra por letra, COMMIT/ROLLBACK/
-- SAVEPOINT (ROLLBACK TO no termina la transacción; recall del
-- commit implícito del DDL), concurrencia Oracle (bloqueo a nivel
-- de FILA, lectura consistente: los lectores no bloquean ni son
-- bloqueados, deadlock y su prevención) y seguridad DCL: privilegios
-- de sistema vs de objeto, GRANT/REVOKE, WITH GRANT OPTION y su
-- riesgo, roles, mínimo privilegio y la vista como capa de seguridad
-- (recall de agenda_recepcion del m04).
-- Práctica de editor (regex+mockOutput): la transacción con red de
-- seguridad (UPDATE + SAVEPOINT + ROLLBACK TO + COMMIT, en orden).
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- OJO: SQL con Oracle está PUBLICADO — esta migración sale en vivo.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 011 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm08-transacciones'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m08-l01-transaccion',      'La transacción: todo o nada',          'leccion',  20, 1),
       ('m08-l02-acid',             'ACID: las cuatro promesas',            'leccion',  20, 2),
       ('m08-l03-commit-savepoint', 'COMMIT, ROLLBACK y SAVEPOINT',         'leccion',  20, 3),
       ('m08-l04-concurrencia',     'Concurrencia: bloqueos y lectura consistente','leccion',20, 4),
       ('m08-l05-privilegios',      'GRANT y REVOKE: quién puede qué',      'leccion',  20, 5),
       ('m08-l06-roles-minimo',     'Roles y el mínimo privilegio',         'leccion',  20, 6),
       ('m08-l07-practica-tx',      'Práctica: la transacción con red',     'practica', 20, 7),
       ('m08-x01-examen',           'Examen: Transacciones y seguridad',    'examen',   40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm08-transacciones';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · La transacción: todo o nada
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Operaciones que no admiten mitades","body":"Surtir una receta toca tres tablas: se descuenta el inventario, se registra la entrega y se marca la receta como surtida. Imagina que el sistema falla ENTRE el paso uno y el dos: el inventario bajó, pero no hay entrega registrada — el medicamento se 'esfumó'. La TRANSACCIÓN existe para prohibir ese estado intermedio: es un grupo de operaciones DML que la base trata como UNA unidad indivisible — o se aplican TODAS, o no se aplica NINGUNA. Todo o nada. Las mitades — inventario sin entrega, cobro sin cita, abono sin cargo — simplemente no pueden existir para el resto del mundo: mientras la transacción vive, sus cambios son provisionales y privados."}$j$),
  (2, 'texto', $j${"title":"Dónde empieza y dónde termina","body":"En Oracle no se declara el inicio: la transacción EMPIEZA sola con tu primer DML (el primer INSERT, UPDATE o DELETE tras la última frontera). Y TERMINA solo de cuatro maneras: (1) COMMIT — confirmas: los cambios se vuelven permanentes y visibles para todos; (2) ROLLBACK — te retractas: todo lo no confirmado se deshace; (3) una orden DDL — el commit implícito que conociste en el m04: el CREATE de en medio confirma tu DML pendiente sin preguntarte; (4) el final de la sesión — salida normal confirma, caída o desconexión abrupta revierte. Ese mapa de fronteras explica accidentes clásicos: el 'yo no hice commit' cuyo DDL intermedio confirmó todo, y el trabajo de una tarde que se esfumó porque la sesión murió antes del COMMIT."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es una transacción?","options":["Cualquier consulta de tipo SELECT simple","Un respaldo automático de la base","Grupo de DML como unidad indivisible","Una tabla temporal de la sesión"],"correctIndex":2,"feedback":{"correct":"Correcto. Todo o nada: la mitad de un surtido de receta (inventario sin entrega) es exactamente lo que la transacción prohíbe.","incorrect":"La transacción agrupa DML en una unidad atómica: sus mitades no pueden quedar a medias ante una falla."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuáles son las CUATRO formas en que termina una transacción en Oracle?","options":["Solamente con un COMMIT del todo explícito","Solo con COMMIT y con ROLLBACK","Cuando transcurre una hora exacta","COMMIT, ROLLBACK, DDL y fin de sesión"],"correctIndex":3,"feedback":{"correct":"Correcto. Las cuatro fronteras — y dos de ellas (DDL y fin de sesión) trabajan sin pedirte opinión.","incorrect":"Además de COMMIT y ROLLBACK explícitos: el DDL confirma implícitamente, y el fin de sesión decide según cómo termine (normal→commit, caída→rollback)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Ejecutaste 30 UPDATEs sin confirmar y tu sesión se cae por un corte de red. ¿Qué pasa con tus cambios?","options":["Se revierten todos: la caída hace rollback","Quedan guardados a medias dentro de la tabla","Quedan guardados completos y firmes","Quedan en una tabla de recuperación"],"correctIndex":0,"feedback":{"correct":"Correcto. La caída revierte: la base prefiere perder tu tarde de trabajo a dejar el hospital en un estado a medias.","incorrect":"Sesión caída = rollback de lo pendiente. Por eso el trabajo largo se confirma por etapas conscientes — jamás 'al final del día'."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — La transacción","points":["Transacción = grupo de DML tratado como unidad INDIVISIBLE: todo o nada.","Los estados intermedios (inventario sin entrega) no existen para el resto del mundo.","Empieza sola con el primer DML; no se declara.","Termina de 4 formas: COMMIT · ROLLBACK · DDL (commit implícito) · fin de sesión (normal confirma, caída revierte).","Mientras vive, sus cambios son provisionales y privados."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-l01-transaccion';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · ACID: las cuatro promesas
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"A y C: ni mitades, ni reglas rotas","body":"ACID es el contrato de cuatro promesas que una base de datos seria firma con cada transacción — y la palabra favorita de los entrevistadores para abrir. A — ATOMICIDAD: la promesa de la lección pasada, todo o nada; la transacción es un átomo, no se parte. C — CONSISTENCIA: la transacción lleva la base de un estado VÁLIDO a otro estado VÁLIDO — todas las reglas que declaraste (PKs, FKs, CHECKs, NOT NULLs) se cumplen al inicio y se cumplen al final. Si algún paso las violara, la transacción no puede confirmarse: el inventario jamás queda negativo si tu CHECK lo prohíbe, ni una entrega apunta a una receta inexistente si tu FK vigila. Nota el ensamble: la consistencia la GARANTIZAN las constraints que aprendiste a declarar — ACID cobra lo que el DDL sembró."}$j$),
  (2, 'texto', $j${"title":"I y D: en privado, y para siempre","body":"I — AISLAMIENTO (isolation): las transacciones concurrentes no se pisan — los cambios SIN confirmar de una sesión son INVISIBLES para las demás. Mientras farmacia surte la receta (transacción abierta), recepción NO ve un inventario a medio descontar: ve el estado anterior, estable y confirmado. Cómo logra Oracle este truco sin frenar a nadie es la próxima lección. D — DURABILIDAD: lo confirmado es PERMANENTE — sobrevive a cortes de luz, caídas del servidor y reinicios. El COMMIT no es una anotación en memoria: Oracle asegura el registro del cambio en disco antes de decirte 'confirmado', y puede reconstruirlo tras cualquier desastre. Las cuatro promesas juntas — átomo, reglas, privacidad, permanencia — son la razón por la que un banco, un hospital o una aerolínea pueden confiar su operación a una base de datos."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué promete la ATOMICIDAD (la A de ACID)?","options":["Que las consultas resultan más rápidas","Que se aplica completa o no se aplica","Que los datos quedan siempre cifrados","Que hay un respaldo hecho cada día"],"correctIndex":1,"feedback":{"correct":"Correcto. El todo-o-nada tiene nombre técnico: atomicidad.","incorrect":"Atomicidad = indivisibilidad: la transacción completa o nada de ella. Las otras letras prometen otras cosas."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"La CONSISTENCIA de ACID promete que la transacción lleva la base 'de un estado válido a otro válido'. ¿Quién define ese 'válido' en la práctica?","options":["El administrador, a mano todas las noches","El proveedor de la nube contratado","Las reglas del esquema: PK, FK, CHECK","Nadie: es automático y sin reglas"],"correctIndex":2,"feedback":{"correct":"Correcto. ACID cobra lo que el DDL sembró: tus constraints SON la definición ejecutable de 'estado válido'.","incorrect":"'Válido' = cumple las constraints que declaraste. Por eso la integridad declarativa del m04 importa: es el contrato que la C hace cumplir."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Mientras farmacia tiene una transacción ABIERTA descontando inventario, ¿qué ve recepción al consultar esa tabla?","options":["El inventario justo a medio descontar","Un error de tabla completamente bloqueada","Solo filas vacías, sin ningún dato","El estado anterior, estable y confirmado"],"correctIndex":3,"feedback":{"correct":"Correcto. La I de ACID: lo provisional es privado. Recepción ve la última foto confirmada, sin esperar ni fallar.","incorrect":"Los cambios sin COMMIT son invisibles para las demás sesiones: recepción ve el estado confirmado anterior — esa es la promesa de aislamiento."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Confirmas un COMMIT y un segundo después se va la luz del centro de datos. ¿Tu cambio sobrevive?","options":["Sí: lo confirmado es permanente en disco","No: se pierde lo del último minuto","Solo si había un respaldo justo de esa hora","Depende del tamaño del cambio hecho"],"correctIndex":0,"feedback":{"correct":"Correcto. El COMMIT que respondió 'listo' ya es indestructible: esa es la D, y es la razón de confiar la operación a la base.","incorrect":"La durabilidad es la promesa del COMMIT: confirmado = asegurado en disco = sobrevive cortes, caídas y reinicios."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — ACID","points":["A · ATOMICIDAD: todo o nada — la transacción es un átomo.","C · CONSISTENCIA: de estado válido a estado válido — y 'válido' lo definen TUS constraints.","I · AISLAMIENTO: lo no confirmado es invisible para las demás sesiones.","D · DURABILIDAD: lo confirmado sobrevive a cualquier desastre — asegurado en disco antes del 'listo'.","El contrato completo es la razón por la que hospitales y bancos confían en la base."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-l02-acid';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · COMMIT, ROLLBACK y SAVEPOINT
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El punto de control a mitad del camino","body":"COMMIT y ROLLBACK ya son viejos conocidos: confirmar todo o deshacer todo. SAVEPOINT agrega el matiz que faltaba: un MARCADOR con nombre a mitad de la transacción — SAVEPOINT tras_cobro — al que puedes regresar sin perderlo todo. ROLLBACK TO tras_cobro deshace SOLO lo posterior al marcador; lo anterior sigue vivo, provisional y tuyo. Y la precisión que los exámenes adoran: ROLLBACK TO un savepoint NO termina la transacción — sigue abierta, puedes continuar trabajando, y el destino final de lo que sobrevivió sigue pendiente de tu COMMIT o ROLLBACK definitivo. El savepoint es la red del trapecista para procesos largos: cargas por etapas, correcciones quirúrgicas donde el paso 3 falló pero los pasos 1 y 2 eran oro."}$j$),
  (2, 'ejemplo_sql', $j${"title":"La corrección quirúrgica","code":"UPDATE citas SET costo = 350 WHERE cita_id = 519;\n-- 1 row updated.  (el cobro, correcto)\n\nSAVEPOINT tras_cobro;\n\nUPDATE inventario SET cantidad = cantidad - 1\nWHERE  medicamento_id = 12;\n-- 1 row updated.  (…medicamento equivocado)\n\nROLLBACK TO tras_cobro;\n-- el descuento se deshace; el cobro SIGUE vivo\n\nCOMMIT;\n-- se confirma solo lo que sobrevivió: el cobro","result":{"columns":["RESULTADO"],"rows":[["Commit complete."]],"note":"El error del paso 2 no costó el paso 1: ROLLBACK TO regresó al marcador (la transacción siguió abierta) y el COMMIT final confirmó únicamente el cobro. Sin savepoint, la alternativa era deshacerlo TODO y repetir el trabajo bueno."}}$j$),
  (3, 'texto', $j${"title":"La disciplina del cuándo confirmar","body":"¿Cada cuánto se confirma? Las dos malas respuestas primero: confirmar tras CADA fila (mil COMMITs por segundo castigan el rendimiento y pulverizan la atomicidad: si el proceso muere a la mitad, quedaron 500 confirmadas y 500 no — el estado a medias que juraste evitar) y confirmar 'al final del día' (una transacción eterna que acumula bloqueos, estorba a todos y lo apuesta todo a que la sesión no muera). La respuesta profesional: el COMMIT se coloca en las FRONTERAS DE LA UNIDAD DE NEGOCIO — el surtido completo de UNA receta es una transacción; el cierre de UNA caja es una transacción. Ni más fino (romperías el átomo), ni más grueso (acapararías la base). La transacción bien dibujada coincide con la operación que el negocio considera indivisible — otra vez: el modelo manda."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión de examen: tras un ROLLBACK TO savepoint, ¿en qué estado queda la transacción?","options":["Terminada: hay que empezar otra nueva","Sigue abierta: solo deshizo lo posterior","Se confirma de forma automática sola","Queda bloqueada hasta que se reinicie todo"],"correctIndex":1,"feedback":{"correct":"Correcto. ROLLBACK TO es retroceso parcial, no final: la transacción vive y el trabajo anterior al marcador sigue en pie (y sin confirmar).","incorrect":"El ROLLBACK TO no cierra nada: deshace lo posterior al savepoint y te deja dentro de la misma transacción, lista para continuar."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un proceso de carga confirma tras CADA fila insertada (mil COMMITs). ¿Cuál es el doble problema?","options":["Ninguno: cuantos más COMMITs, más seguridad","Solo es más lento, pero es correcto","Castiga rendimiento y rompe la atomicidad","Oracle prohíbe más de cien COMMITs"],"correctIndex":2,"feedback":{"correct":"Correcto. El COMMIT por fila convierte una operación atómica en mil operaciones sueltas: cara Y frágil.","incorrect":"Confirmar por fila rompe el átomo del negocio (mitades posibles) y además cuesta rendimiento: el COMMIT va en la frontera de la unidad de negocio."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es el criterio profesional para decidir DÓNDE va el COMMIT?","options":["Cada 10 segundos exactos, siempre","Siempre al final de toda la sesión","Donde lo ponga el editor automáticamente","En la frontera de la unidad de negocio"],"correctIndex":3,"feedback":{"correct":"Correcto. La transacción bien dibujada coincide con la operación que el NEGOCIO considera indivisible: el modelo manda hasta aquí.","incorrect":"El COMMIT dibuja el átomo del negocio: una receta surtida completa = una transacción. Más fino rompe mitades; más grueso acapara la base."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — COMMIT, ROLLBACK y SAVEPOINT","points":["COMMIT confirma todo · ROLLBACK deshace todo lo no confirmado.","SAVEPOINT nombre: marcador a mitad del camino · ROLLBACK TO nombre deshace SOLO lo posterior.","Precisión: ROLLBACK TO no termina la transacción — sigue abierta y pendiente de decisión final.","Ni COMMIT por fila (rompe el átomo, castiga rendimiento) ni transacción eterna (acapara bloqueos).","El COMMIT va en la frontera de la unidad de negocio: una receta surtida, una caja cerrada."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-l03-commit-savepoint';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Concurrencia: bloqueos y lectura consistente
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cincuenta sesiones, una base, cero pisotones","body":"El hospital no es una persona: son cincuenta sesiones tocando las mismas tablas a la vez. Oracle mantiene el orden con dos mecanismos elegantes. PRIMERO, el bloqueo a nivel de FILA: cuando tu UPDATE toca la cita 519, Oracle bloquea ESA fila — no la tabla, no la página: la fila — hasta que confirmes o reviertas. Otra sesión que quiera modificar LA MISMA fila, ESPERA en silencio (no falla: espera su turno); las demás filas de la tabla siguen libres para todos. SEGUNDO, la joya de Oracle: la LECTURA CONSISTENTE — los LECTORES no bloquean ni son bloqueados, jamás. Mientras farmacia modifica sin confirmar, cualquier SELECT de otra sesión ve la última foto CONFIRMADA de los datos (Oracle la reconstruye de sus registros de deshacer). Leer nunca estorba, escribir solo estorba sobre la misma fila: por eso mil consultas y cien capturas conviven sin pisarse."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Dos sesiones, la misma fila","code":"-- SESIÓN A (farmacia):\nUPDATE inventario SET cantidad = cantidad - 5\nWHERE  medicamento_id = 12;\n-- 1 row updated.  (sin COMMIT todavía: la fila 12 queda bloqueada)\n\n-- SESIÓN B (recepción), al mismo tiempo:\nSELECT cantidad FROM inventario WHERE medicamento_id = 12;\n-- → responde AL INSTANTE con el valor CONFIRMADO anterior (30):\n--   los lectores no esperan ni ven lo provisional\n\n-- SESIÓN C (otra captura), al mismo tiempo:\nUPDATE inventario SET cantidad = cantidad - 2\nWHERE  medicamento_id = 12;\n-- → ESPERA en silencio: quiere LA MISMA fila bloqueada por A.\n--   Cuando A confirme, C despierta y aplica su cambio sobre lo nuevo.","result":{"columns":["SESIÓN","OPERACIÓN","RESULTADO"],"rows":[["A","UPDATE fila 12 (sin commit)","fila bloqueada"],["B","SELECT fila 12","lee 30 al instante (foto confirmada)"],["C","UPDATE fila 12","espera su turno hasta el COMMIT de A"]],"note":"Tres sesiones, cero errores: el lector nunca espera (lectura consistente), el segundo escritor espera solo porque quiere exactamente la misma fila. El resto de la tabla siguió libre todo el tiempo."}}$j$),
  (3, 'texto', $j${"title":"El abrazo mortal (y cómo no darlo)","body":"Queda el accidente clásico de la concurrencia: el DEADLOCK o abrazo mortal. La sesión A bloqueó la fila 1 y quiere la 2; la sesión B bloqueó la 2 y quiere la 1 — ambas esperan a la otra, para siempre. Oracle lo DETECTA solo (no se queda colgado): elige a una víctima, cancela su sentencia con el error ORA-00060 y la otra sesión continúa. Pero detectar no es prevenir, y la prevención es disciplina de equipo: (1) tocar las tablas y filas SIEMPRE EN EL MISMO ORDEN en todos los procesos — si todos van primero a citas y luego a inventario, el abrazo cruzado no puede formarse; (2) transacciones CORTAS — el bloqueo que vive segundos casi nunca choca; el que vive una hora (la transacción eterna de la lección pasada) choca con todos. El deadlock ocasional se maneja; el deadlock frecuente delata procesos mal ordenados."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En Oracle, ¿qué bloquea exactamente un UPDATE sin confirmar?","options":["La fila que modificó, hasta el COMMIT","La tabla completa entera mientras dura todo","Toda la base de datos por completo","Nada: los UPDATE no bloquean nunca"],"correctIndex":0,"feedback":{"correct":"Correcto. Bloqueo a nivel de fila: la granularidad fina que permite a cien capturistas convivir en la misma tabla.","incorrect":"Oracle bloquea por FILA, no por tabla: solo choca quien quiere exactamente las mismas filas modificadas y sin confirmar."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La 'lectura consistente' de Oracle promete que…","options":["Los SELECT esperan a los UPDATE","Los lectores no bloquean ni son bloqueados","Todas las sesiones ven siempre lo provisional","Los lectores fallan si hay escritores"],"correctIndex":1,"feedback":{"correct":"Correcto. La joya de Oracle: leer nunca estorba — el SELECT recibe la foto confirmada reconstruida al instante.","incorrect":"Los lectores ni esperan ni estorban: ven el estado confirmado anterior. Solo los escritores de la MISMA fila se hacen cola."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"La sesión A tiene la fila 1 y espera la 2; la B tiene la 2 y espera la 1. ¿Qué pasa y cómo se PREVIENE ese patrón?","options":["Se quedan las dos esperando para siempre","Oracle reinicia entero todo el servidor","Deadlock: Oracle mata una; mismo orden","Las dos sesiones se confirman solas"],"correctIndex":2,"feedback":{"correct":"Correcto. Detección automática + prevención por disciplina: mismo orden de acceso en todos los procesos, y bloqueos que viven poco.","incorrect":"El abrazo mortal no cuelga a Oracle (detecta y sacrifica una sentencia), pero prevenirlo es tuyo: orden consistente de acceso + transacciones cortas."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Concurrencia","points":["Bloqueo a nivel de FILA: el UPDATE bloquea sus filas hasta confirmar; el resto de la tabla sigue libre.","El segundo escritor de la MISMA fila espera en silencio su turno — no falla.","LECTURA CONSISTENTE: los lectores no bloquean ni son bloqueados — ven la última foto confirmada.","DEADLOCK: espera circular; Oracle detecta y sacrifica una sentencia (ORA-00060).","Prevención: mismo orden de acceso en todos los procesos + transacciones cortas."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-l04-concurrencia';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · GRANT y REVOKE: quién puede qué
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La cuarta familia entra en escena","body":"Del mapa de las cuatro familias del m04, faltaba el DCL: GRANT otorga permisos, REVOKE los retira. Los permisos vienen en dos especies que las certificaciones exigen distinguir. PRIVILEGIOS DE SISTEMA: capacidades sobre LA BASE — conectarse (CREATE SESSION), crear objetos (CREATE TABLE, CREATE VIEW). Sin CREATE SESSION, un usuario existe pero no puede ni entrar. PRIVILEGIOS DE OBJETO: acciones sobre UN objeto concreto — GRANT SELECT ON citas TO recepcion, y también INSERT, UPDATE, DELETE (¡e incluso por columnas, para UPDATE e INSERT!). La pregunta que los separa: ¿el permiso habla de la base en general (sistema) o de una tabla/vista con nombre y apellido (objeto)? Esa distinción decide quién puede otorgarlo, cómo se revoca y qué tan peligroso es regalarlo."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El alta de la cuenta de recepción","code":"-- Privilegios de SISTEMA: poder entrar\nGRANT CREATE SESSION TO recepcion;\n\n-- Privilegios de OBJETO: poder hacer, sobre objetos concretos\nGRANT SELECT ON agenda_recepcion TO recepcion;\nGRANT SELECT, INSERT ON citas TO capturista;\nGRANT UPDATE (costo) ON citas TO facturacion;\n\n-- Y la retirada, cuando cambia el puesto:\nREVOKE INSERT ON citas FROM capturista;","result":{"columns":["RESULTADO"],"rows":[["Grant succeeded."],["Grant succeeded."],["Grant succeeded."],["Grant succeeded."],["Revoke succeeded."]],"note":"Cada cuenta recibe EXACTAMENTE lo que su puesto necesita: recepción solo lee su vista, el capturista lee e inserta citas, y facturación solo puede actualizar LA COLUMNA costo. El REVOKE cierra la puerta cuando el puesto cambia."}}$j$),
  (3, 'texto', $j${"title":"WITH GRANT OPTION: el permiso de repartir permisos","body":"GRANT SELECT ON citas TO jefa_archivo WITH GRANT OPTION le da a la jefa algo más que lectura: el poder de REGALAR esa lectura a otros. Suena práctico y es pólvora: el dueño de la tabla pierde el mapa de quién tiene acceso — la jefa se lo dio a su analista, el analista al practicante… La mitigación de Oracle para privilegios de objeto: el REVOKE es EN CASCADA — al retirarle el permiso a la jefa, caen también todos los que ella (y su cadena) repartió. Aún así, la política del oficio es tacaña: WITH GRANT OPTION casi nunca; la distribución de permisos se centraliza en el administrador — y como verás en la próxima lección, ni siquiera se reparte usuario por usuario: se reparte por ROLES."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre un privilegio de SISTEMA y uno de OBJETO?","options":["El de sistema es siempre bastante más rápido","No hay ninguna diferencia real","El de objeto lo otorga cualquiera","Sistema: sobre la base; objeto: un objeto"],"correctIndex":3,"feedback":{"correct":"Correcto. Poder-hacer-en-la-base vs poder-tocar-este-objeto: la distinción que organiza todo el DCL.","incorrect":"CREATE SESSION habla de la base (sistema); SELECT ON citas habla de un objeto con nombre (objeto). Esa es la línea divisoria."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un usuario nuevo existe pero no puede ni conectarse a la base. ¿Qué le falta?","options":["El privilegio de sistema CREATE SESSION","Una contraseña considerablemente más larga","Un GRANT SELECT sobre alguna tabla","Un rol completo de administrador"],"correctIndex":0,"feedback":{"correct":"Correcto. CREATE SESSION es la llave de la puerta: el privilegio de sistema mínimo de cualquier cuenta viva.","incorrect":"Conectarse es una capacidad sobre la base: CREATE SESSION, el privilegio de sistema que toda cuenta necesita primero."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace WITH GRANT OPTION y por qué el oficio lo raciona?","options":["Acelera notablemente los GRANT","Deja al receptor regalar el permiso","Hace el permiso del todo permanente","Convierte el permiso directo en rol"],"correctIndex":1,"feedback":{"correct":"Correcto. Repartir el poder de repartir dispersa el control; la cascada del REVOKE limpia, pero mejor no ensuciar.","incorrect":"WITH GRANT OPTION delega la distribución — y con ella se pierde el mapa. El REVOKE en cascada recupera el control, tarde."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — GRANT y REVOKE","points":["DCL: GRANT otorga, REVOKE retira.","SISTEMA = capacidades sobre la base (CREATE SESSION, CREATE TABLE) · OBJETO = acciones sobre un objeto (SELECT ON citas).","Los privilegios de objeto llegan a granularidad de columna (UPDATE (costo) ON citas).","WITH GRANT OPTION reparte el poder de repartir: casi nunca — el control se centraliza.","REVOKE de objeto es en cascada: al caer el intermediario, cae su cadena."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-l05-privilegios';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Roles y el mínimo privilegio
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Roles: permisos por puesto, no por persona","body":"Repartir permisos usuario por usuario escala fatal: cuarenta recepcionistas × ocho permisos = trescientos veinte GRANTs, y cada alta, baja o cambio de puesto es una sesión de arqueología. El ROL lo arregla: un PAQUETE de privilegios con nombre — CREATE ROLE rol_recepcion; se le otorgan los permisos al ROL (GRANT SELECT ON agenda_recepcion TO rol_recepcion) y el rol se otorga a las personas (GRANT rol_recepcion TO ana). El alta nueva es UN grant; el cambio de política es UN cambio en el rol que alcanza a los cuarenta a la vez. Los permisos siguen al PUESTO, no a la persona — exactamente como el hospital piensa su organigrama. Oracle trae roles predefinidos históricos (CONNECT, RESOURCE), pero el oficio moderno define los suyos por puesto real."}$j$),
  (2, 'texto', $j${"title":"Mínimo privilegio: la política que salva hospitales","body":"El principio rector de toda la seguridad — y respuesta esperada en cualquier entrevista seria: MÍNIMO PRIVILEGIO. Cada cuenta recibe EXACTAMENTE los permisos que su función exige, ni uno más. Recepción NO puede leer diagnósticos: no los necesita para agendar. El becario NO puede borrar: aprende leyendo. La aplicación web NO es dueña del esquema: opera con una cuenta acotada. ¿Por qué tanta tacañería? Porque cada permiso de más es superficie de ataque y de accidente: la cuenta comprometida (o el becario con prisa) solo puede dañar hasta donde sus permisos alcanzan. Y aquí se cierra un círculo del curso: la VISTA del m04 es pieza central del mínimo privilegio — agenda_recepcion expone fecha, paciente y médico; el GRANT se hace SOBRE LA VISTA, jamás sobre la tabla citas con sus costos y diagnósticos. Capa de presentación Y frontera de seguridad: una sola pieza, dos oficios."}$j$),
  (3, 'ejemplo_sql', $j${"title":"El organigrama, hecho permisos","code":"-- El paquete del puesto:\nCREATE ROLE rol_recepcion;\nGRANT CREATE SESSION TO rol_recepcion;\nGRANT SELECT ON agenda_recepcion TO rol_recepcion;\nGRANT INSERT ON citas TO rol_recepcion;\n\n-- Las personas reciben el puesto, no permisos sueltos:\nGRANT rol_recepcion TO ana;\nGRANT rol_recepcion TO luis;\n\n-- El cambio de política alcanza a todos a la vez:\nREVOKE INSERT ON citas FROM rol_recepcion;","result":{"columns":["RESULTADO"],"rows":[["Role ROL_RECEPCION created."],["Grant succeeded."],["Grant succeeded."],["Grant succeeded."],["Grant succeeded."],["Grant succeeded."],["Revoke succeeded."]],"note":"Ana y Luis nunca recibieron permisos directos: reciben el PUESTO. El día que recepción pierda la captura de citas, un solo REVOKE sobre el rol ajusta a todo el equipo — y nota que el SELECT es sobre la VISTA, no sobre la tabla."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué problema resuelve un ROL frente a otorgar permisos usuario por usuario?","options":["Hace las consultas mucho más rápidas","Cifra todas las contraseñas del sistema","Empaqueta privilegios por puesto","Elimina la necesidad de usar REVOKE"],"correctIndex":2,"feedback":{"correct":"Correcto. Los permisos siguen al puesto, no a la persona: cuarenta recepcionistas, un rol, cero arqueología.","incorrect":"El rol es el paquete del puesto: se administra UNA vez y las personas lo reciben completo — altas, bajas y cambios dejan de ser artesanales."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"El principio de MÍNIMO PRIVILEGIO dicta que…","options":["Todos empiezan con todo y luego se recorta","Solo el administrador tiene permisos","Los permisos se renuevan cada año","Cada cuenta: lo justo, ni un permiso más"],"correctIndex":3,"feedback":{"correct":"Correcto. La cuenta comprometida solo daña hasta donde sus permisos alcanzan: la tacañería es la defensa.","incorrect":"Mínimo privilegio = lo necesario y nada más. Empezar con todo y recortar es el anti-patrón exacto."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Recepción necesita ver la agenda (fecha, paciente, médico) pero JAMÁS costos ni diagnósticos. ¿El diseño de permisos correcto?","options":["GRANT SELECT sobre una vista acotada","GRANT SELECT ON citas y pedir discreción","Darles copia de la tabla sin columnas","GRANT SELECT ON citas WITH GRANT OPTION"],"correctIndex":0,"feedback":{"correct":"Correcto. El círculo del curso se cierra: la vista del m04 + el GRANT del m08 = mínimo privilegio ejecutable.","incorrect":"El permiso se otorga sobre la VISTA acotada, no sobre la tabla completa: lo que la vista no expone, no existe para esa cuenta."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Roles y mínimo privilegio","points":["ROL = paquete de privilegios por PUESTO: permisos al rol, rol a las personas.","Altas, bajas y cambios de política se vuelven una sola operación sobre el rol.","MÍNIMO PRIVILEGIO: exactamente lo que la función exige — cada permiso extra es superficie de ataque.","La cuenta comprometida solo daña hasta donde alcanzan sus permisos.","La VISTA + GRANT sobre la vista (no la tabla): presentación y frontera de seguridad en una pieza."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-l06-roles-minimo';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Práctica: la transacción con red (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Facturación te pide aplicar el cobro de la cita 519 y de paso descontar una pieza del medicamento 12… pero a medio camino descubres que el descuento era de OTRO medicamento. Escribe la secuencia transaccional completa que salva el cobro y deshace solo el error.","instructions":["Aplica el cobro: UPDATE citas SET costo = 350 WHERE cita_id = 519.","Planta la red: SAVEPOINT tras_cobro.","Aplica el descuento (el que resultará erróneo): UPDATE inventario SET cantidad = cantidad - 1 WHERE medicamento_id = 12.","Deshaz SOLO el descuento: ROLLBACK TO tras_cobro.","Confirma lo que sobrevivió (el cobro): COMMIT."],"initialCode":"-- El cobro procede; el descuento resultará un error.\n-- Escribe la secuencia completa, en orden.\n\nUPDATE citas SET costo = 350 WHERE cita_id = 519;\n","validators":["update\\s+citas\\s+set\\s+costo\\s*=\\s*350\\s+where\\s+cita_id\\s*=\\s*519","savepoint\\s+tras_cobro","update\\s+inventario\\s+set\\s+cantidad\\s*=\\s*cantidad\\s*-\\s*1\\s+where\\s+medicamento_id\\s*=\\s*12","rollback\\s+to\\s+tras_cobro","savepoint\\s+tras_cobro.*update\\s+inventario.*rollback\\s+to\\s+tras_cobro.*commit\\b"],"mockOutput":{"columns":["PASO","RESULTADO"],"rows":[["UPDATE citas","1 row updated."],["SAVEPOINT tras_cobro","Savepoint created."],["UPDATE inventario","1 row updated."],["ROLLBACK TO tras_cobro","Rollback complete. (solo el descuento)"],["COMMIT","Commit complete. (el cobro, confirmado)"]],"note":"La cita 519 quedó cobrada y el inventario intacto: el savepoint dejó caer únicamente el paso equivocado. La transacción siguió viva tras el ROLLBACK TO — por eso el COMMIT final tenía algo que confirmar."},"hints":["El orden es la respuesta: cobro → SAVEPOINT tras_cobro → descuento → ROLLBACK TO tras_cobro → COMMIT.","SAVEPOINT tras_cobro; se planta DESPUÉS del cobro y ANTES del descuento: protege lo bueno del error que viene.","ROLLBACK TO tras_cobro deshace solo lo posterior al marcador y deja la transacción ABIERTA — el COMMIT final confirma el cobro sobreviviente."],"successMessage":"Transacción con red ejecutada: el savepoint protegió el cobro, el ROLLBACK TO amputó solo el error y el COMMIT confirmó lo que valía. Acabas de usar la herramienta que separa una corrección quirúrgica de un 'deshacer todo y repetir'.","failMessage":"Revisa la secuencia y su ORDEN: UPDATE citas … 519 → SAVEPOINT tras_cobro → UPDATE inventario … 12 → ROLLBACK TO tras_cobro → COMMIT. El savepoint va entre los dos UPDATEs, y el COMMIT cierra al final."}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-l07-practica-tx';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La décima región","body":"Byte ya no protege datos: protege OPERACIONES — y decide quién entra a cada puerta. Once preguntas custodian esta región: el átomo del negocio, las cuatro promesas, la red del savepoint, la convivencia de cincuenta sesiones y la tacañería que salva hospitales. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Surtir una receta descuenta inventario, registra la entrega y marca la receta — y el sistema falla tras el primer paso. Con una TRANSACCIÓN bien dibujada, ¿en qué estado queda la base?","options":["Con el inventario descontado, pero sin entrega","Intacta: la transacción atómica se revierte","Con la entrega pero sin el descuento","Queda en modo de solo-lectura fijo"],"correctIndex":1,"feedback":{"correct":"Correcto. Todo o nada: la falla a medias dispara el nada, y el estado intermedio nunca fue visible.","incorrect":"El átomo no se parte: si el paso 2 no llegó, el paso 1 se revierte. Ese es exactamente el trabajo de la transacción."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Empareja las cuatro promesas de ACID:","options":["Rapidez, compresión, cifrado, respaldo","Atomicidad, consistencia, aislamiento, durabilidad","Alta disponibilidad, caché, índices, disco duro","Autenticación, cifrado, integridad y disponibilidad"],"correctIndex":1,"feedback":{"correct":"Correcto. Átomo, reglas, privacidad, permanencia: el contrato completo.","incorrect":"A-C-I-D: atomicidad, consistencia, aislamiento, durabilidad — cada letra una promesa distinta sobre tus transacciones."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué garantiza la DURABILIDAD en el instante en que Oracle responde 'Commit complete.'?","options":["Que habrá un respaldo esa misma noche","Que nadie más puede leer esa fila","Que la transacción aún puede deshacerse","Que ya está asegurado en disco"],"correctIndex":3,"feedback":{"correct":"Correcto. El 'complete' no es cortesía: es la promesa de permanencia ya cumplida.","incorrect":"La D de ACID: el COMMIT respondido está en disco y se reconstruye tras cualquier desastre. (Y no: confirmado ya no se deshace con ROLLBACK.)"}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Dentro de una transacción ejecutas SAVEPOINT paso1, luego más DML, luego ROLLBACK TO paso1. ¿Qué se deshizo y en qué estado quedas?","options":["Solo lo posterior; la transacción sigue abierta","Se deshizo todo y la transacción terminó","No se deshizo absolutamente nada","Se confirmó lo anterior a paso1 solo"],"correctIndex":0,"feedback":{"correct":"Correcto. Retroceso parcial, transacción viva, decisión final pendiente: las tres piezas de la precisión.","incorrect":"ROLLBACK TO = amputación de lo posterior al marcador, nada más: sigues dentro de la transacción y lo previo sigue provisional."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Un proceso nocturno ejecuta su DML y, a la mitad, corre un TRUNCATE de una tabla temporal. ¿Qué le pasó al DML pendiente?","options":["Nada en absoluto: sigue pendiente","Quedó confirmado: TRUNCATE es DDL","Se revirtió de forma automática solo","Se pausó hasta llegar el COMMIT"],"correctIndex":1,"feedback":{"correct":"Correcto. El DDL de en medio es una frontera de transacción: confirma lo pendiente sin preguntar — el clásico que une m04 y m08.","incorrect":"Todo DDL (TRUNCATE incluido) hace commit implícito: el DML anterior quedó confirmado en ese instante, con o sin tu intención."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Mientras una sesión modifica la fila 12 sin confirmar, otra sesión hace SELECT de esa fila. ¿Qué obtiene?","options":["Un error de fila que está bloqueada","El valor provisional a medias de la otra sesión","El valor confirmado anterior, al instante","Una fila del todo vacía, sin datos"],"correctIndex":2,"feedback":{"correct":"Correcto. La joya de Oracle: leer jamás espera, y jamás ve mitades — la foto confirmada, reconstruida al vuelo.","incorrect":"Los SELECT no hacen cola ni ven lo provisional: reciben la última versión confirmada de la fila."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Dos sesiones quieren hacer UPDATE de LA MISMA fila. La segunda…","options":["Recibe un error de forma inmediata","Sobrescribe a la primera sesión","Crea una copia nueva de la fila","Espera a que la primera confirme"],"correctIndex":3,"feedback":{"correct":"Correcto. Los escritores de la misma fila se forman en fila (literalmente); todos los demás ni se enteran.","incorrect":"El segundo escritor espera su turno — sin error, sin sobrescribir. Y solo por esa fila: la granularidad es fina."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"Los deadlocks (ORA-00060) se volvieron frecuentes entre dos procesos batch. ¿La corrección de fondo?","options":["Tocar todo en el mismo orden y acortar","Aumentar la memoria total del servidor","Ejecutarlos como administrador siempre","Desactivar del todo los bloqueos"],"correctIndex":0,"feedback":{"correct":"Correcto. El deadlock frecuente delata procesos desordenados: mismo orden de acceso + bloqueos breves = abrazo imposible.","incorrect":"Oracle ya detecta y sacrifica; PREVENIR es disciplina: orden de acceso consistente en todos los procesos y transacciones cortas."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"CREATE SESSION y SELECT ON citas: clasifica ambos privilegios.","options":["Ambos son privilegios de objeto","CREATE SESSION sistema; SELECT objeto","Ambos son privilegios de sistema","CREATE SESSION es en realidad un rol"],"correctIndex":1,"feedback":{"correct":"Correcto. ¿Habla de la base o de una tabla concreta? — la pregunta que los clasifica siempre.","incorrect":"Conectarse es capacidad general (sistema); leer UNA tabla es acción sobre objeto. La preposición ON suele delatar al de objeto."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué la seguridad se administra con ROLES y bajo MÍNIMO PRIVILEGIO?","options":["Porque lo exige la licencia comprada","Porque los GRANT directos están off","Permisos por puesto y daño acotado","Para ahorrar bastante espacio en disco"],"correctIndex":2,"feedback":{"correct":"Correcto. Administrable Y acotado: el paquete por puesto más la tacañería deliberada.","incorrect":"Roles = administración por puesto; mínimo privilegio = daño acotado. Juntos son la política estándar de cualquier base seria."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'la app de recepción necesita mostrar la agenda del día. ¿Qué permisos configuras?' Tu respuesta senior:","options":["GRANT ALL ON citas, para que no falte nada","La contraseña del administrador, temporal","SELECT sobre absolutamente todas las tablas, solo lectura","Vista acotada + rol del puesto + mínimo privilegio"],"correctIndex":3,"feedback":{"correct":"Impecable. Vista como frontera + rol como paquete + mínimo privilegio como política: el diseño de seguridad completo en tres piezas.","incorrect":"La respuesta senior ensambla: vista acotada (qué se ve) + rol del puesto (quién lo recibe) + mínimo privilegio (ni un permiso más). Ni ALL, ni tablas directas."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm08-x01-examen';
