-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 045 — SQL con Oracle · m10: Introducción a PL/SQL
-- ═══════════════════════════════════════════════════════════════════
-- Cubre el módulo de PL/SQL del temario: el bloque (DECLARE/BEGIN/
-- EXCEPTION/END), variables con %TYPE, SELECT INTO, control de flujo
-- (IF/CASE/LOOPs), cursores (con el cursor FOR loop como forma
-- profesional), procedures y functions (IN/OUT, EXECUTE), triggers
-- (:NEW/:OLD, BEFORE/AFTER, FOR EACH ROW — con el recall vinculante:
-- declarativas ANTES que triggers, y la auditoría/journaling del m3a
-- como uso legítimo) y excepciones (NO_DATA_FOUND, TOO_MANY_ROWS,
-- OTHERS y el pecado de tragar errores).
-- Práctica de editor (regex+mockOutput): bloque completo con %TYPE,
-- SELECT INTO, IF y manejo de NO_DATA_FOUND.
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- OJO: SQL con Oracle está PUBLICADO — esta migración sale en vivo.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 011 (estructura v2).
-- ═══════════════════════════════════════════════════════════════════

-- Limpia el módulo (cascade borra sus content_blocks)
delete from public.lessons
where module_id = (
  select m.id
  from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'sql-oracle' and m.slug = 'm10-plsql'
);

-- ── Lecciones del módulo ──────────────────────────────────────────────
insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m10-l01-bloque',           'El bloque PL/SQL',                     'leccion',  20, 1),
       ('m10-l02-control',          'Variables, SELECT INTO y control',     'leccion',  20, 2),
       ('m10-l03-cursores',         'Cursores: recorrer resultados',        'leccion',  20, 3),
       ('m10-l04-procedures',       'Procedures y functions',               'leccion',  20, 4),
       ('m10-l05-triggers',         'Triggers: el código que se dispara',   'leccion',  20, 5),
       ('m10-l06-excepciones',      'Excepciones: fallar con elegancia',    'leccion',  20, 6),
       ('m10-l07-practica-plsql',   'Práctica: tu primer bloque completo',  'practica', 20, 7),
       ('m10-x01-examen',           'Examen: Introducción a PL/SQL',        'examen',   40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'sql-oracle' and m.slug = 'm10-plsql';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · El bloque PL/SQL
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuando el SQL necesita lógica","body":"El SQL declara QUÉ quieres; pero hay tareas que exigen PASOS: 'busca el costo, y SI supera el tope, registra la alerta, SI NO, archívalo'. PL/SQL es la extensión procedural de Oracle — SQL más variables, condiciones, ciclos y manejo de errores — y su superpoder es DÓNDE corre: DENTRO de la base, junto a los datos, sin viajes de ida y vuelta por la red. Su unidad es el BLOQUE, con cuatro secciones de las que dos son opcionales: DECLARE (opcional: tus variables), BEGIN (obligatoria: los pasos), EXCEPTION (opcional: qué hacer si algo truena) y END; (obligatoria: el cierre). Un bloque puede vivir suelto (anónimo, se ejecuta y se olvida) o con nombre y residencia permanente — los procedures, functions y triggers de este módulo."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Hola, bloque","code":"DECLARE\n  v_hospital  VARCHAR2(40) := 'San Rafael';\n  v_citas_hoy NUMBER := 0;\nBEGIN\n  SELECT COUNT(*)\n  INTO   v_citas_hoy\n  FROM   citas\n  WHERE  TRUNC(fecha) = TRUNC(SYSDATE);\n\n  DBMS_OUTPUT.PUT_LINE('Hospital ' || v_hospital || ': '\n                       || v_citas_hoy || ' citas hoy');\nEND;\n/","result":{"columns":["DBMS_OUTPUT"],"rows":[["Hospital San Rafael: 12 citas hoy"]],"note":"Las cuatro piezas en miniatura: DECLARE presenta las variables (con := para asignar), BEGIN ejecuta, el SELECT … INTO deposita el resultado EN la variable, y DBMS_OUTPUT.PUT_LINE es el 'imprimir' de PL/SQL. La barra final (/) es la orden de ejecutar el bloque en los editores de Oracle."}}$j$),
  (3, 'texto', $j${"title":"%TYPE: variables que no se desactualizan","body":"Declarar v_costo NUMBER(8,2) funciona… hasta que la columna citas.costo cambie a NUMBER(10,2) y tu variable se quede chica en silencio. La declaración profesional ANCLA la variable a la columna: v_costo citas.costo%TYPE — 'del tipo que tenga esa columna, HOY y siempre'. Si la tabla evoluciona, la variable evoluciona con ella: cero desincronización, cero mantenimiento. Es el mismo instinto que ya entrenaste (la lista de columnas del INSERT, el ON explícito de los joins): amarrar el código a los CONTRATOS del esquema, no a copias manuales que envejecen. Existe también %ROWTYPE — una variable con la forma de una FILA completa — para cuando necesitas la fila entera y no un valor."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuáles son las cuatro secciones de un bloque PL/SQL y cuáles son obligatorias?","options":["SELECT, FROM, WHERE, ORDER BY","DECLARE (opcional) · BEGIN (obligatoria) · EXCEPTION (opcional) · END; (obligatoria)","BEGIN y COMMIT, ambas obligatorias","DECLARE y EXCEPTION, ambas obligatorias"],"correctIndex":1,"feedback":{"correct":"Correcto. El esqueleto mínimo es BEGIN … END; — variables y manejo de errores se suman cuando hacen falta.","incorrect":"DECLARE/BEGIN/EXCEPTION/END: solo BEGIN y END; son obligatorias. Lo demás se agrega según la tarea."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué ventaja da declarar v_costo citas.costo%TYPE en lugar de v_costo NUMBER(8,2)?","options":["Es más corto de escribir","La variable queda ANCLADA al tipo real de la columna: si la tabla evoluciona, la variable evoluciona con ella — sin copias manuales que envejecen","Hace la variable constante","Evita los nulos"],"correctIndex":1,"feedback":{"correct":"Correcto. %TYPE amarra el código al contrato del esquema: el mismo instinto del INSERT con lista y el ON explícito.","incorrect":"%TYPE = 'del tipo que tenga esa columna, hoy y siempre': la tabla cambia y tu variable no se queda chica en silencio."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es el superpoder de que PL/SQL corra DENTRO de la base de datos?","options":["Colores en el editor","La lógica vive JUNTO a los datos: sin viajes de ida y vuelta por la red entre cada paso — y disponible para cualquier aplicación que se conecte","No necesita permisos","Corre sin transacciones"],"correctIndex":1,"feedback":{"correct":"Correcto. Mil pasos junto a los datos cuestan un viaje; mil pasos desde la aplicación cuestan mil viajes.","incorrect":"Correr en la base elimina la red del ciclo: los pasos operan junto a los datos y el resultado viaja una sola vez."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — El bloque","points":["PL/SQL = SQL + lógica procedural, corriendo DENTRO de la base (junto a los datos).","Bloque: DECLARE (opcional) · BEGIN (obligatoria) · EXCEPTION (opcional) · END; (obligatoria).","Asignación con := · SELECT … INTO deposita en variables · DBMS_OUTPUT.PUT_LINE imprime.","%TYPE ancla la variable a la columna (y %ROWTYPE, a la fila): contratos, no copias.","Bloques anónimos para ejecutar-y-olvidar; con nombre (procedures/functions/triggers) para residencia permanente."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-l01-bloque';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Variables, SELECT INTO y control de flujo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"SELECT INTO: el puente con las dos promesas","body":"El puente entre el SQL y tus variables es SELECT columnas INTO variables FROM …: la consulta corre y su resultado se deposita en las variables. Pero el INTO firma un contrato estricto que debes conocer HOY (y manejar con elegancia en la lección de excepciones): la consulta debe devolver EXACTAMENTE UNA fila. Cero filas → explota con NO_DATA_FOUND; más de una → explota con TOO_MANY_ROWS. ¿Te suena? Es la misma lógica de las subconsultas de una fila del m06: el receptor espera un valor y la promesa se rompe con cero o con muchos. La defensa también es la misma: filtra por PK o UNIQUE cuando esperas una fila — la garantía por diseño, no por suerte."}$j$),
  (2, 'texto', $j${"title":"IF, CASE y los tres ciclos","body":"La lógica se escribe como se lee. Condiciones: IF v_costo > 500 THEN … ELSIF v_costo > 300 THEN … ELSE … END IF; — y un CASE análogo al que ya usas en SQL. Ciclos, tres sabores: LOOP … EXIT WHEN condición; END LOOP; (el ciclo crudo: repite hasta que le digas basta), WHILE condición LOOP … END LOOP; (pregunta antes de cada vuelta) y el favorito para rangos: FOR i IN 1..10 LOOP … END LOOP; — la variable i nace y muere con el ciclo, sin declararla. Nada de esto reemplaza al SQL: si algo puede resolverse con UNA consulta (un UPDATE con WHERE, un agregado con GROUP BY), la consulta gana — el ciclo que recorre filas para hacer lo que un UPDATE haría de un golpe es el anti-patrón clásico del principiante de PL/SQL."}$j$),
  (3, 'ejemplo_sql', $j${"title":"La clasificación, con pasos","code":"DECLARE\n  v_costo  citas.costo%TYPE;\nBEGIN\n  SELECT costo INTO v_costo\n  FROM   citas\n  WHERE  cita_id = 517;          -- PK: una fila garantizada\n\n  IF v_costo >= 800 THEN\n    DBMS_OUTPUT.PUT_LINE('Tarifa premium: revisión de dirección');\n  ELSIF v_costo >= 300 THEN\n    DBMS_OUTPUT.PUT_LINE('Tarifa estándar');\n  ELSE\n    DBMS_OUTPUT.PUT_LINE('Tarifa social');\n  END IF;\nEND;\n/","result":{"columns":["DBMS_OUTPUT"],"rows":[["Tarifa premium: revisión de dirección"]],"note":"El SELECT INTO trae el dato (filtrado por PK: la fila única está garantizada por diseño) y el IF/ELSIF decide en orden — gana la primera condición verdadera, como el CASE del m05. La cita 517 cuesta 950: premium."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué contrato firma SELECT … INTO, y qué pasa si se rompe?","options":["Devuelve todas las filas que haya","La consulta debe devolver EXACTAMENTE UNA fila: con cero explota NO_DATA_FOUND, con varias explota TOO_MANY_ROWS — la defensa: filtrar por PK/UNIQUE","Devuelve máximo diez filas","Convierte el resultado en texto"],"correctIndex":1,"feedback":{"correct":"Correcto. La promesa de una-fila del m06, ahora en PL/SQL — y con los mismos guardianes: PK o UNIQUE en el WHERE.","incorrect":"El INTO espera exactamente una fila: cero → NO_DATA_FOUND, muchas → TOO_MANY_ROWS. Se garantiza por diseño, no por suerte."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué distingue al ciclo FOR i IN 1..10 LOOP de los otros ciclos PL/SQL?","options":["Es infinito","La variable contadora nace y muere CON el ciclo (no se declara) y el rango es explícito: el favorito para repeticiones contadas","No puede contener SQL","Corre en paralelo"],"correctIndex":1,"feedback":{"correct":"Correcto. FOR trae contador gratis y límites claros; LOOP/EXIT WHEN y WHILE quedan para condiciones abiertas.","incorrect":"El FOR de rango declara su propio contador y sus límites: la forma más segura de repetir n veces."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Necesitas subir 10% el costo de TODAS las citas de un médico. ¿Un ciclo PL/SQL que recorra fila por fila, o un UPDATE con WHERE?","options":["El ciclo: más control","El UPDATE con WHERE: si UNA consulta lo resuelve, la consulta gana — el ciclo fila-por-fila para trabajo de conjunto es el anti-patrón clásico de PL/SQL","Ambos por igual","Ninguno: se hace a mano"],"correctIndex":1,"feedback":{"correct":"Correcto. PL/SQL complementa al SQL, no lo sustituye: el motor hace en un golpe lo que el ciclo haría en mil viajes.","incorrect":"El trabajo de CONJUNTO es del SQL (un UPDATE); PL/SQL entra cuando hay pasos y decisiones que una consulta no puede expresar."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Variables y control","points":["SELECT … INTO deposita en variables — y exige EXACTAMENTE una fila (NO_DATA_FOUND / TOO_MANY_ROWS).","La garantía de una-fila se diseña: PK o UNIQUE en el WHERE.","IF/ELSIF/ELSE END IF; gana la primera condición verdadera (como el CASE).","Ciclos: LOOP+EXIT WHEN (crudo) · WHILE (pregunta antes) · FOR i IN 1..n (contador gratis).","Si una consulta lo resuelve, la consulta gana: el ciclo fila-por-fila es el anti-patrón clásico."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-l02-control';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Cursores: recorrer resultados
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuando sí necesitas ir fila por fila","body":"El SELECT INTO trae UNA fila; ¿y cuando el proceso legítimamente necesita recorrer MUCHAS — enviar un recordatorio POR CADA cita de mañana, generar un documento POR CADA receta? Ese es el CURSOR: un apuntador con nombre a un conjunto de resultados, que se recorre fila por fila. La mecánica clásica tiene cuatro tiempos — declarar el CURSOR con su consulta, OPEN, FETCH fila por fila, CLOSE — pero el oficio moderno usa casi siempre su forma compacta: el CURSOR FOR LOOP — FOR registro IN (consulta) LOOP … END LOOP; — que abre, trae, itera y cierra SOLO, sin que puedas olvidar el CLOSE. Dentro del ciclo, cada fila llega como un registro con la forma de la consulta: registro.paciente_id, registro.fecha. Y la advertencia sigue en pie: el cursor es para procesos por-fila REALES — el UPDATE de conjunto sigue siendo del SQL."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Los recordatorios de mañana","code":"BEGIN\n  FOR r IN (SELECT p.nombre, c.fecha\n            FROM   citas c\n            JOIN   pacientes p ON p.paciente_id = c.paciente_id\n            WHERE  TRUNC(c.fecha) = TRUNC(SYSDATE) + 1\n            ORDER  BY c.fecha) LOOP\n    DBMS_OUTPUT.PUT_LINE('Recordatorio para ' || r.nombre\n                         || ' — ' || TO_CHAR(r.fecha, 'HH24:MI'));\n  END LOOP;\nEND;\n/","result":{"columns":["DBMS_OUTPUT"],"rows":[["Recordatorio para Laura Méndez — 09:00"],["Recordatorio para Hugo Castañeda — 10:30"],["Recordatorio para Sofía Aguirre — 12:15"]],"note":"El cursor FOR loop en su hábitat: la consulta (con su JOIN del m06 y su TRUNC del m05) define el conjunto, y el ciclo procesa cada fila como r.nombre y r.fecha. OPEN, FETCH y CLOSE ocurrieron solos — imposible olvidar el cierre."}}$j$),
  (3, 'texto', $j${"title":"La forma explícita (y por qué casi nunca la usarás)","body":"La forma clásica existe y las certificaciones la preguntan: CURSOR c_citas IS SELECT …; en el DECLARE, y luego OPEN c_citas; FETCH c_citas INTO variables; (en un ciclo, vigilando el atributo c_citas%NOTFOUND para saber cuándo se acabaron las filas) y CLOSE c_citas;. Sus atributos — %FOUND, %NOTFOUND, %ROWCOUNT (cuántas van) — dan control fino. ¿Cuándo la necesitas de verdad? Casos raros: recorrer dos cursores coordinados, cortar a la mitad con lógica compleja, mantener el cursor abierto entre operaciones. Para todo lo demás — el 95% — el FOR loop es superior precisamente porque administra el ciclo de vida por ti: el cursor olvidado sin CLOSE es una fuga de recursos clásica que el FOR loop vuelve imposible. Conoce la forma larga, usa la corta."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un CURSOR en PL/SQL?","options":["Una tabla temporal","Un apuntador con nombre a un CONJUNTO de resultados, para recorrerlo fila por fila — el complemento del SELECT INTO (que solo trae una)","El puntero del mouse","Un tipo de índice"],"correctIndex":1,"feedback":{"correct":"Correcto. INTO para una fila; cursor para recorrer muchas — cuando el proceso por-fila es genuino.","incorrect":"El cursor apunta a un resultado de varias filas y permite procesarlas una a una: recordatorios, documentos, envíos."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué el CURSOR FOR LOOP es la forma preferida del oficio?","options":["Porque es la única que acepta JOINs","Porque abre, trae, itera y CIERRA solo: el CLOSE olvidado (la fuga de recursos clásica de la forma explícita) se vuelve imposible","Porque es más rápida que el SQL puro","Porque no necesita consulta"],"correctIndex":1,"feedback":{"correct":"Correcto. El ciclo de vida administrado: menos código y cero cursores huérfanos.","incorrect":"El FOR loop administra OPEN/FETCH/CLOSE por ti — la forma explícita deja el CLOSE en tus manos, y las manos olvidan."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En la forma explícita de cursores, ¿qué informa el atributo %NOTFOUND?","options":["Que el cursor no existe","Que el último FETCH ya NO trajo fila: la señal para salir del ciclo — se acabaron los resultados","Que la tabla está vacía desde el inicio","Que faltan permisos"],"correctIndex":1,"feedback":{"correct":"Correcto. %NOTFOUND tras cada FETCH es el 'ya no hay': el EXIT WHEN clásico de la forma larga.","incorrect":"%NOTFOUND se enciende cuando el FETCH regresa vacío: el momento de cerrar el ciclo (y el cursor)."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Cursores","points":["Cursor = apuntador con nombre a un conjunto de resultados, recorrible fila por fila.","CURSOR FOR LOOP: FOR r IN (consulta) LOOP … — abre, trae, itera y cierra SOLO.","Cada fila llega como registro con la forma de la consulta (r.nombre, r.fecha).","Forma explícita (OPEN/FETCH/CLOSE + %NOTFOUND/%ROWCOUNT): control fino para casos raros — y el CLOSE es tu responsabilidad.","El cursor es para procesos por-fila GENUINOS: el trabajo de conjunto sigue siendo del SQL."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-l03-cursores';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Procedures y functions
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Del bloque suelto al ciudadano con nombre","body":"El bloque anónimo se ejecuta y se olvida; para que la lógica VIVA en la base — con nombre, versionada, invocable por cualquier aplicación — existen dos ciudadanos. El PROCEDURE hace UNA TAREA: CREATE OR REPLACE PROCEDURE registrar_cobro(p_cita_id IN NUMBER, p_monto IN NUMBER) AS BEGIN … END; — recibe parámetros IN (entran), OUT (salen) o IN OUT (ambas), y se invoca por su nombre. La FUNCTION DEVUELVE UN VALOR (RETURN NUMBER, RETURN VARCHAR2…) y por eso puede usarse DENTRO de una consulta SQL, como las funciones de fila que ya usas: SELECT cita_id, tarifa_de(costo) FROM citas. La regla para elegir: ¿el objetivo es HACER algo (registrar, procesar, enviar)? → procedure. ¿Es CALCULAR un valor para usarlo donde haga falta? → function."}$j$),
  (2, 'ejemplo_sql', $j${"title":"Una de cada especie","code":"-- La FUNCTION calcula y devuelve (usable en SQL):\nCREATE OR REPLACE FUNCTION tarifa_de(p_costo IN NUMBER)\nRETURN VARCHAR2 AS\nBEGIN\n  RETURN CASE\n           WHEN p_costo >= 800 THEN 'premium'\n           WHEN p_costo >= 300 THEN 'estandar'\n           ELSE 'social'\n         END;\nEND;\n/\n\n-- El PROCEDURE hace una tarea completa:\nCREATE OR REPLACE PROCEDURE registrar_cobro(\n  p_cita_id IN citas.cita_id%TYPE,\n  p_monto   IN citas.costo%TYPE\n) AS\nBEGIN\n  UPDATE citas SET costo = p_monto WHERE cita_id = p_cita_id;\nEND;\n/\n\n-- Y la función, viviendo dentro de un SELECT:\nSELECT cita_id, costo, tarifa_de(costo) AS tarifa FROM citas;","result":{"columns":["CITA_ID","COSTO","TARIFA"],"rows":[["517","950","premium"],["523","350","estandar"],["519","120","social"]],"note":"La function devuelve un valor y por eso el SELECT puede llamarla como a NVL o UPPER; el procedure ejecuta su tarea cuando alguien lo invoca. Nota los parámetros anclados con %TYPE: el contrato del esquema, otra vez."}}$j$),
  (3, 'texto', $j${"title":"Por qué guardar la lógica en la base","body":"Tres razones por las que estos ciudadanos valen su residencia. CENTRALIZACIÓN: la regla de tarifas vive UNA vez — la app web, el reporte mensual y el proceso nocturno llaman a tarifa_de() y ninguno mantiene su propia copia (¿recuerdas la redundancia y sus anomalías del m03? — también aplica al CÓDIGO). SEGURIDAD, y esta es fina: puedes otorgar GRANT EXECUTE sobre registrar_cobro SIN dar UPDATE sobre citas — el usuario solo puede tocar la tabla A TRAVÉS del procedimiento, por el camino que tú pavimentaste: mínimo privilegio del m08, versión quirúrgica. RENDIMIENTO: la lógica corre junto a los datos (el superpoder del bloque, ahora permanente). La contraparte honesta: la lógica en la base debe versionarse y probarse con la misma seriedad que cualquier código — un procedure es software, no un apunte."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es LA diferencia entre un PROCEDURE y una FUNCTION?","options":["El procedure es más rápido","La FUNCTION devuelve un valor (RETURN) y puede usarse DENTRO de una consulta SQL; el PROCEDURE ejecuta una tarea y se invoca por nombre","La function no acepta parámetros","Son sinónimos"],"correctIndex":1,"feedback":{"correct":"Correcto. Calcular-y-devolver (function, invocable desde SELECT) vs hacer-una-tarea (procedure).","incorrect":"La function retorna un valor — por eso vive feliz dentro de un SELECT; el procedure hace algo y se llama por su nombre."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué significan los modos de parámetro IN, OUT e IN OUT?","options":["Niveles de seguridad","IN: el valor ENTRA al programa · OUT: el programa lo DEVUELVE por ahí · IN OUT: entra, se modifica y sale","Tipos de datos","Orden de los parámetros"],"correctIndex":1,"feedback":{"correct":"Correcto. La dirección del dato: entrada, salida, o ambas — el contrato de cada parámetro.","incorrect":"IN entra (el modo por defecto), OUT sale, IN OUT viaja de ida y vuelta: así se declara qué hace el programa con cada dato."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Seguridad fina: ¿qué logra dar GRANT EXECUTE sobre el procedure registrar_cobro SIN dar UPDATE sobre la tabla citas?","options":["Nada: sin UPDATE el procedure falla","Que el usuario solo pueda modificar citas A TRAVÉS del procedimiento — por el camino pavimentado, con sus validaciones: mínimo privilegio quirúrgico","Que el procedure corra más rápido","Que el usuario vea la tabla completa"],"correctIndex":1,"feedback":{"correct":"Correcto. La tabla queda cerrada y el procedimiento es la única puerta: imposible el UPDATE suelto sin WHERE de un usuario distraído.","incorrect":"El procedure ejecuta con los permisos de su dueño: el usuario con solo EXECUTE toca la tabla únicamente por esa puerta controlada."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Procedures y functions","points":["PROCEDURE hace una tarea · FUNCTION devuelve un valor (y vive dentro del SQL).","Parámetros: IN entra · OUT sale · IN OUT ambas — anclados con %TYPE.","CREATE OR REPLACE: la lógica con nombre y residencia permanente en la base.","Centralización (la regla vive una vez), seguridad (EXECUTE sin permisos de tabla) y rendimiento (junto a los datos).","La lógica en la base es SOFTWARE: se versiona y se prueba como tal."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-l04-procedures';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Triggers: el código que se dispara
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Código que nadie llama","body":"Procedures y functions esperan a que alguien los invoque; el TRIGGER se DISPARA SOLO cuando ocurre un evento sobre una tabla: BEFORE o AFTER (antes o después) de un INSERT, UPDATE o DELETE, y con FOR EACH ROW si debe ejecutarse por CADA fila afectada (sin esa cláusula, corre una vez por sentencia). Dentro del trigger de fila viven dos personajes que ya conoces en espíritu: :OLD (la fila como ERA) y :NEW (la fila como QUEDARÁ) — en un UPDATE existen ambos, en un INSERT solo :NEW, en un DELETE solo :OLD. ¿Te suena a algo del m3a? Exacto: el trigger es el mecanismo perfecto para el LOGGING/JOURNALING — anotar el valor viejo antes de pisarlo — que el modelado temporal te prometió."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El diario de salarios, cumplido","code":"-- La promesa del m3a: anotar el valor viejo ANTES de pisarlo\nCREATE OR REPLACE TRIGGER trg_auditar_costo\nAFTER UPDATE OF costo ON citas\nFOR EACH ROW\nBEGIN\n  INSERT INTO auditoria_costos\n    (cita_id, costo_anterior, costo_nuevo, modificado_en)\n  VALUES\n    (:OLD.cita_id, :OLD.costo, :NEW.costo, SYSDATE);\nEND;\n/","result":{"columns":["RESULTADO"],"rows":[["Trigger TRG_AUDITAR_COSTO created."]],"note":"Desde ahora, CADA cambio de costo deja su huella sin que ninguna aplicación tenga que acordarse: :OLD.costo era, :NEW.costo será, SYSDATE cuándo. El journaling del modelado temporal, ejecutándose solo — y a prueba de aplicaciones olvidadizas: el trigger vive en la base, no en el código de cada app."}}$j$),
  (3, 'texto', $j${"title":"La regla vinculante (y los riesgos del poder invisible)","body":"El trigger es poderoso y por eso la regla del m04 vuelve con toda su fuerza: las DECLARATIVAS van ANTES que los triggers. ¿costo >= 0? Una CHECK, jamás un trigger: la constraint es más barata, siempre activa, visible en el diccionario e imposible de esquivar. El trigger se gana su lugar solo donde las declarativas NO alcanzan: auditoría/journaling (el ejemplo de arriba), completar valores calculados complejos, reglas que cruzan tablas de formas que ninguna constraint expresa. Y sus riesgos son reales: es LÓGICA INVISIBLE — el UPDATE parece inocente y por debajo disparó tres triggers que nadie recuerda; puede encadenarse (un trigger dispara DML que dispara otro trigger…) hasta volver el sistema indescifrable; y complica la depuración ('¿QUIÉN cambió esta fila?'). La disciplina: pocos, documentados, simples, y jamás para lo que una constraint ya sabe hacer."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué distingue a un TRIGGER de un procedure?","options":["El trigger es más rápido","NADIE lo llama: se DISPARA solo ante un evento sobre la tabla (BEFORE/AFTER INSERT/UPDATE/DELETE, por fila con FOR EACH ROW)","El trigger no puede contener SQL","El trigger devuelve un valor"],"correctIndex":1,"feedback":{"correct":"Correcto. Código con resorte propio: el evento lo dispara, sin invocación de nadie.","incorrect":"El procedure espera invocación; el trigger reacciona al evento por sí solo — esa autonomía es su poder y su riesgo."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En un trigger FOR EACH ROW sobre un UPDATE, ¿qué contienen :OLD y :NEW?","options":["El nombre viejo y nuevo de la tabla",":OLD es la fila como ERA y :NEW como QUEDARÁ — la pareja perfecta para el journaling: anotar el valor viejo antes de pisarlo","Dos copias idénticas de la fila","Los permisos del usuario"],"correctIndex":1,"feedback":{"correct":"Correcto. El antes y el después, disponibles en el instante exacto del cambio: el diario del m3a, cumplido.","incorrect":":OLD = la fila anterior, :NEW = la entrante. (En INSERT solo hay :NEW; en DELETE solo :OLD.)"}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Regla vinculante: para vigilar costo >= 0, ¿CHECK o trigger? ¿Y cuándo SÍ se gana su lugar el trigger?","options":["Trigger: es más moderno","CHECK sin dudar (declarativas ANTES que triggers: baratas, siempre activas, inesquivables). El trigger queda para lo que ellas no alcanzan: auditoría/journaling, reglas entre tablas complejas","Trigger, porque las CHECK son lentas","Cualquiera da igual"],"correctIndex":1,"feedback":{"correct":"Correcto. La regla del m04 con su excepción precisa: el trigger es el plan B legítimo, no el reflejo.","incorrect":"Lo que una constraint sabe vigilar, la constraint lo vigila. El trigger se reserva para auditoría y reglas que ninguna declarativa expresa."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Triggers","points":["Se dispara SOLO ante eventos: BEFORE/AFTER · INSERT/UPDATE/DELETE · FOR EACH ROW por fila.",":OLD = la fila como era · :NEW = como quedará (INSERT solo :NEW; DELETE solo :OLD).","Uso estrella: auditoría/journaling — el diario del modelado temporal, automático.","REGLA VINCULANTE: declarativas ANTES que triggers — la CHECK gana siempre que alcance.","Riesgos: lógica invisible, cascadas, depuración difícil — pocos, simples y documentados."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-l05-triggers';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Excepciones: fallar con elegancia
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La tercera sección cobra vida","body":"Los errores en tiempo de ejecución — la cita que no existe, el INTO que trajo dos filas, la división entre cero — no tienen por qué tumbar tu bloque: la sección EXCEPTION los atrapa y decide qué hacer. Su sintaxis es un CASE de errores: EXCEPTION WHEN NO_DATA_FOUND THEN … WHEN TOO_MANY_ROWS THEN … WHEN OTHERS THEN …; — Oracle trae las excepciones comunes YA NOMBRADAS (NO_DATA_FOUND: el INTO sin filas; TOO_MANY_ROWS: el INTO con varias; ZERO_DIVIDE; DUP_VAL_ON_INDEX: violaste una PK/UNIQUE…) y OTHERS es la red final que atrapa lo innombrado. Cuando algo truena en el BEGIN, el control SALTA a la sección EXCEPTION, ejecuta el manejador que coincida… y el bloque termina con dignidad en lugar de escupir un error crudo al usuario."}$j$),
  (2, 'ejemplo_sql', $j${"title":"El mismo bloque, ahora indestructible","code":"DECLARE\n  v_costo  citas.costo%TYPE;\nBEGIN\n  SELECT costo INTO v_costo\n  FROM   citas\n  WHERE  cita_id = 999999;   -- esta cita no existe\n\n  DBMS_OUTPUT.PUT_LINE('Costo: ' || v_costo);\nEXCEPTION\n  WHEN NO_DATA_FOUND THEN\n    DBMS_OUTPUT.PUT_LINE('La cita no existe: revisa el folio.');\n  WHEN TOO_MANY_ROWS THEN\n    DBMS_OUTPUT.PUT_LINE('Folio ambiguo: más de una cita.');\nEND;\n/","result":{"columns":["DBMS_OUTPUT"],"rows":[["La cita no existe: revisa el folio."]],"note":"El SELECT INTO rompió su promesa (cero filas) y el control saltó a EXCEPTION: el manejador de NO_DATA_FOUND respondió con un mensaje útil en lugar de un error crudo. El bloque terminó con elegancia — y quien lo llamó recibió información, no metralla."}}$j$),
  (3, 'texto', $j${"title":"El pecado capital: tragarse el error","body":"El poder de atrapar errores trae su tentación: WHEN OTHERS THEN NULL; — 'pase lo que pase, no hagas nada'. Es el PECADO CAPITAL de PL/SQL: el error ocurre, se atrapa, se descarta… y el proceso continúa como si nada, corrompiendo en silencio. El cobro que falló no se registró, nadie lo supo, y el faltante aparece en el corte de fin de mes — irrastreable. Las reglas de la casa: (1) atrapa las excepciones ESPECÍFICAS que sabes manejar, con una respuesta útil cada una; (2) OTHERS solo para registrar el error (en tu tabla de bitácora — el trigger y el journaling saben cómo) y RE-LANZARLO con RAISE; — que la falla se vea, no que se esconda; (3) para reglas de negocio propias, RAISE_APPLICATION_ERROR(-20001, 'El costo no puede bajar') lanza TU error con TU mensaje. Fallar ruidosamente es profesional; fallar en silencio es sabotaje."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace la sección EXCEPTION cuando algo truena dentro del BEGIN?","options":["Reinicia el bloque desde el principio","El control SALTA a ella y ejecuta el manejador que coincida (WHEN NO_DATA_FOUND / TOO_MANY_ROWS / OTHERS): el bloque termina con un mensaje útil en vez de un error crudo","Deshace toda la base","Nada: es decorativa"],"correctIndex":1,"feedback":{"correct":"Correcto. El CASE de errores: cada excepción con su respuesta, y OTHERS como red final.","incorrect":"Al tronar el BEGIN, el control salta a EXCEPTION: el manejador correcto convierte la falla en información."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué excepciones lanza SELECT … INTO cuando su promesa de una-fila se rompe?","options":["ORA-00979 y ORA-00060","NO_DATA_FOUND (cero filas) y TOO_MANY_ROWS (más de una): las dos caras de la promesa rota — ambas ya nombradas por Oracle","ZERO_DIVIDE en ambos casos","Ninguna: devuelve nulo"],"correctIndex":1,"feedback":{"correct":"Correcto. Cero o muchas: cada traición del INTO tiene su excepción nombrada y su manejador natural.","incorrect":"El INTO promete exactamente una fila: NO_DATA_FOUND con cero, TOO_MANY_ROWS con varias — y EXCEPTION las atrapa por nombre."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué WHEN OTHERS THEN NULL; es el 'pecado capital' de PL/SQL?","options":["Porque usa una palabra reservada","Porque TRAGA cualquier error en silencio: el proceso continúa como si nada, corrompiendo sin dejar rastro — la falla invisible es la más cara de todas","Porque es sintaxis inválida","Porque hace lento el bloque"],"correctIndex":1,"feedback":{"correct":"Correcto. Fallar ruidosamente es profesional; fallar en silencio es sabotaje. OTHERS registra y RE-LANZA (RAISE), jamás descarta.","incorrect":"El THEN NULL descarta el error y sigue: el faltante aparecerá semanas después, irrastreable. OTHERS es para registrar y re-lanzar."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Excepciones","points":["EXCEPTION es el CASE de errores: WHEN excepción THEN respuesta, con OTHERS como red final.","Nombradas de fábrica: NO_DATA_FOUND, TOO_MANY_ROWS, ZERO_DIVIDE, DUP_VAL_ON_INDEX…","Atrapa lo ESPECÍFICO que sabes manejar, con respuesta útil.","OTHERS: registrar y RE-LANZAR (RAISE;) — WHEN OTHERS THEN NULL es el pecado capital.","RAISE_APPLICATION_ERROR(-20xxx, 'mensaje'): tus reglas de negocio lanzan su propio error."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-l06-excepciones';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Práctica: tu primer bloque completo (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Caja necesita un verificador de tarifas: dado el folio de una cita, imprimir si es premium o normal — sin tronar cuando el folio no exista. Escribe el bloque PL/SQL completo sobre la tabla citas (PK cita_id, columna costo).","instructions":["DECLARE: una variable v_costo anclada a la columna: citas.costo%TYPE.","BEGIN: trae el costo con SELECT costo INTO v_costo FROM citas WHERE cita_id = 519.","Decide: IF v_costo >= 800 THEN imprime 'Tarifa premium' (con DBMS_OUTPUT.PUT_LINE); ELSE imprime 'Tarifa normal'; END IF.","EXCEPTION: WHEN NO_DATA_FOUND THEN imprime 'Folio inexistente'. Cierra el bloque con END."],"initialCode":"-- Verificador de tarifas de caja (folio 519):\n-- bloque completo con %TYPE, INTO, IF y NO_DATA_FOUND.\n\nDECLARE\n  -- tu variable aquí\nBEGIN\n  NULL; -- tu lógica aquí\nEND;","validators":["declare\\s+v_costo\\s+citas\\.costo%type","select\\s+costo\\s+into\\s+v_costo\\s+from\\s+citas\\s+where\\s+cita_id\\s*=\\s*519","if\\s+v_costo\\s*>=\\s*800\\s+then","dbms_output\\.put_line","exception\\s+when\\s+no_data_found\\s+then"],"mockOutput":{"columns":["DBMS_OUTPUT"],"rows":[["Tarifa normal"]],"note":"La cita 519 cuesta 350: tarifa normal. Y si caja teclea un folio inexistente, el bloque responde 'Folio inexistente' en lugar de escupir ORA-01403 — la diferencia entre una herramienta y un susto."},"hints":["El DECLARE lleva exactamente: v_costo citas.costo%TYPE; — anclada, no NUMBER(8,2).","Dentro del BEGIN: el SELECT … INTO (filtrado por la PK) y después el IF v_costo >= 800 THEN … ELSE … END IF; con DBMS_OUTPUT.PUT_LINE en cada rama.","La sección EXCEPTION va después de la lógica y antes del END final: EXCEPTION WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('Folio inexistente');"],"successMessage":"Bloque completo y blindado: variable anclada con %TYPE, INTO con su promesa vigilada, decisión con IF y la excepción manejada con elegancia. Las cuatro secciones del bloque trabajando juntas — PL/SQL ya es tuyo.","failMessage":"Revisa las cinco piezas: DECLARE v_costo citas.costo%TYPE · SELECT costo INTO v_costo FROM citas WHERE cita_id = 519 · IF v_costo >= 800 THEN · DBMS_OUTPUT.PUT_LINE en las ramas · EXCEPTION WHEN NO_DATA_FOUND THEN."}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-l07-practica-plsql';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región (jefe del módulo)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La duodécima región","body":"Byte cruzó la última frontera técnica: aquí el SQL gana pasos, decisiones y memoria — y el código vive dentro de la base. Once preguntas custodian la región: bloques, promesas del INTO, cursores, ciudadanos con nombre, resortes automáticos y errores con elegancia. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"El esqueleto MÍNIMO de un bloque PL/SQL válido es…","options":["DECLARE … END;","BEGIN … END; — DECLARE y EXCEPTION son opcionales y se suman cuando hacen falta","DECLARE … EXCEPTION;","BEGIN … COMMIT;"],"correctIndex":1,"feedback":{"correct":"Correcto. Dos secciones obligatorias, dos opcionales: el bloque crece según la tarea.","incorrect":"BEGIN y END; bastan: variables (DECLARE) y manejo de errores (EXCEPTION) son secciones opcionales."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué declarar v_costo citas.costo%TYPE es superior a v_costo NUMBER(8,2)?","options":["Ocupa menos memoria","Queda ANCLADA a la columna real: si la tabla evoluciona (NUMBER(10,2)), la variable la sigue — la copia manual envejece en silencio","Acepta nulos","Es requisito de Oracle 19c"],"correctIndex":1,"feedback":{"correct":"Correcto. Contratos del esquema, no copias: el %TYPE es mantenimiento que se hace solo.","incorrect":"%TYPE amarra la variable al tipo vigente de la columna — la declaración copiada a mano se desactualiza sin avisar."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un SELECT … INTO devuelve cero filas. ¿Qué ocurre exactamente?","options":["La variable queda en nulo y el bloque sigue","Explota la excepción NO_DATA_FOUND: el INTO exige exactamente UNA fila — y el control salta a la sección EXCEPTION si existe","Devuelve cero","El bloque se reinicia"],"correctIndex":1,"feedback":{"correct":"Correcto. La promesa de una-fila rota por abajo: NO_DATA_FOUND (y por arriba, TOO_MANY_ROWS).","incorrect":"El INTO no deja la variable en nulo: lanza NO_DATA_FOUND. Por eso el manejador (o el filtro por PK) es parte del diseño."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Hay que subir 10% el costo de 5,000 citas. Tu colega propone un cursor FOR loop con un UPDATE adentro, fila por fila. ¿La observación profesional?","options":["Perfecto: los cursores son para eso","Que UN solo UPDATE con WHERE lo hace de un golpe: el ciclo fila-por-fila para trabajo de CONJUNTO es el anti-patrón clásico — el cursor es para procesos por-fila genuinos (documentos, envíos)","Que use dos cursores","Que lo haga a mano"],"correctIndex":1,"feedback":{"correct":"Correcto. Si una consulta lo resuelve, la consulta gana: el motor en un golpe vs cinco mil viajes.","incorrect":"El trabajo de conjunto es del SQL (UPDATE con WHERE). El cursor se gana su lugar cuando cada fila exige un proceso individual real."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué el CURSOR FOR LOOP es preferible a OPEN/FETCH/CLOSE en el 95% de los casos?","options":["Porque permite modificar la tabla","Porque administra el ciclo de vida completo (abre, trae, itera, CIERRA solo): el CLOSE olvidado — la fuga clásica de la forma explícita — se vuelve imposible","Porque es la única forma con JOINs","Porque no consume memoria"],"correctIndex":1,"feedback":{"correct":"Correcto. Menos código y cero cursores huérfanos: la forma larga queda para el control fino de casos raros.","incorrect":"El FOR loop hace OPEN/FETCH/CLOSE por ti: imposible olvidar el cierre. La forma explícita existe para los casos que exigen control manual."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de las dos puede usarse DENTRO de una consulta SQL (SELECT tarifa_de(costo) FROM citas), y por qué?","options":["El procedure, porque hace tareas","La FUNCTION: devuelve un valor con RETURN — el SELECT la llama como a NVL o UPPER; el procedure no devuelve valor y se invoca aparte","Ambas por igual","Ninguna: el SQL no llama código"],"correctIndex":1,"feedback":{"correct":"Correcto. Devolver-un-valor es el boleto de entrada al SELECT: por eso la function vive feliz dentro del SQL.","incorrect":"Solo la function (con su RETURN) puede vivir dentro de una consulta; el procedure ejecuta tareas y se llama por nombre."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué patrón de seguridad habilita GRANT EXECUTE sobre un procedure sin dar permisos sobre sus tablas?","options":["Ninguno: es un error de configuración","La tabla queda CERRADA y el procedimiento es la única puerta: el usuario modifica datos solo por el camino pavimentado con validaciones — mínimo privilegio quirúrgico","El usuario obtiene permisos completos indirectamente","Solo funciona con SELECT"],"correctIndex":1,"feedback":{"correct":"Correcto. El m08 y el m10 se ensamblan: EXECUTE sin permisos de tabla convierte al procedure en la aduana única.","incorrect":"El procedure corre con los permisos de su dueño: quien solo tiene EXECUTE toca los datos únicamente a través de él."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"En un trigger AFTER UPDATE … FOR EACH ROW, quieres guardar el valor que la fila tenía ANTES del cambio. ¿Dónde vive?","options":["En :NEW","En :OLD — la fila como ERA; :NEW trae la fila como QUEDARÁ: la pareja exacta del journaling","En SYSDATE","En %ROWCOUNT"],"correctIndex":1,"feedback":{"correct":"Correcto. :OLD.costo al diario, :NEW.costo a la tabla: el modelado temporal del m3a, ejecutándose solo.","incorrect":":OLD es el antes, :NEW el después — el trigger de fila los ofrece en el instante exacto del cambio."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Regla vinculante, una vez más: ¿cuándo se gana un trigger su lugar frente a una constraint?","options":["Siempre que haya UPDATE de por medio","SOLO donde las declarativas no alcanzan: auditoría/journaling, reglas complejas entre tablas — lo que una CHECK/FK/UNIQUE sepa vigilar, lo vigila la constraint","Cuando la tabla es grande","Cuando hay más de dos columnas"],"correctIndex":1,"feedback":{"correct":"Correcto. Declarativas antes que triggers: la CHECK es más barata, siempre activa e inesquivable. El trigger es el plan B legítimo.","incorrect":"El trigger no compite con las constraints: las complementa donde ellas no llegan (auditoría, lógica multi-tabla)."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Encuentras WHEN OTHERS THEN NULL; en un procedure de cobros heredado. ¿El diagnóstico?","options":["Código defensivo excelente","El PECADO CAPITAL: cualquier error se traga en silencio y el proceso sigue 'exitoso' — los cobros fallidos se pierden sin rastro. Se corrige: registrar el error y RE-LANZARLO con RAISE","Un optimizador de rendimiento","Sintaxis inválida que no compila"],"correctIndex":1,"feedback":{"correct":"Correcto. Fallar en silencio es sabotaje: el OTHERS legítimo registra en bitácora y re-lanza para que la falla SE VEA.","incorrect":"THEN NULL descarta el error y finge éxito: el faltante aparecerá en el corte mensual, irrastreable. Registrar y RAISE."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final de entrevista: 'necesitamos que ningún costo sea negativo, auditar cada cambio de costo, y que caja aplique cobros sin tocar la tabla directo. Diseña la solución.' Tu respuesta senior:","options":["Tres triggers, uno para cada cosa","CHECK (costo >= 0) para la regla — declarativa antes que trigger; un TRIGGER AFTER UPDATE con :OLD/:NEW para la auditoría — su uso legítimo; y un PROCEDURE registrar_cobro con GRANT EXECUTE (sin UPDATE directo) como única puerta de caja","Un solo procedure gigante que haga todo","Validarlo todo en la aplicación web"],"correctIndex":1,"feedback":{"correct":"Impecable. Cada requisito con SU herramienta: constraint para la regla, trigger para el diario, procedure como aduana — el módulo entero en una respuesta.","incorrect":"La respuesta senior reparte: la regla simple a la CHECK (vinculante), la auditoría al trigger (:OLD/:NEW), y el acceso controlado al procedure con EXECUTE."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'sql-oracle' and l.slug = 'm10-x01-examen';
