-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 049 — Git desde Cero · M1: Fundamentos y el primer commit
-- ═══════════════════════════════════════════════════════════════════
-- Unidad 1 del temario (bloques 1-6 + Práctica 1). Cubre: qué problema
-- resuelve el control de versiones, instalación/identidad, crear un
-- repositorio, LAS TRES ÁREAS + HEAD (Diagrama 1.1), el primer commit
-- y la lectura del historial. Práctica: mi primer historial.
-- Precisiones vinculantes de este módulo: git add NO es "subir"
-- (prepara, no publica); un commit NO es "guardar" (es una unidad
-- lógica con autor/fecha/mensaje/árbol/padre).
-- Hilo conductor: el repositorio del sistema de la clínica.
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos;
-- la práctica usa la vía regex + mockOutput (curso language = bash).
-- El curso SIGUE is_published = false: nada visible hasta el flip final.
-- Idempotente: borra y recrea las lecciones de ESTE módulo.
-- Ejecutar DESPUÉS de 048 (estructura).
-- ═══════════════════════════════════════════════════════════════════

delete from public.lessons
where module_id = (
  select m.id from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'git-desde-cero' and m.slug = 'm01-fundamentos'
);

insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m01-l01-problema',     'El problema que resuelve Git',        'leccion',  20, 1),
       ('m01-l02-identidad',    'Instalación e identidad',             'leccion',  20, 2),
       ('m01-l03-repositorio',  'Crear un repositorio',                'leccion',  20, 3),
       ('m01-l04-tres-areas',   'Las tres áreas y HEAD',               'leccion',  20, 4),
       ('m01-l05-primer-commit','El primer commit',                    'leccion',  20, 5),
       ('m01-l06-historial',    'Consultar el historial',              'leccion',  20, 6),
       ('m01-l07-practica',     'Práctica: mi primer historial',       'practica', 20, 7),
       ('m01-x01-examen',       'Examen: Fundamentos',                 'examen',   40, 8)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'git-desde-cero' and m.slug = 'm01-fundamentos';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · El problema que resuelve Git
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"informe_final_v2_AHORA_SI.sql","body":"Lo has visto (o lo has hecho): una carpeta con proyecto, proyecto_final, proyecto_final_v2, proyecto_final_ahora_si, proyecto_final_ESTE_ES. Cada nombre es un intento de contestar preguntas que la carpeta no puede responder: ¿cuál es la versión buena? ¿qué cambió entre una y otra? ¿quién tocó esto? ¿por qué? ¿cómo vuelvo a como estaba el martes? El CONTROL DE VERSIONES resuelve exactamente eso: en lugar de copias con nombres cada vez más desesperados, un HISTORIAL — una línea de tiempo de tu proyecto donde cada punto guarda qué cambió, cuándo, quién y por qué, y al que puedes volver cuando quieras. Git es la herramienta de control de versiones que usa prácticamente toda la industria del software."}$j$),
  (2, 'texto', $j${"title":"Git no es GitHub (y es distribuido)","body":"Confusión que conviene despejar el primer día: GIT es el programa que corre en TU computadora y lleva el historial; GITHUB (y GitLab, y otros) son SERVICIOS EN LÍNEA donde ese historial puede vivir también, para compartirlo con otras personas. Puedes usar Git toda una vida sin GitHub — el historial es tuyo y local. Y una propiedad clave: Git es DISTRIBUIDO. No hay un servidor central del que dependas para trabajar: cada quien tiene una copia COMPLETA del historial en su equipo. Puedes commitear, ver el historial y crear ramas sin conexión a internet — el trabajo con otros (la nube) llega en el módulo 4, y es opcional para empezar. Primero, Git en tu máquina."}$j$),
  (3, 'texto', $j${"title":"El caso de la clínica","body":"Acompáñanos con un caso real que recorrerá todo el curso: mantienes el REPOSITORIO del sistema de la clínica — los scripts SQL, el código Python, la documentación que otros cursos construyeron. Un lunes, una consulta que funcionaba empieza a dar resultados raros. Sin control de versiones, la investigación es un interrogatorio a ciegas. Con Git, cinco preguntas tienen respuesta inmediata: QUIÉN cambió esa consulta, CUÁNDO, POR QUÉ (el mensaje del cambio lo explica), QUÉ archivos tocó, y CÓMO recuperar la versión que sí funcionaba. Ese es el valor que vas a construir comando a comando: no memorizar Git, sino poder responder esas preguntas sobre tu propio trabajo."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre Git y GitHub?","options":["Son dos nombres para lo mismo","Git es el programa de control de versiones que corre en tu computadora; GitHub es un servicio en línea donde ese historial puede alojarse y compartirse — puedes usar Git sin GitHub","GitHub es gratis y Git de pago","Git es para Windows y GitHub para Mac"],"correctIndex":1,"feedback":{"correct":"Correcto. Git es la herramienta (local); GitHub es un lugar donde publicar su historial. Se puede versionar toda la vida sin salir de tu máquina.","incorrect":"Git = el programa que lleva el historial en tu equipo. GitHub = un servicio para alojarlo y colaborar. Lo primero funciona sin lo segundo."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Que Git sea DISTRIBUIDO significa que…","options":["Reparte tus archivos en varios servidores","Cada persona tiene una copia COMPLETA del historial en su equipo: puedes commitear, ver el historial y ramificar sin conexión — no dependes de un servidor central para trabajar","Solo funciona en equipos grandes","Distribuye el trabajo automáticamente"],"correctIndex":1,"feedback":{"correct":"Correcto. Copia completa por persona: el trabajo local no necesita internet ni un servidor central.","incorrect":"Distribuido = cada quien tiene el historial entero localmente. El servidor compartido (la nube) es un punto de encuentro opcional, no un requisito para trabajar."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Una consulta de la clínica empezó a fallar. ¿Cuál de estas preguntas NO puede responderte el control de versiones?","options":["Quién hizo el último cambio a ese archivo","Cuándo y por qué se hizo el cambio","Cómo volver a la versión anterior que funcionaba","Cuál será el próximo error que aparecerá"],"correctIndex":3,"feedback":{"correct":"Correcto. Git documenta el PASADO con precisión (quién, cuándo, por qué, qué, cómo volver); no predice el futuro.","incorrect":"Git responde quién/cuándo/por qué/qué y cómo recuperar — todo sobre lo que YA pasó. Adivinar el próximo error no es su trabajo."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — El problema","points":["El control de versiones reemplaza las copias (proyecto_final_v2_ahora_si) por un HISTORIAL consultable.","Cada punto del historial guarda qué cambió, cuándo, quién y por qué — y puedes volver a él.","Git = el programa local; GitHub/GitLab = servicios para alojar y compartir ese historial.","Git es DISTRIBUIDO: copia completa por persona, trabajo local sin servidor central.","La meta del curso: poder responder quién/cuándo/por qué/qué/cómo-volver sobre tu propio trabajo."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-l01-problema';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Instalación e identidad
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Comprobar que Git está listo","body":"Antes de versionar nada, Git debe estar instalado y saber QUIÉN eres. Lo primero se comprueba con git --version: si responde con un número (por ejemplo git version 2.43.0), estás listo; si no, se instala desde git-scm.com (Windows y Mac traen instaladores; en Linux suele venir en el gestor de paquetes). En este curso practicas en el editor de la plataforma, así que no necesitas instalar nada para aprender — pero el mismo comando que escribes aquí es el que correrás en tu terminal el día que trabajes en tu equipo o en el de una empresa. Lo que aprendes es transferible tal cual."}$j$),
  (2, 'texto', $j${"title":"Tu identidad: quién firma cada cambio","body":"Cada commit lleva grabado el nombre y correo de quien lo hizo — es parte de responder 'quién cambió esto'. Por eso, lo primero tras instalar Git es presentarte, una sola vez, con git config: se fija el nombre y el correo, y quedan guardados para todos tus proyectos. La opción --global significa 'para este usuario, en todos sus repositorios'; sin ella, la configuración sería solo del repositorio actual (útil para usar otro correo en un proyecto puntual). La buena práctica: usa el MISMO correo que tendrás en el servicio remoto (GitHub/GitLab), para que tu actividad se vincule correctamente cuando colabores."}$j$),
  (3, 'ejemplo_codigo', $j${"title":"La configuración de la primera vez","code":"# ¿Está instalado?\ngit --version\n\n# Preséntate (una sola vez, para todos tus proyectos)\ngit config --global user.name \"Karen Vargas\"\ngit config --global user.email \"karen@ejemplo.com\"\n\n# Que la rama inicial se llame main (convención actual)\ngit config --global init.defaultBranch main\n\n# Revisar lo configurado\ngit config --list","caption":"--global = para tu usuario, en todos los repos. Sin --global, solo para el repositorio actual — útil para usar otro correo en un proyecto puntual.","result":{"columns":["SALIDA"],"rows":[["git version 2.43.0"],["user.name=Karen Vargas"],["user.email=karen@ejemplo.com"],["init.defaultBranch=main"]],"note":"git config --list muestra la configuración activa. El nombre y el correo quedarán grabados en cada commit que hagas: son tu firma."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Para qué sirve configurar user.name y user.email con git config?","options":["Para iniciar sesión en GitHub","Porque cada commit graba el nombre y correo de su autor: son tu firma en el historial — parte de responder 'quién cambió esto'","Para cifrar el repositorio","Es opcional y decorativo"],"correctIndex":1,"feedback":{"correct":"Correcto. Sin identidad, el historial no puede atribuir los cambios: nombre y correo firman cada commit.","incorrect":"El nombre y correo se graban en CADA commit — son la firma del autor. Por eso se configuran antes de empezar."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace la opción --global en git config --global user.name \"...\"?","options":["Lo publica en internet","Aplica la configuración a TODOS los repositorios de tu usuario, no solo al actual — sin ella sería local a un repo","Lo hace visible para todo el equipo","Requiere permisos de administrador"],"correctIndex":1,"feedback":{"correct":"Correcto. --global = para ti, en todos tus repos. La config local (sin --global) solo afecta al repositorio actual.","incorrect":"--global fija la configuración para tu usuario en todos los proyectos. Omitirla la limita al repositorio en el que estás."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cómo compruebas que Git está instalado y en qué versión?","options":["git status","git --version — responde con el número de versión (p. ej. 'git version 2.43.0') si está instalado","git install","git check"],"correctIndex":1,"feedback":{"correct":"Correcto. git --version es la comprobación estándar: un número de versión confirma que Git está listo.","incorrect":"git --version imprime la versión instalada. Es el primer comando que corres para confirmar que Git existe en el sistema."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Instalación e identidad","points":["git --version comprueba que Git está instalado (responde con el número de versión).","git config --global user.name / user.email fija tu identidad para todos los repos, una sola vez.","--global = para tu usuario en todos los proyectos; sin ella, solo el repositorio actual.","Buena práctica: el mismo correo que en tu servicio remoto, para vincular tu actividad.","git config --list muestra la configuración activa; init.defaultBranch main nombra la rama inicial."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-l02-identidad';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Crear un repositorio
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"De carpeta normal a repositorio","body":"Una carpeta cualquiera es solo archivos: nadie lleva su historia. git init la convierte en un REPOSITORIO — le da a Git la capacidad de rastrear cada cambio dentro de ella. El comando se ejecuta UNA vez, dentro de la carpeta del proyecto, y su efecto es discreto pero enorme: crea una subcarpeta oculta llamada .git. Ahí, y solo ahí, Git guarda TODO el historial, las ramas, la configuración local — el repositorio entero cabe en esa carpeta. Copiar tu proyecto con su .git es copiar su historia completa; borrar .git (sin querer) es volver la carpeta a ser 'archivos sueltos' sin memoria. Por eso .git no se edita a mano: es la base de datos de Git, no un archivo de texto."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Inicializar el repositorio de la clínica","code":"# Dentro de la carpeta del proyecto:\ngit init\n\n# ¿Qué ve Git ahora?\ngit status","caption":"git init se corre UNA vez por proyecto. Crea la carpeta oculta .git — el repositorio entero vive ahí.","result":{"columns":["SALIDA"],"rows":[["Initialized empty Git repository in /clinica/.git/"],["On branch main"],["No commits yet"],["nothing to commit (create/copy files to get started)"]],"note":"'No commits yet': el historial está vacío, listo para su primer punto. git status es el comando que más usarás: siempre te dice en qué estado está el repositorio ahora mismo."}}$j$),
  (3, 'texto', $j${"title":"git status: tu brújula","body":"Si un solo comando de Git merece volverse un reflejo, es git status. No cambia nada — solo INFORMA: en qué rama estás, si hay cambios sin guardar, qué archivos están listos para el próximo commit y cuáles Git aún no rastrea. Ante cualquier duda ('¿en qué punto voy? ¿qué me falta? ¿qué va a pasar si hago commit?'), git status responde. A lo largo del curso lo verás una y otra vez entre comando y comando: es la costumbre profesional de mirar el mapa antes de dar el siguiente paso, en lugar de avanzar a ciegas. Recién inicializado, status te dirá 'No commits yet' — el historial en blanco, esperando."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace git init?","options":["Descarga un proyecto de internet","Convierte la carpeta actual en un repositorio Git creando la subcarpeta oculta .git, donde vivirá todo el historial — se corre una sola vez por proyecto","Sube tus archivos a la nube","Crea un archivo nuevo"],"correctIndex":1,"feedback":{"correct":"Correcto. init le da memoria a la carpeta: nace .git y con ella la capacidad de rastrear cambios.","incorrect":"git init inicializa el repositorio (crea .git). Descargar un proyecto existente es git clone, que verás en el módulo de remotos."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es la carpeta .git y por qué no se edita a mano?","options":["Una copia de respaldo semanal","Es la base de datos de Git: guarda TODO el historial, ramas y configuración local del repositorio — editarla a mano puede corromper el repositorio","Un archivo de texto con notas","La carpeta donde van tus archivos de trabajo"],"correctIndex":1,"feedback":{"correct":"Correcto. .git ES el repositorio: todo el historial cabe ahí. Se maneja con comandos de Git, nunca a mano.","incorrect":".git es la base de datos interna de Git (historial, ramas, config). Tus archivos de trabajo viven fuera de ella; .git se toca solo con comandos."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué caracteriza a git status y por qué se usa tanto?","options":["Guarda los cambios","Solo INFORMA (no cambia nada): rama actual, cambios sin guardar, qué está listo para el commit y qué no se rastrea — es la brújula antes de cada paso","Sube los cambios al remoto","Crea un commit"],"correctIndex":1,"feedback":{"correct":"Correcto. status es lectura pura: mirar el mapa antes de avanzar. Por eso aparece entre comando y comando.","incorrect":"git status no modifica nada: reporta el estado actual del repositorio. Es el hábito de comprobar antes de actuar."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Crear un repositorio","points":["git init convierte una carpeta en repositorio: se corre UNA vez por proyecto.","Crea la subcarpeta oculta .git — el historial, las ramas y la config local viven ahí.","Copiar el proyecto con su .git copia su historia; borrar .git la borra. No se edita a mano.","git status solo INFORMA: rama, cambios pendientes, qué está listo y qué no se rastrea.","status es la brújula: se mira antes de cada paso, no se avanza a ciegas."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-l03-repositorio';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Las tres áreas y HEAD (+ Diagrama 1.1)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El modelo mental que evita el 90% de los errores","body":"Aquí está el concepto que separa a quien 'pelea con Git' de quien lo entiende. Git organiza tu trabajo en TRES ÁREAS. El DIRECTORIO DE TRABAJO: la carpeta donde editas, tus archivos tal como los ves ahora. El ÁREA DE PREPARACIÓN (staging): una antesala donde ARMAS el próximo commit, eligiendo QUÉ cambios entran en él. Y el REPOSITORIO: donde los commits quedan guardados para siempre en el historial. Un cambio viaja working → staging → repositorio, y cada frontera tiene su comando: git add mueve del working al staging; git commit mueve del staging al repositorio. La antesala parece un paso de más… hasta que entiendes que es justo lo que te deja hacer commits limpios y con sentido."}$j$),
  (2, 'diagrama', $j${"title":"Diagrama 1.1 · Las tres áreas y HEAD","component":"NetworkDiagram","props":{"label":"El viaje de un cambio: working → staging → repositorio","ancho":520,"alto":300,"nodos":[{"id":"working","x":20,"y":120,"w":140,"h":66,"titulo":"DIRECTORIO DE TRABAJO","subtitulo":"donde editas","descripcion":"Tus archivos tal como los ves y editas ahora mismo. Aquí un archivo está 'modificado' pero Git todavía no lo ha guardado en ninguna parte."},{"id":"staging","x":190,"y":120,"w":140,"h":66,"titulo":"ÁREA DE PREPARACIÓN","subtitulo":"staging — la antesala","descripcion":"Donde ARMAS el próximo commit: eliges qué cambios entran. Un archivo aquí está 'preparado' (staged), listo para la foto — pero la foto aún no se tomó."},{"id":"repo","x":360,"y":120,"w":140,"h":66,"titulo":"REPOSITORIO","subtitulo":"el historial (.git)","descripcion":"Donde los commits quedan guardados para siempre. Un archivo aquí está 'confirmado' (committed): forma parte de la historia y puedes volver a él."},{"id":"head","x":360,"y":30,"w":140,"h":50,"titulo":"HEAD","tag":"dónde estás","descripcion":"Una referencia que apunta al último commit de tu rama actual: el 'estás aquí' del historial. Cada commit nuevo mueve HEAD hacia adelante."}],"enlaces":[{"de":"working","a":"staging","tipo":"flecha","etiqueta":"git add","descripcion":"git add mueve los cambios elegidos del directorio de trabajo al área de preparación. NO los sube a ningún lado: los prepara."},{"de":"staging","a":"repo","tipo":"flecha","etiqueta":"git commit","descripcion":"git commit toma todo lo que está en el área de preparación y lo guarda como un commit en el historial."},{"de":"head","a":"repo","tipo":"flecha","discontinuo":true,"etiqueta":"apunta al último","descripcion":"HEAD señala el commit más reciente de tu rama: el punto desde el que partirá el siguiente."}],"hint":"Toca cada área y sigue las flechas add → commit."},"caption":"Dos fronteras, dos comandos: git add (working → staging) y git commit (staging → repositorio). HEAD marca dónde estás en el historial."}$j$),
  (3, 'texto', $j${"title":"La precisión que hay que grabar: add NO es subir","body":"El malentendido más común de quien empieza: creer que git add 'sube' los archivos a algún lado. NO. git add solo mueve cambios del directorio de trabajo al ÁREA DE PREPARACIÓN — de tu carpeta a la antesala, ambas en TU máquina. No hay internet, no hay servidor, no hay nada 'subido'. Es como apartar en una charola los ingredientes que vas a usar: siguen en tu cocina, solo están seleccionados. 'Subir' (a GitHub) es otra cosa completamente distinta (git push, módulo 4) y ni siquiera existe todavía en tu mundo. Por eso las tres áreas importan: preparar (add) y guardar en el historial (commit) son pasos LOCALES; publicar es un tercer acto que llega mucho después."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuáles son las tres áreas de Git y qué comando cruza cada frontera?","options":["Local, remoto y nube; con push y pull","Directorio de trabajo → (git add) → área de preparación → (git commit) → repositorio","Borrador, revisión y final; con save","Público, privado y oculto"],"correctIndex":1,"feedback":{"correct":"Correcto. add mueve al staging; commit mueve al repositorio. Dos fronteras, dos comandos.","incorrect":"Working → staging → repositorio. git add cruza la primera frontera, git commit la segunda — todo local."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión clave: ¿qué hace exactamente git add y qué NO hace?","options":["Sube el archivo a GitHub","Mueve los cambios del directorio de trabajo al ÁREA DE PREPARACIÓN — todo en tu máquina; NO 'sube' nada a ningún servidor","Guarda el commit en el historial","Borra el archivo"],"correctIndex":1,"feedback":{"correct":"Correcto. add prepara (local); no publica. Como apartar ingredientes en una charola: siguen en tu cocina.","incorrect":"git add NO sube nada: prepara cambios en el staging, en tu propio equipo. Publicar (push) es un acto muy posterior."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En el diagrama de las tres áreas, ¿qué representa HEAD?","options":["El primer commit del proyecto","Una referencia que apunta al ÚLTIMO commit de tu rama actual: el 'estás aquí' del historial, que avanza con cada commit nuevo","El nombre del repositorio","El área de preparación"],"correctIndex":1,"feedback":{"correct":"Correcto. HEAD = dónde estás parado en la historia. Cada commit lo mueve hacia adelante.","incorrect":"HEAD señala el commit más reciente de tu rama (el punto actual), no el primero ni el nombre del repo."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Las tres áreas","points":["Tres áreas: DIRECTORIO DE TRABAJO (editas) → PREPARACIÓN/staging (armas el commit) → REPOSITORIO (historial).","git add cruza working → staging; git commit cruza staging → repositorio. Ambos LOCALES.","PRECISIÓN: git add NO 'sube' nada — prepara cambios en tu máquina; publicar (push) es otro acto, mucho después.","El staging es la antesala que te deja elegir QUÉ entra en cada commit: la clave de los commits limpios.","HEAD apunta al último commit de tu rama: el 'estás aquí' que avanza con cada commit."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-l04-tres-areas';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · El primer commit
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Tomar la foto","body":"Un COMMIT es una foto de tu proyecto en un instante, con una etiqueta que explica qué cambió. Hacerlo son dos pasos, uno por cada frontera: primero git add elige los archivos para la foto (los pasa al área de preparación); luego git commit -m \"mensaje\" toma la foto y la guarda en el historial con ese mensaje. Puedes preparar un archivo concreto (git add clinica.py) o todos los cambios de golpe (git add .) — el punto significa 'todo lo de esta carpeta hacia abajo'. La opción -m pone el mensaje ahí mismo, en la línea; sin ella, Git abriría un editor para que lo escribas. Dos comandos, y tu proyecto tiene su primer punto en la línea de tiempo."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"El primer commit de la clínica","code":"# Preparar un archivo concreto…\ngit add clinica.sql\n\n# …o todo lo que cambió de una vez\ngit add .\n\n# Tomar la foto con su etiqueta\ngit commit -m \"Crea el esquema inicial de la clínica\"","caption":"add elige qué entra en la foto; commit -m la toma y la guarda con su mensaje. git add . prepara todos los cambios de la carpeta.","result":{"columns":["SALIDA"],"rows":[["[main (root-commit) a1b2c3d] Crea el esquema inicial de la clínica"],[" 1 file changed, 40 insertions(+)"]],"note":"'root-commit' porque es el primero del historial. a1b2c3d es el inicio del hash que identifica este commit de forma única. HEAD ahora apunta aquí."}}$j$),
  (3, 'texto', $j${"title":"Qué guarda un commit (y por qué no es 'guardar')","body":"Un commit no es como Ctrl+S. Guardar un archivo sobrescribe el anterior y borra lo que había; un commit AÑADE un punto al historial sin destruir los anteriores — todos siguen ahí, visitables. Cada commit guarda cinco cosas: el AUTOR (tu identidad configurada), la FECHA, el MENSAJE, una foto del ÁRBOL de archivos en ese momento, y un enlace al commit ANTERIOR (así se forma la cadena del historial). Ese enlace al padre es lo que convierte los commits sueltos en una LÍNEA DE TIEMPO. Y cada commit tiene un HASH — una huella única como a1b2c3d… — que lo identifica sin ambigüedad entre miles. Por eso pensamos el commit como una UNIDAD LÓGICA DE CAMBIO: no 'lo que llevo hasta ahora', sino 'un cambio con sentido propio, explicado'."}$j$),
  (4, 'texto', $j${"title":"Mensajes que valen: qué merece un commit","body":"El mensaje es lo que tu yo futuro (y tu equipo) leerá para entender la historia sin abrir el código. Un mensaje vago la arruina: 'cambios', 'arreglos', 'cosas', 'commit final' no dicen nada — dentro de un mes son ruido. Un buen mensaje dice QUÉ cambio incorpora el commit, en modo imperativo, como una orden: 'Agrega validación al formulario de registro', 'Corrige el cálculo del total', 'Crea la estructura de navegación'. Y de aquí sale la otra mitad de la buena práctica: un commit debería ser UN cambio con sentido. Si tu mensaje necesita un 'y' ('arregla el login y cambia colores y actualiza el README'), probablemente deberían ser tres commits. Commits pequeños y enfocados = un historial que se puede leer, revisar y revertir pieza por pieza."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué dos comandos, en orden, crean un commit?","options":["git commit y luego git add","git add (prepara los archivos en el staging) y luego git commit -m \"mensaje\" (toma la foto y la guarda)","git save y git push","git init y git status"],"correctIndex":1,"feedback":{"correct":"Correcto. add elige qué entra; commit lo guarda en el historial con su mensaje. Ese es el orden.","incorrect":"Primero git add (al staging), luego git commit -m (al historial). El commit guarda lo que add preparó."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué un commit NO es lo mismo que 'guardar' un archivo?","options":["Es más lento","Guardar sobrescribe y borra la versión anterior; un commit AÑADE un punto al historial sin destruir los anteriores — todos siguen visitables, encadenados por su enlace al commit padre","Un commit no guarda de verdad","Guardar necesita internet"],"correctIndex":1,"feedback":{"correct":"Correcto. El commit no pisa nada: suma un punto a la línea de tiempo, con enlace al anterior. Por eso puedes volver atrás.","incorrect":"Guardar reemplaza; commitear acumula. Cada commit enlaza al padre y forma el historial — nada se pierde."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estos es un buen mensaje de commit?","options":["\"cambios\"","\"Corrige el cálculo del total del carrito\" — dice QUÉ cambio incorpora, en imperativo","\"commit final\"","\"varias cosas\""],"correctIndex":1,"feedback":{"correct":"Correcto. Concreto, imperativo, dice qué hace el cambio: tu yo futuro lo agradece. 'cambios' y 'cosas' son ruido.","incorrect":"El buen mensaje describe el cambio en imperativo ('Corrige…', 'Agrega…'). Los vagos ('cambios', 'final') no dicen nada dentro de un mes."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — El primer commit","points":["Un commit es una FOTO del proyecto + una etiqueta que explica el cambio.","Dos pasos: git add (elige los archivos) → git commit -m \"mensaje\" (toma y guarda la foto).","git add archivo prepara uno; git add . prepara todos los cambios de la carpeta.","Un commit guarda autor, fecha, mensaje, árbol y enlace al PADRE (así se forma la línea de tiempo); lo identifica un hash único.","Mensajes en imperativo que dicen QUÉ cambió; un commit = un cambio con sentido (si necesitas un 'y', son varios)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-l05-primer-commit';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Consultar el historial
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Leer la línea de tiempo","body":"Los commits solo valen si puedes CONSULTARLOS. git log despliega el historial, del más reciente al más antiguo, mostrando de cada commit su hash, autor, fecha y mensaje. En un proyecto real, el log completo es largo y abrumador, así que existe la forma que de verdad usarás a diario: git log --oneline, que resume cada commit en una línea — hash corto + mensaje. De un vistazo ves toda la historia. Aquí se cobra la factura de los mensajes: un log lleno de 'cambios' y 'arreglos' es ilegible; uno de mensajes claros se lee como el índice de lo que ha pasado en el proyecto."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"El historial de la clínica, dos vistas","code":"# Historial completo (hash, autor, fecha, mensaje)\ngit log\n\n# La vista de todos los días: una línea por commit\ngit log --oneline","caption":"--oneline es la vista de trabajo: hash corto + mensaje, toda la historia de un vistazo.","result":{"columns":["git log --oneline"],"rows":[["c3d4e5f Agrega la tabla de citas"],["b2c3d4e Agrega la tabla de pacientes"],["a1b2c3d Crea el esquema inicial de la clínica"]],"note":"Se lee de arriba (lo más nuevo) hacia abajo (lo más viejo). Cada línea es un commit: su hash corto y su mensaje. Con mensajes claros, el log es el índice del proyecto."}}$j$),
  (3, 'texto', $j${"title":"Ver la forma del historial","body":"Un tercer sabor será tu favorito cuando lleguen las ramas (módulo 3): git log --oneline --graph --decorate --all. Cada opción suma algo — --graph dibuja las líneas del historial a la izquierda (útil cuando hay ramas que se separan y se juntan), --decorate muestra a qué apuntan las etiquetas y ramas (dónde está HEAD, por ejemplo), y --all incluye todas las ramas, no solo en la que estás. Por ahora, con un historial recto de una sola línea, se ve simple; guárdalo en el bolsillo: es la vista que convierte una maraña de ramas en un dibujo legible. Y un apunte: en tu terminal, git log a veces abre un visor de página (se sale con la tecla q) — en el editor de la plataforma verás la salida directa."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué muestra git log y en qué orden?","options":["Los archivos actuales, alfabéticamente","El historial de commits, del MÁS RECIENTE al más antiguo, con hash, autor, fecha y mensaje de cada uno","Solo el último commit","Los cambios sin guardar"],"correctIndex":1,"feedback":{"correct":"Correcto. log recorre la historia de lo nuevo a lo viejo, commit por commit.","incorrect":"git log lista los commits (hash/autor/fecha/mensaje) del más reciente al más antiguo. Los cambios sin guardar son cosa de status/diff."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué ventaja da git log --oneline sobre git log a secas?","options":["Muestra más detalle por commit","Resume cada commit en UNA línea (hash corto + mensaje): toda la historia de un vistazo — la vista de trabajo diaria","Ordena los commits alfabéticamente","Borra los commits viejos"],"correctIndex":1,"feedback":{"correct":"Correcto. --oneline condensa el historial a una línea por commit: legible de un golpe. Aquí se paga el precio de los buenos mensajes.","incorrect":"--oneline compacta cada commit a hash+mensaje en una línea. Es la vista que de verdad se usa a diario."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En git log --oneline --graph --decorate --all, ¿qué aporta la opción --graph?","options":["Colorea el texto","Dibuja las LÍNEAS del historial a la izquierda — indispensable para ver ramas que se separan y se juntan","Ordena por fecha","Borra el historial gráfico"],"correctIndex":1,"feedback":{"correct":"Correcto. --graph traza la forma del historial; con ramas (módulo 3) convierte una maraña en un dibujo legible.","incorrect":"--graph dibuja la estructura de commits y ramas. --decorate muestra dónde apuntan HEAD y las ramas; --all incluye todas las ramas."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Consultar el historial","points":["git log muestra el historial (hash, autor, fecha, mensaje) del más reciente al más antiguo.","git log --oneline: una línea por commit (hash corto + mensaje) — la vista diaria.","git log --oneline --graph --decorate --all dibuja la forma del historial: clave con ramas.","El log es tan legible como tus mensajes: 'cambios' lo arruina, mensajes claros lo vuelven un índice.","En terminal, log puede abrir un visor (se sale con q); en el editor la salida es directa."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-l06-historial';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Práctica: mi primer historial (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Estrenas el repositorio de la clínica. Ya creaste tres archivos (README.md, clinica.sql y estilos.css) y ahora vas a construir el historial: inicializa el repositorio y haz TRES commits, uno por archivo, cada uno con su mensaje. Escribe la secuencia completa de comandos, una por línea.","instructions":["Inicializa el repositorio con git init.","Prepara y confirma el README: git add README.md y luego git commit -m con un mensaje descriptivo (por ejemplo: \"Crea el README del proyecto\").","Prepara y confirma clinica.sql con su propio commit y mensaje.","Prepara y confirma estilos.css con su propio commit y mensaje. Al terminar deben ser TRES commits, cada uno con mensaje no vacío."],"initialCode":"# Mi primer historial — el repositorio de la clínica\n# Archivos ya creados: README.md, clinica.sql, estilos.css\n# Escribe la secuencia: init y tres commits (uno por archivo).\n\n","validators":["git\\s+init","git\\s+add","git\\s+commit\\s+-m\\s+[\"'].+[\"'].*git\\s+commit\\s+-m\\s+[\"'].+[\"'].*git\\s+commit\\s+-m\\s+[\"'].+[\"']"],"mockOutput":{"columns":["ESTADO FINAL — git log --oneline"],"rows":[["c3d4e5f Agrega la hoja de estilos"],["b2c3d4e Agrega el esquema de la clínica"],["a1b2c3d Crea el README del proyecto"]],"note":"Tres archivos, tres commits, tres puntos en la línea de tiempo. El repositorio quedó limpio (nada pendiente) y el historial se lee como el índice de lo que hiciste."},"hints":["Empieza siempre por git init: sin repositorio no hay dónde guardar commits.","El patrón se repite tres veces: git add <archivo> y luego git commit -m \"mensaje\". Un commit por archivo.","Los mensajes no pueden ir vacíos y conviene que digan QUÉ hace el cambio, en imperativo: \"Crea…\", \"Agrega…\"."],"successMessage":"¡Primer historial construido! git init dio memoria a la carpeta y tres commits atómicos —uno por archivo, cada uno con su mensaje— formaron una línea de tiempo legible. Esto es exactamente lo que harás en tu terminal el primer día de cualquier proyecto.","failMessage":"Revisa la secuencia: git init al inicio, y luego TRES bloques de git add <archivo> + git commit -m \"mensaje\", con mensajes no vacíos. Deben ser tres commits, no uno con todo."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-l07-practica';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La primera región","body":"Byte abre su primer repositorio. Once preguntas guardan la salida de esta región: el problema que Git resuelve, la identidad, las tres áreas, el commit y el historial. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué relación hay entre Git y GitHub?","options":["Son sinónimos","Git es el programa de control de versiones en TU equipo; GitHub es un servicio para alojar y compartir ese historial — Git funciona sin GitHub","GitHub crea los commits y Git los sube","Git es la versión vieja de GitHub"],"correctIndex":1,"feedback":{"correct":"Correcto. La herramienta (Git, local) y un lugar para publicarla (GitHub). Lo primero no necesita lo segundo.","incorrect":"Git lleva el historial en tu máquina; GitHub lo aloja en línea. Puedes versionar toda la vida sin GitHub."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Configuras user.name y user.email con --global. ¿Qué efecto tiene?","options":["Inicia sesión en un servidor","Tu identidad queda grabada para TODOS tus repositorios y firmará cada commit que hagas — sin --global, solo el repositorio actual","Publica tu perfil","Cifra tus commits"],"correctIndex":1,"feedback":{"correct":"Correcto. --global = tu firma para todos los proyectos; cada commit la lleva.","incorrect":"--global fija nombre y correo para todos tus repos, y cada commit los graba como autor. Local (sin --global) afecta solo un repo."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace git init y qué crea?","options":["Descarga un proyecto remoto","Convierte la carpeta en repositorio creando la subcarpeta oculta .git, donde vive todo el historial — se corre una vez por proyecto","Crea el primer commit","Sube la carpeta a la nube"],"correctIndex":1,"feedback":{"correct":"Correcto. init crea .git y con ella la memoria del proyecto. Descargar uno existente es clone.","incorrect":"git init inicializa el repositorio (nace .git). No descarga (eso es clone) ni commitea (eso es commit)."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Las tres áreas de Git, en orden, y el comando que cruza cada frontera:","options":["Nube → local → respaldo, con pull","Directorio de trabajo → (git add) → área de preparación → (git commit) → repositorio","Borrador → revisión → publicado, con submit","Todas se cruzan con git save"],"correctIndex":1,"feedback":{"correct":"Correcto. add del working al staging; commit del staging al repositorio. Dos comandos, dos fronteras.","incorrect":"Working → staging → repositorio, con git add y luego git commit. Todo local."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"La precisión que evita el error más común de principiante: ¿qué hace git add?","options":["Sube los archivos a GitHub","Mueve los cambios del directorio de trabajo al área de PREPARACIÓN, en tu propia máquina — NO 'sube' nada a ningún servidor","Crea el commit definitivo","Elimina los archivos preparados"],"correctIndex":1,"feedback":{"correct":"Correcto. add prepara localmente; publicar (push) es otro acto, mucho más tarde.","incorrect":"git add NO sube: prepara cambios en el staging, en tu equipo. Confundirlo con 'subir' es el malentendido clásico."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué guarda un commit, además del mensaje?","options":["Solo el archivo que cambió","Autor, fecha, una foto del árbol de archivos y un enlace al commit ANTERIOR (el padre) — ese enlace forma la línea de tiempo; y un hash único lo identifica","Tu contraseña","Únicamente la fecha"],"correctIndex":1,"feedback":{"correct":"Correcto. Autor, fecha, mensaje, árbol y padre: el enlace al padre encadena la historia. El hash lo identifica.","incorrect":"El commit guarda autor/fecha/mensaje/árbol y el enlace al commit anterior. Ese padre es lo que crea la cadena del historial."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué se dice que un commit NO es 'guardar' (Ctrl+S)?","options":["Porque es más lento","Porque guardar sobrescribe y pierde la versión anterior; el commit AÑADE un punto al historial sin destruir los previos — todos quedan visitables","Porque no guarda realmente","Porque requiere estar en línea"],"correctIndex":1,"feedback":{"correct":"Correcto. Guardar pisa; commitear acumula. Por eso puedes volver a cualquier punto anterior.","incorrect":"El commit no reemplaza nada: suma a la línea de tiempo, encadenado al padre. Guardar un archivo sí borra lo anterior."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"De estos mensajes de commit, ¿cuál sigue la buena práctica?","options":["\"arreglos varios\"","\"Agrega validación al formulario de registro\": concreto, en imperativo, dice QUÉ cambio incorpora","\"final final v2\"","\".\""],"correctIndex":1,"feedback":{"correct":"Correcto. Imperativo y específico: describe el cambio. Los vagos vuelven el log ilegible.","incorrect":"El buen mensaje dice qué hace el cambio, en imperativo ('Agrega…'). 'arreglos varios' no informa nada dentro de un mes."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres ver toda la historia del proyecto de un vistazo, una línea por commit. ¿Qué comando?","options":["git status","git log --oneline — hash corto + mensaje, del más reciente al más antiguo","git show","git commit -m"],"correctIndex":1,"feedback":{"correct":"Correcto. --oneline es la vista compacta y diaria del historial.","incorrect":"git log --oneline resume cada commit a una línea. status muestra el estado actual, no la historia."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Antes de dar cualquier paso, ¿qué comando te dice en qué estado está el repositorio (rama, cambios pendientes, qué está preparado)?","options":["git log","git status — solo informa, no cambia nada: la brújula que se mira entre comando y comando","git init","git add ."],"correctIndex":1,"feedback":{"correct":"Correcto. status es lectura pura: el hábito de mirar el mapa antes de avanzar.","incorrect":"git status reporta el estado actual (rama, pendientes, preparado) sin modificar nada. git log muestra la historia, que es otra cosa."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de cierre: recién inicializado un repositorio con git init, ¿por qué git status dice 'No commits yet' y qué significa para tu trabajo?","options":["Que hubo un error en git init","Que el repositorio existe pero su historial está VACÍO: la carpeta ya tiene memoria (.git), y falta tomar la primera foto — git add para preparar y git commit para el primer punto de la línea de tiempo","Que faltan permisos","Que hay que reinstalar Git"],"correctIndex":1,"feedback":{"correct":"Correcto. init dio la memoria; el historial arranca en blanco. El primer add + commit lo estrena. Cierra el módulo entero: init → status → add → commit → log.","incorrect":"'No commits yet' = repositorio listo pero historial vacío. El siguiente paso es add (preparar) y commit (la primera foto)."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm01-x01-examen';
