-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 050 — Git desde Cero · M2: Un historial profesional
-- ═══════════════════════════════════════════════════════════════════
-- Unidad 2 del temario (bloques 7-13 + Práctica 2 + EVALUACIÓN INTERMEDIA).
-- Cubre: ciclo de vida de los archivos, staging selectivo y commits
-- atómicos, git diff, mensajes profesionales + Conventional Commits,
-- .gitignore (con nota de seguridad de credenciales), git commit --amend,
-- y tags + versionado semántico. Práctica: historial limpio de una
-- funcionalidad. El examen de este módulo es la EVALUACIÓN INTERMEDIA
-- ampliada (~20 preguntas, XP 60 — decisión 1 de Karen).
-- Precisiones vinculantes: .gitignore NO des-rastrea lo ya rastreado
-- (ignorar ≠ eliminar); Conventional Commits es convención de EQUIPO,
-- no regla de Git; corregir historial LOCAL (amend) ≠ reescribir
-- historial PÚBLICO; borrar un commit NO borra el secreto → revocar.
-- Curso language = bash → práctica por regex + mockOutput.
-- Curso is_published = false: nada visible hasta el flip final (056).
-- Idempotente. Ejecutar DESPUÉS de 048.
-- ═══════════════════════════════════════════════════════════════════

delete from public.lessons
where module_id = (
  select m.id from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'git-desde-cero' and m.slug = 'm02-historial'
);

insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m02-l01-ciclo-vida',    'El ciclo de vida de un archivo',      'leccion',  20, 1),
       ('m02-l02-staging',       'Preparación selectiva y commits atómicos','leccion',20, 2),
       ('m02-l03-diff',          'Ver los cambios con git diff',        'leccion',  20, 3),
       ('m02-l04-mensajes',      'Mensajes de commit profesionales',    'leccion',  20, 4),
       ('m02-l05-gitignore',     'Ignorar archivos con .gitignore',     'leccion',  20, 5),
       ('m02-l06-amend',         'Corregir el último commit',           'leccion',  20, 6),
       ('m02-l07-tags',          'Etiquetas y versiones',               'leccion',  20, 7),
       ('m02-l08-practica',      'Práctica: historial de una funcionalidad','practica',20, 8),
       ('m02-x01-intermedia',    'Evaluación intermedia',               'examen',   60, 9)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'git-desde-cero' and m.slug = 'm02-historial';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · El ciclo de vida de un archivo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Los cinco estados de un archivo","body":"En el módulo 1 viste las tres áreas; ahora afinamos la vista a un solo archivo, que a ojos de Git pasa por estados bien definidos. UNTRACKED (no rastreado): un archivo nuevo que Git ve en la carpeta pero aún no vigila — nunca le has hecho git add. TRACKED (rastreado): Git ya lo conoce, y dentro de esta categoría vive en tres momentos: UNMODIFIED (sin cambios desde el último commit — idéntico a la foto), MODIFIED (lo editaste, pero el cambio no está preparado) y STAGED (preparado: el cambio está en el área de preparación, listo para el próximo commit). Un archivo se mueve entre estos estados a golpe de comandos, y entender en cuál está es entender qué pasará cuando hagas commit."}$j$),
  (2, 'texto', $j${"title":"git status cuenta la historia completa","body":"git status no solo dice 'hay cambios': clasifica cada archivo por su estado, y aprender a leerlo es aprender a ver el repositorio con los ojos de Git. Agrupa la salida en tres secciones. 'Changes to be committed' (cambios preparados, staged): lo que ENTRARÁ en el próximo commit. 'Changes not staged for commit' (modificados pero no preparados): cambios que existen pero que git commit ignoraría, porque no les hiciste git add. 'Untracked files' (no rastreados): archivos que Git ve pero no vigila. La pregunta que status responde de un vistazo: si hago commit AHORA, ¿qué se guarda y qué se queda fuera? Todo lo que no esté en la primera sección se queda fuera."}$j$),
  (3, 'ejemplo_codigo', $j${"title":"Leer un git status real","code":"git status","caption":"Tres secciones, tres estados: preparado (entra al commit), modificado (no entra), no rastreado (no entra).","result":{"columns":["git status"],"rows":[["On branch main"],["Changes to be committed:"],["  modified:   pacientes.sql"],["Changes not staged for commit:"],["  modified:   citas.sql"],["Untracked files:"],["  recibo.py"]],"note":"Si hicieras commit ahora, SOLO entraría pacientes.sql (está preparado). citas.sql está modificado pero sin preparar, y recibo.py ni siquiera se rastrea: ambos se quedan fuera hasta que les hagas git add."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un archivo nuevo que acabas de crear y que Git ve pero nunca has preparado con git add está…","options":["Staged","UNTRACKED (no rastreado): Git lo ve en la carpeta pero aún no lo vigila","Modified","Committed"],"correctIndex":1,"feedback":{"correct":"Correcto. Sin un primer git add, el archivo es untracked: Git lo lista pero no guarda su historia.","incorrect":"Un archivo nuevo nunca preparado es untracked. 'Modified' y 'staged' son estados de archivos que Git YA rastrea."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"git status muestra un archivo en 'Changes not staged for commit'. Si haces git commit ahora, ¿qué pasa con ese archivo?","options":["Se guarda en el commit","NO entra: está modificado pero sin preparar — commit solo guarda lo que está en el área de preparación (staged)","Se borra","Da error"],"correctIndex":1,"feedback":{"correct":"Correcto. Modificado ≠ preparado: sin git add, el cambio se queda fuera del commit.","incorrect":"'Not staged' = fuera del próximo commit. Solo lo que está 'to be committed' (staged) se guarda."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Un archivo TRACKED que no has tocado desde el último commit está en estado…","options":["Untracked","UNMODIFIED: idéntico a la última foto, sin cambios pendientes","Staged","Modified"],"correctIndex":1,"feedback":{"correct":"Correcto. Rastreado y sin cambios = unmodified. git status ni lo menciona, porque no hay nada que reportar de él.","incorrect":"Sin cambios desde el commit, el archivo rastreado está unmodified. Por eso status no lo lista: no hay nada pendiente."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Ciclo de vida","points":["UNTRACKED: Git lo ve pero no lo vigila (nunca le hiciste git add).","TRACKED: Git lo conoce, en tres momentos — UNMODIFIED, MODIFIED (editado sin preparar), STAGED (preparado).","git status clasifica cada archivo: preparados (entran al commit), modificados (no entran), no rastreados (no entran).","La pregunta que status responde: si hago commit ahora, ¿qué se guarda y qué queda fuera?","Solo lo staged entra al commit; el resto espera un git add."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l01-ciclo-vida';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Preparación selectiva y commits atómicos
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El staging existe para que ELIJAS","body":"Ahora se revela por qué el área de preparación no es burocracia. Trabajando en el sistema de la clínica, en una misma sesión tocaste tres cosas distintas: corregiste un error de cálculo, cambiaste un color y actualizaste el README. Si haces git add . y un solo commit, esos tres cambios sin relación quedan atrapados en la misma foto — imposibles de revisar por separado, imposibles de revertir uno sin arrastrar los otros. El staging te deja SELECCIONAR: git add calculo.py y commiteas solo la corrección; luego git add estilos.css y commiteas el color; luego el README. Tres commits atómicos, cada uno una idea completa. Esa es la razón de ser de la antesala: no meter todo de golpe, sino armar cada commit a mano."}$j$),
  (2, 'texto', $j${"title":"Sacar del staging sin perder el trabajo","body":"¿Y si preparaste algo por error — hiciste git add de un archivo que no querías en este commit? Se saca del área de preparación con git restore --staged archivo. Ojo con la precisión: esto NO borra tus cambios, solo los devuelve del estado 'preparado' al estado 'modificado' — el trabajo sigue intacto en tu directorio, solo dejó de estar en la fila para el próximo commit. Es el 'deshacer' del add. (Git suele recordártelo en la propia salida de git status, que sugiere el comando para revertir cada situación.) Con add para preparar y restore --staged para sacar, controlas con precisión de cirujano qué entra en cada commit."}$j$),
  (3, 'ejemplo_codigo', $j${"title":"Separar tres cambios en tres commits","code":"# Toqué tres cosas, pero son cambios distintos:\ngit add calculo.py\ngit commit -m \"Corrige el calculo del total de la factura\"\n\ngit add estilos.css\ngit commit -m \"Ajusta el color del boton de pago\"\n\ngit add README.md\ngit commit -m \"Documenta el modulo de facturacion\"","caption":"Preparar de a uno = commits atómicos. Cada foto captura UNA idea completa, revisable y reversible por separado.","result":{"columns":["git log --oneline"],"rows":[["9f8e7d6 Documenta el modulo de facturacion"],["8e7d6c5 Ajusta el color del boton de pago"],["7d6c5b4 Corrige el calculo del total de la factura"]],"note":"Tres commits, tres ideas. Si mañana el cálculo resulta estar mal, se revierte SOLO ese commit sin tocar el color ni la documentación. Con git add . y un commit, los tres estarían atrapados juntos."}}$j$),
  (4, 'texto', $j${"title":"Commits atómicos: la disciplina que se paga sola","body":"Un COMMIT ATÓMICO es un commit que hace UNA sola cosa completa. Es la práctica que más distingue un historial profesional de uno improvisado, y su valor se cobra en el futuro: un historial de commits atómicos se REVISA (cada uno se entiende solo), se REVIERTE (quitas un cambio sin arrastrar otros), se BUSCA (encontrar cuándo entró un error, módulo 5) y se ENTIENDE meses después. El anti-patrón es el 'commit basurero': git add . al final del día con mensaje 'avances', mezclando cinco cambios sin relación. git add . no es malo en sí — es perfecto cuando TODO lo que cambiaste pertenece al mismo commit; el problema es usarlo por pereza cuando los cambios son distintos. La regla: prepara pensando en qué historia quieres que cuente el commit."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Preparaste app.py por error (git add app.py) y quieres sacarlo del próximo commit SIN perder tus cambios. ¿Qué usas?","options":["git rm app.py","git restore --staged app.py — lo devuelve de 'preparado' a 'modificado'; tus cambios siguen intactos","git commit app.py","git delete app.py"],"correctIndex":1,"feedback":{"correct":"Correcto. restore --staged es el 'deshacer' del add: saca del staging sin tocar tu trabajo.","incorrect":"git restore --staged saca del área de preparación conservando los cambios. git rm borraría el archivo — no es eso."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un commit ATÓMICO y por qué importa?","options":["Un commit muy pequeño en bytes","Un commit que hace UNA sola cosa completa: así el historial se revisa, revierte, busca y entiende pieza por pieza — cada commit se explica solo","Un commit sin mensaje","Un commit que no se puede deshacer"],"correctIndex":1,"feedback":{"correct":"Correcto. Una idea por commit: revertir uno no arrastra los demás, y el historial se lee como una secuencia de decisiones claras.","incorrect":"Atómico = una idea completa por commit (no cuestión de tamaño). Es lo que permite revisar y revertir cambios por separado."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"En una sesión corregiste un bug, cambiaste un color y actualizaste el README. ¿Cuál es el enfoque profesional?","options":["git add . y un commit 'varios cambios'","Tres commits separados (git add del archivo correspondiente + commit) — cada cambio es una idea distinta y merece su propia foto atómica","Un commit por cada línea modificada","No commitear hasta terminar todo"],"correctIndex":1,"feedback":{"correct":"Correcto. Cambios sin relación → commits separados. El staging selectivo es justo para esto.","incorrect":"Tres cambios distintos = tres commits atómicos. Meterlos en uno los vuelve imposibles de revisar o revertir por separado."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Staging selectivo","points":["El staging existe para que ELIJAS qué entra en cada commit: prepara de a uno cuando los cambios son distintos.","git restore --staged archivo saca del área de preparación SIN perder los cambios (el 'deshacer' del add).","Commit ATÓMICO = una sola cosa completa: se revisa, revierte, busca y entiende por separado.","git add . es correcto cuando TODO pertenece al mismo commit; es un problema cuando se usa por pereza.","Prepara pensando en qué historia quieres que cuente cada commit."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l02-staging';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Ver los cambios con git diff
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Mirar antes de confirmar","body":"git status dice QUÉ archivos cambiaron; git diff dice QUÉ cambió DENTRO de ellos, línea por línea. Es la revisión que se hace ANTES de commitear, y salva de guardar tonterías: el print de depuración que olvidaste quitar, la línea que borraste sin querer, el cambio que no recuerdas haber hecho. git diff a secas muestra los cambios que están en el directorio de trabajo pero AÚN NO preparados (working vs staging): 'lo que modifiqué y todavía no metí a la charola'. Es la lupa sobre tu trabajo en curso: revisarlo antes de add es la costumbre que evita el commit del que te arrepientes."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Leer un diff","code":"git diff","caption":"- (rojo) = líneas que quitaste · + (verde) = líneas que agregaste. La cabecera @@ ubica en qué parte del archivo.","result":{"columns":["git diff  —  citas.sql"],"rows":[["@@ -12,3 +12,3 @@ SELECT paciente_id"],["   FROM citas"],["-  WHERE estado = 'activa'"],["+  WHERE estado = 'atendida'"],["   ORDER BY fecha;"]],"note":"Se lee así: en citas.sql cambió una línea — quitaste (-) el filtro por 'activa' y pusiste (+) el filtro por 'atendida'. Las líneas sin signo son el contexto que no cambió. Un vistazo y confirmas que el cambio es exactamente el que querías."}}$j$),
  (3, 'texto', $j${"title":"Los dos diff: sin preparar y preparado","body":"Aquí entra la distinción que importa. git diff (a secas) compara el directorio de trabajo contra lo PREPARADO: te muestra lo que modificaste y todavía NO has hecho git add. Pero una vez que preparas un cambio, git diff deja de mostrarlo — porque ya no está 'sin preparar'. Para ver lo que YA está en el área de preparación (lo que realmente entrará en el próximo commit), se usa git diff --staged (también escrito --cached). La rutina profesional completa antes de un commit: git diff para revisar lo pendiente, git add para preparar lo que quieres, y git diff --staged para confirmar que la charola tiene exactamente lo que va a la foto — ni más, ni menos. Revisar lo que vas a commitear es lo que separa el trabajo cuidadoso del descuidado."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿En qué se diferencian git status y git diff?","options":["Son el mismo comando","git status dice QUÉ archivos cambiaron; git diff dice QUÉ cambió dentro de ellos, línea por línea (- quitado, + agregado)","git diff borra los cambios","status es para remotos y diff para local"],"correctIndex":1,"feedback":{"correct":"Correcto. status es el resumen por archivo; diff es la lupa sobre las líneas.","incorrect":"status lista los archivos con cambios; diff muestra el detalle línea a línea de esos cambios."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"En la salida de git diff, ¿qué significan las líneas con - y con +?","options":["- es un error y + es correcto","- (rojo) son las líneas que QUITASTE; + (verde) las que AGREGASTE — juntas muestran el cambio exacto","- resta archivos y + los suma","Son números de línea"],"correctIndex":1,"feedback":{"correct":"Correcto. Menos = lo que se va, más = lo que entra. Las líneas sin signo son contexto sin cambios.","incorrect":"- marca lo eliminado y + lo añadido: el antes y el después de cada línea modificada."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Ya hiciste git add de tus cambios y quieres revisar EXACTAMENTE lo que entrará en el próximo commit. ¿Qué comando?","options":["git diff (a secas)","git diff --staged (o --cached): muestra lo PREPARADO — git diff a secas ya no lo mostraría, porque solo ve lo que aún NO está preparado","git status","git log"],"correctIndex":1,"feedback":{"correct":"Correcto. --staged compara el área de preparación contra el último commit: la foto que estás por tomar.","incorrect":"Tras el add, git diff a secas ya no ve ese cambio. Para lo preparado se usa git diff --staged."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — git diff","points":["git diff muestra QUÉ cambió dentro de los archivos, línea por línea: la revisión antes de commitear.","- (rojo) = líneas quitadas · + (verde) = líneas agregadas · sin signo = contexto sin cambios.","git diff (a secas) = cambios sin preparar (working vs staging).","git diff --staged (o --cached) = cambios preparados (lo que entrará al próximo commit).","Rutina: diff → add → diff --staged, para confirmar que la foto tiene exactamente lo que quieres."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l03-diff';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Mensajes de commit profesionales
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El mensaje es para el futuro","body":"Un mensaje de commit no es un trámite: es una carta a quien lea el historial dentro de seis meses — y ese alguien suele ser tú. Cuando una consulta de la clínica falle y hagas git log para investigar, cada mensaje será una pista o un estorbo. La anatomía de un buen mensaje: una LÍNEA DE ASUNTO corta (unos 50 caracteres) que resume el cambio, en modo IMPERATIVO — como si completara la frase 'Este commit va a…': 'Agrega el filtro por fecha', 'Corrige el cálculo del IVA', 'Elimina el endpoint obsoleto'. El imperativo no es capricho: es la convención que Git mismo usa en sus mensajes automáticos, y hace que el historial se lea como una lista de acciones. Para cambios que necesitan explicación, se deja una línea en blanco y se agrega un CUERPO que responde el POR QUÉ (el qué ya lo dice el código)."}$j$),
  (2, 'texto', $j${"title":"Pequeño, enfocado, y ligado a la tarea","body":"Tres hábitos que acompañan al buen mensaje. COMMITS PEQUEÑOS: un cambio que cabe en una frase de asunto sin necesitar un 'y'. Si escribes 'Agrega login y corrige el carrito y actualiza estilos', el mensaje te está avisando que deberían ser tres commits (volvemos a lo atómico de la lección 2). LIGADO A LA TAREA: en un equipo, los cambios responden a incidencias con número (verás el flujo completo en el módulo 4); mencionar ese número en el mensaje ('Corrige el cálculo del total (CLI-142)') teje la trazabilidad entre la tarea, el commit y —más adelante— la solicitud de integración. CONSISTENCIA: un historial donde todos los mensajes siguen el mismo estilo se lee de un tirón; uno donde cada quien escribe distinto es ruido. El estilo concreto lo fija el equipo; lo innegociable es tener uno."}$j$),
  (3, 'texto', $j${"title":"Conventional Commits: una convención, no una ley","body":"Muchos equipos adoptan un formato estándar llamado CONVENTIONAL COMMITS: el asunto empieza con un TIPO seguido de dos puntos. Los tipos comunes: feat (una funcionalidad nueva), fix (una corrección de error), docs (documentación), refactor (reestructurar sin cambiar comportamiento), test (pruebas) y chore (tareas de mantenimiento, dependencias). Así: 'feat: agrega filtro de productos por categoría', 'fix: evita duplicar usuarios en el registro', 'docs: documenta las variables de entorno'. La ventaja es que el historial se vuelve clasificable de un vistazo (y hasta automatizable: generar changelogs, calcular la siguiente versión). PERO —y esta es la precisión— Conventional Commits es una CONVENCIÓN que ALGUNOS equipos usan, NO una regla de Git: Git acepta cualquier texto como mensaje. Se enseña porque lo encontrarás en muchos proyectos reales, no porque Git lo exija."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la forma recomendada de escribir la línea de asunto de un commit?","options":["En pasado: 'Agregué el filtro'","En modo IMPERATIVO, corta, como si completara 'Este commit va a…': 'Agrega el filtro por fecha'","Con la fecha y tu nombre","En mayúsculas y con signos de exclamación"],"correctIndex":1,"feedback":{"correct":"Correcto. Imperativo y conciso: es la convención que usa Git y hace el historial legible como lista de acciones.","incorrect":"El asunto va en imperativo ('Agrega…', 'Corrige…'), corto. El autor y la fecha ya los graba Git aparte."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu mensaje de commit necesita un 'y' para describir todo lo que hiciste ('Agrega login y corrige el carrito'). ¿Qué te está diciendo eso?","options":["Que el mensaje está perfecto","Que probablemente deberían ser VARIOS commits: el 'y' delata que mezclaste cambios distintos en una sola foto — vuelve a los commits atómicos","Que uses más 'y'","Que el commit es demasiado pequeño"],"correctIndex":1,"feedback":{"correct":"Correcto. El 'y' es la señal de un commit que hace más de una cosa: sepáralo.","incorrect":"Un asunto con 'y' revela varios cambios juntos: es el momento de dividir en commits atómicos, uno por idea."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Sobre Conventional Commits (feat:, fix:, docs:…), ¿cuál afirmación es correcta?","options":["Es obligatorio: Git rechaza los mensajes que no lo sigan","Es una CONVENCIÓN que adoptan algunos equipos para clasificar y automatizar el historial — Git acepta cualquier texto; NO es una regla del propio Git","Lo inventó GitHub y solo funciona ahí","Solo sirve para proyectos en inglés"],"correctIndex":1,"feedback":{"correct":"Correcto. Convención de equipo, no ley de Git: útil y común, pero Git acepta cualquier mensaje.","incorrect":"Conventional Commits es una convención opcional. Git no la impone: se usa porque muchos equipos la adoptan, no porque sea obligatoria."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Para qué se menciona el número de una incidencia en el mensaje ('Corrige el cálculo (CLI-142)')?","options":["Para hacer el mensaje más largo","Para tejer la TRAZABILIDAD entre la tarea, el commit y la futura solicitud de integración: cualquiera puede rastrear por qué existe ese cambio","Es un requisito de sintaxis de Git","Para ordenar los commits por número"],"correctIndex":1,"feedback":{"correct":"Correcto. El número enlaza el commit con la tarea que lo originó: trazabilidad de punta a punta (módulo 4).","incorrect":"Referenciar la incidencia conecta el cambio con su motivo. No es sintaxis de Git: es trazabilidad de equipo."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Mensajes profesionales","points":["Asunto corto (~50 car.) en IMPERATIVO: 'Agrega…', 'Corrige…', como quien completa 'Este commit va a…'.","Cuerpo opcional (tras una línea en blanco) para el POR QUÉ; el qué ya lo dice el código.","Commits pequeños: si el asunto necesita un 'y', son varios commits.","Ligar a la incidencia ('(CLI-142)') teje la trazabilidad tarea ↔ commit ↔ PR.","Conventional Commits (feat/fix/docs/…) es convención de EQUIPO, no regla de Git; consistencia > estilo concreto."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l04-mensajes';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Ignorar archivos con .gitignore
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Lo que NO debe entrar al historial","body":"No todo lo que aparece en la carpeta del proyecto merece versionarse. Cuatro familias sobran casi siempre: las DEPENDENCIAS descargables (la carpeta node_modules, los paquetes que cualquiera reinstala con un comando — versionarlas hincha el repositorio con miles de archivos regenerables), los ARTEFACTOS GENERADOS (la carpeta dist, los compilados: salen del código, no son el código), la CONFIGURACIÓN LOCAL y los LOGS (propios de tu máquina, sin valor para nadie más), y —lo más delicado— los SECRETOS: contraseñas, tokens, llaves privadas, el archivo .env con las credenciales de la base de datos de la clínica. El archivo .gitignore es la lista de lo que Git debe IGNORAR: patrones de nombres que Git no rastreará ni te ofrecerá commitear, manteniéndolos fuera del historial y fuera de tu vista en git status."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Un .gitignore típico","code":"# Dependencias regenerables\nnode_modules/\n\n# Artefactos de compilacion\ndist/\n\n# Logs\n*.log\n\n# Configuracion local y SECRETOS\n.env","caption":"Cada línea es un patrón. La barra final (node_modules/) marca una carpeta; el asterisco (*.log) marca 'cualquier archivo que termine en .log'.","result":{"columns":["EFECTO"],"rows":[["node_modules/  → ignorada entera"],["dist/         → ignorada entera"],["*.log         → todos los .log ignorados"],[".env          → nunca aparece en git status"]],"note":"Con este .gitignore, git status deja de listar esos archivos: no te ofrecerá commitearlos ni por accidente. El propio .gitignore SÍ se versiona (se commitea), para que todo el equipo comparta la misma lista de exclusiones."}}$j$),
  (3, 'texto', $j${"title":"La precisión: ignorar NO es des-rastrear","body":"Aquí vive uno de los tropiezos clásicos. .gitignore solo afecta a archivos que Git AÚN NO rastrea: los mantiene fuera desde el principio. Pero si un archivo YA fue commiteado antes —digamos que subiste .env por error en un commit pasado— agregarlo al .gitignore NO lo saca del repositorio: Git lo sigue rastreando porque ya lo conoce. Ignorar ≠ eliminar del rastreo. Para dejar de rastrear algo ya commiteado se necesita un paso extra (git rm --cached archivo, que lo quita del seguimiento sin borrarlo de tu disco, y luego commiteas esa eliminación). Confundir esto es la causa de que un secreto 'ignorado' siga estando en el historial, expuesto — lo que nos lleva al punto más importante."}$j$),
  (4, 'texto', $j${"title":"⚠ Seguridad: un secreto commiteado no se borra con ignorarlo","body":"Regla de seguridad crítica, y la más cara de aprender por las malas: si commiteaste una credencial —una contraseña, un token, la llave de la base de datos— agregarla al .gitignore DESPUÉS no la elimina; sigue viva en el historial, y cualquiera con acceso al repositorio puede recuperarla de un commit viejo. Peor aún: aunque borres ese commit del historial (con herramientas avanzadas), NO puedes garantizar que el secreto deje de existir — pudo haberse copiado, clonado, respaldado, indexado. Por eso la única respuesta correcta ante un secreto expuesto es ROTARLO: cambiar la contraseña, revocar el token, generar una llave nueva — dar por comprometido lo que se filtró. Prevención primero: .env en .gitignore desde el minuto cero, para que la credencial JAMÁS entre. Y si ya entró: se revoca, no se esconde."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué tipos de archivos van típicamente en .gitignore?","options":["El código fuente del proyecto","Dependencias regenerables (node_modules), artefactos (dist), logs, config local y SECRETOS (.env) — todo lo que no es el código o se puede regenerar","Los mensajes de commit","El archivo .gitignore mismo, que nunca se versiona"],"correctIndex":1,"feedback":{"correct":"Correcto. Fuera del historial: lo regenerable, lo local y lo secreto. El .gitignore en cambio SÍ se versiona, para compartirlo.","incorrect":"Se ignoran dependencias, artefactos, logs, config local y secretos. El código fuente SÍ se versiona, y el .gitignore también (para el equipo)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión clave: agregaste .env al .gitignore, pero .env YA lo habías commiteado la semana pasada. ¿Qué pasa?","options":["Desaparece del repositorio automáticamente","Git lo SIGUE rastreando: .gitignore solo afecta lo que Git aún no conoce — ignorar ≠ des-rastrear. Sacarlo requiere git rm --cached y un commit","Se borra de tu disco","Da error al hacer commit"],"correctIndex":1,"feedback":{"correct":"Correcto. .gitignore no toca lo ya rastreado: para eso está git rm --cached. Ignorar y des-rastrear son cosas distintas.","incorrect":"Un archivo ya commiteado se sigue rastreando pese al .gitignore. Ignorar previene el futuro; no borra el pasado."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Descubres que una contraseña real quedó commiteada en el historial hace tres commits. ¿La acción correcta?","options":["Agregarla al .gitignore y seguir","ROTARLA (cambiar la contraseña / revocar el token / regenerar la llave): un secreto commiteado sigue en el historial y pudo copiarse — borrarlo no garantiza que deje de existir","Borrar el archivo del directorio","Ignorar el problema si el repo es privado"],"correctIndex":1,"feedback":{"correct":"Correcto. Un secreto expuesto se da por comprometido y se revoca. El .gitignore no lo saca del pasado, y borrar el commit no garantiza nada.","incorrect":"La única respuesta segura es rotar la credencial. Ignorarla o borrar el commit no elimina el riesgo: el secreto ya salió."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — .gitignore","points":["Se ignoran: dependencias (node_modules), artefactos (dist), logs, config local y SECRETOS (.env).","Cada línea es un patrón; carpeta/ ignora una carpeta, *.log ignora por extensión. El .gitignore SÍ se versiona.","PRECISIÓN: .gitignore no des-rastrea lo YA commiteado — para eso, git rm --cached + commit. Ignorar ≠ eliminar.","⚠ Un secreto commiteado sigue en el historial aunque lo ignores después: borrar el commit NO garantiza que desaparezca.","Ante un secreto expuesto: ROTARLO (revocar/cambiar). Prevención: .env en .gitignore desde el minuto cero."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l05-gitignore';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Corregir el último commit
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El arreglo del último minuto","body":"Acabas de hacer un commit y te das cuenta: se te olvidó un archivo, o el mensaje tiene un error de dedo. No hace falta un commit nuevo de 'ups, faltó esto' que ensucie el historial — para eso existe git commit --amend, que REEMPLAZA el último commit por una versión corregida. ¿Olvidaste incluir un archivo? Lo preparas (git add) y corres git commit --amend: el archivo se une al commit anterior como si siempre hubiera estado. ¿Solo el mensaje estaba mal? git commit --amend -m \"mensaje corregido\" reescribe el texto. Es la goma de borrar para el commit más reciente — limpia, siempre que se use en el momento y lugar correctos."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Enmendar: archivo olvidado y mensaje","code":"# Caso 1: olvidaste un archivo en el ultimo commit\ngit add config.py\ngit commit --amend --no-edit\n# (--no-edit conserva el mensaje anterior tal cual)\n\n# Caso 2: solo el mensaje estaba mal\ngit commit --amend -m \"Agrega la configuracion de la base de datos\"","caption":"--amend reemplaza el último commit. --no-edit conserva el mensaje; -m lo cambia.","result":{"columns":["RESULTADO"],"rows":[["[main 4f3e2d1] Agrega la configuracion de la base de datos"],[" Date: ..."],[" 2 files changed"]],"note":"El hash cambió (de otro anterior a 4f3e2d1): --amend no edita el commit viejo, crea uno NUEVO que lo sustituye. Ese detalle —el hash distinto— es la clave de la precisión que viene."}}$j$),
  (3, 'texto', $j${"title":"La regla que salva equipos: local sí, público NO","body":"Nota lo que pasó arriba: el commit enmendado tiene un HASH DISTINTO. Es un commit nuevo que ocupa el lugar del anterior — técnicamente, --amend REESCRIBE la historia. Y aquí está la precisión que separa un uso seguro de un desastre: enmienda SOLO commits que todavía son TUYOS y LOCALES, que nadie más ha visto. Si el commit ya lo COMPARTISTE (lo subiste a un repositorio del que otros descargan — módulo 4), enmendarlo reescribe una historia que otras personas ya tienen, y al chocar tu versión reescrita con la de ellos se arma un caos de historiales divergentes. La regla de oro que recorrerá el resto del curso: NO se reescribe historia pública. --amend es una goma de borrar perfecta para el commit local recién hecho, y una trampa para el commit que ya salió al mundo. Corregir historial local (amend) y reescribir historial público son dos actos con el mismo comando y consecuencias opuestas."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Hiciste un commit y olvidaste incluir un archivo. ¿La forma limpia de arreglarlo (siendo un commit local reciente)?","options":["Un commit nuevo llamado 'faltó un archivo'","Preparar el archivo (git add) y git commit --amend: se une al último commit como si siempre hubiera estado, sin ensuciar el historial","Borrar el repositorio y empezar","No se puede arreglar"],"correctIndex":1,"feedback":{"correct":"Correcto. --amend reemplaza el último commit por una versión corregida: el archivo olvidado se integra sin un commit de parche.","incorrect":"git commit --amend es la goma del último commit: incluye el archivo olvidado en él. Un commit de 'ups' extra solo ensucia."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Después de git commit --amend, notas que el commit tiene un HASH distinto. ¿Qué revela eso?","options":["Que hubo un error","Que --amend no edita el commit viejo: crea uno NUEVO que lo sustituye — técnicamente REESCRIBE la historia, y por eso hay que tener cuidado con commits compartidos","Que el commit se duplicó","Que cambió de rama"],"correctIndex":1,"feedback":{"correct":"Correcto. Hash nuevo = commit nuevo = historia reescrita. Inofensivo en local; peligroso si ya se compartió.","incorrect":"El hash distinto significa que --amend sustituyó el commit por uno nuevo (reescribió la historia). De ahí la regla sobre lo público."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo es PELIGROSO usar git commit --amend?","options":["Nunca, es siempre seguro","Cuando el commit YA fue COMPARTIDO (subido a un repositorio del que otros descargan): amend reescribe una historia que otras personas ya tienen — la regla de oro es no reescribir historia pública","Cuando el mensaje es largo","Cuando hay más de un archivo"],"correctIndex":1,"feedback":{"correct":"Correcto. Local y no compartido: seguro. Ya publicado: reescribir esa historia choca con la de los demás. No se toca lo público.","incorrect":"El peligro es enmendar algo ya compartido: reescribes una historia que otros tienen. En local y sin publicar, --amend es seguro."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Corregir el último commit","points":["git commit --amend reemplaza el ÚLTIMO commit por una versión corregida (archivo olvidado o mensaje).","--no-edit conserva el mensaje; -m \"…\" lo cambia.","El commit enmendado tiene HASH NUEVO: --amend REESCRIBE la historia (crea un commit que sustituye al anterior).","Seguro solo en commits LOCALES no compartidos; PELIGROSO si el commit ya se publicó.","Regla de oro del curso: NO se reescribe historia pública."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l06-amend';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Etiquetas y versiones
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Poner un nombre a un momento","body":"En un historial de cientos de commits con hashes crípticos, algunos momentos merecen un nombre memorable: 'esta es la versión 1.0 que salió a producción'. Un TAG (etiqueta) es justo eso — una marca con nombre sobre un commit concreto, que no se mueve. A diferencia de una rama (que avanza con cada commit nuevo, módulo 3), un tag se queda clavado para siempre en el commit que marcaste: es un marcador permanente. Su uso estrella es señalar las VERSIONES o releases del proyecto (v1.0.0, v2.3.1), de modo que cualquiera —tú incluido— pueda volver exactamente al código que se publicó en cierta versión, sin adivinar cuál de los mil commits era."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Crear y consultar tags","code":"# Tag ANOTADO (el recomendado para versiones): lleva mensaje\ngit tag -a v1.0.0 -m \"Primera version estable de la clinica\"\n\n# Ver todos los tags\ngit tag\n\n# Subir un tag al remoto (los tags NO viajan con git push normal)\ngit push origin v1.0.0","caption":"El tag ANOTADO (-a con -m) guarda autor, fecha y mensaje. Existe también el tag ligero (git tag v1.0.0, sin -a): solo un nombre, sin metadatos.","result":{"columns":["git tag"],"rows":[["v1.0.0"]],"note":"Dos tipos: el ANOTADO (git tag -a v1.0.0 -m \"...\") guarda quién, cuándo y por qué — el correcto para releases. El LIGERO (git tag v1.0.0) es solo una etiqueta desnuda. Y ojo: git push a secas no sube los tags; se suben aparte (git push origin v1.0.0)."}}$j$),
  (3, 'texto', $j${"title":"Versionado semántico: qué dice cada número","body":"¿Por qué v1.4.2 y no 'versión de marzo'? El VERSIONADO SEMÁNTICO es la convención más extendida para numerar versiones, y sus tres números cuentan una historia. MAYOR.MENOR.PARCHE: se sube el número de PARCHE (el último) cuando corriges errores sin cambiar cómo se usa el software (v1.4.2 → v1.4.3); se sube el MENOR (el de en medio) cuando agregas funcionalidad nueva compatible con lo anterior (v1.4.3 → v1.5.0, y el parche vuelve a cero); y se sube el MAYOR (el primero) cuando haces un cambio que ROMPE la compatibilidad, obligando a quien lo usa a adaptarse (v1.5.0 → v2.0.0). De un vistazo, el número comunica el RIESGO de actualizar: un parche es seguro, un mayor exige leer con cuidado. Como todo lo profesional de este módulo, es una convención adoptada por la industria, no una imposición de Git — pero tan común que conviene reconocerla."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un tag en Git y en qué se diferencia de una rama?","options":["Un tag y una rama son lo mismo","Un tag es una marca con nombre CLAVADA en un commit concreto (no se mueve); una rama avanza con cada commit nuevo. Los tags señalan versiones/releases","Un tag borra commits","Un tag es un mensaje de commit"],"correctIndex":1,"feedback":{"correct":"Correcto. El tag es un marcador permanente sobre un commit; la rama es móvil. Por eso los tags marcan versiones.","incorrect":"El tag se queda fijo en su commit (marca versiones); la rama se mueve hacia adelante con cada commit. No son lo mismo."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Para marcar una versión de producción, ¿tag anotado o ligero, y por qué?","options":["Ligero: es más rápido","ANOTADO (git tag -a v1.0.0 -m \"...\"): guarda autor, fecha y mensaje — el registro completo que una versión merece; el ligero es solo un nombre sin metadatos","Da igual cuál","Ninguno: las versiones no se etiquetan"],"correctIndex":1,"feedback":{"correct":"Correcto. El anotado documenta la versión (quién, cuándo, por qué). El ligero sirve para marcas internas rápidas.","incorrect":"Para releases se usa el tag anotado (-a -m): registra autor, fecha y mensaje. El ligero (sin -a) es una etiqueta pelada."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En versionado semántico MAYOR.MENOR.PARCHE, corriges un error sin cambiar cómo se usa el software. ¿Qué número sube?","options":["El MAYOR: v1.4.2 → v2.0.0","El PARCHE (el último): v1.4.2 → v1.4.3 — correcciones compatibles suben el parche","El MENOR: v1.4.2 → v1.5.0","Ninguno, no se re-etiqueta"],"correctIndex":1,"feedback":{"correct":"Correcto. Corrección compatible = subir parche. El menor es para funciones nuevas; el mayor para cambios que rompen.","incorrect":"Un arreglo que no cambia el uso sube el PARCHE (último número). Función nueva → menor; ruptura de compatibilidad → mayor."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Subiste tus commits con git push, pero tu compañero no ve el tag v1.0.0 que creaste. ¿Por qué?","options":["El tag se corrompió","Los tags NO viajan con git push normal: se suben aparte (git push origin v1.0.0, o git push --tags)","Tu compañero no tiene permisos","Los tags solo existen en local para siempre"],"correctIndex":1,"feedback":{"correct":"Correcto. push mueve commits de rama, no tags: el tag se publica explícitamente.","incorrect":"git push a secas no incluye los tags. Se suben por separado con git push origin <tag> (o --tags)."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Etiquetas y versiones","points":["Un TAG es una marca con nombre CLAVADA en un commit (no se mueve): señala versiones/releases.","Tag ANOTADO (git tag -a vX -m \"…\"): guarda autor/fecha/mensaje — el correcto para versiones. Ligero (git tag vX): solo nombre.","Versionado semántico MAYOR.MENOR.PARCHE: parche = arreglo compatible · menor = función nueva compatible · mayor = rompe compatibilidad.","El número comunica el RIESGO de actualizar (parche seguro, mayor exige cuidado).","Los tags no viajan con git push: se suben aparte (git push origin vX)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l07-tags';

-- ═════════════════════════════════════════════════════════════════════
-- L08 · Práctica: historial de una funcionalidad (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"En el repositorio de la clínica ya inicializado, implementaste el módulo de facturación en dos pasos y ahora lo publicas como versión 1.0.0. Construye el historial limpio: DOS commits atómicos (primero la funcionalidad, luego una corrección) y una etiqueta de versión anotada. Los archivos ya están creados; escribe la secuencia de comandos.","instructions":["Prepara y confirma la funcionalidad: git add factura.py y git commit -m con un mensaje descriptivo (p. ej. \"Agrega el calculo de facturas\").","Prepara y confirma la corrección como un SEGUNDO commit atómico: git add factura.py y git commit -m con su propio mensaje (p. ej. \"Corrige el redondeo del total\").","Marca la versión con un tag ANOTADO: git tag -a v1.0.0 -m con un mensaje (p. ej. \"Primera version estable\"). El tag debe ser anotado (-a) y con formato de versión semántica (v1.0.0)."],"initialCode":"# Historial limpio del modulo de facturacion + version 1.0.0\n# Archivos ya creados. Escribe: dos commits atomicos y un tag anotado.\n\n","validators":["git\\s+commit\\s+-m\\s+[\"'].+[\"'].*git\\s+commit\\s+-m\\s+[\"'].+[\"']","git\\s+tag\\s+-a\\s+v\\d+\\.\\d+\\.\\d+\\s+-m\\s+[\"'].+[\"']"],"mockOutput":{"columns":["ESTADO FINAL"],"rows":[["git log --oneline:"],["  b2c3d4e Corrige el redondeo del total"],["  a1b2c3d Agrega el calculo de facturas"],["git tag:"],["  v1.0.0"]],"note":"Dos commits atómicos (funcionalidad y corrección por separado) y una versión anotada clavada en el último. Cualquiera puede volver a v1.0.0 y encontrar exactamente este código."},"hints":["Dos bloques de git add + git commit -m, cada uno con su mensaje: primero la funcionalidad, luego la corrección. Son commits SEPARADOS (atómicos).","El tag va al final y debe ser ANOTADO: git tag -a v1.0.0 -m \"mensaje\" — con -a (anotado) y -m (mensaje). Un tag ligero (sin -a) no cumple.","El formato de versión es semántico: v1.0.0 (mayor.menor.parche)."],"successMessage":"¡Historial de funcionalidad terminado! Dos commits atómicos que se leen solos y una versión anotada que marca el release. Este es el patrón de todo trabajo profesional: cambios separados con sentido, y un tag para volver a la versión exacta cuando haga falta.","failMessage":"Revisa las tres piezas: DOS commits (git add + git commit -m, con mensajes, por separado) y un tag ANOTADO git tag -a v1.0.0 -m \"mensaje\". El tag debe llevar -a y -m, y la versión formato vX.Y.Z."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-l08-practica';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · EVALUACIÓN INTERMEDIA (examen ampliado — decisión 1 de Karen)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Evaluación intermedia","body":"Byte llega al primer gran control del camino. Esta evaluación cubre TODO lo aprendido hasta aquí: fundamentos, las tres áreas, el ciclo de vida de los archivos, el staging selectivo, git diff, los mensajes, .gitignore, amend y los tags. Veinte preguntas guardan el paso — más que un examen de región, porque aquí se consolida la base sobre la que se construye el resto. Las que falles volverán al final hasta que las domines. Respira y adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"Las tres áreas de Git, con el comando que cruza cada frontera:","options":["Nube → local → respaldo","Directorio de trabajo → (git add) → área de preparación → (git commit) → repositorio","Borrador → revisión → publicado","Las tres se cruzan con git save"],"correctIndex":1,"feedback":{"correct":"Correcto. add al staging, commit al repositorio. La columna vertebral de Git.","incorrect":"Working → (add) → staging → (commit) → repositorio. Ambos pasos son locales."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"La precisión que evita el error de principiante: git add…","options":["Sube los archivos a GitHub","Prepara los cambios en el área de preparación, en TU máquina — NO 'sube' nada a ningún servidor","Crea el commit","Borra los cambios"],"correctIndex":1,"feedback":{"correct":"Correcto. add prepara localmente; publicar (push) es otro acto, mucho después.","incorrect":"git add NO sube: mueve cambios al staging, en tu equipo. Confundirlo con 'subir' es el malentendido clásico."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un archivo aparece en 'Untracked files' de git status. ¿Qué significa?","options":["Está listo para el commit","Git lo VE pero no lo VIGILA: nunca le hiciste git add — no entrará en ningún commit hasta que lo prepares","Tiene un conflicto","Está en otra rama"],"correctIndex":1,"feedback":{"correct":"Correcto. Untracked = fuera del seguimiento hasta el primer add.","incorrect":"Untracked es un archivo que Git no rastrea aún. Un git add lo empieza a vigilar y lo prepara."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"git status muestra citas.sql en 'Changes not staged for commit'. Haces commit. ¿Entra citas.sql?","options":["Sí, siempre entra todo","NO: está modificado pero sin preparar — el commit solo guarda lo staged. Falta git add citas.sql","Solo si no hay conflictos","Entra a medias"],"correctIndex":1,"feedback":{"correct":"Correcto. Modificado ≠ preparado: sin add, el cambio se queda fuera del commit.","incorrect":"'Not staged' = fuera del commit. Solo entra lo que está preparado (staged)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Tocaste tres cosas sin relación (un bug, un color, el README). El enfoque profesional:","options":["git add . y un commit 'varios cambios'","Tres commits atómicos: preparar y confirmar cada cambio por separado — cada foto captura UNA idea, revisable y reversible sola","Esperar a terminar todo y un commit final","Un commit por línea"],"correctIndex":1,"feedback":{"correct":"Correcto. Cambios distintos → commits separados. El staging selectivo existe para esto.","incorrect":"Cambios sin relación piden commits atómicos separados: uno por idea. El commit basurero mezcla todo."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Preparaste app.py por error y quieres sacarlo del próximo commit sin perder los cambios:","options":["git rm app.py","git restore --staged app.py — lo devuelve de 'preparado' a 'modificado', con los cambios intactos","git commit --amend","git reset --hard"],"correctIndex":1,"feedback":{"correct":"Correcto. restore --staged es el 'deshacer' del add: saca del staging sin tocar el trabajo.","incorrect":"git restore --staged saca del área de preparación conservando los cambios. git rm borraría el archivo."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres revisar EXACTAMENTE lo que entrará en el próximo commit (lo ya preparado). ¿Qué comando?","options":["git diff (a secas)","git diff --staged (o --cached): muestra lo preparado — git diff a secas solo ve lo que aún NO está preparado","git status","git show --all"],"correctIndex":1,"feedback":{"correct":"Correcto. --staged compara el staging contra el último commit: la foto que vas a tomar.","incorrect":"Lo preparado se revisa con git diff --staged; git diff a secas muestra lo que falta preparar."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"En un git diff, las líneas con - (rojo) y + (verde) son…","options":["Errores y aciertos","Líneas QUITADAS (-) y AGREGADAS (+): juntas muestran el cambio exacto; las sin signo son contexto","Números de línea","Ramas distintas"],"correctIndex":1,"feedback":{"correct":"Correcto. Menos = lo que se va, más = lo que entra. El resto es contexto sin cambios.","incorrect":"- es lo eliminado y + lo añadido: el antes y el después de cada línea modificada."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál sigue la buena práctica para un mensaje de commit?","options":["\"cambios varios\"","\"Corrige el cálculo del total del carrito\": concreto, en imperativo, dice QUÉ cambio incorpora","\"final v3 ahora si\"","\"asdf\""],"correctIndex":1,"feedback":{"correct":"Correcto. Imperativo y específico: describe el cambio. Los vagos vuelven ilegible el log.","incorrect":"El buen mensaje dice qué hace el cambio, en imperativo. 'cambios varios' no informa nada."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Sobre Conventional Commits (feat:, fix:, docs:…):","options":["Git lo exige: rechaza mensajes que no lo sigan","Es una CONVENCIÓN que adoptan algunos equipos para clasificar/automatizar el historial — Git acepta cualquier texto; no es una regla del propio Git","Solo funciona en GitHub","Es obligatorio en proyectos grandes"],"correctIndex":1,"feedback":{"correct":"Correcto. Convención de equipo útil y común, pero opcional: Git no la impone.","incorrect":"Conventional Commits es opcional. Git acepta cualquier mensaje; se usa porque muchos equipos lo adoptan."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué tipos de archivos van típicamente en .gitignore?","options":["El código fuente","Dependencias regenerables (node_modules), artefactos (dist), logs, config local y SECRETOS (.env)","Los commits viejos","Los archivos grandes únicamente"],"correctIndex":1,"feedback":{"correct":"Correcto. Fuera del historial: lo regenerable, lo local y lo secreto. El código sí se versiona.","incorrect":"Se ignoran dependencias, artefactos, logs, config y secretos. El código fuente se versiona."}}$j$),
  (13, 'quiz', $j${"variant":"multiple_choice","prompt":"Agregaste .env al .gitignore, pero .env ya lo habías commiteado antes. ¿Qué ocurre?","options":["Desaparece del repositorio solo","Git lo SIGUE rastreando: .gitignore solo afecta lo que Git aún no conoce. Sacarlo requiere git rm --cached + commit — ignorar ≠ des-rastrear","Se borra de tu disco","Da error"],"correctIndex":1,"feedback":{"correct":"Correcto. .gitignore no toca lo ya rastreado. Ignorar previene el futuro; no borra el pasado.","incorrect":"Un archivo ya commiteado se sigue rastreando pese al .gitignore. Para des-rastrearlo: git rm --cached."}}$j$),
  (14, 'quiz', $j${"variant":"multiple_choice","prompt":"Una contraseña real quedó commiteada hace tres commits. ¿La acción correcta?","options":["Agregarla al .gitignore y seguir","ROTARLA (cambiar la contraseña / revocar el token): sigue en el historial y pudo copiarse — borrar el commit no garantiza que deje de existir","Borrar el archivo del directorio","Nada si el repo es privado"],"correctIndex":1,"feedback":{"correct":"Correcto. Secreto expuesto = comprometido: se revoca. Ignorarlo o borrar el commit no elimina el riesgo.","incorrect":"La única respuesta segura es rotar la credencial. El .gitignore no la saca del pasado."}}$j$),
  (15, 'quiz', $j${"variant":"multiple_choice","prompt":"Hiciste un commit local (no compartido) y olvidaste un archivo. ¿La forma limpia?","options":["Un commit nuevo 'faltó un archivo'","git add del archivo + git commit --amend: se integra al último commit sin un commit de parche","git reset --hard","No se puede"],"correctIndex":1,"feedback":{"correct":"Correcto. --amend es la goma del último commit local: incluye lo olvidado sin ensuciar el historial.","incorrect":"git commit --amend integra el archivo al último commit. Un commit de 'ups' extra solo agrega ruido."}}$j$),
  (16, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué git commit --amend es peligroso sobre un commit YA compartido?","options":["Consume mucha memoria","Porque genera un commit con hash NUEVO (reescribe la historia): si otros ya tienen el commit original, tu versión reescrita choca con la suya — no se reescribe historia pública","Porque borra el mensaje","No es peligroso nunca"],"correctIndex":1,"feedback":{"correct":"Correcto. amend reescribe: en local es seguro, sobre lo publicado choca con la historia de los demás.","incorrect":"El commit enmendado tiene hash nuevo (historia reescrita). Sobre algo compartido, eso divide los historiales."}}$j$),
  (17, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un tag y para qué se usa sobre todo?","options":["Una rama con otro nombre","Una marca con nombre CLAVADA en un commit (no se mueve): señala versiones/releases para volver al código exacto de una versión","Un mensaje de commit","Un tipo de conflicto"],"correctIndex":1,"feedback":{"correct":"Correcto. Marcador fijo sobre un commit: los tags marcan versiones (v1.0.0…).","incorrect":"El tag es una etiqueta permanente sobre un commit; marca versiones. La rama, en cambio, se mueve."}}$j$),
  (18, 'quiz', $j${"variant":"multiple_choice","prompt":"En versionado semántico MAYOR.MENOR.PARCHE, agregas una funcionalidad NUEVA compatible con lo anterior. ¿Qué número sube?","options":["El MAYOR: v1.4.3 → v2.0.0","El MENOR (el de en medio): v1.4.3 → v1.5.0, y el parche vuelve a 0","El PARCHE: v1.4.3 → v1.4.4","Ninguno"],"correctIndex":1,"feedback":{"correct":"Correcto. Función nueva compatible = subir menor (parche a 0). Arreglo = parche; ruptura = mayor.","incorrect":"Funcionalidad nueva compatible sube el MENOR (v1.5.0). El parche es para arreglos; el mayor para cambios que rompen."}}$j$),
  (19, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre git diff y git status?","options":["Ninguna","status resume QUÉ archivos cambiaron y en qué estado; diff muestra QUÉ cambió dentro, línea por línea","status es para diff remotos","diff borra y status guarda"],"correctIndex":1,"feedback":{"correct":"Correcto. status = mapa por archivo; diff = lupa por línea. Se usan juntos antes de commitear.","incorrect":"status clasifica los archivos por estado; diff muestra el detalle línea a línea de los cambios."}}$j$),
  (20, 'quiz', $j${"variant":"multiple_choice","prompt":"El hilo que une commits atómicos, mensajes claros y tags: ¿qué buscan todos?","options":["Hacer Git más lento","Un HISTORIAL PROFESIONAL: legible, revisable, reversible y navegable — para que tú y tu equipo entiendan y recuperen el trabajo meses después","Ocupar menos espacio","Impresionar al jefe"],"correctIndex":1,"feedback":{"correct":"Correcto. Todo el módulo apunta a un historial que sirve al futuro: la diferencia entre Git 'usado' y Git 'dominado'.","incorrect":"El objetivo común es un historial profesional: claro, revisable y recuperable. No es velocidad ni espacio."}}$j$),
  (21, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de cierre: ¿por qué el área de preparación (staging), que parece un paso de más, es en realidad la pieza clave de un buen historial?","options":["Porque hace los commits más rápidos","Porque te deja ELEGIR con precisión qué cambios entran en cada commit: sin ella, cada commit sería 'todo lo que toqué'; con ella, cada commit es una idea atómica, revisable y reversible por separado","Porque cifra los archivos","Porque conecta con GitHub"],"correctIndex":1,"feedback":{"correct":"Impecable. El staging es lo que convierte 'guardar cambios' en 'construir un historial con sentido'. Cierra el módulo entero.","incorrect":"El staging existe para que elijas qué entra en cada commit: es lo que hace posibles los commits atómicos y el historial profesional."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm02-x01-intermedia';
