-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 051 — Git desde Cero · M3: Ramas, fusiones y conflictos
-- ═══════════════════════════════════════════════════════════════════
-- Unidad 3 del temario (bloques 14-21 + Práctica 3). Cubre: la rama como
-- puntero (Diagrama 3.1), crear/cambiar de rama (switch), el flujo por
-- funcionalidad, merge fast-forward vs tres vías (Diagrama 3.2), LA
-- resolución de conflictos (la lección clave del curso), la prevención,
-- rebase introductorio y stash. Práctica: resolver un conflicto real.
-- Precisiones vinculantes: una rama es una REFERENCIA ligera a un commit,
-- no una copia; un conflicto NO es un error (es Git pidiendo una decisión
-- humana); switch es el comando moderno (checkout tiene usos más amplios);
-- rebase reescribe historia → no sobre ramas públicas compartidas.
-- Curso language = bash → práctica por regex + mockOutput (resolución de
-- conflicto validada con lookahead negativo: archivo final sin marcadores).
-- Curso is_published = false: nada visible hasta el flip final (056).
-- Idempotente. Ejecutar DESPUÉS de 048.
-- ═══════════════════════════════════════════════════════════════════

delete from public.lessons
where module_id = (
  select m.id from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'git-desde-cero' and m.slug = 'm03-ramas'
);

insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m03-l01-que-es-rama',   'Qué es una rama',                     'leccion',  20, 1),
       ('m03-l02-crear-cambiar', 'Crear y cambiar de rama',             'leccion',  20, 2),
       ('m03-l03-flujo',         'El flujo de trabajo por funcionalidad','leccion', 20, 3),
       ('m03-l04-fusionar',      'Fusionar ramas',                      'leccion',  20, 4),
       ('m03-l05-conflictos',    'Conflictos de fusión',                'leccion',  20, 5),
       ('m03-l06-prevenir',      'Prevenir conflictos',                 'leccion',  20, 6),
       ('m03-l07-rebase',        'Introducción a rebase',               'leccion',  20, 7),
       ('m03-l08-stash',         'Guardar trabajo a medias con stash',  'leccion',  20, 8),
       ('m03-l09-practica',      'Práctica: resolver un conflicto',     'practica', 20, 9),
       ('m03-x01-examen',        'Examen: Ramas y fusiones',            'examen',   40, 10)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'git-desde-cero' and m.slug = 'm03-ramas';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Qué es una rama (+ Diagrama 3.1)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Trabajar sin romper lo que funciona","body":"Hasta ahora tu historial fue una sola línea recta de commits. Pero en la vida real necesitas experimentar sin arriesgar lo que ya funciona: agregar la recuperación de contraseña al sistema de la clínica SIN que un error a medias tumbe la versión que está en producción. Esa es la razón de ser de las RAMAS. Una rama es una línea de desarrollo independiente: te separas de la línea principal, trabajas tranquilo en tu funcionalidad, y cuando está lista la integras de vuelta. Mientras tanto, la rama principal sigue intacta y funcionando. La rama principal se llama por convención main (antes master); las que creas para tareas concretas son ramas de trabajo que nacen, cumplen su propósito y se integran."}$j$),
  (2, 'texto', $j${"title":"La precisión: una rama es un PUNTERO, no una copia","body":"Aquí está el concepto que hace que Git sea rápido y que tantos malentienden. Crear una rama NO copia tus archivos ni duplica el proyecto — sería lentísimo. Una rama es simplemente una REFERENCIA LIGERA: un puntero con nombre que apunta a un commit. Nada más. main es un puntero; feature/login es otro puntero. Crear una rama es crear un puntero nuevo (instantáneo, pesa casi nada). Y como cada commit enlaza a su padre, desde el commit al que apunta una rama se puede reconstruir toda su historia hacia atrás. Lo que MUEVE los punteros es hacer commits: cuando estás en una rama y commiteas, ESA rama avanza al commit nuevo. Entender que 'rama = puntero que se mueve' desarma casi todos los miedos con Git."}$j$),
  (3, 'diagrama', $j${"title":"Diagrama 3.1 · La rama es un puntero","component":"NetworkDiagram","props":{"label":"Los commits son la historia; las ramas son punteros que la señalan","ancho":520,"alto":300,"nodos":[{"id":"c1","x":40,"y":150,"w":80,"h":50,"titulo":"C1","subtitulo":"esquema","descripcion":"El primer commit. Cada commit enlaza a su padre: desde cualquiera se reconstruye la historia hacia atrás."},{"id":"c2","x":170,"y":150,"w":80,"h":50,"titulo":"C2","subtitulo":"pacientes","descripcion":"Segundo commit, hijo de C1."},{"id":"c3","x":300,"y":150,"w":80,"h":50,"titulo":"C3","subtitulo":"citas","descripcion":"Tercer commit. Aquí apuntan ahora mismo las dos ramas: acaban de partir del mismo punto."},{"id":"main","x":270,"y":50,"w":140,"h":44,"titulo":"main","tag":"puntero","descripcion":"La rama principal: un puntero que señala el commit C3. NO es una copia de los archivos — es solo una referencia con nombre."},{"id":"feature","x":270,"y":238,"w":170,"h":44,"titulo":"feature/login","tag":"puntero","descripcion":"Una rama nueva: otro puntero, también sobre C3. Crearla fue instantáneo porque no copió nada. Cuando commitees en ella, ESTE puntero avanzará y main se quedará en C3."}],"enlaces":[{"de":"c2","a":"c1","tipo":"flecha","descripcion":"C2 enlaza a su padre C1. Las flechas de la historia apuntan hacia atrás, al pasado."},{"de":"c3","a":"c2","tipo":"flecha","descripcion":"C3 enlaza a C2: la cadena de commits que forma el historial."},{"de":"main","a":"c3","tipo":"flecha","discontinuo":true,"etiqueta":"apunta a","descripcion":"main señala C3."},{"de":"feature","a":"c3","tipo":"flecha","discontinuo":true,"etiqueta":"apunta a","descripcion":"feature/login también señala C3: ambas ramas parten del mismo commit hasta que una avance."}],"hint":"Toca las ramas: son punteros sobre los commits, no copias."},"caption":"Los commits (C1→C2→C3) son la historia inmutable; main y feature/login son solo punteros que la señalan. Commitear mueve el puntero de la rama actual hacia adelante."}$j$),
  (4, 'texto', $j${"title":"HEAD: en qué rama estás parado","body":"Si las ramas son punteros a commits, HEAD es el puntero a la RAMA en la que estás trabajando ahora — el 'estás aquí'. Normalmente HEAD apunta a una rama (por ejemplo a main), y esa rama apunta a un commit. Por eso, cuando commiteas, Git sabe qué puntero mover: el de la rama a la que HEAD señala. Cambiar de rama es, en el fondo, mover HEAD para que apunte a otra rama. (Existe un estado llamado 'detached HEAD' —HEAD apuntando directo a un commit en vez de a una rama— que suena alarmante pero solo significa 'estás mirando un commit suelto, no la punta de una rama'; se sale volviendo a una rama con git switch. No es un error ni una emergencia.) HEAD → rama → commit: esa cadenita explica todo el movimiento en Git."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es realmente una rama en Git?","options":["Una copia completa de todos los archivos del proyecto","Una REFERENCIA LIGERA: un puntero con nombre que apunta a un commit — crearla es instantáneo porque no copia nada","Una carpeta separada","Un respaldo del proyecto"],"correctIndex":1,"feedback":{"correct":"Correcto. Rama = puntero a un commit. Por eso crear ramas es instantáneo y barato: no se duplica nada.","incorrect":"Una rama no copia archivos: es un puntero con nombre a un commit. Esa ligereza es lo que hace a Git rápido."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Estás en la rama feature/login y haces un commit. ¿Qué le pasa a los punteros?","options":["Se mueven todas las ramas","AVANZA solo feature/login (la rama actual) al commit nuevo; main se queda donde estaba","Se crea una rama nueva","No pasa nada hasta hacer merge"],"correctIndex":1,"feedback":{"correct":"Correcto. Commitear mueve el puntero de la rama en la que estás; las demás no se enteran.","incorrect":"Solo avanza la rama actual (a la que apunta HEAD). main permanece en su commit hasta que integres."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué representa HEAD en el modelo de ramas?","options":["El primer commit del proyecto","El puntero a la RAMA en la que estás trabajando ahora (HEAD → rama → commit): por eso Git sabe qué puntero mover al commitear","El nombre del repositorio","Un tipo de tag"],"correctIndex":1,"feedback":{"correct":"Correcto. HEAD señala tu rama actual; esa rama señala un commit. Cambiar de rama mueve HEAD.","incorrect":"HEAD apunta a la rama actual (normalmente), y esa rama a un commit. Es el 'estás aquí' del trabajo."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Qué es una rama","points":["Una rama es una línea de desarrollo independiente: trabajas sin arriesgar lo que ya funciona en main.","PRECISIÓN: una rama es un PUNTERO ligero a un commit, no una copia — crearla es instantáneo.","Commitear mueve el puntero de la rama ACTUAL hacia adelante; las otras ramas no se mueven.","HEAD apunta a la rama en la que estás (HEAD → rama → commit).","'detached HEAD' = estás mirando un commit suelto, no una emergencia: se sale con git switch a una rama."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l01-que-es-rama';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Crear y cambiar de rama
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Los comandos de las ramas","body":"Tres gestos básicos. LISTAR: git branch (sin argumentos) muestra todas las ramas y marca con un asterisco la actual. CREAR: git branch feature/login crea una rama nueva (un puntero) sobre el commit actual… pero NO te cambia a ella — te quedas donde estabas. CAMBIAR: git switch feature/login te mueve a la rama (HEAD ahora apunta ahí). Como casi siempre quieres crear y cambiarte de una vez, existe el atajo git switch -c feature/login (la c es de 'create'): crea la rama y te lleva a ella en un solo paso. Al cambiar de rama, Git ajusta tu directorio de trabajo para que coincida con esa rama — los archivos se ven como estaban en el commit al que la rama apunta."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Crear una rama para la incidencia CLI-142","code":"# Ver en qué rama estoy\ngit branch\n\n# Crear y cambiarme de una vez a la rama de la tarea\ngit switch -c feature/CLI-142-recuperar-contrasena\n\n# Confirmar dónde estoy ahora\ngit branch","caption":"switch -c = crear + cambiar en un paso. El nombre de la rama refleja la incidencia (CLI-142): trazabilidad desde el inicio.","result":{"columns":["git branch (después)"],"rows":[["* feature/CLI-142-recuperar-contrasena"],["  main"]],"note":"El asterisco marca la rama actual: ya estás en la de la tarea. main sigue ahí, intacta, esperando la integración. El nombre descriptivo (feature/ + número de incidencia) hace evidente para qué existe la rama."}}$j$),
  (3, 'texto', $j${"title":"switch, y por qué no checkout","body":"Quizá veas en tutoriales viejos git checkout para cambiar de rama — y funciona. Pero Git introdujo git switch precisamente para esa tarea, porque checkout hace DEMASIADAS cosas distintas (cambiar de rama, restaurar archivos, mirar commits sueltos…), y esa sobrecarga causaba errores y confusión. La familia moderna reparte el trabajo en comandos con un propósito claro cada uno: git switch para moverte entre ramas, y git restore (que ya usaste) para recuperar archivos. Este curso usa switch por esa razón — es más explícito y más difícil de usar mal. Si en un proyecto ves checkout para cambiar de rama, no está roto; es el estilo anterior. Tú aprende el moderno: dice exactamente lo que hace."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué diferencia hay entre git branch feature/x y git switch feature/x?","options":["Son idénticos","git branch feature/x CREA la rama pero NO te cambia a ella (te quedas donde estás); git switch feature/x te MUEVE a la rama","branch borra y switch crea","Ninguno de los dos crea ramas"],"correctIndex":1,"feedback":{"correct":"Correcto. branch crea el puntero; switch mueve HEAD hacia él. Por eso existe el atajo switch -c (crea y cambia).","incorrect":"git branch crea la rama sin moverte; git switch te lleva a ella. Para hacer ambos: git switch -c."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres crear la rama feature/pago Y empezar a trabajar en ella de inmediato. ¿El comando más directo?","options":["git branch feature/pago","git switch -c feature/pago — crea la rama y te cambia a ella en un solo paso","git checkout feature/pago","git merge feature/pago"],"correctIndex":1,"feedback":{"correct":"Correcto. switch -c (create) hace las dos cosas: crea el puntero y te lleva ahí.","incorrect":"git switch -c feature/pago crea y cambia de una vez. git branch solo crearía la rama sin moverte."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué este curso usa git switch en vez de git checkout para cambiar de rama?","options":["checkout está eliminado de Git","Porque switch tiene UN propósito claro (moverse entre ramas), mientras checkout hace muchas cosas distintas y por eso confunde y se usa mal — switch es más explícito","switch es más rápido","checkout solo sirve en Windows"],"correctIndex":1,"feedback":{"correct":"Correcto. switch (cambiar de rama) y restore (recuperar archivos) reparten lo que checkout mezclaba. Más claro, más seguro.","incorrect":"checkout sigue existiendo, pero hace demasiadas tareas. switch es el comando moderno y específico para cambiar de rama."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Crear y cambiar de rama","points":["git branch lista las ramas (asterisco = actual); git branch nombre crea una sin cambiarte.","git switch nombre te mueve a la rama; git switch -c nombre crea Y cambia en un paso.","Al cambiar de rama, Git ajusta el directorio de trabajo al commit de esa rama.","Nombres descriptivos ligados a la incidencia (feature/CLI-142-…): trazabilidad desde el inicio.","switch es el comando MODERNO y específico; checkout (más amplio) es el estilo anterior."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l02-crear-cambiar';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · El flujo de trabajo por funcionalidad
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La coreografía de una funcionalidad","body":"Las ramas siguen un baile que se repite en todos los equipos, y conviene volverlo un hábito. UNO: partir de main ACTUALIZADA (más importante cuando colaboras, módulo 4). DOS: crear la rama de la tarea desde main (git switch -c feature/…). TRES: implementar los cambios con commits atómicos y buenos mensajes (todo lo del módulo 2 aplica dentro de la rama). CUATRO: revisar el diff antes de integrar. CINCO: integrar la rama de vuelta a main. SEIS: borrar la rama ya integrada, porque su puntero cumplió su función y dejarla acumula ramas muertas que estorban. Cada tarea nace en su rama, vive ahí sin molestar a nadie, y al terminar se funde con main y desaparece. Una rama por tarea: esa es la regla."}$j$),
  (2, 'texto', $j${"title":"Nombres de rama que comunican","body":"El nombre de una rama dice de un vistazo para qué existe. Las convenciones más comunes usan un prefijo por tipo: feature/ para funcionalidades nuevas (feature/recuperar-contrasena), fix/ para correcciones (fix/error-total), hotfix/ para arreglos urgentes en producción (hotfix/pago-duplicado), docs/ para documentación, refactor/ para reestructurar. Muchos equipos incluyen el número de la incidencia (feature/CLI-142-recuperar-contrasena) para tejer la trazabilidad tarea↔rama↔commit↔integración. Como con los mensajes de commit y con Conventional Commits: la nomenclatura exacta la fija cada EQUIPO — Git no impone ninguna. Lo innegociable es tener una convención y respetarla, para que las ramas del proyecto se lean todas igual."}$j$),
  (3, 'ejemplo_codigo', $j${"title":"El ciclo completo de una rama","code":"# 1-2 · Partir de main y crear la rama de la tarea\ngit switch main\ngit switch -c feature/CLI-142-recuperar-contrasena\n\n# 3 · Trabajar: commits atómicos dentro de la rama\ngit add recuperar.py\ngit commit -m \"Agrega el flujo de recuperacion de contrasena\"\n\n# 4 · Revisar antes de integrar\ngit diff main\n\n# 5-6 · (integrar a main — proxima leccion) y limpiar\ngit switch main\ngit branch -d feature/CLI-142-recuperar-contrasena","caption":"Una rama por tarea: nace de main, vive con sus commits, se integra y se borra (-d) una vez fundida.","result":{"columns":["FLUJO"],"rows":[["switch -c  → rama creada y activa"],["commit     → trabajo aislado en la rama"],["(merge)    → integración a main (L4)"],["branch -d  → rama borrada tras integrar"]],"note":"git branch -d borra una rama YA integrada (la -d es de 'delete', y se niega a borrar trabajo sin fusionar, protegiéndote). El puntero desaparece; los commits que aportó viven ahora en main."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es el orden correcto del flujo por funcionalidad?","options":["Crear rama → borrarla → hacer commits","Partir de main actualizada → crear la rama de la tarea → commits atómicos → revisar → integrar a main → borrar la rama","Commitear en main → crear rama → publicar","Fusionar primero → después crear la rama"],"correctIndex":1,"feedback":{"correct":"Correcto. Nace de main, vive con sus commits, se integra y se borra: una tarea, una rama, un ciclo limpio.","incorrect":"El ciclo: main actualizada → rama de la tarea → trabajo → revisar → integrar → borrar la rama fusionada."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué se BORRA una rama después de integrarla a main?","options":["Para ahorrar espacio en disco","Porque su puntero ya cumplió su función: los commits viven ahora en main, y dejar ramas muertas acumula desorden que estorba","Porque Git obliga a borrarla","Para que nadie vea el trabajo"],"correctIndex":1,"feedback":{"correct":"Correcto. Integrada la rama, su puntero sobra. Borrarlo (git branch -d) mantiene la lista de ramas limpia.","incorrect":"Tras el merge, los commits ya están en main; la rama es un puntero muerto. Se borra para no acumular ramas viejas."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Sobre las convenciones de nombres de rama (feature/, fix/, hotfix/…):","options":["Git las exige y valida","Las fija cada EQUIPO — Git no impone ninguna; lo importante es tener una convención consistente y respetarla para que las ramas se lean igual","Solo existen en GitHub","Son obligatorias desde Git 2.0"],"correctIndex":1,"feedback":{"correct":"Correcto. Como los mensajes y Conventional Commits: convención de equipo, no regla de Git. Lo clave es la consistencia.","incorrect":"Los prefijos de rama son convención del equipo. Git acepta cualquier nombre; el valor está en usarlos de forma consistente."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Flujo por funcionalidad","points":["Una tarea, una rama: nace de main actualizada, vive con commits atómicos, se integra y se borra.","El ciclo: partir de main → switch -c → trabajar → revisar (diff) → integrar → git branch -d.","git branch -d borra ramas YA integradas (se niega a borrar trabajo sin fusionar: te protege).","Nombres por tipo (feature/, fix/, hotfix/…) + número de incidencia para trazabilidad.","La convención de nombres la fija el equipo; lo innegociable es tener una y respetarla."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l03-flujo';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Fusionar ramas (+ Diagrama 3.2)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Traer el trabajo de vuelta","body":"Terminaste la funcionalidad en su rama; ahora hay que INTEGRARLA a main. La fusión (merge) combina el trabajo de una rama con otra. El gesto tiene una lógica que confunde al principio pero es simple: te paras en la rama que RECIBE (main) y traes la otra. Es decir: git switch main para ubicarte en el destino, y luego git merge feature/login para traer los commits de la rama de trabajo hacia main. Piénsalo como 'estoy en main y jalo hacia aquí lo de feature'. Tras el merge, main contiene todo lo que hiciste en la rama, y ya puedes borrar esta última. Según cómo hayan evolucionado las dos ramas, Git resuelve la fusión de una de dos maneras."}$j$),
  (2, 'texto', $j${"title":"Fast-forward: cuando main no se movió","body":"Primer caso, el más simple. Si desde que creaste tu rama la rama main NO recibió ningún commit nuevo (nadie más tocó main), entonces main sigue apuntando al commit desde el que partiste, y tu rama simplemente añadió commits más adelante. Integrar es trivial: Git solo tiene que MOVER el puntero de main hacia adelante, hasta donde está tu rama. A esto se le llama FAST-FORWARD ('avance rápido'): no se crea ningún commit nuevo, solo se adelanta el puntero. El historial queda como una línea recta, como si nunca hubiera habido rama. Es el resultado limpio y frecuente cuando trabajas solo o cuando tu rama fue corta y nadie más avanzó main mientras tanto."}$j$),
  (3, 'texto', $j${"title":"Merge de tres vías: cuando las dos avanzaron","body":"Segundo caso. Si main SÍ recibió commits mientras trabajabas en tu rama (alguien más integró otra cosa), las dos líneas DIVERGIERON: main fue por un lado, tu rama por otro, desde un ancestro común. Ahora un simple 'adelantar el puntero' no basta — hay dos historias que combinar. Git hace un MERGE DE TRES VÍAS: mira el ancestro común y las dos puntas, combina los cambios, y crea un COMMIT DE FUSIÓN especial que tiene DOS padres (una punta de cada rama) y ata las dos historias en una. Ese commit de merge es la costura visible donde se unieron dos líneas de trabajo. El historial deja de ser recto: se ve la bifurcación y su reunión — lo cual, lejos de ser feo, cuenta la verdad de cómo se desarrolló el proyecto."}$j$),
  (4, 'diagrama', $j${"title":"Diagrama 3.2 · Fast-forward vs merge de tres vías","component":"NetworkDiagram","props":{"label":"Dos formas de integrar, según si main avanzó o no","ancho":520,"alto":360,"grupos":[{"id":"ff","x":14,"y":24,"w":492,"h":130,"titulo":"FAST-FORWARD — main no se movió","descripcion":"main seguía en A cuando la rama añadió B y C. Integrar = adelantar el puntero main de A hasta C. Sin commit nuevo; historial recto."},{"id":"tw","x":14,"y":170,"w":492,"h":180,"titulo":"TRES VÍAS — las dos avanzaron","descripcion":"Desde el ancestro A, main fue a D y la rama a B-C. Git combina ambas y crea un COMMIT DE FUSIÓN (M) con dos padres."}],"nodos":[{"id":"ffa","x":60,"y":78,"w":70,"h":44,"titulo":"A","descripcion":"El commit donde estaba main cuando creaste la rama."},{"id":"ffb","x":180,"y":78,"w":70,"h":44,"titulo":"B","descripcion":"Primer commit de tu rama."},{"id":"ffc","x":300,"y":78,"w":70,"h":44,"titulo":"C","tag":"main→ aquí","descripcion":"Segundo commit de tu rama. Como main nunca se movió de A, integrar solo adelanta main hasta C: fast-forward."},{"id":"twa","x":50,"y":250,"w":66,"h":42,"titulo":"A","subtitulo":"ancestro","descripcion":"El ancestro común: el punto donde main y la rama se separaron."},{"id":"twd","x":160,"y":196,"w":66,"h":42,"titulo":"D","subtitulo":"main","descripcion":"Mientras trabajabas, main avanzó a D (alguien integró otra cosa)."},{"id":"twb","x":160,"y":300,"w":66,"h":42,"titulo":"B","descripcion":"Tu rama avanzó por otro lado: B…"},{"id":"twc","x":270,"y":300,"w":66,"h":42,"titulo":"C","subtitulo":"rama","descripcion":"…y C. Las dos líneas divergieron desde A."},{"id":"twm","x":380,"y":248,"w":90,"h":46,"titulo":"M","tag":"merge","descripcion":"El COMMIT DE FUSIÓN: tiene DOS padres (D y C) y une las dos historias. main avanza hasta aquí."}],"enlaces":[{"de":"ffb","a":"ffa","tipo":"flecha","descripcion":"B enlaza a A."},{"de":"ffc","a":"ffb","tipo":"flecha","descripcion":"C enlaza a B: una línea recta."},{"de":"twd","a":"twa","tipo":"flecha","descripcion":"D (main) desciende de A."},{"de":"twb","a":"twa","tipo":"flecha","descripcion":"B (rama) también desciende de A: aquí divergen."},{"de":"twc","a":"twb","tipo":"flecha","descripcion":"C enlaza a B."},{"de":"twm","a":"twd","tipo":"flecha","etiqueta":"padre 1","descripcion":"El merge M tiene como un padre a D (la punta de main)."},{"de":"twm","a":"twc","tipo":"flecha","etiqueta":"padre 2","descripcion":"Y como otro padre a C (la punta de la rama): dos historias, un commit que las une."}],"hint":"Arriba: adelantar el puntero. Abajo: un commit de fusión con dos padres."},"caption":"Fast-forward (arriba): main no avanzó, solo se adelanta el puntero — historial recto. Tres vías (abajo): ambas avanzaron, Git crea un commit de fusión con dos padres."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Para fusionar feature/login en main, ¿dónde te paras y qué comando corres?","options":["En feature/login, y git merge main","En main (git switch main), y luego git merge feature/login — te ubicas en el destino y traes la otra rama","En cualquier rama, con git merge --all","No importa la rama actual"],"correctIndex":1,"feedback":{"correct":"Correcto. Te paras en la que RECIBE (main) y jalas la de trabajo: 'estoy en main y traigo feature'.","incorrect":"Primero git switch main (el destino), luego git merge feature/login. Se integra HACIA la rama en la que estás."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo ocurre un FAST-FORWARD al fusionar?","options":["Siempre que haya conflictos","Cuando main NO recibió commits nuevos desde que creaste la rama: Git solo adelanta el puntero de main hasta tu rama, sin crear commit de fusión — historial recto","Cuando hay dos padres","Cuando borras la rama"],"correctIndex":1,"feedback":{"correct":"Correcto. main no se movió → solo se adelanta su puntero. Limpio y sin commit extra.","incorrect":"Fast-forward = main no avanzó, así que integrar es solo mover su puntero hacia adelante. Sin commit de fusión."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué caracteriza a un COMMIT DE FUSIÓN (merge de tres vías)?","options":["No tiene mensaje","Tiene DOS padres (una punta de cada rama) y une dos historias que habían divergido desde un ancestro común — aparece cuando las dos ramas avanzaron","Borra una de las ramas","Es idéntico a un fast-forward"],"correctIndex":1,"feedback":{"correct":"Correcto. Dos padres = la costura donde se reunieron dos líneas. Surge cuando main y la rama divergieron.","incorrect":"El commit de fusión tiene dos padres y ata las dos historias. Aparece en el merge de tres vías, no en el fast-forward."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Fusionar ramas","points":["Para integrar: git switch main (el destino) y luego git merge feature/x (traes la rama de trabajo).","FAST-FORWARD: main no avanzó → Git solo adelanta su puntero; historial recto, sin commit nuevo.","MERGE DE TRES VÍAS: ambas avanzaron → Git combina desde el ancestro común y crea un commit de fusión con DOS padres.","El commit de fusión es la costura visible de dos líneas de trabajo reunidas: no es feo, cuenta la verdad.","Tras integrar, la rama de trabajo se puede borrar (git branch -d)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l04-fusionar';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Conflictos de fusión (la lección clave)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Un conflicto NO es un error","body":"Empecemos por desactivar el miedo, porque este es el tema que más asusta sin razón. Un CONFLICTO DE FUSIÓN ocurre cuando dos ramas cambiaron LA MISMA parte del MISMO archivo de formas distintas, y Git —al fusionar— no puede decidir cuál versión es la buena. Y aquí está la precisión más importante del módulo: eso NO es un error, ni un fallo, ni algo que rompiste. Es Git siendo honesto: 'dos personas editaron esta misma línea; yo no sé cuál es la correcta, esa decisión es HUMANA, decídela tú'. Git combina automáticamente todo lo que puede (cambios en archivos distintos, o en partes distintas del mismo archivo, se fusionan solos sin que te enteres); solo te pide ayuda en el pedazo exacto donde hay una contradicción real. Un conflicto es una pausa para una decisión, no una alarma."}$j$),
  (2, 'texto', $j${"title":"Los marcadores: leer lo que Git te muestra","body":"Cuando hay conflicto, Git pausa la fusión y EDITA el archivo conflictivo para mostrarte las dos versiones, marcadas con símbolos inconfundibles. Se ven así: <<<<<<< HEAD abre la sección con TU versión (la de la rama en la que estás); luego ======= es la línea divisoria; y >>>>>>> nombre-de-rama cierra con la versión de la OTRA rama. Entre esos marcadores están las dos alternativas, una arriba de la línea divisoria y otra abajo. Tu trabajo es simple de enunciar: DECIDIR qué debe quedar —una versión, la otra, una combinación de ambas, o algo nuevo— y BORRAR los marcadores por completo, dejando el archivo como debe quedar de verdad. El archivo resuelto NO lleva ningún <<<<<<<, ninguna =======, ningún >>>>>>>: esos son andamios que se quitan al terminar."}$j$),
  (3, 'ejemplo_codigo', $j${"title":"Un conflicto, antes y después","code":"# Al fusionar, Git avisa:\n#   Auto-merging config.py\n#   CONFLICT (content): Merge conflict in config.py\n#   Automatic merge failed; fix conflicts and then commit.\n\n# Git dejo config.py asi (los marcadores):\n<<<<<<< HEAD\nLIMITE_CITAS = 10\n=======\nLIMITE_CITAS = 20\n>>>>>>> feature/aumentar-limite\n\n# Tu decides (el negocio pidio 20) y lo dejas asi:\nLIMITE_CITAS = 20","caption":"Arriba de ======= tu versión (HEAD); abajo la de la otra rama. Resolver = elegir y borrar TODOS los marcadores.","result":{"columns":["config.py resuelto"],"rows":[["LIMITE_CITAS = 20"]],"note":"El archivo final no tiene ni un marcador: quedó limpio, con el valor decidido. Ese es el criterio de 'conflicto resuelto': ningún <<<<<<<, ======= ni >>>>>>> sobrevive."}}$j$),
  (4, 'texto', $j${"title":"Cerrar la fusión (o abortarla)","body":"Una vez que editaste el archivo y quitaste los marcadores, le avisas a Git que ese archivo ya está resuelto con git add archivo (sí, el mismo add de siempre: marca el conflicto como solucionado). Cuando todos los archivos conflictivos estén resueltos y agregados, git commit cierra la fusión creando el commit de merge — Git suele proponerte un mensaje automático que puedes aceptar. Y si te arrepientes a mitad del camino —el conflicto es más enredado de lo que pensabas, o quieres empezar de nuevo— git merge --abort cancela la fusión por completo y devuelve todo al estado anterior al merge, como si nunca lo hubieras intentado. Tener ese botón de escape quita toda la presión: intentar un merge nunca es irreversible."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Aparece un conflicto de fusión. ¿Qué significa realmente?","options":["Rompiste el repositorio","Dos ramas cambiaron la MISMA parte del MISMO archivo de forma distinta, y Git no sabe cuál es la correcta: te pide una decisión HUMANA — no es un error","Git tiene un bug","Perdiste tu trabajo"],"correctIndex":1,"feedback":{"correct":"Correcto. El conflicto es una pausa para decidir, no una falla. Git resolvió solo todo lo demás.","incorrect":"Un conflicto no es un error: es Git avisando que hay una contradicción que solo un humano puede resolver."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"En un archivo con conflicto, ¿qué separan los marcadores <<<<<<< HEAD … ======= … >>>>>>> rama?","options":["El código bueno del malo","Arriba de ======= está TU versión (HEAD, tu rama); abajo la versión de la OTRA rama — las dos alternativas en conflicto","Los comentarios del código","Dos archivos distintos"],"correctIndex":1,"feedback":{"correct":"Correcto. HEAD arriba (lo tuyo), la otra rama abajo, separadas por =======. Tú eliges qué queda.","incorrect":"Los marcadores muestran las dos versiones: la tuya (HEAD) arriba y la de la otra rama abajo, divididas por ======="}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo se considera RESUELTO un conflicto en un archivo?","options":["Cuando eliges la versión de arriba","Cuando editaste el archivo dejándolo como debe quedar y BORRASTE todos los marcadores (<<<<<<<, =======, >>>>>>>): ninguno debe sobrevivir","Cuando Git lo resuelve solo","Cuando reinicias el merge"],"correctIndex":1,"feedback":{"correct":"Correcto. Resuelto = archivo con la decisión tomada y CERO marcadores. Luego git add lo marca como listo.","incorrect":"Se resuelve dejando el archivo correcto y sin ningún marcador. Un marcador olvidado significa que el conflicto sigue ahí."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Tras editar los archivos y quitar los marcadores, ¿cómo se cierra la fusión? ¿Y cómo se cancela si te arrepientes?","options":["Se guarda el archivo y ya; no se puede cancelar","Cerrar: git add (marca cada archivo como resuelto) y git commit crea el merge. Cancelar: git merge --abort devuelve todo al estado previo al merge","Cerrar con git push; cancelar con git delete","Ambas con git reset"],"correctIndex":1,"feedback":{"correct":"Correcto. add resuelto + commit cierra; --abort es el botón de escape que hace el merge reversible.","incorrect":"Se cierra con git add (resuelto) + git commit. Y git merge --abort cancela todo: intentar un merge nunca es irreversible."}}$j$),
  (9, 'resumen', $j${"title":"Resumen — Conflictos de fusión","points":["PRECISIÓN: un conflicto NO es un error — es Git pidiendo una decisión humana cuando dos ramas cambiaron lo mismo.","Git combina solo todo lo que puede; solo marca el pedazo con contradicción real.","Marcadores: <<<<<<< HEAD (tu versión) ======= (divisoria) >>>>>>> rama (la otra versión).","Resolver = dejar el archivo como debe quedar y BORRAR todos los marcadores; luego git add.","git commit cierra la fusión; git merge --abort la cancela y vuelve al estado previo (reversible)."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l05-conflictos';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · Prevenir conflictos
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Los conflictos se resuelven; mejor evitarlos","body":"Ya sabes resolver un conflicto sin miedo. Pero un conflicto siempre cuesta tiempo y atención, y la mayoría se pueden PREVENIR con hábitos de equipo. El principal: RAMAS PEQUEÑAS Y DE CORTA VIDA. Una rama que vive dos horas casi nunca choca; una que vive tres semanas, acumulando cambios mientras main avanza por su lado, es una bomba de conflictos. Cuanto más tiempo diverge tu rama de main, más probable es que ambas hayan tocado lo mismo. La receta es integrar seguido: tareas chicas, ramas cortas, fusiones frecuentes — en vez de una rama gigante que al final choca con medio proyecto."}$j$),
  (2, 'texto', $j${"title":"Los otros hábitos","body":"Más costumbres que reducen los choques. ACTUALIZARSE CON FRECUENCIA: traer a menudo los cambios de main a tu rama (lo verás con fetch/pull en el módulo 4) para que la divergencia no crezca en silencio — descubres los conflictos pequeños y temprano, no todos juntos al final. COORDINAR LOS CAMBIOS ESTRUCTURALES: si vas a reorganizar un archivo que todos tocan, avisar antes evita que tres personas lo reescriban a la vez. DIVIDIR RESPONSABILIDADES: cuando el equipo se reparte áreas distintas del código, dos personas rara vez editan la misma línea. Y REVISAR EL DIFF ANTES DE FUSIONAR: mirar qué vas a integrar anticipa sorpresas. Ninguna de estas garantiza cero conflictos —son inevitables al colaborar— pero juntas los vuelven raros y pequeños en vez de frecuentes y enormes."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la principal estrategia para prevenir conflictos de fusión?","options":["Nunca usar ramas","RAMAS PEQUEÑAS Y DE CORTA VIDA, integradas seguido: cuanto menos tiempo diverge tu rama de main, menos probable es chocar","Trabajar todos en la misma rama","Prohibir los merges"],"correctIndex":1,"feedback":{"correct":"Correcto. Ramas cortas + integración frecuente = poca divergencia = pocos conflictos.","incorrect":"La clave es reducir la divergencia: ramas pequeñas y de vida corta, fusionadas seguido. Una rama gigante es una bomba de conflictos."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué actualizarte con frecuencia (traer los cambios de main a tu rama) reduce los conflictos graves?","options":["Porque borra los cambios de los demás","Porque descubres los conflictos pequeños TEMPRANO y de a poco, en vez de encontrarlos todos juntos y enormes al final de una rama larga","Porque Git los resuelve solo si actualizas","Porque bloquea a los demás"],"correctIndex":1,"feedback":{"correct":"Correcto. Integrar seguido reparte los conflictos en dosis pequeñas y manejables, en lugar de una avalancha final.","incorrect":"Actualizarte a menudo saca a la luz los choques pronto y pequeños. La rama que ignora main durante semanas choca fuerte al final."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál de estas afirmaciones sobre los conflictos es la correcta?","options":["Con buenos hábitos se garantiza CERO conflictos","Los conflictos son inevitables al colaborar, pero los buenos hábitos (ramas cortas, actualizarse, coordinar, dividir áreas) los vuelven RAROS y PEQUEÑOS en vez de frecuentes y enormes","Los conflictos solo le pasan a los principiantes","Prevenir conflictos es imposible"],"correctIndex":1,"feedback":{"correct":"Correcto. No se eliminan del todo —colaborar implica tocar código común— pero se minimizan en frecuencia y tamaño.","incorrect":"Ningún hábito garantiza cero conflictos, pero los buenos los hacen raros y chicos. Y ya sabes resolverlos sin miedo."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Prevenir conflictos","points":["Principal estrategia: ramas PEQUEÑAS y de corta vida, integradas seguido — menos divergencia, menos choques.","Actualizarse con frecuencia (traer main a tu rama) saca los conflictos pequeños temprano, no todos al final.","Coordinar los cambios estructurales y dividir responsabilidades por áreas del código.","Revisar el diff antes de fusionar anticipa sorpresas.","Los conflictos son inevitables al colaborar; los hábitos los vuelven raros y pequeños, no imposibles."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l06-prevenir';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Introducción a rebase
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Otra forma de integrar: reaplicar en vez de unir","body":"El merge une dos historias creando un commit de fusión. El REBASE resuelve el mismo problema —traer tu rama al día con main— de otra manera: en lugar de UNIR las dos líneas, REAPLICA tus commits encima de la punta de main, como si los hubieras hecho a partir de ahí desde el principio. El resultado es un historial RECTO, sin commit de fusión ni bifurcación visible: se ve como si tu trabajo hubiera venido después del de main, en fila. git rebase main (estando en tu rama) toma tus commits, los 'levanta', avanza tu rama hasta la punta de main, y los vuelve a poner encima uno por uno. Merge conserva la forma real de lo que pasó; rebase la reescribe para que se lea lineal."}$j$),
  (2, 'texto', $j${"title":"La regla de oro (otra vez): no rebasees lo público","body":"El rebase tiene un precio que hay que entender ANTES de usarlo: reaplicar commits crea commits NUEVOS (con hashes distintos) que sustituyen a los viejos. Es decir, rebase REESCRIBE LA HISTORIA — igual que --amend en el módulo 2, y con la misma regla de oro: NUNCA rebasees una rama PÚBLICA que otros ya tienen. Si reescribes commits que tus compañeros ya descargaron, sus historias y la tuya dejan de coincidir y se arma un caos difícil de desenredar. Rebase es seguro solo sobre tu trabajo LOCAL que nadie más ha visto — para limpiar tu propia rama antes de integrarla. Durante un rebase también pueden aparecer conflictos (se resuelven igual: editar, git add, y luego git rebase --continue; o git rebase --abort para cancelar). Este es un vistazo introductorio: el rebase interactivo y sus usos avanzados quedan para más adelante."}$j$),
  (3, 'texto', $j${"title":"Merge o rebase: cuándo cada uno","body":"No hay un ganador universal; son herramientas con filosofías distintas y muchos equipos usan ambas. MERGE conserva la HISTORIA REAL: muestra que hubo una rama, cuándo se separó y cuándo se reunió — la verdad de cómo se desarrolló el proyecto, a cambio de un historial con bifurcaciones. REBASE produce un historial LINEAL y limpio, fácil de leer en línea recta, a cambio de reescribir (y por eso, solo en local). Una postura común: rebase para ORDENAR TU PROPIA rama antes de integrarla (mientras es privada), y merge para INTEGRARLA a main (preservando el registro de la integración). Lo que jamás cambia es la regla de oro: reescribir historia —con rebase o con amend— solo sobre lo que aún es tuyo y local. El equipo define su política; tú respeta la de donde trabajes."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿En qué se diferencia rebase de merge?","options":["Son idénticos","merge UNE las dos líneas con un commit de fusión (historial con bifurcación); rebase REAPLICA tus commits encima de main (historial recto, como si hubieras partido de ahí)","rebase borra commits","merge solo funciona en local"],"correctIndex":1,"feedback":{"correct":"Correcto. Merge une y conserva la forma real; rebase reaplica y la vuelve lineal.","incorrect":"merge crea un commit de fusión uniendo las historias; rebase reaplica tus commits sobre la punta de main, dejando el historial recto."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Por qué NUNCA se debe rebasear una rama pública que otros ya tienen?","options":["Porque rebase es más lento","Porque rebase crea commits NUEVOS (reescribe la historia): si otros ya tienen los commits originales, sus historias y la tuya dejan de coincidir y se arma un caos — misma regla de oro que --amend","Porque rebase borra la rama main","Porque los conflictos no se pueden resolver en rebase"],"correctIndex":1,"feedback":{"correct":"Correcto. Rebase reescribe (hashes nuevos): seguro en local, desastre sobre lo compartido. No se reescribe historia pública.","incorrect":"Rebase reescribe la historia (commits nuevos). Sobre algo que otros ya tienen, eso divide los historiales. Solo en local."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Una postura común sobre cuándo usar cada uno:","options":["Siempre rebase, nunca merge","Rebase para ORDENAR tu propia rama mientras es privada (local), y merge para INTEGRARLA a main preservando el registro — respetando siempre la regla de no reescribir lo público","Siempre merge, rebase está prohibido","Da igual, son intercambiables sin consecuencias"],"correctIndex":1,"feedback":{"correct":"Correcto. Rebase limpia lo local; merge integra y deja registro. Y jamás reescribir lo público.","incorrect":"Muchos equipos: rebase para limpiar la rama privada, merge para integrar. Lo innegociable es no rebasear lo ya compartido."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Rebase (introducción)","points":["Rebase REAPLICA tus commits encima de la punta de main: historial RECTO, sin commit de fusión.","Rebase crea commits nuevos = REESCRIBE la historia (como --amend).","REGLA DE ORO: nunca rebasear una rama PÚBLICA que otros tienen — solo trabajo local.","Conflictos durante rebase: editar + git add + git rebase --continue (o --abort para cancelar).","Merge conserva la historia real; rebase la vuelve lineal. Postura común: rebase para limpiar lo local, merge para integrar."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l07-rebase';

-- ═════════════════════════════════════════════════════════════════════
-- L08 · Guardar trabajo a medias con stash
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La interrupción urgente","body":"Escena típica: estás a media funcionalidad, con cambios sin terminar en tu directorio de trabajo, cuando llega un fuego urgente —un error en producción que hay que arreglar YA en otra rama. No quieres commitear tu trabajo a medias (sería un commit incompleto y feo en el historial), pero tampoco puedes cambiar de rama con cambios sin guardar dando vueltas. La solución es git stash: guarda TEMPORALMENTE tus cambios sin preparar y sin confirmar en una especie de cajón aparte, y deja tu directorio de trabajo LIMPIO, como si acabaras de hacer commit. Ahora sí puedes cambiar de rama, apagar el fuego, y volver a recuperar tu trabajo tal como lo dejaste. Es el 'pausa y guarda esto un momento' de Git."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Guardar, atender el fuego, recuperar","code":"# Tengo cambios a medias y entra una urgencia:\ngit stash              # guarda los cambios y limpia el directorio\n\n# Ahora puedo cambiar de rama y apagar el fuego\ngit switch hotfix/pago-duplicado\n# ...arreglar, commitear...\n\n# Vuelvo a mi trabajo y recupero lo guardado\ngit switch feature/reportes\ngit stash pop          # devuelve los cambios y vacia el cajon","caption":"stash aparta el trabajo a medias; stash pop lo devuelve. En medio, el directorio quedó limpio para moverte con libertad.","result":{"columns":["FLUJO"],"rows":[["git stash → cambios guardados, directorio limpio"],["(switch + hotfix + commit)"],["git stash pop → cambios de vuelta, sigues donde ibas"]],"note":"git stash pop devuelve los cambios y elimina el stash del cajón. Existe git stash apply (devuelve pero CONSERVA la copia en el cajón), git stash list (ver qué hay guardado) y git stash drop (descartar uno)."}}$j$),
  (3, 'texto', $j${"title":"Cuándo stash, cuándo un commit — y no acumules","body":"El stash es para lo TEMPORAL y de corto plazo: la interrupción de cinco minutos, la prueba rápida que quieres apartar. Para trabajo que vas a retomar más tarde o que quieres compartir, casi siempre es mejor un COMMIT (aunque sea en una rama de trabajo): el commit tiene mensaje, queda en el historial, viaja con la rama y no se pierde. El stash, en cambio, vive fuera del historial, es local, y es fácil de olvidar. De ahí el riesgo clásico: ACUMULAR stashes. Si guardas diez cosas 'para después', el cajón se vuelve un misterio de cambios sin nombre que no recuerdas para qué eran (git stash list los muestra, pero sin contexto). La regla sana: usa el stash para pausas cortas y vacíalo pronto (pop). Si algo merece quedarse, merece un commit."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Para qué sirve git stash?","options":["Para borrar cambios definitivamente","Para GUARDAR temporalmente los cambios sin confirmar y dejar el directorio limpio, y así poder cambiar de rama sin hacer un commit a medias — luego se recuperan","Para crear una rama","Para subir cambios al remoto"],"correctIndex":1,"feedback":{"correct":"Correcto. stash aparta el trabajo a medias en un cajón y limpia el directorio; stash pop lo devuelve.","incorrect":"git stash guarda temporalmente los cambios y limpia el directorio, para moverte sin commitear a medias. No borra nada."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué diferencia hay entre git stash pop y git stash apply?","options":["Son idénticos","pop devuelve los cambios y ELIMINA el stash del cajón; apply los devuelve pero CONSERVA la copia guardada","apply borra la rama","pop sube al remoto"],"correctIndex":1,"feedback":{"correct":"Correcto. pop = devolver y vaciar; apply = devolver y conservar. Sutil pero útil saberlo.","incorrect":"pop recupera y elimina el stash; apply recupera pero deja la copia en el cajón por si la necesitas de nuevo."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Tienes trabajo que vas a retomar dentro de varios días. ¿stash o commit?","options":["stash siempre","COMMIT (aunque sea en una rama de trabajo): tiene mensaje, queda en el historial y no se pierde ni se olvida — el stash es para pausas cortas, y acumular stashes es un riesgo","Ninguno, dejarlo suelto","stash y luego borrarlo"],"correctIndex":1,"feedback":{"correct":"Correcto. Lo que se retoma o comparte merece un commit; el stash es para lo temporal y se vacía pronto.","incorrect":"Para trabajo de días, un commit es mejor: con mensaje y en el historial. El stash es para interrupciones cortas, y no conviene acumularlo."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — git stash","points":["git stash guarda temporalmente los cambios sin confirmar y deja el directorio LIMPIO para cambiar de rama.","git stash pop devuelve los cambios y vacía el cajón; git stash apply los devuelve pero conserva la copia.","git stash list muestra lo guardado; git stash drop descarta un stash.","El stash es para lo TEMPORAL (interrupciones cortas); lo que se retoma o comparte merece un COMMIT.","Riesgo: acumular stashes sin nombre que nadie recuerda. Úsalo poco y vacíalo pronto."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l08-stash';

-- ═════════════════════════════════════════════════════════════════════
-- L09 · Práctica: resolver un conflicto (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Fusionaste la rama feature/aumentar-limite en main y Git avisó de un conflicto en config.py: las dos ramas cambiaron la MISMA línea. Git dejó el archivo con los marcadores del conflicto (abajo). Tu rama (HEAD, main) tenía el límite en 10; la otra rama lo subió a 20. El área de operaciones confirmó que el nuevo límite correcto es 20. Resuelve el conflicto: escribe cómo debe quedar el archivo config.py, con el valor correcto y SIN ningún marcador.","instructions":["Decide qué versión queda: operaciones confirmó que LIMITE_CITAS debe ser 20.","Escribe el contenido final del archivo config.py con esa línea: LIMITE_CITAS = 20.","BORRA los tres marcadores del conflicto por completo: no debe quedar ningún <<<<<<<, ningún ======= ni ningún >>>>>>> en tu respuesta."],"initialCode":"<<<<<<< HEAD\nLIMITE_CITAS = 10\n=======\nLIMITE_CITAS = 20\n>>>>>>> feature/aumentar-limite","validators":["limite_citas\\s*=\\s*20","^(?![\\s\\S]*<<<<<<<)[\\s\\S]*$","^(?![\\s\\S]*=======)[\\s\\S]*$","^(?![\\s\\S]*>>>>>>>)[\\s\\S]*$"],"mockOutput":{"columns":["config.py resuelto"],"rows":[["LIMITE_CITAS = 20"]],"note":"Conflicto resuelto: elegiste el valor que operaciones pidió (20) y borraste todos los marcadores. El archivo quedó limpio, listo para git add y git commit — que cerrarán la fusión."},"hints":["Quédate con la línea del valor correcto (LIMITE_CITAS = 20) y elimina todo lo demás.","Los marcadores <<<<<<< HEAD, ======= y >>>>>>> feature/aumentar-limite son andamios: se borran por completo al resolver.","El archivo final es una sola línea: LIMITE_CITAS = 20 — sin ningún símbolo de conflicto."],"successMessage":"¡Conflicto resuelto! Elegiste la versión correcta (la que pidió operaciones) y dejaste el archivo sin un solo marcador. Eso es todo lo que un conflicto pide: una decisión humana y la limpieza de los andamios. Ahora git add y git commit cerrarían la fusión.","failMessage":"Revisa dos cosas: que la línea quede como LIMITE_CITAS = 20 (el valor que confirmó operaciones), y que NO sobreviva ningún marcador — ni <<<<<<<, ni =======, ni >>>>>>>. El archivo resuelto no lleva andamios."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-l09-practica';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La tercera región","body":"Byte aprende a bifurcar el camino y a reunirlo. Once preguntas guardan esta región: la rama como puntero, el flujo por funcionalidad, la fusión en sus dos formas, el conflicto sin miedo, el rebase y su regla, y el stash. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es una rama en Git?","options":["Una copia del proyecto entero","Un PUNTERO ligero con nombre que apunta a un commit — crearla es instantáneo porque no duplica archivos","Una carpeta de respaldo","Un servidor remoto"],"correctIndex":1,"feedback":{"correct":"Correcto. Rama = puntero a un commit. La ligereza es lo que hace baratas y rápidas las ramas.","incorrect":"Una rama es un puntero con nombre a un commit, no una copia. Por eso crear ramas es instantáneo."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Estás en feature/x y haces commit. ¿Qué puntero se mueve?","options":["main","Solo feature/x (la rama actual) avanza al commit nuevo; main se queda donde estaba","Todas las ramas","HEAD deja de existir"],"correctIndex":1,"feedback":{"correct":"Correcto. Commitear mueve la rama a la que apunta HEAD; las demás no se enteran.","incorrect":"Solo avanza la rama actual. main permanece hasta que integres el trabajo."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Quieres crear la rama fix/total Y cambiarte a ella de una vez:","options":["git branch fix/total","git switch -c fix/total — crea y cambia en un solo paso","git merge fix/total","git checkout main"],"correctIndex":1,"feedback":{"correct":"Correcto. switch -c (create) crea el puntero y te lleva ahí. git branch solo crearía sin moverte.","incorrect":"git switch -c fix/total hace ambas cosas. branch solo crea la rama sin cambiarte."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Para fusionar feature/login en main:","options":["Desde feature/login, git merge main","git switch main y luego git merge feature/login — te paras en el destino y traes la rama de trabajo","git push feature/login","git branch -d main"],"correctIndex":1,"feedback":{"correct":"Correcto. Te ubicas en la que recibe (main) y jalas la de trabajo.","incorrect":"Primero switch a main (destino), luego merge feature/login. Se integra HACIA la rama actual."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"main no recibió commits desde que creaste tu rama. Al fusionar, Git hace…","options":["Un commit de fusión con dos padres","Un FAST-FORWARD: solo adelanta el puntero de main hasta tu rama, sin crear commit — historial recto","Un conflicto","Un rebase automático"],"correctIndex":1,"feedback":{"correct":"Correcto. main no se movió → fast-forward: se adelanta el puntero, sin commit extra.","incorrect":"Si main no avanzó, integrar es solo mover su puntero: fast-forward. El commit de fusión aparece cuando ambas ramas avanzaron."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un commit de fusión (merge de tres vías)?","options":["Un commit sin padre","Un commit con DOS padres que une dos historias divergentes desde un ancestro común — aparece cuando main y la rama avanzaron por separado","Un commit vacío","Un tag especial"],"correctIndex":1,"feedback":{"correct":"Correcto. Dos padres = la costura de dos líneas reunidas. Surge del merge de tres vías.","incorrect":"El commit de fusión tiene dos padres y une las dos historias. Es lo que produce el merge de tres vías."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"La precisión clave del módulo: un conflicto de fusión es…","options":["Un error que rompe el repositorio","Git avisando que dos ramas cambiaron lo MISMO de forma distinta y necesita una DECISIÓN HUMANA — no es un fallo, es una pausa para decidir","Un bug de Git","Pérdida de datos"],"correctIndex":1,"feedback":{"correct":"Correcto. El conflicto es una decisión pendiente, no una avería. Git resolvió solo todo lo demás.","incorrect":"Un conflicto no es un error: es Git pidiendo que decidas dónde hay una contradicción real."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo está RESUELTO un conflicto en un archivo?","options":["Cuando Git lo cierra solo","Cuando dejaste el archivo como debe quedar y BORRASTE todos los marcadores (<<<<<<<, =======, >>>>>>>); luego git add lo marca resuelto y git commit cierra la fusión","Cuando eliges siempre la versión de arriba","Cuando reinicias el repositorio"],"correctIndex":1,"feedback":{"correct":"Correcto. Archivo correcto + cero marcadores + git add + git commit. (Y git merge --abort cancela todo si te arrepientes.)","incorrect":"Resuelto = archivo correcto sin ningún marcador, luego git add y git commit. Un marcador olvidado = conflicto sin resolver."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la mejor estrategia para PREVENIR conflictos?","options":["No usar ramas nunca","Ramas pequeñas y de corta vida, integradas seguido, y actualizarse con frecuencia — menos divergencia entre tu rama y main significa menos choques","Trabajar todos en main","Prohibir los merges"],"correctIndex":1,"feedback":{"correct":"Correcto. Poca divergencia = pocos conflictos: ramas cortas y fusiones frecuentes.","incorrect":"La prevención es reducir la divergencia: ramas cortas, integración frecuente, actualizarse a menudo."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"Regla de oro compartida por rebase y --amend:","options":["Usarlos siempre que se pueda","NO reescribir historia PÚBLICA: rebase y amend crean commits nuevos (reescriben), y hacerlo sobre commits que otros ya tienen divide los historiales — solo en trabajo local","Solo funcionan en la rama main","Se pueden usar en cualquier rama sin consecuencias"],"correctIndex":1,"feedback":{"correct":"Correcto. Reescribir (rebase/amend) solo sobre lo tuyo y local; jamás sobre lo que ya se compartió.","incorrect":"La regla de oro: no reescribir historia pública. rebase y amend crean commits nuevos; sobre lo compartido, eso rompe los historiales."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de cierre: estás a media funcionalidad (cambios sin confirmar) y entra un error urgente que debes arreglar YA en otra rama, sin ensuciar tu historial con un commit incompleto. ¿Qué haces?","options":["Commitear el trabajo a medias con mensaje 'wip'","git stash para guardar los cambios y limpiar el directorio → switch a la rama del hotfix, arreglar y commitear → volver y git stash pop para recuperar el trabajo tal como lo dejaste","Borrar los cambios y rehacerlos después","Crear una copia manual de la carpeta"],"correctIndex":1,"feedback":{"correct":"Impecable. El stash aparta lo temporal sin commit feo; apagas el fuego y recuperas con pop. El uso de manual de la interrupción urgente.","incorrect":"git stash guarda el trabajo a medias y limpia el directorio para moverte; tras el hotfix, git stash pop lo devuelve. Sin commits incompletos en el historial."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm03-x01-examen';
