-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 052 — Git desde Cero · M4: Remotos y colaboración de equipo
-- ═══════════════════════════════════════════════════════════════════
-- Unidad 4 del temario (bloques 22-29 + Práctica 4). Cubre: repositorios
-- local y remoto (Diagrama 4.1), publicar con push, recibir con fetch y
-- pull, el flujo basado en incidencias, Pull/Merge Requests, la revisión
-- de código, las ramas protegidas y el papel de Git en la integración
-- continua. Práctica: flujo completo de equipo (DEV-204).
-- Precisiones vinculantes: git pull = fetch + merge (operación compuesta,
-- no primitiva); el remoto es un punto de encuentro, no un respaldo; nada
-- de --force en ramas compartidas (reescribir historia pública otra vez);
-- 'Pull Request' (GitHub) y 'Merge Request' (GitLab) son el MISMO proceso.
-- Curso language = bash → práctica por regex + mockOutput.
-- Curso is_published = false: nada visible hasta el flip final (056).
-- Idempotente. Ejecutar DESPUÉS de 048.
-- ═══════════════════════════════════════════════════════════════════

delete from public.lessons
where module_id = (
  select m.id from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'git-desde-cero' and m.slug = 'm04-remotos'
);

insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m04-l01-remotos',       'Repositorios local y remoto',         'leccion',  20, 1),
       ('m04-l02-push',          'Publicar cambios con push',           'leccion',  20, 2),
       ('m04-l03-fetch-pull',    'Recibir cambios: fetch y pull',       'leccion',  20, 3),
       ('m04-l04-incidencias',   'El flujo basado en incidencias',      'leccion',  20, 4),
       ('m04-l05-pull-request',  'Pull Requests y Merge Requests',      'leccion',  20, 5),
       ('m04-l06-revision',      'La revisión de código',               'leccion',  20, 6),
       ('m04-l07-ramas-protegidas','Ramas protegidas e integración continua','leccion',20, 7),
       ('m04-l08-practica',      'Práctica: el flujo completo de equipo','practica', 20, 8),
       ('m04-x01-examen',        'Examen: Remotos y colaboración',      'examen',   40, 9)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'git-desde-cero' and m.slug = 'm04-remotos';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · Repositorios local y remoto (+ Diagrama 4.1)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El repositorio compartido","body":"Hasta aquí todo vivió en TU máquina: commits, ramas, historial, todo local. Para trabajar con OTRAS personas hace falta un lugar común donde encontrarse — un REPOSITORIO REMOTO: una copia del repositorio alojada en un servidor (GitHub, GitLab u otro) al que todo el equipo tiene acceso. Cada quien sigue teniendo su repositorio local completo (Git es distribuido, ¿recuerdas?); el remoto es el punto de encuentro donde publican y del que descargan. Precisión que conviene fijar desde ya: el remoto es un PUNTO DE ENCUENTRO, no un respaldo. Es fácil pensar 'subo a GitHub para tener copia de seguridad', pero su propósito real es COMPARTIR: sincronizar el trabajo del equipo. (Que de paso haya una copia en otro lado es un bono, no la función.)"}$j$),
  (2, 'texto', $j${"title":"origin y los dos caminos para empezar","body":"Al remoto se le pone un apodo para no escribir su dirección completa cada vez, y por convención universal ese apodo es ORIGIN — el remoto principal de tu proyecto. git remote -v muestra los remotos configurados y sus direcciones (URLs). Hay dos formas de tener un proyecto con remoto. Si el proyecto ya EXISTE en el servidor (te unes a un equipo, contribuyes a algo público), lo DESCARGAS completo con git clone URL: eso trae todo el historial y deja origin configurado automáticamente, apuntando a donde clonaste. Si el proyecto NACIÓ en tu máquina (git init local) y quieres subirlo por primera vez, le AGREGAS el remoto a mano con git remote add origin URL. La diferencia: clone descarga algo que ya está; remote add conecta algo tuyo con un remoto vacío que creaste."}$j$),
  (3, 'diagrama', $j${"title":"Diagrama 4.1 · Local y remoto","component":"NetworkDiagram","props":{"label":"Tres repositorios locales, un punto de encuentro","ancho":520,"alto":320,"nodos":[{"id":"origin","x":190,"y":30,"w":140,"h":58,"titulo":"origin","subtitulo":"remoto (GitHub)","tag":"punto de encuentro","descripcion":"El repositorio remoto: una copia alojada en un servidor a la que todo el equipo accede. NO es un respaldo — es el lugar donde el equipo sincroniza su trabajo."},{"id":"karen","x":30,"y":200,"w":130,"h":58,"titulo":"tu repositorio","subtitulo":"local (Karen)","descripcion":"Tu copia completa: historial, ramas, todo. Trabajas aquí sin conexión; te sincronizas con origin cuando quieres compartir o recibir."},{"id":"luis","x":195,"y":200,"w":130,"h":58,"titulo":"repositorio","subtitulo":"local (Luis)","descripcion":"La copia completa de otra persona del equipo. Cada quien tiene la suya: Git es distribuido."},{"id":"ana","x":360,"y":200,"w":130,"h":58,"titulo":"repositorio","subtitulo":"local (Ana)","descripcion":"Otra copia local. Los tres publican en origin y descargan de origin: así ven el trabajo de los demás."}],"enlaces":[{"de":"karen","a":"origin","tipo":"doble","etiqueta":"push / pull","descripcion":"Subes tu trabajo (push) y bajas el de los demás (pull). La comunicación con el remoto es en ambos sentidos."},{"de":"luis","a":"origin","tipo":"doble","etiqueta":"push / pull","descripcion":"Luis hace lo mismo: publica y recibe a través de origin."},{"de":"ana","a":"origin","tipo":"doble","etiqueta":"push / pull","descripcion":"Ana también. Nadie habla directo con la máquina de otro: todos pasan por origin."}],"hint":"Toca origin y cada repositorio local: el trabajo fluye a través del punto de encuentro."},"caption":"Cada persona tiene su repositorio local completo; origin es el remoto común. Se publica con push y se recibe con pull — nadie habla directo con la máquina de otro."}$j$),
  (4, 'texto', $j${"title":"init vs clone: dos orígenes de un repo","body":"Vale la pena separar bien los dos comandos con los que un repositorio empieza a existir en tu máquina, porque se confunden. git init (módulo 1) crea un repositorio NUEVO y VACÍO a partir de una carpeta tuya: empiezas de cero, sin remoto, sin historial. git clone URL crea tu repositorio local COPIANDO uno que ya existe en un remoto: llega con todo su historial, todas sus ramas, y con origin ya configurado apuntando a la URL de donde lo clonaste. Regla simple: ¿el proyecto ya existe en algún servidor y te quieres unir? → clone. ¿Estás arrancando algo desde tu carpeta? → init (y luego, si quieres compartirlo, remote add origin). Clonar es lo que harás casi siempre al incorporarte a un proyecto de trabajo."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un repositorio REMOTO y cuál es su propósito principal?","options":["Un respaldo automático de tu código","Una copia del repositorio alojada en un servidor (GitHub/GitLab) a la que todo el equipo accede: su propósito es COMPARTIR y sincronizar el trabajo — no ser un respaldo","La única copia real del proyecto","Una carpeta oculta en tu máquina"],"correctIndex":1,"feedback":{"correct":"Correcto. El remoto es el punto de encuentro del equipo. Que de paso sea una copia es un bono, no su función.","incorrect":"El remoto es el lugar común para compartir y sincronizar. Cada quien conserva su repositorio local completo (Git es distribuido)."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es 'origin'?","options":["El primer commit del proyecto","El APODO por convención del repositorio remoto principal — evita escribir su URL completa cada vez","La rama principal","El autor original del código"],"correctIndex":1,"feedback":{"correct":"Correcto. origin es el nombre corto del remoto principal. clone lo configura solo; con init lo agregas con remote add.","incorrect":"origin es el alias del remoto principal (no una rama ni un commit). Se usa para no escribir la URL entera."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Te unes a un equipo cuyo proyecto YA existe en GitHub. ¿Qué comando usas para empezar?","options":["git init","git clone URL — descarga el proyecto completo con todo su historial y deja origin ya configurado","git remote add origin URL","git pull"],"correctIndex":1,"feedback":{"correct":"Correcto. clone copia un repo existente con su historial y configura origin automáticamente. init es para arrancar de cero.","incorrect":"Para un proyecto que ya existe en el servidor: git clone. init crearía uno nuevo y vacío en tu carpeta."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Local y remoto","points":["El remoto es una copia en un servidor a la que accede todo el equipo: punto de encuentro, NO respaldo.","Cada persona conserva su repositorio local completo (Git distribuido); se sincronizan a través del remoto.","origin = apodo por convención del remoto principal; git remote -v los lista con sus URLs.","git clone URL descarga un proyecto existente (con historial y origin ya configurado).","git init + git remote add origin URL conecta un repo que nació en tu máquina. clone: unirse; init: arrancar."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l01-remotos';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Publicar cambios con push
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Subir el trabajo al punto de encuentro","body":"Ahora sí, 'subir' — la palabra que reservamos desde el módulo 1. git push envía TUS commits locales al remoto, para que el resto del equipo los vea. Ojo con lo que esto significa: push publica commits YA hechos; no sube cambios sin confirmar ni el trabajo del directorio. El flujo completo es local hasta el último paso: editas, git add (preparas), git commit (guardas en tu historial local) y, cuando quieras compartir, git push (publicas en origin). Todo lo de los módulos anteriores ocurría sin red; push es el momento en que tu trabajo sale de tu máquina. La primera vez que publicas una rama, se usa git push -u origin nombre-rama: la -u (de 'upstream') ATA tu rama local con su gemela en el remoto, para que a partir de entonces baste con git push a secas."}$j$),
  (2, 'ejemplo_codigo', $j${"title":"Publicar una rama por primera vez","code":"# Trabajo local ya commiteado en mi rama\ngit switch feature/CLI-142-recuperar-contrasena\n\n# Primera publicacion: -u ata la rama local con la remota\ngit push -u origin feature/CLI-142-recuperar-contrasena\n\n# A partir de ahora, para publicar mas commits de esta rama:\ngit push","caption":"push -u (upstream) la primera vez: crea la rama en el remoto y la enlaza. Después, git push a secas basta.","result":{"columns":["SALIDA"],"rows":[["Enumerating objects: 5, done."],["To github.com:clinica/sistema.git"],[" * [new branch]  feature/CLI-142-recuperar-contrasena -> feature/CLI-142-recuperar-contrasena"],["branch set up to track 'origin/feature/CLI-142-recuperar-contrasena'"]],"note":"'[new branch]' porque es la primera vez: la rama nace en el remoto. 'set up to track' confirma el enlace que hizo -u: tu rama local ahora sabe con qué rama remota sincronizarse."}}$j$),
  (3, 'texto', $j${"title":"Cuando el push es RECHAZADO (y por qué no se fuerza)","body":"A veces push falla con un mensaje de RECHAZO ('rejected'). No es un error tuyo: significa que el remoto tiene commits que TÚ no tienes localmente — alguien más publicó en esa rama mientras trabajabas, y Git no te deja pisar su trabajo. La solución correcta es TRAER primero esos cambios (git pull, próxima lección), integrarlos con los tuyos, y luego volver a hacer push. Lo que JAMÁS se hace ante un rechazo en una rama compartida es forzar el push (git push --force): forzar SOBREESCRIBE en el remoto los commits de los demás con los tuyos, borrando su trabajo del historial compartido. Es la regla de oro de nuevo —no reescribir historia pública— ahora en su forma más destructiva. Un push rechazado se resuelve integrando, no imponiendo. (Y cuando limpias una rama tuya, borrar la remota se hace con git push origin --delete nombre-rama, no forzando.)"}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace exactamente git push?","options":["Sube todos tus archivos, incluidos los cambios sin confirmar","Envía tus COMMITS locales (ya confirmados) al remoto, para que el equipo los vea — no sube cambios sin commitear","Crea un commit nuevo","Descarga los cambios del equipo"],"correctIndex":1,"feedback":{"correct":"Correcto. push publica commits ya hechos. El flujo: add → commit (local) → push (al remoto).","incorrect":"push envía commits ya confirmados al remoto. Los cambios sin commitear no viajan: primero add y commit."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La primera vez que publicas una rama nueva usas git push -u origin nombre. ¿Qué hace la -u?","options":["Fuerza la subida","Ata (upstream) tu rama local con su gemela remota, para que después baste git push a secas","Sube todas las ramas","Borra la rama remota"],"correctIndex":1,"feedback":{"correct":"Correcto. -u enlaza local y remota; a partir de ahí git push solo ya sabe adónde ir.","incorrect":"-u (upstream) establece el enlace entre tu rama local y la remota. No fuerza nada: solo la primera publicación lo necesita."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu git push es RECHAZADO porque el remoto tiene commits que tú no tienes. ¿Qué haces?","options":["git push --force para imponer tu versión","TRAER primero esos cambios (git pull), integrarlos con los tuyos, y volver a hacer push — jamás forzar en una rama compartida, porque --force sobreescribe el trabajo de los demás","Borrar la rama y empezar","Ignorarlo y reintentar igual"],"correctIndex":1,"feedback":{"correct":"Correcto. Rechazo = te falta el trabajo de alguien: se integra (pull) y se re-publica. Forzar borra el historial ajeno.","incorrect":"Un push rechazado se resuelve integrando (pull) primero, no forzando. --force sobreescribe los commits de los demás: la regla de oro rota."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Publicar con push","points":["git push envía tus COMMITS locales al remoto: es el 'subir' que reservamos. No sube cambios sin confirmar.","El flujo completo: add → commit (local) → push (compartir en origin).","Primera vez en una rama: git push -u origin nombre (la -u ata local con remota); después basta git push.","Push RECHAZADO = el remoto tiene commits que te faltan: haz pull, integra y vuelve a pushear.","JAMÁS git push --force en ramas compartidas: sobreescribe el trabajo ajeno (regla de oro). Borrar rama remota: git push origin --delete."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l02-push';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Recibir cambios: fetch y pull
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Traer el trabajo de los demás","body":"Si push publica lo tuyo, ¿cómo recibes lo de los demás? Con dos comandos que conviene NO confundir. git fetch origin DESCARGA los commits nuevos del remoto a tu repositorio local… pero NO los mezcla con tu trabajo: los deja aparte, para que puedas MIRAR qué llegó antes de integrarlo. Es el 'a ver qué hay de nuevo, sin tocar todavía lo mío'. git pull, en cambio, hace las dos cosas de un tirón: descarga los cambios Y los integra en tu rama actual inmediatamente. Es más rápido, y es lo que usarás a diario cuando confíes en integrar directo. Pero fetch existe para las veces que quieres inspeccionar antes de mezclar — sobre todo en ramas compartidas y activas."}$j$),
  (2, 'texto', $j${"title":"La precisión: pull = fetch + merge","body":"Aquí está el concepto que ordena todo. git pull NO es un comando primitivo: es una OPERACIÓN COMPUESTA que hace dos cosas seguidas — primero un git fetch (descarga los commits del remoto) y luego un git merge (integra esos commits en tu rama actual). pull = fetch + merge. Entender esto explica dos cosas importantes. Primero, por qué un pull a veces 'trae sorpresas': porque incluye un merge, y un merge puede provocar un CONFLICTO (¡el mismo del módulo 3!) si el remoto y tú tocaron lo mismo — un conflicto durante un pull se resuelve exactamente igual: editar, quitar marcadores, git add, git commit. Segundo, por qué fetch es el paso 'seguro': hace solo la mitad (descargar), dejándote decidir cuándo y cómo integrar. pull es la comodidad; fetch + revisar + merge es el control."}$j$),
  (3, 'ejemplo_codigo', $j${"title":"Dos formas de recibir","code":"# Camino seguro: descargar y MIRAR antes de integrar\ngit fetch origin\ngit log origin/main --oneline   # ¿que trajo el remoto?\ngit merge origin/main           # ahora si, integrar\n\n# Camino rapido: descargar e integrar de un tiron\ngit pull                        # = fetch + merge, juntos","caption":"pull = fetch + merge en un solo comando. fetch solo descarga; tú decides cuándo hacer el merge.","result":{"columns":["git pull"],"rows":[["remote: Enumerating objects: 8, done."],["Updating a1b2c3d..e5f6g7h"],["Fast-forward"],[" citas.sql | 12 +++++++"],[" 1 file changed, 7 insertions(+)"]],"note":"Aquí el pull hizo un fast-forward limpio (nadie tocó lo mismo). Si tú y el remoto hubieran cambiado la misma parte, el merge interno del pull habría dado un CONFLICTO, que se resuelve como cualquier otro."}}$j$),
  (4, 'texto', $j${"title":"Mantenerse al día: el hábito que evita dolores","body":"El uso más importante de pull no es al final, sino al PRINCIPIO y a MENUDO. Antes de empezar a trabajar en el día, un git pull de main te pone al día con lo que el equipo integró mientras no estabas. Y durante una tarea larga, traer de vez en cuando los cambios de main a tu rama mantiene la divergencia bajo control — justo la prevención de conflictos del módulo 3, ahora con el comando concreto. La rama que ignora el remoto durante una semana y hasta el final hace pull se lleva la avalancha de conflictos de golpe; la que se sincroniza seguido los encuentra pequeños y manejables. La disciplina del equipo: pull frecuente, push cuando tengas algo completo. Recibir seguido y publicar terminado."}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre git fetch y git pull?","options":["Son idénticos","git fetch solo DESCARGA los commits del remoto (los deja aparte para mirarlos); git pull descarga E INTEGRA en tu rama de un tirón","fetch integra y pull solo descarga","fetch sube y pull baja"],"correctIndex":1,"feedback":{"correct":"Correcto. fetch = descargar sin mezclar (revisar antes); pull = descargar + integrar de golpe.","incorrect":"fetch solo trae los commits (para inspeccionar); pull además los integra en tu rama. Uno mira, el otro mezcla."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión clave: git pull es en realidad…","options":["Un comando primitivo e indivisible","Una operación COMPUESTA: git fetch (descargar) + git merge (integrar) — por eso un pull puede provocar un CONFLICTO, que se resuelve como cualquier merge","Lo mismo que push pero al revés","Solo para la primera descarga"],"correctIndex":1,"feedback":{"correct":"Correcto. pull = fetch + merge. Eso explica las 'sorpresas' del pull: el merge interno puede chocar.","incorrect":"pull no es primitivo: es fetch + merge. El merge de adentro puede dar conflicto — el mismo del módulo 3."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es el hábito profesional para mantenerse al día con el equipo?","options":["Hacer pull solo cuando algo falla","git pull FRECUENTE (al empezar el día y durante tareas largas) para que la divergencia no crezca — y push cuando tengas algo completo. Recibir seguido, publicar terminado","No hacer pull nunca","Solo push, nunca pull"],"correctIndex":1,"feedback":{"correct":"Correcto. pull frecuente encuentra los conflictos pequeños; ignorar el remoto una semana los junta todos al final.","incorrect":"El hábito: pull a menudo (empezar el día, tareas largas) y push cuando termines algo. Sincronizarse seguido evita avalanchas."}}$j$),
  (8, 'resumen', $j${"title":"Resumen — Recibir: fetch y pull","points":["git fetch DESCARGA los commits del remoto sin integrarlos (para mirar antes de mezclar).","git pull DESCARGA E INTEGRA de un tirón en tu rama actual.","PRECISIÓN: git pull = git fetch + git merge (operación compuesta) — por eso un pull puede dar CONFLICTO.","Un conflicto durante pull se resuelve igual que cualquier merge: editar, quitar marcadores, add, commit.","Hábito: pull frecuente (empezar el día, tareas largas), push cuando algo esté completo."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l03-fetch-pull';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · El flujo basado en incidencias
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Del comando al proceso de trabajo","body":"Ya tienes todos los comandos; ahora viene lo que de verdad distingue trabajar en equipo: el PROCESO. En una empresa, el trabajo no empieza con 'se me ocurrió cambiar algo', sino con una INCIDENCIA (también llamada ticket o issue): una unidad de trabajo registrada, con un número, una descripción y un criterio de aceptación (qué debe cumplirse para darla por terminada). 'DEV-204: validar el correo en el registro'. La incidencia es el porqué de todo lo que sigue: se asigna a una persona, esa persona crea una rama para resolverla, hace commits que la referencian, publica, abre una solicitud para integrarla, se revisa, se corrige y se cierra. El código no vive solo: vive atado a la razón por la que se escribió."}$j$),
  (2, 'texto', $j${"title":"La cadena de trazabilidad","body":"El valor de este flujo es la TRAZABILIDAD: poder seguir el hilo completo de cualquier cambio hacia atrás. La cadena se teje con nombres consistentes. La incidencia DEV-204 origina la rama feature/DEV-204-validar-correo; los commits mencionan el número ('Agrega validación de formato de correo (DEV-204)'); la solicitud de integración enlaza a la incidencia; y al integrarse, la incidencia se cierra —muchas plataformas la cierran automáticamente al detectar la referencia—. Resultado: dentro de un año, ante cualquier línea de código, puedes responder 'esto se agregó por la incidencia DEV-204, que pedía validar el correo, revisada por Ana, integrada el 3 de marzo'. Es la versión de equipo de las cinco preguntas del módulo 1 (quién, cuándo, por qué, qué), ahora enlazando código, tarea y decisión."}$j$),
  (3, 'texto', $j${"title":"El recorrido completo de una incidencia","body":"Puesto en orden, el ciclo de vida de una incidencia en un equipo es este: (1) se CREA la incidencia con su descripción y criterio de aceptación; (2) se ASIGNA a una persona; (3) esa persona parte de main actualizada y CREA la rama de la tarea; (4) DESARROLLA la solución con commits atómicos que referencian la incidencia; (5) PUBLICA la rama (push); (6) abre una SOLICITUD DE INTEGRACIÓN (Pull/Merge Request, próxima lección); (7) se ejecutan las PRUEBAS automáticas; (8) el equipo REVISA el código; (9) se aplican las CORRECCIONES observadas; (10) se INTEGRA el cambio; (11) se CIERRA la incidencia. Reconocerás los módulos anteriores viviendo dentro de este proceso: las ramas del módulo 3, el push de esta unidad, los commits atómicos del módulo 2 — todo ensamblado en la coreografía real de un equipo. Los pasos 6 a 10 son el corazón de la colaboración, y las próximas lecciones los abren uno por uno."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"En un flujo de trabajo de empresa, ¿con qué empieza normalmente una tarea?","options":["Con un commit directo a main","Con una INCIDENCIA (ticket/issue): una unidad de trabajo registrada con número, descripción y criterio de aceptación — el porqué de todo lo que sigue","Con un push","Con la creación del repositorio"],"correctIndex":1,"feedback":{"correct":"Correcto. La incidencia es el origen: define qué se hace y cuándo se considera terminado. Todo lo demás cuelga de ella.","incorrect":"El trabajo arranca con una incidencia registrada (número + descripción + criterio de aceptación), no con un cambio suelto."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es la TRAZABILIDAD en el flujo basado en incidencias?","options":["Un permiso especial","Poder seguir el hilo completo de un cambio: la incidencia origina la rama, los commits la referencian, el PR la enlaza — así cualquiera puede saber por qué existe cada línea de código","Un tipo de rama","La velocidad del equipo"],"correctIndex":1,"feedback":{"correct":"Correcto. La cadena incidencia↔rama↔commit↔PR responde 'por qué existe esto' para cualquier cambio, siempre.","incorrect":"Trazabilidad = el hilo que conecta cada cambio con la tarea que lo pidió. Se teje con referencias consistentes al número de incidencia."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es el orden correcto (simplificado) del ciclo de una incidencia?","options":["Integrar → crear rama → revisar → asignar","Crear la incidencia → asignar → crear rama → desarrollar (commits) → publicar → abrir PR → pruebas → revisar → corregir → integrar → cerrar","Push → commit → rama → incidencia","Revisar → integrar → crear incidencia"],"correctIndex":1,"feedback":{"correct":"Correcto. Del ticket al cierre, en orden: la coreografía real donde viven las ramas, los commits y el push que ya conoces.","incorrect":"El ciclo va de la incidencia a su cierre: crear → asignar → rama → desarrollar → publicar → PR → pruebas → revisar → corregir → integrar → cerrar."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Flujo basado en incidencias","points":["El trabajo de equipo empieza con una INCIDENCIA: unidad registrada con número, descripción y criterio de aceptación.","La cadena de TRAZABILIDAD: incidencia → rama (feature/DEV-204-…) → commits que la referencian → PR que la enlaza → cierre.","Permite responder 'por qué existe esta línea' para cualquier cambio, meses después.","El ciclo: crear → asignar → rama → desarrollar → publicar → PR → pruebas → revisar → corregir → integrar → cerrar.","Los módulos anteriores (ramas, commits atómicos, push) viven ensamblados dentro de este proceso."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l04-incidencias';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Pull Requests y Merge Requests
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Pedir que integren tu trabajo","body":"Terminaste tu rama y la publicaste. En un equipo NO la fusionas tú directo a main — propones que se integre, para que otros la revisen primero. Esa propuesta es una PULL REQUEST (el nombre en GitHub) o MERGE REQUEST (el nombre en GitLab): son EXACTAMENTE lo mismo, dos nombres para el mismo proceso, así que no te confunda encontrar uno u otro. Una PR dice, en esencia: 'preparé estos cambios en mi rama; propongo integrarlos a main; por favor revísenlos'. Declara una rama ORIGEN (la tuya, con el trabajo nuevo) y una rama DESTINO (normalmente main, donde quieres que aterrice). No es un comando de Git: es una función de la plataforma (GitHub/GitLab) construida ENCIMA de Git, donde el trabajo se revisa y se discute antes de entrar."}$j$),
  (2, 'texto', $j${"title":"Anatomía de una buena Pull Request","body":"Una PR no es solo 'aquí está mi rama'; es una pieza de comunicación. Lo que una buena PR incluye: un TÍTULO claro que resume el cambio; una DESCRIPCIÓN que explica el QUÉ y el POR QUÉ (el mismo espíritu de un buen mensaje de commit, pero para el conjunto); el ENLACE a la incidencia que resuelve (trazabilidad); la EVIDENCIA de que funciona (capturas, resultado de las pruebas); y los REVISORES asignados. La plataforma muestra automáticamente todos los cambios (el diff completo de la rama) para que los revisores vean exactamente qué se propone. Una PR bien escrita hace la revisión rápida y respetuosa del tiempo ajeno; una PR de una línea sin contexto ('cambios') obliga al revisor a adivinar. La PR es donde tu trabajo se presenta al equipo: se prepara con el mismo cuidado que el código."}$j$),
  (3, 'texto', $j${"title":"El ciclo de vida de una PR","body":"Una vez abierta, la PR vive un proceso: los REVISORES miran los cambios y dejan COMENTARIOS; pueden APROBARLA (se ve bien) o SOLICITAR CAMBIOS (hay que ajustar algo antes). Si piden cambios, tú haces nuevos commits en la MISMA rama y los publicas — la PR se actualiza automáticamente con ellos, sin abrir una nueva; la conversación continúa donde estaba. Cuando la PR reúne las aprobaciones necesarias y las pruebas pasan, se INTEGRA (merge) a la rama destino, normalmente con un botón en la plataforma. Y si la PR estaba enlazada a la incidencia, muchas plataformas la CIERRAN automáticamente al integrarse. La PR es, entonces, el lugar donde convergen todos los hilos de este módulo: la rama publicada, la revisión del equipo, la integración final y el cierre de la tarea."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué relación hay entre una 'Pull Request' y una 'Merge Request'?","options":["Son procesos opuestos","Son EXACTAMENTE el mismo proceso con distinto nombre: 'Pull Request' en GitHub, 'Merge Request' en GitLab — proponer integrar una rama para que la revisen","La PR es para código y la MR para documentación","La MR es una versión avanzada de la PR"],"correctIndex":1,"feedback":{"correct":"Correcto. Mismo concepto, dos nombres según la plataforma. No te confunda encontrar uno u otro.","incorrect":"Pull Request (GitHub) y Merge Request (GitLab) son lo mismo: la propuesta de integrar tu rama, revisada antes de entrar."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué NO es una Pull Request?","options":["Una propuesta de integrar una rama a otra","Un COMANDO de Git — es una función de la PLATAFORMA (GitHub/GitLab) construida encima de Git, donde el cambio se revisa y discute antes de integrarse","Un lugar para revisar cambios","Algo con rama origen y destino"],"correctIndex":1,"feedback":{"correct":"Correcto. La PR no es Git puro: es una capa de colaboración de la plataforma sobre el merge de Git.","incorrect":"La PR es una función de la plataforma (no un comando de Git): añade revisión y discusión alrededor del merge."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Un revisor SOLICITA CAMBIOS en tu PR. ¿Cómo respondes?","options":["Abres una PR nueva desde cero","Haces nuevos commits en la MISMA rama y los publicas: la PR se actualiza automáticamente y la conversación continúa donde estaba","Cierras la PR y renuncias","Fuerzas el merge ignorando el comentario"],"correctIndex":1,"feedback":{"correct":"Correcto. Nuevos commits en la misma rama actualizan la PR: no se abre otra, se sigue el mismo hilo.","incorrect":"Respondes con commits nuevos en la misma rama; la PR los recoge sola. Abrir otra rompería la conversación y la trazabilidad."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — Pull/Merge Requests","points":["PR (GitHub) y MR (GitLab) son el MISMO proceso: proponer integrar tu rama para que la revisen antes de entrar.","No es un comando de Git: es una función de la plataforma construida sobre el merge, con revisión y discusión.","Declara rama ORIGEN (la tuya) y DESTINO (normalmente main); muestra el diff completo.","Buena PR: título claro, descripción del qué/por qué, enlace a la incidencia, evidencia, revisores.","Ciclo: comentarios → aprobar o pedir cambios (respondes con commits en la misma rama) → integrar → cerrar la incidencia."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l05-pull-request';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · La revisión de código
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Cuatro ojos ven más que dos","body":"La REVISIÓN DE CÓDIGO (code review) es el corazón del trabajo en equipo: antes de que un cambio entre a main, otra persona lo lee. No es desconfianza — es cómo los equipos mantienen la calidad, comparten conocimiento y atrapan errores temprano. ¿Qué se revisa? CORRECCIÓN: ¿hace lo que debe, resuelve la incidencia? CLARIDAD: ¿se entiende, o es un enredo que nadie podrá mantener? MANTENIBILIDAD: ¿encaja con el resto del proyecto? SEGURIDAD: ¿introduce riesgos, expone secretos? PRUEBAS: ¿está probado lo que cambió? ALCANCE: ¿hace solo lo que la incidencia pide, sin colar cambios no relacionados? Un buen revisor no busca lucirse encontrando fallos: busca que el cambio entre al proyecto en las mejores condiciones posibles."}$j$),
  (2, 'texto', $j${"title":"Revisar el cambio, no a la persona","body":"La regla cultural que hace que la revisión funcione: se revisa el CÓDIGO, no a quien lo escribió. 'Esta función podría fallar si el correo viene vacío' habla del código; 'siempre escribes mal esto' ataca a la persona — y envenena al equipo. Los comentarios se escriben con claridad y respeto, distinguiendo su peso: una SUGERENCIA ('quizá sea más legible así', opcional), una DUDA ('¿por qué elegiste este enfoque?', busca entender), o un BLOQUEO ('esto expone la contraseña, hay que cambiarlo antes de integrar', no puede entrar así). Confundir los tres frustra a todos: bloquear por una preferencia personal, o dejar pasar como sugerencia algo que de verdad rompe. Del lado de quien recibe la revisión: los comentarios se responden (con un commit que corrige, o explicando por qué se hizo así), no se ignoran. La revisión es una conversación entre profesionales sobre cómo mejorar un cambio."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué NO se revisa normalmente en un code review?","options":["Corrección: ¿hace lo que debe?","La ORTOGRAFÍA del nombre del autor — se revisa el cambio: corrección, claridad, mantenibilidad, seguridad, pruebas y alcance","Seguridad: ¿introduce riesgos?","Alcance: ¿hace solo lo que la incidencia pide?"],"correctIndex":1,"feedback":{"correct":"Correcto. La revisión mira el CAMBIO (corrección, claridad, mantenibilidad, seguridad, pruebas, alcance), no a la persona.","incorrect":"Se revisan las cualidades del cambio: corrección, claridad, mantenibilidad, seguridad, pruebas, alcance. No a quien lo escribió."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la regla cultural central de una buena revisión de código?","options":["Encontrar tantos fallos como sea posible","Revisar el CÓDIGO, no a la persona: 'esta función podría fallar si...' (sobre el código) en vez de 'siempre lo haces mal' (ataque personal)","Aprobar siempre para no incomodar","Bloquear todo por si acaso"],"correctIndex":1,"feedback":{"correct":"Correcto. El comentario habla del cambio, con claridad y respeto. Atacar a la persona envenena al equipo.","incorrect":"Se revisa el código, no a quien lo escribió. Los comentarios describen el cambio, sin volverse personales."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Un comentario de revisión dice: 'esto expone la contraseña en texto plano, hay que cambiarlo antes de integrar'. ¿Qué tipo de comentario es?","options":["Una sugerencia opcional","Un BLOQUEO: señala algo que no puede entrar así — se distingue de una sugerencia (preferencia opcional) o una duda (busca entender)","Una duda","Un ataque personal"],"correctIndex":1,"feedback":{"correct":"Correcto. Es un bloqueo legítimo: un riesgo real de seguridad. Distinguir bloqueo/sugerencia/duda hace la revisión justa.","incorrect":"Exponer una contraseña es un bloqueo (no puede integrarse así), no una simple sugerencia. Confundir los pesos frustra al equipo."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Revisión de código","points":["El code review: otra persona lee el cambio antes de que entre a main — calidad, conocimiento compartido, errores atrapados temprano.","Se revisa: corrección, claridad, mantenibilidad, seguridad, pruebas y alcance.","Regla cultural: revisar el CÓDIGO, no a la persona — comentarios claros y respetuosos.","Distinguir el peso: SUGERENCIA (opcional), DUDA (entender), BLOQUEO (no puede entrar así).","Quien recibe la revisión RESPONDE los comentarios (con un commit o una explicación), no los ignora."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l06-revision';

-- ═════════════════════════════════════════════════════════════════════
-- L07 · Ramas protegidas e integración continua
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Poner reglas a main","body":"Si cualquiera puede hacer push directo a main, todo el proceso de revisión es opcional — y lo opcional se salta bajo presión. Por eso las plataformas permiten declarar RAMAS PROTEGIDAS: main (y otras ramas críticas) se marcan como protegidas, y sobre ellas se imponen reglas que Git y la plataforma hacen cumplir automáticamente. Las más comunes: PROHIBIR el push directo (a main solo se entra por Pull Request, nunca a mano); EXIGIR revisiones (la PR necesita una o más aprobaciones antes de poder integrarse); exigir que las PRUEBAS AUTOMÁTICAS pasen (status checks en verde); definir CODE OWNERS (ciertos archivos requieren la aprobación de personas concretas); y RESTRINGIR el force push (nadie reescribe la historia de main — la regla de oro, ahora blindada por la plataforma). Las ramas protegidas convierten las buenas prácticas de 'costumbre que se puede saltar' en 'regla que el sistema no te deja saltar'."}$j$),
  (2, 'texto', $j${"title":"Git y la integración continua","body":"Cuando publicas una rama o abres una PR, en muchos proyectos se dispara algo automático: un PIPELINE de INTEGRACIÓN CONTINUA (CI). Es una serie de comprobaciones que corren solas sobre tu cambio — típicamente: BUILD (¿el proyecto compila?), LINT (¿el código sigue el estilo acordado?), PRUEBAS (¿pasan las pruebas automáticas?) y a veces ANÁLISIS de seguridad. El resultado es un veredicto: verde (todo pasó) o rojo (algo falló). La regla que conecta esto con Git: NO se integra un cambio con las comprobaciones en rojo — por eso las ramas protegidas exigen los status checks en verde. Si el pipeline falla, corriges, haces nuevos commits en la misma rama, los publicas, y el pipeline vuelve a correr sobre la versión actualizada. Nota de alcance: esto NO es un curso de CI/CD —montar pipelines es otro tema—; aquí solo importa el papel de Git en el proceso: tu push y tu PR son los que disparan y alimentan esas comprobaciones."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué logra marcar main como RAMA PROTEGIDA?","options":["Cifrarla","Imponer reglas que el sistema hace cumplir: prohibir push directo (solo por PR), exigir revisiones y pruebas en verde, restringir el force push — convierte las buenas prácticas en reglas inquebrantables","Hacerla más rápida","Ocultarla del equipo"],"correctIndex":1,"feedback":{"correct":"Correcto. La protección vuelve obligatorio lo que era costumbre: a main solo se entra revisado, probado y por PR.","incorrect":"Una rama protegida impone reglas automáticas (no push directo, revisiones y checks obligatorios, sin force). Lo opcional se vuelve obligatorio."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un pipeline de integración continua (CI) y cuándo se dispara?","options":["Un servidor de respaldo","Comprobaciones automáticas (build, lint, pruebas, análisis) que corren solas sobre tu cambio — típicamente al hacer push o abrir una PR — y dan un veredicto verde/rojo","Un tipo de rama","Un comando de Git"],"correctIndex":1,"feedback":{"correct":"Correcto. El CI verifica el cambio automáticamente; tu push/PR lo dispara. Verde = pasó, rojo = algo falló.","incorrect":"El CI son comprobaciones automáticas (build/lint/pruebas) disparadas por tu push o PR. No es una rama ni un comando de Git."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"El pipeline de tu PR está en ROJO (una prueba falló). ¿Qué corresponde hacer?","options":["Integrar igual, se arregla después","NO integrar: corriges, haces nuevos commits en la misma rama y los publicas — el pipeline vuelve a correr sobre la versión corregida. Las ramas protegidas exigen los checks en verde","Forzar el merge","Cerrar la PR"],"correctIndex":1,"feedback":{"correct":"Correcto. Rojo = no se integra. Se corrige con commits nuevos en la rama y el CI se vuelve a ejecutar. Integrar en rojo mete el fallo a main.","incorrect":"Con el pipeline en rojo no se integra: se corrige (commits en la misma rama) y el CI reevalúa. Por eso los checks en verde son requisito."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — Ramas protegidas y CI","points":["RAMAS PROTEGIDAS: reglas que el sistema hace cumplir sobre main — no push directo (solo PR), revisiones y checks obligatorios, sin force push.","Convierten las buenas prácticas de 'costumbre saltable' en 'regla inquebrantable'.","CI: comprobaciones automáticas (build, lint, pruebas, seguridad) disparadas por tu push o PR; veredicto verde/rojo.","NO se integra con el pipeline en rojo: se corrige con commits nuevos en la misma rama y el CI reevalúa.","No es un curso de CI/CD: aquí importa el papel de Git — push y PR disparan y alimentan las comprobaciones."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l07-ramas-protegidas';

-- ═════════════════════════════════════════════════════════════════════
-- L08 · Práctica: el flujo completo de equipo (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Te asignaron la incidencia DEV-204: validar el correo en el registro. Ejecuta el flujo de equipo de principio a fin, con los comandos de Git que te tocan (la Pull Request y la revisión ocurren en la plataforma, fuera de la terminal). El repositorio ya está clonado y estás en main. Escribe la secuencia de comandos.","instructions":["Ponte al día antes de empezar: git pull (trae lo que el equipo integró).","Crea y cámbiate a la rama de la incidencia: git switch -c feature/DEV-204-validar-correo.","Haz DOS commits atómicos (git add + git commit -m con mensaje) para tu solución; que al menos un mensaje referencie la incidencia (DEV-204).","Publica la rama por primera vez: git push -u origin feature/DEV-204-validar-correo."],"initialCode":"# Incidencia DEV-204: validar el correo en el registro\n# Estas en main, repo ya clonado. Escribe el flujo de comandos.\n\n","validators":["git\\s+pull","git\\s+switch\\s+-c\\s+feature/dev-204-validar-correo","git\\s+commit\\s+-m\\s+[\"'].+[\"'].*git\\s+commit\\s+-m\\s+[\"'].+[\"']","git\\s+commit\\s+-m\\s+[\"'][^\"']*dev-204","git\\s+push\\s+-u\\s+origin\\s+feature/dev-204-validar-correo"],"mockOutput":{"columns":["FLUJO DE EQUIPO — DEV-204"],"rows":[["git pull → al día con main"],["git switch -c feature/DEV-204-validar-correo → rama creada"],["2 commits atómicos (uno referencia DEV-204)"],["git push -u origin feature/... → rama publicada"],["(en la plataforma: abrir PR → revisión → integrar → cerrar DEV-204)"]],"note":"El flujo de equipo completo del lado de Git: te pusiste al día, aislaste el trabajo en su rama, hiciste commits atómicos trazables a la incidencia y publicaste la rama lista para su Pull Request. La revisión y la integración siguen en la plataforma."},"hints":["El orden importa: git pull (al día) → git switch -c feature/DEV-204-validar-correo → commits → git push -u origin ...","Los DOS commits van con git add + git commit -m \"mensaje\"; incluye 'DEV-204' en al menos un mensaje para la trazabilidad (p. ej. \"Agrega validacion de correo (DEV-204)\").","La primera publicación de la rama lleva -u: git push -u origin feature/DEV-204-validar-correo."],"successMessage":"¡Flujo de equipo ejecutado! Te pusiste al día (pull), aislaste el trabajo en su rama, hiciste commits atómicos trazables a la incidencia y publicaste la rama lista para su Pull Request. Del lado de Git, esto es exactamente lo que harás en cualquier equipo: el resto (revisión, integración, cierre) vive en la plataforma.","failMessage":"Revisa la secuencia y su orden: git pull → git switch -c feature/DEV-204-validar-correo → DOS commits (con 'DEV-204' en un mensaje) → git push -u origin feature/DEV-204-validar-correo."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-l08-practica';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · Examen de región
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"La cuarta región","body":"Byte sale de su máquina y se une al equipo. Once preguntas guardan esta región: el remoto y sus comandos, el flujo por incidencias, las Pull Requests, la revisión y las reglas que protegen main. Las que falles volverán al final hasta que las domines. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un repositorio remoto y para qué sirve principalmente?","options":["Un respaldo automático","Una copia en un servidor a la que accede todo el equipo: sirve para COMPARTIR y sincronizar el trabajo, no como respaldo","La única copia del proyecto","Una rama especial"],"correctIndex":1,"feedback":{"correct":"Correcto. Punto de encuentro del equipo; la copia extra es un bono, no su función.","incorrect":"El remoto existe para compartir y sincronizar. Cada quien conserva su repositorio local completo."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Te unes a un proyecto que YA existe en GitHub. ¿Con qué comando empiezas?","options":["git init","git clone URL — descarga el proyecto con su historial y configura origin automáticamente","git remote add","git push"],"correctIndex":1,"feedback":{"correct":"Correcto. clone copia un repo existente y deja origin listo. init es para arrancar de cero.","incorrect":"Un proyecto existente se trae con git clone. init crearía uno nuevo y vacío."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué hace git push?","options":["Descarga el trabajo del equipo","Envía tus COMMITS locales (ya confirmados) al remoto para compartirlos — no sube cambios sin commitear","Crea una rama","Resuelve conflictos"],"correctIndex":1,"feedback":{"correct":"Correcto. push publica commits ya hechos. El flujo: add → commit → push.","incorrect":"push sube commits confirmados al remoto. Descargar lo de otros es pull/fetch."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu push es RECHAZADO porque el remoto tiene commits que te faltan. ¿Qué haces?","options":["git push --force para imponer tu versión","Haces pull para traer e integrar esos commits, y vuelves a pushear — nunca forzar en una rama compartida (--force sobreescribe el trabajo ajeno)","Borras la rama remota","Reintentas el push igual"],"correctIndex":1,"feedback":{"correct":"Correcto. Rechazo = te falta trabajo ajeno: integrar (pull) y re-publicar. Forzar borra el historial de los demás.","incorrect":"Se resuelve con pull + re-push, no forzando. --force en una rama compartida destruye los commits ajenos."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión clave: git pull es en realidad…","options":["Un comando primitivo","git fetch + git merge: una operación compuesta — por eso un pull puede provocar un CONFLICTO, que se resuelve como cualquier merge","Lo mismo que push","Solo la primera descarga"],"correctIndex":1,"feedback":{"correct":"Correcto. pull = fetch + merge. El merge interno explica las 'sorpresas' (conflictos) del pull.","incorrect":"pull no es primitivo: descarga (fetch) e integra (merge). El merge puede chocar, igual que en el módulo 3."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"¿En qué se diferencia git fetch de git pull?","options":["Son idénticos","fetch solo DESCARGA (para mirar antes de integrar); pull descarga E INTEGRA de un tirón","fetch sube, pull baja","fetch borra ramas"],"correctIndex":1,"feedback":{"correct":"Correcto. fetch mira sin mezclar; pull mezcla. Uno da control, el otro comodidad.","incorrect":"fetch solo trae los commits (para revisar); pull además los integra. fetch es el paso seguro."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"En el flujo de empresa, ¿qué es la TRAZABILIDAD?","options":["La velocidad del equipo","El hilo que conecta cada cambio con su origen: la incidencia origina la rama, los commits la referencian, el PR la enlaza — para saber por qué existe cada línea","Un tipo de rama protegida","El número de commits por día"],"correctIndex":1,"feedback":{"correct":"Correcto. La cadena incidencia↔rama↔commit↔PR responde 'por qué existe esto' para cualquier cambio.","incorrect":"Trazabilidad = seguir un cambio hasta la tarea que lo pidió, vía referencias consistentes al número de incidencia."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"'Pull Request' y 'Merge Request' son…","options":["Procesos distintos","El MISMO proceso con distinto nombre (GitHub / GitLab): proponer integrar una rama para que la revisen antes de entrar","Comandos de Git","Tipos de conflicto"],"correctIndex":1,"feedback":{"correct":"Correcto. Mismo concepto, dos nombres. Es una función de la plataforma, no un comando de Git.","incorrect":"PR (GitHub) y MR (GitLab) son lo mismo: la propuesta revisada de integrar una rama."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Un revisor pide cambios en tu PR. ¿Cómo respondes?","options":["Abres una PR nueva","Haces nuevos commits en la MISMA rama y los publicas: la PR se actualiza sola y la conversación continúa","Cierras la PR","Fuerzas el merge"],"correctIndex":1,"feedback":{"correct":"Correcto. Commits nuevos en la misma rama actualizan la PR: se sigue el mismo hilo.","incorrect":"Respondes con commits en la misma rama; la PR los recoge. Abrir otra rompería la trazabilidad."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué impone una RAMA PROTEGIDA sobre main, y qué papel juega el CI?","options":["Nada relevante","Reglas obligatorias: no push directo (solo por PR), revisiones y pruebas en verde para integrar, sin force push. El CI corre las comprobaciones automáticas (build/lint/pruebas) que deben pasar","Solo cifra la rama","Acelera los merges"],"correctIndex":1,"feedback":{"correct":"Correcto. La protección vuelve obligatorias las buenas prácticas; el CI aporta el veredicto verde/rojo que exigen los checks.","incorrect":"Rama protegida = reglas que el sistema hace cumplir (PR obligatoria, revisiones, checks). El CI son las comprobaciones automáticas que deben estar en verde."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta de cierre: la regla de oro '(no reescribir historia pública)' ha aparecido con amend, con rebase y ahora con push. ¿Cómo se manifiesta en este módulo de remotos, y por qué es aún más grave aquí?","options":["No aplica a los remotos","git push --force sobre una rama compartida sobreescribe en el remoto los commits de TODO el equipo — es la forma más destructiva de reescribir historia pública, porque el daño ya no es local sino que borra el trabajo ajeno del punto de encuentro común","Solo importa en local","Se resuelve con git pull --force"],"correctIndex":1,"feedback":{"correct":"Impecable. amend/rebase reescriben tu historia local; --force la impone al remoto compartido, borrando el trabajo de otros. Misma regla, consecuencia máxima. Un push rechazado se integra, no se fuerza.","incorrect":"En remotos, reescribir historia pública toma la forma de git push --force: sobreescribe los commits del equipo en el punto de encuentro común. Por eso un rechazo se resuelve con pull + re-push, jamás forzando."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm04-x01-examen';
