-- ═══════════════════════════════════════════════════════════════════
-- CodeQuest · Migración 055 — Git desde Cero · M7: Proyecto integrador
-- ═══════════════════════════════════════════════════════════════════
-- CIERRE DEL CURSO. El flujo completo de una funcionalidad de empresa,
-- de punta a punta, con un caso NUEVO que obliga a usar todo el arsenal:
-- clonar/leer -> rama de incidencia -> commits atómicos -> push -> PR y
-- revisión -> resolver un conflicto -> integrar -> tag de versión ->
-- reversión segura. Estructura de capstone: lección de encargo, cuatro
-- PRÁCTICAS encadenadas, lección de cierre con retrospectiva, y la
-- EVALUACIÓN FINAL (~30 preguntas, XP 80 — decisión 1 de Karen).
-- Reglas de contenido: quizzes autocontenidos o con términos técnicos.
-- Curso language = bash -> prácticas por regex + mockOutput (incluye la
-- resolución de conflicto con lookahead negativo).
-- Curso is_published = false: nada visible hasta el flip final (056).
-- Idempotente. Ejecutar DESPUÉS de 048.
-- ═══════════════════════════════════════════════════════════════════

delete from public.lessons
where module_id = (
  select m.id from public.modules m
  join public.courses c on c.id = m.course_id
  where c.slug = 'git-desde-cero' and m.slug = 'm07-proyecto'
);

insert into public.lessons (module_id, slug, title, kind, xp, sort_order)
select m.id, v.slug, v.title, v.kind, v.xp, v.ord
from public.modules m
join public.courses c on c.id = m.course_id,
     (values
       ('m07-l01-encargo',            'El encargo: una tarea de equipo',     'leccion',  20, 1),
       ('m07-l02-practica-preparar',  'Práctica: preparar el trabajo',       'practica', 20, 2),
       ('m07-l03-practica-colaborar', 'Práctica: publicar y colaborar',      'practica', 20, 3),
       ('m07-l04-practica-conflicto', 'Práctica: resolver el conflicto',     'practica', 20, 4),
       ('m07-l05-practica-publicar',  'Práctica: versión y reversión',       'practica', 20, 5),
       ('m07-l06-cierre',             'El viaje completo y el cierre',       'leccion',  20, 6),
       ('m07-x01-final',              'Evaluación final del curso',          'examen',   80, 7)
     ) as v(slug, title, kind, xp, ord)
where c.slug = 'git-desde-cero' and m.slug = 'm07-proyecto';

-- ═════════════════════════════════════════════════════════════════════
-- L01 · El encargo: una tarea de equipo
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Tu primera semana en el equipo","body":"Llegó el momento de juntarlo todo. Te incorporas al equipo que mantiene el sistema de la clínica —el mismo repositorio que has acompañado todo el curso—, y te asignan tu primera tarea real. La cuenta la líder técnica así: 'El registro de pacientes acepta correos con formato inválido y eso está ensuciando la base. Tu incidencia es CLI-305: validar el correo en el alta de pacientes. Trabajamos con GitHub Flow: main siempre estable, una rama por tarea, todo entra por Pull Request revisada, y main está protegida (no se puede pushear directo). Lee el CONTRIBUTING antes de empezar: nombramos las ramas feature/NUMERO-descripcion y referenciamos la incidencia en los commits. Ah, y esta semana hay movimiento en el archivo de configuración: es probable que te toque un conflicto al integrar.' Ese párrafo es tu encargo: el resto del módulo lo ejecutas, práctica a práctica."}$j$),
  (2, 'texto', $j${"title":"El plan: el flujo completo, paso a paso","body":"Antes de teclear, el plan — que es, en realidad, todo el curso puesto en orden. ETAPA 1 (preparar): ponerte al día con main, leer las convenciones, y crear tu rama de la incidencia siguiendo el estándar del equipo (módulos 3 y 6). ETAPA 2 (colaborar): hacer commits atómicos y trazables, publicar la rama, y abrir la Pull Request para que te revisen (módulos 2 y 4). ETAPA 3 (el conflicto): al poner tu rama al día con main, otra persona tocó el mismo archivo de config — resolver el conflicto sin miedo (módulo 3). ETAPA 4 (publicar y recuperarse): integrar, etiquetar la versión, y —giro final— cuando un cambio posterior rompa producción, revertirlo de forma segura (módulos 5 y 6). Cuatro etapas, cuatro prácticas. No hay comandos nuevos que aprender: solo el oficio completo, ensamblado como lo vivirás en un trabajo real."}$j$),
  (3, 'texto', $j${"title":"Las reglas del equipo, en limpio","body":"Tu lista de convenciones a respetar (las del CONTRIBUTING de este equipo, que en tu vida profesional variarán de un lugar a otro): (R1) main es la rama principal y está PROTEGIDA — nada de push directo; todo entra por Pull Request. (R2) las ramas se nombran feature/NUMERO-descripcion (ej. feature/CLI-305-validar-correo). (R3) los commits son ATÓMICOS y referencian la incidencia en el mensaje (CLI-305). (R4) antes de integrar, la rama se pone al día con main (y se resuelven los conflictos que aparezcan). (R5) las versiones se marcan con tags anotados en versionado semántico. (R6) para deshacer algo que ya llegó a main/producción se usa revert, nunca reset. Seis reglas que ya dominas por separado; el proyecto es aplicarlas juntas, en secuencia, sin que se te caiga ninguna. Empecemos."}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"El equipo trabaja con GitHub Flow y main está protegida. ¿Qué significa eso para tu tarea?","options":["Puedes pushear tu cambio directo a main si es pequeño","NO se puede pushear directo a main: tu trabajo va en una rama por tarea y entra por Pull Request revisada — la protección hace obligatorio el proceso","main es de solo lectura para siempre","Debes crear tu propio main"],"correctIndex":1,"feedback":{"correct":"Correcto. GitHub Flow + main protegida = rama por tarea y PR obligatoria. Nada entra a main sin revisión.","incorrect":"main protegida prohíbe el push directo: tu cambio va por una rama y una Pull Request revisada. Ese es el proceso del equipo."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"La líder anticipa 'es probable que te toque un conflicto al integrar'. ¿Qué revela eso sobre el flujo?","options":["Que el repositorio está roto","Que otras personas están tocando archivos que tú también tocarás: al poner tu rama al día con main aparecerá un conflicto — algo NORMAL en el trabajo en equipo, que resolverás con una decisión humana","Que debes evitar integrar","Que Git tiene un bug esta semana"],"correctIndex":1,"feedback":{"correct":"Correcto. Un conflicto anticipado no es alarma: es la señal de un equipo activo. Se resuelve, no se teme.","incorrect":"El conflicto esperado significa que el equipo está tocando lo mismo que tú: es normal y se resuelve con una decisión, no un error."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"Según las reglas del equipo (R6), para deshacer algo que ya llegó a main se usa…","options":["reset --hard, para borrarlo","revert: crea un commit que lo deshace SIN reescribir la historia compartida — reset reescribiría una historia que el equipo ya tiene","git restore","git commit --amend"],"correctIndex":1,"feedback":{"correct":"Correcto. Público → revert (no reescribe). La regla de oro, ahora como norma explícita del equipo.","incorrect":"Sobre lo que ya está en main (compartido), revert. reset reescribiría la historia del equipo: prohibido."}}$j$),
  (7, 'resumen', $j${"title":"Resumen — El encargo","points":["Te incorporas al equipo del sistema de la clínica; tu tarea: la incidencia CLI-305 (validar el correo en el alta).","El equipo usa GitHub Flow con main PROTEGIDA: rama por tarea, todo por Pull Request revisada.","El plan es el curso completo en 4 etapas: preparar → colaborar → resolver conflicto → publicar y recuperarse.","Reglas (R1-R6): main protegida, ramas feature/NUMERO-desc, commits atómicos trazables, poner al día antes de integrar, tags semver, revert para lo público.","No hay comandos nuevos: el proyecto es aplicar todo junto, en secuencia, sin que se caiga nada."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm07-l01-encargo';

-- ═════════════════════════════════════════════════════════════════════
-- L02 · Práctica: preparar el trabajo (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Etapa 1 del proyecto. Estás en main, en el repositorio ya clonado de la clínica. Prepara el terreno para la incidencia CLI-305 (validar el correo en el alta de pacientes): ponte al día con el equipo y crea tu rama de trabajo siguiendo la convención (feature/NUMERO-descripcion). Escribe la secuencia de comandos.","instructions":["Ponte al día con lo que el equipo integró: git pull.","Crea y cámbiate a la rama de la incidencia, con el nombre según la convención del equipo: git switch -c feature/CLI-305-validar-correo.","Confirma en qué rama quedaste: git branch (opcional, pero buena costumbre para verificar)."],"initialCode":"# Etapa 1 · Preparar el trabajo — incidencia CLI-305\n# Estas en main, repo ya clonado. Ponte al dia y crea tu rama.\n\n","validators":["git\\s+pull","git\\s+switch\\s+-c\\s+feature/cli-305-validar-correo"],"mockOutput":{"columns":["ETAPA 1 — PREPARAR"],"rows":[["git pull → al día con main"],["git switch -c feature/CLI-305-validar-correo → rama creada y activa"],["* feature/CLI-305-validar-correo"],["  main"]],"note":"Terreno preparado: te pusiste al día con el equipo (menos divergencia, menos conflictos) y aislaste tu trabajo en una rama que nombra la incidencia según la convención. Listo para la Etapa 2."},"hints":["Primero git pull: empezar al día evita divergencia y conflictos innecesarios.","La rama sigue la convención del equipo (R2): git switch -c feature/CLI-305-validar-correo — con el número de incidencia y una descripción corta.","switch -c crea y cambia en un paso; git branch te confirma dónde quedaste (el asterisco marca la rama actual)."],"successMessage":"¡Etapa 1 lista! Te pusiste al día con main y creaste tu rama siguiendo la convención del equipo. Este par de comandos es el arranque de CUALQUIER tarea en un equipo: sincronizarse y aislar el trabajo. Sigue la Etapa 2: hacer el cambio y publicarlo.","failMessage":"Revisa: git pull (ponerte al día) y luego git switch -c feature/CLI-305-validar-correo (la rama con la convención del equipo: feature/NUMERO-descripcion)."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm07-l02-practica-preparar';

-- ═════════════════════════════════════════════════════════════════════
-- L03 · Práctica: publicar y colaborar (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Etapa 2. Ya estás en tu rama feature/CLI-305-validar-correo y escribiste la validación del correo en dos pasos (la función y luego un ajuste tras probarla). Registra el trabajo con commits atómicos trazables, publícalo, y prepáralo para la revisión del equipo. Escribe la secuencia de comandos (la Pull Request se abre en la plataforma).","instructions":["Confirma la validación como primer commit atómico: git add validacion.py y git commit -m con un mensaje que referencie la incidencia (CLI-305).","Confirma el ajuste como SEGUNDO commit atómico: git add validacion.py y git commit -m con su propio mensaje (también puede referenciar CLI-305).","Publica la rama por primera vez para poder abrir la Pull Request: git push -u origin feature/CLI-305-validar-correo."],"initialCode":"# Etapa 2 · Publicar y colaborar — CLI-305\n# Estas en tu rama con el trabajo hecho. Commitea, referencia la\n# incidencia y publica la rama.\n\n","validators":["git\\s+commit\\s+-m\\s+[\"'].+[\"'].*git\\s+commit\\s+-m\\s+[\"'].+[\"']","git\\s+commit\\s+-m\\s+[\"'][^\"']*cli-305","git\\s+push\\s+-u\\s+origin\\s+feature/cli-305-validar-correo"],"mockOutput":{"columns":["ETAPA 2 — PUBLICAR Y COLABORAR"],"rows":[["commit 1: la validacion (referencia CLI-305)"],["commit 2: el ajuste (atomico, por separado)"],["git push -u origin feature/CLI-305-validar-correo → rama publicada"],["(en la plataforma: abrir Pull Request → esperar revisión)"]],"note":"Dos commits atómicos y trazables a la incidencia, y la rama publicada: lista para su Pull Request. La revisión del equipo ocurre en la plataforma; del lado de Git, tu trabajo ya está compartido y ordenado."},"hints":["Dos commits SEPARADOS (atómicos): git add + git commit -m para la validación, y otra vez para el ajuste. Al menos uno referencia 'CLI-305' en el mensaje.","La primera publicación de la rama lleva -u: git push -u origin feature/CLI-305-validar-correo.","La Pull Request se abre en GitHub/GitLab, no con un comando de Git — tu push deja la rama lista para ella."],"successMessage":"¡Etapa 2 lista! Dos commits atómicos trazables a CLI-305 y la rama publicada: lista para su Pull Request y la revisión del equipo. Del lado de Git, tu trabajo ya está compartido y ordenado. Ahora viene el conflicto anunciado.","failMessage":"Revisa: DOS commits atómicos (git add + git commit -m, por separado), con 'CLI-305' en al menos un mensaje, y la publicación git push -u origin feature/CLI-305-validar-correo."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm07-l03-practica-colaborar';

-- ═════════════════════════════════════════════════════════════════════
-- L04 · Práctica: resolver el conflicto (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Etapa 3, el conflicto anunciado. Para poner tu rama al día antes de integrar, hiciste git merge main y —tal como avisó la líder— apareció un conflicto en config.py: mientras trabajabas, otra persona cambió el mismo parámetro. Tu rama (HEAD) traía VALIDAR_CORREO = False (aún no lo activabas); la de main lo puso en True porque tu incidencia CLI-305 justamente pide activar la validación. Git dejó el archivo con los marcadores (abajo). Resuelve el conflicto: escribe cómo debe quedar config.py, con el valor correcto y SIN ningún marcador.","instructions":["Decide el valor correcto: tu incidencia CLI-305 ACTIVA la validación de correo, así que VALIDAR_CORREO debe quedar en True.","Escribe el contenido final de config.py con esa línea: VALIDAR_CORREO = True.","BORRA los tres marcadores del conflicto por completo: no debe quedar ningún <<<<<<<, ningún ======= ni ningún >>>>>>> en tu respuesta."],"initialCode":"<<<<<<< HEAD\nVALIDAR_CORREO = False\n=======\nVALIDAR_CORREO = True\n>>>>>>> main","validators":["validar_correo\\s*=\\s*true","^(?![\\s\\S]*<<<<<<<)[\\s\\S]*$","^(?![\\s\\S]*=======)[\\s\\S]*$","^(?![\\s\\S]*>>>>>>>)[\\s\\S]*$"],"mockOutput":{"columns":["config.py resuelto"],"rows":[["VALIDAR_CORREO = True"]],"note":"Conflicto resuelto con criterio: tu incidencia pide activar la validación, así que gana True. Los marcadores desaparecieron, el archivo quedó limpio. Ahora git add config.py y git commit cerrarían la fusión, y tu rama estaría al día con main, lista para integrarse."},"hints":["El criterio lo da tu tarea: CLI-305 ACTIVA la validación → VALIDAR_CORREO = True. (Dejarlo en False contradiría tu propia incidencia.)","El archivo final es una sola línea con el valor correcto: VALIDAR_CORREO = True.","Borra por completo los marcadores <<<<<<< HEAD, ======= y >>>>>>> main: el archivo resuelto no lleva ninguno."],"successMessage":"¡Conflicto resuelto con criterio! No elegiste al azar: tu incidencia pide activar la validación, así que True es lo correcto, y borraste todos los marcadores. Un conflicto no es un error, es una decisión humana — y la tomaste bien. Tu rama queda al día con main, lista para integrarse por la Pull Request.","failMessage":"Revisa dos cosas: el valor debe ser VALIDAR_CORREO = True (tu incidencia CLI-305 activa la validación), y NO debe sobrevivir ningún marcador — ni <<<<<<<, ni =======, ni >>>>>>>."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm07-l04-practica-conflicto';

-- ═════════════════════════════════════════════════════════════════════
-- L05 · Práctica: versión y reversión (kind = practica)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'ejercicio', $j${"scenario":"Etapa 4, el cierre. Tu Pull Request fue aprobada e integrada a main: CLI-305 quedó lista y marcaste la versión v1.4.0. Pero horas después, el equipo detecta que OTRO commit ya integrado en main (hash c0ffee1, de otra tarea) rompió el envío de recordatorios en producción. Hay que deshacerlo YA, sin reescribir la historia que todo el equipo tiene. Escribe los comandos: primero etiqueta tu versión, luego revierte con seguridad el commit culpable.","instructions":["Marca tu versión con un tag ANOTADO en versionado semántico: git tag -a v1.4.0 -m con un mensaje.","Publica el tag al remoto: git push origin v1.4.0.","Deshaz de forma SEGURA el commit que rompió producción (c0ffee1), sin reescribir la historia compartida: git revert c0ffee1.","(Tras revert, se integra por el flujo normal: aquí basta con el comando de reversión correcto)."],"initialCode":"# Etapa 4 · Version y reversion\n# Tu PR se integro (CLI-305). Marca la version v1.4.0 y luego\n# revierte con seguridad el commit c0ffee1 que rompio produccion.\n\n","validators":["git\\s+tag\\s+-a\\s+v1\\.4\\.0\\s+-m\\s+[\"'].+[\"']","git\\s+push\\s+origin\\s+v1\\.4\\.0","git\\s+revert\\s+c0ffee1"],"mockOutput":{"columns":["ETAPA 4 — VERSIÓN Y REVERSIÓN"],"rows":[["git tag -a v1.4.0 -m \"...\" → versión marcada"],["git push origin v1.4.0 → tag publicado"],["git revert c0ffee1 → commit malo deshecho con un commit NUEVO"],["(historia intacta; el equipo recibe un commit más)"]],"note":"Cierre impecable: marcaste tu versión con un tag anotado y deshiciste el commit roto con revert — un commit inverso que NO reescribe la historia compartida. Usar reset aquí habría roto los historiales de todo el equipo. Proyecto completo."},"hints":["El tag es ANOTADO y semántico: git tag -a v1.4.0 -m \"mensaje\", y se publica aparte con git push origin v1.4.0 (los tags no viajan con push normal).","Para deshacer algo YA en main (compartido) se usa revert, JAMÁS reset: git revert c0ffee1 crea un commit inverso sin reescribir la historia.","c0ffee1 es el hash del commit culpable: git revert seguido de ese hash."],"successMessage":"¡Proyecto completo! Marcaste tu versión con un tag anotado y apagaste el fuego de producción con revert —seguro, sin reescribir la historia que todo el equipo tiene—. Del brief al despliegue, con un conflicto resuelto y una reversión limpia en el camino: acabas de ejecutar el flujo completo de una tarea de equipo. Eso es Git en el mundo real.","failMessage":"Revisa las tres piezas: git tag -a v1.4.0 -m \"...\" (anotado y semántico) · git push origin v1.4.0 (publicar el tag) · git revert c0ffee1 (deshacer lo público SIN reescribir la historia — nada de reset)."}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm07-l05-practica-publicar';

-- ═════════════════════════════════════════════════════════════════════
-- L06 · El viaje completo y el cierre
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"El mapa de lo que hiciste","body":"Detente un momento y mira el viaje completo de CLI-305, porque cada paso fue un módulo del curso trabajando en conjunto. Leíste las convenciones y te pusiste al día (M6: incorporarse; M4: pull). Creaste tu rama siguiendo el estándar del equipo (M3: ramas; M6: convenciones). Hiciste commits atómicos y trazables a la incidencia (M2: commits limpios; M4: trazabilidad). Publicaste y abriste una Pull Request para que te revisaran (M4: push, PR, revisión). Al ponerte al día apareció un conflicto y lo resolviste con criterio, no al azar (M3: conflictos). Integraste, marcaste la versión con un tag semántico (M2: tags, semver) y, cuando un cambio posterior rompió producción, lo revertiste sin reescribir la historia del equipo (M5: revert; M6: la regla de oro). Del brief al despliegue: no siete temas sueltos, sino UN oficio."}$j$),
  (2, 'texto', $j${"title":"Lo que Git te dio (y lo que sigue)","body":"Empezaste el curso con carpetas llamadas proyecto_final_v2_ahora_si y las cinco preguntas sin respuesta: quién, cuándo, por qué, qué, cómo volver. Ahora respondes las cinco sobre cualquier línea de código —tuya o del equipo— y, más importante, trabajas con la red puesta: sabes que casi nada en Git es irreversible si entiendes dónde estás parado. Deshaces sin miedo (restore, revert, reset, reflog), colaboras sin pisar a nadie (ramas, PR, pull), y te recuperas de los errores en lugar de temerlos. Lo que queda fuera de este curso —rebase interactivo, submódulos, firmas, worktrees— son herramientas que aprenderás cuando un problema real las pida; tienes la base para entenderlas. Y la regla que resume todo el oficio, la que apareció una y otra vez: no reescribas la historia que ya compartiste. Con eso, y con lo que sabes, ya puedes contribuir a cualquier proyecto del mundo. Solo queda una puerta: la evaluación final."}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"En el proyecto, al ponerte al día con main apareció un conflicto y elegiste VALIDAR_CORREO = True (no al azar). ¿Por qué esa era la decisión correcta?","options":["Porque True siempre gana","Porque tu incidencia CLI-305 pedía ACTIVAR la validación de correo: el criterio de resolución lo da la TAREA, no una regla mecánica — un conflicto se resuelve con una decisión humana informada","Porque main siempre tiene razón","Porque era la versión de arriba"],"correctIndex":1,"feedback":{"correct":"Correcto. El conflicto se resuelve con criterio: tu tarea pedía activar la validación, así que True. La decisión es humana e informada.","incorrect":"El valor correcto lo dicta tu incidencia (activar la validación → True), no una regla automática. Resolver un conflicto es decidir con contexto."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"Un commit ya integrado en main rompió producción. En el proyecto lo deshiciste con revert (no reset). ¿Por qué era lo correcto?","options":["revert es más rápido","Porque el commit ya estaba en main (compartido): revert lo deshace con un commit nuevo SIN reescribir la historia que todo el equipo tiene; reset la habría reescrito, rompiendo sus historiales","reset no existe para main","Daba igual cuál usar"],"correctIndex":1,"feedback":{"correct":"Correcto. Público → revert (no reescribe). La regla de oro del curso, aplicada en el cierre del proyecto.","incorrect":"Sobre lo compartido, revert: deshace sin reescribir. reset habría alterado la historia del equipo — la regla de oro rota."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"Mirando el proyecto completo, ¿qué demuestra haber ensamblado todos los módulos en una sola tarea?","options":["Que Git tiene demasiados comandos","Que Git no son siete temas sueltos sino UN oficio: leer convenciones, ramificar, commitear limpio, colaborar por PR, resolver conflictos, versionar y recuperarse — todo encadenado como en un trabajo real","Que el proyecto era demasiado difícil","Que solo importa el último paso"],"correctIndex":1,"feedback":{"correct":"Correcto. El valor del capstone: ver que las piezas se sostienen entre sí. Del brief al despliegue, un flujo continuo.","incorrect":"El proyecto muestra que los módulos son un oficio único y encadenado, no temas aislados: así se trabaja de verdad."}}$j$),
  (6, 'resumen', $j${"title":"Resumen — El viaje completo","points":["El proyecto CLI-305 encadenó todos los módulos: leer/pull → rama → commits atómicos → push/PR → conflicto → integrar → tag → revert.","Cada etapa fue un módulo trabajando en conjunto: Git es UN oficio, no siete temas sueltos.","Empezaste sin poder responder quién/cuándo/por qué/qué/cómo-volver; ahora respondes las cinco y trabajas con red.","Deshaces sin miedo, colaboras sin pisar a nadie, te recuperas de los errores en lugar de temerlos.","La regla que resume todo: no reescribas la historia que ya compartiste. Solo queda la evaluación final."]}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm07-l06-cierre';

-- ═════════════════════════════════════════════════════════════════════
-- X01 · EVALUACIÓN FINAL DEL CURSO (~30 preguntas, XP 80 — decisión 1)
-- ═════════════════════════════════════════════════════════════════════
insert into public.content_blocks (lesson_id, sort_order, kind, payload)
select l.id, v.ord, v.kind, v.payload::jsonb
from public.lessons l
join public.modules m on m.id = l.module_id
join public.courses c on c.id = m.course_id,
(values
  (1, 'texto', $j${"title":"Evaluación final","body":"La última puerta del curso, y no hay otra región detrás: está el título. Treinta preguntas recorren TODO el camino —fundamentos, historial, ramas, remotos, recuperación y trabajo de empresa—. Es todo lo que aprendiste, junto. Las que falles volverán al final hasta que las domines. Respira. Ya sabes hacer esto. Adelante."}$j$),
  (2, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es la diferencia entre Git y GitHub?","options":["Son lo mismo","Git es el programa de control de versiones en tu equipo; GitHub es un servicio para alojar y compartir ese historial — Git funciona sin GitHub","GitHub crea commits, Git los sube","Git es la versión vieja"],"correctIndex":1,"feedback":{"correct":"Correcto. La herramienta local (Git) y un lugar para publicarla (GitHub).","incorrect":"Git lleva el historial en tu máquina; GitHub lo aloja. Se puede versionar sin GitHub."}}$j$),
  (3, 'quiz', $j${"variant":"multiple_choice","prompt":"Las tres áreas de Git y el comando que cruza cada frontera:","options":["Nube → local → respaldo","Directorio de trabajo → (git add) → área de preparación → (git commit) → repositorio","Borrador → revisión → publicado","Se cruzan con git save"],"correctIndex":1,"feedback":{"correct":"Correcto. add al staging, commit al repositorio. Todo local.","incorrect":"Working → (add) → staging → (commit) → repositorio. Dos comandos, dos fronteras."}}$j$),
  (4, 'quiz', $j${"variant":"multiple_choice","prompt":"La precisión que evita el error de principiante: git add…","options":["Sube a GitHub","Prepara los cambios en el área de preparación, en tu máquina — NO sube nada a ningún servidor","Crea el commit","Borra el archivo"],"correctIndex":1,"feedback":{"correct":"Correcto. add prepara localmente; publicar (push) es otro acto.","incorrect":"git add NO sube: prepara en el staging, local. Publicar es push."}}$j$),
  (5, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuál es un buen mensaje de commit?","options":["\"cambios\"","\"Corrige el cálculo del total del carrito\": concreto, en imperativo, dice qué cambio incorpora","\"final v2\"","\".\""],"correctIndex":1,"feedback":{"correct":"Correcto. Imperativo y específico. Los vagos vuelven ilegible el log.","incorrect":"El buen mensaje describe el cambio en imperativo. 'cambios' no informa nada."}}$j$),
  (6, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es un commit ATÓMICO y por qué importa?","options":["Uno muy pequeño en bytes","Uno que hace UNA sola cosa completa: el historial se revisa, revierte, busca y entiende pieza por pieza","Uno sin mensaje","Uno que no se deshace"],"correctIndex":1,"feedback":{"correct":"Correcto. Una idea por commit: revertir uno no arrastra los demás.","incorrect":"Atómico = una idea completa por commit. Permite revisar y revertir por separado."}}$j$),
  (7, 'quiz', $j${"variant":"multiple_choice","prompt":"Agregaste .env al .gitignore, pero ya lo habías commiteado antes. ¿Qué pasa?","options":["Desaparece solo","Git lo SIGUE rastreando: .gitignore solo afecta lo que aún no conoce — sacarlo requiere git rm --cached + commit. Ignorar ≠ des-rastrear","Se borra del disco","Da error"],"correctIndex":1,"feedback":{"correct":"Correcto. .gitignore no toca lo ya rastreado. Ignorar previene el futuro, no borra el pasado.","incorrect":"Lo ya commiteado se sigue rastreando pese al .gitignore. Para des-rastrearlo: git rm --cached."}}$j$),
  (8, 'quiz', $j${"variant":"multiple_choice","prompt":"Una contraseña real quedó commiteada y se publicó. ¿La acción OBLIGATORIA?","options":["Agregarla al .gitignore","REVOCARLA (cambiarla / invalidar el token): un secreto expuesto pudo copiarse — borrar el commit NO garantiza que deje de existir","Borrar el archivo","Nada si el repo es privado"],"correctIndex":1,"feedback":{"correct":"Correcto. Rotar la credencial es obligatorio; limpiar el historial no garantiza nada.","incorrect":"La única respuesta segura es revocar el secreto. Borrar el commit no elimina las copias."}}$j$),
  (9, 'quiz', $j${"variant":"multiple_choice","prompt":"git commit --amend sobre un commit YA compartido es peligroso porque…","options":["Consume memoria","Genera un commit con hash NUEVO (reescribe la historia): si otros ya tienen el original, tu versión choca con la suya — no se reescribe historia pública","Borra el mensaje","No es peligroso"],"correctIndex":1,"feedback":{"correct":"Correcto. amend reescribe: seguro en local, desastre sobre lo publicado.","incorrect":"El commit enmendado tiene hash nuevo (historia reescrita). Sobre lo compartido, divide los historiales."}}$j$),
  (10, 'quiz', $j${"variant":"multiple_choice","prompt":"Versionado semántico MAYOR.MENOR.PARCHE: agregas una funcionalidad nueva compatible. ¿Qué número sube?","options":["El MAYOR","El MENOR (v1.4.3 → v1.5.0, parche a 0): función nueva compatible","El PARCHE","Ninguno"],"correctIndex":1,"feedback":{"correct":"Correcto. Función nueva compatible = subir menor. Arreglo = parche; ruptura = mayor.","incorrect":"Funcionalidad nueva compatible sube el MENOR. El parche es para arreglos; el mayor rompe compatibilidad."}}$j$),
  (11, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es realmente una rama en Git?","options":["Una copia del proyecto","Un PUNTERO ligero con nombre que apunta a un commit — crearla es instantánea","Una carpeta","Un servidor"],"correctIndex":1,"feedback":{"correct":"Correcto. Rama = puntero a un commit. Por eso es barata y rápida.","incorrect":"Una rama es un puntero, no una copia. Esa ligereza es lo que hace a Git rápido."}}$j$),
  (12, 'quiz', $j${"variant":"multiple_choice","prompt":"Para crear la rama fix/total y cambiarte a ella de una vez:","options":["git branch fix/total","git switch -c fix/total — crea y cambia en un paso","git merge fix/total","git checkout main"],"correctIndex":1,"feedback":{"correct":"Correcto. switch -c crea y mueve. branch solo crea sin cambiarte.","incorrect":"git switch -c hace ambas cosas. branch solo crea la rama."}}$j$),
  (13, 'quiz', $j${"variant":"multiple_choice","prompt":"main no recibió commits desde que creaste tu rama. Al fusionar, Git hace…","options":["Un commit de fusión con dos padres","Un FAST-FORWARD: adelanta el puntero de main hasta tu rama, sin commit nuevo — historial recto","Un conflicto","Un rebase"],"correctIndex":1,"feedback":{"correct":"Correcto. main no se movió → fast-forward. El commit de fusión aparece si ambas avanzaron.","incorrect":"Si main no avanzó, integrar solo adelanta su puntero: fast-forward."}}$j$),
  (14, 'quiz', $j${"variant":"multiple_choice","prompt":"La precisión clave sobre los conflictos: un conflicto de fusión es…","options":["Un error que rompe el repo","Git avisando que dos ramas cambiaron lo MISMO de forma distinta y necesita una DECISIÓN HUMANA — no es un fallo","Un bug de Git","Pérdida de datos"],"correctIndex":1,"feedback":{"correct":"Correcto. El conflicto es una decisión pendiente, no una avería.","incorrect":"No es un error: es Git pidiendo que decidas dónde hay una contradicción real."}}$j$),
  (15, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Cuándo está RESUELTO un conflicto en un archivo?","options":["Cuando Git lo cierra solo","Cuando dejaste el archivo como debe quedar y BORRASTE todos los marcadores (<<<<<<<, =======, >>>>>>>); luego git add + git commit","Cuando eliges la versión de arriba","Cuando reinicias"],"correctIndex":1,"feedback":{"correct":"Correcto. Archivo correcto + cero marcadores + add + commit.","incorrect":"Resuelto = archivo correcto sin ningún marcador. Un marcador olvidado = sigue sin resolver."}}$j$),
  (16, 'quiz', $j${"variant":"multiple_choice","prompt":"Regla de oro compartida por rebase, amend, reset y push --force:","options":["Usarlos siempre","NO reescribir historia PÚBLICA: crean/mueven commits, y hacerlo sobre lo que otros tienen divide los historiales — solo en trabajo local","Solo en main","Sin consecuencias"],"correctIndex":1,"feedback":{"correct":"Correcto. Reescribir solo sobre lo tuyo y local; jamás sobre lo compartido.","incorrect":"No reescribir historia pública: sobre lo compartido rompe los historiales del equipo."}}$j$),
  (17, 'quiz', $j${"variant":"multiple_choice","prompt":"Estás a media funcionalidad (cambios sin confirmar) y entra un fuego urgente en otra rama. ¿Qué haces sin ensuciar el historial?","options":["Commit 'wip'","git stash (guarda y limpia el directorio) → switch al hotfix → arreglar → volver y git stash pop","Borrar los cambios","Copiar la carpeta"],"correctIndex":1,"feedback":{"correct":"Correcto. stash aparta lo temporal sin commit feo; pop lo devuelve.","incorrect":"git stash guarda el trabajo a medias y limpia el directorio; pop lo recupera. Sin commits incompletos."}}$j$),
  (18, 'quiz', $j${"variant":"multiple_choice","prompt":"¿Qué es 'origin'?","options":["El primer commit","El apodo por convención del repositorio remoto principal","La rama principal","El autor original"],"correctIndex":1,"feedback":{"correct":"Correcto. origin = nombre corto del remoto principal.","incorrect":"origin es el alias del remoto principal, no una rama ni un commit."}}$j$),
  (19, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión clave: git pull es en realidad…","options":["Un comando primitivo","git fetch + git merge: una operación compuesta — por eso un pull puede provocar un conflicto","Lo mismo que push","Solo la primera descarga"],"correctIndex":1,"feedback":{"correct":"Correcto. pull = fetch + merge. El merge interno explica las 'sorpresas'.","incorrect":"pull no es primitivo: descarga (fetch) e integra (merge)."}}$j$),
  (20, 'quiz', $j${"variant":"multiple_choice","prompt":"Tu push es RECHAZADO porque el remoto tiene commits que te faltan. ¿Qué haces?","options":["git push --force","Haces pull para integrar esos commits y vuelves a pushear — nunca forzar en una rama compartida","Borras la rama remota","Reintentas igual"],"correctIndex":1,"feedback":{"correct":"Correcto. Rechazo = te falta trabajo ajeno: pull + re-push. Forzar borra el historial de otros.","incorrect":"Se resuelve con pull + re-push, no forzando. --force destruye los commits ajenos."}}$j$),
  (21, 'quiz', $j${"variant":"multiple_choice","prompt":"'Pull Request' y 'Merge Request' son…","options":["Procesos distintos","El MISMO proceso con distinto nombre (GitHub / GitLab): proponer integrar una rama para que la revisen","Comandos de Git","Tipos de conflicto"],"correctIndex":1,"feedback":{"correct":"Correcto. Mismo concepto, dos nombres. Función de la plataforma, no comando de Git.","incorrect":"PR (GitHub) y MR (GitLab) son lo mismo: la propuesta revisada de integrar una rama."}}$j$),
  (22, 'quiz', $j${"variant":"multiple_choice","prompt":"La regla cultural central de una buena revisión de código:","options":["Encontrar tantos fallos como sea posible","Revisar el CÓDIGO, no a la persona — 'esta función podría fallar si...' en vez de 'siempre lo haces mal'","Aprobar siempre","Bloquear todo"],"correctIndex":1,"feedback":{"correct":"Correcto. El comentario habla del cambio, con respeto. Atacar a la persona envenena al equipo.","incorrect":"Se revisa el código, no a quien lo escribió. Los comentarios describen el cambio."}}$j$),
  (23, 'quiz', $j${"variant":"multiple_choice","prompt":"Editaste un archivo, NO lo commiteaste, y quieres descartar el cambio. ¿Qué usas?","options":["git revert archivo","git restore archivo — descarta el cambio no confirmado (irreversible: no estaba en ningún commit)","git reset --soft","git bisect"],"correctIndex":1,"feedback":{"correct":"Correcto. restore descarta lo no confirmado. revert es para commits; bisect diagnostica.","incorrect":"Lo no confirmado se descarta con restore. revert deshace commits ya hechos."}}$j$),
  (24, 'quiz', $j${"variant":"multiple_choice","prompt":"Un commit YA en main (compartido) rompió producción. ¿Cómo lo deshaces de forma segura?","options":["git reset --hard","git revert HASH: un commit nuevo que lo anula sin reescribir la historia — seguro en lo compartido","git restore","git commit --amend"],"correctIndex":1,"feedback":{"correct":"Correcto. Público → revert: deshace con un commit inverso, sin tocar la historia ajena.","incorrect":"Sobre lo compartido, revert. reset o amend reescribirían la historia del equipo."}}$j$),
  (25, 'quiz', $j${"variant":"multiple_choice","prompt":"Los tres modos de git reset (--soft/--mixed/--hard) se diferencian en…","options":["La velocidad","Qué pasa con los cambios de los commits deshechos: --soft los deja preparados, --mixed sin preparar, --hard los BORRA (los tres mueven el puntero atrás)","El mensaje","Nada"],"correctIndex":1,"feedback":{"correct":"Correcto. Los tres mueven el puntero; difieren en el destino de los cambios. Solo --hard pierde trabajo.","incorrect":"Todos deshacen commits (mueven el puntero); la diferencia es preparados/sin preparar/borrados."}}$j$),
  (26, 'quiz', $j${"variant":"multiple_choice","prompt":"Hiciste git reset --hard y perdiste un commit importante. ¿Cómo lo recuperas?","options":["Es imposible","git reflog para hallar su hash (sigue registrado aunque no salga en git log) y crear una rama de rescate sobre él","git pull","git restore"],"correctIndex":1,"feedback":{"correct":"Correcto. El reflog guarda el hash del commit huérfano: una rama de rescate lo trae de vuelta.","incorrect":"El reflog conserva el hash tras el reset: lo buscas ahí y creas una rama. No está perdido."}}$j$),
  (27, 'quiz', $j${"variant":"multiple_choice","prompt":"Algo se rompió en algún punto de los últimos 150 commits y no sabes cuál. ¿Qué herramienta lo encuentra?","options":["git reflog","git bisect: por BÚSQUEDA BINARIA reduce 150 commits a ~8 preguntas hasta señalar al culpable","git revert","git status"],"correctIndex":1,"feedback":{"correct":"Correcto. bisect localiza al culpable por búsqueda binaria. Diagnóstico, no arreglo.","incorrect":"git bisect encuentra el commit culpable partiendo el rango a la mitad. reflog recupera; bisect diagnostica."}}$j$),
  (28, 'quiz', $j${"variant":"multiple_choice","prompt":"Precisión de vocabulario profesional: rama, tag, release y despliegue…","options":["Son lo mismo","Son cuatro cosas distintas: rama (línea móvil), tag (marca fija), release (versión empaquetada) y despliegue (ponerla a correr)","Rama = tag; release = despliegue","El release es una rama"],"correctIndex":1,"feedback":{"correct":"Correcto. Cuatro conceptos distintos que se confunden.","incorrect":"Rama ≠ tag ≠ release ≠ despliegue: cada uno significa algo distinto."}}$j$),
  (29, 'quiz', $j${"variant":"multiple_choice","prompt":"Sobre los flujos de ramas (trunk-based, GitHub Flow, GitFlow):","options":["GitFlow es el mejor","Ninguno es universalmente superior: se elige por contexto (tamaño, frecuencia de despliegue, versiones en paralelo)","Trunk-based es el único válido","Son intercambiables sin consecuencias"],"correctIndex":1,"feedback":{"correct":"Correcto. Cada flujo para su contexto; defender uno como 'el correcto' es el error.","incorrect":"Ninguno gana siempre: la elección depende del contexto del equipo y el producto."}}$j$),
  (30, 'quiz', $j${"variant":"multiple_choice","prompt":"Un hotfix corrige un error en la versión 2.1.0 que está en producción. ¿De dónde parte su rama y qué versión se etiqueta?","options":["De desarrollo; v3.0.0","Del TAG de producción (v2.1.0), para llevar solo la corrección; y se etiqueta v2.1.1 (sube el PARCHE)","De main; v2.2.0","De una rama vacía; sin tag"],"correctIndex":1,"feedback":{"correct":"Correcto. Hotfix desde el tag de producción, sube el parche (2.1.0 → 2.1.1). Cirugía acotada.","incorrect":"El hotfix parte del tag de producción y sube el parche (v2.1.1): arreglo compatible, sin arrastrar trabajo a medias."}}$j$),
  (31, 'quiz', $j${"variant":"multiple_choice","prompt":"Te unes a un proyecto ajeno ya clonado. ¿Qué haces ANTES de escribir código?","options":["Cambiar cosas de inmediato","LEER el README (cómo corre) y CONTRIBUTING (las convenciones del equipo), para adoptar SU cultura en vez de imponer la tuya","Borrar main","Reescribir el historial"],"correctIndex":1,"feedback":{"correct":"Correcto. README y CONTRIBUTING primero: el recién llegado adopta la cultura del proyecto.","incorrect":"Antes de tocar: leer README y CONTRIBUTING. Cada equipo tiene su cultura escrita ahí."}}$j$),
  (32, 'quiz', $j${"variant":"multiple_choice","prompt":"Pregunta final del curso: la regla que apareció con amend, rebase, reset, push --force y en la elección revert-vs-reset. ¿Cuál es, y por qué la entiendes ahora?","options":["'Commitea seguido', para no perder trabajo","'No reescribas la historia que ya compartiste': reescribir (amend/rebase/reset) o sobreescribir (push --force) commits que otros ya tienen divide los historiales del equipo — por eso lo público se deshace con revert (que solo agrega un commit) y lo local se reorganiza libremente","'Usa siempre ramas', para aislar","'Haz pull antes de push', para evitar rechazos"],"correctIndex":1,"feedback":{"correct":"Impecable. La regla de oro que teje todo el curso: local se reescribe con libertad, público solo se deshace hacia adelante (revert). Con eso —y con todo lo que sabes— ya puedes contribuir a cualquier proyecto del mundo. Curso terminado.","incorrect":"La regla de oro: no reescribir historia pública. Reescribir/sobreescribir lo que otros tienen rompe sus historiales; por eso lo público se deshace con revert y lo local se reorganiza libre. Es el hilo que une amend, rebase, reset y push --force."}}$j$)
) as v(ord, kind, payload)
where c.slug = 'git-desde-cero' and l.slug = 'm07-x01-final';
